const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Behaviors.Timer,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Exps.BBoxMidX,
		C3.Plugins.Sprite.Exps.BBoxMidY,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.dt
	];
};
self.C3_JsPropNameTable = [
	{Dragging: 0},
	{HorizontalMovement: 0},
	{VerticalMovement: 0},
	{InitialX: 0},
	{InitialY: 0},
	{OffsetX: 0},
	{OffsetY: 0},
	{TargetX: 0},
	{TargetY: 0},
	{Block: 0},
	{Mouse: 0},
	{Touch: 0},
	{Enabled: 0},
	{DefaultWidth: 0},
	{DefaultHeight: 0},
	{OtherSolid: 0},
	{SelfSolid: 0},
	{Timer: 0},
	{GameManager: 0},
	{SmokeParticles: 0},
	{Background: 0},
	{Leaves: 0},
	{Sine: 0},
	{Leaf: 0},
	{WeeGooSDK: 0},
	{AllowPlayerInput: 0},
	{PreviousPosition: 0},
	{BoardMargin: 0},
	{BlockUID: 0},
	{Direction: 0},
	{CurrentValue: 0},
	{TargetValue: 0},
	{Speed: 0}
];

self.InstanceType = {
	Block: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	OtherSolid: class extends self.ISpriteInstance {},
	SelfSolid: class extends self.ISpriteInstance {},
	GameManager: class extends self.ISpriteInstance {},
	SmokeParticles: class extends self.IParticlesInstance {},
	Background: class extends self.ISpriteInstance {},
	Leaves: class extends self.ISpriteInstance {},
	Leaf: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {}
}