const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Behaviors.destroy,
		C3.Plugins.LocalStorage,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsPost,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsInvite,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{Bullet: 0},
	{Ball: 0},
	{Touch: 0},
	{Sprite: 0},
	{rright: 0},
	{lleft: 0},
	{Solid: 0},
	{TiledBackground: 0},
	{lvl: 0},
	{Sprite2: 0},
	{Anchor: 0},
	{Sprite3: 0},
	{Text: 0},
	{Sine: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{DestroyOutsideLayout: 0},
	{Sprite6: 0},
	{LVL: 0},
	{Sprite7: 0},
	{Text2: 0},
	{LocalStorage: 0},
	{GameScore: 0},
	{next: 0},
	{friend: 0},
	{friend2: 0},
	{level: 0}
];

self.InstanceType = {
	Ball: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	rright: class extends self.ISpriteInstance {},
	lleft: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	GameScore: class extends self.C3.Plugins.Eponesh_GameScore.Instance {},
	next: class extends self.ITextInstance {},
	friend: class extends self.ITextInstance {},
	friend2: class extends self.ITextInstance {}
}