const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Behaviors.DragnDrop,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Browser: 0},
	{Touch: 0},
	{Mouse: 0},
	{bg_pause: 0},
	{Tween: 0},
	{btn_refresh: 0},
	{btn_change: 0},
	{btn_change2: 0},
	{btn_change3: 0},
	{btn_change_h: 0},
	{btn_change_h2: 0},
	{btn_change_h3: 0},
	{btn_more: 0},
	{btn_more_start: 0},
	{btn_start: 0},
	{btn_main: 0},
	{btn_no: 0},
	{btn_yes: 0},
	{blank1: 0},
	{blank2: 0},
	{blank3: 0},
	{blank4: 0},
	{blank5: 0},
	{blank6: 0},
	{blank7: 0},
	{blank8: 0},
	{blank9: 0},
	{FunBot: 0},
	{Vinera: 0},
	{Orange: 0},
	{Purple: 0},
	{Red: 0},
	{Silver: 0},
	{Gray: 0},
	{Brown: 0},
	{Gold: 0},
	{Lime: 0},
	{Sky: 0},
	{Sun: 0},
	{Tann: 0},
	{Tree: 0},
	{Yellow: 0},
	{Computer: 0},
	{White: 0},
	{Blue: 0},
	{Pink: 0},
	{Black: 0},
	{bg_icons: 0},
	{bg_top: 0},
	{frame: 0},
	{BG: 0},
	{Sine: 0},
	{clouds: 0},
	{Particles: 0},
	{text_dont: 0},
	{Txt_Warning: 0},
	{bg_start: 0},
	{DragDrop: 0},
	{funbot_icon: 0},
	{funbot_icon2: 0},
	{orange_icon: 0},
	{orange_icon2: 0},
	{red_icon: 0},
	{red_icon2: 0},
	{silver_icon: 0},
	{silver_icon2: 0},
	{vinera_icon: 0},
	{vinera_icon2: 0},
	{gray_icon2: 0},
	{gray_icon: 0},
	{brown_icon2: 0},
	{brown_icon: 0},
	{gold_icon2: 0},
	{gold_icon: 0},
	{lime_icon: 0},
	{lime_icon2: 0},
	{sky_icon: 0},
	{sky_icon2: 0},
	{sun_icon: 0},
	{sun_icon2: 0},
	{purple_icon: 0},
	{purple_icon2: 0},
	{tree_icon: 0},
	{tree_icon2: 0},
	{yellow_icon: 0},
	{yellow_icon2: 0},
	{tann_icon: 0},
	{tann_icon2: 0},
	{white_icon: 0},
	{white_icon2: 0},
	{pink_icon: 0},
	{pink_icon2: 0},
	{blue_icon: 0},
	{blue_icon2: 0},
	{computer_icon: 0},
	{blue_down: 0},
	{brown_down: 0},
	{computer_down: 0},
	{funbot_down: 0},
	{gold_down: 0},
	{gray_down: 0},
	{lime_down: 0},
	{orange_down: 0},
	{pink_down: 0},
	{purple_down: 0},
	{red_down: 0},
	{silver_down: 0},
	{sky_down: 0},
	{sun_down: 0},
	{tann_down: 0},
	{tree_down: 0},
	{vinera_down: 0},
	{white_down: 0},
	{yellow_down: 0},
	{black_icon: 0},
	{black_down_h: 0},
	{black_icon_h: 0},
	{normal_icon: 0},
	{normal_down: 0},
	{WeeGooSDK: 0},
	{Sprunki_Blank: 0},
	{Icons: 0},
	{Icons_Down: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	bg_pause: class extends self.ISpriteInstance {},
	btn_refresh: class extends self.ISpriteInstance {},
	btn_change: class extends self.ISpriteInstance {},
	btn_change2: class extends self.ISpriteInstance {},
	btn_change3: class extends self.ISpriteInstance {},
	btn_change_h: class extends self.ISpriteInstance {},
	btn_change_h2: class extends self.ISpriteInstance {},
	btn_change_h3: class extends self.ISpriteInstance {},
	btn_more: class extends self.ISpriteInstance {},
	btn_more_start: class extends self.ISpriteInstance {},
	btn_start: class extends self.ISpriteInstance {},
	btn_main: class extends self.ISpriteInstance {},
	btn_no: class extends self.ISpriteInstance {},
	btn_yes: class extends self.ISpriteInstance {},
	blank1: class extends self.ISpriteInstance {},
	blank2: class extends self.ISpriteInstance {},
	blank3: class extends self.ISpriteInstance {},
	blank4: class extends self.ISpriteInstance {},
	blank5: class extends self.ISpriteInstance {},
	blank6: class extends self.ISpriteInstance {},
	blank7: class extends self.ISpriteInstance {},
	blank8: class extends self.ISpriteInstance {},
	blank9: class extends self.ISpriteInstance {},
	FunBot: class extends self.ISpriteInstance {},
	Vinera: class extends self.ISpriteInstance {},
	Orange: class extends self.ISpriteInstance {},
	Purple: class extends self.ISpriteInstance {},
	Red: class extends self.ISpriteInstance {},
	Silver: class extends self.ISpriteInstance {},
	Gray: class extends self.ISpriteInstance {},
	Brown: class extends self.ISpriteInstance {},
	Gold: class extends self.ISpriteInstance {},
	Lime: class extends self.ISpriteInstance {},
	Sky: class extends self.ISpriteInstance {},
	Sun: class extends self.ISpriteInstance {},
	Tann: class extends self.ISpriteInstance {},
	Tree: class extends self.ISpriteInstance {},
	Yellow: class extends self.ISpriteInstance {},
	Computer: class extends self.ISpriteInstance {},
	White: class extends self.ISpriteInstance {},
	Blue: class extends self.ISpriteInstance {},
	Pink: class extends self.ISpriteInstance {},
	Black: class extends self.ISpriteInstance {},
	bg_icons: class extends self.ISpriteInstance {},
	bg_top: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	clouds: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	text_dont: class extends self.ISpriteInstance {},
	Txt_Warning: class extends self.ISpriteInstance {},
	bg_start: class extends self.ISpriteInstance {},
	funbot_icon: class extends self.ISpriteInstance {},
	funbot_icon2: class extends self.ISpriteInstance {},
	orange_icon: class extends self.ISpriteInstance {},
	orange_icon2: class extends self.ISpriteInstance {},
	red_icon: class extends self.ISpriteInstance {},
	red_icon2: class extends self.ISpriteInstance {},
	silver_icon: class extends self.ISpriteInstance {},
	silver_icon2: class extends self.ISpriteInstance {},
	vinera_icon: class extends self.ISpriteInstance {},
	vinera_icon2: class extends self.ISpriteInstance {},
	gray_icon2: class extends self.ISpriteInstance {},
	gray_icon: class extends self.ISpriteInstance {},
	brown_icon2: class extends self.ISpriteInstance {},
	brown_icon: class extends self.ISpriteInstance {},
	gold_icon2: class extends self.ISpriteInstance {},
	gold_icon: class extends self.ISpriteInstance {},
	lime_icon: class extends self.ISpriteInstance {},
	lime_icon2: class extends self.ISpriteInstance {},
	sky_icon: class extends self.ISpriteInstance {},
	sky_icon2: class extends self.ISpriteInstance {},
	sun_icon: class extends self.ISpriteInstance {},
	sun_icon2: class extends self.ISpriteInstance {},
	purple_icon: class extends self.ISpriteInstance {},
	purple_icon2: class extends self.ISpriteInstance {},
	tree_icon: class extends self.ISpriteInstance {},
	tree_icon2: class extends self.ISpriteInstance {},
	yellow_icon: class extends self.ISpriteInstance {},
	yellow_icon2: class extends self.ISpriteInstance {},
	tann_icon: class extends self.ISpriteInstance {},
	tann_icon2: class extends self.ISpriteInstance {},
	white_icon: class extends self.ISpriteInstance {},
	white_icon2: class extends self.ISpriteInstance {},
	pink_icon: class extends self.ISpriteInstance {},
	pink_icon2: class extends self.ISpriteInstance {},
	blue_icon: class extends self.ISpriteInstance {},
	blue_icon2: class extends self.ISpriteInstance {},
	computer_icon: class extends self.ISpriteInstance {},
	blue_down: class extends self.ISpriteInstance {},
	brown_down: class extends self.ISpriteInstance {},
	computer_down: class extends self.ISpriteInstance {},
	funbot_down: class extends self.ISpriteInstance {},
	gold_down: class extends self.ISpriteInstance {},
	gray_down: class extends self.ISpriteInstance {},
	lime_down: class extends self.ISpriteInstance {},
	orange_down: class extends self.ISpriteInstance {},
	pink_down: class extends self.ISpriteInstance {},
	purple_down: class extends self.ISpriteInstance {},
	red_down: class extends self.ISpriteInstance {},
	silver_down: class extends self.ISpriteInstance {},
	sky_down: class extends self.ISpriteInstance {},
	sun_down: class extends self.ISpriteInstance {},
	tann_down: class extends self.ISpriteInstance {},
	tree_down: class extends self.ISpriteInstance {},
	vinera_down: class extends self.ISpriteInstance {},
	white_down: class extends self.ISpriteInstance {},
	yellow_down: class extends self.ISpriteInstance {},
	black_icon: class extends self.ISpriteInstance {},
	black_down_h: class extends self.ISpriteInstance {},
	black_icon_h: class extends self.ISpriteInstance {},
	normal_icon: class extends self.ISpriteInstance {},
	normal_down: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	Sprunki_Blank: class extends self.ISpriteInstance {},
	Icons: class extends self.ISpriteInstance {},
	Icons_Down: class extends self.ISpriteInstance {}
}