const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Shape3D,
		C3.Plugins.Sprite,
		C3.Plugins.Camera3D,
		C3.Plugins.Keyboard,
		C3.Behaviors.custom,
		C3.Behaviors.Sin,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.LOS,
		C3.Plugins.gamepad,
		C3.Behaviors.Tween,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Behaviors.Rotate,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Pin,
		C3.Behaviors.solid,
		C3.Plugins.Tilemap,
		C3.Plugins.Mouse,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Camera3D.Acts.LookParallelToLayout,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Camera3D.Exps.CameraXRotation,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Acts.MoveToLayer,
		C3.Plugins.Shape3D.Acts.MoveToLayer,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Camera3D.Acts.RotateCamera,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Camera3D.Acts.SetPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.custom.Acts.PushOutSolid,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.System.Exps.random,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Behaviors.custom.Cnds.IsMoving,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Shape3D.Acts.SetZHeight,
		C3.Plugins.Shape3D.Exps.ZHeight,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Shape3D.Cnds.OnCreated,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Shape3D.Acts.SetInstanceVar,
		C3.Plugins.Shape3D.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Shape3D.Acts.SetTowardPosition,
		C3.Plugins.Shape3D.Acts.SetFaceObject,
		C3.Plugins.Shape3D.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Pathfinding.Acts.AddObstacle,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Pathfinding.Acts.SetAcc,
		C3.Behaviors.Pathfinding.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Pathfinding.Cnds.OnFailedToFindPath,
		C3.Plugins.Shape3D.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Pathfinding.Acts.Stop,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Shape3D.Cnds.CompareZElevation,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Plugins.Shape3D.Acts.SetSize,
		C3.Plugins.Shape3D.Acts.MoveAtAngle,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.Shape3D.Cnds.IsOnScreen,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Shape3D.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Shape3D.Acts.SetBoolInstanceVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Sin.Acts.SetMovement,
		C3.Plugins.Shape3D.Acts.SetEffectParam,
		C3.Behaviors.Sin.Exps.Value,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.Shape3D.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.gamepad.Cnds.HasGamepads,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Spritefont2.Exps.Count,
		C3.Plugins.Spritefont2.Cnds.PickDistance,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Shape3D.Exps.Width,
		C3.Plugins.Shape3D.Exps.Height,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.Pin.Acts.PinByDistance,
		C3.Behaviors.Pin.Acts.SetPinDistance,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.gamepad.Cnds.OnAnyButtonDown,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.WGSDK.Cnds.RewardReady,
		C3.Plugins.WGSDK.Cnds.RewardGranted
	];
};
self.C3_JsPropNameTable = [
	{fps_bg: 0},
	{fps_3d_walls: 0},
	{fps_top: 0},
	{fps_wall: 0},
	{fps_camera: 0},
	{"3DCamera": 0},
	{Keyboard: 0},
	{PlayerSpeed: 0},
	{Powee: 0},
	{isPerforante: 0},
	{Distance: 0},
	{WeaponNum: 0},
	{isKnife: 0},
	{ammo_gun: 0},
	{ammo_fucile: 0},
	{ammo_mitra: 0},
	{ammo_sniper: 0},
	{ammo_scar: 0},
	{isGame: 0},
	{WepSwap: 0},
	{hpMax: 0},
	{hpActual: 0},
	{isMap: 0},
	{Custom: 0},
	{Sine: 0},
	{player: 0},
	{fps_roof: 0},
	{AngleOfMotion: 0},
	{fps_CharacterBillboard: 0},
	{isAnimated: 0},
	{fps_CharacterTextures: 0},
	{state: 0},
	{isHit: 0},
	{HP: 0},
	{Pathfinding: 0},
	{LineOfSight: 0},
	{fps_EnemyController: 0},
	{fps_Zombie_Dead: 0},
	{Gamepad: 0},
	{fps_shadow: 0},
	{fps_coll: 0},
	{State: 0},
	{Tween: 0},
	{fps_player_UI: 0},
	{fps_Bullseye: 0},
	{BulletPower: 0},
	{BulletDistance: 0},
	{Bullet: 0},
	{fps_player_bullet: 0},
	{Closed: 0},
	{PosX: 0},
	{PosY: 0},
	{SelfAngel: 0},
	{ClosedDoorY: 0},
	{fps_Door: 0},
	{door: 0},
	{fps_3Dblood: 0},
	{fps_blood: 0},
	{isCreated: 0},
	{fps_CharacterBody: 0},
	{Fade: 0},
	{fps_muzzle_flash: 0},
	{fps_muzzle_flash2: 0},
	{fps_flash: 0},
	{fps_3DScintilla: 0},
	{fps_smoke: 0},
	{fps_blood_spot: 0},
	{fps_sound: 0},
	{fps_fence: 0},
	{fps_floor: 0},
	{Type: 0},
	{Ammo: 0},
	{Rotate: 0},
	{"3D_Box": 0},
	{"3D_Letto": 0},
	{"3D_Table_s": 0},
	{"3D_Table": 0},
	{"3D_Scrivania": 0},
	{"3D_Scrivania2": 0},
	{"3D_Armadio_D": 0},
	{Audio: 0},
	{egg: 0},
	{SelfUID: 0},
	{Sine2: 0},
	{"3D_egg": 0},
	{WepNum: 0},
	{egg_spawner: 0},
	{type: 0},
	{fps_SpriteFont: 0},
	{fps_wep_UI: 0},
	{fps_knife_Ui: 0},
	{fps_bg2: 0},
	{fps_bg3: 0},
	{fps_SpriteFont_Shadow: 0},
	{fps_screenblood: 0},
	{fps_fader: 0},
	{fps_minimap: 0},
	{fps_mapWalls: 0},
	{fps_mapDoor: 0},
	{fps_mapPlayer: 0},
	{fps_bloodHit: 0},
	{fps_bg_black: 0},
	{UI_fps_Pause: 0},
	{UI_fps_Resume: 0},
	{UI_fps_Quit: 0},
	{UI_fps_Yes: 0},
	{UI_fps_No: 0},
	{UI_fps_Controls: 0},
	{UI_fps_Play: 0},
	{UI_fps_Title: 0},
	{fps_gameOver_screen: 0},
	{UI_fps_GameOver: 0},
	{UI_fps_Retry: 0},
	{UI_Selected: 0},
	{isSelected: 0},
	{isYes: 0},
	{isEntered: 0},
	{KillsCount: 0},
	{fps_GameController: 0},
	{SpawnerID: 0},
	{fps_Spawner: 0},
	{fps_bg_Controls: 0},
	{fps_GamepadLayout: 0},
	{"3D_DinalDoor": 0},
	{LocalStorage: 0},
	{fps_WinScreen: 0},
	{fps_collisionZombie: 0},
	{bg_black: 0},
	{cover_PI: 0},
	{cover_Dev: 0},
	{cover_Ti: 0},
	{cover_Ball_Red: 0},
	{cover_Ball_blu: 0},
	{crazy_fader: 0},
	{audioOff: 0},
	{btn_rewarded: 0},
	{ammox: 0},
	{Touch: 0},
	{PlatformInfo: 0},
	{touch_map: 0},
	{touch_Shoot: 0},
	{touch_Up: 0},
	{touch_Down: 0},
	{touch_Right: 0},
	{touch_Left: 0},
	{touch_RotateR: 0},
	{touch_RotateL: 0},
	{touch_Pause: 0},
	{Aimpad: 0},
	{DragDrop: 0},
	{Pin: 0},
	{Aimstick: 0},
	{Joypad: 0},
	{Joystick: 0},
	{Rotater: 0},
	{TexturesCom_Skies0201_1_M: 0},
	{"3DShape": 0},
	{"3DRoof": 0},
	{fps_fence2: 0},
	{Solid: 0},
	{"3D_tavolo": 0},
	{"3D_shot": 0},
	{Tilemap: 0},
	{Sprite: 0},
	{Cover2: 0},
	{tree: 0},
	{"3d_tree": 0},
	{Mouse: 0},
	{WeeGooSDK: 0},
	{fps_entities: 0},
	{fps_solid: 0},
	{fps_UI: 0},
	{fps_maps: 0},
	{CoverScreen: 0},
	{Cover: 0},
	{TouchControls: 0},
	{eggs: 0},
	{best_eggs: 0},
	{fps_Wep: 0},
	{isSound: 0},
	{fps_gameOver: 0},
	{fps_isPause: 0},
	{fps_timer: 0},
	{fps_Kills: 0},
	{fps_BestTime: 0},
	{fps_BestKills: 0}
];

self.InstanceType = {
	fps_bg: class extends self.ITiledBackgroundInstance {},
	fps_3d_walls: class extends self.I3DShapeInstance {},
	fps_top: class extends self.ITiledBackgroundInstance {},
	fps_wall: class extends self.ITiledBackgroundInstance {},
	fps_camera: class extends self.ISpriteInstance {},
	_3DCamera: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	player: class extends self.ISpriteInstance {},
	fps_roof: class extends self.ITiledBackgroundInstance {},
	fps_CharacterBillboard: class extends self.I3DShapeInstance {},
	fps_CharacterTextures: class extends self.ISpriteInstance {},
	fps_EnemyController: class extends self.ISpriteInstance {},
	fps_Zombie_Dead: class extends self.ISpriteInstance {},
	Gamepad: class extends self.IInstance {},
	fps_shadow: class extends self.ISpriteInstance {},
	fps_coll: class extends self.ITiledBackgroundInstance {},
	fps_player_UI: class extends self.ISpriteInstance {},
	fps_Bullseye: class extends self.ISpriteInstance {},
	fps_player_bullet: class extends self.ISpriteInstance {},
	fps_Door: class extends self.I3DShapeInstance {},
	door: class extends self.ISpriteInstance {},
	fps_3Dblood: class extends self.I3DShapeInstance {},
	fps_blood: class extends self.ISpriteInstance {},
	fps_CharacterBody: class extends self.I3DShapeInstance {},
	fps_muzzle_flash: class extends self.ISpriteInstance {},
	fps_muzzle_flash2: class extends self.ISpriteInstance {},
	fps_flash: class extends self.ISpriteInstance {},
	fps_3DScintilla: class extends self.I3DShapeInstance {},
	fps_smoke: class extends self.ISpriteInstance {},
	fps_blood_spot: class extends self.ISpriteInstance {},
	fps_sound: class extends self.ISpriteInstance {},
	fps_fence: class extends self.ITiledBackgroundInstance {},
	fps_floor: class extends self.ITiledBackgroundInstance {},
	_3D_Box: class extends self.I3DShapeInstance {},
	_3D_Letto: class extends self.I3DShapeInstance {},
	_3D_Table_s: class extends self.I3DShapeInstance {},
	_3D_Table: class extends self.I3DShapeInstance {},
	_3D_Scrivania: class extends self.I3DShapeInstance {},
	_3D_Scrivania2: class extends self.I3DShapeInstance {},
	_3D_Armadio_D: class extends self.I3DShapeInstance {},
	Audio: class extends self.IInstance {},
	egg: class extends self.ISpriteInstance {},
	_3D_egg: class extends self.I3DShapeInstance {},
	egg_spawner: class extends self.ISpriteInstance {},
	fps_SpriteFont: class extends self.ISpriteFontInstance {},
	fps_wep_UI: class extends self.ISpriteInstance {},
	fps_knife_Ui: class extends self.ISpriteInstance {},
	fps_bg2: class extends self.ITiledBackgroundInstance {},
	fps_bg3: class extends self.ITiledBackgroundInstance {},
	fps_SpriteFont_Shadow: class extends self.ISpriteFontInstance {},
	fps_screenblood: class extends self.ISpriteInstance {},
	fps_fader: class extends self.ISpriteInstance {},
	fps_minimap: class extends self.ISpriteInstance {},
	fps_mapWalls: class extends self.ISpriteInstance {},
	fps_mapDoor: class extends self.ISpriteInstance {},
	fps_mapPlayer: class extends self.ISpriteInstance {},
	fps_bloodHit: class extends self.ISpriteInstance {},
	fps_bg_black: class extends self.ISpriteInstance {},
	UI_fps_Pause: class extends self.ISpriteInstance {},
	UI_fps_Resume: class extends self.ISpriteInstance {},
	UI_fps_Quit: class extends self.ISpriteInstance {},
	UI_fps_Yes: class extends self.ISpriteInstance {},
	UI_fps_No: class extends self.ISpriteInstance {},
	UI_fps_Controls: class extends self.ISpriteInstance {},
	UI_fps_Play: class extends self.ISpriteInstance {},
	UI_fps_Title: class extends self.ISpriteInstance {},
	fps_gameOver_screen: class extends self.ISpriteInstance {},
	UI_fps_GameOver: class extends self.ISpriteInstance {},
	UI_fps_Retry: class extends self.ISpriteInstance {},
	fps_GameController: class extends self.ISpriteInstance {},
	fps_Spawner: class extends self.ISpriteInstance {},
	fps_bg_Controls: class extends self.ISpriteInstance {},
	fps_GamepadLayout: class extends self.ISpriteInstance {},
	_3D_DinalDoor: class extends self.I3DShapeInstance {},
	LocalStorage: class extends self.IInstance {},
	fps_WinScreen: class extends self.ISpriteInstance {},
	fps_collisionZombie: class extends self.ISpriteInstance {},
	bg_black: class extends self.ITiledBackgroundInstance {},
	cover_PI: class extends self.ISpriteInstance {},
	cover_Dev: class extends self.ISpriteInstance {},
	cover_Ti: class extends self.ISpriteInstance {},
	cover_Ball_Red: class extends self.ISpriteInstance {},
	cover_Ball_blu: class extends self.ISpriteInstance {},
	crazy_fader: class extends self.ITiledBackgroundInstance {},
	audioOff: class extends self.ISpriteInstance {},
	btn_rewarded: class extends self.ISpriteInstance {},
	ammox: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	touch_map: class extends self.ISpriteInstance {},
	touch_Shoot: class extends self.ISpriteInstance {},
	touch_Up: class extends self.ISpriteInstance {},
	touch_Down: class extends self.ISpriteInstance {},
	touch_Right: class extends self.ISpriteInstance {},
	touch_Left: class extends self.ISpriteInstance {},
	touch_RotateR: class extends self.ISpriteInstance {},
	touch_RotateL: class extends self.ISpriteInstance {},
	touch_Pause: class extends self.ISpriteInstance {},
	Aimpad: class extends self.ISpriteInstance {},
	Aimstick: class extends self.ISpriteInstance {},
	Joypad: class extends self.ISpriteInstance {},
	Joystick: class extends self.ISpriteInstance {},
	Rotater: class extends self.ISpriteInstance {},
	TexturesCom_Skies0201_1_M: class extends self.ISpriteInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	_3DRoof: class extends self.I3DShapeInstance {},
	fps_fence2: class extends self.ITiledBackgroundInstance {},
	_3D_tavolo: class extends self.I3DShapeInstance {},
	_3D_shot: class extends self.I3DShapeInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Cover2: class extends self.ISpriteInstance {},
	tree: class extends self.ISpriteInstance {},
	_3d_tree: class extends self.I3DShapeInstance {},
	Mouse: class extends self.IInstance {},
	WeeGooSDK: class extends self.IInstance {},
	fps_entities: class extends self.ISpriteInstance {},
	fps_solid: class extends self.I3DShapeInstance {},
	fps_UI: class extends self.ISpriteInstance {},
	fps_maps: class extends self.ISpriteInstance {},
	CoverScreen: class extends self.ISpriteInstance {},
	Cover: class extends self.ISpriteInstance {},
	TouchControls: class extends self.ISpriteInstance {}
}