const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Keyboard,
		C3.Plugins.gamepad,
		C3.Plugins.Arr,
		C3.Plugins.TiledBg,
		C3.Plugins.DrawingCanvas,
		C3.Behaviors.Tween,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Behaviors.Flash,
		C3.Behaviors.Pin,
		C3.Plugins.NinePatch,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.PlatformInfo,
		C3.Plugins.WGSDK,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Acts.SetLayoutEffectParam,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Text.Acts.Destroy,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.Sprite.Cnds.HasParent,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.DrawingCanvas.Acts.SetSize,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.DrawingCanvas.Acts.SetInstanceVar,
		C3.Plugins.DrawingCanvas.Acts.ClearCanvas,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.DrawingCanvas.Acts.OutlineEllipse,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.Browser.Acts.GoToURL
	];
};
self.C3_JsPropNameTable = [
	{Picked: 0},
	{Block: 0},
	{Reference: 0},
	{Keyboard: 0},
	{Gamepad: 0},
	{Trigger: 0},
	{Player: 0},
	{Destroy: 0},
	{WorldEdge: 0},
	{Sight: 0},
	{Sky: 0},
	{Grid: 0},
	{Laser: 0},
	{RockWall: 0},
	{Cannons: 0},
	{Explosion: 0},
	{PositionX: 0},
	{PositionY: 0},
	{Thickness: 0},
	{Radius: 0},
	{Time: 0},
	{Tween: 0},
	{DrawingCanvas: 0},
	{SwitchBeam: 0},
	{PushBeam: 0},
	{Bullet: 0},
	{Rotate: 0},
	{DestroyedBlock: 0},
	{IDName: 0},
	{Fade: 0},
	{Flash: 0},
	{TextFont: 0},
	{PullBeam: 0},
	{PlayerTrail: 0},
	{Shine: 0},
	{JetFire: 0},
	{Pin: 0},
	{BlockFlash: 0},
	{TextFrame: 0},
	{GameManager: 0},
	{TutorialFrame: 0},
	{Sine: 0},
	{Play: 0},
	{Touch: 0},
	{Tutorial: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{igraj: 0},
	{playgame: 0},
	{moregamesadd: 0},
	{joystick: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{TextFont2: 0},
	{Sprite8: 0},
	{FireworkParticles: 0},
	{Sprite45: 0},
	{winpanel4: 0},
	{Sprite9: 0},
	{home: 0},
	{Sprite10: 0},
	{home2: 0},
	{audioOn: 0},
	{BSound: 0},
	{Audio: 0},
	{Browser: 0},
	{swap: 0},
	{Sprite11: 0},
	{grab: 0},
	{Sprite12: 0},
	{leftarrow: 0},
	{leftarrow2: 0},
	{PlatformInfo: 0},
	{lagged: 0},
	{Sprite13: 0},
	{HOWTO: 0},
	{Sprite14: 0},
	{WeeGooSDK: 0},
	{Solids: 0},
	{Particles: 0},
	{Mobile: 0},
	{Sound: 0},
	{SoundEf: 0},
	{StartingX: 0},
	{StartingY: 0},
	{MAXROWS: 0},
	{MAXCOLUMNS: 0},
	{TILESIZE: 0},
	{TotalPicked: 0},
	{CurrentColor: 0},
	{BlockUID: 0},
	{SnappedBlocks: 0},
	{LEFTEDGE: 0},
	{RIGHTEDGE: 0},
	{Direction: 0},
	{IsCarryingBlock: 0},
	{StoredY: 0},
	{PinToBlock: 0},
	{AutoSpawn: 0},
	{SpawnTime: 0},
	{AvoidLeft: 0},
	{AvoidBelow: 0},
	{Score: 0},
	{ElapsedTime: 0},
	{Value: 0}
];

self.InstanceType = {
	Block: class extends self.ISpriteInstance {},
	Reference: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	Trigger: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Destroy: class extends self.IArrayInstance {},
	WorldEdge: class extends self.ISpriteInstance {},
	Sight: class extends self.ITiledBackgroundInstance {},
	Sky: class extends self.ITiledBackgroundInstance {},
	Grid: class extends self.ITiledBackgroundInstance {},
	Laser: class extends self.ITiledBackgroundInstance {},
	RockWall: class extends self.ITiledBackgroundInstance {},
	Cannons: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	SwitchBeam: class extends self.ISpriteInstance {},
	PushBeam: class extends self.ISpriteInstance {},
	DestroyedBlock: class extends self.ISpriteInstance {},
	TextFont: class extends self.ISpriteFontInstance {},
	PullBeam: class extends self.ISpriteInstance {},
	PlayerTrail: class extends self.ISpriteInstance {},
	Shine: class extends self.ISpriteInstance {},
	JetFire: class extends self.ISpriteInstance {},
	BlockFlash: class extends self.ISpriteInstance {},
	TextFrame: class extends self.IWorldInstance {},
	GameManager: class extends self.ISpriteInstance {},
	TutorialFrame: class extends self.IWorldInstance {},
	Play: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Tutorial: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	igraj: class extends self.ISpriteInstance {},
	playgame: class extends self.ISpriteInstance {},
	moregamesadd: class extends self.ISpriteInstance {},
	joystick: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	TextFont2: class extends self.ISpriteFontInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	FireworkParticles: class extends self.IParticlesInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	winpanel4: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	home2: class extends self.ISpriteInstance {},
	BSound: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	swap: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	grab: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	leftarrow: class extends self.ISpriteInstance {},
	leftarrow2: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	lagged: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	HOWTO: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends C3.Plugins.WGSDK.Instance {},
	Solids: class extends self.ISpriteInstance {},
	Particles: class extends self.ISpriteInstance {},
	Mobile: class extends self.ISpriteInstance {}
}