const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Plugins.Keyboard,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Plugins.Browser,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.WGSDK.Cnds.RewardGranted
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Physics: 0},
	{Tilemap: 0},
	{Tilemap2: 0},
	{attack: 0},
	{spawn: 0},
	{malzemevar: 0},
	{Platform: 0},
	{Tween: 0},
	{Timer: 0},
	{player: 0},
	{Keyboard: 0},
	{player2: 0},
	{p1_attack: 0},
	{p2_attack: 0},
	{id: 0},
	{spawn_point: 0},
	{tnt: 0},
	{tnt_boom: 0},
	{tnt_patlama: 0},
	{Sine: 0},
	{TiledBackground: 0},
	{buttons: 0},
	{PlatformInfo: 0},
	{Touch: 0},
	{Mouse: 0},
	{skin_oge: 0},
	{skin_degistirme_ok: 0},
	{Pin: 0},
	{p1_skin: 0},
	{p2_skin: 0},
	{score_tabl: 0},
	{time_text: 0},
	{p1_score_text: 0},
	{p2_score_text: 0},
	{winner_card: 0},
	{winner_text: 0},
	{mobile_buttona: 0},
	{stop: 0},
	{cake: 0},
	{Bullet: 0},
	{baluun: 0},
	{malzemeler: 0},
	{Sine2: 0},
	{craftingTable: 0},
	{debug_text: 0},
	{Sprite: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{Sprite2: 0},
	{kanat: 0},
	{kanatgame: 0},
	{kanatbutton: 0},
	{Browser: 0},
	{WeeGooSDK: 0},
	{second: 0},
	{p1_score: 0},
	{p2_score: 0},
	{game_stop: 0}
];

self.InstanceType = {
	Tilemap: class extends self.ITilemapInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	player: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	player2: class extends self.ISpriteInstance {},
	p1_attack: class extends self.ISpriteInstance {},
	p2_attack: class extends self.ISpriteInstance {},
	spawn_point: class extends self.ISpriteInstance {},
	tnt: class extends self.ISpriteInstance {},
	tnt_boom: class extends self.IParticlesInstance {},
	tnt_patlama: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	buttons: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	skin_oge: class extends self.ISpriteInstance {},
	skin_degistirme_ok: class extends self.ISpriteInstance {},
	p1_skin: class extends self.ISpriteInstance {},
	p2_skin: class extends self.ISpriteInstance {},
	score_tabl: class extends self.ISpriteInstance {},
	time_text: class extends self.ITextInstance {},
	p1_score_text: class extends self.ITextInstance {},
	p2_score_text: class extends self.ITextInstance {},
	winner_card: class extends self.ISpriteInstance {},
	winner_text: class extends self.ITextInstance {},
	mobile_buttona: class extends self.ISpriteInstance {},
	stop: class extends self.ISpriteInstance {},
	cake: class extends self.ISpriteInstance {},
	baluun: class extends self.ISpriteInstance {},
	malzemeler: class extends self.ISpriteInstance {},
	craftingTable: class extends self.ISpriteInstance {},
	debug_text: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	kanat: class extends self.ISpriteInstance {},
	kanatgame: class extends self.ISpriteInstance {},
	kanatbutton: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	WeeGooSDK: class extends self.IInstance {}
}