const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Flash,
		C3.Behaviors.Tween,
		C3.Plugins.Button,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Behaviors.Timer,
		C3.Plugins.Arr,
		C3.Plugins.Particles,
		C3.Behaviors.Orbit,
		C3.Plugins.Keyboard,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Audio,
		C3.Plugins.AJAX,
		C3.Plugins.Dictionary,
		C3.Plugins.Json,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse,
		C3.Plugins.PlatformInfo,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Fade,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.NinePatch,
		C3.Plugins.TiledBg,
		C3.Plugins.LocalStorage,
		C3.Plugins.Internationalization,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Timeline,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Json.Exps.CurrentKey,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Eponesh_GameScore.Cnds.PlatformType,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.HasParent,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.roundtodp,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Json.Exps.ToBeautifiedString,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.System.Acts.ScrollX,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Exps.LayerName,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Width,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Text.Acts.AddChild,
		C3.Plugins.Text.Cnds.PickParent,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Internationalization.Exps.Lookup,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Sprite.Cnds.OnURLLoaded,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Plugins.AdvancedRandom.Acts.CreateProbabilityTable,
		C3.Plugins.AdvancedRandom.Acts.AddProbabilityEntry,
		C3.Plugins.Json.Cnds.CompareValue,
		C3.Plugins.AdvancedRandom.Exps.WeightedByName,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.TemplateName,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Json.Acts.SetPath,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Internationalization.Acts.PopContext,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Json.Exps.Path,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Json.Acts.SetNull,
		C3.Plugins.Json.Acts.SetObject,
		C3.Plugins.Eponesh_GameScore.Acts.AnalyticsGoal,
		C3.Plugins.Json.Acts.SetJSON,
		C3.Plugins.Json.Exps.GetAsCompactString,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Exps.Depth,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Arr.Acts.AddInstanceVar,
		C3.Plugins.Arr.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Arr.Cnds.CompareXYZ,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Particles.Acts.SetZElevation,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.Height,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Json.Acts.AddTo,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.Text.Cnds.PickChildren,
		C3.Plugins.TiledBg.Cnds.PickChildren,
		C3.Plugins.Internationalization.Acts.SetContext,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.System.Cnds.PickOverlappingPoint,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Behaviors.Tween.Exps.Time,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetZElevation,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.time,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Json.Exps.CurrentValue,
		C3.Plugins.Json.Acts.DeleteKey,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Exps.lowercase,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Json.Acts.SubtractFrom,
		C3.Plugins.Json.Acts.SetBoolean,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSetScore,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.System.Exps.find,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardFetch,
		C3.Plugins.Eponesh_GameScore.Cnds.OnLeaderboardFetch,
		C3.Plugins.Eponesh_GameScore.Cnds.LeaderboardEachPlayer,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerIndex,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerPosition,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerName,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerScore,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerID,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerID,
		C3.Plugins.Arr.Acts.SetBoolInstanceVar,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.Eponesh_GameScore.Cnds.IsPlayerStub,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Eponesh_GameScore.Cnds.PlayerCompare,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Text.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetX,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Text.Acts.SetSize,
		C3.Behaviors.Tween.Exps.Progress,
		C3.Plugins.Eponesh_GameScore.Cnds.EventsHas,
		C3.Plugins.Eponesh_GameScore.Cnds.EventsIsJoined,
		C3.ScriptsInEvents.Commones_Event17_Act1,
		C3.Plugins.Eponesh_GameScore.Acts.EventsJoin,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenAvailable,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsRewardedAvailable,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsStickyAvailable,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsStickyPlaying,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowSticky,
		C3.Plugins.Eponesh_GameScore.Cnds.IsPaused,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.NinePatch.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Acts.SetBoolInstanceVar,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Plugins.Eponesh_GameScore.Cnds.IsMobile,
		C3.Plugins.Eponesh_GameScore.Acts.ChangeLanguage,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardOpen,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.Eponesh_GameScore.Cnds.DeviceType,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Timeline.Acts.SetInstance,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.TiledBg.Acts.SetTowardPosition,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.Plugins.Text.Acts.SetWrapping,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.Internationalization.Acts.SetLocale,
		C3.Plugins.Internationalization.Acts.LoadFromJSON
	];
};
self.C3_JsPropNameTable = [
	{characterName: 0},
	{visNum: 0},
	{requestImageNum: 0},
	{defX: 0},
	{defY: 0},
	{defWidth: 0},
	{controlBy: 0},
	{isInGame: 0},
	{isStepped: 0},
	{hp: 0},
	{hpDefault: 0},
	{name: 0},
	{strength: 0},
	{stamina: 0},
	{staminaMax: 0},
	{moral: 0},
	{moralMax: 0},
	{mana: 0},
	{manaMax: 0},
	{magicPower: 0},
	{indexQuery: 0},
	{agility: 0},
	{isDestroy: 0},
	{isBurn: 0},
	{burnStep: 0},
	{isShield: 0},
	{isCursed: 0},
	{curseStep: 0},
	{curseKdown: 0},
	{isBless: 0},
	{blessStep: 0},
	{isLifeRage: 0},
	{lifeRageHits: 0},
	{isFireShield: 0},
	{countFireShield: 0},
	{isBlind: 0},
	{blindDamage: 0},
	{countBlind: 0},
	{isCold: 0},
	{coldCount: 0},
	{coldKdown: 0},
	{isBlunder: 0},
	{countBlunder: 0},
	{isEnergyShield: 0},
	{energyShieldK: 0},
	{countEnergyShield: 0},
	{jsonPath: 0},
	{isWaitStartSay: 0},
	{level: 0},
	{type: 0},
	{hitType: 0},
	{hitSpriteName: 0},
	{style: 0},
	{blunderAgility: 0},
	{isRiposte: 0},
	{countRiposte: 0},
	{riposteChance: 0},
	{sideCard: 0},
	{visName: 0},
	{Flash: 0},
	{Tween: 0},
	{personaCard: 0},
	{whoContol: 0},
	{id: 0},
	{dicName: 0},
	{isAvailable: 0},
	{manaCost: 0},
	{isMagic: 0},
	{indexInventory: 0},
	{staminaCost: 0},
	{defHeight: 0},
	{isEnabled: 0},
	{actionsBut: 0},
	{tag: 0},
	{butSystem: 0},
	{Browser: 0},
	{Touch: 0},
	{tagOptional: 0},
	{translate: 0},
	{bevel: 0},
	{isTranslateOnCreate: 0},
	{infoLabel: 0},
	{visEffectText: 0},
	{stageClearly: 0},
	{stageMax: 0},
	{lastIdCard: 0},
	{prizesIsCreated: 0},
	{isNeedBafEnemyCard: 0},
	{roundCounter: 0},
	{actionCounter: 0},
	{Timer: 0},
	{MainInfo: 0},
	{dungeon: 0},
	{Back2: 0},
	{plane: 0},
	{isSelected: 0},
	{selectedItem: 0},
	{isActive: 0},
	{isEnable: 0},
	{audio_name: 0},
	{volume: 0},
	{audioPath: 0},
	{isPanel: 0},
	{button: 0},
	{isPlayAvailable: 0},
	{mode: 0},
	{isStopUpSpawn: 0},
	{PEditorInfo: 0},
	{areaCircle: 0},
	{effect_line: 0},
	{particleHealEffect: 0},
	{particles_fireball: 0},
	{particleBurn: 0},
	{Orbit: 0},
	{particles_fireball2: 0},
	{lastOpacity_tween: 0},
	{spriteEffect: 0},
	{stateBless: 0},
	{maskEffects: 0},
	{num: 0},
	{icons: 0},
	{Keyboard: 0},
	{labelLevelThis: 0},
	{DragDrop: 0},
	{dndMask: 0},
	{Audio: 0},
	{inventory_full: 0},
	{curIndexQuery: 0},
	{queryArray: 0},
	{fireBall: 0},
	{AJAX: 0},
	{costsBase: 0},
	{baseCostsDic: 0},
	{spellsInfoJSON: 0},
	{Rotate: 0},
	{meerkens: 0},
	{source: 0},
	{blood: 0},
	{coldMask: 0},
	{energyShield: 0},
	{iceImpact: 0},
	{Sine: 0},
	{lightingMask: 0},
	{gameDataJSON: 0},
	{gameModesCards: 0},
	{characSelect: 0},
	{pselector: 0},
	{dialogueCloud: 0},
	{dialogueText: 0},
	{phrasesArray: 0},
	{levelParamBut: 0},
	{aboutLabel: 0},
	{Mouse: 0},
	{magicShield: 0},
	{KeyWords: 0},
	{iconText: 0},
	{stateCurse: 0},
	{stateLabel: 0},
	{stateEnergyShield: 0},
	{stateCold: 0},
	{stateFireShield: 0},
	{stateLifeRage: 0},
	{stateBlind: 0},
	{stateBurn: 0},
	{landAbout: 0},
	{effect1: 0},
	{award1: 0},
	{effect2: 0},
	{award2: 0},
	{status: 0},
	{isEnemy: 0},
	{isItem: 0},
	{isSpell: 0},
	{card: 0},
	{effect: 0},
	{award: 0},
	{cardAbilities: 0},
	{cardAbilAward: 0},
	{charactersBase: 0},
	{arrow: 0},
	{knifeAnim: 0},
	{iconMoney: 0},
	{gameSettings: 0},
	{frameSpell: 0},
	{companion: 0},
	{PlatformInfo: 0},
	{isBaseRemoteLoad: 0},
	{lastPosX_MB: 0},
	{lastPosY_MB: 0},
	{isMotionBlur: 0},
	{personaVis: 0},
	{mpower_k: 0},
	{effects_add_turn: 0},
	{event_strength_k: 0},
	{event_miss_k: 0},
	{BackBattleHolder: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{rainSimple: 0},
	{Fade: 0},
	{rainWater: 0},
	{lightning: 0},
	{lightning2: 0},
	{leaf: 0},
	{lightMask: 0},
	{cardAbilLabel: 0},
	{AdvRandom: 0},
	{AssetManager: 0},
	{cardBot: 0},
	{dungeonScenario: 0},
	{hit_tikva: 0},
	{hit_fire: 0},
	{endingBack: 0},
	{but9patch: 0},
	{panel9Patch: 0},
	{lineDecore: 0},
	{xDefault: 0},
	{cloud: 0},
	{gameIcons: 0},
	{but9patchBlue: 0},
	{upEffect: 0},
	{LightStreaks: 0},
	{phrasesJSON: 0},
	{LocalStorage: 0},
	{stateBlunder: 0},
	{hit_knife: 0},
	{stateRiposte: 0},
	{Internationalization: 0},
	{cleanseEffect: 0},
	{blunderEffect: 0},
	{riposteEffect: 0},
	{knife: 0},
	{iconParameters: 0},
	{infoLabelAbout: 0},
	{baseSize: 0},
	{lifeBarFront: 0},
	{hpLabel: 0},
	{awardObj: 0},
	{curSpellVis: 0},
	{loadingStep: 0},
	{loadingLabel: 0},
	{loadingSystem: 0},
	{simplePanel: 0},
	{backMenu: 0},
	{panelLeader: 0},
	{isOver: 0},
	{wait: 0},
	{waitTime: 0},
	{menuBut: 0},
	{menuIcons: 0},
	{GamePush: 0},
	{isLoaded: 0},
	{yourPos: 0},
	{yourScore: 0},
	{leaderArray: 0},
	{hand: 0},
	{lineTutorial: 0},
	{lineInventory: 0},
	{lineInventoryTB: 0},
	{modeFlags: 0},
	{lenta: 0},
	{placeLeaders: 0},
	{backPanel: 0},
	{effect_line2: 0},
	{companion2: 0},
	{companionPart2: 0},
	{companionPart3: 0},
	{TimelineController: 0},
	{spellDebuf: 0},
	{decoreEditor: 0},
	{rewardButton: 0},
	{videoIcon: 0},
	{Cards: 0},
	{stateIcons: 0},
	{BackBattles: 0},
	{but9patches: 0},
	{CardEffects: 0},
	{Buttons: 0},
	{dungeonLevel: 0},
	{statusGame: 0},
	{gameMode: 0},
	{isDebug: 0},
	{querySize: 0},
	{isHaveSpellItem: 0},
	{sizeDeck: 0},
	{uidChild: 0},
	{childY: 0},
	{numTarget: 0},
	{nameTarget: 0},
	{numChild: 0},
	{nameChild: 0},
	{indexTarget: 0},
	{indexChild: 0},
	{strTarget: 0},
	{strChild: 0},
	{childX: 0},
	{isShift: 0},
	{isPlayAgree: 0},
	{worldEvent: 0},
	{worldEventState: 0},
	{lastWorldEvent: 0},
	{event_: 0},
	{isAgree: 0},
	{eventL: 0},
	{isTimerNext: 0},
	{who: 0},
	{time_: 0},
	{intensity_: 0},
	{textl: 0},
	{isEnd: 0},
	{typeL: 0},
	{nameL: 0},
	{frameL: 0},
	{weaponL: 0},
	{armorL: 0},
	{accessL: 0},
	{addItemValue: 0},
	{nameItem: 0},
	{middleCount: 0},
	{hightCount: 0},
	{lowCount: 0},
	{maxMap: 0},
	{selectMap: 0},
	{levelL: 0},
	{npcNum: 0},
	{tempParam: 0},
	{hpL: 0},
	{strengthL: 0},
	{mpoweL: 0},
	{manaL: 0},
	{pathToCharacPlayer: 0},
	{staminaL: 0},
	{templateName: 0},
	{offAI: 0},
	{action_: 0},
	{xSpell: 0},
	{yPersonaCard: 0},
	{yPos: 0},
	{anim: 0},
	{slot: 0},
	{numL: 0},
	{isNextStepAgree: 0},
	{counStepped: 0},
	{countCards: 0},
	{actionL: 0},
	{damage: 0},
	{uidTargetCard: 0},
	{xTarget: 0},
	{isSuper: 0},
	{yTarget: 0},
	{isFireShieldTarget: 0},
	{controlByTarget: 0},
	{isPropertyCrit: 0},
	{isPropertyLifer: 0},
	{hpEnemyMAX: 0},
	{isSlide: 0},
	{isMagicShield: 0},
	{isRiposteNext: 0},
	{riposteK: 0},
	{indexSpellCur: 0},
	{isMiss: 0},
	{missChance: 0},
	{chance: 0},
	{crit: 0},
	{sprite_: 0},
	{isOglushenie: 0},
	{hitSoundName: 0},
	{restoreNum: 0},
	{heal_: 0},
	{burnCount: 0},
	{curseKval: 0},
	{curseCount: 0},
	{blessCount: 0},
	{isSpecial: 0},
	{turns: 0},
	{coldValue: 0},
	{agilityDebaf: 0},
	{riposteCount: 0},
	{spellName: 0},
	{uidSpellHolder: 0},
	{isHaveCard: 0},
	{charac: 0},
	{itemName: 0},
	{itemPropName: 0},
	{itemPropNum: 0},
	{itemParamSTR: 0},
	{itemParam: 0},
	{itemFrame: 0},
	{itemType: 0},
	{isGave: 0},
	{result: 0},
	{victoryWord: 0},
	{defeatWord: 0},
	{pickNameVic: 0},
	{pickNameDef: 0},
	{word: 0},
	{uidAttackHolder: 0},
	{uidShieldHolder: 0},
	{damageL: 0},
	{life: 0},
	{numl: 0},
	{super: 0},
	{moneyCount: 0},
	{expCoinCount: 0},
	{scoreCount: 0},
	{sumL: 0},
	{d: 0},
	{a1: 0},
	{aLast: 0},
	{xCentre: 0},
	{yCentre: 0},
	{isReturn: 0},
	{uidLocal: 0},
	{indexPersonaCard: 0},
	{maxIndex: 0},
	{mapNum: 0},
	{mapName: 0},
	{costL: 0},
	{resource: 0},
	{costFullName: 0},
	{costName: 0},
	{costNum: 0},
	{uidCardHolder: 0},
	{stepL: 0},
	{yCoord: 0},
	{isFinded: 0},
	{playerQueryPos: 0},
	{enemyIDLocal: 0},
	{playerIDLocal: 0},
	{count: 0},
	{indexL: 0},
	{soundPath: 0},
	{isLog: 0},
	{textL: 0},
	{soundName: 0},
	{iconName: 0},
	{tactic: 0},
	{selectedSpell: 0},
	{typeEnemy: 0},
	{levelEnemy: 0},
	{shieldCount: 0},
	{hitCount: 0},
	{isHasCurse: 0},
	{meerkensCount: 0},
	{isCurse: 0},
	{typeOfEnemy: 0},
	{nothingCount: 0},
	{fireCount: 0},
	{isBlunderOpponent: 0},
	{isColdOpponent: 0},
	{styleL: 0},
	{tempSelect: 0},
	{isChose: 0},
	{spell_get: 0},
	{index: 0},
	{isHave: 0},
	{spellL: 0},
	{whoNum: 0},
	{retVal: 0},
	{nameObj: 0},
	{difficult: 0},
	{numStage: 0},
	{lastCharSelect: 0},
	{uid: 0},
	{loadingStepNum: 0},
	{loadingStepCount: 0},
	{newParams: 0},
	{newLabels: 0},
	{item: 0},
	{characL: 0},
	{nameSelfButton: 0},
	{layerSelfButton: 0},
	{uidSelfButton: 0},
	{cost: 0},
	{moneyL: 0},
	{newCharName: 0},
	{curCharName: 0},
	{isChanged: 0},
	{indexDirect: 0},
	{targetIndex: 0},
	{i: 0},
	{i2: 0},
	{direct: 0},
	{numForLevel: 0},
	{nameParam: 0},
	{animName: 0},
	{animFrame: 0},
	{typeItem: 0},
	{numVisMultiple: 0},
	{isFirstGame: 0},
	{agreeSave: 0},
	{returnVal: 0},
	{tempString: 0},
	{aboutLoaded: 0},
	{charPath: 0},
	{charL: 0},
	{newAbout: 0},
	{isReset: 0},
	{loadSave: 0},
	{isCardTween: 0},
	{isRemoveChild: 0},
	{selfWidth: 0},
	{selfHeight: 0},
	{template: 0},
	{layerName: 0},
	{isOn: 0},
	{addJsonPath: 0},
	{tutorialStep: 0},
	{tutorialStepEditorStart: 0},
	{tutorLocked: 0},
	{isAgreeSkipTutorial: 0},
	{isTutorial: 0},
	{Variable1: 0},
	{assetsNeed: 0},
	{assetsCount: 0},
	{isAssetsLoaded: 0},
	{numEnemy: 0},
	{enemyType: 0},
	{countCur: 0},
	{countMax: 0},
	{isMultiplayer: 0},
	{playerName: 0},
	{enemyName: 0},
	{isMusic: 0},
	{isSound: 0},
	{numLines: 0},
	{nameLines: 0},
	{scoreLines: 0},
	{translateLoaded: 0},
	{language: 0}
];

self.InstanceType = {
	personaCard: class extends self.ISpriteInstance {},
	actionsBut: class extends self.ISpriteInstance {},
	butSystem: class extends self.IButtonInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	infoLabel: class extends self.ITextInstance {},
	visEffectText: class extends self.ITextInstance {},
	MainInfo: class extends self.ISpriteInstance {},
	dungeon: class extends self.IArrayInstance {},
	Back2: class extends self.ISpriteInstance {},
	plane: class extends self.ISpriteInstance {},
	button: class extends self.ISpriteInstance {},
	PEditorInfo: class extends self.ISpriteInstance {},
	areaCircle: class extends self.ISpriteInstance {},
	effect_line: class extends self.ISpriteInstance {},
	particleHealEffect: class extends self.IParticlesInstance {},
	particles_fireball: class extends self.IParticlesInstance {},
	particleBurn: class extends self.IParticlesInstance {},
	particles_fireball2: class extends self.IParticlesInstance {},
	spriteEffect: class extends self.ISpriteInstance {},
	stateBless: class extends self.ISpriteInstance {},
	maskEffects: class extends self.ISpriteInstance {},
	icons: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	labelLevelThis: class extends self.ITextInstance {},
	dndMask: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	inventory_full: class extends self.IArrayInstance {},
	queryArray: class extends self.IArrayInstance {},
	fireBall: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	costsBase: class extends self.IArrayInstance {},
	baseCostsDic: class extends self.IDictionaryInstance {},
	spellsInfoJSON: class extends self.IJSONInstance {},
	meerkens: class extends self.ISpriteInstance {},
	blood: class extends self.ISpriteInstance {},
	coldMask: class extends self.ISpriteInstance {},
	energyShield: class extends self.ISpriteInstance {},
	iceImpact: class extends self.IParticlesInstance {},
	lightingMask: class extends self.ISpriteInstance {},
	gameDataJSON: class extends self.IJSONInstance {},
	gameModesCards: class extends self.ISpriteInstance {},
	pselector: class extends self.ISpriteInstance {},
	dialogueCloud: class extends self.ISpriteInstance {},
	dialogueText: class extends self.ITextInstance {},
	phrasesArray: class extends self.IArrayInstance {},
	levelParamBut: class extends self.ISpriteInstance {},
	aboutLabel: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	magicShield: class extends self.ISpriteInstance {},
	KeyWords: class extends self.IDictionaryInstance {},
	iconText: class extends self.ISpriteInstance {},
	stateCurse: class extends self.ISpriteInstance {},
	stateLabel: class extends self.ITextInstance {},
	stateEnergyShield: class extends self.ISpriteInstance {},
	stateCold: class extends self.ISpriteInstance {},
	stateFireShield: class extends self.ISpriteInstance {},
	stateLifeRage: class extends self.ISpriteInstance {},
	stateBlind: class extends self.ISpriteInstance {},
	stateBurn: class extends self.ISpriteInstance {},
	landAbout: class extends self.ITextInstance {},
	card: class extends self.ISpriteInstance {},
	cardAbilities: class extends self.ISpriteInstance {},
	cardAbilAward: class extends self.ITextInstance {},
	charactersBase: class extends self.IJSONInstance {},
	arrow: class extends self.ISpriteInstance {},
	knifeAnim: class extends self.ISpriteInstance {},
	iconMoney: class extends self.ISpriteInstance {},
	gameSettings: class extends self.IDictionaryInstance {},
	frameSpell: class extends self.ISpriteInstance {},
	companion: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	personaVis: class extends self.ISpriteInstance {},
	BackBattleHolder: class extends self.ISpriteInstance {},
	rainSimple: class extends self.ISpriteInstance {},
	rainWater: class extends self.ISpriteInstance {},
	lightning: class extends self.ISpriteInstance {},
	lightning2: class extends self.ISpriteInstance {},
	leaf: class extends self.ISpriteInstance {},
	lightMask: class extends self.ISpriteInstance {},
	cardAbilLabel: class extends self.ITextInstance {},
	AdvRandom: class extends self.IInstance {},
	AssetManager: class extends self.ISpriteInstance {},
	cardBot: class extends self.ISpriteInstance {},
	dungeonScenario: class extends self.IJSONInstance {},
	hit_tikva: class extends self.ISpriteInstance {},
	hit_fire: class extends self.ISpriteInstance {},
	endingBack: class extends self.ISpriteInstance {},
	but9patch: class extends self.IWorldInstance {},
	panel9Patch: class extends self.IWorldInstance {},
	lineDecore: class extends self.ITiledBackgroundInstance {},
	cloud: class extends self.ISpriteInstance {},
	gameIcons: class extends self.ISpriteInstance {},
	but9patchBlue: class extends self.IWorldInstance {},
	upEffect: class extends self.ISpriteInstance {},
	LightStreaks: class extends self.ITiledBackgroundInstance {},
	phrasesJSON: class extends self.IJSONInstance {},
	LocalStorage: class extends self.IInstance {},
	stateBlunder: class extends self.ISpriteInstance {},
	hit_knife: class extends self.ISpriteInstance {},
	stateRiposte: class extends self.ISpriteInstance {},
	Internationalization: class extends self.IInstance {},
	cleanseEffect: class extends self.ISpriteInstance {},
	blunderEffect: class extends self.ISpriteInstance {},
	riposteEffect: class extends self.ISpriteInstance {},
	knife: class extends self.ISpriteInstance {},
	iconParameters: class extends self.ISpriteInstance {},
	infoLabelAbout: class extends self.ITextInstance {},
	lifeBarFront: class extends self.ITiledBackgroundInstance {},
	hpLabel: class extends self.ITextInstance {},
	awardObj: class extends self.ISpriteInstance {},
	curSpellVis: class extends self.ISpriteInstance {},
	loadingStep: class extends self.ISpriteInstance {},
	loadingLabel: class extends self.ITextInstance {},
	loadingSystem: class extends self.ISpriteInstance {},
	simplePanel: class extends self.ISpriteInstance {},
	backMenu: class extends self.ISpriteInstance {},
	panelLeader: class extends self.ISpriteInstance {},
	menuBut: class extends self.ISpriteInstance {},
	menuIcons: class extends self.ISpriteInstance {},
	GamePush: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	leaderArray: class extends self.IArrayInstance {},
	hand: class extends self.ISpriteInstance {},
	lineTutorial: class extends self.ITiledBackgroundInstance {},
	lineInventory: class extends self.ISpriteInstance {},
	lineInventoryTB: class extends self.ITiledBackgroundInstance {},
	modeFlags: class extends self.ISpriteInstance {},
	lenta: class extends self.ISpriteInstance {},
	placeLeaders: class extends self.ISpriteInstance {},
	backPanel: class extends self.ISpriteInstance {},
	effect_line2: class extends self.ISpriteInstance {},
	companion2: class extends self.ISpriteInstance {},
	companionPart2: class extends self.ISpriteInstance {},
	companionPart3: class extends self.ISpriteInstance {},
	TimelineController: class extends self.IInstance {},
	spellDebuf: class extends self.ISpriteInstance {},
	decoreEditor: class extends self.ISpriteInstance {},
	rewardButton: class extends self.ISpriteInstance {},
	videoIcon: class extends self.ISpriteInstance {},
	Cards: class extends self.ISpriteInstance {},
	stateIcons: class extends self.ISpriteInstance {},
	BackBattles: class extends self.ISpriteInstance {},
	but9patches: class extends self.IWorldInstance {},
	CardEffects: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {}
}