const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.sliderbar,
		C3.Plugins.Spritefont2,
		C3.Plugins.NinePatch,
		C3.Plugins.Touch,
		C3.Plugins.DrawingCanvas,
		C3.Plugins.filechooser,
		C3.Plugins.Browser,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Plugins.WGSDK,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.sliderbar.Acts.SetCSSStyle,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.sliderbar.Cnds.CompareInstanceVar,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.sliderbar.Cnds.CompareValue,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.DrawingCanvas.Cnds.OnSavedImage,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.DrawingCanvas.Exps.SavedImageURL,
		C3.Plugins.DrawingCanvas.Acts.ClearCanvas,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Plugins.DrawingCanvas.Acts.SaveImage,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.random,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.sliderbar.Cnds.OnChanging,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Fade.Acts.StartFade
	];
};
self.C3_JsPropNameTable = [
	{Red: 0},
	{Green: 0},
	{Blue: 0},
	{body: 0},
	{leg_L: 0},
	{leg_R: 0},
	{arm_R: 0},
	{arm_L: 0},
	{neck: 0},
	{head: 0},
	{foot_R: 0},
	{foot_L: 0},
	{hand_R: 0},
	{hand_l: 0},
	{Type: 0},
	{SliderBar: 0},
	{Eyes: 0},
	{Mouth: 0},
	{sprite: 0},
	{Pos: 0},
	{uiBG: 0},
	{type: 0},
	{slider_L: 0},
	{slider_R: 0},
	{head2: 0},
	{arm_L2: 0},
	{arm_R2: 0},
	{body2: 0},
	{Eyes2: 0},
	{Mouth2: 0},
	{hand_l2: 0},
	{hand_R2: 0},
	{leg_L2: 0},
	{leg_R2: 0},
	{foot_L2: 0},
	{foot_R2: 0},
	{arrowRight: 0},
	{arrowLeft: 0},
	{Touch: 0},
	{foglio: 0},
	{btn_reward: 0},
	{DrawingCanvas: 0},
	{FileChooser: 0},
	{Browser: 0},
	{Tween: 0},
	{monsterMaker_Title: 0},
	{audioOn: 0},
	{bg_black: 0},
	{cover_PI: 0},
	{Fade: 0},
	{cover_Dev: 0},
	{cover_Ti: 0},
	{cover_Ball_Red: 0},
	{cover_Ball_blu: 0},
	{fader: 0},
	{Audio: 0},
	{isSelected: 0},
	{btn_play: 0},
	{foglio2: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{WeeGooSDK: 0},
	{Sine: 0},
	{BodyParts: 0},
	{Sliders: 0},
	{buttons: 0},
	{CanvasObjects: 0},
	{Covers: 0},
	{v_head: 0},
	{v_footR: 0},
	{v_footL: 0},
	{v_armL: 0},
	{v_armR: 0},
	{v_body: 0},
	{v_handL: 0},
	{v_handR: 0},
	{v_legL: 0},
	{v_legR: 0},
	{v_mouth: 0},
	{v_eyes: 0},
	{position: 0},
	{isSound: 0}
];

self.InstanceType = {
	body: class extends self.ISpriteInstance {},
	leg_L: class extends self.ISpriteInstance {},
	leg_R: class extends self.ISpriteInstance {},
	arm_R: class extends self.ISpriteInstance {},
	arm_L: class extends self.ISpriteInstance {},
	neck: class extends self.ISpriteInstance {},
	head: class extends self.ISpriteInstance {},
	foot_R: class extends self.ISpriteInstance {},
	foot_L: class extends self.ISpriteInstance {},
	hand_R: class extends self.ISpriteInstance {},
	hand_l: class extends self.ISpriteInstance {},
	SliderBar: class extends self.ISliderBarInstance {},
	Eyes: class extends self.ISpriteInstance {},
	Mouth: class extends self.ISpriteInstance {},
	sprite: class extends self.ISpriteFontInstance {},
	uiBG: class extends self.IWorldInstance {},
	slider_L: class extends self.ISpriteInstance {},
	slider_R: class extends self.ISpriteInstance {},
	head2: class extends self.ISpriteInstance {},
	arm_L2: class extends self.ISpriteInstance {},
	arm_R2: class extends self.ISpriteInstance {},
	body2: class extends self.ISpriteInstance {},
	Eyes2: class extends self.ISpriteInstance {},
	Mouth2: class extends self.ISpriteInstance {},
	hand_l2: class extends self.ISpriteInstance {},
	hand_R2: class extends self.ISpriteInstance {},
	leg_L2: class extends self.ISpriteInstance {},
	leg_R2: class extends self.ISpriteInstance {},
	foot_L2: class extends self.ISpriteInstance {},
	foot_R2: class extends self.ISpriteInstance {},
	arrowRight: class extends self.ISpriteInstance {},
	arrowLeft: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	foglio: class extends self.ISpriteInstance {},
	btn_reward: class extends self.ISpriteInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	FileChooser: class extends self.IWorldInstance {},
	Browser: class extends self.IInstance {},
	monsterMaker_Title: class extends self.ISpriteInstance {},
	audioOn: class extends self.ISpriteInstance {},
	bg_black: class extends self.ITiledBackgroundInstance {},
	cover_PI: class extends self.ISpriteInstance {},
	cover_Dev: class extends self.ISpriteInstance {},
	cover_Ti: class extends self.ISpriteInstance {},
	cover_Ball_Red: class extends self.ISpriteInstance {},
	cover_Ball_blu: class extends self.ISpriteInstance {},
	fader: class extends self.ITiledBackgroundInstance {},
	Audio: class extends self.IInstance {},
	btn_play: class extends self.ISpriteInstance {},
	foglio2: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	BodyParts: class extends self.ISpriteInstance {},
	Sliders: class extends self.ISpriteInstance {},
	buttons: class extends self.ISpriteInstance {},
	CanvasObjects: class extends self.ISpriteInstance {},
	Covers: class extends self.ISpriteInstance {}
}