const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Pin,
		C3.Behaviors.solid,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Plugins.LocalStorage,
		C3.Behaviors.lunarray_LiteTween,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Browser,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Rotate,
		C3.Behaviors.Tween,
		C3.Behaviors.bound,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.ApplyTorque,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Physics.Acts.ApplyForce,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.WGSDK.Cnds.RewardGranted,
		C3.Plugins.LocalStorage.Cnds.OnAllGetsComplete,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{Physics: 0},
	{Ground: 0},
	{Text: 0},
	{BackWheel: 0},
	{Mouse: 0},
	{ScrollTo: 0},
	{CarBody: 0},
	{FrontWheel: 0},
	{Keyboard: 0},
	{Ground2: 0},
	{kriva: 0},
	{Pin: 0},
	{okidac: 0},
	{oklop: 0},
	{Solid: 0},
	{Ground3: 0},
	{Body: 0},
	{Head: 0},
	{kapa: 0},
	{cilj: 0},
	{BG: 0},
	{zemlja: 0},
	{bomba: 0},
	{Sprite3: 0},
	{Sprite11: 0},
	{platforma: 0},
	{Touch: 0},
	{drive: 0},
	{menu: 0},
	{BSound2: 0},
	{Audio: 0},
	{stop: 0},
	{Sine: 0},
	{dalje: 0},
	{ponovo: 0},
	{failed2: 0},
	{okvir: 0},
	{okvir2: 0},
	{Firework: 0},
	{diamond: 0},
	{LocalStorage: 0},
	{Mejor: 0},
	{Sprite: 0},
	{LiteTween: 0},
	{ruka: 0},
	{Sprite2: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{btn_games: 0},
	{bridge: 0},
	{Sprite6: 0},
	{TiledBackground4: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{TiledBackground5: 0},
	{Sprite10: 0},
	{Sprite12: 0},
	{TiledBackground6: 0},
	{platformaudar: 0},
	{TiledBackground7: 0},
	{Sprite13: 0},
	{platformalet: 0},
	{box: 0},
	{Anchor: 0},
	{HomeButton: 0},
	{ShipSkin2: 0},
	{Open: 0},
	{Level: 0},
	{LevelsBlock: 0},
	{Sprite28: 0},
	{leveli: 0},
	{Sprite14: 0},
	{Rope3: 0},
	{Wheel1: 0},
	{Rope5: 0},
	{Rope0: 0},
	{Rope1: 0},
	{Rope6: 0},
	{Rope4: 0},
	{Rope2: 0},
	{Sprite27: 0},
	{pozadina: 0},
	{Fireworknove: 0},
	{zvijezda: 0},
	{masna: 0},
	{menu2: 0},
	{Sprite15: 0},
	{Browser: 0},
	{skip: 0},
	{Ground4: 0},
	{START: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{drvomrda: 0},
	{cvijet: 0},
	{bomba2: 0},
	{tlo2: 0},
	{bomba3: 0},
	{Sprite21: 0},
	{tlo3: 0},
	{kruzna: 0},
	{kruzna1: 0},
	{kruzna2: 0},
	{slovazalevele: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{list: 0},
	{Sprite25: 0},
	{drva: 0},
	{ScoreText: 0},
	{highscoretext: 0},
	{cjev: 0},
	{zid: 0},
	{zid1: 0},
	{Sprite26: 0},
	{cjev2: 0},
	{zid2: 0},
	{safe: 0},
	{cjev3: 0},
	{zid3: 0},
	{safe2: 0},
	{daljezakraj: 0},
	{cilj2: 0},
	{Sprite29: 0},
	{lagged: 0},
	{slash: 0},
	{slashh: 0},
	{play: 0},
	{turbo: 0},
	{linija: 0},
	{replay: 0},
	{Sprite30: 0},
	{konfettiii: 0},
	{list2: 0},
	{START2: 0},
	{list3: 0},
	{win: 0},
	{zemlja2: 0},
	{cjev4: 0},
	{START3: 0},
	{lopta: 0},
	{Rotate: 0},
	{zaga: 0},
	{Sprite24: 0},
	{cilj3: 0},
	{dalje2: 0},
	{curScale: 0},
	{TrailGlow: 0},
	{OldX: 0},
	{OldY: 0},
	{trailCreator: 0},
	{oldX: 0},
	{oldY: 0},
	{Tween: 0},
	{BoundToLayout: 0},
	{CueBall: 0},
	{levels: 0},
	{Sprite32: 0},
	{HomeBTN: 0},
	{Sprite31: 0},
	{skiplevel: 0},
	{WeeGooSDK: 0},
	{CarGame: 0},
	{obstacles: 0},
	{buttons: 0},
	{lastX: 0},
	{lastY: 0},
	{LAST_LEVEL: 0},
	{WIN: 0},
	{ClaveMejor: 0},
	{MejorPuntuacion: 0},
	{Puntuacion: 0},
	{ctd_score: 0},
	{sound: 0},
	{recorde: 0},
	{SoundEf: 0},
	{HighScore: 0},
	{Score: 0},
	{TrailResolution: 0},
	{OldToNew: 0},
	{OldToNew2: 0}
];

self.InstanceType = {
	Ground: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	BackWheel: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	CarBody: class extends self.ISpriteInstance {},
	FrontWheel: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Ground2: class extends self.ISpriteInstance {},
	kriva: class extends self.ISpriteInstance {},
	okidac: class extends self.ISpriteInstance {},
	oklop: class extends self.ISpriteInstance {},
	Ground3: class extends self.ISpriteInstance {},
	Body: class extends self.ISpriteInstance {},
	Head: class extends self.ISpriteInstance {},
	kapa: class extends self.ISpriteInstance {},
	cilj: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	zemlja: class extends self.ISpriteInstance {},
	bomba: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	platforma: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	drive: class extends self.ISpriteInstance {},
	menu: class extends self.ISpriteInstance {},
	BSound2: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	stop: class extends self.ISpriteInstance {},
	dalje: class extends self.ISpriteInstance {},
	ponovo: class extends self.ISpriteInstance {},
	failed2: class extends self.ISpriteInstance {},
	okvir: class extends self.ISpriteInstance {},
	okvir2: class extends self.ISpriteInstance {},
	Firework: class extends self.IParticlesInstance {},
	diamond: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Mejor: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	ruka: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	btn_games: class extends self.ISpriteInstance {},
	bridge: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	platformaudar: class extends self.ISpriteInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	platformalet: class extends self.ISpriteInstance {},
	box: class extends self.ITiledBackgroundInstance {},
	HomeButton: class extends self.ISpriteInstance {},
	ShipSkin2: class extends self.ISpriteInstance {},
	LevelsBlock: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	leveli: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Rope3: class extends self.ISpriteInstance {},
	Wheel1: class extends self.ISpriteInstance {},
	Rope5: class extends self.ISpriteInstance {},
	Rope0: class extends self.ISpriteInstance {},
	Rope1: class extends self.ISpriteInstance {},
	Rope6: class extends self.ISpriteInstance {},
	Rope4: class extends self.ISpriteInstance {},
	Rope2: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	pozadina: class extends self.ISpriteInstance {},
	Fireworknove: class extends self.IParticlesInstance {},
	zvijezda: class extends self.ISpriteInstance {},
	masna: class extends self.ISpriteInstance {},
	menu2: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	skip: class extends self.ISpriteInstance {},
	Ground4: class extends self.ISpriteInstance {},
	START: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	drvomrda: class extends self.ISpriteInstance {},
	cvijet: class extends self.ISpriteInstance {},
	bomba2: class extends self.ISpriteInstance {},
	tlo2: class extends self.ISpriteInstance {},
	bomba3: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	tlo3: class extends self.ISpriteInstance {},
	kruzna: class extends self.ISpriteInstance {},
	kruzna1: class extends self.ISpriteInstance {},
	kruzna2: class extends self.ISpriteInstance {},
	slovazalevele: class extends self.ISpriteFontInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	list: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	drva: class extends self.ISpriteInstance {},
	ScoreText: class extends self.ITextInstance {},
	highscoretext: class extends self.ITextInstance {},
	cjev: class extends self.ISpriteInstance {},
	zid: class extends self.ISpriteInstance {},
	zid1: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	cjev2: class extends self.ISpriteInstance {},
	zid2: class extends self.ISpriteInstance {},
	safe: class extends self.ISpriteInstance {},
	cjev3: class extends self.ISpriteInstance {},
	zid3: class extends self.ISpriteInstance {},
	safe2: class extends self.ISpriteInstance {},
	daljezakraj: class extends self.ISpriteInstance {},
	cilj2: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	lagged: class extends self.ISpriteInstance {},
	slash: class extends self.ISpriteInstance {},
	slashh: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	turbo: class extends self.ISpriteInstance {},
	linija: class extends self.ISpriteInstance {},
	replay: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	konfettiii: class extends self.ISpriteInstance {},
	list2: class extends self.ISpriteInstance {},
	START2: class extends self.ISpriteInstance {},
	list3: class extends self.ISpriteInstance {},
	win: class extends self.ISpriteInstance {},
	zemlja2: class extends self.ISpriteInstance {},
	cjev4: class extends self.ISpriteInstance {},
	START3: class extends self.ISpriteInstance {},
	lopta: class extends self.ISpriteInstance {},
	zaga: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	cilj3: class extends self.ISpriteInstance {},
	dalje2: class extends self.ISpriteInstance {},
	TrailGlow: class extends self.ISpriteInstance {},
	trailCreator: class extends self.ISpriteInstance {},
	CueBall: class extends self.ISpriteInstance {},
	levels: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	HomeBTN: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	skiplevel: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends C3.Plugins.WGSDK.Instance {},
	CarGame: class extends self.ISpriteInstance {},
	obstacles: class extends self.ISpriteInstance {},
	buttons: class extends self.ISpriteInstance {}
}