const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Car,
		C3.Plugins.Camera3D,
		C3.Plugins.Keyboard,
		C3.Plugins.Shape3D,
		C3.Behaviors.solid,
		C3.Behaviors.Tween,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.scrollto,
		C3.Behaviors.custom,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Behaviors.Rotate,
		C3.Plugins.LocalStorage,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Pin,
		C3.Plugins.PlatformInfo,
		C3.Plugins.WGSDK,
		C3.Behaviors.Pathfinding,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Shape3D.Cnds.OnCreated,
		C3.Plugins.Shape3D.Acts.SetZHeight,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Shape3D.Acts.SetWidth,
		C3.Plugins.Shape3D.Acts.SetFaceVisible,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Camera3D.Acts.LookParallelToLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Shape3D.Acts.SetTowardPosition,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Car.Acts.SimulateControl,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.SetLayerEffectEnabled,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Shape3D.Exps.Width,
		C3.Plugins.Shape3D.Exps.Height,
		C3.Plugins.Shape3D.Acts.SetPosToObject,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Shape3D.Acts.AddChild,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.Pathfinding.Cnds.OnFailedToFindPath,
		C3.Behaviors.Pathfinding.Cnds.OnArrived,
		C3.Behaviors.Pathfinding.Cnds.IsMoving,
		C3.Behaviors.Pathfinding.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Pin.Acts.PinByDistance,
		C3.Behaviors.Pin.Acts.SetPinDistance,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.custom.Acts.SetSpeed,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.WGSDK.Cnds.RewardReady,
		C3.Plugins.WGSDK.Cnds.RewardGranted,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Behaviors.Fade.Acts.StartFade
	];
};
self.C3_JsPropNameTable = [
	{bg_floor: 0},
	{playerSpeed: 0},
	{isMoving: 0},
	{Car: 0},
	{player: 0},
	{"3DCamera": 0},
	{Keyboard: 0},
	{wall: 0},
	{Solid: 0},
	{walls: 0},
	{ceiling: 0},
	{Player_arm: 0},
	{isUp: 0},
	{Tween: 0},
	{Paper: 0},
	{Mouse: 0},
	{"3dPerson_1": 0},
	{Person_1: 0},
	{state: 0},
	{isGuilty: 0},
	{saccoNum: 0},
	{isWomen: 0},
	{person_1_ctrl: 0},
	{shadow: 0},
	{"3dPerson_2": 0},
	{person_2_ctrl: 0},
	{Person_2: 0},
	{hit: 0},
	{Audio: 0},
	{"3dPerson_2_dead": 0},
	{person_2_dead_mask: 0},
	{"3dPerson_1_dead": 0},
	{person_1_dead_mask: 0},
	{person_3_ctrl: 0},
	{Person_3: 0},
	{person_3_dead_mask: 0},
	{"3dPerson_3": 0},
	{"3dPerson_3_dead": 0},
	{person_4_ctrl: 0},
	{Person_4: 0},
	{person_4_dead_mask: 0},
	{"3dPerson_4": 0},
	{"3dPerson_4_dead": 0},
	{Person_5: 0},
	{person_5_dead_mask: 0},
	{person_5_ctrl: 0},
	{"3dPerson_5": 0},
	{"3dPerson_5_dead": 0},
	{guard: 0},
	{Sprite: 0},
	{hp: 0},
	{hpMax: 0},
	{percentage: 0},
	{bloodLevel: 0},
	{randomValue: 0},
	{sacco: 0},
	{sacco_dead: 0},
	{Touch: 0},
	{sgabello: 0},
	{sizeValue: 0},
	{bloodSpot: 0},
	{Level: 0},
	{Difficulty: 0},
	{GameType: 0},
	{GameTimer: 0},
	{MinigameTimer: 0},
	{victimHP: 0},
	{isGameover: 0},
	{isWin: 0},
	{isGame: 0},
	{GameControl: 0},
	{Sfondo: 0},
	{Sine: 0},
	{Lampada: 0},
	{lamp_light: 0},
	{lamp_front: 0},
	{bloodspot2: 0},
	{Clock: 0},
	{timer: 0},
	{Lancetta: 0},
	{Clock2: 0},
	{SpriteFont: 0},
	{interrogatio_wall: 0},
	{fader: 0},
	{ui_Hint_game: 0},
	{ui_Play: 0},
	{darkner: 0},
	{ScrollTo: 0},
	{camera: 0},
	{ui_barra: 0},
	{ui_triangle: 0},
	{movement: 0},
	{Custom: 0},
	{ui_pointer: 0},
	{trigger: 0},
	{ui_bar: 0},
	{o_paint: 0},
	{o_vario: 0},
	{ui_hp: 0},
	{heart_full: 0},
	{person_6_ctrl: 0},
	{Person_6: 0},
	{person_6_dead_mask: 0},
	{"3dPerson_6": 0},
	{"3dPerson_6_dead": 0},
	{ui_gameOver: 0},
	{ui_YouWin: 0},
	{Person_7: 0},
	{Person_7_dead_mask: 0},
	{person_7_ctrl: 0},
	{"3dPerson_7": 0},
	{"3dPerson_7_dead": 0},
	{"3D_paint_1": 0},
	{"3D_paint_2": 0},
	{"3D_paint_3": 0},
	{"3D_paint_4": 0},
	{"3D_paint_5": 0},
	{"3D_paint_6": 0},
	{"3D_paint_7": 0},
	{"3D_paint_8": 0},
	{"3D_paint_9": 0},
	{"3D_paint_10": 0},
	{"3D_paint_11": 0},
	{"3D_paint_12": 0},
	{"3D_paint_13": 0},
	{"3D_door": 0},
	{"3D_exit": 0},
	{person_8_ctrl: 0},
	{"3dPerson_8": 0},
	{"3dPerson_8_dead": 0},
	{Person_8: 0},
	{Person_8_dead_mask: 0},
	{person_9_ctrl: 0},
	{Person_9: 0},
	{Person_9_dead_mask: 0},
	{"3dPerson_9": 0},
	{"3dPerson_9_dead": 0},
	{person_10_ctrl: 0},
	{Person_10: 0},
	{Person_10_dead_mask: 0},
	{"3dPerson_10": 0},
	{"3dPerson_10_dead": 0},
	{person_11_ctrl: 0},
	{Person_11: 0},
	{Person_11_dead_mask: 0},
	{"3dPerson_11": 0},
	{"3dPerson_11_dead": 0},
	{Person_12: 0},
	{Person_12_dead_mask: 0},
	{person_12_ctrl: 0},
	{"3dPerson_12": 0},
	{"3dPerson_12_dead": 0},
	{person_13_ctrl: 0},
	{Person_13: 0},
	{Person_13_dead_mask: 0},
	{"3dPerson_13": 0},
	{"3dPerson_13_dead": 0},
	{Person_14: 0},
	{Person_14_dead_mask: 0},
	{person_14_ctrl: 0},
	{"3dPerson_14": 0},
	{"3dPerson_14_dead": 0},
	{person_15_ctrl: 0},
	{Person_15: 0},
	{Person_15_dead_mask: 0},
	{"3dPerson_15": 0},
	{"3dPerson_15_dead": 0},
	{hint_level_: 0},
	{"3D_paint_14": 0},
	{"3D_paint_15": 0},
	{"3D_paint_16": 0},
	{"3D_paint_17": 0},
	{"3D_paint_18": 0},
	{"3D_paint_19": 0},
	{"3D_paint_20": 0},
	{"3D_paint_21": 0},
	{"3D_paint_22": 0},
	{"3D_paint_23": 0},
	{Plant: 0},
	{"3D_plant": 0},
	{wall_top: 0},
	{bronzo: 0},
	{"3D_statue": 0},
	{luogoInteresse: 0},
	{Sacco_anim: 0},
	{human_collapsed: 0},
	{ui_center: 0},
	{Bullet: 0},
	{ui_ball: 0},
	{ui_timesUp: 0},
	{gioconda: 0},
	{paint_anim: 0},
	{splatter: 0},
	{ui_audio: 0},
	{bg_sacco: 0},
	{color: 0},
	{Play: 0},
	{ui_titolo: 0},
	{wall2: 0},
	{level: 0},
	{ui_lev_1: 0},
	{ui_lev_2: 0},
	{ui_lev_3: 0},
	{ui_QUADRO: 0},
	{ui_levelSelect: 0},
	{cordoni: 0},
	{Fade: 0},
	{eff_hit: 0},
	{Vernice: 0},
	{Rotate: 0},
	{sun: 0},
	{LocalStorage: 0},
	{ui_skip: 0},
	{ui_tutorial: 0},
	{ui_hint: 0},
	{letterM: 0},
	{hint_level_2: 0},
	{hint_level_3: 0},
	{Aimpad: 0},
	{DragDrop: 0},
	{Pin: 0},
	{Aimstick: 0},
	{Joypad: 0},
	{Joystick: 0},
	{ui_attack: 0},
	{PlatformInfo: 0},
	{btn_rewarded: 0},
	{UI_extraTime: 0},
	{bg_black: 0},
	{cover_PI: 0},
	{cover_Dev: 0},
	{cover_Ti: 0},
	{cover_Ball_Red: 0},
	{cover_Ball_blu: 0},
	{WeeGooSDK: 0},
	{People: 0},
	{People_mask: 0},
	{Pathfinding: 0},
	{People_controls: 0},
	{uis: 0},
	{Objects: 0},
	{Levels: 0},
	{buttons: 0},
	{TouchControls: 0},
	{Logos: 0},
	{CoverScreen: 0},
	{Cover: 0},
	{isSound: 0},
	{LevelToUnlock: 0},
	{VictimHP: 0},
	{difficulty: 0},
	{Timer: 0},
	{RightPerson: 0},
	{isUncensored: 0},
	{isWoman: 0}
];

self.InstanceType = {
	bg_floor: class extends self.ITiledBackgroundInstance {},
	player: class extends self.ISpriteInstance {},
	_3DCamera: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	wall: class extends self.ITiledBackgroundInstance {},
	walls: class extends self.I3DShapeInstance {},
	ceiling: class extends self.ITiledBackgroundInstance {},
	Player_arm: class extends self.ISpriteInstance {},
	Paper: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	_3dPerson_1: class extends self.I3DShapeInstance {},
	Person_1: class extends self.ISpriteInstance {},
	person_1_ctrl: class extends self.ISpriteInstance {},
	shadow: class extends self.ISpriteInstance {},
	_3dPerson_2: class extends self.I3DShapeInstance {},
	person_2_ctrl: class extends self.ISpriteInstance {},
	Person_2: class extends self.ISpriteInstance {},
	hit: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	_3dPerson_2_dead: class extends self.I3DShapeInstance {},
	person_2_dead_mask: class extends self.ISpriteInstance {},
	_3dPerson_1_dead: class extends self.I3DShapeInstance {},
	person_1_dead_mask: class extends self.ISpriteInstance {},
	person_3_ctrl: class extends self.ISpriteInstance {},
	Person_3: class extends self.ISpriteInstance {},
	person_3_dead_mask: class extends self.ISpriteInstance {},
	_3dPerson_3: class extends self.I3DShapeInstance {},
	_3dPerson_3_dead: class extends self.I3DShapeInstance {},
	person_4_ctrl: class extends self.ISpriteInstance {},
	Person_4: class extends self.ISpriteInstance {},
	person_4_dead_mask: class extends self.ISpriteInstance {},
	_3dPerson_4: class extends self.I3DShapeInstance {},
	_3dPerson_4_dead: class extends self.I3DShapeInstance {},
	Person_5: class extends self.ISpriteInstance {},
	person_5_dead_mask: class extends self.ISpriteInstance {},
	person_5_ctrl: class extends self.ISpriteInstance {},
	_3dPerson_5: class extends self.I3DShapeInstance {},
	_3dPerson_5_dead: class extends self.I3DShapeInstance {},
	guard: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	sacco: class extends self.ISpriteInstance {},
	sacco_dead: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	sgabello: class extends self.ISpriteInstance {},
	bloodSpot: class extends self.ISpriteInstance {},
	GameControl: class extends self.ISpriteInstance {},
	Sfondo: class extends self.ISpriteInstance {},
	Lampada: class extends self.ISpriteInstance {},
	lamp_light: class extends self.ISpriteInstance {},
	lamp_front: class extends self.ISpriteInstance {},
	bloodspot2: class extends self.ISpriteInstance {},
	Clock: class extends self.ISpriteInstance {},
	Lancetta: class extends self.ISpriteInstance {},
	Clock2: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	interrogatio_wall: class extends self.ISpriteInstance {},
	fader: class extends self.ISpriteInstance {},
	ui_Hint_game: class extends self.ISpriteInstance {},
	ui_Play: class extends self.ISpriteInstance {},
	darkner: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	ui_barra: class extends self.ISpriteInstance {},
	ui_triangle: class extends self.ISpriteInstance {},
	ui_pointer: class extends self.ISpriteInstance {},
	trigger: class extends self.ISpriteInstance {},
	ui_bar: class extends self.ISpriteInstance {},
	o_paint: class extends self.ISpriteInstance {},
	o_vario: class extends self.ISpriteInstance {},
	ui_hp: class extends self.ITiledBackgroundInstance {},
	heart_full: class extends self.ISpriteInstance {},
	person_6_ctrl: class extends self.ISpriteInstance {},
	Person_6: class extends self.ISpriteInstance {},
	person_6_dead_mask: class extends self.ISpriteInstance {},
	_3dPerson_6: class extends self.I3DShapeInstance {},
	_3dPerson_6_dead: class extends self.I3DShapeInstance {},
	ui_gameOver: class extends self.ISpriteInstance {},
	ui_YouWin: class extends self.ISpriteInstance {},
	Person_7: class extends self.ISpriteInstance {},
	Person_7_dead_mask: class extends self.ISpriteInstance {},
	person_7_ctrl: class extends self.ISpriteInstance {},
	_3dPerson_7: class extends self.I3DShapeInstance {},
	_3dPerson_7_dead: class extends self.I3DShapeInstance {},
	_3D_paint_1: class extends self.I3DShapeInstance {},
	_3D_paint_2: class extends self.I3DShapeInstance {},
	_3D_paint_3: class extends self.I3DShapeInstance {},
	_3D_paint_4: class extends self.I3DShapeInstance {},
	_3D_paint_5: class extends self.I3DShapeInstance {},
	_3D_paint_6: class extends self.I3DShapeInstance {},
	_3D_paint_7: class extends self.I3DShapeInstance {},
	_3D_paint_8: class extends self.I3DShapeInstance {},
	_3D_paint_9: class extends self.I3DShapeInstance {},
	_3D_paint_10: class extends self.I3DShapeInstance {},
	_3D_paint_11: class extends self.I3DShapeInstance {},
	_3D_paint_12: class extends self.I3DShapeInstance {},
	_3D_paint_13: class extends self.I3DShapeInstance {},
	_3D_door: class extends self.I3DShapeInstance {},
	_3D_exit: class extends self.I3DShapeInstance {},
	person_8_ctrl: class extends self.ISpriteInstance {},
	_3dPerson_8: class extends self.I3DShapeInstance {},
	_3dPerson_8_dead: class extends self.I3DShapeInstance {},
	Person_8: class extends self.ISpriteInstance {},
	Person_8_dead_mask: class extends self.ISpriteInstance {},
	person_9_ctrl: class extends self.ISpriteInstance {},
	Person_9: class extends self.ISpriteInstance {},
	Person_9_dead_mask: class extends self.ISpriteInstance {},
	_3dPerson_9: class extends self.I3DShapeInstance {},
	_3dPerson_9_dead: class extends self.I3DShapeInstance {},
	person_10_ctrl: class extends self.ISpriteInstance {},
	Person_10: class extends self.ISpriteInstance {},
	Person_10_dead_mask: class extends self.ISpriteInstance {},
	_3dPerson_10: class extends self.I3DShapeInstance {},
	_3dPerson_10_dead: class extends self.I3DShapeInstance {},
	person_11_ctrl: class extends self.ISpriteInstance {},
	Person_11: class extends self.ISpriteInstance {},
	Person_11_dead_mask: class extends self.ISpriteInstance {},
	_3dPerson_11: class extends self.I3DShapeInstance {},
	_3dPerson_11_dead: class extends self.I3DShapeInstance {},
	Person_12: class extends self.ISpriteInstance {},
	Person_12_dead_mask: class extends self.ISpriteInstance {},
	person_12_ctrl: class extends self.ISpriteInstance {},
	_3dPerson_12: class extends self.I3DShapeInstance {},
	_3dPerson_12_dead: class extends self.I3DShapeInstance {},
	person_13_ctrl: class extends self.ISpriteInstance {},
	Person_13: class extends self.ISpriteInstance {},
	Person_13_dead_mask: class extends self.ISpriteInstance {},
	_3dPerson_13: class extends self.I3DShapeInstance {},
	_3dPerson_13_dead: class extends self.I3DShapeInstance {},
	Person_14: class extends self.ISpriteInstance {},
	Person_14_dead_mask: class extends self.ISpriteInstance {},
	person_14_ctrl: class extends self.ISpriteInstance {},
	_3dPerson_14: class extends self.I3DShapeInstance {},
	_3dPerson_14_dead: class extends self.I3DShapeInstance {},
	person_15_ctrl: class extends self.ISpriteInstance {},
	Person_15: class extends self.ISpriteInstance {},
	Person_15_dead_mask: class extends self.ISpriteInstance {},
	_3dPerson_15: class extends self.I3DShapeInstance {},
	_3dPerson_15_dead: class extends self.I3DShapeInstance {},
	hint_level_: class extends self.ISpriteInstance {},
	_3D_paint_14: class extends self.I3DShapeInstance {},
	_3D_paint_15: class extends self.I3DShapeInstance {},
	_3D_paint_16: class extends self.I3DShapeInstance {},
	_3D_paint_17: class extends self.I3DShapeInstance {},
	_3D_paint_18: class extends self.I3DShapeInstance {},
	_3D_paint_19: class extends self.I3DShapeInstance {},
	_3D_paint_20: class extends self.I3DShapeInstance {},
	_3D_paint_21: class extends self.I3DShapeInstance {},
	_3D_paint_22: class extends self.I3DShapeInstance {},
	_3D_paint_23: class extends self.I3DShapeInstance {},
	Plant: class extends self.ISpriteInstance {},
	_3D_plant: class extends self.I3DShapeInstance {},
	wall_top: class extends self.ITiledBackgroundInstance {},
	bronzo: class extends self.ISpriteInstance {},
	_3D_statue: class extends self.I3DShapeInstance {},
	luogoInteresse: class extends self.ISpriteInstance {},
	Sacco_anim: class extends self.ISpriteInstance {},
	human_collapsed: class extends self.ISpriteInstance {},
	ui_center: class extends self.ISpriteInstance {},
	ui_ball: class extends self.ISpriteInstance {},
	ui_timesUp: class extends self.ISpriteInstance {},
	gioconda: class extends self.ISpriteInstance {},
	paint_anim: class extends self.ISpriteInstance {},
	splatter: class extends self.ISpriteInstance {},
	ui_audio: class extends self.ISpriteInstance {},
	bg_sacco: class extends self.ISpriteInstance {},
	color: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	ui_titolo: class extends self.ISpriteInstance {},
	wall2: class extends self.ITiledBackgroundInstance {},
	ui_lev_1: class extends self.ISpriteInstance {},
	ui_lev_2: class extends self.ISpriteInstance {},
	ui_lev_3: class extends self.ISpriteInstance {},
	ui_QUADRO: class extends self.ISpriteInstance {},
	ui_levelSelect: class extends self.ISpriteInstance {},
	cordoni: class extends self.ISpriteInstance {},
	eff_hit: class extends self.ISpriteInstance {},
	Vernice: class extends self.ISpriteInstance {},
	sun: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	ui_skip: class extends self.ISpriteInstance {},
	ui_tutorial: class extends self.ISpriteInstance {},
	ui_hint: class extends self.ISpriteInstance {},
	letterM: class extends self.ISpriteInstance {},
	hint_level_2: class extends self.ISpriteInstance {},
	hint_level_3: class extends self.ISpriteInstance {},
	Aimpad: class extends self.ISpriteInstance {},
	Aimstick: class extends self.ISpriteInstance {},
	Joypad: class extends self.ISpriteInstance {},
	Joystick: class extends self.ISpriteInstance {},
	ui_attack: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	btn_rewarded: class extends self.ISpriteInstance {},
	UI_extraTime: class extends self.ISpriteInstance {},
	bg_black: class extends self.ITiledBackgroundInstance {},
	cover_PI: class extends self.ISpriteInstance {},
	cover_Dev: class extends self.ISpriteInstance {},
	cover_Ti: class extends self.ISpriteInstance {},
	cover_Ball_Red: class extends self.ISpriteInstance {},
	cover_Ball_blu: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	People: class extends self.I3DShapeInstance {},
	People_mask: class extends self.ISpriteInstance {},
	People_controls: class extends self.ISpriteInstance {},
	uis: class extends self.ISpriteInstance {},
	Objects: class extends self.ISpriteInstance {},
	Levels: class extends self.ISpriteInstance {},
	buttons: class extends self.ISpriteInstance {},
	TouchControls: class extends self.ISpriteInstance {},
	Logos: class extends self.ISpriteInstance {},
	CoverScreen: class extends self.ISpriteInstance {},
	Cover: class extends self.ISpriteInstance {}
}