const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.DrawingCanvas,
		C3.Plugins.TiledBg,
		C3.Behaviors.custom,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.sliderbar,
		C3.Plugins.Spritefont2,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.filechooser,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Behaviors.scrollto,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Fade,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.DrawingCanvas.Acts.SetSize,
		C3.Plugins.DrawingCanvas.Acts.SetY,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.filechooser.Acts.Click,
		C3.Plugins.filechooser.Cnds.OnChanged,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.filechooser.Exps.FileURLAt,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.OnURLLoaded,
		C3.Plugins.DrawingCanvas.Acts.ClearCanvas,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.sliderbar.Cnds.OnChanging,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.DrawingCanvas.Cnds.OnSavedImage,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.DrawingCanvas.Exps.SavedImageURL,
		C3.Plugins.DrawingCanvas.Acts.SaveImage,
		C3.Behaviors.custom.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Fade.Acts.StartFade
	];
};
self.C3_JsPropNameTable = [
	{DrawingCanvas: 0},
	{Custom: 0},
	{bg: 0},
	{Touch: 0},
	{Tween: 0},
	{brush: 0},
	{color_R: 0},
	{Color_G: 0},
	{Color_B: 0},
	{Saturation: 0},
	{Value: 0},
	{size: 0},
	{isSelected: 0},
	{gameController: 0},
	{SliderBar_size: 0},
	{SliderBar_saturation: 0},
	{SliderBar_value: 0},
	{draw_: 0},
	{R: 0},
	{G: 0},
	{B: 0},
	{isTouched: 0},
	{color: 0},
	{SpriteFont: 0},
	{btn_reward: 0},
	{Browser: 0},
	{Mouse: 0},
	{Download: 0},
	{FileChooser: 0},
	{ImagePicker: 0},
	{Sine: 0},
	{Selector: 0},
	{audioOn: 0},
	{barsHorizontal: 0},
	{Audio: 0},
	{Title: 0},
	{fader: 0},
	{draw_menu: 0},
	{mask: 0},
	{ui_play: 0},
	{ui_left: 0},
	{ui_right: 0},
	{ScrollTo: 0},
	{MoveTo: 0},
	{camera: 0},
	{Sprite: 0},
	{txt_drawing_select: 0},
	{bg_black: 0},
	{cover_PI: 0},
	{Fade: 0},
	{cover_Dev: 0},
	{cover_Ti: 0},
	{cover_Ball_Red: 0},
	{cover_Ball_blu: 0},
	{logocom: 0},
	{WeeGooSDK: 0},
	{Buttons: 0},
	{Sliders: 0},
	{Covers: 0},
	{SketchNum: 0},
	{PointerX: 0},
	{PointerY: 0},
	{isSound: 0}
];

self.InstanceType = {
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	bg: class extends self.ITiledBackgroundInstance {},
	Touch: class extends self.IInstance {},
	brush: class extends self.ISpriteInstance {},
	gameController: class extends self.ISpriteInstance {},
	SliderBar_size: class extends self.ISliderBarInstance {},
	SliderBar_saturation: class extends self.ISliderBarInstance {},
	SliderBar_value: class extends self.ISliderBarInstance {},
	draw_: class extends self.ISpriteInstance {},
	color: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	btn_reward: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Download: class extends self.ISpriteInstance {},
	FileChooser: class extends self.IWorldInstance {},
	ImagePicker: class extends self.ISpriteInstance {},
	Selector: class extends self.ISpriteInstance {},
	audioOn: class extends self.ISpriteInstance {},
	barsHorizontal: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Title: class extends self.ISpriteInstance {},
	fader: class extends self.ITiledBackgroundInstance {},
	draw_menu: class extends self.ISpriteInstance {},
	mask: class extends self.ISpriteInstance {},
	ui_play: class extends self.ISpriteInstance {},
	ui_left: class extends self.ISpriteInstance {},
	ui_right: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	txt_drawing_select: class extends self.ISpriteInstance {},
	bg_black: class extends self.ITiledBackgroundInstance {},
	cover_PI: class extends self.ISpriteInstance {},
	cover_Dev: class extends self.ISpriteInstance {},
	cover_Ti: class extends self.ISpriteInstance {},
	cover_Ball_Red: class extends self.ISpriteInstance {},
	cover_Ball_blu: class extends self.ISpriteInstance {},
	logocom: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	Buttons: class extends self.ISpriteInstance {},
	Sliders: class extends self.ISliderBarInstance {},
	Covers: class extends self.ISpriteInstance {}
}