const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Particles,
		C3.Behaviors.Fade,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.Destroy,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Particles.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Particles.Cnds.CompareX,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.Particles.Exps.Count,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Browser: 0},
	{LocalStorege: 0},
	{Audio: 0},
	{OrverLine: 0},
	{Tween: 0},
	{Circle_Purple: 0},
	{Circle_Green: 0},
	{Circle_Red: 0},
	{Circle_Blue: 0},
	{Circle_Orange: 0},
	{Circle_Yellow: 0},
	{Line_Green: 0},
	{Line_Blue: 0},
	{Line_Orange: 0},
	{Line_Purple: 0},
	{Line_Red: 0},
	{Line_Yellow: 0},
	{Shadow: 0},
	{Fade: 0},
	{P_Confetti: 0},
	{Rotate: 0},
	{Sine: 0},
	{Sine2: 0},
	{Confetti: 0},
	{Frame: 0},
	{YouWin: 0},
	{Stage: 0},
	{Finger: 0},
	{MoveLvl: 0},
	{Esmaecer: 0},
	{P_Confetti_Colors: 0},
	{ConfettiGreen: 0},
	{P_Confetti_Black: 0},
	{ConfettiBlack: 0},
	{Shadow2: 0},
	{Circle_Wave: 0},
	{Color: 0},
	{efx_touch: 0},
	{efx_touch_P: 0},
	{Error: 0},
	{Smoke: 0},
	{BtnAudioOff: 0},
	{BtnLevels: 0},
	{BtnMusicOff: 0},
	{BtnRestart: 0},
	{BtnNext_Left: 0},
	{BtnNext_Right: 0},
	{Number: 0},
	{Levels: 0},
	{BtnBack: 0},
	{btn_clear: 0},
	{BtnPlay: 0},
	{btn_more: 0},
	{btn_m: 0},
	{txt_nameLvl: 0},
	{txt_tutorial: 0},
	{txt_titleLvl: 0},
	{txt_NumberLvl: 0},
	{txt_title_nice: 0},
	{txt_reset: 0},
	{txt_reset2: 0},
	{StartX: 0},
	{StartY: 0},
	{Direction: 0},
	{bg_game: 0},
	{WeeGooSDK: 0},
	{F_Btns: 0},
	{F_line: 0},
	{F_Circles: 0},
	{F_Shake: 0},
	{prevX: 0},
	{prevY: 0},
	{CurrentCircle: 0},
	{Connected: 0},
	{Circle_Quantity: 0},
	{Overlaping: 0},
	{Completed_Level: 0},
	{Current_Level: 0},
	{Circle: 0},
	{Music: 0},
	{Sound: 0},
	{vChooseDi: 0},
	{vChooseFre: 0},
	{vChooseAniBlock: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorege: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Circle_Purple: class extends self.ISpriteInstance {},
	Circle_Green: class extends self.ISpriteInstance {},
	Circle_Red: class extends self.ISpriteInstance {},
	Circle_Blue: class extends self.ISpriteInstance {},
	Circle_Orange: class extends self.ISpriteInstance {},
	Circle_Yellow: class extends self.ISpriteInstance {},
	Line_Green: class extends self.ISpriteInstance {},
	Line_Blue: class extends self.ISpriteInstance {},
	Line_Orange: class extends self.ISpriteInstance {},
	Line_Purple: class extends self.ISpriteInstance {},
	Line_Red: class extends self.ISpriteInstance {},
	Line_Yellow: class extends self.ISpriteInstance {},
	Shadow: class extends self.ISpriteInstance {},
	P_Confetti: class extends self.IParticlesInstance {},
	Confetti: class extends self.ISpriteInstance {},
	Frame: class extends self.ISpriteInstance {},
	Fade: class extends self.ISpriteInstance {},
	YouWin: class extends self.ISpriteInstance {},
	Finger: class extends self.ISpriteInstance {},
	MoveLvl: class extends self.ISpriteInstance {},
	P_Confetti_Colors: class extends self.IParticlesInstance {},
	ConfettiGreen: class extends self.ISpriteInstance {},
	P_Confetti_Black: class extends self.IParticlesInstance {},
	ConfettiBlack: class extends self.ISpriteInstance {},
	Shadow2: class extends self.ISpriteInstance {},
	Circle_Wave: class extends self.ISpriteInstance {},
	Color: class extends self.ISpriteInstance {},
	efx_touch: class extends self.ISpriteInstance {},
	efx_touch_P: class extends self.IParticlesInstance {},
	Error: class extends self.ISpriteInstance {},
	Smoke: class extends self.ISpriteInstance {},
	BtnAudioOff: class extends self.ISpriteInstance {},
	BtnLevels: class extends self.ISpriteInstance {},
	BtnMusicOff: class extends self.ISpriteInstance {},
	BtnRestart: class extends self.ISpriteInstance {},
	BtnNext_Left: class extends self.ISpriteInstance {},
	BtnNext_Right: class extends self.ISpriteInstance {},
	Levels: class extends self.ISpriteInstance {},
	BtnBack: class extends self.ISpriteInstance {},
	btn_clear: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	btn_more: class extends self.ISpriteInstance {},
	btn_m: class extends self.ISpriteInstance {},
	txt_nameLvl: class extends self.ITextInstance {},
	txt_tutorial: class extends self.ITextInstance {},
	txt_titleLvl: class extends self.ITextInstance {},
	txt_NumberLvl: class extends self.ITextInstance {},
	txt_title_nice: class extends self.ITextInstance {},
	txt_reset: class extends self.ITextInstance {},
	txt_reset2: class extends self.ITextInstance {},
	bg_game: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	F_Btns: class extends self.ISpriteInstance {},
	F_line: class extends self.ISpriteInstance {},
	F_Circles: class extends self.ISpriteInstance {},
	F_Shake: class extends self.ISpriteInstance {}
}