const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Rotate,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Behaviors.scrollto,
		C3.Behaviors.Timer,
		C3.Plugins.TiledBg,
		C3.Behaviors.EightDir,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.solid,
		C3.Behaviors.Fade,
		C3.Behaviors.Flash,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Pathfinding.Acts.AddObstacle,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.UnloadUnusedTextures,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Exps.AnimationSpeed,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.canvastolayerx,
		C3.Plugins.Touch.Exps.AbsoluteXForID,
		C3.Plugins.Touch.Exps.AbsoluteYForID,
		C3.Plugins.System.Exps.canvastolayery,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.TouchID,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.EightDir.Acts.SetVectorX,
		C3.Behaviors.EightDir.Acts.SetVectorY,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.Sin.Exps.Value,
		C3.Plugins.System.Exps.tickcount,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Exps.len,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Pathfinding.Acts.Stop,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.TiledBg.Cnds.PickDistance,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.EightDir.Acts.Stop,
		C3.Behaviors.Pathfinding.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.SetEnabled,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.SortZOrderByInstVar,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Cnds.IsEnabled,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Behaviors.Pathfinding.Acts.RegenerateMap,
		C3.Behaviors.Pathfinding.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.Pathfinding.Cnds.OnArrived,
		C3.Plugins.Sprite.Cnds.CompareAnimSpeed,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Behaviors.Pathfinding.Cnds.IsMoving,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Pathfinding.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Sprite.Exps.LayerNumber,
		C3.Plugins.System.Exps.layertocanvasx,
		C3.Plugins.System.Exps.layertocanvasy,
		C3.Plugins.System.Acts.SetLayerEffectEnabled,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Behaviors.Sin.Cnds.CompareMagnitude,
		C3.Behaviors.Sin.Exps.Magnitude,
		C3.Behaviors.Sin.Cnds.ComparePeriod,
		C3.Behaviors.Sin.Exps.Period,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.PickAll,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.System.Acts.SetLayerParallax,
		C3.Plugins.System.Exps.layerparallaxx,
		C3.Plugins.System.Exps.layerparallaxy,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.Mouse.Cnds.IsOverObject
	];
};
self.C3_JsPropNameTable = [
	{ID: 0},
	{Pin: 0},
	{PlayerShadow: 0},
	{Sprite4: 0},
	{StatikShadow: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{PlatformInfo: 0},
	{LocalStorage: 0},
	{Rotate: 0},
	{Tween: 0},
	{CountDown: 0},
	{Sine: 0},
	{CountDownTxt: 0},
	{Game_Txt: 0},
	{JumpButton: 0},
	{Menu_Button: 0},
	{SangPad: 0},
	{Bullet: 0},
	{Qualified: 0},
	{Sprite8: 0},
	{Menu_Text: 0},
	{conAngle: 0},
	{XP: 0},
	{YP: 0},
	{SangStick: 0},
	{Sprite6: 0},
	{ScrollTo: 0},
	{Timer: 0},
	{Cam: 0},
	{CheckPoint: 0},
	{MoveTouch: 0},
	{Path: 0},
	{path: 0},
	{True: 0},
	{DestionationUID: 0},
	{TargetPath: 0},
	{"8Direction": 0},
	{Pathfinding: 0},
	{PlayerBox: 0},
	{HeightZ: 0},
	{Floor: 0},
	{Picked: 0},
	{Frame: 0},
	{Holder: 0},
	{Shaking: 0},
	{Solid: 0},
	{Platform: 0},
	{NotSort: 0},
	{Ycoord: 0},
	{reversed: 0},
	{Fade: 0},
	{Obstacles: 0},
	{isJumping: 0},
	{Bounciness: 0},
	{JumpHeight: 0},
	{isAnimReversed: 0},
	{PushAngle: 0},
	{HeightZStart: 0},
	{isFell: 0},
	{ToCheckpoint: 0},
	{Flash: 0},
	{Player: 0},
	{TiledBackground2: 0},
	{Sprite5: 0},
	{StatikEnvironment: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite: 0},
	{Drop: 0},
	{FinishLine: 0},
	{PlayerIndicator: 0},
	{TiledBackground: 0},
	{Transition: 0},
	{WeeGooSDK: 0},
	{Family1: 0},
	{EnemyLeft: 0},
	{GameOver: 0},
	{Hue: 0},
	{Radius: 0},
	{dist: 0},
	{cangle: 0},
	{TouchID: 0},
	{TouchID2: 0},
	{ScaleXParam: 0},
	{ScaleYparam: 0},
	{TouchIDD: 0},
	{CorrectParallax: 0},
	{CollisionsDisabled: 0},
	{PrepareCountdown: 0},
	{Status: 0},
	{First: 0},
	{Second: 0},
	{third: 0},
	{fourth: 0},
	{ResultFrame: 0},
	{Control_Method: 0},
	{Phase: 0}
];

self.InstanceType = {
	PlayerShadow: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	StatikShadow: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	CountDown: class extends self.ISpriteInstance {},
	CountDownTxt: class extends self.ISpriteInstance {},
	Game_Txt: class extends self.ITextInstance {},
	JumpButton: class extends self.ISpriteInstance {},
	Menu_Button: class extends self.ISpriteInstance {},
	SangPad: class extends self.ISpriteInstance {},
	Qualified: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Menu_Text: class extends self.ITextInstance {},
	SangStick: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Cam: class extends self.ISpriteInstance {},
	CheckPoint: class extends self.ISpriteInstance {},
	MoveTouch: class extends self.ITiledBackgroundInstance {},
	path: class extends self.ITiledBackgroundInstance {},
	PlayerBox: class extends self.ISpriteInstance {},
	Platform: class extends self.ISpriteInstance {},
	Obstacles: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	StatikEnvironment: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Drop: class extends self.ISpriteInstance {},
	FinishLine: class extends self.ISpriteInstance {},
	PlayerIndicator: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Transition: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	Family1: class extends self.ISpriteInstance {}
}