const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.DrawingCanvas,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Plugins.filechooser,
		C3.Plugins.Button,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Plugins.AJAX,
		C3.Plugins.BinaryData,
		C3.Plugins.Share,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Audio,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.DrawingCanvas.Exps.BBoxLeft,
		C3.Plugins.DrawingCanvas.Exps.PixelScale,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.DrawingCanvas.Exps.BBoxTop,
		C3.JavaScriptInEvents["Bucket-Paint_Event12_Act5"],
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.JavaScriptInEvents["Bucket-Paint_Event16_Act1"],
		C3.Plugins.filechooser.Cnds.OnChanged,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.DrawingCanvas.Exps.X,
		C3.Plugins.DrawingCanvas.Exps.Width,
		C3.Plugins.DrawingCanvas.Exps.Y,
		C3.Plugins.DrawingCanvas.Exps.Height,
		C3.Plugins.DrawingCanvas.Acts.ClearCanvas,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.filechooser.Exps.FileURLAt,
		C3.Plugins.filechooser.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnURLLoaded,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.System.Cnds.OnCanvasSnapshot,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.WGSDK.Cnds.RewardGranted,
		C3.Plugins.Sprite.Cnds.CompareFrame
	];
};
self.C3_JsPropNameTable = [
	{DrawingCanvas: 0},
	{Mouse: 0},
	{Browser: 0},
	{Image: 0},
	{R: 0},
	{G: 0},
	{B: 0},
	{ColorSprite: 0},
	{Frame: 0},
	{FileChooser: 0},
	{type: 0},
	{LoadButton: 0},
	{BrushSelector: 0},
	{ButtonRestart: 0},
	{BrushSelect: 0},
	{ColorSelect: 0},
	{CanvasTemp: 0},
	{Stencil: 0},
	{Canvas: 0},
	{Button: 0},
	{BG: 0},
	{Touch: 0},
	{Paint: 0},
	{ColorSelector: 0},
	{Keyboard: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Background: 0},
	{homebtn: 0},
	{pozadinazvuk: 0},
	{BSound: 0},
	{Sprite6: 0},
	{ponovo1: 0},
	{Sine: 0},
	{ponovo: 0},
	{pozadinabijela: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{SpriteFont: 0},
	{btn_camera: 0},
	{ScreenshotSprite: 0},
	{sharebtn: 0},
	{downloadbtn: 0},
	{sharebtn2: 0},
	{AJAX: 0},
	{ShareButton: 0},
	{DownloadButton: 0},
	{TakeScreenshotButton: 0},
	{BinaryData: 0},
	{Share: 0},
	{pozadinazvuk2: 0},
	{pozadinazvuk3: 0},
	{DragDrop: 0},
	{stamp: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{PRVABUCKET: 0},
	{PRVABRUSH: 0},
	{DRUGABUCKET: 0},
	{DRUGABRUSH: 0},
	{TRECABRUSH: 0},
	{TRECABUCKET: 0},
	{CETVRTABUCKET: 0},
	{CETVRTABRUSH: 0},
	{PETABRUSH: 0},
	{PETABUCKET: 0},
	{SESTABUCKET: 0},
	{SESTABRUSH: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Audio: 0},
	{REWARDMEDO: 0},
	{REWARDDJECAK: 0},
	{okidac: 0},
	{moregames: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{LoadButton2: 0},
	{kocka2: 0},
	{riba2: 0},
	{kanta: 0},
	{grasdugme: 0},
	{grassplavadugme: 0},
	{kucadugme: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Image2: 0},
	{Sprite32: 0},
	{slike1: 0},
	{slike2: 0},
	{slike3: 0},
	{slike4: 0},
	{slike5: 0},
	{slike6: 0},
	{slike7: 0},
	{slike8: 0},
	{slike9: 0},
	{Sprite33: 0},
	{slike10: 0},
	{Sprite34: 0},
	{slike11: 0},
	{zadnja: 0},
	{predzadnja: 0},
	{addtimereklama: 0},
	{reklamakocka: 0},
	{Sprite7: 0},
	{Sprite14: 0},
	{Image3: 0},
	{Image4: 0},
	{trokut: 0},
	{knjiga: 0},
	{BG_Table: 0},
	{olovka: 0},
	{olovka1: 0},
	{zoomin: 0},
	{zoomout: 0},
	{Sprite15: 0},
	{PLAY: 0},
	{more: 0},
	{Sprite16: 0},
	{slike12: 0},
	{Sprite17: 0},
	{Image5: 0},
	{Image6: 0},
	{Sprite18: 0},
	{WeeGooSDK: 0},
	{addtimereklama2: 0},
	{buttons: 0},
	{slike: 0},
	{x: 0},
	{y: 0},
	{r: 0},
	{g: 0},
	{b: 0},
	{tolerance: 0},
	{OffsetSpeed: 0},
	{MAX_IMAGE_SIZE: 0},
	{s: 0},
	{sound: 0},
	{SoundEf: 0}
];

self.InstanceType = {
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	Mouse: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Image: class extends self.ISpriteInstance {},
	ColorSprite: class extends self.ISpriteInstance {},
	Frame: class extends self.ISpriteInstance {},
	FileChooser: class extends self.IFileChooserInstance {},
	LoadButton: class extends self.IButtonInstance {},
	BrushSelector: class extends self.ISpriteInstance {},
	ButtonRestart: class extends self.IButtonInstance {},
	BrushSelect: class extends self.ISpriteInstance {},
	ColorSelect: class extends self.ISpriteInstance {},
	CanvasTemp: class extends self.IDrawingCanvasInstance {},
	Stencil: class extends self.ISpriteInstance {},
	Canvas: class extends self.IDrawingCanvasInstance {},
	Button: class extends self.IButtonInstance {},
	BG: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Paint: class extends self.ISpriteInstance {},
	ColorSelector: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	homebtn: class extends self.ISpriteInstance {},
	pozadinazvuk: class extends self.ISpriteInstance {},
	BSound: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	ponovo1: class extends self.ISpriteInstance {},
	ponovo: class extends self.ISpriteInstance {},
	pozadinabijela: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	btn_camera: class extends self.ISpriteInstance {},
	ScreenshotSprite: class extends self.ISpriteInstance {},
	sharebtn: class extends self.ISpriteInstance {},
	downloadbtn: class extends self.ISpriteInstance {},
	sharebtn2: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	ShareButton: class extends self.IButtonInstance {},
	DownloadButton: class extends self.IButtonInstance {},
	TakeScreenshotButton: class extends self.IButtonInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	Share: class extends self.IInstance {},
	pozadinazvuk2: class extends self.ISpriteInstance {},
	pozadinazvuk3: class extends self.ISpriteInstance {},
	stamp: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	PRVABUCKET: class extends self.ISpriteInstance {},
	PRVABRUSH: class extends self.ISpriteInstance {},
	DRUGABUCKET: class extends self.ISpriteInstance {},
	DRUGABRUSH: class extends self.ISpriteInstance {},
	TRECABRUSH: class extends self.ISpriteInstance {},
	TRECABUCKET: class extends self.ISpriteInstance {},
	CETVRTABUCKET: class extends self.ISpriteInstance {},
	CETVRTABRUSH: class extends self.ISpriteInstance {},
	PETABRUSH: class extends self.ISpriteInstance {},
	PETABUCKET: class extends self.ISpriteInstance {},
	SESTABUCKET: class extends self.ISpriteInstance {},
	SESTABRUSH: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	REWARDMEDO: class extends self.ISpriteInstance {},
	REWARDDJECAK: class extends self.ISpriteInstance {},
	okidac: class extends self.ISpriteInstance {},
	moregames: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	LoadButton2: class extends self.IButtonInstance {},
	kocka2: class extends self.ISpriteInstance {},
	riba2: class extends self.ISpriteInstance {},
	kanta: class extends self.ISpriteInstance {},
	grasdugme: class extends self.ISpriteInstance {},
	grassplavadugme: class extends self.ISpriteInstance {},
	kucadugme: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Image2: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	slike1: class extends self.ISpriteInstance {},
	slike2: class extends self.ISpriteInstance {},
	slike3: class extends self.ISpriteInstance {},
	slike4: class extends self.ISpriteInstance {},
	slike5: class extends self.ISpriteInstance {},
	slike6: class extends self.ISpriteInstance {},
	slike7: class extends self.ISpriteInstance {},
	slike8: class extends self.ISpriteInstance {},
	slike9: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	slike10: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	slike11: class extends self.ISpriteInstance {},
	zadnja: class extends self.ISpriteInstance {},
	predzadnja: class extends self.ISpriteInstance {},
	addtimereklama: class extends self.ISpriteInstance {},
	reklamakocka: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Image3: class extends self.ISpriteInstance {},
	Image4: class extends self.ISpriteInstance {},
	trokut: class extends self.ISpriteInstance {},
	knjiga: class extends self.ISpriteInstance {},
	BG_Table: class extends self.ISpriteInstance {},
	olovka: class extends self.ISpriteInstance {},
	olovka1: class extends self.ISpriteInstance {},
	zoomin: class extends self.ISpriteInstance {},
	zoomout: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	PLAY: class extends self.ISpriteInstance {},
	more: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	slike12: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Image5: class extends self.ISpriteInstance {},
	Image6: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	addtimereklama2: class extends self.ISpriteInstance {},
	buttons: class extends self.ISpriteInstance {},
	slike: class extends self.ISpriteInstance {}
}