const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Function,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.ppstudio_ga4,
		C3.Plugins.WGSDK,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Behaviors.scrollto,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Flash,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Browser.Acts.ExecJs,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.ppstudio_ga4.Acts.GASendEvent,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.RotateCounterclockwise,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.ppstudio_ga4.Acts.InitGA,
		C3.Plugins.Spritefont2.Cnds.PickByUID,
		C3.Plugins.Browser.Acts.Close
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Browser: 0},
	{Function: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{PlatformInfo: 0},
	{Touch: 0},
	{Keyboard: 0},
	{GA4: 0},
	{WeeGooSDK: 0},
	{Sine: 0},
	{Back_bubble: 0},
	{backBtn: 0},
	{bg2: 0},
	{btn_Home: 0},
	{btn_Play: 0},
	{btn_Volume: 0},
	{ID: 0},
	{GameControl: 0},
	{Line: 0},
	{score: 0},
	{Bullet: 0},
	{Shape: 0},
	{ScrollTo: 0},
	{Shape_icon: 0},
	{Scale: 0},
	{increase: 0},
	{Decrease: 0},
	{spr_Effect: 0},
	{spr_GameTitle: 0},
	{spr_Score: 0},
	{spr_Touch_to_Start: 0},
	{Sprite: 0},
	{SpriteFont: 0},
	{Flash: 0},
	{Thunder: 0},
	{btn: 0},
	{StartGame: 0},
	{Gameover: 0},
	{HighScore: 0},
	{Score: 0},
	{IsScreenRotate: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	GA4: class extends C3.Plugins.ppstudio_ga4.Instance {},
	WeeGooSDK: class extends C3.Plugins.WGSDK.Instance {},
	Back_bubble: class extends self.ISpriteInstance {},
	backBtn: class extends self.ISpriteInstance {},
	bg2: class extends self.ISpriteInstance {},
	btn_Home: class extends self.ISpriteInstance {},
	btn_Play: class extends self.ISpriteInstance {},
	btn_Volume: class extends self.ISpriteInstance {},
	GameControl: class extends self.ISpriteInstance {},
	Line: class extends self.ISpriteInstance {},
	score: class extends self.ISpriteInstance {},
	Shape: class extends self.ISpriteInstance {},
	Shape_icon: class extends self.ISpriteInstance {},
	spr_Effect: class extends self.ISpriteInstance {},
	spr_GameTitle: class extends self.ISpriteInstance {},
	spr_Score: class extends self.ISpriteInstance {},
	spr_Touch_to_Start: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Thunder: class extends self.ISpriteInstance {},
	btn: class extends self.ISpriteInstance {}
}