const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Camera3D,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Keyboard,
		C3.Plugins.Shape3D,
		C3.Behaviors.Tween,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.Car,
		C3.Behaviors.Timer,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Rotate,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Audio,
		C3.Behaviors.Pin,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.WGSDK,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.AdvancedRandom.Acts.CreatePermutationTable,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Shape3D.Acts.SetAngle,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Behaviors.Car.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Plugins.Shape3D.Acts.SetWidth,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Shape3D.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Camera3D.Exps.CameraX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Camera3D.Exps.CameraY,
		C3.Plugins.Camera3D.Exps.CameraZ,
		C3.Plugins.Camera3D.Exps.LookZ,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Car.Acts.SimulateControl,
		C3.Behaviors.Car.Cnds.CompareSpeed,
		C3.Behaviors.Car.Acts.SetSpeed,
		C3.Plugins.System.Exps.max,
		C3.Behaviors.Car.Exps.Speed,
		C3.Behaviors.Car.Exps.MaxSpeed,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Car.Acts.SetSteerSpeed,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Behaviors.Car.Acts.SetAcceleration,
		C3.Behaviors.Car.Acts.SetMaxSpeed,
		C3.Behaviors.Car.Acts.SetDeceleration,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Shape3D.Cnds.PickChildren,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.AdvancedRandom.Exps.Permutation,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.Shape3D.Acts.SetDefaultColor,
		C3.Plugins.Spritefont2.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Sin.Exps.Value,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Shape3D.Acts.SetEffectParam,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Shape3D.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Plugins.Shape3D.Cnds.OnCreated,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.Spritefont2.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Shape3D.Acts.SetInstanceVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Shape3D.Acts.SetSize,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.Shape3D.Cnds.IsOverlapping,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.Shape3D.Acts.SetTowardPosition,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Shape3D.Exps.ZHeight,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Shape3D.Exps.Angle,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Shape3D.Acts.SetZHeight,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.LocalStorage.Cnds.OnAllGetsComplete,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.GoToLayoutByName
	];
};
self.C3_JsPropNameTable = [
	{"3DCamera": 0},
	{AdvancedRandom: 0},
	{Keyboard: 0},
	{Tween: 0},
	{Corn: 0},
	{CornTex: 0},
	{CornWall: 0},
	{CornWallTex0: 0},
	{CornWallTex1: 0},
	{CornWallTex2: 0},
	{Solid: 0},
	{FenceModel: 0},
	{FenceTex: 0},
	{FinishLine: 0},
	{OutsideTerrain: 0},
	{Sky: 0},
	{SmashedCorn: 0},
	{StartLine: 0},
	{TerrainModel: 0},
	{TerrainTex0: 0},
	{TerrainTex1: 0},
	{TerrainTex2: 0},
	{Sine: 0},
	{FenceModel2: 0},
	{SmokeTex: 0},
	{T_Engine_Bottom: 0},
	{T_Engine_Front: 0},
	{T_Engine_Right: 0},
	{T_Engine_Top: 0},
	{T_Main_Bottom: 0},
	{T_Main_Front: 0},
	{T_Main_Left: 0},
	{T_Main_Right: 0},
	{T_Main_Top: 0},
	{T_WheelLeft_Bottom: 0},
	{T_WheelLeft_Front: 0},
	{T_WheelLeft_Left: 0},
	{T_WheelLeft_Right: 0},
	{T_WheelLeft_Top: 0},
	{T_WheelRight_Bottom: 0},
	{T_WheelRight_Front: 0},
	{T_WheelRight_Left: 0},
	{T_WheelRight_Right: 0},
	{T_WheelRight_Top: 0},
	{T_WheelSmallLeft_Bottom: 0},
	{T_WheelSmallLeft_Front: 0},
	{T_WheelSmallLeft_Left: 0},
	{T_WheelSmallLeft_Right: 0},
	{T_WheelSmallLeft_Top: 0},
	{T_WheelSmallRight_Bottom: 0},
	{T_WheelSmallRight_Front: 0},
	{T_WheelSmallRight_Left: 0},
	{T_WheelSmallRight_Right: 0},
	{T_WheelSmallRight_Top: 0},
	{SmokeModel: 0},
	{stoppedAtX: 0},
	{stoppedAtY: 0},
	{tractorCaught: 0},
	{tractorSkin: 0},
	{Car: 0},
	{TractorBase: 0},
	{TractorBigWheelLeft: 0},
	{TractorBigWheelRight: 0},
	{TractorBody: 0},
	{TractorEngine: 0},
	{TractorExhaust: 0},
	{spawnSmoke: 0},
	{Timer: 0},
	{TractorExhaustTop: 0},
	{TractorLight: 0},
	{TractorNumber: 0},
	{TractorNumberTex: 0},
	{TractorSmallWheelLeft: 0},
	{TractorSmallWheelRight: 0},
	{action: 0},
	{AIPlayer: 0},
	{GameTimer: 0},
	{Player: 0},
	{Minimap: 0},
	{StationaryGauge: 0},
	{StationaryLimit: 0},
	{StationaryPointer: 0},
	{StopLights: 0},
	{TextGauge: 0},
	{TextMinimap: 0},
	{Fader: 0},
	{TextTutorial: 0},
	{TextGameOver: 0},
	{Scarecrow: 0},
	{ScarecrowHatBase: 0},
	{ScarecrowHatTop: 0},
	{ScarecrowHead: 0},
	{ScarecrowLeftArm: 0},
	{ScarecrowRightArm: 0},
	{ScarecrowTorso: 0},
	{tractor: 0},
	{Rotate: 0},
	{UFO: 0},
	{UFOAbduction: 0},
	{UFOAbductionTex: 0},
	{UFOBottom: 0},
	{UFOSideTex: 0},
	{UFOTop: 0},
	{Play: 0},
	{Sprite7: 0},
	{Sprite: 0},
	{Touch: 0},
	{Sprite2: 0},
	{more: 0},
	{Sprite4: 0},
	{upute: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Home: 0},
	{Again: 0},
	{Sprite8: 0},
	{winner: 0},
	{lijevo: 0},
	{desno: 0},
	{vozi: 0},
	{nazad: 0},
	{PlatformInfo: 0},
	{BSound: 0},
	{Audio: 0},
	{Home2: 0},
	{NEXTLEVEL: 0},
	{"3DShape": 0},
	{Open: 0},
	{Level: 0},
	{LevelsBlock: 0},
	{select: 0},
	{Pin: 0},
	{SpriteFont123: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{LevelsText: 0},
	{skip: 0},
	{Browser: 0},
	{WeeGooSDK: 0},
	{mobilni: 0},
	{LastLevel: 0},
	{WIN: 0},
	{LevelComplete: 0},
	{LAST_LEVEL: 0},
	{sound: 0},
	{SoundEf: 0},
	{tutorial: 0},
	{difficulty: 0},
	{pointerChallenge: 0},
	{pointerSide: 0},
	{pointerSpeed: 0},
	{pointerCounterSpeed: 0},
	{numOfDirChanges: 0},
	{movementChecking: 0},
	{CAM_DIST: 0},
	{CAM_SPEED: 0},
	{P_BRAKE_STRENGTH: 0},
	{tractorUID: 0},
	{skin: 0},
	{speed: 0},
	{animation: 0},
	{mStart: 0},
	{mEnd: 0},
	{start: 0},
	{end: 0},
	{type: 0}
];

self.InstanceType = {
	_3DCamera: class extends self.IInstance {},
	AdvancedRandom: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Corn: class extends self.I3DShapeInstance {},
	CornTex: class extends self.ISpriteInstance {},
	CornWall: class extends self.I3DShapeInstance {},
	CornWallTex0: class extends self.ITiledBackgroundInstance {},
	CornWallTex1: class extends self.ITiledBackgroundInstance {},
	CornWallTex2: class extends self.ITiledBackgroundInstance {},
	FenceModel: class extends self.I3DShapeInstance {},
	FenceTex: class extends self.ITiledBackgroundInstance {},
	FinishLine: class extends self.ITiledBackgroundInstance {},
	OutsideTerrain: class extends self.ITiledBackgroundInstance {},
	Sky: class extends self.ISpriteInstance {},
	SmashedCorn: class extends self.ISpriteInstance {},
	StartLine: class extends self.ITiledBackgroundInstance {},
	TerrainModel: class extends self.I3DShapeInstance {},
	TerrainTex0: class extends self.ITiledBackgroundInstance {},
	TerrainTex1: class extends self.ITiledBackgroundInstance {},
	TerrainTex2: class extends self.ITiledBackgroundInstance {},
	FenceModel2: class extends self.I3DShapeInstance {},
	SmokeTex: class extends self.ISpriteInstance {},
	T_Engine_Bottom: class extends self.ISpriteInstance {},
	T_Engine_Front: class extends self.ISpriteInstance {},
	T_Engine_Right: class extends self.ISpriteInstance {},
	T_Engine_Top: class extends self.ISpriteInstance {},
	T_Main_Bottom: class extends self.ISpriteInstance {},
	T_Main_Front: class extends self.ISpriteInstance {},
	T_Main_Left: class extends self.ISpriteInstance {},
	T_Main_Right: class extends self.ISpriteInstance {},
	T_Main_Top: class extends self.ISpriteInstance {},
	T_WheelLeft_Bottom: class extends self.ISpriteInstance {},
	T_WheelLeft_Front: class extends self.ISpriteInstance {},
	T_WheelLeft_Left: class extends self.ISpriteInstance {},
	T_WheelLeft_Right: class extends self.ISpriteInstance {},
	T_WheelLeft_Top: class extends self.ISpriteInstance {},
	T_WheelRight_Bottom: class extends self.ISpriteInstance {},
	T_WheelRight_Front: class extends self.ISpriteInstance {},
	T_WheelRight_Left: class extends self.ISpriteInstance {},
	T_WheelRight_Right: class extends self.ISpriteInstance {},
	T_WheelRight_Top: class extends self.ISpriteInstance {},
	T_WheelSmallLeft_Bottom: class extends self.ISpriteInstance {},
	T_WheelSmallLeft_Front: class extends self.ISpriteInstance {},
	T_WheelSmallLeft_Left: class extends self.ISpriteInstance {},
	T_WheelSmallLeft_Right: class extends self.ISpriteInstance {},
	T_WheelSmallLeft_Top: class extends self.ISpriteInstance {},
	T_WheelSmallRight_Bottom: class extends self.ISpriteInstance {},
	T_WheelSmallRight_Front: class extends self.ISpriteInstance {},
	T_WheelSmallRight_Left: class extends self.ISpriteInstance {},
	T_WheelSmallRight_Right: class extends self.ISpriteInstance {},
	T_WheelSmallRight_Top: class extends self.ISpriteInstance {},
	SmokeModel: class extends self.I3DShapeInstance {},
	TractorBase: class extends self.ISpriteInstance {},
	TractorBigWheelLeft: class extends self.I3DShapeInstance {},
	TractorBigWheelRight: class extends self.I3DShapeInstance {},
	TractorBody: class extends self.I3DShapeInstance {},
	TractorEngine: class extends self.I3DShapeInstance {},
	TractorExhaust: class extends self.I3DShapeInstance {},
	TractorExhaustTop: class extends self.I3DShapeInstance {},
	TractorLight: class extends self.I3DShapeInstance {},
	TractorNumber: class extends self.I3DShapeInstance {},
	TractorNumberTex: class extends self.ISpriteInstance {},
	TractorSmallWheelLeft: class extends self.I3DShapeInstance {},
	TractorSmallWheelRight: class extends self.I3DShapeInstance {},
	AIPlayer: class extends self.ISpriteInstance {},
	GameTimer: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Minimap: class extends self.ISpriteInstance {},
	StationaryGauge: class extends self.ISpriteInstance {},
	StationaryLimit: class extends self.ISpriteInstance {},
	StationaryPointer: class extends self.ISpriteInstance {},
	StopLights: class extends self.ISpriteInstance {},
	TextGauge: class extends self.ISpriteFontInstance {},
	TextMinimap: class extends self.ISpriteFontInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	TextTutorial: class extends self.ISpriteFontInstance {},
	TextGameOver: class extends self.ISpriteFontInstance {},
	Scarecrow: class extends self.I3DShapeInstance {},
	ScarecrowHatBase: class extends self.I3DShapeInstance {},
	ScarecrowHatTop: class extends self.I3DShapeInstance {},
	ScarecrowHead: class extends self.I3DShapeInstance {},
	ScarecrowLeftArm: class extends self.I3DShapeInstance {},
	ScarecrowRightArm: class extends self.I3DShapeInstance {},
	ScarecrowTorso: class extends self.I3DShapeInstance {},
	UFO: class extends self.I3DShapeInstance {},
	UFOAbduction: class extends self.I3DShapeInstance {},
	UFOAbductionTex: class extends self.ITiledBackgroundInstance {},
	UFOBottom: class extends self.I3DShapeInstance {},
	UFOSideTex: class extends self.ISpriteInstance {},
	UFOTop: class extends self.I3DShapeInstance {},
	Play: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	more: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	upute: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Home: class extends self.ISpriteInstance {},
	Again: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	winner: class extends self.ISpriteInstance {},
	lijevo: class extends self.ISpriteInstance {},
	desno: class extends self.ISpriteInstance {},
	vozi: class extends self.ISpriteInstance {},
	nazad: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	BSound: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Home2: class extends self.ISpriteInstance {},
	NEXTLEVEL: class extends self.ISpriteInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	LevelsBlock: class extends self.ISpriteInstance {},
	select: class extends self.ISpriteInstance {},
	SpriteFont123: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	LevelsText: class extends self.ISpriteFontInstance {},
	skip: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	WeeGooSDK: class extends C3.Plugins.WGSDK.Instance {},
	mobilni: class extends self.ISpriteInstance {}
}