const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.Pin,
		C3.Behaviors.Tween,
		C3.Behaviors.Rotate,
		C3.Plugins.Mouse,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Timeline,
		C3.Plugins.Audio,
		C3.Behaviors.Persist,
		C3.Plugins.Touch,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Behaviors.Pin.Cnds.IsPinned,
		C3.Behaviors.Bullet.Cnds.IsEnabled,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Cnds.IsOnScreen
	];
};
self.C3_JsPropNameTable = [
	{s: 0},
	{Bullet: 0},
	{Pin: 0},
	{Tween: 0},
	{Rotate: 0},
	{sword1: 0},
	{enemy1: 0},
	{Mouse: 0},
	{apple1: 0},
	{apple2: 0},
	{particles1: 0},
	{Particles: 0},
	{Text: 0},
	{Text4: 0},
	{play: 0},
	{Text3: 0},
	{rstrt: 0},
	{Sprite2: 0},
	{resume: 0},
	{main: 0},
	{pause: 0},
	{p: 0},
	{Text2: 0},
	{Sprite3: 0},
	{Sine: 0},
	{Sprite4: 0},
	{Asset: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Asset2: 0},
	{Text5: 0},
	{Sprite7: 0},
	{Text6: 0},
	{Asset6: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{break1: 0},
	{break3: 0},
	{break2: 0},
	{TimelineController: 0},
	{apple3: 0},
	{Sprite: 0},
	{enemy2: 0},
	{break6: 0},
	{break4: 0},
	{break5: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{shop: 0},
	{Audio: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{buy: 0},
	{Persist: 0},
	{use: 0},
	{price: 0},
	{fakeuse: 0},
	{Touch: 0},
	{WeeGooSDK: 0},
	{swordcount: 0},
	{score: 0},
	{apple: 0},
	{hscore: 0},
	{highapple: 0},
	{show: 0},
	{level: 0},
	{speed: 0},
	{rotate: 0},
	{speed2: 0},
	{rotate2: 0},
	{skin: 0},
	{isselected: 0},
	{sound: 0},
	{music: 0}
];

self.InstanceType = {
	sword1: class extends self.ISpriteInstance {},
	enemy1: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	apple1: class extends self.ISpriteInstance {},
	apple2: class extends self.ISpriteInstance {},
	particles1: class extends self.IParticlesInstance {},
	Particles: class extends self.IParticlesInstance {},
	Text: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	play: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	rstrt: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	resume: class extends self.ISpriteInstance {},
	main: class extends self.ISpriteInstance {},
	pause: class extends self.ISpriteInstance {},
	p: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Asset: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Asset2: class extends self.ISpriteInstance {},
	Text5: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Text6: class extends self.ITextInstance {},
	Asset6: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	break1: class extends self.ISpriteInstance {},
	break3: class extends self.ISpriteInstance {},
	break2: class extends self.ISpriteInstance {},
	TimelineController: class extends self.IInstance {},
	apple3: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	enemy2: class extends self.ISpriteInstance {},
	break6: class extends self.ISpriteInstance {},
	break4: class extends self.ISpriteInstance {},
	break5: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	shop: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	use: class extends self.ISpriteInstance {},
	price: class extends self.ISpriteInstance {},
	fakeuse: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	WeeGooSDK: class extends self.IInstance {}
}