const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Behaviors.Flash,
		C3.Plugins.PlatformInfo,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Behaviors.Flash.Acts.Flash
	];
};
self.C3_JsPropNameTable = [
	{Array: 0},
	{Audio: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{SpriteFont: 0},
	{SpriteFont2: 0},
	{TXT_Coin: 0},
	{TXT_price: 0},
	{TXT_Score: 0},
	{BG: 0},
	{BG2: 0},
	{BoomEffect: 0},
	{Pin: 0},
	{Character5_Laser: 0},
	{Character5_Laser3: 0},
	{CoinIcon: 0},
	{destroedBox: 0},
	{destroyBox: 0},
	{Hand_Left: 0},
	{Hand_Right: 0},
	{HandHolder: 0},
	{HealthBar_Solder: 0},
	{laserDot: 0},
	{laserDot2: 0},
	{LiteTween: 0},
	{LiteTween2: 0},
	{LosePanel: 0},
	{PriceBar: 0},
	{ScoreBar: 0},
	{Shadow_Shop: 0},
	{Shop_Item_Box: 0},
	{Shop_Panel: 0},
	{Sprite11: 0},
	{time_End: 0},
	{Time: 0},
	{TimeBar: 0},
	{Sine: 0},
	{Title: 0},
	{TouchPad_Right: 0},
	{TouchPad_Right2: 0},
	{robotboxSpown: 0},
	{Asset34x: 0},
	{Spown: 0},
	{Box1: 0},
	{Colour: 0},
	{box2: 0},
	{Box4: 0},
	{Box5Spwn: 0},
	{Box5: 0},
	{colour: 0},
	{Box3: 0},
	{BTN_Buy: 0},
	{BTN_Close: 0},
	{BTN_Exit: 0},
	{BTN_Home: 0},
	{BTN_Play: 0},
	{BTN_Retry: 0},
	{BTN_Shop: 0},
	{BTN_Sound: 0},
	{BTN_Buy2: 0},
	{Btn_play_shop: 0},
	{BTN_Buy3: 0},
	{Btn_play_shop2: 0},
	{IsDaed: 0},
	{BUY: 0},
	{Playe: 0},
	{Player2: 0},
	{Player3: 0},
	{Player4: 0},
	{Player5: 0},
	{Player6: 0},
	{Rotate: 0},
	{Asset14x: 0},
	{Asset24x: 0},
	{Asset24x2: 0},
	{Box2_Balt: 0},
	{Box2_Kata: 0},
	{Box3_Balt: 0},
	{Box3_Kata: 0},
	{Sprite: 0},
	{txt_playercount: 0},
	{txt_show: 0},
	{BTN_Owned: 0},
	{BTN_Home1: 0},
	{Logo: 0},
	{Particles: 0},
	{Flash: 0},
	{txt_message: 0},
	{txt_Add_Value: 0},
	{BTN_ADD: 0},
	{Animation: 0},
	{Animation1: 0},
	{Animation2: 0},
	{txt_AddCounter: 0},
	{PlatformInfo: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{WeeGooSDK: 0},
	{Coin: 0},
	{SpownType: 0},
	{Score: 0},
	{AddShow: 0},
	{timer: 0},
	{sound: 0},
	{SILENT2: 0},
	{BuyPlayer: 0},
	{SHOW_ROBOT: 0}
];

self.InstanceType = {
	Array: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	TXT_Coin: class extends self.ITextInstance {},
	TXT_price: class extends self.ITextInstance {},
	TXT_Score: class extends self.ITextInstance {},
	BG: class extends self.ISpriteInstance {},
	BG2: class extends self.ISpriteInstance {},
	BoomEffect: class extends self.ISpriteInstance {},
	Character5_Laser: class extends self.ISpriteInstance {},
	Character5_Laser3: class extends self.ISpriteInstance {},
	CoinIcon: class extends self.ISpriteInstance {},
	destroedBox: class extends self.ISpriteInstance {},
	destroyBox: class extends self.ISpriteInstance {},
	Hand_Left: class extends self.ISpriteInstance {},
	Hand_Right: class extends self.ISpriteInstance {},
	HandHolder: class extends self.ISpriteInstance {},
	HealthBar_Solder: class extends self.ISpriteInstance {},
	laserDot: class extends self.ISpriteInstance {},
	laserDot2: class extends self.ISpriteInstance {},
	LosePanel: class extends self.ISpriteInstance {},
	PriceBar: class extends self.ISpriteInstance {},
	ScoreBar: class extends self.ISpriteInstance {},
	Shadow_Shop: class extends self.ISpriteInstance {},
	Shop_Item_Box: class extends self.ISpriteInstance {},
	Shop_Panel: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	time_End: class extends self.ISpriteInstance {},
	TimeBar: class extends self.ISpriteInstance {},
	Title: class extends self.ISpriteInstance {},
	TouchPad_Right: class extends self.ISpriteInstance {},
	TouchPad_Right2: class extends self.ISpriteInstance {},
	Asset34x: class extends self.ISpriteInstance {},
	Box1: class extends self.ISpriteInstance {},
	box2: class extends self.ISpriteInstance {},
	Box4: class extends self.ISpriteInstance {},
	Box5: class extends self.ISpriteInstance {},
	Box3: class extends self.ISpriteInstance {},
	BTN_Buy: class extends self.ISpriteInstance {},
	BTN_Close: class extends self.ISpriteInstance {},
	BTN_Exit: class extends self.ISpriteInstance {},
	BTN_Home: class extends self.ISpriteInstance {},
	BTN_Play: class extends self.ISpriteInstance {},
	BTN_Retry: class extends self.ISpriteInstance {},
	BTN_Shop: class extends self.ISpriteInstance {},
	BTN_Sound: class extends self.ISpriteInstance {},
	BTN_Buy2: class extends self.ISpriteInstance {},
	Btn_play_shop: class extends self.ISpriteInstance {},
	BTN_Buy3: class extends self.ISpriteInstance {},
	Btn_play_shop2: class extends self.ISpriteInstance {},
	Playe: class extends self.ISpriteInstance {},
	Player2: class extends self.ISpriteInstance {},
	Player3: class extends self.ISpriteInstance {},
	Player4: class extends self.ISpriteInstance {},
	Player5: class extends self.ISpriteInstance {},
	Player6: class extends self.ISpriteInstance {},
	Asset14x: class extends self.ISpriteInstance {},
	Asset24x: class extends self.ISpriteInstance {},
	Asset24x2: class extends self.ISpriteInstance {},
	Box2_Balt: class extends self.ISpriteInstance {},
	Box2_Kata: class extends self.ISpriteInstance {},
	Box3_Balt: class extends self.ISpriteInstance {},
	Box3_Kata: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	txt_playercount: class extends self.ITextInstance {},
	txt_show: class extends self.ITextInstance {},
	BTN_Owned: class extends self.ISpriteInstance {},
	BTN_Home1: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	txt_message: class extends self.ITextInstance {},
	txt_Add_Value: class extends self.ITextInstance {},
	BTN_ADD: class extends self.ISpriteInstance {},
	Animation: class extends self.ISpriteInstance {},
	Animation1: class extends self.ISpriteInstance {},
	Animation2: class extends self.ISpriteInstance {},
	txt_AddCounter: class extends self.ITextInstance {},
	PlatformInfo: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {}
}