const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Particles,
		C3.Behaviors.Tween,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward
	];
};
self.C3_JsPropNameTable = [
	{up_black: 0},
	{Pin: 0},
	{up_white: 0},
	{down_white: 0},
	{black_down: 0},
	{Mouse: 0},
	{Bullet: 0},
	{Flash: 0},
	{ball: 0},
	{Keyboard: 0},
	{score: 0},
	{Particles: 0},
	{Particles2: 0},
	{highscore: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Tween: 0},
	{santa: 0},
	{play: 0},
	{sound: 0},
	{home: 0},
	{retry: 0},
	{Sprite5: 0},
	{Audio: 0},
	{Touch: 0},
	{WeeGooSDK: 0},
	{position: 0},
	{movement: 0},
	{color: 0},
	{hscore: 0}
];

self.InstanceType = {
	up_black: class extends self.ISpriteInstance {},
	up_white: class extends self.ISpriteInstance {},
	down_white: class extends self.ISpriteInstance {},
	black_down: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	ball: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	score: class extends self.ITextInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	highscore: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	santa: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	sound: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	retry: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	WeeGooSDK: class extends self.IInstance {}
}