const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Plugins.ppstudio_ga4,
		C3.Plugins.WGSDK,
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Tween,
		C3.Plugins.Particles,
		C3.Behaviors.Pin,
		C3.Behaviors.Physics,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Physics.Acts.SetFriction,
		C3.Behaviors.Physics.Acts.SetElasticity,
		C3.Behaviors.Pin.Acts.SetDestroy,
		C3.Behaviors.Physics.Acts.SetDensity,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Behaviors.Pin.Cnds.IsPinned,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.ppstudio_ga4.Acts.GASendEvent,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.MoveTo.Acts.SetAcceleration,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.ppstudio_ga4.Acts.InitGA,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.SetMuted
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Touch: 0},
	{PlatformInfo: 0},
	{Browser: 0},
	{GA4: 0},
	{WeeGooSDK: 0},
	{bgArtboard: 0},
	{blackScreenAsset: 0},
	{clockAnimationAsset: 0},
	{Rotate: 0},
	{Sine: 0},
	{Sine2: 0},
	{Confetti: 0},
	{MoveTo: 0},
	{crow: 0},
	{crowDestroy: 0},
	{dropPebble: 0},
	{fakeJar: 0},
	{GAMEBUTTONAsset2: 0},
	{gameItemsAsset: 0},
	{gameItemsAsset2: 0},
	{gameItemsAsset3: 0},
	{gameOverAsset: 0},
	{home: 0},
	{jar: 0},
	{LevelNo: 0},
	{level: 0},
	{Tween: 0},
	{life: 0},
	{loseBanner: 0},
	{menuAnimationAsset: 0},
	{menuScreenAssetsEffectsAsset: 0},
	{menuScreenAssetsEffectsAsset2: 0},
	{Particles: 0},
	{Pin: 0},
	{Physics: 0},
	{pebbleAsset: 0},
	{play: 0},
	{retry: 0},
	{slide: 0},
	{sound: 0},
	{Solid: 0},
	{Platform: 0},
	{Sprite3: 0},
	{stop: 0},
	{titleAsset: 0},
	{vcArtboard: 0},
	{water: 0},
	{waterIncrease: 0},
	{winBanner: 0},
	{winnerAsset2: 0},
	{timeGone: 0},
	{pebblesGot: 0},
	{waterLevel: 0},
	{levelNo: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	GA4: class extends C3.Plugins.ppstudio_ga4.Instance {},
	WeeGooSDK: class extends C3.Plugins.WGSDK.Instance {},
	bgArtboard: class extends self.ISpriteInstance {},
	blackScreenAsset: class extends self.ISpriteInstance {},
	clockAnimationAsset: class extends self.ISpriteInstance {},
	Confetti: class extends self.ISpriteInstance {},
	crow: class extends self.ISpriteInstance {},
	crowDestroy: class extends self.ISpriteInstance {},
	dropPebble: class extends self.ISpriteInstance {},
	fakeJar: class extends self.ISpriteInstance {},
	GAMEBUTTONAsset2: class extends self.ISpriteInstance {},
	gameItemsAsset: class extends self.ISpriteInstance {},
	gameItemsAsset2: class extends self.ISpriteInstance {},
	gameItemsAsset3: class extends self.ISpriteInstance {},
	gameOverAsset: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	jar: class extends self.ISpriteInstance {},
	level: class extends self.ISpriteInstance {},
	life: class extends self.ISpriteInstance {},
	loseBanner: class extends self.ISpriteInstance {},
	menuAnimationAsset: class extends self.ISpriteInstance {},
	menuScreenAssetsEffectsAsset: class extends self.ISpriteInstance {},
	menuScreenAssetsEffectsAsset2: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	pebbleAsset: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	retry: class extends self.ISpriteInstance {},
	slide: class extends self.ISpriteInstance {},
	sound: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	stop: class extends self.ISpriteInstance {},
	titleAsset: class extends self.ISpriteInstance {},
	vcArtboard: class extends self.ISpriteInstance {},
	water: class extends self.ISpriteInstance {},
	waterIncrease: class extends self.ISpriteInstance {},
	winBanner: class extends self.ISpriteInstance {},
	winnerAsset2: class extends self.ISpriteInstance {}
}