const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Function,
		C3.Plugins.LocalStorage,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.AJAX,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Behaviors.scrollto,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Spritefont2.Cnds.PickByUID,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetSize,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.Alert,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Function.Cnds.CompareParam,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Cnds.CompareXYZ,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Function.Exps.Call,
		C3.Plugins.Function.Acts.SetReturnValue,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Browser.Cnds.OnBackButton,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Touch.Cnds.CompareTouchSpeed,
		C3.Plugins.Touch.Exps.AngleAt,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Function: 0},
	{LocalStorage: 0},
	{GameData: 0},
	{SwapData: 0},
	{Touch: 0},
	{ArrayTemp: 0},
	{ArrayTemp2: 0},
	{array_level: 0},
	{Browser: 0},
	{Keyboard: 0},
	{AJAX: 0},
	{array_localstorage: 0},
	{array_save: 0},
	{type: 0},
	{Anchor: 0},
	{SpriteFont1: 0},
	{SpriteFont2: 0},
	{SpriteFont3: 0},
	{SpriteFont4: 0},
	{btn_back: 0},
	{btn_menu: 0},
	{btn_next: 0},
	{btn_pause: 0},
	{btn_music: 0},
	{btn_play: 0},
	{Reset: 0},
	{btn_restart: 0},
	{btn_resume: 0},
	{btn_sound: 0},
	{row: 0},
	{col: 0},
	{Moving: 0},
	{TargetY: 0},
	{GameDi: 0},
	{Swap: 0},
	{isMatch: 0},
	{Trigger: 0},
	{Tween: 0},
	{Candy: 0},
	{Tile: 0},
	{Candy2: 0},
	{check: 0},
	{Candy_tween: 0},
	{Fade: 0},
	{effect: 0},
	{collision: 0},
	{window: 0},
	{darkBG: 0},
	{header: 0},
	{Outline: 0},
	{timer_frame: 0},
	{timer_progress: 0},
	{combos: 0},
	{timerSS: 0},
	{ScrollTo: 0},
	{scroll: 0},
	{id: 0},
	{btn_level: 0},
	{page_dots: 0},
	{Rotate: 0},
	{loading: 0},
	{target_bar2: 0},
	{win_level: 0},
	{Esmaecer: 0},
	{Interpolação: 0},
	{Effects: 0},
	{Particles_Star: 0},
	{Effects2: 0},
	{BG: 0},
	{S_Angle: 0},
	{S_Width: 0},
	{S_Height: 0},
	{Logo: 0},
	{btn_play2: 0},
	{btn_play3: 0},
	{Particles_Star2: 0},
	{Objectives: 0},
	{bg_btn: 0},
	{S_Heigh: 0},
	{btn_more: 0},
	{WeeGooSDK: 0},
	{Popup_btn: 0},
	{Button: 0},
	{Pause_btn: 0},
	{best_score: 0},
	{score: 0},
	{game_mode: 0},
	{max_color: 0},
	{moves: 0},
	{cur_moves: 0},
	{state: 0},
	{width: 0},
	{height: 0},
	{PosX: 0},
	{PosY: 0},
	{tile_size: 0},
	{fall_speed: 0},
	{is_falling: 0},
	{draging: 0},
	{top_cell: 0},
	{shift: 0},
	{shift2: 0},
	{cur: 0},
	{Touching: 0},
	{NotMatch: 0},
	{plus: 0},
	{substract: 0},
	{ScoreTemp: 0},
	{ScoreTemp2: 0},
	{Target1: 0},
	{Target2: 0},
	{Target3: 0},
	{music: 0},
	{sound: 0},
	{cur_level: 0},
	{unlock_level: 0},
	{max_page: 0},
	{cur_page: 0},
	{total_level: 0},
	{space_x: 0},
	{space_y: 0},
	{x: 0},
	{y: 0},
	{counter: 0},
	{counter2: 0},
	{is_swiping: 0},
	{loop: 0},
	{loop_int: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	GameData: class extends self.IArrayInstance {},
	SwapData: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	ArrayTemp: class extends self.IArrayInstance {},
	ArrayTemp2: class extends self.IArrayInstance {},
	array_level: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	array_localstorage: class extends self.IArrayInstance {},
	array_save: class extends self.IArrayInstance {},
	SpriteFont1: class extends self.ISpriteFontInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	SpriteFont3: class extends self.ISpriteFontInstance {},
	SpriteFont4: class extends self.ISpriteFontInstance {},
	btn_back: class extends self.ISpriteInstance {},
	btn_menu: class extends self.ISpriteInstance {},
	btn_next: class extends self.ISpriteInstance {},
	btn_pause: class extends self.ISpriteInstance {},
	btn_music: class extends self.ISpriteInstance {},
	btn_play: class extends self.ISpriteInstance {},
	btn_restart: class extends self.ISpriteInstance {},
	btn_resume: class extends self.ISpriteInstance {},
	btn_sound: class extends self.ISpriteInstance {},
	Candy: class extends self.ISpriteInstance {},
	Tile: class extends self.ISpriteInstance {},
	Candy2: class extends self.ISpriteInstance {},
	check: class extends self.ISpriteInstance {},
	Candy_tween: class extends self.ISpriteInstance {},
	effect: class extends self.ISpriteInstance {},
	collision: class extends self.ISpriteInstance {},
	window: class extends self.ISpriteInstance {},
	darkBG: class extends self.ITiledBackgroundInstance {},
	header: class extends self.ISpriteInstance {},
	Outline: class extends self.ISpriteInstance {},
	timer_frame: class extends self.ISpriteInstance {},
	timer_progress: class extends self.ITiledBackgroundInstance {},
	combos: class extends self.ISpriteInstance {},
	timerSS: class extends self.ISpriteInstance {},
	scroll: class extends self.ISpriteInstance {},
	btn_level: class extends self.ISpriteInstance {},
	page_dots: class extends self.ISpriteInstance {},
	loading: class extends self.ISpriteInstance {},
	target_bar2: class extends self.ISpriteInstance {},
	win_level: class extends self.ISpriteInstance {},
	Effects: class extends self.ISpriteInstance {},
	Particles_Star: class extends self.IParticlesInstance {},
	Effects2: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	btn_play2: class extends self.ISpriteInstance {},
	btn_play3: class extends self.ISpriteInstance {},
	Particles_Star2: class extends self.IParticlesInstance {},
	Objectives: class extends self.ISpriteInstance {},
	bg_btn: class extends self.ISpriteInstance {},
	btn_more: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	Popup_btn: class extends self.ISpriteInstance {},
	Button: class extends self.ISpriteInstance {},
	Pause_btn: class extends self.ISpriteInstance {}
}