const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.Tween,
		C3.Behaviors.LOS,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Plugins.gamepad,
		C3.Behaviors.Timer,
		C3.Plugins.WGSDK,
		C3.Behaviors.solid,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Physics.Acts.SetSteppingMode,
		C3.Behaviors.Physics.Acts.SetIterations,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Exps.layoutscale,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.SetAngle,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.LOS.Acts.CastRay,
		C3.Behaviors.LOS.Exps.Range,
		C3.Behaviors.LOS.Cnds.RayIntersected,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Behaviors.LOS.Exps.HitDistance,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.LOS.Exps.HitX,
		C3.Behaviors.LOS.Exps.HitY,
		C3.Behaviors.LOS.Exps.NormalAngle,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.layoutheight
	];
};
self.C3_JsPropNameTable = [
	{LastX: 0},
	{LastY: 0},
	{ThunderAngle: 0},
	{Physics: 0},
	{Tween: 0},
	{LineOfSight: 0},
	{BallPhysics: 0},
	{IDName: 0},
	{Flipper: 0},
	{Keyboard: 0},
	{DarkBlueBackground: 0},
	{MachineChunk: 0},
	{CanBounce: 0},
	{CooldownDuration: 0},
	{SlingshotRadial: 0},
	{SlingshotBottomLeft: 0},
	{SligshotTopRight: 0},
	{SlingshotTopLeft: 0},
	{Shooter: 0},
	{WallLarge: 0},
	{WallMedium: 0},
	{WallSmall: 0},
	{SlingshotCeiling: 0},
	{Light: 0},
	{HoleEntrance: 0},
	{HoleExit: 0},
	{BallGraphics: 0},
	{SlingshotBottomRight: 0},
	{BallTrail: 0},
	{Launcher: 0},
	{BlackBackgorund: 0},
	{Fade: 0},
	{Text: 0},
	{WallTextureMask: 0},
	{WallTexture: 0},
	{FlipperCollision: 0},
	{Screw: 0},
	{Thunder: 0},
	{Sparkles: 0},
	{Rain: 0},
	{ShooterMuzzleFlash: 0},
	{Gamepad: 0},
	{LightOutline: 0},
	{Timer: 0},
	{GameManager: 0},
	{WeeGooSDK: 0},
	{Solid: 0},
	{PhysicsSolid: 0},
	{Slingshot: 0},
	{BallUID: 0},
	{BallImpulse: 0},
	{BallAngle: 0},
	{DisplayScore: 0},
	{SlingshotUID: 0},
	{Duration: 0}
];

self.InstanceType = {
	BallPhysics: class extends self.ISpriteInstance {},
	Flipper: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	DarkBlueBackground: class extends self.ITiledBackgroundInstance {},
	MachineChunk: class extends self.ISpriteInstance {},
	SlingshotRadial: class extends self.ISpriteInstance {},
	SlingshotBottomLeft: class extends self.ISpriteInstance {},
	SligshotTopRight: class extends self.ISpriteInstance {},
	SlingshotTopLeft: class extends self.ISpriteInstance {},
	Shooter: class extends self.ISpriteInstance {},
	WallLarge: class extends self.ISpriteInstance {},
	WallMedium: class extends self.ISpriteInstance {},
	WallSmall: class extends self.ISpriteInstance {},
	SlingshotCeiling: class extends self.ISpriteInstance {},
	Light: class extends self.ISpriteInstance {},
	HoleEntrance: class extends self.ISpriteInstance {},
	HoleExit: class extends self.ISpriteInstance {},
	BallGraphics: class extends self.ISpriteInstance {},
	SlingshotBottomRight: class extends self.ISpriteInstance {},
	BallTrail: class extends self.ISpriteInstance {},
	Launcher: class extends self.ISpriteInstance {},
	BlackBackgorund: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ISpriteFontInstance {},
	WallTextureMask: class extends self.ISpriteInstance {},
	WallTexture: class extends self.ITiledBackgroundInstance {},
	FlipperCollision: class extends self.ISpriteInstance {},
	Screw: class extends self.ISpriteInstance {},
	Thunder: class extends self.ITiledBackgroundInstance {},
	Sparkles: class extends self.IParticlesInstance {},
	Rain: class extends self.IParticlesInstance {},
	ShooterMuzzleFlash: class extends self.IParticlesInstance {},
	Gamepad: class extends self.IInstance {},
	LightOutline: class extends self.ISpriteInstance {},
	GameManager: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	PhysicsSolid: class extends self.ISpriteInstance {},
	Slingshot: class extends self.ISpriteInstance {}
}