const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.NinePatch,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Behaviors.Pin,
		C3.Plugins.TiledBg,
		C3.Plugins.GameRecorder,
		C3.Plugins.UserMedia,
		C3.Plugins.List,
		C3.Plugins.AJAX,
		C3.Plugins.BinaryData,
		C3.Plugins.Share,
		C3.Plugins.FileSystem,
		C3.Plugins.Browser,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.Fade,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Anchor,
		C3.Plugins.Keyboard,
		C3.Plugins.WGSDK,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Particles.Acts.SetInitSize,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.WGSDK.Cnds.RewardGranted,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Cnds.AdvancedAudioSupported,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Acts.AddFilterEffect,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Audio.Acts.AddDelayEffect,
		C3.Plugins.Audio.Acts.RemoveEffects,
		C3.Plugins.Audio.Acts.AddFlangerEffect,
		C3.Plugins.Audio.Acts.AddPhaserEffect,
		C3.Plugins.Audio.Acts.AddCompressorEffect,
		C3.Plugins.Audio.Acts.AddConvolutionEffect,
		C3.Plugins.Audio.Acts.AddTremoloEffect,
		C3.Plugins.Audio.Acts.AddRingModEffect,
		C3.Plugins.Audio.Acts.AddDistortionEffect,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Acts.SetFontFace,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.GameRecorder.Cnds.SupportsRecording,
		C3.Plugins.UserMedia.Acts.GetMediaSources,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.UserMedia.Exps.AudioSourceCount,
		C3.Plugins.List.Acts.SetEnabled,
		C3.Plugins.List.Acts.Clear,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.List.Acts.AddItem,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.UserMedia.Exps.AudioSourceLabelAt,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.UserMedia.Acts.RequestMic,
		C3.Plugins.List.Exps.SelectedIndex,
		C3.Plugins.UserMedia.Cnds.OnApproved,
		C3.Plugins.UserMedia.Cnds.OnDeclined,
		C3.Plugins.GameRecorder.Acts.StartRecording,
		C3.Plugins.GameRecorder.Acts.StopRecording,
		C3.Plugins.GameRecorder.Cnds.OnRecordingReady,
		C3.Plugins.Audio.Acts.AddRemoteURL,
		C3.Plugins.GameRecorder.Exps.RecordingURL,
		C3.Plugins.GameRecorder.Exps.RecordingType,
		C3.Plugins.AJAX.Acts.SetResponseBinary,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Share.Cnds.IsSharingFilesSupported,
		C3.Plugins.FileSystem.Cnds.IsSupported,
		C3.Plugins.GameRecorder.Cnds.OnRecordingError,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.GameRecorder.Exps.RecordingFileExtension,
		C3.Plugins.Share.Acts.AddFile,
		C3.Plugins.Share.Acts.Share,
		C3.Plugins.FileSystem.Acts.AddAcceptType,
		C3.Plugins.FileSystem.Acts.ShowSaveFilePicker,
		C3.Plugins.FileSystem.Cnds.OnPickerComplete,
		C3.Plugins.FileSystem.Acts.WriteBinaryFile,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Audio.Acts.AddAnalyserEffect,
		C3.Plugins.Audio.Acts.AddMuteEffect,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Audio.Exps.AnalyserFreqBinAt,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Text.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{PlayNoise: 0},
	{PlayToneC: 0},
	{PlayToneE: 0},
	{PlayToneG: 0},
	{Text: 0},
	{PlayToneF: 0},
	{PlayToneD: 0},
	{PlayToneA: 0},
	{PlayToneH: 0},
	{PlayToneCIS: 0},
	{PlayToneDIS: 0},
	{PlayToneFIS: 0},
	{PlayToneGIS: 0},
	{PlayToneHMINOR: 0},
	{PlayToneAIS: 0},
	{C3: 0},
	{C4: 0},
	{C5: 0},
	{Touch: 0},
	{ZANOTE: 0},
	{D3: 0},
	{D4: 0},
	{D5: 0},
	{E3: 0},
	{E4: 0},
	{E5: 0},
	{F3: 0},
	{F4: 0},
	{F5: 0},
	{G3: 0},
	{G4: 0},
	{G5: 0},
	{A3: 0},
	{A4: 0},
	{A5: 0},
	{H3: 0},
	{H4: 0},
	{H5: 0},
	{CIS3: 0},
	{CIS4: 0},
	{CIS5: 0},
	{DIS3: 0},
	{DIS4: 0},
	{DIS5: 0},
	{FIS3: 0},
	{FIS4: 0},
	{FIS5: 0},
	{GIS3: 0},
	{GIS4: 0},
	{GIS5: 0},
	{AIS3: 0},
	{AIS4: 0},
	{AIS5: 0},
	{effect: 0},
	{"9patch2": 0},
	{FXAdded: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{dugmeefekti: 0},
	{dugmeefekti2: 0},
	{dugmeefekti3: 0},
	{dugmeefekti4: 0},
	{dugmeefekti5: 0},
	{Sprite6: 0},
	{dugmeefekti6: 0},
	{dugmeefekti7: 0},
	{dugmeefekti8: 0},
	{dugmeefekti9: 0},
	{dugmeefekti10: 0},
	{dugmeefekti11: 0},
	{dugmeefekti12: 0},
	{dugmeefekti13: 0},
	{dugmeefekti14: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{"1efekt": 0},
	{"1efekt2": 0},
	{"1efekt3": 0},
	{"1efekt4": 0},
	{"1efekt5": 0},
	{"1efekt6": 0},
	{"1efekt7": 0},
	{"1efekt8": 0},
	{"1efekt9": 0},
	{"1efekt10": 0},
	{"1efekt11": 0},
	{slikapozadina: 0},
	{Sine: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{klavir: 0},
	{Text2: 0},
	{ToolTip: 0},
	{Pin: 0},
	{Snow: 0},
	{FXAdded2: 0},
	{Sprite9: 0},
	{Sprite14: 0},
	{equalizer: 0},
	{FunBot: 0},
	{GarnelDugme: 0},
	{Marddugme: 0},
	{MrSunButton: 0},
	{MrFunCompButton: 0},
	{Sprite: 0},
	{Sprite13: 0},
	{Garnel: 0},
	{Mard: 0},
	{MrSun: 0},
	{MrFunComp: 0},
	{StartRecording: 0},
	{StopRecording: 0},
	{PlayRecording: 0},
	{SaveRecording: 0},
	{DownloadRecording: 0},
	{ShareRecording: 0},
	{binNumber: 0},
	{SpectrumBar: 0},
	{VideoRecorder: 0},
	{UserMedia: 0},
	{InputDeviceList: 0},
	{RequestMic: 0},
	{Status: 0},
	{AJAX: 0},
	{BinaryData: 0},
	{Share: 0},
	{FileSystem: 0},
	{Browser: 0},
	{SpectrumBase: 0},
	{Sprite19: 0},
	{rekordingaktive: 0},
	{stoprekordingaktive: 0},
	{playrekordingnoaktive: 0},
	{rekording2: 0},
	{stoprekordingnoactive: 0},
	{playrekordingaktive: 0},
	{Sprite20: 0},
	{changebackground: 0},
	{zelena: 0},
	{zuta: 0},
	{svjetlozelena: 0},
	{narandjasta: 0},
	{ljubicasta: 0},
	{plava: 0},
	{svjetloplava: 0},
	{roza: 0},
	{crvena: 0},
	{resetbtn: 0},
	{home: 0},
	{BSound: 0},
	{Play: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{downloadaktive: 0},
	{downloadnoaktive: 0},
	{Snow2: 0},
	{note: 0},
	{logo: 0},
	{Sprite21: 0},
	{slikapozadina2: 0},
	{LiteTween: 0},
	{zavjesa: 0},
	{info: 0},
	{home2: 0},
	{tekstmuzika: 0},
	{pozadinamuzika: 0},
	{close: 0},
	{addtimereklama: 0},
	{Fade: 0},
	{HelpImg4: 0},
	{Anchor: 0},
	{StarsFont3: 0},
	{pozadinazaaddgifts: 0},
	{rekording3: 0},
	{rewarded: 0},
	{rekordingnoaktive: 0},
	{Keyboard: 0},
	{klavir2: 0},
	{pozadinazaboje: 0},
	{Sprite24: 0},
	{slikapozadina3: 0},
	{klavir3: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Text3: 0},
	{kexboard: 0},
	{klavir4: 0},
	{Text4: 0},
	{info2: 0},
	{fullscreen: 0},
	{Sprite29: 0},
	{stopfunbot: 0},
	{funbotples: 0},
	{garnelstopsound: 0},
	{garnelples: 0},
	{mardstopsound: 0},
	{mardples: 0},
	{MrSunPles: 0},
	{mrsunstopsound: 0},
	{MrFunCompPles: 0},
	{MrFunCompstopsound: 0},
	{MrTreeButton: 0},
	{MrTree: 0},
	{MrTreePles: 0},
	{MrTreestopsound2: 0},
	{OrenButton: 0},
	{Oren: 0},
	{OrenStopSound: 0},
	{OrenPles: 0},
	{JevinButton: 0},
	{Jevin: 0},
	{JevinStopSound: 0},
	{JevinPles: 0},
	{PinkiButton: 0},
	{Pinki: 0},
	{PinkiStopSound: 0},
	{PinkiPles: 0},
	{Sprite15: 0},
	{slikapozadina4: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{vrijeme: 0},
	{more: 0},
	{Sprite18: 0},
	{WeeGooSDK: 0},
	{notebuttons: 0},
	{Sound: 0},
	{VrijemeuIgri: 0},
	{SoundEf: 0},
	{FrequencyBinCount: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	PlayNoise: class extends self.IButtonInstance {},
	PlayToneC: class extends self.IButtonInstance {},
	PlayToneE: class extends self.IButtonInstance {},
	PlayToneG: class extends self.IButtonInstance {},
	Text: class extends self.ITextInstance {},
	PlayToneF: class extends self.IButtonInstance {},
	PlayToneD: class extends self.IButtonInstance {},
	PlayToneA: class extends self.IButtonInstance {},
	PlayToneH: class extends self.IButtonInstance {},
	PlayToneCIS: class extends self.IButtonInstance {},
	PlayToneDIS: class extends self.IButtonInstance {},
	PlayToneFIS: class extends self.IButtonInstance {},
	PlayToneGIS: class extends self.IButtonInstance {},
	PlayToneHMINOR: class extends self.IButtonInstance {},
	PlayToneAIS: class extends self.IButtonInstance {},
	C3: class extends self.ISpriteInstance {},
	C4: class extends self.ISpriteInstance {},
	C5: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	ZANOTE: class extends self.ISpriteInstance {},
	D3: class extends self.ISpriteInstance {},
	D4: class extends self.ISpriteInstance {},
	D5: class extends self.ISpriteInstance {},
	E3: class extends self.ISpriteInstance {},
	E4: class extends self.ISpriteInstance {},
	E5: class extends self.ISpriteInstance {},
	F3: class extends self.ISpriteInstance {},
	F4: class extends self.ISpriteInstance {},
	F5: class extends self.ISpriteInstance {},
	G3: class extends self.ISpriteInstance {},
	G4: class extends self.ISpriteInstance {},
	G5: class extends self.ISpriteInstance {},
	A3: class extends self.ISpriteInstance {},
	A4: class extends self.ISpriteInstance {},
	A5: class extends self.ISpriteInstance {},
	H3: class extends self.ISpriteInstance {},
	H4: class extends self.ISpriteInstance {},
	H5: class extends self.ISpriteInstance {},
	CIS3: class extends self.ISpriteInstance {},
	CIS4: class extends self.ISpriteInstance {},
	CIS5: class extends self.ISpriteInstance {},
	DIS3: class extends self.ISpriteInstance {},
	DIS4: class extends self.ISpriteInstance {},
	DIS5: class extends self.ISpriteInstance {},
	FIS3: class extends self.ISpriteInstance {},
	FIS4: class extends self.ISpriteInstance {},
	FIS5: class extends self.ISpriteInstance {},
	GIS3: class extends self.ISpriteInstance {},
	GIS4: class extends self.ISpriteInstance {},
	GIS5: class extends self.ISpriteInstance {},
	AIS3: class extends self.ISpriteInstance {},
	AIS4: class extends self.ISpriteInstance {},
	AIS5: class extends self.ISpriteInstance {},
	_9patch2: class extends self.IWorldInstance {},
	FXAdded: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	dugmeefekti: class extends self.ISpriteInstance {},
	dugmeefekti2: class extends self.ISpriteInstance {},
	dugmeefekti3: class extends self.ISpriteInstance {},
	dugmeefekti4: class extends self.ISpriteInstance {},
	dugmeefekti5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	dugmeefekti6: class extends self.ISpriteInstance {},
	dugmeefekti7: class extends self.ISpriteInstance {},
	dugmeefekti8: class extends self.ISpriteInstance {},
	dugmeefekti9: class extends self.ISpriteInstance {},
	dugmeefekti10: class extends self.ISpriteInstance {},
	dugmeefekti11: class extends self.ISpriteInstance {},
	dugmeefekti12: class extends self.ISpriteInstance {},
	dugmeefekti13: class extends self.ISpriteInstance {},
	dugmeefekti14: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	_1efekt: class extends self.ISpriteInstance {},
	_1efekt2: class extends self.ISpriteInstance {},
	_1efekt3: class extends self.ISpriteInstance {},
	_1efekt4: class extends self.ISpriteInstance {},
	_1efekt5: class extends self.ISpriteInstance {},
	_1efekt6: class extends self.ISpriteInstance {},
	_1efekt7: class extends self.ISpriteInstance {},
	_1efekt8: class extends self.ISpriteInstance {},
	_1efekt9: class extends self.ISpriteInstance {},
	_1efekt10: class extends self.ISpriteInstance {},
	_1efekt11: class extends self.ISpriteInstance {},
	slikapozadina: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	klavir: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Snow: class extends self.IParticlesInstance {},
	FXAdded2: class extends self.ITextInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	equalizer: class extends self.ISpriteInstance {},
	FunBot: class extends self.ISpriteInstance {},
	GarnelDugme: class extends self.ISpriteInstance {},
	Marddugme: class extends self.ISpriteInstance {},
	MrSunButton: class extends self.ISpriteInstance {},
	MrFunCompButton: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Garnel: class extends self.ISpriteInstance {},
	Mard: class extends self.ISpriteInstance {},
	MrSun: class extends self.ISpriteInstance {},
	MrFunComp: class extends self.ISpriteInstance {},
	StartRecording: class extends self.IButtonInstance {},
	StopRecording: class extends self.IButtonInstance {},
	PlayRecording: class extends self.IButtonInstance {},
	SaveRecording: class extends self.IButtonInstance {},
	DownloadRecording: class extends self.IButtonInstance {},
	ShareRecording: class extends self.IButtonInstance {},
	SpectrumBar: class extends self.ITiledBackgroundInstance {},
	VideoRecorder: class extends self.IInstance {},
	UserMedia: class extends self.IWorldInstance {},
	InputDeviceList: class extends self.IListInstance {},
	RequestMic: class extends self.IButtonInstance {},
	Status: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	Share: class extends self.IInstance {},
	FileSystem: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	SpectrumBase: class extends self.ITiledBackgroundInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	rekordingaktive: class extends self.ISpriteInstance {},
	stoprekordingaktive: class extends self.ISpriteInstance {},
	playrekordingnoaktive: class extends self.ISpriteInstance {},
	rekording2: class extends self.ISpriteInstance {},
	stoprekordingnoactive: class extends self.ISpriteInstance {},
	playrekordingaktive: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	changebackground: class extends self.ISpriteInstance {},
	zelena: class extends self.ISpriteInstance {},
	zuta: class extends self.ISpriteInstance {},
	svjetlozelena: class extends self.ISpriteInstance {},
	narandjasta: class extends self.ISpriteInstance {},
	ljubicasta: class extends self.ISpriteInstance {},
	plava: class extends self.ISpriteInstance {},
	svjetloplava: class extends self.ISpriteInstance {},
	roza: class extends self.ISpriteInstance {},
	crvena: class extends self.ISpriteInstance {},
	resetbtn: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	BSound: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	downloadaktive: class extends self.ISpriteInstance {},
	downloadnoaktive: class extends self.ISpriteInstance {},
	Snow2: class extends self.IParticlesInstance {},
	note: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	slikapozadina2: class extends self.ISpriteInstance {},
	zavjesa: class extends self.ISpriteInstance {},
	info: class extends self.ISpriteInstance {},
	home2: class extends self.ISpriteInstance {},
	tekstmuzika: class extends self.ITextInstance {},
	pozadinamuzika: class extends self.ISpriteInstance {},
	close: class extends self.ISpriteInstance {},
	addtimereklama: class extends self.ISpriteInstance {},
	HelpImg4: class extends self.ISpriteInstance {},
	StarsFont3: class extends self.ISpriteFontInstance {},
	pozadinazaaddgifts: class extends self.ISpriteInstance {},
	rekording3: class extends self.ISpriteInstance {},
	rewarded: class extends self.ISpriteInstance {},
	rekordingnoaktive: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	klavir2: class extends self.ISpriteInstance {},
	pozadinazaboje: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	slikapozadina3: class extends self.ISpriteInstance {},
	klavir3: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	kexboard: class extends self.ISpriteInstance {},
	klavir4: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {},
	info2: class extends self.ISpriteInstance {},
	fullscreen: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	stopfunbot: class extends self.ISpriteInstance {},
	funbotples: class extends self.ISpriteInstance {},
	garnelstopsound: class extends self.ISpriteInstance {},
	garnelples: class extends self.ISpriteInstance {},
	mardstopsound: class extends self.ISpriteInstance {},
	mardples: class extends self.ISpriteInstance {},
	MrSunPles: class extends self.ISpriteInstance {},
	mrsunstopsound: class extends self.ISpriteInstance {},
	MrFunCompPles: class extends self.ISpriteInstance {},
	MrFunCompstopsound: class extends self.ISpriteInstance {},
	MrTreeButton: class extends self.ISpriteInstance {},
	MrTree: class extends self.ISpriteInstance {},
	MrTreePles: class extends self.ISpriteInstance {},
	MrTreestopsound2: class extends self.ISpriteInstance {},
	OrenButton: class extends self.ISpriteInstance {},
	Oren: class extends self.ISpriteInstance {},
	OrenStopSound: class extends self.ISpriteInstance {},
	OrenPles: class extends self.ISpriteInstance {},
	JevinButton: class extends self.ISpriteInstance {},
	Jevin: class extends self.ISpriteInstance {},
	JevinStopSound: class extends self.ISpriteInstance {},
	JevinPles: class extends self.ISpriteInstance {},
	PinkiButton: class extends self.ISpriteInstance {},
	Pinki: class extends self.ISpriteInstance {},
	PinkiStopSound: class extends self.ISpriteInstance {},
	PinkiPles: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	slikapozadina4: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	vrijeme: class extends self.ITextInstance {},
	more: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	notebuttons: class extends self.ISpriteInstance {}
}