const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Behaviors.Platform,
		C3.Plugins.Spritefont2,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Plugins.TiledBg,
		C3.Plugins.Particles,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Exps.viewportbottom
	];
};
self.C3_JsPropNameTable = [
	{mainmenuBG: 0},
	{Tween: 0},
	{Play_btn: 0},
	{Logo: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{Audio: 0},
	{Btn_Sound: 0},
	{Platform: 0},
	{Player: 0},
	{Player_Sprite: 0},
	{Player_Sprite_main_menu: 0},
	{bar_bg: 0},
	{bar_fg: 0},
	{heartAsset: 0},
	{scoreAsset: 0},
	{SpriteFont: 0},
	{infographics_start: 0},
	{gameOverAsset: 0},
	{game_over_home: 0},
	{game_over_restart: 0},
	{gameover_trans: 0},
	{waterMainAsset: 0},
	{Solid: 0},
	{Bullet: 0},
	{Block: 0},
	{food: 0},
	{home_btn: 0},
	{TiledBackground: 0},
	{plus_10: 0},
	{minus_10: 0},
	{Particles: 0},
	{food_particle_sprite: 0},
	{mainmenu_ground: 0},
	{nextbutonAsset: 0},
	{instructionAsset2: 0},
	{instructionAsset: 0},
	{main_menu_decoration: 0},
	{Particles2: 0},
	{menuObjectAsset: 0},
	{WeeGooSDK: 0},
	{btn: 0},
	{block_uid: 0},
	{TotalDistance: 0},
	{CurrentDistance: 0},
	{NextBlock: 0},
	{health_condition: 0},
	{new_game: 0},
	{life_amount: 0},
	{score_amount: 0}
];

self.InstanceType = {
	mainmenuBG: class extends self.ISpriteInstance {},
	Play_btn: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Btn_Sound: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Player_Sprite: class extends self.ISpriteInstance {},
	Player_Sprite_main_menu: class extends self.ISpriteInstance {},
	bar_bg: class extends self.ISpriteInstance {},
	bar_fg: class extends self.ISpriteInstance {},
	heartAsset: class extends self.ISpriteInstance {},
	scoreAsset: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	infographics_start: class extends self.ISpriteInstance {},
	gameOverAsset: class extends self.ISpriteInstance {},
	game_over_home: class extends self.ISpriteInstance {},
	game_over_restart: class extends self.ISpriteInstance {},
	gameover_trans: class extends self.ISpriteInstance {},
	waterMainAsset: class extends self.ISpriteInstance {},
	Block: class extends self.ISpriteInstance {},
	food: class extends self.ISpriteInstance {},
	home_btn: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	plus_10: class extends self.ISpriteInstance {},
	minus_10: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	food_particle_sprite: class extends self.ISpriteInstance {},
	mainmenu_ground: class extends self.ISpriteInstance {},
	nextbutonAsset: class extends self.ISpriteInstance {},
	instructionAsset2: class extends self.ISpriteInstance {},
	instructionAsset: class extends self.ISpriteInstance {},
	main_menu_decoration: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	menuObjectAsset: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	btn: class extends self.ISpriteInstance {}
}