const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.solid,
		C3.Plugins.Particles,
		C3.Behaviors.Platform,
		C3.Behaviors.Sin,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.WGSDK,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Particles.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{BG: 0},
	{HILL: 0},
	{HOME: 0},
	{TREE: 0},
	{Text: 0},
	{Solid: 0},
	{P2: 0},
	{P1: 0},
	{E2: 0},
	{E3: 0},
	{Platform: 0},
	{Sine: 0},
	{CHARACTER: 0},
	{E1: 0},
	{coin: 0},
	{GAME_NAME: 0},
	{PLAY: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{WeeGooSDK: 0},
	{Text2: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Browser: 0},
	{platform2: 0},
	{platformSpeed: 0},
	{charstatus: 0},
	{score: 0},
	{platform: 0},
	{TimescaleGV: 0},
	{Highscore: 0}
];

self.InstanceType = {
	BG: class extends self.ISpriteInstance {},
	HILL: class extends self.ISpriteInstance {},
	HOME: class extends self.ISpriteInstance {},
	TREE: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	P2: class extends self.ISpriteInstance {},
	P1: class extends self.ISpriteInstance {},
	E2: class extends self.IParticlesInstance {},
	E3: class extends self.IParticlesInstance {},
	CHARACTER: class extends self.ISpriteInstance {},
	E1: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	GAME_NAME: class extends self.ISpriteInstance {},
	PLAY: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	WeeGooSDK: class extends self.IInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {}
}