const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Behaviors.Sin,
		C3.Plugins.Browser,
		C3.Plugins.Particles,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Rotate,
		C3.Behaviors.scrollto,
		C3.Plugins.WGSDK,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Tween.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Acts.SetLayerAngle,
		C3.Plugins.System.Exps.anglelerp,
		C3.Plugins.System.Exps.layerangle,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.LocalStorage.Cnds.OnAllGetsComplete,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.GoToLayoutByName
	];
};
self.C3_JsPropNameTable = [
	{Ground: 0},
	{Physics: 0},
	{Box1: 0},
	{Text: 0},
	{Pig: 0},
	{Touch: 0},
	{Sprite: 0},
	{Ground2: 0},
	{Sprite2: 0},
	{Box2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{pecurka: 0},
	{pecurka1: 0},
	{mac: 0},
	{poluga: 0},
	{platforma19leveli20: 0},
	{menu: 0},
	{more: 0},
	{ponovo: 0},
	{Sprite10: 0},
	{Tween: 0},
	{zavjesa: 0},
	{Pin: 0},
	{menu2: 0},
	{dalje: 0},
	{procesing: 0},
	{process: 0},
	{Sprite8: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sine: 0},
	{play: 0},
	{igrice: 0},
	{Browser: 0},
	{land: 0},
	{kovceg: 0},
	{Sprite9: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{statua: 0},
	{lopta: 0},
	{mac1: 0},
	{glavastiva: 0},
	{novaploca: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{FireSparks: 0},
	{SemiRealFire2: 0},
	{Firework: 0},
	{Mouse: 0},
	{Audio: 0},
	{dodir: 0},
	{Sprite21: 0},
	{Rope3: 0},
	{Rope5: 0},
	{Rope4: 0},
	{Wheel1: 0},
	{Rope6: 0},
	{Rope0: 0},
	{Rope1: 0},
	{Rope2: 0},
	{Sprite28: 0},
	{dalje2: 0},
	{Rope7: 0},
	{Sprite33: 0},
	{LeftLeg: 0},
	{LeftArm: 0},
	{RightArm: 0},
	{Head: 0},
	{RightLeg: 0},
	{Body: 0},
	{HAT: 0},
	{maska: 0},
	{Head2: 0},
	{igrice2: 0},
	{zid: 0},
	{zid2: 0},
	{BSound: 0},
	{ruka: 0},
	{kula: 0},
	{ne: 0},
	{Sprite7: 0},
	{DOLL: 0},
	{jedan: 0},
	{cetiri: 0},
	{select: 0},
	{SpriteFont123: 0},
	{tri: 0},
	{sest: 0},
	{dva: 0},
	{pet: 0},
	{Open: 0},
	{Level: 0},
	{LevelsBlock: 0},
	{LevelsText: 0},
	{LocalStorage: 0},
	{konfeti: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{youtube: 0},
	{ne2: 0},
	{statua2: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{glava: 0},
	{glava2: 0},
	{tnt: 0},
	{Sprite27: 0},
	{crvenalinijakraj: 0},
	{replay: 0},
	{Rotate: 0},
	{Sprite6: 0},
	{lavablock: 0},
	{vatra: 0},
	{logo: 0},
	{Sprite31: 0},
	{usta: 0},
	{tntbox: 0},
	{lokot: 0},
	{eksplozija: 0},
	{lokot2: 0},
	{tntbox2: 0},
	{eksplozija2: 0},
	{dalje3: 0},
	{Sprite35: 0},
	{zidmali: 0},
	{Sprite32: 0},
	{Sprite34: 0},
	{scale: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{platformanoclick: 0},
	{lokot3: 0},
	{lokot4: 0},
	{platformanoclick2: 0},
	{platformanoclick3: 0},
	{lokot5: 0},
	{platformanovaclick: 0},
	{lavablock2: 0},
	{lokot6: 0},
	{lavablock3: 0},
	{lokot7: 0},
	{Sprite29: 0},
	{Sine2: 0},
	{Sprite30: 0},
	{WeeGooSDK: 0},
	{Sprite36: 0},
	{amir: 0},
	{Family1: 0},
	{boksovi: 0},
	{btn: 0},
	{sound: 0},
	{SoundEf: 0},
	{LAST_LEVEL: 0},
	{WIN: 0},
	{LevelComplete: 0}
];

self.InstanceType = {
	Ground: class extends self.ITiledBackgroundInstance {},
	Box1: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Pig: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Ground2: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Box2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	pecurka: class extends self.ISpriteInstance {},
	pecurka1: class extends self.ISpriteInstance {},
	mac: class extends self.ISpriteInstance {},
	poluga: class extends self.ISpriteInstance {},
	platforma19leveli20: class extends self.ISpriteInstance {},
	menu: class extends self.ISpriteInstance {},
	more: class extends self.ISpriteInstance {},
	ponovo: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	zavjesa: class extends self.ISpriteInstance {},
	menu2: class extends self.ISpriteInstance {},
	dalje: class extends self.ISpriteInstance {},
	procesing: class extends self.ISpriteInstance {},
	process: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	igrice: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	land: class extends self.ISpriteInstance {},
	kovceg: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	statua: class extends self.ISpriteInstance {},
	lopta: class extends self.ISpriteInstance {},
	mac1: class extends self.ISpriteInstance {},
	glavastiva: class extends self.ISpriteInstance {},
	novaploca: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	FireSparks: class extends self.IParticlesInstance {},
	SemiRealFire2: class extends self.IParticlesInstance {},
	Firework: class extends self.IParticlesInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	dodir: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Rope3: class extends self.ISpriteInstance {},
	Rope5: class extends self.ISpriteInstance {},
	Rope4: class extends self.ISpriteInstance {},
	Wheel1: class extends self.ISpriteInstance {},
	Rope6: class extends self.ISpriteInstance {},
	Rope0: class extends self.ISpriteInstance {},
	Rope1: class extends self.ISpriteInstance {},
	Rope2: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	dalje2: class extends self.ISpriteInstance {},
	Rope7: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	LeftLeg: class extends self.ISpriteInstance {},
	LeftArm: class extends self.ISpriteInstance {},
	RightArm: class extends self.ISpriteInstance {},
	Head: class extends self.ISpriteInstance {},
	RightLeg: class extends self.ISpriteInstance {},
	Body: class extends self.ISpriteInstance {},
	HAT: class extends self.ISpriteInstance {},
	maska: class extends self.ISpriteInstance {},
	Head2: class extends self.ISpriteInstance {},
	igrice2: class extends self.ISpriteInstance {},
	zid: class extends self.ISpriteInstance {},
	zid2: class extends self.ISpriteInstance {},
	BSound: class extends self.ISpriteInstance {},
	ruka: class extends self.ISpriteInstance {},
	kula: class extends self.ISpriteInstance {},
	ne: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	DOLL: class extends self.ISpriteFontInstance {},
	jedan: class extends self.ISpriteInstance {},
	cetiri: class extends self.ISpriteInstance {},
	select: class extends self.ISpriteInstance {},
	SpriteFont123: class extends self.ISpriteFontInstance {},
	tri: class extends self.ISpriteInstance {},
	sest: class extends self.ISpriteInstance {},
	dva: class extends self.ISpriteInstance {},
	pet: class extends self.ISpriteInstance {},
	LevelsBlock: class extends self.ISpriteInstance {},
	LevelsText: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	konfeti: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	youtube: class extends self.ISpriteInstance {},
	ne2: class extends self.ISpriteInstance {},
	statua2: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	glava: class extends self.ISpriteInstance {},
	glava2: class extends self.ISpriteInstance {},
	tnt: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	crvenalinijakraj: class extends self.ISpriteInstance {},
	replay: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	lavablock: class extends self.ISpriteInstance {},
	vatra: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	usta: class extends self.ISpriteInstance {},
	tntbox: class extends self.ISpriteInstance {},
	lokot: class extends self.ISpriteInstance {},
	eksplozija: class extends self.ISpriteInstance {},
	lokot2: class extends self.ISpriteInstance {},
	tntbox2: class extends self.ISpriteInstance {},
	eksplozija2: class extends self.ISpriteInstance {},
	dalje3: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	zidmali: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	platformanoclick: class extends self.ISpriteInstance {},
	lokot3: class extends self.ISpriteInstance {},
	lokot4: class extends self.ISpriteInstance {},
	platformanoclick2: class extends self.ISpriteInstance {},
	platformanoclick3: class extends self.ISpriteInstance {},
	lokot5: class extends self.ISpriteInstance {},
	platformanovaclick: class extends self.ISpriteInstance {},
	lavablock2: class extends self.ISpriteInstance {},
	lokot6: class extends self.ISpriteInstance {},
	lavablock3: class extends self.ISpriteInstance {},
	lokot7: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	amir: class extends self.ISpriteInstance {},
	Family1: class extends self.ITiledBackgroundInstance {},
	boksovi: class extends self.ISpriteInstance {},
	btn: class extends self.ISpriteInstance {}
}