const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.WGSDK,
		C3.Plugins.ppstudio_ga4,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Spritefont2,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.ppstudio_ga4.Acts.GASendEvent,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.ppstudio_ga4.Acts.InitGA,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetEffect,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{PlatformInfo: 0},
	{WeeGooSDK: 0},
	{GA4: 0},
	{board: 0},
	{btn_exit: 0},
	{btn_home: 0},
	{Sine: 0},
	{btn_Play: 0},
	{btn_Play2: 0},
	{btn_retry: 0},
	{BTN_Sound: 0},
	{nomer: 0},
	{Particles: 0},
	{Particles2: 0},
	{revive: 0},
	{Shadow: 0},
	{skip: 0},
	{control: 0},
	{Sprite: 0},
	{naprav: 0},
	{Bullet: 0},
	{Sprite10: 0},
	{num: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Fade: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite2: 0},
	{Sprite20: 0},
	{Solid: 0},
	{Sprite7: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{SpriteFont: 0},
	{Text: 0},
	{TouchLeft: 0},
	{TouchRight: 0},
	{txt_timer: 0},
	{color: 0},
	{music: 0},
	{score: 0},
	{speed: 0},
	{touch: 0},
	{Down: 0},
	{Timer: 0},
	{Advert: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	WeeGooSDK: class extends C3.Plugins.WGSDK.Instance {},
	GA4: class extends C3.Plugins.ppstudio_ga4.Instance {},
	board: class extends self.ISpriteInstance {},
	btn_exit: class extends self.ISpriteInstance {},
	btn_home: class extends self.ISpriteInstance {},
	btn_Play: class extends self.ISpriteInstance {},
	btn_Play2: class extends self.ISpriteInstance {},
	btn_retry: class extends self.ISpriteInstance {},
	BTN_Sound: class extends self.ISpriteInstance {},
	nomer: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	revive: class extends self.ITextInstance {},
	Shadow: class extends self.ISpriteInstance {},
	skip: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Text: class extends self.ITextInstance {},
	TouchLeft: class extends self.ISpriteInstance {},
	TouchRight: class extends self.ISpriteInstance {},
	txt_timer: class extends self.ITextInstance {}
}