const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Camera3D,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Spritefont2,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Behaviors.MoveTo,
		C3.Behaviors.custom,
		C3.Behaviors.Fade,
		C3.Behaviors.scrollto,
		C3.Behaviors.Rotate,
		C3.Plugins.Audio,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Behaviors.custom.Acts.SetSpeed,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.custom.Acts.Stop,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Behaviors.Tween.Acts.PauseTweens,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.WGSDK.Cnds.RewardReady,
		C3.Plugins.WGSDK.Cnds.RewardGranted,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Behaviors.Fade.Acts.StartFade
	];
};
self.C3_JsPropNameTable = [
	{"3DCamera": 0},
	{Tween: 0},
	{BloccoDomanda: 0},
	{isTouched: 0},
	{questionNum: 0},
	{BloccoRisposta: 0},
	{SpriteFont: 0},
	{rightAnswer: 0},
	{ArrayY: 0},
	{MaxLevel: 0},
	{isSelected: 0},
	{Timer: 0},
	{gameSpeed: 0},
	{GameControl: 0},
	{Array: 0},
	{AJAX: 0},
	{Touch: 0},
	{array_shuffle: 0},
	{Text: 0},
	{bg_domande: 0},
	{bg_city: 0},
	{sidewalk: 0},
	{MoveTo: 0},
	{Player: 0},
	{Custom: 0},
	{Enemy: 0},
	{shadow: 0},
	{ui_title: 0},
	{fader: 0},
	{btn_play: 0},
	{timer: 0},
	{timer_back: 0},
	{timer3: 0},
	{player_death: 0},
	{bot_death: 0},
	{Fade: 0},
	{flash: 0},
	{type: 0},
	{text_num: 0},
	{btn_retry: 0},
	{btn_menu: 0},
	{btn_reward: 0},
	{btn_audio: 0},
	{ui_GameOver: 0},
	{ui_win: 0},
	{ScrollTo: 0},
	{camera: 0},
	{Rotate: 0},
	{sun: 0},
	{Audio: 0},
	{bg_black: 0},
	{cover_PI: 0},
	{cover_Dev: 0},
	{cover_Ti: 0},
	{cover_Ball_Red: 0},
	{cover_Ball_blu: 0},
	{WeeGooSDK: 0},
	{MovingBGS: 0},
	{Buttons: 0},
	{CoverScreen: 0},
	{Covers: 0},
	{Logos: 0},
	{Cover: 0},
	{Lingua: 0},
	{Score: 0},
	{Level: 0},
	{CardNum: 0},
	{isSound: 0}
];

self.InstanceType = {
	_3DCamera: class extends self.IInstance {},
	BloccoDomanda: class extends self.ISpriteInstance {},
	BloccoRisposta: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	GameControl: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	array_shuffle: class extends self.IArrayInstance {},
	Text: class extends self.ITextInstance {},
	bg_domande: class extends self.ISpriteInstance {},
	bg_city: class extends self.ISpriteInstance {},
	sidewalk: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	shadow: class extends self.ISpriteInstance {},
	ui_title: class extends self.ISpriteInstance {},
	fader: class extends self.ISpriteInstance {},
	btn_play: class extends self.ISpriteInstance {},
	timer: class extends self.ISpriteInstance {},
	timer_back: class extends self.ISpriteInstance {},
	timer3: class extends self.ISpriteInstance {},
	player_death: class extends self.ISpriteInstance {},
	bot_death: class extends self.ISpriteInstance {},
	flash: class extends self.ISpriteInstance {},
	text_num: class extends self.ITextInstance {},
	btn_retry: class extends self.ISpriteInstance {},
	btn_menu: class extends self.ISpriteInstance {},
	btn_reward: class extends self.ISpriteInstance {},
	btn_audio: class extends self.ISpriteInstance {},
	ui_GameOver: class extends self.ISpriteInstance {},
	ui_win: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	sun: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	bg_black: class extends self.ITiledBackgroundInstance {},
	cover_PI: class extends self.ISpriteInstance {},
	cover_Dev: class extends self.ISpriteInstance {},
	cover_Ti: class extends self.ISpriteInstance {},
	cover_Ball_Red: class extends self.ISpriteInstance {},
	cover_Ball_blu: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	MovingBGS: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	CoverScreen: class extends self.ISpriteInstance {},
	Covers: class extends self.ISpriteInstance {},
	Logos: class extends self.ISpriteInstance {},
	Cover: class extends self.ISpriteInstance {}
}