const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse,
		C3.Behaviors.Physics,
		C3.Behaviors.scrollto,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard,
		C3.Plugins.Particles,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.ScirraArcadeV4,
		C3.Plugins.TiledBg,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Fade,
		C3.Plugins.Spritefont2,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Behaviors.Anchor,
		C3.Behaviors.Tween,
		C3.Plugins.WGSDK,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.WGSDK.Cnds.RewardGranted,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Physics.Acts.ApplyForce,
		C3.Behaviors.Physics.Acts.ApplyForceToward,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Physics.Acts.RemoveJoints,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.LocalStorage.Cnds.OnAllGetsComplete,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY
	];
};
self.C3_JsPropNameTable = [
	{Sine: 0},
	{dalje: 0},
	{Mouse: 0},
	{Physics: 0},
	{ScrollTo: 0},
	{car: 0},
	{FrontWheel: 0},
	{BackWheel: 0},
	{Ground: 0},
	{Pin: 0},
	{Guide: 0},
	{Keyboard: 0},
	{Thrust: 0},
	{MAxFuel: 0},
	{CurrFuel: 0},
	{Bullet: 0},
	{Rocket: 0},
	{Head: 0},
	{Blood: 0},
	{Touch: 0},
	{Ground2: 0},
	{BG: 0},
	{FuelTank: 0},
	{DIS: 0},
	{ScirraArcade: 0},
	{Lava: 0},
	{OutOfFuel: 0},
	{FuelBar: 0},
	{FuelBarBG: 0},
	{Ground3: 0},
	{LocalStorage: 0},
	{zemlja: 0},
	{bomba: 0},
	{drvo4: 0},
	{kaktus: 0},
	{Sprite4: 0},
	{drvo5: 0},
	{Sprite6: 0},
	{ruka5: 0},
	{Sprite7: 0},
	{TiledBackground: 0},
	{player: 0},
	{tacke: 0},
	{tacke2: 0},
	{kapa: 0},
	{zid: 0},
	{Fade: 0},
	{Coin: 0},
	{ScoreText: 0},
	{Roads: 0},
	{Sprite: 0},
	{LiteTween: 0},
	{ogradapokretna: 0},
	{odgovor: 0},
	{maze: 0},
	{cilj: 0},
	{DragDrop: 0},
	{lopta: 0},
	{LevelsText: 0},
	{ruka6: 0},
	{CRVENA: 0},
	{ZELENA: 0},
	{zidZAMOSTZELENI: 0},
	{ruka7: 0},
	{zastava: 0},
	{Firework: 0},
	{Sprite9: 0},
	{upozerenja: 0},
	{BSound: 0},
	{Audio: 0},
	{gas: 0},
	{kocnica: 0},
	{drvo2: 0},
	{drvo3: 0},
	{kupigorivo: 0},
	{moregames: 0},
	{Browser: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{home: 0},
	{Sprite15: 0},
	{replay: 0},
	{Sprite16: 0},
	{auto2: 0},
	{auto3: 0},
	{Smoke: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{tacka: 0},
	{Rocket2: 0},
	{BG2: 0},
	{Anchor: 0},
	{skip: 0},
	{addfuelreklama: 0},
	{Sprite2: 0},
	{UPUTE: 0},
	{D: 0},
	{Open: 0},
	{Level: 0},
	{LevelsBlock: 0},
	{CoinsFont3: 0},
	{SpriteFont123: 0},
	{ShopCharacter1: 0},
	{ShopCharacter2: 0},
	{ShopCharacter3: 0},
	{ShopCharacter4: 0},
	{ShopCharacter5: 0},
	{ShopCharacter6: 0},
	{ShopCharacter7: 0},
	{ShopCharacter8: 0},
	{ShopCharacter9: 0},
	{ShopCharacter10: 0},
	{Lockdrugilik: 0},
	{Lockdrugilik2: 0},
	{Lockdrugilik3: 0},
	{Lockdrugilik4: 0},
	{Lockdrugilik5: 0},
	{Lockdrugilik6: 0},
	{Lockdrugilik7: 0},
	{Lockdrugilik8: 0},
	{Lockdrugilik9: 0},
	{StarsFont2: 0},
	{PlayerSkins: 0},
	{ShopSelector: 0},
	{ShopCharacter11: 0},
	{ShopCharacter12: 0},
	{ShopCharacter13: 0},
	{ShopCharacter14: 0},
	{ShopCharacter15: 0},
	{ShopCharacter16: 0},
	{ShopCharacter17: 0},
	{ShopCharacter18: 0},
	{ShopCharacter19: 0},
	{ShopCharacter20: 0},
	{Particles4: 0},
	{shopdugme: 0},
	{home2: 0},
	{Zoomtarget: 0},
	{ZoomTrigger: 0},
	{Camera: 0},
	{Id: 0},
	{Zooming: 0},
	{Tween: 0},
	{ShadowScrool: 0},
	{LeftMask: 0},
	{RightMask: 0},
	{Text2: 0},
	{addfuelreklama2: 0},
	{ScoreText2: 0},
	{UPUTE2: 0},
	{BG3: 0},
	{CoinsFont4: 0},
	{desnobalans: 0},
	{lijevobalans: 0},
	{spawncilj: 0},
	{trigerzakraj: 0},
	{spawncilj2: 0},
	{vozinazad: 0},
	{Sprite3: 0},
	{Ground4: 0},
	{zemlja2: 0},
	{dizalicapostolje: 0},
	{zemlja3: 0},
	{dizalicapostolje2: 0},
	{trigerzalift: 0},
	{dizalicapostolje3: 0},
	{trigerzalift2: 0},
	{Sprite5: 0},
	{Sprite8: 0},
	{Sprite11: 0},
	{dalje2: 0},
	{ScoreText3: 0},
	{ruka8: 0},
	{triggerzareklamu: 0},
	{PlayerSkins2: 0},
	{WeeGooSDK: 0},
	{buttons: 0},
	{gasikocnica: 0},
	{drva: 0},
	{Min_Zoom: 0},
	{Max_Zoom: 0},
	{MaX_Speed: 0},
	{speed: 0},
	{Unlock20: 0},
	{Unlock19: 0},
	{Unlock18: 0},
	{Unlock17: 0},
	{Unlock16: 0},
	{Unlock15: 0},
	{Unlock14: 0},
	{Unlock13: 0},
	{Unlock12: 0},
	{Unlock11: 0},
	{Unlock10: 0},
	{Unlock9: 0},
	{Unlock8: 0},
	{Unlock7: 0},
	{Unlock6: 0},
	{Unlock5: 0},
	{Unlock4: 0},
	{Unlock3: 0},
	{Unlock2: 0},
	{Unlock1: 0},
	{PlayerScore: 0},
	{character: 0},
	{unlocks: 0},
	{stars: 0},
	{LAST_LEVEL: 0},
	{WIN: 0},
	{sound: 0},
	{SoundEf: 0},
	{Score: 0},
	{Coins: 0},
	{Highscore: 0},
	{RocketGoAble: 0}
];

self.InstanceType = {
	dalje: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	car: class extends self.ISpriteInstance {},
	FrontWheel: class extends self.ISpriteInstance {},
	BackWheel: class extends self.ISpriteInstance {},
	Ground: class extends self.ISpriteInstance {},
	Guide: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Thrust: class extends self.IParticlesInstance {},
	Rocket: class extends self.ISpriteInstance {},
	Head: class extends self.ISpriteInstance {},
	Blood: class extends self.IParticlesInstance {},
	Touch: class extends self.IInstance {},
	Ground2: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	FuelTank: class extends self.ISpriteInstance {},
	DIS: class extends self.ITextInstance {},
	ScirraArcade: class extends self.IInstance {},
	Lava: class extends self.ISpriteInstance {},
	OutOfFuel: class extends self.ISpriteInstance {},
	FuelBar: class extends self.ITiledBackgroundInstance {},
	FuelBarBG: class extends self.ITiledBackgroundInstance {},
	Ground3: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	zemlja: class extends self.ISpriteInstance {},
	bomba: class extends self.ISpriteInstance {},
	drvo4: class extends self.ISpriteInstance {},
	kaktus: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	drvo5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	ruka5: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	player: class extends self.ISpriteInstance {},
	tacke: class extends self.ISpriteInstance {},
	tacke2: class extends self.ISpriteInstance {},
	kapa: class extends self.ISpriteInstance {},
	zid: class extends self.ISpriteInstance {},
	Coin: class extends self.ISpriteInstance {},
	ScoreText: class extends self.ISpriteFontInstance {},
	Roads: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	ogradapokretna: class extends self.ISpriteInstance {},
	odgovor: class extends self.ISpriteInstance {},
	maze: class extends self.ISpriteInstance {},
	cilj: class extends self.ISpriteInstance {},
	lopta: class extends self.ISpriteInstance {},
	LevelsText: class extends self.ISpriteFontInstance {},
	ruka6: class extends self.ISpriteInstance {},
	CRVENA: class extends self.ISpriteInstance {},
	ZELENA: class extends self.ISpriteInstance {},
	zidZAMOSTZELENI: class extends self.ISpriteInstance {},
	ruka7: class extends self.ISpriteInstance {},
	zastava: class extends self.ISpriteInstance {},
	Firework: class extends self.IParticlesInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	upozerenja: class extends self.ISpriteInstance {},
	BSound: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	gas: class extends self.ISpriteInstance {},
	kocnica: class extends self.ISpriteInstance {},
	drvo2: class extends self.ISpriteInstance {},
	drvo3: class extends self.ISpriteInstance {},
	kupigorivo: class extends self.ISpriteInstance {},
	moregames: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	replay: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	auto2: class extends self.ISpriteInstance {},
	auto3: class extends self.ISpriteInstance {},
	Smoke: class extends self.IParticlesInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	tacka: class extends self.ISpriteInstance {},
	Rocket2: class extends self.ISpriteInstance {},
	BG2: class extends self.ISpriteInstance {},
	skip: class extends self.ISpriteInstance {},
	addfuelreklama: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	UPUTE: class extends self.ISpriteInstance {},
	D: class extends self.ISpriteInstance {},
	LevelsBlock: class extends self.ISpriteInstance {},
	CoinsFont3: class extends self.ISpriteFontInstance {},
	SpriteFont123: class extends self.ISpriteFontInstance {},
	ShopCharacter1: class extends self.ISpriteInstance {},
	ShopCharacter2: class extends self.ISpriteInstance {},
	ShopCharacter3: class extends self.ISpriteInstance {},
	ShopCharacter4: class extends self.ISpriteInstance {},
	ShopCharacter5: class extends self.ISpriteInstance {},
	ShopCharacter6: class extends self.ISpriteInstance {},
	ShopCharacter7: class extends self.ISpriteInstance {},
	ShopCharacter8: class extends self.ISpriteInstance {},
	ShopCharacter9: class extends self.ISpriteInstance {},
	ShopCharacter10: class extends self.ISpriteInstance {},
	Lockdrugilik: class extends self.ISpriteInstance {},
	Lockdrugilik2: class extends self.ISpriteInstance {},
	Lockdrugilik3: class extends self.ISpriteInstance {},
	Lockdrugilik4: class extends self.ISpriteInstance {},
	Lockdrugilik5: class extends self.ISpriteInstance {},
	Lockdrugilik6: class extends self.ISpriteInstance {},
	Lockdrugilik7: class extends self.ISpriteInstance {},
	Lockdrugilik8: class extends self.ISpriteInstance {},
	Lockdrugilik9: class extends self.ISpriteInstance {},
	StarsFont2: class extends self.ISpriteFontInstance {},
	PlayerSkins: class extends self.ISpriteInstance {},
	ShopSelector: class extends self.ISpriteInstance {},
	ShopCharacter11: class extends self.ISpriteInstance {},
	ShopCharacter12: class extends self.ISpriteInstance {},
	ShopCharacter13: class extends self.ISpriteInstance {},
	ShopCharacter14: class extends self.ISpriteInstance {},
	ShopCharacter15: class extends self.ISpriteInstance {},
	ShopCharacter16: class extends self.ISpriteInstance {},
	ShopCharacter17: class extends self.ISpriteInstance {},
	ShopCharacter18: class extends self.ISpriteInstance {},
	ShopCharacter19: class extends self.ISpriteInstance {},
	ShopCharacter20: class extends self.ISpriteInstance {},
	Particles4: class extends self.IParticlesInstance {},
	shopdugme: class extends self.ISpriteInstance {},
	home2: class extends self.ISpriteInstance {},
	ZoomTrigger: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	Zooming: class extends self.ISpriteInstance {},
	ShadowScrool: class extends self.ISpriteInstance {},
	LeftMask: class extends self.ISpriteInstance {},
	RightMask: class extends self.ISpriteInstance {},
	Fade: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	addfuelreklama2: class extends self.ISpriteInstance {},
	ScoreText2: class extends self.ISpriteFontInstance {},
	UPUTE2: class extends self.ISpriteInstance {},
	BG3: class extends self.ISpriteInstance {},
	CoinsFont4: class extends self.ISpriteFontInstance {},
	desnobalans: class extends self.ISpriteInstance {},
	lijevobalans: class extends self.ISpriteInstance {},
	spawncilj: class extends self.ISpriteInstance {},
	trigerzakraj: class extends self.ISpriteInstance {},
	spawncilj2: class extends self.ISpriteInstance {},
	vozinazad: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Ground4: class extends self.ISpriteInstance {},
	zemlja2: class extends self.ISpriteInstance {},
	dizalicapostolje: class extends self.ISpriteInstance {},
	zemlja3: class extends self.ISpriteInstance {},
	dizalicapostolje2: class extends self.ISpriteInstance {},
	trigerzalift: class extends self.ISpriteInstance {},
	dizalicapostolje3: class extends self.ISpriteInstance {},
	trigerzalift2: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	dalje2: class extends self.ISpriteInstance {},
	ScoreText3: class extends self.ISpriteFontInstance {},
	ruka8: class extends self.ISpriteInstance {},
	triggerzareklamu: class extends self.ISpriteInstance {},
	PlayerSkins2: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	buttons: class extends self.ISpriteInstance {},
	gasikocnica: class extends self.ISpriteInstance {},
	drva: class extends self.ISpriteInstance {}
}