const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Keyboard,
		C3.Behaviors.Timer,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Plugins.TiledBg,
		C3.Plugins.gamepad,
		C3.Plugins.LocalStorage,
		C3.Plugins.Particles,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Acts.SetFunctionReturnValue
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{Player: 0},
	{EggAngle: 0},
	{Tween: 0},
	{Chicken: 0},
	{VectorX: 0},
	{VectorY: 0},
	{EggCollision: 0},
	{Keyboard: 0},
	{Ramp: 0},
	{Timer: 0},
	{GameManager: 0},
	{Flash: 0},
	{UserInterface: 0},
	{EggCatcher: 0},
	{Fade: 0},
	{EggTexture: 0},
	{Gamepad: 0},
	{LocalStorage: 0},
	{Particles: 0},
	{Overlay: 0},
	{UserInterfaceDropShadow: 0},
	{WeeGooSDK: 0},
	{AllowPlayerInput: 0},
	{HasStarted: 0},
	{CurrentDifficulty: 0},
	{EGGSBEFOREMAXDIFFICULTY: 0},
	{EASYEGGSPAWNINTERVAL: 0},
	{HARDEGGSPAWNINTERVAL: 0},
	{CurrentScore: 0},
	{MAXEXTRALIVES: 0},
	{RemainingExtraLives: 0},
	{HighScore: 0},
	{PreviousChickenUID: 0},
	{RAMPDETECTIONTHRESHOLD: 0},
	{WasOverlappingRamp: 0},
	{IsOverlappingRamp: 0},
	{OverlappingRampUID: 0},
	{Direction: 0},
	{CurrentValue: 0},
	{TargetValue: 0},
	{Speed: 0}
];

self.InstanceType = {
	Background: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Chicken: class extends self.ISpriteInstance {},
	EggCollision: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Ramp: class extends self.ISpriteInstance {},
	GameManager: class extends self.ISpriteInstance {},
	UserInterface: class extends self.ITextInstance {},
	EggCatcher: class extends self.ISpriteInstance {},
	Fade: class extends self.ITiledBackgroundInstance {},
	EggTexture: class extends self.ISpriteInstance {},
	Gamepad: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Particles: class extends self.IParticlesInstance {},
	Overlay: class extends self.ISpriteInstance {},
	UserInterfaceDropShadow: class extends self.ITextInstance {},
	WeeGooSDK: class extends self.IInstance {}
}