const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Behaviors.lunarray_LiteTween,
		C3.Plugins.Mouse,
		C3.Behaviors.Pin,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Plugins.Button,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.bound,
		C3.Behaviors.Fade,
		C3.Plugins.Keyboard,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.WGSDK.Cnds.RewardGranted,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Behaviors.lunarray_LiteTween.Acts.Stop,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.lunarray_LiteTween.Cnds.OnStart,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.LocalStorage.Cnds.OnAllGetsComplete,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.GoToLayoutByName
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sprite2: 0},
	{Sine: 0},
	{play: 0},
	{home: 0},
	{Sprite6: 0},
	{difference: 0},
	{ScoreTextt: 0},
	{Touch: 0},
	{Sprite7: 0},
	{sesir: 0},
	{hat: 0},
	{krug: 0},
	{Browser: 0},
	{vatromet: 0},
	{LiteTween: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Mouse: 0},
	{ploca: 0},
	{Pin: 0},
	{NEXTLEVEL: 0},
	{igrice: 0},
	{Sprite19: 0},
	{zvijezde: 0},
	{Fireworks1: 0},
	{Fireworks2: 0},
	{Fireworks5: 0},
	{Fireworks6: 0},
	{Fireworks4: 0},
	{Fireworks3: 0},
	{menu: 0},
	{welldone: 0},
	{difference2: 0},
	{Audio: 0},
	{BG_Table: 0},
	{BSound: 0},
	{Sprite20: 0},
	{Sprite23: 0},
	{ToolTip: 0},
	{Snow: 0},
	{Open: 0},
	{Level: 0},
	{LevelsBlock: 0},
	{select: 0},
	{SpriteFont123: 0},
	{LocalStorage: 0},
	{LevelsText: 0},
	{hintID: 0},
	{Hint: 0},
	{Button: 0},
	{difference1: 0},
	{difference3: 0},
	{difference4: 0},
	{difference5: 0},
	{difference6: 0},
	{hintreklama: 0},
	{BackgroundSprite: 0},
	{slikepozadina: 0},
	{slikepozadina2: 0},
	{frame: 0},
	{pozadinamenu: 0},
	{howto: 0},
	{start: 0},
	{wall2: 0},
	{wall3: 0},
	{menuploca: 0},
	{replayploca2: 0},
	{Sprite18: 0},
	{wall4: 0},
	{TimeFont: 0},
	{timeisup: 0},
	{menutimeup: 0},
	{replaytimeup: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{Sprite38: 0},
	{Sprite39: 0},
	{Sprite40: 0},
	{Sprite41: 0},
	{Sprite42: 0},
	{Sprite43: 0},
	{Sprite44: 0},
	{Sprite45: 0},
	{Sprite46: 0},
	{Sprite47: 0},
	{Sprite48: 0},
	{Sprite49: 0},
	{Sprite50: 0},
	{Sprite51: 0},
	{Sprite52: 0},
	{Sprite53: 0},
	{Sprite54: 0},
	{Sprite55: 0},
	{Sprite56: 0},
	{Sprite57: 0},
	{Sprite58: 0},
	{Sprite59: 0},
	{Sprite60: 0},
	{Sprite61: 0},
	{ponovo: 0},
	{Sprite62: 0},
	{Sprite3: 0},
	{"10sekundioff": 0},
	{hat1: 0},
	{KOCKAREKLAME: 0},
	{DragDrop: 0},
	{BoundToLayout: 0},
	{Scope: 0},
	{Lens: 0},
	{Sprite4: 0},
	{Lens2: 0},
	{Scope2: 0},
	{LEVELCLEARED: 0},
	{zvijezdenove: 0},
	{Sprite5: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite12: 0},
	{Scope3: 0},
	{Lens3: 0},
	{Sprite13: 0},
	{glavasprunkija: 0},
	{Fade: 0},
	{Sprite14: 0},
	{MessageBox: 0},
	{Sprite15: 0},
	{Keyboard: 0},
	{frame2: 0},
	{Sprite16: 0},
	{pozadinamenu2: 0},
	{pozadinamenu3: 0},
	{Sprite17: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite24: 0},
	{WeeGooSDK: 0},
	{buttons: 0},
	{DIFFERENCEDUGMAD: 0},
	{LastLevel: 0},
	{WIN: 0},
	{LevelComplete: 0},
	{LAST_LEVEL: 0},
	{Seconds: 0},
	{Pause: 0},
	{Minutes: 0},
	{CountSeconds: 0},
	{currentHintID: 0},
	{sound: 0},
	{SoundEf: 0},
	{Score: 0},
	{Highscore: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	difference: class extends self.ISpriteInstance {},
	ScoreTextt: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	hat: class extends self.ISpriteInstance {},
	krug: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	vatromet: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	ploca: class extends self.ISpriteInstance {},
	NEXTLEVEL: class extends self.ISpriteInstance {},
	igrice: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	zvijezde: class extends self.ISpriteInstance {},
	Fireworks1: class extends self.IParticlesInstance {},
	Fireworks2: class extends self.IParticlesInstance {},
	Fireworks5: class extends self.IParticlesInstance {},
	Fireworks6: class extends self.IParticlesInstance {},
	Fireworks4: class extends self.IParticlesInstance {},
	Fireworks3: class extends self.IParticlesInstance {},
	menu: class extends self.ISpriteInstance {},
	welldone: class extends self.ISpriteInstance {},
	difference2: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	BG_Table: class extends self.ISpriteInstance {},
	BSound: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Snow: class extends self.IParticlesInstance {},
	LevelsBlock: class extends self.ISpriteInstance {},
	select: class extends self.ISpriteInstance {},
	SpriteFont123: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	LevelsText: class extends self.ISpriteFontInstance {},
	Hint: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	difference1: class extends self.ISpriteInstance {},
	difference3: class extends self.ISpriteInstance {},
	difference4: class extends self.ISpriteInstance {},
	difference5: class extends self.ISpriteInstance {},
	difference6: class extends self.ISpriteInstance {},
	hintreklama: class extends self.ISpriteInstance {},
	BackgroundSprite: class extends self.ISpriteInstance {},
	slikepozadina: class extends self.ISpriteInstance {},
	slikepozadina2: class extends self.ISpriteInstance {},
	frame: class extends self.ISpriteInstance {},
	pozadinamenu: class extends self.ISpriteInstance {},
	howto: class extends self.ISpriteInstance {},
	start: class extends self.ISpriteInstance {},
	wall2: class extends self.ISpriteInstance {},
	wall3: class extends self.ISpriteInstance {},
	menuploca: class extends self.ISpriteInstance {},
	replayploca2: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	wall4: class extends self.ISpriteInstance {},
	TimeFont: class extends self.ISpriteFontInstance {},
	timeisup: class extends self.ISpriteInstance {},
	menutimeup: class extends self.ISpriteInstance {},
	replaytimeup: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	Sprite49: class extends self.ISpriteInstance {},
	Sprite50: class extends self.ISpriteInstance {},
	Sprite51: class extends self.ISpriteInstance {},
	Sprite52: class extends self.ISpriteInstance {},
	Sprite53: class extends self.ISpriteInstance {},
	Sprite54: class extends self.ISpriteInstance {},
	Sprite55: class extends self.ISpriteInstance {},
	Sprite56: class extends self.ISpriteInstance {},
	Sprite57: class extends self.ISpriteInstance {},
	Sprite58: class extends self.ISpriteInstance {},
	Sprite59: class extends self.ISpriteInstance {},
	Sprite60: class extends self.ISpriteInstance {},
	Sprite61: class extends self.ISpriteInstance {},
	ponovo: class extends self.ISpriteInstance {},
	Sprite62: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	_10sekundioff: class extends self.ISpriteInstance {},
	hat1: class extends self.ISpriteInstance {},
	KOCKAREKLAME: class extends self.ISpriteInstance {},
	Scope: class extends self.ISpriteInstance {},
	Lens: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Lens2: class extends self.ISpriteInstance {},
	Scope2: class extends self.ISpriteInstance {},
	LEVELCLEARED: class extends self.ISpriteInstance {},
	zvijezdenove: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Scope3: class extends self.ISpriteInstance {},
	Lens3: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	glavasprunkija: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	MessageBox: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	frame2: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	pozadinamenu2: class extends self.ISpriteInstance {},
	pozadinamenu3: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends C3.Plugins.WGSDK.Instance {},
	buttons: class extends self.ISpriteInstance {},
	DIFFERENCEDUGMAD: class extends self.ISpriteInstance {}
}