const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Behaviors.Bullet,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Plugins.Function,
		C3.Plugins.Share,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.Spritefont2.Acts.SetCharacterWidth,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.System.Acts.SetFullscreenQuality,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sprite10: 0},
	{Sine: 0},
	{spawn: 0},
	{delete: 0},
	{nub: 0},
	{platform: 0},
	{gameOver: 0},
	{NAME: 0},
	{platformB: 0},
	{up: 0},
	{Rotate: 0},
	{Panda: 0},
	{Shuriken1: 0},
	{Shuriken2: 0},
	{Shuriken3: 0},
	{Bullet: 0},
	{Fruit: 0},
	{Sprite14: 0},
	{Sound: 0},
	{restart: 0},
	{MoreGame2: 0},
	{Menu: 0},
	{Play: 0},
	{bestScore: 0},
	{fruct: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Audio: 0},
	{Browser: 0},
	{Touch: 0},
	{SpriteFont: 0},
	{SpriteFont2: 0},
	{SpriteFont3: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{GameResultsFont: 0},
	{Sprite4: 0},
	{Explosion: 0},
	{Pause: 0},
	{Function: 0},
	{Share: 0},
	{tochUP: 0},
	{blfon: 0},
	{Fade: 0},
	{EFFECT: 0},
	{LastScoreFont: 0},
	{Sprite16: 0},
	{Text: 0},
	{Sprite5: 0},
	{WeeGooSDK: 0},
	{MoreGame: 0},
	{sound: 0},
	{best: 0},
	{score: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	spawn: class extends self.ISpriteInstance {},
	delete: class extends self.ISpriteInstance {},
	nub: class extends self.ISpriteInstance {},
	platform: class extends self.ISpriteInstance {},
	gameOver: class extends self.ISpriteInstance {},
	NAME: class extends self.ISpriteInstance {},
	platformB: class extends self.ISpriteInstance {},
	Panda: class extends self.ISpriteInstance {},
	Shuriken1: class extends self.ISpriteInstance {},
	Shuriken2: class extends self.ISpriteInstance {},
	Shuriken3: class extends self.ISpriteInstance {},
	Fruit: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sound: class extends self.ISpriteInstance {},
	restart: class extends self.ISpriteInstance {},
	MoreGame2: class extends self.ISpriteInstance {},
	Menu: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	bestScore: class extends self.ISpriteInstance {},
	fruct: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	SpriteFont3: class extends self.ISpriteFontInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	GameResultsFont: class extends self.ISpriteFontInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	Pause: class extends self.ISpriteInstance {},
	Function: class extends self.IInstance {},
	Share: class extends self.IInstance {},
	tochUP: class extends self.ISpriteInstance {},
	blfon: class extends self.ISpriteInstance {},
	EFFECT: class extends self.ISpriteInstance {},
	LastScoreFont: class extends self.ISpriteFontInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {}
}