const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.Particles,
		C3.Behaviors.scrollto,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.WGSDK,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Text.Exps.Text,
		C3.JavaScriptInEvents.Game_Event28_Act1,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.JavaScriptInEvents.Game_Event41_Act1,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.JavaScriptInEvents.Game_Event54_Act1,
		C3.JavaScriptInEvents.Game_Event67_Act1,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.JavaScriptInEvents.Make_donut_es_Event9_Act2,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Text.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{setting_btn: 0},
	{setting_text: 0},
	{Settings_BG: 0},
	{State: 0},
	{Tween: 0},
	{Settings_btn_indicate: 0},
	{Settings_music_text: 0},
	{Settings_sound_text: 0},
	{ToggleButton: 0},
	{setttings_close_btn: 0},
	{level_icon: 0},
	{levelmenu_text: 0},
	{NextLevelMenu_Icon: 0},
	{PrevLevelMenu_Icon: 0},
	{donut_sprite: 0},
	{donut_holder: 0},
	{donut_selector: 0},
	{DonutMakerText: 0},
	{life: 0},
	{Game_Menu_btn: 0},
	{tick_cross: 0},
	{trans_black: 0},
	{WINLOSEscreenBG: 0},
	{GreatJobBadJob: 0},
	{winlose_next_level_btn: 0},
	{winlose_restart_btn: 0},
	{winlose_mainmenu_btn: 0},
	{ConfettiSprite: 0},
	{ConfettiParticles: 0},
	{ScrollTo: 0},
	{BG: 0},
	{Logo1_Shape: 0},
	{Logo2_Shape: 0},
	{Play_btn: 0},
	{Donut_deco: 0},
	{Touch: 0},
	{Number_Font: 0},
	{GameInstruction: 0},
	{TheGameInstructionMini: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{Browser: 0},
	{WeeGooSDK: 0},
	{btns: 0},
	{level_menu_index: 0},
	{most_level_menu_index: 0},
	{most_level_unlocked: 0},
	{sound_state: 0},
	{music_state: 0},
	{Selected_Anime_Name: 0},
	{Selected_Anime_Index: 0},
	{Selected_obj_id: 0},
	{life_amount: 0},
	{game_type: 0},
	{state: 0},
	{make_donut_shape: 0},
	{make_donut_color_id: 0},
	{position_to_be_placed_x: 0},
	{position_to_be_placed_y: 0},
	{loopindex_var: 0}
];

self.InstanceType = {
	setting_btn: class extends self.ISpriteInstance {},
	setting_text: class extends self.ISpriteInstance {},
	Settings_BG: class extends self.ISpriteInstance {},
	Settings_btn_indicate: class extends self.ISpriteInstance {},
	Settings_music_text: class extends self.ISpriteInstance {},
	Settings_sound_text: class extends self.ISpriteInstance {},
	ToggleButton: class extends self.ISpriteInstance {},
	setttings_close_btn: class extends self.ISpriteInstance {},
	level_icon: class extends self.ISpriteInstance {},
	levelmenu_text: class extends self.ISpriteInstance {},
	NextLevelMenu_Icon: class extends self.ISpriteInstance {},
	PrevLevelMenu_Icon: class extends self.ISpriteInstance {},
	donut_sprite: class extends self.ISpriteInstance {},
	donut_holder: class extends self.ISpriteInstance {},
	donut_selector: class extends self.ISpriteInstance {},
	DonutMakerText: class extends self.ITextInstance {},
	life: class extends self.ISpriteInstance {},
	Game_Menu_btn: class extends self.ISpriteInstance {},
	tick_cross: class extends self.ISpriteInstance {},
	trans_black: class extends self.ISpriteInstance {},
	WINLOSEscreenBG: class extends self.ISpriteInstance {},
	GreatJobBadJob: class extends self.ISpriteInstance {},
	winlose_next_level_btn: class extends self.ISpriteInstance {},
	winlose_restart_btn: class extends self.ISpriteInstance {},
	winlose_mainmenu_btn: class extends self.ISpriteInstance {},
	ConfettiSprite: class extends self.ISpriteInstance {},
	ConfettiParticles: class extends self.IParticlesInstance {},
	BG: class extends self.ISpriteInstance {},
	Logo1_Shape: class extends self.ISpriteInstance {},
	Logo2_Shape: class extends self.ISpriteInstance {},
	Play_btn: class extends self.ISpriteInstance {},
	Donut_deco: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Number_Font: class extends self.ISpriteFontInstance {},
	GameInstruction: class extends self.ITextInstance {},
	TheGameInstructionMini: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	WeeGooSDK: class extends self.IInstance {},
	btns: class extends self.ISpriteInstance {}
}