const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.wrap,
		C3.Behaviors.Physics,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Behaviors.Sin,
		C3.Plugins.Button,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Plugins.Browser,
		C3.Behaviors.Pin,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.EightDir,
		C3.Plugins.Mouse,
		C3.Plugins.LocalStorage,
		C3.Behaviors.lunarray_LiteTween,
		C3.Plugins.WGSDK,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetPos
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{Wrap: 0},
	{Physics: 0},
	{Player: 0},
	{Solid: 0},
	{Bullet: 0},
	{Piso: 0},
	{LineaMortal: 0},
	{GameOverLabel: 0},
	{Touch: 0},
	{Sine: 0},
	{PuntosLabel: 0},
	{Mejor: 0},
	{Text: 0},
	{Text2: 0},
	{Text3: 0},
	{jugar: 0},
	{instrucciones: 0},
	{regresar: 0},
	{LeftScreen: 0},
	{RightScreen: 0},
	{Keyboard: 0},
	{Bonus: 0},
	{Piso2: 0},
	{Audio: 0},
	{Fade: 0},
	{Ouch: 0},
	{Particles: 0},
	{zvuk: 0},
	{zvuk1: 0},
	{transparencia: 0},
	{Sprite: 0},
	{play: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite2: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{obj_ballparticles: 0},
	{Sprite8: 0},
	{Piso3: 0},
	{Player2: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{home: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Browser: 0},
	{santa: 0},
	{Sprite12: 0},
	{Sprite16: 0},
	{Pin: 0},
	{Sprite17: 0},
	{zaslova: 0},
	{BreathBubbles: 0},
	{DragDrop: 0},
	{Sprite37: 0},
	{"8Direction": 0},
	{JetBubbles: 0},
	{JetBubbleszaboba: 0},
	{Sprite18: 0},
	{Piso4: 0},
	{Mouse: 0},
	{Sprite5: 0},
	{LocalStorage: 0},
	{playerName: 0},
	{LiteTween: 0},
	{play2: 0},
	{WeeGooSDK: 0},
	{buttons: 0},
	{ClaveMejor: 0},
	{Highscore: 0},
	{Score: 0},
	{ClaveMejor2: 0},
	{MejorPuntuacion2: 0},
	{Puntuacion2: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Piso: class extends self.ISpriteInstance {},
	LineaMortal: class extends self.ISpriteInstance {},
	GameOverLabel: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	PuntosLabel: class extends self.ITextInstance {},
	Mejor: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	jugar: class extends self.IButtonInstance {},
	instrucciones: class extends self.IButtonInstance {},
	regresar: class extends self.IButtonInstance {},
	LeftScreen: class extends self.ISpriteInstance {},
	RightScreen: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Bonus: class extends self.ISpriteInstance {},
	Piso2: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Ouch: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	zvuk: class extends self.ISpriteInstance {},
	zvuk1: class extends self.ISpriteInstance {},
	transparencia: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	obj_ballparticles: class extends self.IParticlesInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Piso3: class extends self.ISpriteInstance {},
	Player2: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	santa: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	zaslova: class extends self.ISpriteInstance {},
	BreathBubbles: class extends self.IParticlesInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	JetBubbles: class extends self.IParticlesInstance {},
	JetBubbleszaboba: class extends self.IParticlesInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Piso4: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	playerName: class extends self.ITextInstance {},
	play2: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	buttons: class extends self.ISpriteInstance {}
}