const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Plugins.Particles,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.LocalStorage.Cnds.IsProcessingGets,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Exps.originalwindowwidth,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Spritefont2.Exps.LayerName,
		C3.Plugins.Spritefont2.Exps.Height,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Spritefont2.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Touch.Exps.TouchCount,
		C3.Plugins.System.Cnds.PickOverlappingPoint,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.GameEvent
	];
};
self.C3_JsPropNameTable = [
	{LocalStorage: 0},
	{Touch: 0},
	{Mouse: 0},
	{Audio: 0},
	{Active: 0},
	{Original_Width: 0},
	{Original_Height: 0},
	{Button_Exit: 0},
	{Button_Fullscreen: 0},
	{Button_More_Games: 0},
	{Button_Music: 0},
	{Button_Play: 0},
	{Button_Sound: 0},
	{Show: 0},
	{Hide: 0},
	{Object_Width: 0},
	{Object_Height: 0},
	{Button_Start: 0},
	{Button_Menu: 0},
	{Button_Reload: 0},
	{Button_Return: 0},
	{Button_Pause: 0},
	{Button_Restart: 0},
	{Button_Facebook: 0},
	{Button_Twitter: 0},
	{Button_Store: 0},
	{Button_Next: 0},
	{Button_Next_Booster: 0},
	{Button_Previous_Booster: 0},
	{Button_Ads: 0},
	{Button_Buy: 0},
	{Orientation_Font: 0},
	{Total_Score_Font: 0},
	{Game_Score_Font: 0},
	{Block_ID: 0},
	{Blocks_Font: 0},
	{Booster_Name: 0},
	{Boosters_Font: 0},
	{Level_Font: 0},
	{Moves_Font: 0},
	{Big_Level_Font: 0},
	{Blocks_Popup_Font: 0},
	{Coins_Font: 0},
	{Price_Font: 0},
	{Text_Paused: 0},
	{Fade: 0},
	{Text_Game_Over: 0},
	{Text_Tap_To_Play: 0},
	{Text_You_Score: 0},
	{Text_Loading: 0},
	{Text_Level_Completed: 0},
	{Text_Level_Failed: 0},
	{Sine: 0},
	{Text_Perfect: 0},
	{Text_Awesome: 0},
	{Text_Try_Again: 0},
	{Text_Good_Work: 0},
	{Text_Level: 0},
	{Store: 0},
	{Text_Boosters: 0},
	{Black_Screen: 0},
	{Red_Screen: 0},
	{Frame_Pause: 0},
	{Frame_Level: 0},
	{Blocks_Icon: 0},
	{Booster_Change_Block: 0},
	{Booster_Cut_Block: 0},
	{Booster_Cut_Column: 0},
	{Booster_Cut_Row: 0},
	{Frame_Moves: 0},
	{Stars_Big: 0},
	{Stars_Small: 0},
	{Blocks_Done: 0},
	{Blocks_Popup: 0},
	{Blocks_Popup_Done: 0},
	{Separator: 0},
	{Boosters_Shop: 0},
	{Coins: 0},
	{Store_Window: 0},
	{Game_Icon: 0},
	{Game_Logo: 0},
	{LifeLost: 0},
	{Empty: 0},
	{Column: 0},
	{HighLight: 0},
	{Stopper: 0},
	{Hold: 0},
	{Drop: 0},
	{Picked: 0},
	{Frame: 0},
	{Single: 0},
	{Destroyed: 0},
	{Blocks: 0},
	{Block_Destroyer: 0},
	{Background: 0},
	{Tiles: 0},
	{Log_Frame: 0},
	{Log: 0},
	{Log_Frame_Big: 0},
	{Sprite: 0},
	{Particles: 0},
	{Foreground_Bottom_Right: 0},
	{Foreground_Top_Left: 0},
	{Foreground_Bottom_Left: 0},
	{Foreground_Top_Right: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{WeeGooSDK: 0},
	{Buttons: 0},
	{Spawn_Effect: 0},
	{Texts: 0},
	{Boosters: 0},
	{Sound: 0},
	{Sound_Status: 0},
	{Sound_Volume: 0},
	{Music: 0},
	{Music_Status: 0},
	{Music_Volume: 0},
	{Fullscreen: 0},
	{Size_Difference: 0},
	{Current_Distance: 0},
	{DISTANCE_BETWEEN_OBJECTS: 0},
	{Game_Status: 0},
	{Score: 0},
	{Total_Score: 0},
	{Booster_Cut_Row_Count: 0},
	{Booster_Cut_Block_Count: 0},
	{Booster_Cut_Column_Count: 0},
	{Booster_Change_Block_Count: 0},
	{Booster_Change_Block_Current_Block_Frame: 0},
	{Block_Frames: 0},
	{Block_Type_1: 0},
	{Block_Type_1_Count: 0},
	{Block_Type_1_Target: 0},
	{Block_Type_1_All_Count: 0},
	{Block_Type_2: 0},
	{Block_Type_2_Count: 0},
	{Block_Type_2_Target: 0},
	{Block_Type_2_All_Count: 0},
	{Block_Type_3: 0},
	{Block_Type_3_Count: 0},
	{Block_Type_3_Target: 0},
	{Block_Type_3_All_Count: 0},
	{Block_Y: 0},
	{Column_X: 0},
	{Column_Y: 0},
	{Stars: 0},
	{Saved_Level_Type: 0},
	{Difficulty_Level: 0},
	{SingleOne: 0},
	{Remain: 0},
	{ActiveBlockColor: 0},
	{Take: 0},
	{Total: 0},
	{ActiveColumn: 0},
	{Block_Size: 0},
	{Column_Speed_X: 0},
	{Block_Fall_Speed_Y: 0},
	{Max_Level: 0},
	{Level: 0},
	{Moves: 0},
	{Wait_Timer: 0},
	{DESCRIPTION: 0},
	{REDIRECT_URL: 0},
	{IMAGE: 0},
	{Max_Coins: 0},
	{Count_Coins: 0},
	{Max_Boosters: 0},
	{Current_Booster: 0},
	{Booster_1_Price: 0},
	{Booster_2_Price: 0},
	{Booster_3_Price: 0},
	{Booster_4_Price: 0}
];

self.InstanceType = {
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Button_Exit: class extends self.ISpriteInstance {},
	Button_Fullscreen: class extends self.ISpriteInstance {},
	Button_More_Games: class extends self.ISpriteInstance {},
	Button_Music: class extends self.ISpriteInstance {},
	Button_Play: class extends self.ISpriteInstance {},
	Button_Sound: class extends self.ISpriteInstance {},
	Button_Start: class extends self.ISpriteInstance {},
	Button_Menu: class extends self.ISpriteInstance {},
	Button_Reload: class extends self.ISpriteInstance {},
	Button_Return: class extends self.ISpriteInstance {},
	Button_Pause: class extends self.ISpriteInstance {},
	Button_Restart: class extends self.ISpriteInstance {},
	Button_Facebook: class extends self.ISpriteInstance {},
	Button_Twitter: class extends self.ISpriteInstance {},
	Button_Store: class extends self.ISpriteInstance {},
	Button_Next: class extends self.ISpriteInstance {},
	Button_Next_Booster: class extends self.ISpriteInstance {},
	Button_Previous_Booster: class extends self.ISpriteInstance {},
	Button_Ads: class extends self.ISpriteInstance {},
	Button_Buy: class extends self.ISpriteInstance {},
	Orientation_Font: class extends self.ISpriteFontInstance {},
	Total_Score_Font: class extends self.ISpriteFontInstance {},
	Game_Score_Font: class extends self.ISpriteFontInstance {},
	Blocks_Font: class extends self.ISpriteFontInstance {},
	Boosters_Font: class extends self.ISpriteFontInstance {},
	Level_Font: class extends self.ISpriteFontInstance {},
	Moves_Font: class extends self.ISpriteFontInstance {},
	Big_Level_Font: class extends self.ISpriteFontInstance {},
	Blocks_Popup_Font: class extends self.ISpriteFontInstance {},
	Coins_Font: class extends self.ISpriteFontInstance {},
	Price_Font: class extends self.ISpriteFontInstance {},
	Text_Paused: class extends self.ISpriteInstance {},
	Text_Game_Over: class extends self.ISpriteInstance {},
	Text_Tap_To_Play: class extends self.ISpriteInstance {},
	Text_You_Score: class extends self.ISpriteInstance {},
	Text_Loading: class extends self.ISpriteInstance {},
	Text_Level_Completed: class extends self.ISpriteInstance {},
	Text_Level_Failed: class extends self.ISpriteInstance {},
	Text_Perfect: class extends self.ISpriteInstance {},
	Text_Awesome: class extends self.ISpriteInstance {},
	Text_Try_Again: class extends self.ISpriteInstance {},
	Text_Good_Work: class extends self.ISpriteInstance {},
	Text_Level: class extends self.ISpriteInstance {},
	Store: class extends self.ISpriteInstance {},
	Text_Boosters: class extends self.ISpriteInstance {},
	Black_Screen: class extends self.ISpriteInstance {},
	Red_Screen: class extends self.ISpriteInstance {},
	Frame_Pause: class extends self.ISpriteInstance {},
	Frame_Level: class extends self.ISpriteInstance {},
	Blocks_Icon: class extends self.ISpriteInstance {},
	Booster_Change_Block: class extends self.ISpriteInstance {},
	Booster_Cut_Block: class extends self.ISpriteInstance {},
	Booster_Cut_Column: class extends self.ISpriteInstance {},
	Booster_Cut_Row: class extends self.ISpriteInstance {},
	Frame_Moves: class extends self.ISpriteInstance {},
	Stars_Big: class extends self.ISpriteInstance {},
	Stars_Small: class extends self.ISpriteInstance {},
	Blocks_Done: class extends self.ISpriteInstance {},
	Blocks_Popup: class extends self.ISpriteInstance {},
	Blocks_Popup_Done: class extends self.ISpriteInstance {},
	Separator: class extends self.ISpriteInstance {},
	Boosters_Shop: class extends self.ISpriteInstance {},
	Coins: class extends self.ISpriteInstance {},
	Store_Window: class extends self.ISpriteInstance {},
	Game_Icon: class extends self.ISpriteInstance {},
	Game_Logo: class extends self.ISpriteInstance {},
	LifeLost: class extends self.ISpriteInstance {},
	Column: class extends self.ISpriteInstance {},
	HighLight: class extends self.ISpriteInstance {},
	Stopper: class extends self.ISpriteInstance {},
	Blocks: class extends self.ISpriteInstance {},
	Block_Destroyer: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Tiles: class extends self.ITiledBackgroundInstance {},
	Log_Frame: class extends self.ISpriteInstance {},
	Log: class extends self.ISpriteInstance {},
	Log_Frame_Big: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Foreground_Bottom_Right: class extends self.ISpriteInstance {},
	Foreground_Top_Left: class extends self.ISpriteInstance {},
	Foreground_Bottom_Left: class extends self.ISpriteInstance {},
	Foreground_Top_Right: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	Buttons: class extends self.ISpriteInstance {},
	Spawn_Effect: class extends self.ISpriteInstance {},
	Texts: class extends self.ISpriteInstance {},
	Boosters: class extends self.ISpriteInstance {}
}