const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.LocalStorage,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.TiledBg.Acts.SetTowardPosition,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Particles.Cnds.CompareY,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{Size: 0},
	{ID: 0},
	{Tween: 0},
	{DrawingPart: 0},
	{Touch: 0},
	{Line: 0},
	{Sine: 0},
	{SineSize: 0},
	{Draw: 0},
	{Rotate: 0},
	{Sine2: 0},
	{Confetti: 0},
	{Esmaecer: 0},
	{P_Confetti: 0},
	{Flash: 0},
	{Logo: 0},
	{Senóide: 0},
	{BtnPlay: 0},
	{Btn_sound: 0},
	{P_btn: 0},
	{Number: 0},
	{btn_levels: 0},
	{Btn_tip: 0},
	{txt_quantityHlp: 0},
	{Btn_pLevel: 0},
	{Fade: 0},
	{Brights: 0},
	{P_Tip: 0},
	{icon_tutorial: 0},
	{txt_level: 0},
	{Btn_RightL: 0},
	{Btn_LeftL: 0},
	{Drag_lvl: 0},
	{LocalStorege: 0},
	{Keyboard: 0},
	{txt_slevel: 0},
	{Btn_back: 0},
	{Mouse: 0},
	{txt_tip: 0},
	{Fadee: 0},
	{txt_Congratulations: 0},
	{Audio: 0},
	{btn_more: 0},
	{Browser: 0},
	{WeeGooSDK: 0},
	{F_btns: 0},
	{prevX: 0},
	{prevY: 0},
	{DrawingCorrect: 0},
	{Q_TipTouched: 0},
	{Q_Tip: 0},
	{EarnTip: 0},
	{CurrentLevel: 0},
	{CompletedLevel: 0}
];

self.InstanceType = {
	DrawingPart: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Line: class extends self.ITiledBackgroundInstance {},
	Draw: class extends self.ISpriteInstance {},
	Confetti: class extends self.ISpriteInstance {},
	P_Confetti: class extends self.IParticlesInstance {},
	Flash: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	Btn_sound: class extends self.ISpriteInstance {},
	P_btn: class extends self.IParticlesInstance {},
	btn_levels: class extends self.ISpriteInstance {},
	Btn_tip: class extends self.ISpriteInstance {},
	txt_quantityHlp: class extends self.ITextInstance {},
	Btn_pLevel: class extends self.ISpriteInstance {},
	Fade: class extends self.ISpriteInstance {},
	Brights: class extends self.ISpriteInstance {},
	P_Tip: class extends self.IParticlesInstance {},
	icon_tutorial: class extends self.ISpriteInstance {},
	txt_level: class extends self.ITextInstance {},
	Btn_RightL: class extends self.ISpriteInstance {},
	Btn_LeftL: class extends self.ISpriteInstance {},
	Drag_lvl: class extends self.ISpriteInstance {},
	LocalStorege: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	txt_slevel: class extends self.ITextInstance {},
	Btn_back: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	txt_tip: class extends self.ITextInstance {},
	txt_Congratulations: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	btn_more: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	WeeGooSDK: class extends self.IInstance {},
	F_btns: class extends self.ISpriteInstance {}
}