const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.Text,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Sprite.Acts.SetSize
	];
};
self.C3_JsPropNameTable = [
	{ID: 0},
	{colorID: 0},
	{DrawJoint: 0},
	{Tween: 0},
	{BGCircle: 0},
	{Touch: 0},
	{Browser: 0},
	{DrawLine: 0},
	{used: 0},
	{Rotate: 0},
	{Sine: 0},
	{Cell: 0},
	{CurrDrawArray: 0},
	{ColorPallete: 0},
	{AJAX: 0},
	{CellsArray: 0},
	{Text: 0},
	{Reset: 0},
	{Background: 0},
	{Magnifier: 0},
	{WeeGooSDK: 0},
	{Drawing: 0},
	{Cells: 0},
	{NLEVELS: 0},
	{startPointUID: 0},
	{startPointColor: 0},
	{lastX: 0},
	{lastY: 0},
	{nextID: 0},
	{currLevel: 0},
	{x: 0},
	{y: 0},
	{distPos: 0},
	{numUsedCells: 0}
];

self.InstanceType = {
	DrawJoint: class extends self.ISpriteInstance {},
	BGCircle: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	DrawLine: class extends self.ISpriteInstance {},
	Cell: class extends self.ISpriteInstance {},
	CurrDrawArray: class extends self.IArrayInstance {},
	ColorPallete: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	CellsArray: class extends self.IArrayInstance {},
	Text: class extends self.ITextInstance {},
	Reset: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Magnifier: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	Drawing: class extends self.ISpriteInstance {},
	Cells: class extends self.ISpriteInstance {}
}