const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Mouse,
		C3.Behaviors.Pin,
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Plugins.Keyboard,
		C3.Plugins.Spritefont2,
		C3.Plugins.NinePatch,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.LocalStorage,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Platform,
		C3.Behaviors.Bullet,
		C3.Behaviors.Flash,
		C3.Behaviors.Physics,
		C3.Behaviors.DragnDrop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.AdvancedRandom.Acts.CreatePermutationTable,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.AdvancedRandom.Exps.Permutation,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.NinePatch.Cnds.OnCreated,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.NinePatch.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.TiledBg.Acts.SetZElevation,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStart,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStop,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardSetRecord,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardPublishRecord,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsFullscreenStart,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsFullscreenClose,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedStart,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedClose,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.SetTweensDestroyOnComplete,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsRewardedPlaying,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Eponesh_GameScore.Cnds.IsPaused,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Eponesh_GameScore.Exps.PaymentsCurProductCurrencySymbol,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowSticky,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsStickyAvailable,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsStickyPlaying,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Eponesh_GameScore.Cnds.IsPlayerStub,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardOpenScoped,
		C3.Plugins.Text.Acts.ZMoveToObject,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsPreloaderStart,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsPreloaderClose,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsPreloaderPlaying,
		C3.Plugins.Eponesh_GameScore.Acts.PaymentsPurchase,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPaymentsPurchase,
		C3.Plugins.Eponesh_GameScore.Acts.PaymentsConsume,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPaymentsConsume,
		C3.Plugins.Eponesh_GameScore.Cnds.IsPaymentsAvailable,
		C3.Plugins.Eponesh_GameScore.Cnds.PaymentsPickProduct,
		C3.Plugins.Eponesh_GameScore.Cnds.IsPaymentsCurProductPurchased,
		C3.Plugins.Eponesh_GameScore.Exps.PaymentsCurProductTag,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.Pathfinding.Cnds.IsMoving,
		C3.Behaviors.Pathfinding.Cnds.OnArrived,
		C3.Plugins.System.Cnds.PickRandom,
		C3.ScriptsInEvents.Menucode_Event400_Act1,
		C3.ScriptsInEvents.Menucode_Event401_Act1,
		C3.ScriptsInEvents.Menucode_Event402_Act1,
		C3.ScriptsInEvents.Menucode_Event403_Act1,
		C3.ScriptsInEvents.Menucode_Event404_Act1,
		C3.ScriptsInEvents.Menucode_Event405_Act1,
		C3.ScriptsInEvents.Menucode_Event406_Act1,
		C3.ScriptsInEvents.Menucode_Event407_Act1,
		C3.ScriptsInEvents.Menucode_Event408_Act1,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.int
	];
};
self.C3_JsPropNameTable = [
	{CardIndex: 0},
	{Active: 0},
	{Ready: 0},
	{beh_tween: 0},
	{Card: 0},
	{Mouse: 0},
	{beh_pin: 0},
	{CardShadow: 0},
	{SelectedCards: 0},
	{Browser: 0},
	{AdvancedRandom: 0},
	{GlowParticles: 0},
	{beh_fade: 0},
	{Flash: 0},
	{Table: 0},
	{CardsRandomizer: 0},
	{Keyboard: 0},
	{FontID: 0},
	{Fade: 0},
	{Text: 0},
	{SelectedArea: 0},
	{Touch: 0},
	{PlatformInfo: 0},
	{GamePush: 0},
	{Твинанимация: 0},
	{Button: 0},
	{Cards: 0},
	{Levels1MetalButtonsIcons: 0},
	{x: 0},
	{Аудио: 0},
	{Tutor: 0},
	{ReminedCards: 0},
	{home: 0},
	{IMG_: 0},
	{Level: 0},
	{levelsIdle: 0},
	{Спрайт: 0},
	{Спрайт2: 0},
	{Спрайт3: 0},
	{Спрайт4: 0},
	{Спрайт5: 0},
	{Спрайт6: 0},
	{Спрайт7: 0},
	{Спрайт8: 0},
	{Спрайт9: 0},
	{Спрайт10: 0},
	{levelsIdle2: 0},
	{levelsIdle3: 0},
	{levelsIdle4: 0},
	{levelsIdle5: 0},
	{levelsIdle6: 0},
	{levelsIdle7: 0},
	{levelsIdle8: 0},
	{levelsIdle9: 0},
	{levelsIdle10: 0},
	{levelsIdle11: 0},
	{levelsIdle12: 0},
	{levelsIdle13: 0},
	{levelsIdle14: 0},
	{levelsIdle15: 0},
	{levelsIdle16: 0},
	{levelsIdle17: 0},
	{levelsIdle18: 0},
	{levelsIdle19: 0},
	{levelsIdle20: 0},
	{levelsIdle21: 0},
	{levelsIdle22: 0},
	{levelsIdle23: 0},
	{levelsIdle24: 0},
	{levelsIdle25: 0},
	{levelsIdle26: 0},
	{levelsIdle27: 0},
	{levelsIdle28: 0},
	{levelsIdle29: 0},
	{levelsIdle30: 0},
	{levelsIdle31: 0},
	{levelsIdle32: 0},
	{levelsIdle33: 0},
	{levelsIdle34: 0},
	{levelsIdle35: 0},
	{levelsIdle36: 0},
	{levelsIdle37: 0},
	{levelsIdle38: 0},
	{levelsIdle39: 0},
	{levelsIdle40: 0},
	{levelsIdle41: 0},
	{levelsIdle42: 0},
	{levelsIdle43: 0},
	{levelsIdle44: 0},
	{LocalStorage: 0},
	{IMG_2: 0},
	{Block2: 0},
	{Block3: 0},
	{Block4: 0},
	{Block5: 0},
	{Block6: 0},
	{Block7: 0},
	{Block8: 0},
	{Block9: 0},
	{Block10: 0},
	{Block11: 0},
	{Block12: 0},
	{Block13: 0},
	{Block14: 0},
	{Block15: 0},
	{Block16: 0},
	{Block17: 0},
	{Block18: 0},
	{Block19: 0},
	{Block20: 0},
	{Block21: 0},
	{Block22: 0},
	{Block23: 0},
	{Block24: 0},
	{Block25: 0},
	{Block26: 0},
	{Block27: 0},
	{Block28: 0},
	{Block29: 0},
	{Block30: 0},
	{Block31: 0},
	{Block32: 0},
	{Block33: 0},
	{Block34: 0},
	{Block35: 0},
	{Block36: 0},
	{Block37: 0},
	{Block38: 0},
	{Block39: 0},
	{Block40: 0},
	{Block41: 0},
	{Block42: 0},
	{Block43: 0},
	{Block44: 0},
	{Button2: 0},
	{adsidle: 0},
	{text5: 0},
	{text6: 0},
	{text7: 0},
	{text8: 0},
	{"1coins": 0},
	{Tower_Blue: 0},
	{buycastle: 0},
	{G_Idle_NoShadow: 0},
	{G_Idle: 0},
	{Текст: 0},
	{Частицы: 0},
	{buyRatue: 0},
	{buyratuetext: 0},
	{buytowertext: 0},
	{no: 0},
	{Спрайт12: 0},
	{buyhousetext: 0},
	{buyhouse: 0},
	{buytower: 0},
	{Info: 0},
	{Tutorial: 0},
	{Array_save: 0},
	{Текст2: 0},
	{leaderidle: 0},
	{levelsIdle45: 0},
	{levelsIdle46: 0},
	{levelsIdle47: 0},
	{levelsIdle48: 0},
	{levelsIdle49: 0},
	{levelsIdle50: 0},
	{levelsIdle51: 0},
	{levelsIdle52: 0},
	{levelsIdle53: 0},
	{levelsIdle54: 0},
	{levelsIdle55: 0},
	{levelsIdle56: 0},
	{levelsIdle57: 0},
	{levelsIdle58: 0},
	{levelsIdle59: 0},
	{levelsIdle60: 0},
	{levelsIdle61: 0},
	{levelsIdle62: 0},
	{levelsIdle63: 0},
	{levelsIdle64: 0},
	{levelsIdle65: 0},
	{levelsIdle66: 0},
	{levelsIdle67: 0},
	{levelsIdle68: 0},
	{levelsIdle69: 0},
	{levelsIdle70: 0},
	{levelsIdle71: 0},
	{levelsIdle72: 0},
	{levelsIdle73: 0},
	{levelsIdle74: 0},
	{levelsIdle75: 0},
	{levelsIdle76: 0},
	{levelsIdle77: 0},
	{levelsIdle78: 0},
	{levelsIdle79: 0},
	{levelsIdle80: 0},
	{levelsIdle81: 0},
	{levelsIdle82: 0},
	{levelsIdle83: 0},
	{levelsIdle84: 0},
	{levelsIdle85: 0},
	{levelsIdle86: 0},
	{levelsIdle87: 0},
	{levelsIdle88: 0},
	{levelsIdle89: 0},
	{levelsIdle90: 0},
	{levelsIdle91: 0},
	{levelsIdle92: 0},
	{levelsIdle93: 0},
	{levelsIdle94: 0},
	{levelsIdle95: 0},
	{levelsIdle96: 0},
	{levelsIdle97: 0},
	{levelsIdle98: 0},
	{levelsIdle99: 0},
	{levelsIdle100: 0},
	{Block45: 0},
	{Block46: 0},
	{Block47: 0},
	{Block48: 0},
	{Block49: 0},
	{Block50: 0},
	{Block51: 0},
	{Block52: 0},
	{Block53: 0},
	{Block54: 0},
	{Block55: 0},
	{Block56: 0},
	{Block57: 0},
	{Block58: 0},
	{Block59: 0},
	{Block60: 0},
	{Block61: 0},
	{Block62: 0},
	{Block63: 0},
	{Block64: 0},
	{Block65: 0},
	{Block66: 0},
	{Block67: 0},
	{Block68: 0},
	{Block69: 0},
	{Block70: 0},
	{Block71: 0},
	{Block72: 0},
	{Block73: 0},
	{Block74: 0},
	{Block75: 0},
	{Block76: 0},
	{Block77: 0},
	{Block78: 0},
	{Block79: 0},
	{Block80: 0},
	{Block81: 0},
	{Block82: 0},
	{Block83: 0},
	{Block84: 0},
	{Block85: 0},
	{Block86: 0},
	{Block87: 0},
	{Block88: 0},
	{Block89: 0},
	{Block90: 0},
	{Block91: 0},
	{Block92: 0},
	{Block93: 0},
	{Block94: 0},
	{Block95: 0},
	{Block96: 0},
	{Block97: 0},
	{Block98: 0},
	{Block99: 0},
	{Block100: 0},
	{Текст3: 0},
	{offeridleMetalButtonsIcons: 0},
	{coin: 0},
	{coin2: 0},
	{coin3: 0},
	{coin4: 0},
	{coin5: 0},
	{coin66fotor: 0},
	{coin6: 0},
	{Button_Blue_9Slides_Pressed: 0},
	{Pressed_: 0},
	{Disable_: 0},
	{text10: 0},
	{Currency: 0},
	{pressRamButtons: 0},
	{pressRamButtons2: 0},
	{pressRamButtons3: 0},
	{pressRamButtons4: 0},
	{pressRamButtons5: 0},
	{pressRamButtons6: 0},
	{pressRamButtons7: 0},
	{Currency2: 0},
	{Currency3: 0},
	{Currency4: 0},
	{Currency5: 0},
	{Currency6: 0},
	{Currency7: 0},
	{Structures: 0},
	{MapDecorations: 0},
	{Tiles: 0},
	{Твёрдый: 0},
	{готитмельницаTinyRanch_Structuresfotor: 0},
	{волна1TinyRanch_Tiles: 0},
	{PrevX: 0},
	{ПоискПути: 0},
	{цыпленок_TinyRanch_Animals: 0},
	{Платформер: 0},
	{курица_TinyRanch_Animals: 0},
	{корова_TinyRanch_Animals: 0},
	{кот_TinyRanch_Animals: 0},
	{собака_TinyRanch_Animals: 0},
	{ценникмельница: 0},
	{Амбар: 0},
	{ГлинянныйДом: 0},
	{ДеревянныйДом: 0},
	{КаменныйДом: 0},
	{КирпичныйДом: 0},
	{Коровник: 0},
	{мастерская: 0},
	{ценник_курица_TinyRanch_Animals2: 0},
	{ценник_корова_TinyRanch_Animals2: 0},
	{стальнаяЗаготовка: 0},
	{деревяннаяЗаготовка: 0},
	{пацанчик: 0},
	{СтенкаКурятника: 0},
	{молоко: 0},
	{яйцо: 0},
	{коробка: 0},
	{Текст4: 0},
	{Button_Blue_9Slides_Pressed2: 0},
	{СтенкаКоровника: 0},
	{buycat: 0},
	{buycattext: 0},
	{buydog: 0},
	{buydogtext: 0},
	{Пуля: 0},
	{котценник_TinyRanch_Animals: 0},
	{собакаценник_TinyRanch_Animals: 0},
	{buyцыпленок: 0},
	{buyцыпленокtext: 0},
	{цыпленокценник_TinyRanch_Animals: 0},
	{точкихожденияботиков: 0},
	{золотойкот_TinyRanch_Animals: 0},
	{золотаясобака_TinyRanch_Animals: 0},
	{buygoldcattext: 0},
	{buygoldcat: 0},
	{ценникзолотойкот_TinyRanch_Animals: 0},
	{buygolddog: 0},
	{buygolddogtext: 0},
	{ценникзолотаясобака_TinyRanch_Animals: 0},
	{buyfarm: 0},
	{TextFruitShadow: 0},
	{Tween: 0},
	{TextFruit: 0},
	{TextScore: 0},
	{TextTutorial: 0},
	{TextGameOver: 0},
	{Physics: 0},
	{Limits: 0},
	{Fader: 0},
	{Background: 0},
	{"DALL·E20250305002844A2DBackgroundForACasualMobileGameAboutPackingFarmProductsTheSceneShouldHaveACleanWarmAndCozyAtmosphereWithAWoodenTableOr": 0},
	{Counting: 0},
	{HasGold: 0},
	{IsCounted: 0},
	{box: 0},
	{eggboxempty: 0},
	{IsGold: 0},
	{Перетаскивание: 0},
	{egg: 0},
	{milk: 0},
	{goldegg: 0},
	{goldmilk: 0},
	{TrashBin: 0},
	{badmilk: 0},
	{badegg: 0},
	{buywoodhouse: 0},
	{buywoodhousetext: 0},
	{buyblockhouse: 0},
	{buyblockhousetext: 0},
	{КирпичныйДом2: 0},
	{buygoose: 0},
	{buygoosetext: 0},
	{Гусь: 0},
	{Гусьценник: 0},
	{leaderproducers: 0},
	{leadergoldenfarm: 0},
	{Текстproducers: 0},
	{Текстgoldenfarm: 0},
	{Тексттутор: 0},
	{музыкаНорм: 0},
	{выборуровняненажат: 0},
	{Topcoins: 0},
	{Текст5: 0},
	{Farm: 0},
	{Текст7: 0},
	{MatchingPairs: 0},
	{LevelSelection: 0},
	{Coinstexttutor: 0},
	{Packaging: 0},
	{поварстоит: 0},
	{ковбойстоит: 0},
	{CARDSMAXHEIGHT: 0},
	{ActiveCards: 0},
	{ReadyCards: 0},
	{FinishLevels: 0},
	{LevelTimer: 0},
	{MaxTime: 0},
	{LevelNumber: 0},
	{GamePaused: 0},
	{Coins: 0},
	{LevelReward: 0},
	{LevelCompleted: 0},
	{Fullscreen: 0},
	{Step: 0},
	{CURSORBORDER: 0},
	{CurrentCursorSpeed: 0},
	{CursorAngle: 0},
	{ShowCards: 0},
	{OpenLevels: 0},
	{StateCastle: 0},
	{StateTower: 0},
	{StateHouse: 0},
	{Statewoodhouse: 0},
	{StatewoodhouseUI: 0},
	{Stateblockhouse: 0},
	{StateblockhouseUI: 0},
	{GoldDog: 0},
	{GoldCat: 0},
	{GoldAnimal: 0},
	{Dog: 0},
	{Cat: 0},
	{Cipa: 0},
	{Chickens: 0},
	{Cows: 0},
	{Muteaudio: 0},
	{Goods: 0},
	{MilkTimer: 0},
	{EggTimer: 0},
	{Goose: 0},
	{EggProductionTicked: 0},
	{ItemCount: 0},
	{BoxCount: 0},
	{IsBoxMoving: 0},
	{BadItemChance: 0}
];

self.InstanceType = {
	Card: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	CardShadow: class extends self.ISpriteInstance {},
	SelectedCards: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	AdvancedRandom: class extends self.IInstance {},
	GlowParticles: class extends self.IParticlesInstance {},
	Flash: class extends self.ITiledBackgroundInstance {},
	Table: class extends self.ITiledBackgroundInstance {},
	CardsRandomizer: class extends self.IArrayInstance {},
	Keyboard: class extends self.IInstance {},
	Text: class extends self.ISpriteFontInstance {},
	SelectedArea: class extends self.IWorldInstance {},
	Touch: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	GamePush: class extends self.C3.Plugins.Eponesh_GameScore.Instance {},
	Button: class extends self.ISpriteInstance {},
	Cards: class extends self.IArrayInstance {},
	Levels1MetalButtonsIcons: class extends self.ISpriteInstance {},
	x: class extends self.ISpriteInstance {},
	Аудио: class extends self.IInstance {},
	Tutor: class extends self.ITextInstance {},
	ReminedCards: class extends self.ITextInstance {},
	home: class extends self.ISpriteInstance {},
	IMG_: class extends self.ISpriteInstance {},
	levelsIdle: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	levelsIdle2: class extends self.ISpriteInstance {},
	levelsIdle3: class extends self.ISpriteInstance {},
	levelsIdle4: class extends self.ISpriteInstance {},
	levelsIdle5: class extends self.ISpriteInstance {},
	levelsIdle6: class extends self.ISpriteInstance {},
	levelsIdle7: class extends self.ISpriteInstance {},
	levelsIdle8: class extends self.ISpriteInstance {},
	levelsIdle9: class extends self.ISpriteInstance {},
	levelsIdle10: class extends self.ISpriteInstance {},
	levelsIdle11: class extends self.ISpriteInstance {},
	levelsIdle12: class extends self.ISpriteInstance {},
	levelsIdle13: class extends self.ISpriteInstance {},
	levelsIdle14: class extends self.ISpriteInstance {},
	levelsIdle15: class extends self.ISpriteInstance {},
	levelsIdle16: class extends self.ISpriteInstance {},
	levelsIdle17: class extends self.ISpriteInstance {},
	levelsIdle18: class extends self.ISpriteInstance {},
	levelsIdle19: class extends self.ISpriteInstance {},
	levelsIdle20: class extends self.ISpriteInstance {},
	levelsIdle21: class extends self.ISpriteInstance {},
	levelsIdle22: class extends self.ISpriteInstance {},
	levelsIdle23: class extends self.ISpriteInstance {},
	levelsIdle24: class extends self.ISpriteInstance {},
	levelsIdle25: class extends self.ISpriteInstance {},
	levelsIdle26: class extends self.ISpriteInstance {},
	levelsIdle27: class extends self.ISpriteInstance {},
	levelsIdle28: class extends self.ISpriteInstance {},
	levelsIdle29: class extends self.ISpriteInstance {},
	levelsIdle30: class extends self.ISpriteInstance {},
	levelsIdle31: class extends self.ISpriteInstance {},
	levelsIdle32: class extends self.ISpriteInstance {},
	levelsIdle33: class extends self.ISpriteInstance {},
	levelsIdle34: class extends self.ISpriteInstance {},
	levelsIdle35: class extends self.ISpriteInstance {},
	levelsIdle36: class extends self.ISpriteInstance {},
	levelsIdle37: class extends self.ISpriteInstance {},
	levelsIdle38: class extends self.ISpriteInstance {},
	levelsIdle39: class extends self.ISpriteInstance {},
	levelsIdle40: class extends self.ISpriteInstance {},
	levelsIdle41: class extends self.ISpriteInstance {},
	levelsIdle42: class extends self.ISpriteInstance {},
	levelsIdle43: class extends self.ISpriteInstance {},
	levelsIdle44: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	IMG_2: class extends self.ISpriteInstance {},
	Block2: class extends self.ISpriteInstance {},
	Block3: class extends self.ISpriteInstance {},
	Block4: class extends self.ISpriteInstance {},
	Block5: class extends self.ISpriteInstance {},
	Block6: class extends self.ISpriteInstance {},
	Block7: class extends self.ISpriteInstance {},
	Block8: class extends self.ISpriteInstance {},
	Block9: class extends self.ISpriteInstance {},
	Block10: class extends self.ISpriteInstance {},
	Block11: class extends self.ISpriteInstance {},
	Block12: class extends self.ISpriteInstance {},
	Block13: class extends self.ISpriteInstance {},
	Block14: class extends self.ISpriteInstance {},
	Block15: class extends self.ISpriteInstance {},
	Block16: class extends self.ISpriteInstance {},
	Block17: class extends self.ISpriteInstance {},
	Block18: class extends self.ISpriteInstance {},
	Block19: class extends self.ISpriteInstance {},
	Block20: class extends self.ISpriteInstance {},
	Block21: class extends self.ISpriteInstance {},
	Block22: class extends self.ISpriteInstance {},
	Block23: class extends self.ISpriteInstance {},
	Block24: class extends self.ISpriteInstance {},
	Block25: class extends self.ISpriteInstance {},
	Block26: class extends self.ISpriteInstance {},
	Block27: class extends self.ISpriteInstance {},
	Block28: class extends self.ISpriteInstance {},
	Block29: class extends self.ISpriteInstance {},
	Block30: class extends self.ISpriteInstance {},
	Block31: class extends self.ISpriteInstance {},
	Block32: class extends self.ISpriteInstance {},
	Block33: class extends self.ISpriteInstance {},
	Block34: class extends self.ISpriteInstance {},
	Block35: class extends self.ISpriteInstance {},
	Block36: class extends self.ISpriteInstance {},
	Block37: class extends self.ISpriteInstance {},
	Block38: class extends self.ISpriteInstance {},
	Block39: class extends self.ISpriteInstance {},
	Block40: class extends self.ISpriteInstance {},
	Block41: class extends self.ISpriteInstance {},
	Block42: class extends self.ISpriteInstance {},
	Block43: class extends self.ISpriteInstance {},
	Block44: class extends self.ISpriteInstance {},
	Button2: class extends self.ISpriteInstance {},
	adsidle: class extends self.ISpriteInstance {},
	text5: class extends self.ITextInstance {},
	text6: class extends self.ITextInstance {},
	text7: class extends self.ITextInstance {},
	text8: class extends self.ITextInstance {},
	_1coins: class extends self.ITextInstance {},
	Tower_Blue: class extends self.ISpriteInstance {},
	buycastle: class extends self.ISpriteInstance {},
	G_Idle_NoShadow: class extends self.ISpriteInstance {},
	G_Idle: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	Частицы: class extends self.IParticlesInstance {},
	buyRatue: class extends self.ISpriteInstance {},
	buyratuetext: class extends self.ITextInstance {},
	buytowertext: class extends self.ITextInstance {},
	no: class extends self.ITextInstance {},
	Спрайт12: class extends self.ISpriteInstance {},
	buyhousetext: class extends self.ITextInstance {},
	buyhouse: class extends self.ISpriteInstance {},
	buytower: class extends self.ISpriteInstance {},
	Info: class extends self.ISpriteInstance {},
	Tutorial: class extends self.ITextInstance {},
	Array_save: class extends self.IArrayInstance {},
	Текст2: class extends self.ITextInstance {},
	leaderidle: class extends self.ISpriteInstance {},
	levelsIdle45: class extends self.ISpriteInstance {},
	levelsIdle46: class extends self.ISpriteInstance {},
	levelsIdle47: class extends self.ISpriteInstance {},
	levelsIdle48: class extends self.ISpriteInstance {},
	levelsIdle49: class extends self.ISpriteInstance {},
	levelsIdle50: class extends self.ISpriteInstance {},
	levelsIdle51: class extends self.ISpriteInstance {},
	levelsIdle52: class extends self.ISpriteInstance {},
	levelsIdle53: class extends self.ISpriteInstance {},
	levelsIdle54: class extends self.ISpriteInstance {},
	levelsIdle55: class extends self.ISpriteInstance {},
	levelsIdle56: class extends self.ISpriteInstance {},
	levelsIdle57: class extends self.ISpriteInstance {},
	levelsIdle58: class extends self.ISpriteInstance {},
	levelsIdle59: class extends self.ISpriteInstance {},
	levelsIdle60: class extends self.ISpriteInstance {},
	levelsIdle61: class extends self.ISpriteInstance {},
	levelsIdle62: class extends self.ISpriteInstance {},
	levelsIdle63: class extends self.ISpriteInstance {},
	levelsIdle64: class extends self.ISpriteInstance {},
	levelsIdle65: class extends self.ISpriteInstance {},
	levelsIdle66: class extends self.ISpriteInstance {},
	levelsIdle67: class extends self.ISpriteInstance {},
	levelsIdle68: class extends self.ISpriteInstance {},
	levelsIdle69: class extends self.ISpriteInstance {},
	levelsIdle70: class extends self.ISpriteInstance {},
	levelsIdle71: class extends self.ISpriteInstance {},
	levelsIdle72: class extends self.ISpriteInstance {},
	levelsIdle73: class extends self.ISpriteInstance {},
	levelsIdle74: class extends self.ISpriteInstance {},
	levelsIdle75: class extends self.ISpriteInstance {},
	levelsIdle76: class extends self.ISpriteInstance {},
	levelsIdle77: class extends self.ISpriteInstance {},
	levelsIdle78: class extends self.ISpriteInstance {},
	levelsIdle79: class extends self.ISpriteInstance {},
	levelsIdle80: class extends self.ISpriteInstance {},
	levelsIdle81: class extends self.ISpriteInstance {},
	levelsIdle82: class extends self.ISpriteInstance {},
	levelsIdle83: class extends self.ISpriteInstance {},
	levelsIdle84: class extends self.ISpriteInstance {},
	levelsIdle85: class extends self.ISpriteInstance {},
	levelsIdle86: class extends self.ISpriteInstance {},
	levelsIdle87: class extends self.ISpriteInstance {},
	levelsIdle88: class extends self.ISpriteInstance {},
	levelsIdle89: class extends self.ISpriteInstance {},
	levelsIdle90: class extends self.ISpriteInstance {},
	levelsIdle91: class extends self.ISpriteInstance {},
	levelsIdle92: class extends self.ISpriteInstance {},
	levelsIdle93: class extends self.ISpriteInstance {},
	levelsIdle94: class extends self.ISpriteInstance {},
	levelsIdle95: class extends self.ISpriteInstance {},
	levelsIdle96: class extends self.ISpriteInstance {},
	levelsIdle97: class extends self.ISpriteInstance {},
	levelsIdle98: class extends self.ISpriteInstance {},
	levelsIdle99: class extends self.ISpriteInstance {},
	levelsIdle100: class extends self.ISpriteInstance {},
	Block45: class extends self.ISpriteInstance {},
	Block46: class extends self.ISpriteInstance {},
	Block47: class extends self.ISpriteInstance {},
	Block48: class extends self.ISpriteInstance {},
	Block49: class extends self.ISpriteInstance {},
	Block50: class extends self.ISpriteInstance {},
	Block51: class extends self.ISpriteInstance {},
	Block52: class extends self.ISpriteInstance {},
	Block53: class extends self.ISpriteInstance {},
	Block54: class extends self.ISpriteInstance {},
	Block55: class extends self.ISpriteInstance {},
	Block56: class extends self.ISpriteInstance {},
	Block57: class extends self.ISpriteInstance {},
	Block58: class extends self.ISpriteInstance {},
	Block59: class extends self.ISpriteInstance {},
	Block60: class extends self.ISpriteInstance {},
	Block61: class extends self.ISpriteInstance {},
	Block62: class extends self.ISpriteInstance {},
	Block63: class extends self.ISpriteInstance {},
	Block64: class extends self.ISpriteInstance {},
	Block65: class extends self.ISpriteInstance {},
	Block66: class extends self.ISpriteInstance {},
	Block67: class extends self.ISpriteInstance {},
	Block68: class extends self.ISpriteInstance {},
	Block69: class extends self.ISpriteInstance {},
	Block70: class extends self.ISpriteInstance {},
	Block71: class extends self.ISpriteInstance {},
	Block72: class extends self.ISpriteInstance {},
	Block73: class extends self.ISpriteInstance {},
	Block74: class extends self.ISpriteInstance {},
	Block75: class extends self.ISpriteInstance {},
	Block76: class extends self.ISpriteInstance {},
	Block77: class extends self.ISpriteInstance {},
	Block78: class extends self.ISpriteInstance {},
	Block79: class extends self.ISpriteInstance {},
	Block80: class extends self.ISpriteInstance {},
	Block81: class extends self.ISpriteInstance {},
	Block82: class extends self.ISpriteInstance {},
	Block83: class extends self.ISpriteInstance {},
	Block84: class extends self.ISpriteInstance {},
	Block85: class extends self.ISpriteInstance {},
	Block86: class extends self.ISpriteInstance {},
	Block87: class extends self.ISpriteInstance {},
	Block88: class extends self.ISpriteInstance {},
	Block89: class extends self.ISpriteInstance {},
	Block90: class extends self.ISpriteInstance {},
	Block91: class extends self.ISpriteInstance {},
	Block92: class extends self.ISpriteInstance {},
	Block93: class extends self.ISpriteInstance {},
	Block94: class extends self.ISpriteInstance {},
	Block95: class extends self.ISpriteInstance {},
	Block96: class extends self.ISpriteInstance {},
	Block97: class extends self.ISpriteInstance {},
	Block98: class extends self.ISpriteInstance {},
	Block99: class extends self.ISpriteInstance {},
	Block100: class extends self.ISpriteInstance {},
	Текст3: class extends self.ITextInstance {},
	offeridleMetalButtonsIcons: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	coin2: class extends self.ISpriteInstance {},
	coin3: class extends self.ISpriteInstance {},
	coin4: class extends self.ISpriteInstance {},
	coin5: class extends self.ISpriteInstance {},
	coin66fotor: class extends self.ISpriteInstance {},
	coin6: class extends self.ISpriteInstance {},
	Button_Blue_9Slides_Pressed: class extends self.ISpriteInstance {},
	Pressed_: class extends self.ISpriteInstance {},
	Disable_: class extends self.ISpriteInstance {},
	text10: class extends self.ITextInstance {},
	Currency: class extends self.ITextInstance {},
	pressRamButtons: class extends self.ISpriteInstance {},
	pressRamButtons2: class extends self.ISpriteInstance {},
	pressRamButtons3: class extends self.ISpriteInstance {},
	pressRamButtons4: class extends self.ISpriteInstance {},
	pressRamButtons5: class extends self.ISpriteInstance {},
	pressRamButtons6: class extends self.ISpriteInstance {},
	pressRamButtons7: class extends self.ISpriteInstance {},
	Currency2: class extends self.ITextInstance {},
	Currency3: class extends self.ITextInstance {},
	Currency4: class extends self.ITextInstance {},
	Currency5: class extends self.ITextInstance {},
	Currency6: class extends self.ITextInstance {},
	Currency7: class extends self.ITextInstance {},
	Structures: class extends self.ITilemapInstance {},
	MapDecorations: class extends self.ITilemapInstance {},
	Tiles: class extends self.ITilemapInstance {},
	готитмельницаTinyRanch_Structuresfotor: class extends self.ISpriteInstance {},
	волна1TinyRanch_Tiles: class extends self.ISpriteInstance {},
	цыпленок_TinyRanch_Animals: class extends self.ISpriteInstance {},
	курица_TinyRanch_Animals: class extends self.ISpriteInstance {},
	корова_TinyRanch_Animals: class extends self.ISpriteInstance {},
	кот_TinyRanch_Animals: class extends self.ISpriteInstance {},
	собака_TinyRanch_Animals: class extends self.ISpriteInstance {},
	ценникмельница: class extends self.ISpriteInstance {},
	Амбар: class extends self.ISpriteInstance {},
	ГлинянныйДом: class extends self.ISpriteInstance {},
	ДеревянныйДом: class extends self.ISpriteInstance {},
	КаменныйДом: class extends self.ISpriteInstance {},
	КирпичныйДом: class extends self.ISpriteInstance {},
	Коровник: class extends self.ISpriteInstance {},
	мастерская: class extends self.ISpriteInstance {},
	ценник_курица_TinyRanch_Animals2: class extends self.ISpriteInstance {},
	ценник_корова_TinyRanch_Animals2: class extends self.ISpriteInstance {},
	стальнаяЗаготовка: class extends self.ISpriteInstance {},
	деревяннаяЗаготовка: class extends self.ISpriteInstance {},
	пацанчик: class extends self.ISpriteInstance {},
	СтенкаКурятника: class extends self.ISpriteInstance {},
	молоко: class extends self.ISpriteInstance {},
	яйцо: class extends self.ISpriteInstance {},
	коробка: class extends self.ISpriteInstance {},
	Текст4: class extends self.ITextInstance {},
	Button_Blue_9Slides_Pressed2: class extends self.ISpriteInstance {},
	СтенкаКоровника: class extends self.ISpriteInstance {},
	buycat: class extends self.ISpriteInstance {},
	buycattext: class extends self.ITextInstance {},
	buydog: class extends self.ISpriteInstance {},
	buydogtext: class extends self.ITextInstance {},
	котценник_TinyRanch_Animals: class extends self.ISpriteInstance {},
	собакаценник_TinyRanch_Animals: class extends self.ISpriteInstance {},
	buyцыпленок: class extends self.ISpriteInstance {},
	buyцыпленокtext: class extends self.ITextInstance {},
	цыпленокценник_TinyRanch_Animals: class extends self.ISpriteInstance {},
	точкихожденияботиков: class extends self.ISpriteInstance {},
	золотойкот_TinyRanch_Animals: class extends self.ISpriteInstance {},
	золотаясобака_TinyRanch_Animals: class extends self.ISpriteInstance {},
	buygoldcattext: class extends self.ITextInstance {},
	buygoldcat: class extends self.ISpriteInstance {},
	ценникзолотойкот_TinyRanch_Animals: class extends self.ISpriteInstance {},
	buygolddog: class extends self.ISpriteInstance {},
	buygolddogtext: class extends self.ITextInstance {},
	ценникзолотаясобака_TinyRanch_Animals: class extends self.ISpriteInstance {},
	buyfarm: class extends self.ISpriteInstance {},
	TextFruitShadow: class extends self.ITextInstance {},
	TextFruit: class extends self.ITextInstance {},
	TextScore: class extends self.ITextInstance {},
	TextTutorial: class extends self.ITextInstance {},
	TextGameOver: class extends self.ITextInstance {},
	Limits: class extends self.ITiledBackgroundInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	Background: class extends self.ISpriteInstance {},
	__InvalidName0__: class extends self.ISpriteInstance {},
	box: class extends self.ISpriteInstance {},
	eggboxempty: class extends self.ISpriteInstance {},
	egg: class extends self.ISpriteInstance {},
	milk: class extends self.ISpriteInstance {},
	goldegg: class extends self.ISpriteInstance {},
	goldmilk: class extends self.ISpriteInstance {},
	TrashBin: class extends self.ISpriteInstance {},
	badmilk: class extends self.ISpriteInstance {},
	badegg: class extends self.ISpriteInstance {},
	buywoodhouse: class extends self.ISpriteInstance {},
	buywoodhousetext: class extends self.ITextInstance {},
	buyblockhouse: class extends self.ISpriteInstance {},
	buyblockhousetext: class extends self.ITextInstance {},
	КирпичныйДом2: class extends self.ISpriteInstance {},
	buygoose: class extends self.ISpriteInstance {},
	buygoosetext: class extends self.ITextInstance {},
	Гусь: class extends self.ISpriteInstance {},
	Гусьценник: class extends self.ISpriteInstance {},
	leaderproducers: class extends self.ISpriteInstance {},
	leadergoldenfarm: class extends self.ISpriteInstance {},
	Текстproducers: class extends self.ITextInstance {},
	Текстgoldenfarm: class extends self.ITextInstance {},
	Тексттутор: class extends self.ITextInstance {},
	музыкаНорм: class extends self.ISpriteInstance {},
	выборуровняненажат: class extends self.ISpriteInstance {},
	Topcoins: class extends self.ITextInstance {},
	Текст5: class extends self.ITextInstance {},
	Farm: class extends self.ITextInstance {},
	Текст7: class extends self.ITextInstance {},
	MatchingPairs: class extends self.ITextInstance {},
	LevelSelection: class extends self.ITextInstance {},
	Coinstexttutor: class extends self.ITextInstance {},
	Packaging: class extends self.ITextInstance {},
	поварстоит: class extends self.ISpriteInstance {},
	ковбойстоит: class extends self.ISpriteInstance {}
}