const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Behaviors.Fade,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Particles,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsFullscreenStart,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsPreloaderStart,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsFullscreenClose,
		C3.Plugins.Audio.Cnds.IsAnyPlaying,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsPreloaderClose,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedStart,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedClose,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowSticky,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowPreloader,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Exps.windowwidth,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsPreloaderPlaying,
		C3.Plugins.Sprite.Exps.ImagePointCount,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.Tween.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.Particles.Acts.SetXRandomiser,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerReset
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Browser: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{loaderPan: 0},
	{LoaderMask: 0},
	{Tween: 0},
	{Loader: 0},
	{dynamic: 0},
	{Game_Bg: 0},
	{id: 0},
	{Sine: 0},
	{Game_play_obj: 0},
	{Pin: 0},
	{Spot: 0},
	{ImgPt: 0},
	{Touch_obj: 0},
	{Hint: 0},
	{Opacity: 0},
	{Wrong: 0},
	{Wrong_place: 0},
	{Wrong2: 0},
	{Wrong3: 0},
	{Hint_btn: 0},
	{Refresh: 0},
	{Volume: 0},
	{Fail_replay: 0},
	{Fail_bg: 0},
	{text: 0},
	{keyboard: 0},
	{Твинанимация: 0},
	{star: 0},
	{Угасание: 0},
	{text2: 0},
	{AJAX: 0},
	{ArrayLang: 0},
	{part1: 0},
	{part2: 0},
	{part3: 0},
	{part4: 0},
	{part5: 0},
	{text3: 0},
	{text4: 0},
	{text5: 0},
	{text6: 0},
	{hintCircle: 0},
	{hintText: 0},
	{GameScore: 0},
	{Obj_Touch: 0},
	{Ui_fam: 0},
	{Ad_mute: 0},
	{Ad_time: 0},
	{Lang: 0},
	{Imgpoint: 0},
	{Transision_control: 0},
	{Sound: 0},
	{Score: 0},
	{Total_Score: 0},
	{Loader_Width: 0},
	{Correct_fun: 0},
	{Wrong_fun: 0},
	{Fail: 0},
	{Hin_fun_break: 0},
	{Count: 0},
	{In_point: 0},
	{Live_Lev: 0},
	{scale_touch: 0},
	{FireworkCount: 0},
	{hintCounter: 0},
	{particle: 0},
	{X2: 0},
	{X1: 0},
	{AdBlock: 0},
	{pause: 0},
	{Cur_lev: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	loaderPan: class extends self.ISpriteInstance {},
	LoaderMask: class extends self.ISpriteInstance {},
	Loader: class extends self.ISpriteInstance {},
	Game_Bg: class extends self.ISpriteInstance {},
	Game_play_obj: class extends self.ISpriteInstance {},
	Spot: class extends self.ISpriteInstance {},
	Touch_obj: class extends self.ISpriteInstance {},
	Hint: class extends self.ISpriteInstance {},
	Opacity: class extends self.ISpriteInstance {},
	Wrong: class extends self.ISpriteInstance {},
	Wrong_place: class extends self.ISpriteInstance {},
	Wrong2: class extends self.ISpriteInstance {},
	Wrong3: class extends self.ISpriteInstance {},
	Hint_btn: class extends self.ISpriteInstance {},
	Refresh: class extends self.ISpriteInstance {},
	Volume: class extends self.ISpriteInstance {},
	Fail_replay: class extends self.ISpriteInstance {},
	Fail_bg: class extends self.ISpriteInstance {},
	text: class extends self.ITextInstance {},
	keyboard: class extends self.IInstance {},
	star: class extends self.ISpriteInstance {},
	text2: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	ArrayLang: class extends self.IArrayInstance {},
	part1: class extends self.IParticlesInstance {},
	part2: class extends self.IParticlesInstance {},
	part3: class extends self.IParticlesInstance {},
	part4: class extends self.IParticlesInstance {},
	part5: class extends self.IParticlesInstance {},
	text3: class extends self.ITextInstance {},
	text4: class extends self.ITextInstance {},
	text5: class extends self.ITextInstance {},
	text6: class extends self.ITextInstance {},
	hintCircle: class extends self.ISpriteInstance {},
	hintText: class extends self.ITextInstance {},
	GameScore: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	Obj_Touch: class extends self.ISpriteInstance {},
	Ui_fam: class extends self.ISpriteInstance {}
}