const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Mouse,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Touch,
		C3.Plugins.AJAX,
		C3.Plugins.Keyboard,
		C3.Plugins.Clipboard,
		C3.Plugins.Dictionary,
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Arr,
		C3.Plugins.TiledBg,
		C3.Plugins.Particles,
		C3.Behaviors.Pin,
		C3.Behaviors.Rotate,
		C3.Behaviors.scrollto,
		C3.Plugins.NinePatch,
		C3.Behaviors.NoSave,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Behaviors.destroy,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Eponesh_GameScore.Cnds.IsSocialsSupportsShare,
		C3.Plugins.Eponesh_GameScore.Cnds.PlatformType,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Eponesh_GameScore.Cnds.IsGamesCollectionsAvailable,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgba255,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.AsJSON,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.LoadFromJsonString,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.TiledBg.Exps.UID,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.TiledBg.Cnds.PickByUID,
		C3.Plugins.TiledBg.Acts.AddChild,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.System.Exps.layoutheight,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.DragnDrop.Cnds.IsEnabled,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.NinePatch.Cnds.IsOnScreen,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Eponesh_GameScore.Cnds.IsSFXMuted,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Eponesh_GameScore.Acts.UnmuteSFX,
		C3.Plugins.Eponesh_GameScore.Acts.UnmuteMusic,
		C3.Plugins.Eponesh_GameScore.Acts.MuteSFX,
		C3.Plugins.Eponesh_GameScore.Acts.MuteMusic,
		C3.Plugins.Eponesh_GameScore.Cnds.IsMusicMuted,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStart,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStop,
		C3.Plugins.Eponesh_GameScore.Cnds.IsPlayerReady,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.Eponesh_GameScore.Cnds.IsPaused,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsStickyPlaying,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowSticky,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedClose,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsLastAdSuccess,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsInvite,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardOpen,
		C3.Plugins.Eponesh_GameScore.Acts.GamesCollectionsOpen,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerReset,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerScore,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSetScore,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Browser: 0},
	{GamePush: 0},
	{Mouse: 0},
	{PlatformInfo: 0},
	{Touch: 0},
	{AJAX: 0},
	{Keyboard: 0},
	{Clipboard: 0},
	{Dictionary: 0},
	{num0: 0},
	{num1: 0},
	{num2: 0},
	{num3: 0},
	{num4: 0},
	{num5: 0},
	{num6: 0},
	{num7: 0},
	{num8: 0},
	{num9: 0},
	{num10: 0},
	{num11: 0},
	{num12: 0},
	{num13: 0},
	{DragDrop: 0},
	{Tween: 0},
	{Sine: 0},
	{Person: 0},
	{num: 0},
	{Item: 0},
	{class: 0},
	{state: 0},
	{Brainrot: 0},
	{BrainrotDisco: 0},
	{DictionaryBrainrotsMerge: 0},
	{ArrayBrainrotsOpen: 0},
	{ArrayAd: 0},
	{ArrayPosition: 0},
	{Board: 0},
	{classSub: 0},
	{defaultWidth: 0},
	{defaultHeight: 0},
	{Button: 0},
	{Disco: 0},
	{Icon: 0},
	{Particles: 0},
	{Pin: 0},
	{Rotate: 0},
	{LightColor: 0},
	{LightWhite: 0},
	{ScrollTo: 0},
	{Shake: 0},
	{WindowBackground: 0},
	{Border: 0},
	{BackgroundPicture: 0},
	{NoSave: 0},
	{Window: 0},
	{Bullet: 0},
	{Fade: 0},
	{DestroyOutsideLayout: 0},
	{Coin: 0},
	{TextMoney: 0},
	{Bar: 0},
	{Finger: 0},
	{defaultX: 0},
	{TextInfo: 0},
	{Transition: 0},
	{ADS_Timer: 0},
	{ADS: 0},
	{offsetBottom: 0},
	{countBrainrots: 0},
	{trigger: 0},
	{objectJSON: 0},
	{frame: 0},
	{boardUID: 0},
	{x: 0},
	{y: 0},
	{brainrotNum: 0},
	{personUID: 0},
	{itemUID: 0},
	{offsetMoneyX: 0},
	{loadDictionaryBrainrots: 0},
	{mode: 0},
	{fingerStep: 0},
	{musicVolume: 0},
	{soundVolume: 0},
	{scrollmarkerMouseDistance: 0},
	{offset: 0},
	{layout: 0},
	{layer: 0},
	{fadeIn: 0},
	{opacity: 0},
	{letterWidth: 0},
	{previousLeft: 0},
	{previousUID: 0},
	{previousFrame: 0},
	{timeAction: 0},
	{soundName: 0},
	{volume: 0},
	{musicName: 0},
	{arrow: 0},
	{backgroundNum: 0},
	{gameName: 0},
	{gameSavePrevious: 0},
	{help: 0},
	{language: 0},
	{languageNum: 0},
	{languagePrevious: 0},
	{loadArrayBrainrotsOpen: 0},
	{loadArrayAd: 0},
	{loadArrayPosition: 0},
	{loadDictionary: 0},
	{loadGameStart: 0},
	{loadPlayerFields: 0},
	{money: 0},
	{string: 0},
	{testReset: 0},
	{aaTestString: 0},
	{counterTapTest: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	GamePush: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	Mouse: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Clipboard: class extends self.IInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	Person: class extends self.ISpriteInstance {},
	Item: class extends self.ISpriteInstance {},
	Brainrot: class extends self.ISpriteInstance {},
	BrainrotDisco: class extends self.ISpriteInstance {},
	DictionaryBrainrotsMerge: class extends self.IDictionaryInstance {},
	ArrayBrainrotsOpen: class extends self.IArrayInstance {},
	ArrayAd: class extends self.IArrayInstance {},
	ArrayPosition: class extends self.IArrayInstance {},
	Board: class extends self.ITiledBackgroundInstance {},
	Button: class extends self.ISpriteInstance {},
	Disco: class extends self.ISpriteInstance {},
	Icon: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	LightColor: class extends self.ISpriteInstance {},
	LightWhite: class extends self.ISpriteInstance {},
	Shake: class extends self.ISpriteInstance {},
	WindowBackground: class extends self.ISpriteInstance {},
	Border: class extends self.ITiledBackgroundInstance {},
	BackgroundPicture: class extends self.ISpriteInstance {},
	Window: class extends self.I9PatchInstance {},
	Coin: class extends self.ISpriteInstance {},
	TextMoney: class extends self.ISpriteFontInstance {},
	Bar: class extends self.I9PatchInstance {},
	Finger: class extends self.ISpriteInstance {},
	TextInfo: class extends self.ITextInstance {},
	Transition: class extends self.ISpriteInstance {}
}