const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.NinePatch,
		C3.Behaviors.Timer,
		C3.Plugins.Timeline,
		C3.Plugins.Keyboard,
		C3.Behaviors.destroy,
		C3.Behaviors.MoveTo,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Behaviors.LOS,
		C3.Plugins.Particles,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Text.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Timeline.Cnds.OnKeyframeReached,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.LOS.Acts.CastRay,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Behaviors.LOS.Exps.HitDistance,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.TiledBg.Exps.X,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetSolidCollisionFilter,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.TiledBg.Cnds.PickParent,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Timeline.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Exps.TemplateName,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Particles.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Cnds.IsCollisionEnabled,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.Sprite.Acts.AddChild
	];
};
self.C3_JsPropNameTable = [
	{bucketFull: 0},
	{climbing: 0},
	{climbSpeed: 0},
	{doneClimbing: 0},
	{Platform: 0},
	{Tween: 0},
	{Player: 0},
	{PlayerSprite: 0},
	{Solid: 0},
	{Collider: 0},
	{DecorationLeft: 0},
	{DecorationRight: 0},
	{Ground: 0},
	{Background: 0},
	{Clouds: 0},
	{specialProbability: 0},
	{Timer: 0},
	{Dragon: 0},
	{spawnTrail: 0},
	{tutorialOnScreen: 0},
	{playerWon: 0},
	{GameManager: 0},
	{IntroAnim: 0},
	{TimelineController: 0},
	{Keyboard: 0},
	{IntroAnimTrail: 0},
	{PlatLeft: 0},
	{PlatRight: 0},
	{descendingLadder: 0},
	{DestroyOutsideLayout: 0},
	{MoveTo: 0},
	{Flame: 0},
	{Fader: 0},
	{Fade: 0},
	{TextTutorial: 0},
	{Ladder: 0},
	{LineOfSight: 0},
	{LadderSpawner: 0},
	{WaterPickup: 0},
	{DragonRing: 0},
	{DragonLoveParticles: 0},
	{PlayerWaterParticles: 0},
	{PlayerWaterCollider: 0},
	{FlameLadder: 0},
	{FlameLimit: 0},
	{TextGameOver: 0},
	{FlameSummonSpot: 0},
	{WinZone: 0},
	{PlayerHeartParticles: 0},
	{TextPlayerWon: 0},
	{Heart: 0},
	{DragonEffect: 0},
	{Mountain1: 0},
	{Mountain2: 0},
	{Tree: 0},
	{Sign1: 0},
	{Sign2: 0},
	{Light: 0},
	{Stalactite: 0},
	{StalactiteParticles: 0},
	{WeeGooSDK: 0},
	{CLOUDS_SPEED: 0},
	{GRAVITY: 0},
	{expandSide: 0},
	{X_axis: 0},
	{anim: 0},
	{beginning: 0},
	{template: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	PlayerSprite: class extends self.ISpriteInstance {},
	Collider: class extends self.ITiledBackgroundInstance {},
	DecorationLeft: class extends self.ISpriteInstance {},
	DecorationRight: class extends self.ISpriteInstance {},
	Ground: class extends self.IWorldInstance {},
	Background: class extends self.ISpriteInstance {},
	Clouds: class extends self.ITiledBackgroundInstance {},
	Dragon: class extends self.ISpriteInstance {},
	GameManager: class extends self.ISpriteInstance {},
	IntroAnim: class extends self.ISpriteInstance {},
	TimelineController: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	IntroAnimTrail: class extends self.ISpriteInstance {},
	PlatLeft: class extends self.IWorldInstance {},
	PlatRight: class extends self.IWorldInstance {},
	Flame: class extends self.ISpriteInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	TextTutorial: class extends self.ITextInstance {},
	Ladder: class extends self.ITiledBackgroundInstance {},
	LadderSpawner: class extends self.ISpriteInstance {},
	WaterPickup: class extends self.ITiledBackgroundInstance {},
	DragonRing: class extends self.ISpriteInstance {},
	DragonLoveParticles: class extends self.IParticlesInstance {},
	PlayerWaterParticles: class extends self.IParticlesInstance {},
	PlayerWaterCollider: class extends self.ISpriteInstance {},
	FlameLadder: class extends self.ISpriteInstance {},
	FlameLimit: class extends self.ITiledBackgroundInstance {},
	TextGameOver: class extends self.ITextInstance {},
	FlameSummonSpot: class extends self.ISpriteInstance {},
	WinZone: class extends self.ITiledBackgroundInstance {},
	PlayerHeartParticles: class extends self.IParticlesInstance {},
	TextPlayerWon: class extends self.ITextInstance {},
	Heart: class extends self.ISpriteInstance {},
	DragonEffect: class extends self.ISpriteInstance {},
	Mountain1: class extends self.ISpriteInstance {},
	Mountain2: class extends self.ISpriteInstance {},
	Tree: class extends self.ISpriteInstance {},
	Sign1: class extends self.ISpriteInstance {},
	Sign2: class extends self.ISpriteInstance {},
	Light: class extends self.ISpriteInstance {},
	Stalactite: class extends self.ISpriteInstance {},
	StalactiteParticles: class extends self.IParticlesInstance {},
	WeeGooSDK: class extends self.IInstance {}
}