const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.Timer,
		C3.Behaviors.Flash,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Behaviors.destroy,
		C3.Behaviors.EightDir,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Exps.ImagePointCount,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Cnds.Repeat
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{gCell: 0},
	{row: 0},
	{col: 0},
	{rowOffset: 0},
	{colOffset: 0},
	{shaN: 0},
	{shaC: 0},
	{pWidth: 0},
	{pHeight: 0},
	{crXoffset: 0},
	{crYoffset: 0},
	{Score: 0},
	{linesNB: 0},
	{scoreMultiplier: 0},
	{fallTime: 0},
	{pieceInLine: 0},
	{lineScan: 0},
	{over: 0},
	{lineRemove: 0},
	{Timer: 0},
	{Game: 0},
	{border: 0},
	{Flash: 0},
	{Solid: 0},
	{piecePlaced: 0},
	{txtEnd: 0},
	{txtScore: 0},
	{line: 0},
	{top: 0},
	{DestroyOutsideLayout: 0},
	{"8Direction": 0},
	{sha: 0},
	{shaPreview: 0},
	{WeeGooSDK: 0},
	{result: 0},
	{offsetX: 0},
	{offsetY: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	gCell: class extends self.ISpriteInstance {},
	Game: class extends self.ISpriteInstance {},
	piecePlaced: class extends self.ISpriteInstance {},
	txtEnd: class extends self.ITextInstance {},
	txtScore: class extends self.ITextInstance {},
	line: class extends self.ISpriteInstance {},
	top: class extends self.ISpriteInstance {},
	sha: class extends self.ISpriteInstance {},
	shaPreview: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {}
}