const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Spriter,
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Dictionary,
		C3.Plugins.NinePatch,
		C3.Behaviors.Anchor,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Behaviors.scrollto,
		C3.Behaviors.Rotate,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Json,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.PlatformInfo,
		C3.Plugins.qrcode,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Behaviors.Bullet,
		C3.Plugins.Button,
		C3.Plugins.yagames_adaptivetext,
		C3.Plugins.List,
		C3.Plugins.sliderbar,
		C3.Plugins.TextBox,
		C3.Plugins.Spritefont2,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Spriter.Acts.setObjectScaleRatio,
		C3.Plugins.Spriter.Acts.SetInstanceVar,
		C3.Plugins.Spriter.Exps.UID,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Json.Cnds.CompareInstanceVar,
		C3.Plugins.Dictionary.Acts.Clear,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Dictionary.Cnds.ForEachKey,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.AdvancedRandom.Exps.WeightedByName,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.Dictionary.Exps.CurrentKey,
		C3.Plugins.Dictionary.Exps.CurrentValue,
		C3.Plugins.Dictionary.Exps.KeyCount,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Dictionary.Acts.DeleteKey,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Spriter.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Spriter.Acts.appendCharMap,
		C3.Plugins.Spriter.Acts.removeAllCharMaps,
		C3.Plugins.Spriter.Acts.SetVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Eponesh_GameScore.Cnds.PlatformType,
		C3.Plugins.AdvancedRandom.Acts.CreateProbabilityTable,
		C3.Plugins.AdvancedRandom.Acts.SetProbabilityTable,
		C3.Plugins.AdvancedRandom.Acts.AddProbabilityEntry,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Button.Cnds.CompareInstanceVar,
		C3.Plugins.Eponesh_GameScore.Exps.VariablesGet,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Browser.Acts.Reload,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.List.Exps.SelectedIndex,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Spriter.Exps.LayerName,
		C3.Plugins.System.Exps.min,
		C3.Plugins.sliderbar.Cnds.OnChanging,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Arr.Cnds.CompareXYZ,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Browser.Acts.InvokeDownloadString,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Button.Cnds.OnCreated,
		C3.Plugins.Button.Acts.SetText,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsStickyAvailable,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowSticky,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStart,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsRewardedAvailable,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Spriter.Cnds.readyForSetup,
		C3.Plugins.Spriter.Acts.associateTypeWithName,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.fps,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.time,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.NinePatch.Cnds.PickChildren,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Spriter.Cnds.isMirrored,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Spriter.Acts.setAnimation,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Spriter.Acts.setObjectXFlip,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Spriter.Cnds.CompareInstanceVar,
		C3.Plugins.Spriter.Exps.Y,
		C3.Plugins.Spriter.Exps.LayerNumber,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.ScriptsInEvents.Ecat_Event51_Act3,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.DragnDrop.Acts.Drop,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.System.Cnds.PickOverlappingPoint,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Spriter.Cnds.OnAnimFinished,
		C3.Plugins.Spriter.Cnds.PickParent,
		C3.Plugins.Sprite.Acts.SetEffect,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Spriter.Acts.MoveToLayer,
		C3.Plugins.Spriter.Acts.MoveToTop,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.NinePatch.Acts.MoveToLayer,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Spriter.Acts.SetX,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Acts.SetEffectEnabled,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Cnds.LayerNameExists,
		C3.Plugins.NinePatch.Acts.MoveToTop,
		C3.Plugins.NinePatch.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.NinePatch.Cnds.IsVisible,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenAvailable,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Arr.Exps.CurZ,
		C3.Plugins.NinePatch.Acts.SetHeight,
		C3.Plugins.Dictionary.Cnds.CompareInstanceVar,
		C3.Plugins.Spriter.Acts.Destroy,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.Arr.Cnds.CompareInstanceVar,
		C3.Plugins.Arr.Acts.SubInstanceVar,
		C3.Plugins.Arr.Acts.AddInstanceVar,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Spriter.Acts.pauseAnimation,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Text.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Exps.dt,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.AdvancedRandom.Acts.SetSeed,
		C3.Plugins.Dictionary.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsPreloaderAvailable,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowPreloader,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.Arr.Acts.SetInstanceVar,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Dictionary.Acts.Destroy,
		C3.Plugins.AdvancedRandom.Exps.RandomSeed,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Acts.Destroy,
		C3.Plugins.Eponesh_GameScore.Exps.ServerTimeUnix,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.NinePatch.Acts.AddInstanceVar,
		C3.Plugins.NinePatch.Exps.dt,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardSetRecord,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardPublishRecord,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Particles.Acts.SetInitSpeed,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Particles.Acts.SetGrowRate,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.Text.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.NinePatch.Cnds.IsOnLayer,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Exps.find,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.right,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AdvancedRandom.Exps.ProbabilityTableAsJSON,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.Json.Exps.Path,
		C3.Plugins.Json.Cnds.CompareType,
		C3.Plugins.Json.Exps.CurrentValue,
		C3.Plugins.AdvancedRandom.Acts.RemoveProbabilityEntry,
		C3.Plugins.Sprite.Exps.ChildCount,
		C3.Plugins.Sprite.Cnds.PickNthChild,
		C3.Plugins.NinePatch.Exps.UID,
		C3.Plugins.Text.Exps.UID,
		C3.Plugins.NinePatch.Cnds.PickByUID,
		C3.Plugins.NinePatch.Exps.ChildCount,
		C3.Plugins.NinePatch.Cnds.PickNthChild,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Plugins.NinePatch.Acts.SetEffect,
		C3.Plugins.NinePatch.Exps.LayerName,
		C3.Plugins.NinePatch.Acts.AddChild,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.NinePatch.Cnds.CompareOpacity,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Exps.LayerName,
		C3.Plugins.NinePatch.Acts.ZMoveToObject,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Arr.Acts.SplitString,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardOpenScoped,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsInvite,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsShare,
		C3.Plugins.Eponesh_GameScore.Exps.AppUrl,
		C3.Plugins.Sprite.Cnds.HasChildren,
		C3.Plugins.Dictionary.Cnds.IsEmpty,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Arr.Exps.JoinString,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.Json.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Acts.LoadURL,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.NinePatch.Cnds.PickParent,
		C3.Plugins.NinePatch.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Json.Cnds.CompareValue,
		C3.Plugins.NinePatch.Acts.SetBoolInstanceVar,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetEffect,
		C3.Plugins.Sprite.Acts.RotateCounterclockwise,
		C3.Plugins.Json.Exps.CurrentKey,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Dictionary.Acts.SetBoolInstanceVar,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Dictionary.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Touch.Cnds.OnDoubleTapGesture,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Json.Acts.SetJSON,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPause,
		C3.Plugins.Eponesh_GameScore.Cnds.OnResume,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPlayerChange,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPlayerFetchFieldsComplete,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPlayerFetchFieldsError,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPlayerLoadComplete,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPlayerLoadError,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPlayerLoginComplete,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPlayerLoginError,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPlayerReady,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPlayerSyncComplete,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPlayerSyncError,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsFullscreenClose,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsFullscreenStart,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsPreloaderStart,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsPreloaderClose,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedStart,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedClose,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.Eponesh_GameScore.Cnds.VariablesHas,
		C3.Plugins.Eponesh_GameScore.Cnds.VariablesEachVariable,
		C3.Plugins.Eponesh_GameScore.Exps.VariablesCurKey,
		C3.Plugins.Eponesh_GameScore.Exps.VariablesCurValue,
		C3.Plugins.Eponesh_GameScore.Cnds.OnVariablesFetch,
		C3.Plugins.Eponesh_GameScore.Cnds.OnVariablesFetchError,
		C3.Plugins.Eponesh_GameScore.Cnds.OnGameplayStart,
		C3.Plugins.Eponesh_GameScore.Cnds.OnOverlayReady,
		C3.Plugins.Eponesh_GameScore.Exps.AppImage,
		C3.Plugins.Eponesh_GameScore.Cnds.IsSocialsSupportsShare,
		C3.Plugins.Eponesh_GameScore.Cnds.IsSocialsSupportsNativeShare,
		C3.Plugins.Eponesh_GameScore.Cnds.IsSocialsSupportsNativeInvite,
		C3.Plugins.NinePatch.Cnds.HasTags
	];
};
self.C3_JsPropNameTable = [
	{sort: 0},
	{location: 0},
	{bodyColorIndex: 0},
	{spotsType: 0},
	{spotsColorIndex: 0},
	{hatUID: 0},
	{cats_spriter: 0},
	{cats_spriter_entity_000_body: 0},
	{cats_spriter_entity_000_eye: 0},
	{cats_spriter_entity_000_head: 0},
	{cats_spriter_entity_000_lapa_p1: 0},
	{cats_spriter_entity_000_lapa_p2: 0},
	{cats_spriter_entity_000_lapa_z1: 0},
	{cats_spriter_entity_000_lapa_z2: 0},
	{cats_spriter_entity_000_tail: 0},
	{cats_spriter_entity_000_body2: 0},
	{cats_spriter_entity_000_lapa_p1_2: 0},
	{cats_spriter_entity_000_lapa_p1_2_000: 0},
	{cats_spriter_entity_000_lapa_p1_2_001: 0},
	{cats_spriter_entity_000_lapa_p1_2_002: 0},
	{cats_spriter_entity_000_spot: 0},
	{cats_spriter_entity_000_tail_spot: 0},
	{data: 0},
	{state: 0},
	{curTime: 0},
	{targetX: 0},
	{targetY: 0},
	{vectorX: 0},
	{vectorY: 0},
	{moveAngle: 0},
	{lastX: 0},
	{lastY: 0},
	{bodyColor: 0},
	{spots: 0},
	{spotsColor: 0},
	{age: 0},
	{acc0: 0},
	{acc1: 0},
	{acc2: 0},
	{DragDrop: 0},
	{Base: 0},
	{CatData: 0},
	{variant: 0},
	{"9patch": 0},
	{"9patch2": 0},
	{"9patch3": 0},
	{"9patch4": 0},
	{"9patch5": 0},
	{"9patch6": 0},
	{"9patchRed": 0},
	{"9patch8": 0},
	{Anchor: 0},
	{"9patch9": 0},
	{currentTime: 0},
	{everyXSec: 0},
	{warnTime: 0},
	{bonusTime: 0},
	{adOnTheWay: 0},
	{Tween: 0},
	{ADWarn: 0},
	{anchored: 0},
	{stage: 0},
	{timeClicked: 0},
	{makeaction: 0},
	{initialScale: 0},
	{initialY: 0},
	{enabled: 0},
	{initialWidth: 0},
	{initialHeight: 0},
	{bClose: 0},
	{bContinue: 0},
	{bCustColClose: 0},
	{bHouseCancel: 0},
	{bHouseUpgrade: 0},
	{bLeaderboard: 0},
	{bNext: 0},
	{bNextField: 0},
	{bPrev: 0},
	{bPrevField: 0},
	{bRemoveSame: 0},
	{oldLocation: 0},
	{index: 0},
	{Card: 0},
	{CardBackground: 0},
	{Sine: 0},
	{CardBeams: 0},
	{CardFrame: 0},
	{CardSlot: 0},
	{CardSlotForeground: 0},
	{CardSlotFrame: 0},
	{CardSlotMask: 0},
	{catHead: 0},
	{BtnMusic: 0},
	{BtnSound: 0},
	{bRWMoney: 0},
	{bSell: 0},
	{bSellerUpgrade: 0},
	{bShowHand: 0},
	{colorDrop: 0},
	{DarkSprite: 0},
	{gainedReward: 0},
	{ArrowUpgrade: 0},
	{bSpeedUp: 0},
	{Ground: 0},
	{Group: 0},
	{Group2: 0},
	{Group3: 0},
	{Group4: 0},
	{HandArea: 0},
	{HandCenter: 0},
	{cat1: 0},
	{cat2: 0},
	{listOfCats: 0},
	{level: 0},
	{maxTime: 0},
	{PredefinedResult: 0},
	{House: 0},
	{cat1UID: 0},
	{cat2UID: 0},
	{HouseBgnd: 0},
	{HouseIconBase: 0},
	{Lighting: 0},
	{MaskGroup: 0},
	{MaskGroup2: 0},
	{MaskGroup4: 0},
	{val: 0},
	{maxVal: 0},
	{maxW: 0},
	{minW: 0},
	{pb9: 0},
	{pb9Bgnd: 0},
	{pb9BgndHouse: 0},
	{pb9House: 0},
	{notification: 0},
	{plus: 0},
	{pStar: 0},
	{Rectangle: 0},
	{Seller: 0},
	{Sky: 0},
	{Sprite6: 0},
	{Star: 0},
	{TiledBackground: 0},
	{Tooltip: 0},
	{tooltipButtonImage: 0},
	{TutHand: 0},
	{TutImage: 0},
	{ScrollTo: 0},
	{viewPoint: 0},
	{WindowFrame: 0},
	{enable: 0},
	{CollectionTab: 0},
	{CustColTab: 0},
	{isDragging: 0},
	{startX: 0},
	{startY: 0},
	{dragYMin: 0},
	{dragYMax: 0},
	{CustColTabsScroller: 0},
	{CustomTabsMask: 0},
	{RewardImage: 0},
	{gained: 0},
	{ind: 0},
	{RewardButton: 0},
	{CustColTabSelected: 0},
	{pbCust: 0},
	{pb9CustBgnd: 0},
	{BtnLeaders: 0},
	{bHelp: 0},
	{CustomCatsMask: 0},
	{initialX: 0},
	{wasDragged: 0},
	{dragStartY: 0},
	{dragThreshold: 0},
	{touchDragStartY: 0},
	{dragDistance: 0},
	{CustomScroller: 0},
	{CustColCatShadow: 0},
	{Mask: 0},
	{ShortNote: 0},
	{CustShopLockIcon: 0},
	{CustShopTab: 0},
	{CustShopButton: 0},
	{bSimple: 0},
	{CustSlotNewNote: 0},
	{CollectionTabIcon: 0},
	{CustShopTabImage: 0},
	{"9patchRed2": 0},
	{DarkSpriteCustom: 0},
	{Rotate: 0},
	{RewardBeams: 0},
	{tooltipButtonImage2: 0},
	{backpack: 0},
	{WindowFrame2: 0},
	{CustShopTab2: 0},
	{BtnInvite: 0},
	{BtnShare: 0},
	{bSkip: 0},
	{TempArr1: 0},
	{AJAX: 0},
	{AR: 0},
	{Audio: 0},
	{Browser: 0},
	{ColorsArray: 0},
	{ColorsIndexes: 0},
	{HandCards: 0},
	{HandData: 0},
	{HandTemp: 0},
	{HouseArray: 0},
	{HouseValues: 0},
	{JSON: 0},
	{jsonarr: 0},
	{Keyboard: 0},
	{Lang: 0},
	{Languages: 0},
	{LocalStorage: 0},
	{MergeColorsTemp: 0},
	{MergeColorsTempArray: 0},
	{Mouse: 0},
	{NotifArray: 0},
	{notifications: 0},
	{PlatformInfo: 0},
	{QRCode: 0},
	{RepeatedCatsUIDs: 0},
	{Save: 0},
	{SaveTempArray: 0},
	{SaveTempObj: 0},
	{SoundLimits: 0},
	{TestBodyColorsDic: 0},
	{TestDic: 0},
	{Touch: 0},
	{TutNativeData: 0},
	{SaveDic: 0},
	{JSONSave: 0},
	{Locales: 0},
	{TempSaveDic: 0},
	{key: 0},
	{useLocalization: 0},
	{tADWarn: 0},
	{tCatsOnField: 0},
	{tCollectionHeader: 0},
	{tCollectionPage: 0},
	{tDbgBC: 0},
	{tDbgSC: 0},
	{tDbgST: 0},
	{tFPS: 0},
	{tHouseUpgradePrice: 0},
	{tMoney: 0},
	{tNotification: 0},
	{Fade: 0},
	{Bullet: 0},
	{tPopupMoney: 0},
	{tProgressBarValue: 0},
	{tSimpleTextWEff: 0},
	{tSpeedUpPrice: 0},
	{tSpeedUpPrice2: 0},
	{tTooltipButtonText: 0},
	{tTooltipRewardText: 0},
	{tTooltipText: 0},
	{tUnlockAmount: 0},
	{tCustColUnlockAmount: 0},
	{tRewardCount: 0},
	{tTaskNumber: 0},
	{tDbg: 0},
	{bDbgLeft: 0},
	{bDbgRight: 0},
	{bDBGToggle: 0},
	{dbgBgnd: 0},
	{DebugDic: 0},
	{DebugText: 0},
	{dbgBtn: 0},
	{dbgLog: 0},
	{TextDebugLog: 0},
	{curPage: 0},
	{CustomCollectionData: 0},
	{CustColSlotFrame: 0},
	{colorIndex: 0},
	{type: 0},
	{CustColTabImage: 0},
	{CustomCollectionTasks: 0},
	{CustomCollectionSpotsColorsUnlocked: 0},
	{CustomCollectionBodyColorsUnlocked: 0},
	{CustColTabsHeaderImage: 0},
	{CollectionTabImage: 0},
	{CustColSlotFrame2: 0},
	{CustShopSlotFrameImage2: 0},
	{CustShopSlotFrameImage3: 0},
	{btn9pImage: 0},
	{PrivateCollectionData: 0},
	{btnBuySlotForRV: 0},
	{price: 0},
	{btnBuySlotForStars: 0},
	{btnBuyCustomizationForRV: 0},
	{btnBuyCustomizationForStars: 0},
	{btnCustWatchRV: 0},
	{btnCustSelect: 0},
	{btnWImage: 0},
	{LBBgnd: 0},
	{LBEntries: 0},
	{LBLoading: 0},
	{LBTitle: 0},
	{ID: 0},
	{LBPlayerRank: 0},
	{LBPlayerName: 0},
	{LBPlayerScore: 0},
	{LBPlayerAvatar: 0},
	{LBDic: 0},
	{CollectionData: 0},
	{CollectionUnlockInfo: 0},
	{CollectionTasks: 0},
	{ShortNot: 0},
	{SlotNot: 0},
	{ShopNot: 0},
	{eventHatsArray: 0},
	{tabIndex: 0},
	{hatID: 0},
	{lastHatID: 0},
	{fieldID: 0},
	{lastFieldID: 0},
	{houseID: 0},
	{lastHouseID: 0},
	{CustShop: 0},
	{initWidth: 0},
	{HatIcon: 0},
	{FieldIcon: 0},
	{HouseIcon: 0},
	{itemID: 0},
	{isSelected: 0},
	{CustShopSlotFrame: 0},
	{UIState: 0},
	{UIStatesTable: 0},
	{finished: 0},
	{TAU: 0},
	{maxY: 0},
	{minY: 0},
	{Scroll: 0},
	{Maskk: 0},
	{msgWindow: 0},
	{tmsg: 0},
	{msgButtonImage: 0},
	{tTooltipButtonText2: 0},
	{bMsg: 0},
	{art_cat: 0},
	{Paws: 0},
	{Hat: 0},
	{CustColorsMask: 0},
	{List: 0},
	{pointHead: 0},
	{pointHat: 0},
	{SlotNoteImage: 0},
	{UIPanels: 0},
	{HintSprite: 0},
	{maxWaitTime: 0},
	{curWaitTime: 0},
	{Sine2: 0},
	{FlyingReward: 0},
	{HandEmptySlot: 0},
	{reward_art: 0},
	{Group5: 0},
	{timeTillReward: 0},
	{GotReward: 0},
	{FlyingRewardController: 0},
	{"9patch7": 0},
	{DbgRewardSlider: 0},
	{DbgRewardNumber: 0},
	{SpriteFont: 0},
	{GamePush: 0},
	{TabStars: 0},
	{CloudSaveImage: 0},
	{lapka: 0},
	{SoundImg: 0},
	{IniteImage: 0},
	{ShareImage: 0},
	{SettingsImage: 0},
	{CloudImage: 0},
	{fBuyBtn: 0},
	{cats_spriterFamily: 0},
	{fSpriteSort: 0},
	{fButtons: 0},
	{fTextEffects: 0},
	{fPB9: 0},
	{fGS: 0},
	{fLayered9p: 0},
	{fLayered: 0},
	{fLayeredText: 0},
	{fLayeredAnother: 0},
	{fCat: 0},
	{fCustShopIcon: 0},
	{fScroller: 0},
	{fTextLocale: 0},
	{fCustShopSlot: 0},
	{fUtilsColor: 0},
	{fixedString: 0},
	{scale: 0},
	{x: 0},
	{y: 0},
	{bodyFrom: 0},
	{rndTreshold1: 0},
	{rndTreshold2: 0},
	{body1ColorIndex: 0},
	{spots1ColorIndex: 0},
	{spots1Type: 0},
	{body2ColorIndex: 0},
	{spots2ColorIndex: 0},
	{spots2Type: 0},
	{colorsCount: 0},
	{newObjectString: 0},
	{newBodyColorIndex: 0},
	{newSpotsColorIndex: 0},
	{newSpotsType: 0},
	{dominantColorIndex: 0},
	{recessiveColorIndex: 0},
	{color1Index: 0},
	{color2Index: 0},
	{result: 0},
	{object1String: 0},
	{object2String: 0},
	{outputString: 0},
	{inputString: 0},
	{tempString2: 0},
	{index1: 0},
	{index2: 0},
	{tempString: 0},
	{spotType: 0},
	{res: 0},
	{object1: 0},
	{object2: 0},
	{count: 0},
	{objectInfo: 0},
	{colorInfo: 0},
	{text: 0},
	{xCount: 0},
	{xCur: 0},
	{yCur: 0},
	{xOffset: 0},
	{yOffset: 0},
	{xStep: 0},
	{yStep: 0},
	{c: 0},
	{sp: 0},
	{spCol: 0},
	{varsCount: 0},
	{spotsCount: 0},
	{exclude: 0},
	{spriterUID: 0},
	{lastPageUnlocked: 0},
	{количество_столбцов: 0},
	{количество_строк: 0},
	{CloudSaveData: 0},
	{rewardName: 0},
	{separator: 0},
	{element: 0},
	{list: 0},
	{newList: 0},
	{value: 0},
	{msg: 0},
	{color: 0},
	{status: 0},
	{CleanMatchTable: 0},
	{CleanBodyWeight1: 0},
	{CleanBodyWeight2: 0},
	{CleanBodyWeight3: 0},
	{CleanSpotsTable: 0},
	{CleanSpotsWeight1: 0},
	{CleanSpotsWeight2: 0},
	{CleanSpotsWeight3: 0},
	{CleanNewSpotsTable: 0},
	{CleanNewSpotsWeight1: 0},
	{CleanNewSpotsWeight2: 0},
	{CleanNewSpotsWeight3: 0},
	{CleanMatchSpotsUpgradeTable: 0},
	{CleanSpotsUpgradeWeight: 0},
	{Clean1SBMatchTable: 0},
	{Clean1SBDominantWeight: 0},
	{Clean1SBRecessiveWeight: 0},
	{Clean1SBSpotsTableDominant: 0},
	{Clean1SBDomSpotsWeight1: 0},
	{Clean1SBDomSpotsWeight2: 0},
	{Clean1SBDomSpotsWeight3: 0},
	{Clean1SBSpotsTableRecessive: 0},
	{Clean1SBRecSpotsWeight2: 0},
	{Clean1SBRecSpotsWeight3: 0},
	{Clean1MatchTable: 0},
	{Clean1DominantWeight: 0},
	{Clean1RecessiveWeight: 0},
	{Clean1SpotsTableDominant: 0},
	{Clean1SpotsTableRecessive: 0},
	{Clean1SpotsWeight1: 0},
	{Clean1SpotsWeight2: 0},
	{Clean1SpotsWeight3Dominant: 0},
	{Clean1SpotsWeight3Recessive: 0},
	{Clean1Col3MatchTable: 0},
	{Clean1Col3DominantWeight: 0},
	{Clean1Col3RecessiveWeight: 0},
	{Clean1Col3SpotsColWeight: 0},
	{Clean1Col3SpotsTableDominant: 0},
	{Clean1Col3SpotsTableRecessive: 0},
	{Clean1Col3SpotsWeight1: 0},
	{Clean1Col3SpotsWeight2: 0},
	{Clean1Col3SpotsWeight3Dominant: 0},
	{Clean1Col3SpotsWeight3Recessive: 0},
	{Clean1Col3SpotsTableSpot1: 0},
	{Clean1Col3SpotsWeight1Spot1: 0},
	{Clean1Col3SpotsWeight2Spot1: 0},
	{Clean1Col3SpotsWeight3Spot1: 0},
	{TK_Parent1: 0},
	{TK_Parent2: 0},
	{TK_New: 0},
	{TK_None: 0},
	{TK_Common: 0},
	{TK_Rare: 0},
	{TK_None4: 0},
	{TK_Dominant: 0},
	{TK_Recessive: 0},
	{TK_Spots1: 0},
	{TK_Spots2: 0},
	{MSBC2ColTable: 0},
	{MSBC2ColDominantWeight: 0},
	{MSBC2ColRecessiveWeight: 0},
	{MSBC2ColSpotsTableDominant: 0},
	{MSBC2ColDominantNoSpotsWeight: 0},
	{MSBC2ColDominantCommonSpotsWeight: 0},
	{MSBC2ColDominantRareSpotsWeight: 0},
	{MSBC2ColSpotsTableRecessive: 0},
	{MSBC2ColRecessiveNoSpotsWeight: 0},
	{MSBC2ColRecessiveCommonSpotsWeight: 0},
	{MSBC2ColRecessiveRareSpotsWeight: 0},
	{MSBC3ColTable: 0},
	{MSBC3ColDominantWeight: 0},
	{MSBC3ColWeight3: 0},
	{MSBC3ColWeight4: 0},
	{MSBC3ColSpotsTableDominant: 0},
	{MSBC3ColDominantNoSpotsWeight: 0},
	{MSBC3ColDominantCommonSpotsWeight: 0},
	{MSBC3ColDominantRareSpotsWeight: 0},
	{MSBC3ColSpotsTableRecessive: 0},
	{MSBC3ColRecessiveCommonSpotsWeight: 0},
	{MSBC3ColRecessiveRareSpotsWeight: 0},
	{MDBC2ColTable: 0},
	{MDBC2ColDominantWeight: 0},
	{MDBC2ColRecessiveWeight: 0},
	{MDBC2ColSpotsTableDominant: 0},
	{MDBC2ColDominantNoSpotsWeight: 0},
	{MDBC2ColDominantCommonSpotsWeight: 0},
	{MDBC2ColDominantRareSpotsWeight: 0},
	{MDBC3ColTable: 0},
	{MDBC3ColDominantWeight: 0},
	{MDBC3ColRecessiveWeight: 0},
	{MDBC3ColWeight3: 0},
	{MDBC3ColSpotsTableDominant: 0},
	{MDBC3ColDominantNoSpotsWeight: 0},
	{MDBC3ColDominantCommonSpotsWeight: 0},
	{MDBC3ColDominantRareSpotsWeight: 0},
	{MDBC3ColSpotsTableRecessive: 0},
	{MDBC3ColRecessiveCommonSpotsWeight: 0},
	{MDBC3ColRecessiveRareSpotsWeight: 0},
	{MDBC3ColSMTable: 0},
	{MDBC3ColSMDominantWeight: 0},
	{MDBC3ColSMRecessiveWeight: 0},
	{MDBC3ColSMWeight3: 0},
	{MDBC3ColSMSpotsTableDominant: 0},
	{MDBC3ColSMDominantNoSpotsWeight: 0},
	{MDBC3ColSMDominantCommonSpotsWeight: 0},
	{MDBC3ColSMDominantRareSpotsWeight: 0},
	{MDBC3ColSMSpotsTableRecessive: 0},
	{MDBC3ColSMRecessiveNoSpotsWeight: 0},
	{MDBC3ColSMRecessiveCommonSpotsWeight: 0},
	{MDBC3ColSMRecessiveRareSpotsWeight: 0},
	{MDBC4ColTable: 0},
	{MDBC4ColDominantWeight: 0},
	{MDBC4ColRecessiveWeight: 0},
	{MDBC4ColWeight3: 0},
	{MDBC4ColWeight4: 0},
	{MDBC4ColSpotsTableDominant: 0},
	{MDBC4ColDominantNoSpotsWeight: 0},
	{MDBC4ColDominantCommonSpotsWeight: 0},
	{MDBC4ColDominantRareSpotsWeight: 0},
	{MDBC4ColSpotsTableRecessive: 0},
	{MDBC4ColRecessiveCommonSpotsWeight: 0},
	{MDBC4ColRecessiveRareSpotsWeight: 0},
	{CatsTableName: 0},
	{CatsRandomStep: 0},
	{CatsMaxProb: 0},
	{none: 0},
	{new: 0},
	{DebugEnabled: 0},
	{DebugSavingDisabled: 0},
	{testlist: 0},
	{dbgBodyColor: 0},
	{dbgSpotsType: 0},
	{dbgSpotsColor: 0},
	{col: 0},
	{page: 0},
	{cat: 0},
	{max_log_messages: 0},
	{logMsg: 0},
	{catString: 0},
	{giveMoney: 0},
	{repeatedCount: 0},
	{GameVersion: 0},
	{ReadedVersion: 0},
	{GameSeed: 0},
	{CommonSpotsCount: 0},
	{RareSpotsCount: 0},
	{TotalColorsCount: 0},
	{RareSpotsIndexOffset: 0},
	{string1: 0},
	{string2: 0},
	{test_no_spots_count: 0},
	{test_one_spot_count: 0},
	{test_two_spots_count: 0},
	{LAD: 0},
	{LMESSAGE: 0},
	{LREWARDS: 0},
	{LTUTORIAL: 0},
	{LPICKED: 0},
	{LDEBUG: 0},
	{LCOLLECTION: 0},
	{LCOLLECTIONBGND: 0},
	{LPRIVATECOLLECTIONBGND: 0},
	{LCOLLECTIONSBGND: 0},
	{LCOLLECTIONForeground: 0},
	{LCOLLECTION_CUSTOM_ALL: 0},
	{LCOLLECTION_CUSTOM_BACKGROUND: 0},
	{LCOLLECTION_CUSTOM_FOREGROUND: 0},
	{LCOLLECTION_CUSTOM_FOREGROUND_MASKED: 0},
	{LCATSINHOUSE: 0},
	{LHAND: 0},
	{LMAIN: 0},
	{LTUTORIAL_NATIVE: 0},
	{LUI: 0},
	{LMENU: 0},
	{LGROUND: 0},
	{LHOUSE: 0},
	{LHOUSE_BGND: 0},
	{LSKY: 0},
	{LLEADERBOARD: 0},
	{LFLYING_REWARD: 0},
	{LOVER_FIELD: 0},
	{CLOC_Field: 0},
	{CLOC_Hand: 0},
	{CLOC_Picked: 0},
	{CLOC_Collection: 0},
	{CLOC_CustomCollection: 0},
	{CLOC_PrivateCollection: 0},
	{MUSIC_MAINTHEME: 0},
	{SOUND_CLICK: 0},
	{SOUND_PICK: 0},
	{SOUND_PLACE: 0},
	{MAX_CATS: 0},
	{Money: 0},
	{catSpeed: 0},
	{catScaleChild: 0},
	{catScaleAdult: 0},
	{catAgingThreshold: 0},
	{catSpawnX1: 0},
	{catSpawnX2: 0},
	{catSpawnY1: 0},
	{catSpawnY2: 0},
	{catIdleMinTime: 0},
	{catIdleMaxTime: 0},
	{catsInterractable: 0},
	{CAT_EMOTION_NORMAL: 0},
	{CAT_EMOTION_ANGRY: 0},
	{CAT_EMOTION_2: 0},
	{CAT_EMOTION_3: 0},
	{catSpeedX: 0},
	{catSpeedY: 0},
	{dropX: 0},
	{dropY: 0},
	{freePos: 0},
	{catUID: 0},
	{layerName: 0},
	{sum: 0},
	{hx: 0},
	{hy: 0},
	{name: 0},
	{HouseSpeedUpTime: 0},
	{HouseMaxLevel: 0},
	{HOUSE0X: 0},
	{HOUSE0Y: 0},
	{HOUSE1X: 0},
	{HOUSE1Y: 0},
	{HOUSEIND_UPPRICE: 0},
	{HOUSEIND_UPTIME: 0},
	{HOUSEIND_MERGETIME: 0},
	{HOUSEIND_CATSCOUNT: 0},
	{HOUSEIND_SPEEDUPPRICE: 0},
	{catsCount: 0},
	{newCat: 0},
	{loopInd: 0},
	{houseUID: 0},
	{offsetX: 0},
	{offsetY: 0},
	{catToIconOfsetX: 0},
	{slot: 0},
	{colors: 0},
	{tempColors: 0},
	{curColor: 0},
	{curWord: 0},
	{hasNewColor: 0},
	{lockedList: 0},
	{lockedCat: 0},
	{k: 0},
	{loopStop: 0},
	{rndResult: 0},
	{curProb: 0},
	{ratio: 0},
	{upgradePrice: 0},
	{speedUpPrice: 0},
	{HandOpenY: 0},
	{HandCloseY: 0},
	{HandRadius: 0},
	{HandY: 0},
	{HandCardAngleStep: 0},
	{HandX: 0},
	{HandMaxCards: 0},
	{HandOpened: 0},
	{catScale: 0},
	{hasSubLayer: 0},
	{subLayerName: 0},
	{cardUID: 0},
	{starOffsetX1: 0},
	{starOffsetX2: 0},
	{starOffsetY1: 0},
	{CollectionMaxPages: 0},
	{COLLECTION_PAGE_REWARD: 0},
	{dropOffsetX: 0},
	{dropOffsetY: 0},
	{dropScale: 0},
	{COLLECTION_TAB_MAIN: 0},
	{COLLECTION_TAB_PRIVATE: 0},
	{COLLECTION_TAB_CUSTOM: 0},
	{smallHeight: 0},
	{bigHeight: 0},
	{col1: 0},
	{col2: 0},
	{gainRewardOffset: 0},
	{allMatched: 0},
	{valNoAge: 0},
	{giveReward: 0},
	{toUnlock: 0},
	{unlocked: 0},
	{isOdd: 0},
	{isEven: 0},
	{cols: 0},
	{lines: 0},
	{slotIndex: 0},
	{stepX: 0},
	{stepY: 0},
	{curCol: 0},
	{curLine: 0},
	{amount: 0},
	{centerX: 0},
	{centerY: 0},
	{rewardType: 0},
	{rewardParam1: 0},
	{Sound: 0},
	{Music: 0},
	{SoundPrev: 0},
	{MusicPrev: 0},
	{InstantSaveMusic: 0},
	{InstantSaveSound: 0},
	{SoundAndMusicTogether: 0},
	{volume: 0},
	{tag: 0},
	{looped: 0},
	{limit: 0},
	{limitPeriod: 0},
	{langID: 0},
	{GameLoadingFinished: 0},
	{GameTransferredToCloud: 0},
	{LocalSaveCheckState: 0},
	{CloudSaveCheckState: 0},
	{CheckPeriod: 0},
	{LocalSaveTime: 0},
	{CloudSaveTime: 0},
	{SAVECHECKSTATE_IDLE: 0},
	{SAVECHECKSTATE_CHECKING: 0},
	{SAVECHECKSTATE_FINISHED: 0},
	{LocalSaveStringData: 0},
	{CloudSaveStringData: 0},
	{CloudSavePeriod: 0},
	{CloudTimeFromLastSave: 0},
	{forceCloud: 0},
	{catsData: 0},
	{catData: 0},
	{cardsData: 0},
	{cardData: 0},
	{collectionData: 0},
	{housesData: 0},
	{houseData: 0},
	{catsCount2: 0},
	{SaveData: 0},
	{dictionaryString: 0},
	{cardsAmount: 0},
	{pagesAmount: 0},
	{barUID: 0},
	{ADEnabled: 0},
	{FullscreenActive: 0},
	{fsad_show_flag: 0},
	{PlayerUID: 0},
	{PlayerAuthorized: 0},
	{CanSendToLB: 0},
	{LeaderboardName: 0},
	{rwdName: 0},
	{rwdPage: 0},
	{rwdSlot: 0},
	{rwdNumberParam1: 0},
	{FLAG_EVENT_NY: 0},
	{FLAG_EVENT_Helloween: 0},
	{newScore: 0},
	{tutState: 0},
	{TutorialEnabled: 0},
	{TutorialHandEnabled: 0},
	{TutorialHandSourсeType: 0},
	{TutorialHandSourceUID: 0},
	{TutorialHandSourceParams: 0},
	{TutorialHandDestinationX: 0},
	{TutorialHandDestinationY: 0},
	{TutorialHandAngle: 0},
	{TutorialHandTime: 0},
	{TutorialHandPeriod: 0},
	{TutorialLastHandSize: 0},
	{TUTSTATE_START: 0},
	{TUTSTATE_PLACE_CAT_1: 0},
	{TUTSTATE_PLACE_CAT_2: 0},
	{TUTSTATE_WAIT_SELECTION: 0},
	{TUTSTATE_WAIT_ACCELERATION: 0},
	{TUTSTATE_MAKE_CARD: 0},
	{TUTSTATE_OPEN_COLLECTION: 0},
	{TUTSTATE_PLACE_CARD: 0},
	{TUTSTATE_CLOSE_COLLECTION: 0},
	{TUTSTATE_MAKE_CATS: 0},
	{TUTSTATE_ADD_ORANGE: 0},
	{TUTSTATE_INTRO1: 0},
	{TUTSTATE_INTRO2: 0},
	{TUTSTATE_NEXT_PAGE: 0},
	{TUTSTATE_INFO_TASKS: 0},
	{TUTSTATE_INFO_ANY_CARD: 0},
	{TUTSTATE_TRY_MESSAGE: 0},
	{TUTSTATE_TRY_NO_HELP: 0},
	{TUTSTATE_UPGRADE: 0},
	{TUTSTATE_WAIT_UPGRADE: 0},
	{TUTSTATE_INFO_GATHER_REWARDS: 0},
	{TUTSTATE_INFO_INVENTORY_TAB: 0},
	{TUTSTATE_INFO_COLLECTION_TAB: 0},
	{TUTSTATE_INFO_COLLECTION: 0},
	{TUTSTATE_INFO_TASKS_TAB: 0},
	{TUTSTATE_INFO_TASKS_REWARD: 0},
	{TUTSTATE_INFO_COLLECTION_REWARD: 0},
	{TUTSTATE_FINISHED: 0},
	{TUT_SOURCE_DEFAULT: 0},
	{TUT_SOURCE_CARDBYSPOTS: 0},
	{TutorialCheckNative: 0},
	{TutorialNativeWaitTime: 0},
	{x1: 0},
	{y1: 0},
	{x2: 0},
	{y2: 0},
	{message: 0},
	{w: 0},
	{h: 0},
	{showButton: 0},
	{sameCatsCount: 0},
	{lockedCatsList: 0},
	{catsOnField: 0},
	{catToUnlock: 0},
	{stopped: 0},
	{slotsAmount: 0},
	{slotsOffset: 0},
	{SELLER_PRICE: 0},
	{SELLER_SPEEDUP_PRICE: 0},
	{inputTime: 0},
	{startIndex: 0},
	{elemLen: 0},
	{s1: 0},
	{s2: 0},
	{tok: 0},
	{tableName: 0},
	{keyName: 0},
	{childrenCount: 0},
	{objectUID: 0},
	{v1: 0},
	{v2: 0},
	{v3: 0},
	{versionString: 0},
	{size: 0},
	{r: 0},
	{g: 0},
	{b: 0},
	{hexString: 0},
	{HEXDIGITS: 0},
	{hex: 0},
	{fieldCurIndex: 0},
	{FIELD_MIN_INDEX: 0},
	{FIELD_MAX_INDEX: 0},
	{FIELD_SWITCH_TIME: 0},
	{NOTIFICATION_MANY_CATS: 0},
	{NOTIFICATION_NO_MONEY: 0},
	{NOTIFICATION_CANT_SELL_LAST: 0},
	{NOTIFICATION_CAN_SELL_ONE: 0},
	{NOTIFICATION_CAN_SELL_MANY: 0},
	{NOTIFICATION_CAN_PLACE_TO_COLLECTION: 0},
	{NOTIFICATION_NO_SPACE_IN_INVENTORY: 0},
	{NOTIFICATION_NO_SPACE_IN_HAND: 0},
	{NOTIFICATION_LET_KITTY_GROW: 0},
	{notificationShowTime: 0},
	{notificationCurTime: 0},
	{notificationID: 0},
	{CustCollectionCurBodyColor: 0},
	{CustCollectionCurSpotsColor: 0},
	{UseCustomCollection: 0},
	{CustColIsDragging: 0},
	{CustColTouchedTab: 0},
	{CustColReleasedTab: 0},
	{CustColMaskDragYMin: 0},
	{CustColMaskDragYMax: 0},
	{CustColLastUnlockedCount: 0},
	{CustColUnlockedCount: 0},
	{CustColTaskIndex: 0},
	{CustColCatsCollected: 0},
	{curSpotType: 0},
	{x1Step: 0},
	{y1Step: 0},
	{x2Step: 0},
	{sizeSmall: 0},
	{sizeBig: 0},
	{butImage: 0},
	{body: 0},
	{foundIndex: 0},
	{tx: 0},
	{ty: 0},
	{step: 0},
	{PrivateCollectionMaxPages: 0},
	{PrivateCollectionUnlockedPages: 0},
	{PrivateCollectionCardsPerPage: 0},
	{PC_SLOT_OPEN: 0},
	{PC_SLOT_LOCKED: 0},
	{PC_SLOT_LOCKED_AD: 0},
	{PC_SLOT_LOCKED_STARS: 0},
	{PrivateCollectionCatScale: 0},
	{PrivateCollectionRewardedSlotPrice: 0},
	{isLocked: 0},
	{LockedSlotsAmount: 0},
	{LockedSlotsIndex: 0},
	{maxOpenedSlots: 0},
	{notify: 0},
	{pos: 0},
	{found: 0},
	{RWDT_MONEY: 0},
	{RWDT_PRIVATE_PAGE: 0},
	{RWDT_PRIVATE_SLOT: 0},
	{RWDT_CAT: 0},
	{RWDT_HAT: 0},
	{RWDT_HOUSE: 0},
	{RWDT_FIELD: 0},
	{RARENESS_COMMON: 0},
	{rewardString: 0},
	{rewardAmount: 0},
	{bgndWidth: 0},
	{reward: 0},
	{readyForMassReward: 0},
	{rows: 0},
	{rewardsAmount: 0},
	{chestX: 0},
	{chestY: 0},
	{moneyX: 0},
	{moneyY: 0},
	{moneyString: 0},
	{moneyIndex: 0},
	{waitTimeMoney: 0},
	{indRow: 0},
	{indCol: 0},
	{allRewardsString: 0},
	{chestString: 0},
	{delayIndex: 0},
	{moveTime: 0},
	{bdClrString: 0},
	{bdspots: 0},
	{keyString: 0},
	{pageString: 0},
	{CurrentEventFlag: 0},
	{STATE_FIELD: 0},
	{STATE_COLLECTIONS: 0},
	{STATE_CUSTOMIZATION_SHOP: 0},
	{STATE_HINT: 0},
	{STATE_REWARDING: 0},
	{STATE_AD: 0},
	{STATE_RV: 0},
	{STATE_LEADERBOARD: 0},
	{STATE_FLYING_REWARD: 0},
	{STATE_MENU: 0},
	{INPUT_OPEN_COLLECTIONS: 0},
	{INPUT_CLOSE: 0},
	{INPUT_SET_COLLECTION_TAB_TASKS: 0},
	{INPUT_SET_COLLECTION_TAB_INVENTORY: 0},
	{INPUT_SET_COLLECTION_TAB_COLLECTION: 0},
	{INPUT_OPEN_CUSTOMIZATION_SHOP: 0},
	{INPUT_SHOW_HINT: 0},
	{INPUT_GET_REWARD: 0},
	{INPUT_AD_TIME: 0},
	{INPUT_RV_TIME: 0},
	{INPUT_OPEN_LEADERBOARD: 0},
	{INPUT_OPEN_FLYING_REWARD: 0},
	{INPUT_OPEN_MENU: 0},
	{WIN_FIELD: 0},
	{WIN_COLLECTION_TASKS: 0},
	{stateID: 0},
	{interactionOnly: 0},
	{inputID: 0},
	{curState: 0},
	{newState: 0},
	{oldStateInteractionsOnly: 0},
	{newStateInteractionsOnly: 0},
	{token: 0},
	{SHOPSLOT_UNLOCKED: 0},
	{SHOPSLOT_SELECTED: 0},
	{SHOPSLOT_NOT_SELECTED: 0},
	{SHOPSLOT_LOCKED: 0},
	{SHOPSLOT_FOR_REWARD: 0},
	{SHOPSLOT_STATUS_UNLOCKED: 0},
	{SHOPSLOT_STATUS_FOR_STARS: 0},
	{SHOPSLOT_STATUS_FOR_RW: 0},
	{SHOPSLOT_STATUS_FOR_TASK: 0},
	{SHOPSLOT_ITEM_SCALE: 0},
	{SHOPSLOT_ITEM_OFFSETX: 0},
	{SHOPSLOT_ITEM_OFFSETY: 0},
	{HEXCOL_SHOPBTN_GREEN: 0},
	{HEXCOL_SHOPBTN_GRAY: 0},
	{HEXCOL_SHOPBTN_BLUE: 0},
	{CustShopRewardedPrice: 0},
	{CustShopSlotsOffsetX: 0},
	{CustShopSlotsOffsetY: 0},
	{CustShopSlotsStepX: 0},
	{CustShopSlotsStepY: 0},
	{tab: 0},
	{arrName: 0},
	{statusString: 0},
	{arr: 0},
	{slot_state: 0},
	{FR_Time1: 0},
	{FR_Time2: 0},
	{TAU_WAIT_PAGE_OPENED: 0},
	{currentLayoutName: 0},
	{lang: 0},
	{keyHasDot: 0},
	{MenuSaveForcedPeriod: 0},
	{MenuSaveForcedTime: 0},
	{buttonsCount: 0},
	{posY3: 0},
	{posY4: 0}
];

self.InstanceType = {
	cats_spriter: class extends self.IWorldInstance {},
	cats_spriter_entity_000_body: class extends self.ISpriteInstance {},
	cats_spriter_entity_000_eye: class extends self.ISpriteInstance {},
	cats_spriter_entity_000_head: class extends self.ISpriteInstance {},
	cats_spriter_entity_000_lapa_p1: class extends self.ISpriteInstance {},
	cats_spriter_entity_000_lapa_p2: class extends self.ISpriteInstance {},
	cats_spriter_entity_000_lapa_z1: class extends self.ISpriteInstance {},
	cats_spriter_entity_000_lapa_z2: class extends self.ISpriteInstance {},
	cats_spriter_entity_000_tail: class extends self.ISpriteInstance {},
	cats_spriter_entity_000_body2: class extends self.ISpriteInstance {},
	cats_spriter_entity_000_lapa_p1_2: class extends self.ISpriteInstance {},
	cats_spriter_entity_000_lapa_p1_2_000: class extends self.ISpriteInstance {},
	cats_spriter_entity_000_lapa_p1_2_001: class extends self.ISpriteInstance {},
	cats_spriter_entity_000_lapa_p1_2_002: class extends self.ISpriteInstance {},
	cats_spriter_entity_000_spot: class extends self.ISpriteInstance {},
	cats_spriter_entity_000_tail_spot: class extends self.ISpriteInstance {},
	Base: class extends self.ISpriteInstance {},
	CatData: class extends self.IDictionaryInstance {},
	_9patch: class extends self.IWorldInstance {},
	_9patch2: class extends self.IWorldInstance {},
	_9patch3: class extends self.IWorldInstance {},
	_9patch4: class extends self.IWorldInstance {},
	_9patch5: class extends self.IWorldInstance {},
	_9patch6: class extends self.IWorldInstance {},
	_9patchRed: class extends self.IWorldInstance {},
	_9patch8: class extends self.IWorldInstance {},
	_9patch9: class extends self.IWorldInstance {},
	ADWarn: class extends self.IWorldInstance {},
	anchored: class extends self.ISpriteInstance {},
	bClose: class extends self.ISpriteInstance {},
	bContinue: class extends self.ISpriteInstance {},
	bCustColClose: class extends self.ISpriteInstance {},
	bHouseCancel: class extends self.ISpriteInstance {},
	bHouseUpgrade: class extends self.ISpriteInstance {},
	bLeaderboard: class extends self.ISpriteInstance {},
	bNext: class extends self.ISpriteInstance {},
	bNextField: class extends self.ISpriteInstance {},
	bPrev: class extends self.ISpriteInstance {},
	bPrevField: class extends self.ISpriteInstance {},
	bRemoveSame: class extends self.ISpriteInstance {},
	Card: class extends self.ISpriteInstance {},
	CardBackground: class extends self.IWorldInstance {},
	CardBeams: class extends self.ISpriteInstance {},
	CardFrame: class extends self.IWorldInstance {},
	CardSlot: class extends self.ISpriteInstance {},
	CardSlotForeground: class extends self.IWorldInstance {},
	CardSlotFrame: class extends self.IWorldInstance {},
	CardSlotMask: class extends self.IWorldInstance {},
	catHead: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	bRWMoney: class extends self.ISpriteInstance {},
	bSell: class extends self.ISpriteInstance {},
	bSellerUpgrade: class extends self.ISpriteInstance {},
	bShowHand: class extends self.ISpriteInstance {},
	colorDrop: class extends self.ISpriteInstance {},
	DarkSprite: class extends self.ISpriteInstance {},
	gainedReward: class extends self.ISpriteInstance {},
	ArrowUpgrade: class extends self.ISpriteInstance {},
	bSpeedUp: class extends self.ISpriteInstance {},
	Ground: class extends self.ISpriteInstance {},
	Group: class extends self.ISpriteInstance {},
	Group2: class extends self.ISpriteInstance {},
	Group3: class extends self.ISpriteInstance {},
	Group4: class extends self.ISpriteInstance {},
	HandArea: class extends self.ISpriteInstance {},
	HandCenter: class extends self.ISpriteInstance {},
	House: class extends self.ISpriteInstance {},
	HouseBgnd: class extends self.ISpriteInstance {},
	HouseIconBase: class extends self.ISpriteInstance {},
	Lighting: class extends self.ISpriteInstance {},
	MaskGroup: class extends self.ISpriteInstance {},
	MaskGroup2: class extends self.ISpriteInstance {},
	MaskGroup4: class extends self.ISpriteInstance {},
	pb9: class extends self.IWorldInstance {},
	pb9Bgnd: class extends self.IWorldInstance {},
	pb9BgndHouse: class extends self.IWorldInstance {},
	pb9House: class extends self.IWorldInstance {},
	notification: class extends self.ISpriteInstance {},
	plus: class extends self.ISpriteInstance {},
	pStar: class extends self.IParticlesInstance {},
	Rectangle: class extends self.ISpriteInstance {},
	Seller: class extends self.ISpriteInstance {},
	Sky: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Star: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Tooltip: class extends self.IWorldInstance {},
	tooltipButtonImage: class extends self.IWorldInstance {},
	TutHand: class extends self.ISpriteInstance {},
	TutImage: class extends self.ISpriteInstance {},
	viewPoint: class extends self.ISpriteInstance {},
	WindowFrame: class extends self.IWorldInstance {},
	CollectionTab: class extends self.ISpriteInstance {},
	CustColTab: class extends self.ISpriteInstance {},
	CustColTabsScroller: class extends self.ISpriteInstance {},
	CustomTabsMask: class extends self.ISpriteInstance {},
	RewardImage: class extends self.ISpriteInstance {},
	RewardButton: class extends self.ISpriteInstance {},
	CustColTabSelected: class extends self.ISpriteInstance {},
	pbCust: class extends self.IWorldInstance {},
	pb9CustBgnd: class extends self.IWorldInstance {},
	BtnLeaders: class extends self.ISpriteInstance {},
	bHelp: class extends self.ISpriteInstance {},
	CustomCatsMask: class extends self.ISpriteInstance {},
	CustomScroller: class extends self.ISpriteInstance {},
	CustColCatShadow: class extends self.ISpriteInstance {},
	Mask: class extends self.ISpriteInstance {},
	ShortNote: class extends self.ISpriteInstance {},
	CustShopLockIcon: class extends self.ISpriteInstance {},
	CustShopTab: class extends self.ISpriteInstance {},
	CustShopButton: class extends self.ISpriteInstance {},
	bSimple: class extends self.ISpriteInstance {},
	CustSlotNewNote: class extends self.ISpriteInstance {},
	CollectionTabIcon: class extends self.ISpriteInstance {},
	CustShopTabImage: class extends self.ISpriteInstance {},
	_9patchRed2: class extends self.IWorldInstance {},
	DarkSpriteCustom: class extends self.ISpriteInstance {},
	RewardBeams: class extends self.ISpriteInstance {},
	tooltipButtonImage2: class extends self.IWorldInstance {},
	backpack: class extends self.ISpriteInstance {},
	WindowFrame2: class extends self.IWorldInstance {},
	CustShopTab2: class extends self.ISpriteInstance {},
	BtnInvite: class extends self.ISpriteInstance {},
	BtnShare: class extends self.ISpriteInstance {},
	bSkip: class extends self.ISpriteInstance {},
	TempArr1: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	AR: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	ColorsArray: class extends self.IArrayInstance {},
	ColorsIndexes: class extends self.IArrayInstance {},
	HandCards: class extends self.IArrayInstance {},
	HandData: class extends self.IArrayInstance {},
	HandTemp: class extends self.IArrayInstance {},
	HouseArray: class extends self.IArrayInstance {},
	HouseValues: class extends self.IArrayInstance {},
	JSON: class extends self.IJSONInstance {},
	jsonarr: class extends self.IArrayInstance {},
	Keyboard: class extends self.IInstance {},
	Lang: class extends self.IDictionaryInstance {},
	Languages: class extends self.IArrayInstance {},
	LocalStorage: class extends self.IInstance {},
	MergeColorsTemp: class extends self.IDictionaryInstance {},
	MergeColorsTempArray: class extends self.IArrayInstance {},
	Mouse: class extends self.IInstance {},
	NotifArray: class extends self.IArrayInstance {},
	notifications: class extends self.IDictionaryInstance {},
	PlatformInfo: class extends self.IInstance {},
	QRCode: class extends self.IQRCodeInstance {},
	RepeatedCatsUIDs: class extends self.IArrayInstance {},
	Save: class extends self.IArrayInstance {},
	SaveTempArray: class extends self.IArrayInstance {},
	SaveTempObj: class extends self.IDictionaryInstance {},
	SoundLimits: class extends self.IDictionaryInstance {},
	TestBodyColorsDic: class extends self.IDictionaryInstance {},
	TestDic: class extends self.IDictionaryInstance {},
	Touch: class extends self.IInstance {},
	TutNativeData: class extends self.IArrayInstance {},
	SaveDic: class extends self.IDictionaryInstance {},
	JSONSave: class extends self.IJSONInstance {},
	Locales: class extends self.IJSONInstance {},
	TempSaveDic: class extends self.IDictionaryInstance {},
	tADWarn: class extends self.ITextInstance {},
	tCatsOnField: class extends self.ITextInstance {},
	tCollectionHeader: class extends self.ITextInstance {},
	tCollectionPage: class extends self.ITextInstance {},
	tDbgBC: class extends self.ITextInstance {},
	tDbgSC: class extends self.ITextInstance {},
	tDbgST: class extends self.ITextInstance {},
	tFPS: class extends self.ITextInstance {},
	tHouseUpgradePrice: class extends self.ITextInstance {},
	tMoney: class extends self.ITextInstance {},
	tNotification: class extends self.ITextInstance {},
	tPopupMoney: class extends self.ITextInstance {},
	tProgressBarValue: class extends self.ITextInstance {},
	tSimpleTextWEff: class extends self.ITextInstance {},
	tSpeedUpPrice: class extends self.ITextInstance {},
	tSpeedUpPrice2: class extends self.ITextInstance {},
	tTooltipButtonText: class extends self.ITextInstance {},
	tTooltipRewardText: class extends self.ITextInstance {},
	tTooltipText: class extends self.ITextInstance {},
	tUnlockAmount: class extends self.ITextInstance {},
	tCustColUnlockAmount: class extends self.ITextInstance {},
	tRewardCount: class extends self.ITextInstance {},
	tTaskNumber: class extends self.ITextInstance {},
	tDbg: class extends self.ITextInstance {},
	bDbgLeft: class extends self.ISpriteInstance {},
	bDbgRight: class extends self.ISpriteInstance {},
	bDBGToggle: class extends self.ISpriteInstance {},
	dbgBgnd: class extends self.IWorldInstance {},
	DebugDic: class extends self.IDictionaryInstance {},
	DebugText: class extends self.ITextInstance {},
	dbgBtn: class extends self.IButtonInstance {},
	dbgLog: class extends self.IArrayInstance {},
	TextDebugLog: class extends self.ITextInstance {},
	CustomCollectionData: class extends self.IArrayInstance {},
	CustColSlotFrame: class extends self.IWorldInstance {},
	CustColTabImage: class extends self.IWorldInstance {},
	CustomCollectionTasks: class extends self.IArrayInstance {},
	CustomCollectionSpotsColorsUnlocked: class extends self.IArrayInstance {},
	CustomCollectionBodyColorsUnlocked: class extends self.IArrayInstance {},
	CustColTabsHeaderImage: class extends self.ISpriteInstance {},
	CollectionTabImage: class extends self.IWorldInstance {},
	CustColSlotFrame2: class extends self.IWorldInstance {},
	CustShopSlotFrameImage2: class extends self.IWorldInstance {},
	CustShopSlotFrameImage3: class extends self.IWorldInstance {},
	btn9pImage: class extends self.IWorldInstance {},
	PrivateCollectionData: class extends self.IArrayInstance {},
	btnBuySlotForRV: class extends self.ISpriteInstance {},
	btnBuySlotForStars: class extends self.ISpriteInstance {},
	btnBuyCustomizationForRV: class extends self.ISpriteInstance {},
	btnBuyCustomizationForStars: class extends self.ISpriteInstance {},
	btnCustWatchRV: class extends self.ISpriteInstance {},
	btnCustSelect: class extends self.ISpriteInstance {},
	btnWImage: class extends self.ISpriteInstance {},
	LBBgnd: class extends self.ISpriteInstance {},
	LBEntries: class extends self.ISpriteInstance {},
	LBLoading: class extends self.ISpriteInstance {},
	LBTitle: class extends self.ISpriteInstance {},
	LBPlayerRank: class extends self.IWorldInstance {},
	LBPlayerName: class extends self.IWorldInstance {},
	LBPlayerScore: class extends self.IWorldInstance {},
	LBPlayerAvatar: class extends self.ISpriteInstance {},
	LBDic: class extends self.IDictionaryInstance {},
	CollectionData: class extends self.IArrayInstance {},
	CollectionUnlockInfo: class extends self.IArrayInstance {},
	CollectionTasks: class extends self.IArrayInstance {},
	ShortNot: class extends self.IDictionaryInstance {},
	SlotNot: class extends self.IDictionaryInstance {},
	ShopNot: class extends self.IDictionaryInstance {},
	eventHatsArray: class extends self.IArrayInstance {},
	CustShop: class extends self.IJSONInstance {},
	HatIcon: class extends self.ISpriteInstance {},
	FieldIcon: class extends self.ISpriteInstance {},
	HouseIcon: class extends self.ISpriteInstance {},
	CustShopSlotFrame: class extends self.IWorldInstance {},
	UIState: class extends self.IArrayInstance {},
	UIStatesTable: class extends self.IArrayInstance {},
	TAU: class extends self.IDictionaryInstance {},
	Scroll: class extends self.ISpriteInstance {},
	Maskk: class extends self.ISpriteInstance {},
	msgWindow: class extends self.IWorldInstance {},
	tmsg: class extends self.ITextInstance {},
	msgButtonImage: class extends self.IWorldInstance {},
	tTooltipButtonText2: class extends self.ITextInstance {},
	bMsg: class extends self.ISpriteInstance {},
	art_cat: class extends self.ISpriteInstance {},
	Paws: class extends self.ISpriteInstance {},
	Hat: class extends self.ISpriteInstance {},
	CustColorsMask: class extends self.ISpriteInstance {},
	List: class extends self.IListInstance {},
	pointHead: class extends self.ISpriteInstance {},
	pointHat: class extends self.ISpriteInstance {},
	SlotNoteImage: class extends self.ISpriteInstance {},
	UIPanels: class extends self.IArrayInstance {},
	HintSprite: class extends self.ISpriteInstance {},
	FlyingReward: class extends self.ISpriteInstance {},
	HandEmptySlot: class extends self.ISpriteInstance {},
	reward_art: class extends self.ISpriteInstance {},
	Group5: class extends self.ISpriteInstance {},
	FlyingRewardController: class extends self.IDictionaryInstance {},
	_9patch7: class extends self.IWorldInstance {},
	DbgRewardSlider: class extends self.ISliderBarInstance {},
	DbgRewardNumber: class extends self.ITextInputInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	GamePush: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	TabStars: class extends self.ISpriteInstance {},
	CloudSaveImage: class extends self.ISpriteInstance {},
	lapka: class extends self.ISpriteInstance {},
	SoundImg: class extends self.ISpriteInstance {},
	IniteImage: class extends self.ISpriteInstance {},
	ShareImage: class extends self.ISpriteInstance {},
	SettingsImage: class extends self.ISpriteInstance {},
	CloudImage: class extends self.ISpriteInstance {},
	fBuyBtn: class extends self.ISpriteInstance {},
	cats_spriterFamily: class extends self.ISpriteInstance {},
	fSpriteSort: class extends self.ISpriteInstance {},
	fButtons: class extends self.ISpriteInstance {},
	fTextEffects: class extends self.ITextInstance {},
	fPB9: class extends self.IWorldInstance {},
	fGS: class extends self.ISpriteInstance {},
	fLayered9p: class extends self.IWorldInstance {},
	fLayered: class extends self.ISpriteInstance {},
	fLayeredText: class extends self.ITextInstance {},
	fLayeredAnother: class extends self.ISpriteInstance {},
	fCat: class extends self.ISpriteInstance {},
	fCustShopIcon: class extends self.ISpriteInstance {},
	fScroller: class extends self.ISpriteInstance {},
	fTextLocale: class extends self.ITextInstance {},
	fCustShopSlot: class extends self.IWorldInstance {},
	fUtilsColor: class extends self.IWorldInstance {}
}