var TEXT_PRELOADER_CONTINUE = " ";
var TEXT_PLAY      = " ";
var TEXT_MORE      = " ";
var TEXT_HELP1     = "PLEASE, PICK A COLOR";
var TEXT_CHOOSE    = "SELECT THE PICTURE YOU WANT TO PAINT";
var TEXT_SURE       = "YOU WANT TO QUIT THE GAME?";
var TEXT_ERASE_PAINT = "YOU WANT TO ERASE PAINT?";