const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Rotate,
		C3.Behaviors.scrollto,
		C3.Plugins.Particles,
		C3.Behaviors.Pin,
		C3.Behaviors.Timer,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.WGSDK.Cnds.RewardGranted,
		C3.ScriptsInEvents.Es_wingame_Event2_Act1,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Audio.Acts.StopAll
	];
};
self.C3_JsPropNameTable = [
	{IdentifyBox: 0},
	{PosX: 0},
	{DragDrop: 0},
	{box_1: 0},
	{box_10: 0},
	{box_11: 0},
	{box_12: 0},
	{box_2: 0},
	{box_3: 0},
	{box_4: 0},
	{box_5: 0},
	{box_6: 0},
	{box_7: 0},
	{box_8: 0},
	{box_9: 0},
	{box_13: 0},
	{box_14: 0},
	{box_15: 0},
	{box_16: 0},
	{Array: 0},
	{Audio: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{Sine: 0},
	{Tween: 0},
	{btn_again: 0},
	{btn_back: 0},
	{btn_continue: 0},
	{btn_home: 0},
	{btn_inst: 0},
	{btn_play: 0},
	{info: 0},
	{menu_btn: 0},
	{next_btn: 0},
	{nextLeft: 0},
	{nextRight: 0},
	{retry_btn: 0},
	{sounds: 0},
	{watch: 0},
	{btn_more: 0},
	{txt_Complete: 0},
	{Fade: 0},
	{txt_congra: 0},
	{txt_game: 0},
	{txt_instruct: 0},
	{txt_levels: 0},
	{txt_move: 0},
	{txt_moves: 0},
	{txt_time: 0},
	{txt_timer: 0},
	{txt_timersUp: 0},
	{txt_win: 0},
	{PosY: 0},
	{Identify: 0},
	{Okay: 0},
	{verificador: 0},
	{menu: 0},
	{title: 0},
	{btn_background: 0},
	{inst: 0},
	{Fade2: 0},
	{BlackScreen: 0},
	{level: 0},
	{frame: 0},
	{levels: 0},
	{bg_levels: 0},
	{bg_ui: 0},
	{Rotate: 0},
	{rotate: 0},
	{blackScreenGame: 0},
	{position0: 0},
	{position1: 0},
	{ScrollTo: 0},
	{cam: 0},
	{a1: 0},
	{a2: 0},
	{weblogo: 0},
	{Particles: 0},
	{hand_click: 0},
	{noads: 0},
	{bean_smile_sad: 0},
	{number: 0},
	{Pin: 0},
	{Timer: 0},
	{star_burst: 0},
	{Sine2: 0},
	{Confetti: 0},
	{ConfettiWinParticle: 0},
	{bean_win: 0},
	{Sprite: 0},
	{WeeGooSDK: 0},
	{space: 0},
	{correct: 0},
	{LastCurrentX: 0},
	{LastCurrentY: 0},
	{Complete: 0},
	{timer: 0},
	{GameOver: 0},
	{Desb: 0},
	{i: 0},
	{temp: 0},
	{LS_Name: 0},
	{lS_Rewards: 0},
	{CurrentLevel: 0},
	{playbleLevel: 0},
	{CamPos: 0},
	{sound: 0},
	{duration: 0}
];

self.InstanceType = {
	box_1: class extends self.ISpriteInstance {},
	box_10: class extends self.ISpriteInstance {},
	box_11: class extends self.ISpriteInstance {},
	box_12: class extends self.ISpriteInstance {},
	box_2: class extends self.ISpriteInstance {},
	box_3: class extends self.ISpriteInstance {},
	box_4: class extends self.ISpriteInstance {},
	box_5: class extends self.ISpriteInstance {},
	box_6: class extends self.ISpriteInstance {},
	box_7: class extends self.ISpriteInstance {},
	box_8: class extends self.ISpriteInstance {},
	box_9: class extends self.ISpriteInstance {},
	box_13: class extends self.ISpriteInstance {},
	box_14: class extends self.ISpriteInstance {},
	box_15: class extends self.ISpriteInstance {},
	box_16: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	btn_again: class extends self.ISpriteInstance {},
	btn_back: class extends self.ISpriteInstance {},
	btn_continue: class extends self.ISpriteInstance {},
	btn_home: class extends self.ISpriteInstance {},
	btn_inst: class extends self.ISpriteInstance {},
	btn_play: class extends self.ISpriteInstance {},
	menu_btn: class extends self.ISpriteInstance {},
	next_btn: class extends self.ISpriteInstance {},
	nextLeft: class extends self.ISpriteInstance {},
	nextRight: class extends self.ISpriteInstance {},
	retry_btn: class extends self.ISpriteInstance {},
	sounds: class extends self.ISpriteInstance {},
	watch: class extends self.ISpriteInstance {},
	btn_more: class extends self.ISpriteInstance {},
	txt_Complete: class extends self.ITextInstance {},
	txt_congra: class extends self.ISpriteInstance {},
	txt_game: class extends self.ISpriteInstance {},
	txt_instruct: class extends self.ISpriteInstance {},
	txt_levels: class extends self.ISpriteInstance {},
	txt_move: class extends self.ISpriteFontInstance {},
	txt_moves: class extends self.ITextInstance {},
	txt_time: class extends self.ISpriteFontInstance {},
	txt_timer: class extends self.ITextInstance {},
	txt_timersUp: class extends self.ISpriteInstance {},
	txt_win: class extends self.ISpriteInstance {},
	verificador: class extends self.ISpriteInstance {},
	menu: class extends self.ISpriteInstance {},
	title: class extends self.ISpriteInstance {},
	btn_background: class extends self.ISpriteInstance {},
	inst: class extends self.ISpriteInstance {},
	BlackScreen: class extends self.ISpriteInstance {},
	levels: class extends self.ISpriteInstance {},
	bg_levels: class extends self.ISpriteInstance {},
	bg_ui: class extends self.ISpriteInstance {},
	rotate: class extends self.ISpriteInstance {},
	blackScreenGame: class extends self.ISpriteInstance {},
	cam: class extends self.ISpriteInstance {},
	a1: class extends self.ISpriteInstance {},
	a2: class extends self.ISpriteInstance {},
	weblogo: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	hand_click: class extends self.ISpriteInstance {},
	noads: class extends self.ISpriteInstance {},
	bean_smile_sad: class extends self.ISpriteInstance {},
	star_burst: class extends self.ISpriteInstance {},
	Confetti: class extends self.ISpriteInstance {},
	ConfettiWinParticle: class extends self.IParticlesInstance {},
	bean_win: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {}
}