const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.Arr,
		C3.Plugins.Text,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Arr.Acts.Pop,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Text.Cnds.CompareOpacity,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnDoubleTapGesture,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.min,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y
	];
};
self.C3_JsPropNameTable = [
	{DragDrop: 0},
	{BGIncomplete: 0},
	{Tween: 0},
	{BGComplete: 0},
	{Touch: 0},
	{inventoryID: 0},
	{Sticker: 0},
	{stickerAnim: 0},
	{StickerSpot: 0},
	{StickerInventory: 0},
	{InventoryArray: 0},
	{Fader: 0},
	{TextTutorial: 0},
	{TextGameCompleted: 0},
	{InventoryGradient: 0},
	{WeeGooSDK: 0},
	{stickersPlaced: 0},
	{inventorySlot: 0}
];

self.InstanceType = {
	BGIncomplete: class extends self.ITiledBackgroundInstance {},
	BGComplete: class extends self.ITiledBackgroundInstance {},
	Touch: class extends self.IInstance {},
	Sticker: class extends self.ISpriteInstance {},
	StickerSpot: class extends self.ISpriteInstance {},
	StickerInventory: class extends self.ISpriteInstance {},
	InventoryArray: class extends self.IArrayInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	TextTutorial: class extends self.ITextInstance {},
	TextGameCompleted: class extends self.ITextInstance {},
	InventoryGradient: class extends self.ITiledBackgroundInstance {},
	WeeGooSDK: class extends self.IInstance {}
}