const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.MixonGames_EasyInGameConsole,
		C3.Plugins.WGSDK,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Plugins.Sprite,
		C3.Plugins.HTMLElement,
		C3.Behaviors.solid,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.JavaScriptInEvents.Esglobal_Event3_Act1,
		C3.JavaScriptInEvents.Esglobal_Event4_Act1,
		C3.JavaScriptInEvents.Esglobal_Event5_Act1,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.WGSDK.Cnds.RewardGranted,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{InGameConsole: 0},
	{WeeGooSDK: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Fade: 0},
	{Sine: 0},
	{LevelName: 0},
	{ScoreTitle: 0},
	{ScoreValue: 0},
	{BestScoreTitle: 0},
	{BestScoreValue: 0},
	{GameOver: 0},
	{Spr_b_button: 0},
	{Title: 0},
	{AdsBtn: 0},
	{CloseLeaderboards: 0},
	{LeaderboardButton: 0},
	{Spr_s_button: 0},
	{Spr_s_button2: 0},
	{LeaderboardsTable: 0},
	{PopupWindow: 0},
	{MuteBtn: 0},
	{Bg: 0},
	{DestroyEffect: 0},
	{Solid: 0},
	{SolidBounds: 0},
	{Spr_c_ball: 0},
	{Spr_w_ball: 0},
	{Spri_black: 0},
	{Sprite: 0},
	{SprTutorial: 0},
	{CompanyLogo: 0},
	{Tween: 0},
	{CompanyMotto: 0},
	{CompanyName: 0},
	{Pin: 0},
	{Family1: 0},
	{Buttons: 0},
	{Effects: 0},
	{level: 0},
	{re: 0},
	{num2: 0},
	{go: 0},
	{ang: 0},
	{num: 0},
	{play: 0},
	{best: 0},
	{score: 0},
	{GameIsMuted: 0},
	{Username: 0},
	{url: 0},
	{CanShowAds: 0},
	{Mediation: 0},
	{AdsCounter: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	InGameConsole: class extends C3.Plugins.MixonGames_EasyInGameConsole.Instance {},
	WeeGooSDK: class extends self.IInstance {},
	LevelName: class extends self.ITextInstance {},
	ScoreTitle: class extends self.ITextInstance {},
	ScoreValue: class extends self.ITextInstance {},
	BestScoreTitle: class extends self.ITextInstance {},
	BestScoreValue: class extends self.ITextInstance {},
	GameOver: class extends self.ITextInstance {},
	Spr_b_button: class extends self.ISpriteInstance {},
	Title: class extends self.ISpriteInstance {},
	AdsBtn: class extends self.ISpriteInstance {},
	CloseLeaderboards: class extends self.ISpriteInstance {},
	LeaderboardButton: class extends self.ISpriteInstance {},
	Spr_s_button: class extends self.ISpriteInstance {},
	Spr_s_button2: class extends self.ISpriteInstance {},
	LeaderboardsTable: class extends self.IHTMLElementInstance {},
	PopupWindow: class extends self.ISpriteInstance {},
	MuteBtn: class extends self.ISpriteInstance {},
	Bg: class extends self.ISpriteInstance {},
	DestroyEffect: class extends self.ISpriteInstance {},
	SolidBounds: class extends self.ISpriteInstance {},
	Spr_c_ball: class extends self.ISpriteInstance {},
	Spr_w_ball: class extends self.ISpriteInstance {},
	Spri_black: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	SprTutorial: class extends self.ISpriteInstance {},
	CompanyLogo: class extends self.ISpriteInstance {},
	CompanyMotto: class extends self.ISpriteInstance {},
	CompanyName: class extends self.ISpriteInstance {},
	Family1: class extends self.ITextInstance {},
	Buttons: class extends self.ISpriteInstance {},
	Effects: class extends self.ISpriteInstance {}
}