const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Behaviors.Timer,
		C3.Plugins.Particles,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Plugins.Json,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Rotate,
		C3.Plugins.NinePatch,
		C3.Plugins.SpellSync_Core,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Json.Cnds.IsBooleanSet,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.NinePatch.Cnds.IsOnLayer,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Cnds.IsOnLayer,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.PickNthChild,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Spritefont2.Cnds.IsOnLayer,
		C3.Plugins.Spritefont2.Acts.MoveToTop,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.SetX,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.TiledBg.Cnds.IsVisible,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.SpellSync_Core.Acts.GameplayStop,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.Text.Cnds.PickParent,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Json.Exps.GetAsCompactString,
		C3.Plugins.Json.Exps.CurrentKey,
		C3.Behaviors.Physics.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Physics.Acts.SetElasticity,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.TiledBg.Exps.ColorValue,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Cnds.CompareHeight,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Acts.SetDensity,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Physics.Acts.ApplyForce,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Physics.Exps.Mass,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Text.Cnds.IsOnLayer,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetPos,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Text.Exps.Y,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.SpellSync_Core.Acts.GameplayStart,
		C3.ScriptsInEvents.Gamesheet_Event375,
		C3.Plugins.TiledBg.Exps.ImageHeight,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Behaviors.Tween.Acts.PauseAllTweens,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Behaviors.Tween.Acts.ResumeAllTweens,
		C3.Plugins.Sprite.Exps.AnimationFrameTag,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.TiledBg.Acts.RemoveFromParent,
		C3.Plugins.Json.Acts.SetBoolean,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.SpellSync_Core.Acts.AdsShowFullscreen,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.SpellSync_Core.Acts.AdsShowRewarded,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageWidth,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.TiledBg.Acts.SetImageScaleX,
		C3.Plugins.TiledBg.Acts.SetImageScaleY,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.SpellSync_Core.Cnds.IsAdsPreloaderAvailable,
		C3.Plugins.SpellSync_Core.Acts.AdsShowPreloader,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.SpellSync_Core.Cnds.OnPause,
		C3.Plugins.SpellSync_Core.Cnds.OnResume,
		C3.Plugins.SpellSync_Core.Cnds.OnAdsRewardedReward
	];
};
self.C3_JsPropNameTable = [
	{Physics: 0},
	{Bounding: 0},
	{Box: 0},
	{IsCollided: 0},
	{IsGrounded: 0},
	{CanDrop: 0},
	{Fruit: 0},
	{Tween: 0},
	{AnimMerge: 0},
	{Sine: 0},
	{DangerLine: 0},
	{DefaultHieght: 0},
	{FruitLine: 0},
	{FruitIcon: 0},
	{ProgressBarAmount: 0},
	{GiftBox: 0},
	{Timer: 0},
	{GiftTop: 0},
	{TiledBgGame: 0},
	{AnimDeletion: 0},
	{Dropped: 0},
	{Bomb: 0},
	{TutHand: 0},
	{ParticlesSpark: 0},
	{GiftBoxInside: 0},
	{TiledBgHome: 0},
	{TiledBgSkyParts: 0},
	{BoosterIcon: 0},
	{InteractiveArea: 0},
	{AJAX: 0},
	{ArrayChance: 0},
	{Browser: 0},
	{FruitList: 0},
	{JSON_LS: 0},
	{JSONConfig: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{Keyboard: 0},
	{Audio: 0},
	{TxtBestScore: 0},
	{TxtGeneral: 0},
	{TxtProgressBar: 0},
	{TxtGameOver: 0},
	{TxtDeleter: 0},
	{TxtBomb: 0},
	{TxtShaker: 0},
	{TxtUpgrade: 0},
	{TxtAdsCoin: 0},
	{TxtBoosterCoin: 0},
	{TxtAds: 0},
	{TxtAdsTime: 0},
	{TxtBuyBoosterInfo: 0},
	{TxtBuyBooster: 0},
	{TxtCoin: 0},
	{TxtScore: 0},
	{TxtCombo: 0},
	{TxtFlyingScore: 0},
	{ComboBg: 0},
	{Gift: 0},
	{GoalIconBg: 0},
	{ProgressBarBg: 0},
	{ScoreBg: 0},
	{CoinIcon: 0},
	{CoinBg: 0},
	{Rotate: 0},
	{Sparkle: 0},
	{BlurBG: 0},
	{GiftCoinBg: 0},
	{GiftBoosterBg: 0},
	{GoalGiftBg: 0},
	{TiledBgSky: 0},
	{BoosterCountBg: 0},
	{Logo: 0},
	{ArrowToNext: 0},
	{BasketBot: 0},
	{BasketTop: 0},
	{Cloud_1: 0},
	{Cloud_2: 0},
	{Fence: 0},
	{HomeFence: 0},
	{Playground: 0},
	{Tree: 0},
	{PlayButtonShadow: 0},
	{IconSparkle: 0},
	{GoalAchievedText: 0},
	{BuyBoosterBg: 0},
	{BestScoreIcon: 0},
	{FirstW: 0},
	{FirstH: 0},
	{IsTouched: 0},
	{Available: 0},
	{BtnBuy: 0},
	{BtnClosePopUp: 0},
	{BtnAds: 0},
	{BtnNoAds: 0},
	{BtnDeleter: 0},
	{BtnShaker: 0},
	{BtnBomb: 0},
	{BtnUpgrade: 0},
	{BtnCancel: 0},
	{BtnHome: 0},
	{BtnInfo: 0},
	{BtnMusic: 0},
	{BtnPause: 0},
	{BtnPlay: 0},
	{BtnReset: 0},
	{BtnSFX: 0},
	{BtnStudio: 0},
	{BtnBuyBooster: 0},
	{BtnGetGift: 0},
	{FirstY: 0},
	{"9patchPopUp": 0},
	{"9patchGameOverPopUp": 0},
	{"9patchTutTextBg": 0},
	{SpellSync: 0},
	{FFruit: 0},
	{FIcon: 0},
	{FButton: 0},
	{FTxtFlyingScore: 0},
	{MinUnlockedCount: 0},
	{MaxUnlockedCount: 0},
	{UnlockedFruit: 0},
	{MaxProgressBar: 0},
	{CoinChance: 0},
	{BoosterChance: 0},
	{MinGiftCoin: 0},
	{MaxGiftCoin: 0},
	{MinGiftBooster: 0},
	{MaxGiftBooster: 0},
	{DeleterChance: 0},
	{BombChance: 0},
	{ShakerChance: 0},
	{UpgradeChance: 0},
	{FruitUnitSize: 0},
	{DangerLineY: 0},
	{DashedLineSpeed: 0},
	{AllFruitTypes: 0},
	{GoalFruit: 0},
	{DeleterCount: 0},
	{BombCount: 0},
	{ShakerCount: 0},
	{UpgradeCount: 0},
	{Coin: 0},
	{Score: 0},
	{ProgressBar: 0},
	{Combo: 0},
	{MergeOccured: 0},
	{CanTouch: 0},
	{SecondChance: 0},
	{CanShowGoal: 0},
	{AdTime: 0},
	{FruitType: 0},
	{vChance: 0},
	{CurFruit: 0},
	{vRandom: 0},
	{vCumulative: 0},
	{SpawnPosX: 0},
	{SpawnPosY: 0},
	{NewFruit: 0},
	{NewFruitID: 0},
	{Size: 0},
	{FirstFruit: 0},
	{SecondFruit: 0},
	{vScore: 0},
	{Pos_X: 0},
	{Pos_Y: 0},
	{Val: 0},
	{FruitID: 0},
	{IsStopTopLoop: 0},
	{BoosterTag: 0},
	{BombID: 0},
	{SpawnX: 0},
	{SpawnY: 0},
	{IsCoin: 0},
	{vRndBooster: 0},
	{vRndCount: 0},
	{Difference: 0},
	{GiftCoin: 0},
	{LayerName: 0},
	{R: 0},
	{G: 0},
	{B: 0},
	{HEXColor: 0},
	{BestScore: 0},
	{GameState: 0},
	{LS_Key: 0},
	{SFX: 0},
	{Music: 0},
	{ScreenWidth: 0},
	{ScreenHeight: 0},
	{SfxTag: 0},
	{FinalGiftCoin: 0}
];

self.InstanceType = {
	Bounding: class extends self.ISpriteInstance {},
	Box: class extends self.ISpriteInstance {},
	Fruit: class extends self.ISpriteInstance {},
	AnimMerge: class extends self.ISpriteInstance {},
	DangerLine: class extends self.ITiledBackgroundInstance {},
	FruitLine: class extends self.ITiledBackgroundInstance {},
	FruitIcon: class extends self.ISpriteInstance {},
	ProgressBarAmount: class extends self.ITiledBackgroundInstance {},
	GiftBox: class extends self.ISpriteInstance {},
	GiftTop: class extends self.ISpriteInstance {},
	TiledBgGame: class extends self.ITiledBackgroundInstance {},
	AnimDeletion: class extends self.ISpriteInstance {},
	Bomb: class extends self.ISpriteInstance {},
	TutHand: class extends self.ISpriteInstance {},
	ParticlesSpark: class extends self.IParticlesInstance {},
	GiftBoxInside: class extends self.ISpriteInstance {},
	TiledBgHome: class extends self.ITiledBackgroundInstance {},
	TiledBgSkyParts: class extends self.ITiledBackgroundInstance {},
	BoosterIcon: class extends self.ISpriteInstance {},
	InteractiveArea: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	ArrayChance: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	FruitList: class extends self.IArrayInstance {},
	JSON_LS: class extends self.IJSONInstance {},
	JSONConfig: class extends self.IJSONInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	TxtBestScore: class extends self.ITextInstance {},
	TxtGeneral: class extends self.ITextInstance {},
	TxtProgressBar: class extends self.ITextInstance {},
	TxtGameOver: class extends self.ITextInstance {},
	TxtDeleter: class extends self.ITextInstance {},
	TxtBomb: class extends self.ITextInstance {},
	TxtShaker: class extends self.ITextInstance {},
	TxtUpgrade: class extends self.ITextInstance {},
	TxtAdsCoin: class extends self.ITextInstance {},
	TxtBoosterCoin: class extends self.ITextInstance {},
	TxtAds: class extends self.ITextInstance {},
	TxtAdsTime: class extends self.ITextInstance {},
	TxtBuyBoosterInfo: class extends self.ITextInstance {},
	TxtBuyBooster: class extends self.ITextInstance {},
	TxtCoin: class extends self.ITextInstance {},
	TxtScore: class extends self.ITextInstance {},
	TxtCombo: class extends self.ITextInstance {},
	TxtFlyingScore: class extends self.ISpriteFontInstance {},
	ComboBg: class extends self.ISpriteInstance {},
	Gift: class extends self.ISpriteInstance {},
	GoalIconBg: class extends self.ISpriteInstance {},
	ProgressBarBg: class extends self.ISpriteInstance {},
	ScoreBg: class extends self.ISpriteInstance {},
	CoinIcon: class extends self.ISpriteInstance {},
	CoinBg: class extends self.ISpriteInstance {},
	Sparkle: class extends self.ISpriteInstance {},
	BlurBG: class extends self.ITiledBackgroundInstance {},
	GiftCoinBg: class extends self.ISpriteInstance {},
	GiftBoosterBg: class extends self.ISpriteInstance {},
	GoalGiftBg: class extends self.ISpriteInstance {},
	TiledBgSky: class extends self.ITiledBackgroundInstance {},
	BoosterCountBg: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	ArrowToNext: class extends self.ISpriteInstance {},
	BasketBot: class extends self.ISpriteInstance {},
	BasketTop: class extends self.ISpriteInstance {},
	Cloud_1: class extends self.ISpriteInstance {},
	Cloud_2: class extends self.ISpriteInstance {},
	Fence: class extends self.ISpriteInstance {},
	HomeFence: class extends self.ISpriteInstance {},
	Playground: class extends self.ISpriteInstance {},
	Tree: class extends self.ISpriteInstance {},
	PlayButtonShadow: class extends self.ISpriteInstance {},
	IconSparkle: class extends self.ISpriteInstance {},
	GoalAchievedText: class extends self.ISpriteInstance {},
	BuyBoosterBg: class extends self.ISpriteInstance {},
	BestScoreIcon: class extends self.ISpriteInstance {},
	BtnBuy: class extends self.ISpriteInstance {},
	BtnClosePopUp: class extends self.ISpriteInstance {},
	BtnAds: class extends self.ISpriteInstance {},
	BtnNoAds: class extends self.ISpriteInstance {},
	BtnDeleter: class extends self.ISpriteInstance {},
	BtnShaker: class extends self.ISpriteInstance {},
	BtnBomb: class extends self.ISpriteInstance {},
	BtnUpgrade: class extends self.ISpriteInstance {},
	BtnCancel: class extends self.ISpriteInstance {},
	BtnHome: class extends self.ISpriteInstance {},
	BtnInfo: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	BtnReset: class extends self.ISpriteInstance {},
	BtnSFX: class extends self.ISpriteInstance {},
	BtnStudio: class extends self.ISpriteInstance {},
	BtnBuyBooster: class extends self.ISpriteInstance {},
	BtnGetGift: class extends self.ISpriteInstance {},
	_9patchPopUp: class extends self.IWorldInstance {},
	_9patchGameOverPopUp: class extends self.IWorldInstance {},
	_9patchTutTextBg: class extends self.IWorldInstance {},
	SpellSync: class extends self.IInstance {},
	FFruit: class extends self.ISpriteInstance {},
	FIcon: class extends self.ISpriteInstance {},
	FButton: class extends self.ISpriteInstance {},
	FTxtFlyingScore: class extends self.ISpriteFontInstance {}
}