const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Date,
		C3.Plugins.LocalStorage,
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Plugins.Mouse,
		C3.Plugins.Arr,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Date.Exps.GetMinutes,
		C3.Plugins.Date.Exps.GetSeconds,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgba255,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Cnds.OnAllGetsComplete,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY
	];
};
self.C3_JsPropNameTable = [
	{Date: 0},
	{LocalStorage: 0},
	{Keyboard: 0},
	{Browser: 0},
	{Background: 0},
	{OffLimits: 0},
	{startTime: 0},
	{endTime: 0},
	{timeToBuild: 0},
	{Tween: 0},
	{Timer: 0},
	{Building: 0},
	{Mouse: 0},
	{BuildingsArr: 0},
	{BuildingTimerText: 0},
	{Text: 0},
	{BuildingCollision: 0},
	{Clouds: 0},
	{Smoke: 0},
	{WeeGooSDK: 0},
	{currentlyHoldingUID: 0},
	{numOfBuildings: 0},
	{timeStamp: 0},
	{type: 0}
];

self.InstanceType = {
	Date: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Background: class extends self.ISpriteInstance {},
	OffLimits: class extends self.ISpriteInstance {},
	Building: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	BuildingsArr: class extends self.IArrayInstance {},
	BuildingTimerText: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	BuildingCollision: class extends self.ISpriteInstance {},
	Clouds: class extends self.ITiledBackgroundInstance {},
	Smoke: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {}
}