const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Anchor,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.TextBox,
		C3.Plugins.Spritefont2,
		C3.Behaviors.TR_AnimatedCounter,
		C3.Behaviors.EightDir,
		C3.Behaviors.LOS,
		C3.Behaviors.MoveTo,
		C3.Behaviors.solid,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Keyboard,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Eponesh_GameScore,
		C3.Behaviors.Pathfinding,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Json.Cnds.CompareValue,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Eponesh_GameScore.Cnds.DeviceType,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Json.Acts.AddTo,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Exps.regexreplace,
		C3.Plugins.System.Exps.regexsearch,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Behaviors.EightDir.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Pathfinding.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.Pathfinding.Cnds.CompareSpeed,
		C3.Behaviors.Pathfinding.Exps.NodeXAt,
		C3.Behaviors.Pathfinding.Exps.CurrentNode,
		C3.Behaviors.Pathfinding.Cnds.OnArrived,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Pathfinding.Acts.Stop,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Pathfinding.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.TouchID,
		C3.Plugins.Touch.Exps.XForID,
		C3.Plugins.Touch.Exps.YForID,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPause,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Eponesh_GameScore.Cnds.OnResume,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Json.Acts.SubtractFrom,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowSticky,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowPreloader,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.TextBox.Acts.AppendText,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Json.Cnds.OnParseSuccess,
		C3.Plugins.LocalStorage.Cnds.OnItemSet,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Json.Exps.ToBeautifiedString,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Eponesh_GameScore.Cnds.IsMobile,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Tween.Exps.Value,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Sin.Acts.UpdateInitialState,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Spritefont2.Cnds.CompareOpacity,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetY
	];
};
self.C3_JsPropNameTable = [
	{a5: 0},
	{СледитьЗа: 0},
	{camera_gk_mu: 0},
	{Якорь: 0},
	{Kill_bot: 0},
	{ui_f: 0},
	{ui_luk: 0},
	{Синусоид: 0},
	{Синусоид2: 0},
	{"2w25": 0},
	{Угасание: 0},
	{w20: 0},
	{Поворот: 0},
	{fx_rotate_line2: 0},
	{Синусоида: 0},
	{fx_star_white: 0},
	{startY: 0},
	{"9patch": 0},
	{ID: 0},
	{PlayerAva: 0},
	{hh3: 0},
	{knpss: 0},
	{d3: 0},
	{KNP_ZAB: 0},
	{d13: 0},
	{L: 0},
	{d17: 0},
	{d8: 0},
	{tgtgt: 0},
	{"12d": 0},
	{d16: 0},
	{Nagg: 0},
	{w32: 0},
	{w31: 0},
	{game_go: 0},
	{a6: 0},
	{w2: 0},
	{s5: 0},
	{w23: 0},
	{d2: 0},
	{h5: 0},
	{w16: 0},
	{w7: 0},
	{w8: 0},
	{w9: 0},
	{w18: 0},
	{"4as": 0},
	{Gg2: 0},
	{h1: 0},
	{h6: 0},
	{pet_gl: 0},
	{w12: 0},
	{d11: 0},
	{d1: 0},
	{w19: 0},
	{Background_ScreenGlow2: 0},
	{fx_glow: 0},
	{GL_Avatar_M: 0},
	{Image_CircleGlow_White2: 0},
	{image_glow_rectangle: 0},
	{Per_1: 0},
	{Per_2: 0},
	{Popup_Slide02_Single_Navy_TopGlow: 0},
	{SPRATE15: 0},
	{SPRATE16: 0},
	{SPRATE17: 0},
	{gg_1: 0},
	{SPRATE20: 0},
	{g33: 0},
	{ggq: 0},
	{ext_gg: 0},
	{зз1: 0},
	{w30: 0},
	{w4: 0},
	{w25: 0},
	{j7: 0},
	{h7: 0},
	{d7: 0},
	{Твинанимация: 0},
	{a8: 0},
	{d5: 0},
	{d15: 0},
	{d12: 0},
	{w29: 0},
	{"1Im2age_Effect_Rotate_White": 0},
	{"2Background_ScreenGlow": 0},
	{Glow_Cirlce: 0},
	{Image_CircleGlow_White: 0},
	{manis: 0},
	{manis2: 0},
	{UI: 0},
	{UI00: 0},
	{UI11: 0},
	{UI12: 0},
	{UI14: 0},
	{UI2: 0},
	{UI3: 0},
	{UI4: 0},
	{UI6: 0},
	{UI7: 0},
	{UI9: 0},
	{d6: 0},
	{Go: 0},
	{Wheel_k: 0},
	{w11: 0},
	{w3: 0},
	{ext: 0},
	{a7: 0},
	{a22: 0},
	{w21: 0},
	{w15: 0},
	{w6: 0},
	{ukzatel: 0},
	{"4epi": 0},
	{Pl: 0},
	{a1: 0},
	{a4: 0},
	{w33: 0},
	{a21: 0},
	{w24: 0},
	{w22: 0},
	{h77: 0},
	{w14: 0},
	{Icon_Battle: 0},
	{d4: 0},
	{w28: 0},
	{str1: 0},
	{SDDDS: 0},
	{IDS: 0},
	{a3: 0},
	{Kill_bot2: 0},
	{ui_luk2: 0},
	{AA: 0},
	{DD: 0},
	{SS: 0},
	{OB4: 0},
	{a2: 0},
	{fff: 0},
	{WW: 0},
	{Jou_part_one2: 0},
	{Jou_part_run2: 0},
	{tahh: 0},
	{logs: 0},
	{XX: 0},
	{HE_Kontur: 0},
	{Text_UI: 0},
	{ID_Tovar: 0},
	{AnimatedCounter: 0},
	{Kontur: 0},
	{ВвентиляцииС: 0},
	{ПрыгаетС: 0},
	{ВыходитИзВентиляцииС: 0},
	{"8Направлений": 0},
	{ПолеЗрения: 0},
	{Play: 0},
	{Speed: 0},
	{cam: 0},
	{Какая: 0},
	{Hapka: 0},
	{plau_gl: 0},
	{hapka_gl: 0},
	{gl_ti: 0},
	{ДвижениеК: 0},
	{pet: 0},
	{ZZ1: 0},
	{ZZ2: 0},
	{ZZ3: 0},
	{ZZ4: 0},
	{ZZ5: 0},
	{ZZ6: 0},
	{ZZ7: 0},
	{ZZ8: 0},
	{ZZ9: 0},
	{ZZ10: 0},
	{ZZ11: 0},
	{ZZ12: 0},
	{ZZ13: 0},
	{ZZ14: 0},
	{ZZ15: 0},
	{ZZ16: 0},
	{ZZ17: 0},
	{ZZ18: 0},
	{ZZ19: 0},
	{ZZ20: 0},
	{tk_play: 0},
	{tk_bot_1: 0},
	{tk_bot_2: 0},
	{tk_bot_3: 0},
	{tk_bot_4: 0},
	{tk_bot_5: 0},
	{tk_bot_6: 0},
	{tk_bot_7: 0},
	{tk_bot_8: 0},
	{tk_bot_9: 0},
	{Mini_karta: 0},
	{tk_bot_10: 0},
	{tk_bot_11: 0},
	{Mini_karta2: 0},
	{z1: 0},
	{z2: 0},
	{z3: 0},
	{ventel: 0},
	{LX: 0},
	{lik: 0},
	{l3: 0},
	{l4: 0},
	{l2: 0},
	{l5: 0},
	{l1: 0},
	{l6: 0},
	{g19: 0},
	{g16: 0},
	{g22: 0},
	{Твердый: 0},
	{g2: 0},
	{g1: 0},
	{g26: 0},
	{g9: 0},
	{g10: 0},
	{g12: 0},
	{g13: 0},
	{g14: 0},
	{g24: 0},
	{g7: 0},
	{g8: 0},
	{g6: 0},
	{g4: 0},
	{g3: 0},
	{g30: 0},
	{hh4: 0},
	{g28: 0},
	{AAASS: 0},
	{g20: 0},
	{g21: 0},
	{g23: 0},
	{g18: 0},
	{g25: 0},
	{Задание: 0},
	{ВыполняетсяЗадание: 0},
	{Мертв: 0},
	{Замечен: 0},
	{ТрупНайден: 0},
	{Нету: 0},
	{Шапка: 0},
	{Bot: 0},
	{Bot2: 0},
	{Bot3: 0},
	{Bot4: 0},
	{Bot5: 0},
	{Bot6: 0},
	{Bot7: 0},
	{Bot8: 0},
	{Bot9: 0},
	{krov: 0},
	{Bot10: 0},
	{Bot11: 0},
	{"4erep": 0},
	{ggg1: 0},
	{aktiv_fon: 0},
	{Jou_part_one: 0},
	{Jou_part_run: 0},
	{Тач: 0},
	{Аудио: 0},
	{ЛокальноеХранилище: 0},
	{Клавиатура: 0},
	{AJAX: 0},
	{JSON: 0},
	{GamePush: 0},
	{po_Y: 0},
	{skin: 0},
	{ПоискПути: 0},
	{vrag: 0},
	{st_UI: 0},
	{skin_play: 0},
	{Kd_kill: 0},
	{Play_game: 0},
	{Kill_DA: 0},
	{n: 0},
	{q: 0},
	{zd_gotovo: 0},
	{zd_maks: 0},
	{ТачX_aim: 0},
	{ТачY_aim: 0},
	{Тач_1_id: 0},
	{scroll: 0},
	{scrollC: 0},
	{scrollM: 0},
	{scrollS: 0},
	{skin_gl: 0},
	{Music: 0},
	{Sound: 0},
	{Obloko: 0},
	{Time_AD: 0},
	{sectorCount: 0},
	{winningSector: 0}
];

self.InstanceType = {
	a5: class extends self.ISpriteInstance {},
	camera_gk_mu: class extends self.ISpriteInstance {},
	Kill_bot: class extends self.ISpriteInstance {},
	ui_f: class extends self.ISpriteInstance {},
	ui_luk: class extends self.ISpriteInstance {},
	_2w25: class extends self.ISpriteInstance {},
	w20: class extends self.ISpriteInstance {},
	fx_rotate_line2: class extends self.ISpriteInstance {},
	fx_star_white: class extends self.ISpriteInstance {},
	_9patch: class extends self.ISpriteInstance {},
	PlayerAva: class extends self.ISpriteInstance {},
	hh3: class extends self.ISpriteInstance {},
	d3: class extends self.ISpriteInstance {},
	d13: class extends self.ISpriteInstance {},
	d17: class extends self.ISpriteInstance {},
	d8: class extends self.ISpriteInstance {},
	_12d: class extends self.ISpriteInstance {},
	d16: class extends self.ISpriteInstance {},
	w32: class extends self.ISpriteInstance {},
	w31: class extends self.ISpriteInstance {},
	game_go: class extends self.ISpriteInstance {},
	a6: class extends self.ISpriteInstance {},
	w2: class extends self.ISpriteInstance {},
	s5: class extends self.ISpriteInstance {},
	w23: class extends self.ISpriteInstance {},
	d2: class extends self.ISpriteInstance {},
	h5: class extends self.ISpriteInstance {},
	w16: class extends self.ISpriteInstance {},
	w7: class extends self.ISpriteInstance {},
	w8: class extends self.ISpriteInstance {},
	w9: class extends self.ISpriteInstance {},
	w18: class extends self.ISpriteInstance {},
	_4as: class extends self.IParticlesInstance {},
	h1: class extends self.ISpriteInstance {},
	h6: class extends self.ITiledBackgroundInstance {},
	pet_gl: class extends self.ISpriteInstance {},
	w12: class extends self.ISpriteInstance {},
	d11: class extends self.ISpriteInstance {},
	d1: class extends self.ISpriteInstance {},
	w19: class extends self.ISpriteInstance {},
	Background_ScreenGlow2: class extends self.ISpriteInstance {},
	fx_glow: class extends self.ISpriteInstance {},
	GL_Avatar_M: class extends self.ISpriteInstance {},
	Image_CircleGlow_White2: class extends self.ISpriteInstance {},
	image_glow_rectangle: class extends self.ISpriteInstance {},
	Per_1: class extends self.ISpriteInstance {},
	Per_2: class extends self.ISpriteInstance {},
	Popup_Slide02_Single_Navy_TopGlow: class extends self.ISpriteInstance {},
	SPRATE15: class extends self.ISpriteInstance {},
	SPRATE16: class extends self.ISpriteInstance {},
	SPRATE17: class extends self.ISpriteInstance {},
	SPRATE20: class extends self.ISpriteInstance {},
	g33: class extends self.ISpriteInstance {},
	ggq: class extends self.ISpriteInstance {},
	ext_gg: class extends self.ISpriteInstance {},
	зз1: class extends self.ISpriteInstance {},
	w30: class extends self.ISpriteInstance {},
	w4: class extends self.ISpriteInstance {},
	w25: class extends self.ISpriteInstance {},
	j7: class extends self.ISpriteInstance {},
	h7: class extends self.ISpriteInstance {},
	d7: class extends self.ISpriteInstance {},
	a8: class extends self.ISpriteInstance {},
	d5: class extends self.ISpriteInstance {},
	d15: class extends self.ISpriteInstance {},
	d12: class extends self.ISpriteInstance {},
	w29: class extends self.ISpriteInstance {},
	_1Im2age_Effect_Rotate_White: class extends self.ISpriteInstance {},
	_2Background_ScreenGlow: class extends self.ISpriteInstance {},
	Glow_Cirlce: class extends self.ISpriteInstance {},
	Image_CircleGlow_White: class extends self.ISpriteInstance {},
	manis: class extends self.ISpriteInstance {},
	manis2: class extends self.ISpriteInstance {},
	UI: class extends self.ISpriteInstance {},
	UI00: class extends self.ISpriteInstance {},
	UI11: class extends self.ISpriteInstance {},
	UI12: class extends self.ISpriteInstance {},
	UI14: class extends self.ISpriteInstance {},
	UI2: class extends self.ISpriteInstance {},
	UI3: class extends self.ISpriteInstance {},
	UI4: class extends self.ISpriteInstance {},
	UI6: class extends self.ISpriteInstance {},
	UI7: class extends self.ISpriteInstance {},
	UI9: class extends self.ISpriteInstance {},
	d6: class extends self.ISpriteInstance {},
	Wheel_k: class extends self.ISpriteInstance {},
	w11: class extends self.ISpriteInstance {},
	w3: class extends self.ISpriteInstance {},
	ext: class extends self.ISpriteInstance {},
	a7: class extends self.ISpriteInstance {},
	a22: class extends self.ISpriteInstance {},
	w21: class extends self.ISpriteInstance {},
	w15: class extends self.ISpriteInstance {},
	w6: class extends self.ISpriteInstance {},
	ukzatel: class extends self.ISpriteInstance {},
	_4epi: class extends self.ISpriteInstance {},
	Pl: class extends self.ISpriteInstance {},
	a1: class extends self.ISpriteInstance {},
	a4: class extends self.ISpriteInstance {},
	w33: class extends self.ISpriteInstance {},
	a21: class extends self.ISpriteInstance {},
	w24: class extends self.ISpriteInstance {},
	w22: class extends self.ISpriteInstance {},
	h77: class extends self.ISpriteInstance {},
	w14: class extends self.ISpriteInstance {},
	Icon_Battle: class extends self.ISpriteInstance {},
	d4: class extends self.ISpriteInstance {},
	w28: class extends self.ISpriteInstance {},
	str1: class extends self.ISpriteInstance {},
	SDDDS: class extends self.ISpriteInstance {},
	a3: class extends self.ISpriteInstance {},
	Kill_bot2: class extends self.ISpriteInstance {},
	ui_luk2: class extends self.ISpriteInstance {},
	AA: class extends self.ISpriteInstance {},
	DD: class extends self.ISpriteInstance {},
	SS: class extends self.ISpriteInstance {},
	OB4: class extends self.ISpriteInstance {},
	a2: class extends self.ISpriteInstance {},
	fff: class extends self.ISpriteInstance {},
	WW: class extends self.ISpriteInstance {},
	Jou_part_one2: class extends self.ISpriteInstance {},
	Jou_part_run2: class extends self.ISpriteInstance {},
	tahh: class extends self.ISpriteInstance {},
	logs: class extends self.ITextInputInstance {},
	HE_Kontur: class extends self.ISpriteFontInstance {},
	Kontur: class extends self.ISpriteFontInstance {},
	Play: class extends self.ISpriteInstance {},
	cam: class extends self.ISpriteInstance {},
	Hapka: class extends self.ISpriteInstance {},
	plau_gl: class extends self.ISpriteInstance {},
	hapka_gl: class extends self.ISpriteInstance {},
	gl_ti: class extends self.ISpriteInstance {},
	pet: class extends self.ISpriteInstance {},
	ZZ1: class extends self.ISpriteInstance {},
	ZZ2: class extends self.ISpriteInstance {},
	ZZ3: class extends self.ISpriteInstance {},
	ZZ4: class extends self.ISpriteInstance {},
	ZZ5: class extends self.ISpriteInstance {},
	ZZ6: class extends self.ISpriteInstance {},
	ZZ7: class extends self.ISpriteInstance {},
	ZZ8: class extends self.ISpriteInstance {},
	ZZ9: class extends self.ISpriteInstance {},
	ZZ10: class extends self.ISpriteInstance {},
	ZZ11: class extends self.ISpriteInstance {},
	ZZ12: class extends self.ISpriteInstance {},
	ZZ13: class extends self.ISpriteInstance {},
	ZZ14: class extends self.ISpriteInstance {},
	ZZ15: class extends self.ISpriteInstance {},
	ZZ16: class extends self.ISpriteInstance {},
	ZZ17: class extends self.ISpriteInstance {},
	ZZ18: class extends self.ISpriteInstance {},
	ZZ19: class extends self.ISpriteInstance {},
	ZZ20: class extends self.ISpriteInstance {},
	tk_play: class extends self.ISpriteInstance {},
	tk_bot_1: class extends self.ISpriteInstance {},
	tk_bot_2: class extends self.ISpriteInstance {},
	tk_bot_3: class extends self.ISpriteInstance {},
	tk_bot_4: class extends self.ISpriteInstance {},
	tk_bot_5: class extends self.ISpriteInstance {},
	tk_bot_6: class extends self.ISpriteInstance {},
	tk_bot_7: class extends self.ISpriteInstance {},
	tk_bot_8: class extends self.ISpriteInstance {},
	tk_bot_9: class extends self.ISpriteInstance {},
	Mini_karta: class extends self.ISpriteInstance {},
	tk_bot_10: class extends self.ISpriteInstance {},
	tk_bot_11: class extends self.ISpriteInstance {},
	Mini_karta2: class extends self.ISpriteInstance {},
	z1: class extends self.ISpriteInstance {},
	z2: class extends self.ISpriteInstance {},
	z3: class extends self.ISpriteInstance {},
	ventel: class extends self.ISpriteInstance {},
	lik: class extends self.ISpriteInstance {},
	l3: class extends self.ISpriteInstance {},
	l4: class extends self.ISpriteInstance {},
	l2: class extends self.ISpriteInstance {},
	l5: class extends self.ISpriteInstance {},
	l1: class extends self.ISpriteInstance {},
	l6: class extends self.ISpriteInstance {},
	g19: class extends self.ISpriteInstance {},
	g16: class extends self.ISpriteInstance {},
	g22: class extends self.ISpriteInstance {},
	g2: class extends self.ISpriteInstance {},
	g1: class extends self.ISpriteInstance {},
	g26: class extends self.ISpriteInstance {},
	g9: class extends self.ISpriteInstance {},
	g10: class extends self.ISpriteInstance {},
	g12: class extends self.ISpriteInstance {},
	g13: class extends self.ISpriteInstance {},
	g14: class extends self.ISpriteInstance {},
	g24: class extends self.ISpriteInstance {},
	g7: class extends self.ISpriteInstance {},
	g8: class extends self.ISpriteInstance {},
	g6: class extends self.ISpriteInstance {},
	g4: class extends self.ISpriteInstance {},
	g3: class extends self.ISpriteInstance {},
	g30: class extends self.ISpriteInstance {},
	hh4: class extends self.ISpriteInstance {},
	g28: class extends self.ISpriteInstance {},
	AAASS: class extends self.ISpriteInstance {},
	g20: class extends self.ISpriteInstance {},
	g21: class extends self.ISpriteInstance {},
	g23: class extends self.ISpriteInstance {},
	g18: class extends self.ISpriteInstance {},
	g25: class extends self.ISpriteInstance {},
	Bot: class extends self.ISpriteInstance {},
	Bot2: class extends self.ISpriteInstance {},
	Bot3: class extends self.ISpriteInstance {},
	Bot4: class extends self.ISpriteInstance {},
	Bot5: class extends self.ISpriteInstance {},
	Bot6: class extends self.ISpriteInstance {},
	Bot7: class extends self.ISpriteInstance {},
	Bot8: class extends self.ISpriteInstance {},
	Bot9: class extends self.ISpriteInstance {},
	krov: class extends self.IParticlesInstance {},
	Bot10: class extends self.ISpriteInstance {},
	Bot11: class extends self.ISpriteInstance {},
	_4erep: class extends self.ISpriteInstance {},
	ggg1: class extends self.ISpriteInstance {},
	aktiv_fon: class extends self.ITiledBackgroundInstance {},
	Jou_part_one: class extends self.ISpriteInstance {},
	Jou_part_run: class extends self.ISpriteInstance {},
	Тач: class extends self.IInstance {},
	Аудио: class extends self.IInstance {},
	ЛокальноеХранилище: class extends self.IInstance {},
	Клавиатура: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	GamePush: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	po_Y: class extends self.ISpriteInstance {},
	skin: class extends self.ISpriteInstance {},
	vrag: class extends self.ISpriteInstance {},
	st_UI: class extends self.ISpriteInstance {}
}