const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Shape3D,
		C3.Behaviors.solid,
		C3.Plugins.Camera3D,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Behaviors.LOS,
		C3.Plugins.Spritefont2,
		C3.Behaviors.destroy,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.Particles,
		C3.Plugins.Touch,
		C3.Behaviors.Pin,
		C3.Plugins.Audio,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.bound,
		C3.Behaviors.Rotate,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.WGSDK,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Camera3D.Acts.LookParallelToLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Camera3D.Acts.SetPosition,
		C3.Plugins.Mouse.Cnds.OnMovement,
		C3.Plugins.Camera3D.Acts.RotateCamera,
		C3.Plugins.Mouse.Exps.MovementX,
		C3.Plugins.Mouse.Exps.MovementY,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.Mouse.Cnds.HasPointerLock,
		C3.Plugins.Mouse.Acts.RequestPointerLock,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.LOS.Acts.AddObstacle,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.EightDir.Acts.SetVectorX,
		C3.Behaviors.EightDir.Acts.SetVectorY,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Camera3D.Exps.CameraXRotation,
		C3.Behaviors.EightDir.Exps.MaxSpeed,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Shape3D.Cnds.OnCreated,
		C3.Plugins.Shape3D.Acts.SetWidth,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Shape3D.Acts.SetFaceObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Shape3D.Acts.SetTowardPosition,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Plugins.Shape3D.Exps.ZHeight,
		C3.Plugins.Shape3D.Acts.SetInstanceVar,
		C3.Plugins.Camera3D.Exps.CameraYRotation,
		C3.Plugins.Shape3D.Acts.SetAngle,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Shape3D.Acts.SetPos,
		C3.Plugins.Shape3D.Exps.Angle,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Shape3D.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Shape3D.Acts.AddInstanceVar,
		C3.Plugins.Shape3D.Cnds.CompareZElevation,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.Shape3D.Cnds.OnCollision,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Mouse.Acts.ReleasePointerLock,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.fps,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Exps.int,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Camera3D.Exps.CameraX,
		C3.Plugins.Camera3D.Exps.CameraY,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Tween.Exps.Value,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.WGSDK.Cnds.RewardReady,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.WGSDK.Cnds.RewardGranted,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnAllGetsComplete,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.GoToLayoutByName
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Building01: 0},
	{"3DCamera": 0},
	{"8Direction": 0},
	{PlayerCollision: 0},
	{Mouse: 0},
	{Skybox: 0},
	{ZombieBillboard: 0},
	{Keyboard: 0},
	{Building02: 0},
	{Building03: 0},
	{Wall02: 0},
	{TrashBottom: 0},
	{Fence: 0},
	{Building04: 0},
	{Building05: 0},
	{VanBottom: 0},
	{Wall03: 0},
	{Wall01: 0},
	{Wall04: 0},
	{TrashTop: 0},
	{InitialX: 0},
	{InitialY: 0},
	{InitialAngle: 0},
	{Tween: 0},
	{Sine: 0},
	{GunOverlay: 0},
	{Ground: 0},
	{InvisibleWall01: 0},
	{InvisibleWall02: 0},
	{LineOfSight: 0},
	{ZombieCollision: 0},
	{aim: 0},
	{Pipe01: 0},
	{Pipe02: 0},
	{AC: 0},
	{ElectricPanelBox: 0},
	{Crate: 0},
	{ZombieAnimations: 0},
	{Building5: 0},
	{VanTop: 0},
	{VanWindow: 0},
	{Cables01: 0},
	{Cables2: 0},
	{ruke: 0},
	{zang: 0},
	{speed: 0},
	{DestroyOutsideLayout: 0},
	{"3DBullet": 0},
	{Sprite2: 0},
	{bljesak: 0},
	{ang: 0},
	{zVEL: 0},
	{grav: 0},
	{Fade: 0},
	{"3DParticles": 0},
	{yVEL: 0},
	{rand: 0},
	{"3DParticles2": 0},
	{Blood: 0},
	{Building2: 0},
	{"3DGround": 0},
	{zid: 0},
	{StarsFont: 0},
	{StarsFont2: 0},
	{Sprite: 0},
	{Confetti: 0},
	{nextlevel: 0},
	{Touch: 0},
	{Pin: 0},
	{BSound: 0},
	{ponovo: 0},
	{home: 0},
	{BSound3: 0},
	{Pozadinazakraj: 0},
	{StarsFont3: 0},
	{replay: 0},
	{Audio: 0},
	{bljesak2: 0},
	{zamka: 0},
	{shootbtn: 0},
	{naprijed: 0},
	{lijevo: 0},
	{nazad: 0},
	{desno: 0},
	{Sprite3: 0},
	{play: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{ZombieAnimations2: 0},
	{Lens: 0},
	{DragDrop: 0},
	{BoundToLayout: 0},
	{Scope: 0},
	{metci: 0},
	{Rotate: 0},
	{coin3d: 0},
	{COIN: 0},
	{noammo: 0},
	{PlatformInfo: 0},
	{Sprite6: 0},
	{play2: 0},
	{nextlevel2: 0},
	{SkipLevel: 0},
	{crvena: 0},
	{House02: 0},
	{Roof02: 0},
	{home2: 0},
	{Plant: 0},
	{Stone01: 0},
	{TreeModel: 0},
	{TreeTexture: 0},
	{"3DShape025": 0},
	{"3DShape023": 0},
	{"3DShape024": 0},
	{"3DShape010": 0},
	{"3DShape022": 0},
	{"3DShape005": 0},
	{"3DShape013": 0},
	{"3DShape014": 0},
	{"3DShape012": 0},
	{sok: 0},
	{sokprskanje: 0},
	{sokeksplozija: 0},
	{Sprite7: 0},
	{vatromet: 0},
	{congrat: 0},
	{replay123: 0},
	{MOREGAMES: 0},
	{Tutorial2: 0},
	{Browser: 0},
	{a: 0},
	{Wheel: 0},
	{Text: 0},
	{krug: 0},
	{zavrti: 0},
	{playzawheels: 0},
	{zavrtisareklamama: 0},
	{addmetakreklama: 0},
	{StarsFont4: 0},
	{Sprite19: 0},
	{zavrti3: 0},
	{StarsFont1: 0},
	{zavrti2: 0},
	{playerName: 0},
	{Loginy8moja: 0},
	{y8: 0},
	{skip: 0},
	{tacka: 0},
	{LocalStorage: 0},
	{hintreklama2: 0},
	{Sprite8: 0},
	{scopebutton: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite26: 0},
	{zidleveli: 0},
	{levelselect: 0},
	{zidlevelidonji: 0},
	{Open: 0},
	{Level: 0},
	{LevelsBlock: 0},
	{SpriteFont123: 0},
	{WeeGooSDK: 0},
	{nagrade: 0},
	{Family1: 0},
	{mobilebuttons: 0},
	{LAST_LEVEL: 0},
	{WIN2: 0},
	{Win: 0},
	{Metci: 0},
	{Coins: 0},
	{Score: 0},
	{sound: 0},
	{dz: 0},
	{SoundEf: 0},
	{InputLeft: 0},
	{InputRight: 0},
	{InputUp: 0},
	{InputDown: 0},
	{HorizontalAxis: 0},
	{VerticalAxis: 0},
	{AxisAngle: 0},
	{WALKSPEED: 0},
	{RUNSPEED: 0},
	{AngleTowardsPlayer: 0},
	{sectorCount: 0},
	{prizes: 0},
	{Stars: 0},
	{winningSector: 0}
];

self.InstanceType = {
	Building01: class extends self.I3DShapeInstance {},
	_3DCamera: class extends self.IInstance {},
	PlayerCollision: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Skybox: class extends self.I3DShapeInstance {},
	ZombieBillboard: class extends self.I3DShapeInstance {},
	Keyboard: class extends self.IInstance {},
	Building02: class extends self.I3DShapeInstance {},
	Building03: class extends self.I3DShapeInstance {},
	Wall02: class extends self.I3DShapeInstance {},
	TrashBottom: class extends self.I3DShapeInstance {},
	Fence: class extends self.I3DShapeInstance {},
	Building04: class extends self.I3DShapeInstance {},
	Building05: class extends self.I3DShapeInstance {},
	VanBottom: class extends self.I3DShapeInstance {},
	Wall03: class extends self.I3DShapeInstance {},
	Wall01: class extends self.I3DShapeInstance {},
	Wall04: class extends self.I3DShapeInstance {},
	TrashTop: class extends self.I3DShapeInstance {},
	GunOverlay: class extends self.ISpriteInstance {},
	Ground: class extends self.ISpriteInstance {},
	InvisibleWall01: class extends self.ISpriteInstance {},
	InvisibleWall02: class extends self.ISpriteInstance {},
	ZombieCollision: class extends self.ISpriteInstance {},
	aim: class extends self.ISpriteInstance {},
	Pipe01: class extends self.I3DShapeInstance {},
	Pipe02: class extends self.I3DShapeInstance {},
	AC: class extends self.I3DShapeInstance {},
	ElectricPanelBox: class extends self.I3DShapeInstance {},
	Crate: class extends self.I3DShapeInstance {},
	ZombieAnimations: class extends self.ISpriteInstance {},
	Building5: class extends self.I3DShapeInstance {},
	VanTop: class extends self.I3DShapeInstance {},
	VanWindow: class extends self.I3DShapeInstance {},
	Cables01: class extends self.I3DShapeInstance {},
	Cables2: class extends self.I3DShapeInstance {},
	ruke: class extends self.ISpriteFontInstance {},
	_3DBullet: class extends self.I3DShapeInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	bljesak: class extends self.ISpriteInstance {},
	_3DParticles: class extends self.I3DShapeInstance {},
	_3DParticles2: class extends self.I3DShapeInstance {},
	Blood: class extends self.ISpriteInstance {},
	Building2: class extends self.I3DShapeInstance {},
	_3DGround: class extends self.I3DShapeInstance {},
	zid: class extends self.I3DShapeInstance {},
	StarsFont: class extends self.ITextInstance {},
	StarsFont2: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Confetti: class extends self.IParticlesInstance {},
	nextlevel: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	BSound: class extends self.ISpriteInstance {},
	ponovo: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	BSound3: class extends self.ISpriteInstance {},
	Pozadinazakraj: class extends self.ISpriteInstance {},
	StarsFont3: class extends self.ITextInstance {},
	replay: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	bljesak2: class extends self.ISpriteInstance {},
	zamka: class extends self.I3DShapeInstance {},
	shootbtn: class extends self.ISpriteInstance {},
	naprijed: class extends self.ISpriteInstance {},
	lijevo: class extends self.ISpriteInstance {},
	nazad: class extends self.ISpriteInstance {},
	desno: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	ZombieAnimations2: class extends self.ISpriteInstance {},
	Lens: class extends self.ISpriteInstance {},
	Scope: class extends self.ISpriteInstance {},
	metci: class extends self.ITextInstance {},
	coin3d: class extends self.I3DShapeInstance {},
	COIN: class extends self.ISpriteInstance {},
	noammo: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	play2: class extends self.ISpriteInstance {},
	nextlevel2: class extends self.ISpriteInstance {},
	SkipLevel: class extends self.ISpriteInstance {},
	crvena: class extends self.ISpriteInstance {},
	House02: class extends self.I3DShapeInstance {},
	Roof02: class extends self.I3DShapeInstance {},
	home2: class extends self.ISpriteInstance {},
	Plant: class extends self.I3DShapeInstance {},
	Stone01: class extends self.I3DShapeInstance {},
	TreeModel: class extends self.I3DShapeInstance {},
	TreeTexture: class extends self.ISpriteInstance {},
	_3DShape025: class extends self.I3DShapeInstance {},
	_3DShape023: class extends self.I3DShapeInstance {},
	_3DShape024: class extends self.I3DShapeInstance {},
	_3DShape010: class extends self.I3DShapeInstance {},
	_3DShape022: class extends self.I3DShapeInstance {},
	_3DShape005: class extends self.I3DShapeInstance {},
	_3DShape013: class extends self.I3DShapeInstance {},
	_3DShape014: class extends self.I3DShapeInstance {},
	_3DShape012: class extends self.I3DShapeInstance {},
	sok: class extends self.I3DShapeInstance {},
	sokprskanje: class extends self.ISpriteInstance {},
	sokeksplozija: class extends self.I3DShapeInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	vatromet: class extends self.ISpriteInstance {},
	congrat: class extends self.ISpriteInstance {},
	replay123: class extends self.ISpriteInstance {},
	MOREGAMES: class extends self.ISpriteInstance {},
	Tutorial2: class extends self.ISpriteFontInstance {},
	Browser: class extends self.IInstance {},
	Wheel: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	krug: class extends self.ISpriteInstance {},
	Pin: class extends self.ISpriteInstance {},
	zavrti: class extends self.ISpriteInstance {},
	playzawheels: class extends self.ISpriteInstance {},
	zavrtisareklamama: class extends self.ISpriteInstance {},
	addmetakreklama: class extends self.ISpriteInstance {},
	StarsFont4: class extends self.ITextInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	zavrti3: class extends self.ISpriteInstance {},
	StarsFont1: class extends self.ITextInstance {},
	zavrti2: class extends self.ISpriteInstance {},
	playerName: class extends self.ITextInstance {},
	Loginy8moja: class extends self.ISpriteInstance {},
	y8: class extends self.ISpriteInstance {},
	skip: class extends self.ISpriteInstance {},
	tacka: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	hintreklama2: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	scopebutton: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	zidleveli: class extends self.ISpriteInstance {},
	levelselect: class extends self.ISpriteInstance {},
	zidlevelidonji: class extends self.ISpriteInstance {},
	LevelsBlock: class extends self.ISpriteInstance {},
	SpriteFont123: class extends self.ISpriteFontInstance {},
	WeeGooSDK: class extends self.IInstance {},
	nagrade: class extends self.ISpriteInstance {},
	Family1: class extends self.I3DShapeInstance {},
	mobilebuttons: class extends self.ISpriteInstance {}
}