const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Camera3D,
		C3.Plugins.Touch,
		C3.Plugins.Shape3D,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.Spritefont2,
		C3.Plugins.Sprite,
		C3.Behaviors.Timer,
		C3.Behaviors.Rotate,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Shape3D.Exps.Width,
		C3.Plugins.Shape3D.Exps.Height,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Shape3D.Acts.SetSize,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Shape3D.Acts.SetZHeight,
		C3.Plugins.Shape3D.Exps.ZHeight,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Plugins.Shape3D.Cnds.IsOverlapping,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Shape3D.Exps.Count,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Shape3D.Acts.SetBoolInstanceVar,
		C3.Plugins.TiledBg.Cnds.CompareOpacity,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Shape3D.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Shape3D.Acts.SetPos,
		C3.Plugins.Shape3D.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Shape3D.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Repeat,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.Camera3D.Exps.CameraX,
		C3.Plugins.Camera3D.Exps.CameraY,
		C3.Plugins.Camera3D.Exps.LookX,
		C3.Plugins.Camera3D.Exps.LookY
	];
};
self.C3_JsPropNameTable = [
	{"3DCamera": 0},
	{Touch: 0},
	{Terrain: 0},
	{Sine: 0},
	{WaterTexture: 0},
	{TerrainTopTex: 0},
	{Tween: 0},
	{Berry: 0},
	{TerrainSideTex: 0},
	{orbiting: 0},
	{orbitAngle: 0},
	{Harvester1: 0},
	{HarvesterSaw: 0},
	{Harvester2: 0},
	{Fader: 0},
	{TextTutorial: 0},
	{TextGameOver: 0},
	{TextVictory: 0},
	{Obstacle: 0},
	{TexStoneLargeSide_0: 0},
	{TexStoneSmallSide: 0},
	{TexStoneLargeFront: 0},
	{TexStoneSmallFront: 0},
	{TexStoneLargeSide_1: 0},
	{TexLogFront: 0},
	{TexLogSide_0: 0},
	{TexLogSide_1: 0},
	{onCooldown: 0},
	{Timer: 0},
	{Mushroom: 0},
	{TexMushroomSide: 0},
	{TexMushroomFront: 0},
	{ProgressBar: 0},
	{TextProgress: 0},
	{ProgressBarBackground: 0},
	{TextVictoryFinal: 0},
	{TexTreeSide: 0},
	{TreeLeaves_0: 0},
	{TreeLeaves_1: 0},
	{TreeLeaves_2: 0},
	{TerrainFake: 0},
	{ShipPart0: 0},
	{ShipPart1: 0},
	{ShipPart2: 0},
	{ShipPart3: 0},
	{ShipPart4: 0},
	{ShipPart5: 0},
	{TexStoneHugeSides: 0},
	{TexStoneHugeFront: 0},
	{Rotate: 0},
	{Particles: 0},
	{BerryShort: 0},
	{TexBerryTall_02: 0},
	{TexBerryTall_12: 0},
	{TexBerryTall_22: 0},
	{TexBerryTall_32: 0},
	{TexBerryTall_01: 0},
	{TexBerryTall_11: 0},
	{TexBerryTall_21: 0},
	{TexBerryTall_31: 0},
	{TexBerryTall_00: 0},
	{TexBerryTall_10: 0},
	{TexBerryTall_20: 0},
	{TexBerryTall_30: 0},
	{TexBerryShort_02: 0},
	{TexBerryShort_12: 0},
	{TexBerryShort_22: 0},
	{TexBerryShort_32: 0},
	{TexBerryShort_01: 0},
	{TexBerryShort_11: 0},
	{TexBerryShort_21: 0},
	{TexBerryShort_31: 0},
	{TexBerryShort_00: 0},
	{TexBerryShort_10: 0},
	{TexBerryShort_20: 0},
	{TexBerryShort_30: 0},
	{WeeGooSDK: 0},
	{objective: 0},
	{quota: 0},
	{orbitSpeed: 0},
	{orbitDirection: 0},
	{gameOver: 0},
	{levelBeaten: 0},
	{levelTransition: 0},
	{tutorial: 0},
	{BERRY_SIZE: 0},
	{QUOTA_PERCENTAGE: 0},
	{whichHarvester: 0},
	{RandomAngle: 0},
	{RandomDistance: 0},
	{RandomDuration: 0}
];

self.InstanceType = {
	_3DCamera: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Terrain: class extends self.I3DShapeInstance {},
	WaterTexture: class extends self.ITiledBackgroundInstance {},
	TerrainTopTex: class extends self.ITiledBackgroundInstance {},
	Berry: class extends self.I3DShapeInstance {},
	TerrainSideTex: class extends self.ITiledBackgroundInstance {},
	Harvester1: class extends self.I3DShapeInstance {},
	HarvesterSaw: class extends self.ITiledBackgroundInstance {},
	Harvester2: class extends self.I3DShapeInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	TextTutorial: class extends self.ISpriteFontInstance {},
	TextGameOver: class extends self.ISpriteFontInstance {},
	TextVictory: class extends self.ISpriteFontInstance {},
	Obstacle: class extends self.I3DShapeInstance {},
	TexStoneLargeSide_0: class extends self.ISpriteInstance {},
	TexStoneSmallSide: class extends self.ISpriteInstance {},
	TexStoneLargeFront: class extends self.ISpriteInstance {},
	TexStoneSmallFront: class extends self.ISpriteInstance {},
	TexStoneLargeSide_1: class extends self.ISpriteInstance {},
	TexLogFront: class extends self.ISpriteInstance {},
	TexLogSide_0: class extends self.ISpriteInstance {},
	TexLogSide_1: class extends self.ISpriteInstance {},
	Mushroom: class extends self.I3DShapeInstance {},
	TexMushroomSide: class extends self.ISpriteInstance {},
	TexMushroomFront: class extends self.ISpriteInstance {},
	ProgressBar: class extends self.ITiledBackgroundInstance {},
	TextProgress: class extends self.ISpriteFontInstance {},
	ProgressBarBackground: class extends self.ITiledBackgroundInstance {},
	TextVictoryFinal: class extends self.ISpriteFontInstance {},
	TexTreeSide: class extends self.ISpriteInstance {},
	TreeLeaves_0: class extends self.I3DShapeInstance {},
	TreeLeaves_1: class extends self.I3DShapeInstance {},
	TreeLeaves_2: class extends self.I3DShapeInstance {},
	TerrainFake: class extends self.I3DShapeInstance {},
	ShipPart0: class extends self.I3DShapeInstance {},
	ShipPart1: class extends self.I3DShapeInstance {},
	ShipPart2: class extends self.I3DShapeInstance {},
	ShipPart3: class extends self.I3DShapeInstance {},
	ShipPart4: class extends self.I3DShapeInstance {},
	ShipPart5: class extends self.I3DShapeInstance {},
	TexStoneHugeSides: class extends self.ISpriteInstance {},
	TexStoneHugeFront: class extends self.ISpriteInstance {},
	Particles: class extends self.I3DShapeInstance {},
	BerryShort: class extends self.I3DShapeInstance {},
	TexBerryTall_02: class extends self.ITiledBackgroundInstance {},
	TexBerryTall_12: class extends self.ITiledBackgroundInstance {},
	TexBerryTall_22: class extends self.ITiledBackgroundInstance {},
	TexBerryTall_32: class extends self.ITiledBackgroundInstance {},
	TexBerryTall_01: class extends self.ITiledBackgroundInstance {},
	TexBerryTall_11: class extends self.ITiledBackgroundInstance {},
	TexBerryTall_21: class extends self.ITiledBackgroundInstance {},
	TexBerryTall_31: class extends self.ITiledBackgroundInstance {},
	TexBerryTall_00: class extends self.ITiledBackgroundInstance {},
	TexBerryTall_10: class extends self.ITiledBackgroundInstance {},
	TexBerryTall_20: class extends self.ITiledBackgroundInstance {},
	TexBerryTall_30: class extends self.ITiledBackgroundInstance {},
	TexBerryShort_02: class extends self.ITiledBackgroundInstance {},
	TexBerryShort_12: class extends self.ITiledBackgroundInstance {},
	TexBerryShort_22: class extends self.ITiledBackgroundInstance {},
	TexBerryShort_32: class extends self.ITiledBackgroundInstance {},
	TexBerryShort_01: class extends self.ITiledBackgroundInstance {},
	TexBerryShort_11: class extends self.ITiledBackgroundInstance {},
	TexBerryShort_21: class extends self.ITiledBackgroundInstance {},
	TexBerryShort_31: class extends self.ITiledBackgroundInstance {},
	TexBerryShort_00: class extends self.ITiledBackgroundInstance {},
	TexBerryShort_10: class extends self.ITiledBackgroundInstance {},
	TexBerryShort_20: class extends self.ITiledBackgroundInstance {},
	TexBerryShort_30: class extends self.ITiledBackgroundInstance {},
	WeeGooSDK: class extends self.IInstance {}
}