const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Tilemap,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Behaviors.Physics,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.WGSDK.Acts.InitReward
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sprite2: 0},
	{Tilemap: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Music: 0},
	{Sprite9: 0},
	{Sound: 0},
	{Sprite11: 0},
	{Touch: 0},
	{Audio: 0},
	{Sprite8: 0},
	{Basket: 0},
	{Sprite12: 0},
	{Sprite10: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Physics: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Win: 0},
	{Fade: 0},
	{Sprite18: 0},
	{Sine: 0},
	{NotDestroy: 0},
	{Destroy: 0},
	{Ball2: 0},
	{Ball: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Text: 0},
	{Sprite26: 0},
	{Sprite38: 0},
	{Sprite37: 0},
	{Browser: 0},
	{WeeGooSDK: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Music: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sound: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Basket: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Win: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	NotDestroy: class extends self.ISpriteInstance {},
	Destroy: class extends self.ISpriteInstance {},
	Ball2: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	WeeGooSDK: class extends C3.Plugins.WGSDK.Instance {}
}