const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Behaviors.jumpthru,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Behaviors.Tween,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Behaviors.MoveTo.Cnds.OnHitSolid,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.WGSDK.Cnds.RewardGranted
	];
};
self.C3_JsPropNameTable = [
	{beh_solid: 0},
	{map_ground: 0},
	{beh_platform: 0},
	{beh_scroll_to: 0},
	{beh_move_to: 0},
	{spr_player_collision: 0},
	{beh_pin: 0},
	{spr_player_graphic: 0},
	{plu_keyboard: 0},
	{Kapı: 0},
	{Rotate: 0},
	{carklar: 0},
	{Sine: 0},
	{gmes: 0},
	{yumurtahud: 0},
	{surungen: 0},
	{Bullet: 0},
	{Yeşiltopatartopu: 0},
	{Startclick: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{pause: 0},
	{Audio: 0},
	{sol: 0},
	{sag: 0},
	{zipla: 0},
	{PlatformInfo: 0},
	{lvlfinish: 0},
	{Sine2: 0},
	{sinek: 0},
	{Jumpthru: 0},
	{tahta: 0},
	{Pin: 0},
	{donensinek: 0},
	{Soltopatar: 0},
	{Sprite5: 0},
	{sagtopatar: 0},
	{Mavitopatartopu: 0},
	{replay: 0},
	{TiledBackground2: 0},
	{Sprite: 0},
	{replaybut: 0},
	{nextbut: 0},
	{Homebut: 0},
	{snopbut: 0},
	{caointext: 0},
	{Sprite2: 0},
	{Array: 0},
	{Tween: 0},
	{Sprite9: 0},
	{Sprite11: 0},
	{Text: 0},
	{tap: 0},
	{leveltext: 0},
	{adsbut: 0},
	{WeeGooSDK: 0},
	{squarekingsummerlevel: 0},
	{squarekingsummerscore: 0},
	{sound: 0},
	{music: 0},
	{P1Skin: 0},
	{P1SkinSelect: 0},
	{dur: 0},
	{var_distance: 0},
	{var_direction: 0}
];

self.InstanceType = {
	map_ground: class extends self.ITilemapInstance {},
	spr_player_collision: class extends self.ISpriteInstance {},
	spr_player_graphic: class extends self.ISpriteInstance {},
	plu_keyboard: class extends self.IInstance {},
	Kapı: class extends self.ISpriteInstance {},
	carklar: class extends self.ISpriteInstance {},
	gmes: class extends self.ISpriteInstance {},
	yumurtahud: class extends self.ISpriteInstance {},
	surungen: class extends self.ISpriteInstance {},
	Yeşiltopatartopu: class extends self.ISpriteInstance {},
	Startclick: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	pause: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	sol: class extends self.ISpriteInstance {},
	sag: class extends self.ISpriteInstance {},
	zipla: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	lvlfinish: class extends self.ISpriteInstance {},
	sinek: class extends self.ISpriteInstance {},
	tahta: class extends self.ISpriteInstance {},
	donensinek: class extends self.ISpriteInstance {},
	Soltopatar: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	sagtopatar: class extends self.ISpriteInstance {},
	Mavitopatartopu: class extends self.ISpriteInstance {},
	replay: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	replaybut: class extends self.ISpriteInstance {},
	nextbut: class extends self.ISpriteInstance {},
	Homebut: class extends self.ISpriteInstance {},
	snopbut: class extends self.ISpriteInstance {},
	caointext: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	tap: class extends self.ISpriteInstance {},
	leveltext: class extends self.ITextInstance {},
	adsbut: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {}
}