const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.PlatformInfo,
		C3.Plugins.WGSDK,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Acts.SetSize,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.DragnDrop.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Preload
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Touch: 0},
	{Mouse: 0},
	{Browser: 0},
	{PlatformInfo: 0},
	{WeeGooSDK: 0},
	{Sine: 0},
	{Play_Button: 0},
	{back_button: 0},
	{Home_Button: 0},
	{settingsButton: 0},
	{Tween: 0},
	{SoundBoard: 0},
	{CrossButton: 0},
	{musicButton: 0},
	{SoundButton: 0},
	{CrossButton2: 0},
	{voiceclick: 0},
	{movetoX: 0},
	{movetoY: 0},
	{Character: 0},
	{load_obj: 0},
	{loading: 0},
	{LoadingFont: 0},
	{menu_broccoli: 0},
	{menu_cabbage: 0},
	{menu_onion: 0},
	{tree: 0},
	{MenuBG: 0},
	{Learning_Icon: 0},
	{GamePlay_icon: 0},
	{MenuObject7: 0},
	{Game_TypeBg: 0},
	{ExampleCH: 0},
	{Example1Object: 0},
	{shv: 0},
	{GamePlay_BG: 0},
	{index: 0},
	{pieceIndex: 0},
	{placeHolder: 0},
	{txtWin: 0},
	{Effect: 0},
	{Particles: 0},
	{Rotate: 0},
	{Confetti: 0},
	{Bar: 0},
	{WinEffect: 0},
	{GamePlay_Board: 0},
	{distance: 0},
	{Frame: 0},
	{active: 0},
	{placeHolderIndex: 0},
	{scaleto: 0},
	{DragDrop: 0},
	{piece: 0},
	{Sprite: 0},
	{Broccoli: 0},
	{aubergin: 0},
	{cabbage: 0},
	{corn: 0},
	{garlic: 0},
	{tomato: 0},
	{radish: 0},
	{redPaper: 0},
	{pumkin: 0},
	{potato: 0},
	{onion: 0},
	{Cucumber: 0},
	{settings: 0},
	{Sine2: 0},
	{toucheffect: 0},
	{Gindex: 0},
	{GselectedIndex: 0},
	{GmagnetDistance: 0},
	{Gdistance: 0},
	{GlevelImage: 0},
	{GremainingPieces: 0},
	{Gwin: 0},
	{iPiece: 0},
	{iPlace: 0},
	{GimageName: 0},
	{sound: 0},
	{Music: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	WeeGooSDK: class extends self.IInstance {},
	Play_Button: class extends self.ISpriteInstance {},
	back_button: class extends self.ISpriteInstance {},
	Home_Button: class extends self.ISpriteInstance {},
	settingsButton: class extends self.ISpriteInstance {},
	SoundBoard: class extends self.ISpriteInstance {},
	CrossButton: class extends self.ISpriteInstance {},
	musicButton: class extends self.ISpriteInstance {},
	SoundButton: class extends self.ISpriteInstance {},
	CrossButton2: class extends self.ISpriteInstance {},
	voiceclick: class extends self.ISpriteInstance {},
	Character: class extends self.ISpriteInstance {},
	load_obj: class extends self.ISpriteInstance {},
	loading: class extends self.ISpriteInstance {},
	LoadingFont: class extends self.ITextInstance {},
	menu_broccoli: class extends self.ISpriteInstance {},
	menu_cabbage: class extends self.ISpriteInstance {},
	menu_onion: class extends self.ISpriteInstance {},
	tree: class extends self.ISpriteInstance {},
	MenuBG: class extends self.ISpriteInstance {},
	Learning_Icon: class extends self.ISpriteInstance {},
	GamePlay_icon: class extends self.ISpriteInstance {},
	MenuObject7: class extends self.ISpriteInstance {},
	Game_TypeBg: class extends self.ISpriteInstance {},
	ExampleCH: class extends self.ISpriteInstance {},
	Example1Object: class extends self.ISpriteInstance {},
	shv: class extends self.ISpriteInstance {},
	GamePlay_BG: class extends self.ISpriteInstance {},
	placeHolder: class extends self.ISpriteInstance {},
	txtWin: class extends self.ISpriteInstance {},
	Effect: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Confetti: class extends self.ISpriteInstance {},
	Bar: class extends self.ISpriteInstance {},
	WinEffect: class extends self.ISpriteInstance {},
	GamePlay_Board: class extends self.ISpriteInstance {},
	Frame: class extends self.ISpriteInstance {},
	piece: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Broccoli: class extends self.ITextInstance {},
	aubergin: class extends self.ITextInstance {},
	cabbage: class extends self.ITextInstance {},
	corn: class extends self.ITextInstance {},
	garlic: class extends self.ITextInstance {},
	tomato: class extends self.ITextInstance {},
	radish: class extends self.ITextInstance {},
	redPaper: class extends self.ITextInstance {},
	pumkin: class extends self.ITextInstance {},
	potato: class extends self.ITextInstance {},
	onion: class extends self.ITextInstance {},
	Cucumber: class extends self.ITextInstance {},
	settings: class extends self.ISpriteInstance {},
	toucheffect: class extends self.ISpriteInstance {}
}