const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Fade,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Behaviors.jumpthru,
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Acts.RotateCounterclockwise,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Exps.MaxSpeed,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsRewardedPlaying,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsFullscreenClose,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedClose,
		C3.Behaviors.Tween.Cnds.IsAnyPaused,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SetLayoutEffectEnabled,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Text.Acts.SetPos,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsShare,
		C3.Plugins.Eponesh_GameScore.Cnds.IsSocialsSupportsShare,
		C3.Plugins.Eponesh_GameScore.Cnds.PlatformType,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowSticky,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Cnds.PreloadsComplete,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsPreloaderPlaying,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsPreloaderClose
	];
};
self.C3_JsPropNameTable = [
	{bg: 0},
	{bg1: 0},
	{objects: 0},
	{blank_fon_castle: 0},
	{ugol: 0},
	{Твердый: 0},
	{solid_block: 0},
	{on_cat: 0},
	{state: 0},
	{teleportation: 0},
	{wiii: 0},
	{jump: 0},
	{wing: 0},
	{damage: 0},
	{Платформер: 0},
	{СледитьЗа: 0},
	{Твинанимация: 0},
	{bc_base: 0},
	{Прикрепить: 0},
	{Синусоид: 0},
	{black_cat: 0},
	{bg2: 0},
	{bg3: 0},
	{bg4: 0},
	{Клавиатура: 0},
	{Тач: 0},
	{ОбУстройстве: 0},
	{ЛокальноеХранилище: 0},
	{Угасание: 0},
	{falling_track: 0},
	{jump_track: 0},
	{Пуля: 0},
	{paws_dim: 0},
	{bc_shadow: 0},
	{mobil_arrows: 0},
	{id: 0},
	{mobil_button: 0},
	{mobil_arrows2: 0},
	{control_board: 0},
	{black_cat_control: 0},
	{objects_dolid: 0},
	{life: 0},
	{enemy_sprite: 0},
	{lifebar: 0},
	{cat_icon: 0},
	{hearts: 0},
	{sprite2: 0},
	{УничтожатьЗаПределамиМакета: 0},
	{coin: 0},
	{money_icon_gui: 0},
	{coin_text: 0},
	{kittens_icon: 0},
	{kitten_text: 0},
	{resp_sprite: 0},
	{Аудио: 0},
	{iskri: 0},
	{feather: 0},
	{enemy: 0},
	{move_to: 0},
	{timer_to_jump: 0},
	{plant_side: 0},
	{enemy_base: 0},
	{side: 0},
	{enemy_walk_zone: 0},
	{claw_effect: 0},
	{fog: 0},
	{prison_cell: 0},
	{cat_in_prison: 0},
	{control_text: 0},
	{control_text2: 0},
	{lvl_coins_need: 0},
	{lvl_cats_need: 0},
	{coins_now: 0},
	{save_cats_now: 0},
	{check_point_x: 0},
	{check_point_y: 0},
	{water_resp_x: 0},
	{water_resp_y: 0},
	{star_left: 0},
	{star_right: 0},
	{lvl_stars: 0},
	{var: 0},
	{complete_icon: 0},
	{cat_right_dot: 0},
	{cat_left_dot: 0},
	{active: 0},
	{cat_attack_dot: 0},
	{is_active: 0},
	{check_point: 0},
	{teleport_efx3: 0},
	{cat_hearts: 0},
	{waterfall: 0},
	{water: 0},
	{vsplesk: 0},
	{water_cp: 0},
	{water_zone: 0},
	{СквознаяПлатформа: 0},
	{platforma: 0},
	{fog_bg: 0},
	{bc_box_puller: 0},
	{box: 0},
	{fire: 0},
	{end_lvl_activator: 0},
	{lvl_complete_elements: 0},
	{dark_fon: 0},
	{comple_text: 0},
	{star_level_complete: 0},
	{skill_up_elem_gui2: 0},
	{lvlup_effect_in_game: 0},
	{darkening: 0},
	{lvl_map: 0},
	{firefly: 0},
	{peaks: 0},
	{ground_fon_castle: 0},
	{bg_fon_castle: 0},
	{ground_fon_castle2: 0},
	{cell_fon_castle3: 0},
	{torch: 0},
	{torch_light: 0},
	{objects2: 0},
	{cell_fon_castle4: 0},
	{spikes_fon_castle: 0},
	{fireball: 0},
	{fireball_effect: 0},
	{shining: 0},
	{ground_fon_lvl5: 0},
	{bg4_1: 0},
	{bg4_2: 0},
	{bg4_3: 0},
	{invisible_obj: 0},
	{ground_fon_lvl6: 0},
	{crow: 0},
	{ground_fon_castle3: 0},
	{tf1: 0},
	{sprite3: 0},
	{tf2: 0},
	{bg_lvl_7_8: 0},
	{bg4_5: 0},
	{bg4_6: 0},
	{ground_fon_lvl7: 0},
	{blizzard: 0},
	{solid_block2: 0},
	{tf3: 0},
	{snow_dim: 0},
	{bg_lvl_9_10: 0},
	{tf4: 0},
	{far_clouds_fon: 0},
	{mid_mountains: 0},
	{bg_9_10: 0},
	{bg9_10_1: 0},
	{tf5: 0},
	{water_fon: 0},
	{water_fon2: 0},
	{button_mobil2: 0},
	{lvls_bg: 0},
	{black_cat_lvls: 0},
	{cat_in_prison2: 0},
	{level_text: 0},
	{text_number: 0},
	{stars: 0},
	{locks: 0},
	{buttons_lvl: 0},
	{stars_array: 0},
	{fps_text: 0},
	{cover: 0},
	{logo_title: 0},
	{flag_lang: 0},
	{Синусоида: 0},
	{play_b_title: 0},
	{text_preloader: 0},
	{lvl: 0},
	{Угасание2: 0},
	{dark_cover: 0},
	{preloader_icon: 0},
	{sound: 0},
	{sound_button: 0},
	{status: 0},
	{restart_button: 0},
	{home_button: 0},
	{pause_button: 0},
	{options_button: 0},
	{clap_clap_cat: 0},
	{more_games: 0},
	{Браузер: 0},
	{cong_desc_text: 0},
	{arrow_next_lvl: 0},
	{arrow_prew_lvl: 0},
	{cong_level_text: 0},
	{GamePush: 0},
	{social: 0},
	{lvl_now: 0},
	{lang: 0},
	{adtimer: 0},
	{flag: 0},
	{open_lvl: 0},
	{enter_lvl: 0},
	{lvl_table: 0}
];

self.InstanceType = {
	bg: class extends self.ISpriteInstance {},
	bg1: class extends self.ITiledBackgroundInstance {},
	objects: class extends self.ISpriteInstance {},
	blank_fon_castle: class extends self.ITiledBackgroundInstance {},
	solid_block: class extends self.ITiledBackgroundInstance {},
	bc_base: class extends self.ISpriteInstance {},
	black_cat: class extends self.ISpriteInstance {},
	bg2: class extends self.ITiledBackgroundInstance {},
	bg3: class extends self.ITiledBackgroundInstance {},
	bg4: class extends self.ITiledBackgroundInstance {},
	Клавиатура: class extends self.IInstance {},
	Тач: class extends self.IInstance {},
	ОбУстройстве: class extends self.IInstance {},
	ЛокальноеХранилище: class extends self.IInstance {},
	falling_track: class extends self.ISpriteInstance {},
	jump_track: class extends self.ISpriteInstance {},
	paws_dim: class extends self.ISpriteInstance {},
	bc_shadow: class extends self.ISpriteInstance {},
	mobil_arrows: class extends self.ISpriteInstance {},
	mobil_button: class extends self.ISpriteInstance {},
	mobil_arrows2: class extends self.ISpriteInstance {},
	control_board: class extends self.ISpriteInstance {},
	black_cat_control: class extends self.ISpriteInstance {},
	objects_dolid: class extends self.ISpriteInstance {},
	enemy_sprite: class extends self.ISpriteInstance {},
	lifebar: class extends self.ISpriteInstance {},
	cat_icon: class extends self.ISpriteInstance {},
	hearts: class extends self.ISpriteInstance {},
	sprite2: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	money_icon_gui: class extends self.ISpriteInstance {},
	coin_text: class extends self.ITextInstance {},
	kittens_icon: class extends self.ISpriteInstance {},
	kitten_text: class extends self.ITextInstance {},
	resp_sprite: class extends self.ISpriteInstance {},
	Аудио: class extends self.IInstance {},
	iskri: class extends self.ISpriteInstance {},
	wing: class extends self.ISpriteInstance {},
	feather: class extends self.ISpriteInstance {},
	enemy_base: class extends self.ISpriteInstance {},
	enemy_walk_zone: class extends self.ISpriteInstance {},
	claw_effect: class extends self.ISpriteInstance {},
	fog: class extends self.ISpriteInstance {},
	prison_cell: class extends self.ISpriteInstance {},
	cat_in_prison: class extends self.ISpriteInstance {},
	control_text: class extends self.ITextInstance {},
	control_text2: class extends self.ITextInstance {},
	var: class extends self.ISpriteInstance {},
	complete_icon: class extends self.ISpriteInstance {},
	cat_right_dot: class extends self.ISpriteInstance {},
	cat_left_dot: class extends self.ISpriteInstance {},
	cat_attack_dot: class extends self.ISpriteInstance {},
	check_point: class extends self.ISpriteInstance {},
	teleport_efx3: class extends self.ISpriteInstance {},
	cat_hearts: class extends self.ISpriteInstance {},
	waterfall: class extends self.ISpriteInstance {},
	water: class extends self.ISpriteInstance {},
	vsplesk: class extends self.ISpriteInstance {},
	water_cp: class extends self.ISpriteInstance {},
	water_zone: class extends self.ISpriteInstance {},
	platforma: class extends self.ISpriteInstance {},
	fog_bg: class extends self.ISpriteInstance {},
	bc_box_puller: class extends self.ISpriteInstance {},
	box: class extends self.ISpriteInstance {},
	fire: class extends self.ISpriteInstance {},
	end_lvl_activator: class extends self.ISpriteInstance {},
	lvl_complete_elements: class extends self.ISpriteInstance {},
	dark_fon: class extends self.ITiledBackgroundInstance {},
	comple_text: class extends self.ITextInstance {},
	star_level_complete: class extends self.ISpriteInstance {},
	skill_up_elem_gui2: class extends self.ISpriteInstance {},
	lvlup_effect_in_game: class extends self.ISpriteInstance {},
	darkening: class extends self.ITiledBackgroundInstance {},
	lvl_map: class extends self.ISpriteInstance {},
	firefly: class extends self.ISpriteInstance {},
	peaks: class extends self.ISpriteInstance {},
	ground_fon_castle: class extends self.ITiledBackgroundInstance {},
	bg_fon_castle: class extends self.ITiledBackgroundInstance {},
	ground_fon_castle2: class extends self.ITiledBackgroundInstance {},
	cell_fon_castle3: class extends self.ITiledBackgroundInstance {},
	torch: class extends self.ISpriteInstance {},
	torch_light: class extends self.ISpriteInstance {},
	objects2: class extends self.ISpriteInstance {},
	cell_fon_castle4: class extends self.ITiledBackgroundInstance {},
	spikes_fon_castle: class extends self.ITiledBackgroundInstance {},
	fireball: class extends self.ISpriteInstance {},
	fireball_effect: class extends self.ISpriteInstance {},
	shining: class extends self.ISpriteInstance {},
	ground_fon_lvl5: class extends self.ITiledBackgroundInstance {},
	bg4_1: class extends self.ITiledBackgroundInstance {},
	bg4_2: class extends self.ITiledBackgroundInstance {},
	bg4_3: class extends self.ITiledBackgroundInstance {},
	invisible_obj: class extends self.ISpriteInstance {},
	ground_fon_lvl6: class extends self.ITiledBackgroundInstance {},
	crow: class extends self.ISpriteInstance {},
	ground_fon_castle3: class extends self.ITiledBackgroundInstance {},
	tf1: class extends self.ITiledBackgroundInstance {},
	sprite3: class extends self.ISpriteInstance {},
	tf2: class extends self.ITiledBackgroundInstance {},
	bg_lvl_7_8: class extends self.ISpriteInstance {},
	bg4_5: class extends self.ITiledBackgroundInstance {},
	bg4_6: class extends self.ITiledBackgroundInstance {},
	ground_fon_lvl7: class extends self.ITiledBackgroundInstance {},
	blizzard: class extends self.ISpriteInstance {},
	solid_block2: class extends self.ITiledBackgroundInstance {},
	tf3: class extends self.ITiledBackgroundInstance {},
	snow_dim: class extends self.ISpriteInstance {},
	bg_lvl_9_10: class extends self.ISpriteInstance {},
	tf4: class extends self.ITiledBackgroundInstance {},
	far_clouds_fon: class extends self.ITiledBackgroundInstance {},
	mid_mountains: class extends self.ITiledBackgroundInstance {},
	bg_9_10: class extends self.ITiledBackgroundInstance {},
	bg9_10_1: class extends self.ITiledBackgroundInstance {},
	tf5: class extends self.ITiledBackgroundInstance {},
	water_fon: class extends self.ITiledBackgroundInstance {},
	water_fon2: class extends self.ITiledBackgroundInstance {},
	button_mobil2: class extends self.ISpriteInstance {},
	lvls_bg: class extends self.ISpriteInstance {},
	black_cat_lvls: class extends self.ISpriteInstance {},
	cat_in_prison2: class extends self.ISpriteInstance {},
	level_text: class extends self.ITextInstance {},
	text_number: class extends self.ITextInstance {},
	stars: class extends self.ISpriteInstance {},
	locks: class extends self.ISpriteInstance {},
	buttons_lvl: class extends self.ISpriteInstance {},
	stars_array: class extends self.IArrayInstance {},
	fps_text: class extends self.ITextInstance {},
	cover: class extends self.ISpriteInstance {},
	logo_title: class extends self.ISpriteInstance {},
	flag_lang: class extends self.ISpriteInstance {},
	play_b_title: class extends self.ISpriteInstance {},
	text_preloader: class extends self.ITextInstance {},
	dark_cover: class extends self.ISpriteInstance {},
	preloader_icon: class extends self.ISpriteInstance {},
	sound_button: class extends self.ISpriteInstance {},
	restart_button: class extends self.ISpriteInstance {},
	home_button: class extends self.ISpriteInstance {},
	pause_button: class extends self.ISpriteInstance {},
	options_button: class extends self.ISpriteInstance {},
	clap_clap_cat: class extends self.ISpriteInstance {},
	more_games: class extends self.ISpriteInstance {},
	Браузер: class extends self.IInstance {},
	cong_desc_text: class extends self.ITextInstance {},
	arrow_next_lvl: class extends self.ISpriteInstance {},
	arrow_prew_lvl: class extends self.ISpriteInstance {},
	cong_level_text: class extends self.ITextInstance {},
	GamePush: class extends self.IInstance {},
	social: class extends self.ISpriteInstance {}
}