const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.shadowcaster,
		C3.Behaviors.Pin,
		C3.Behaviors.Anchor,
		C3.Behaviors.Fade,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Behaviors.scrollto,
		C3.Behaviors.destroy,
		C3.Behaviors.Rotate,
		C3.Behaviors.solid,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Flash,
		C3.Plugins.TiledBg,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Spritefont2,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Function,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Plugins.Facebook,
		C3.Plugins.video,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Physics.Acts.RemoveJoints,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Behaviors.Physics.Acts.CreateLimitedRevoluteJoint,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Physics.Acts.ApplyTorque,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Physics.Acts.ApplyTorqueToAngle,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Behaviors.Pin.Cnds.IsPinned,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Text.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.System.Exps.anglediff,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Acts.SetLayoutEffectParam,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.System.Exps.layoutscale,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Physics.Acts.ApplyForceToward,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Behaviors.Physics.Acts.SetElasticity,
		C3.Plugins.System.Acts.SetLayoutEffectEnabled,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.System.Cnds.CompareTime,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Arr.Acts.Clear,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Function.Exps.Param,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.Particles.Cnds.IsSpraying,
		C3.Plugins.Particles.Acts.SetSpeedRandomiser,
		C3.Plugins.video.Acts.SetSource,
		C3.Plugins.video.Acts.SetLooping,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Acts.RotateTowardAngle,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.ScriptsInEvents.Sound_Event5_Act1,
		C3.ScriptsInEvents.Sound_Event6_Act1,
		C3.Plugins.System.Cnds.IsSuspended,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.video.Acts.Play
	];
};
self.C3_JsPropNameTable = [
	{Arrowpush: 0},
	{Physics: 0},
	{bacak_sag: 0},
	{lower_angle: 0},
	{upper_angle: 0},
	{rotate_down: 0},
	{rotate_up: 0},
	{ShadowCaster: 0},
	{bacak_sag2: 0},
	{bacak_sag2bg: 0},
	{bacak_sagbg: 0},
	{bacak_sol: 0},
	{bacak_sol2: 0},
	{bacak_sol2bg: 0},
	{bacak_solbg: 0},
	{baldir_sag: 0},
	{baldir_sag2: 0},
	{baldir_sag2bg: 0},
	{baldir_sagbg: 0},
	{baldir_sol: 0},
	{baldir_sol2: 0},
	{baldir_sol2bg: 0},
	{baldir_solbg: 0},
	{bas_sag: 0},
	{Pin: 0},
	{bas_sag_timewarp: 0},
	{bas_sagbg: 0},
	{bas_sol: 0},
	{bas_sol_timewarp: 0},
	{bas_solbg: 0},
	{Anchor: 0},
	{bg: 0},
	{Fade: 0},
	{bgfade: 0},
	{blue_healt_bar: 0},
	{blue_star_panel: 0},
	{Bullet: 0},
	{bluebullet: 0},
	{Sine: 0},
	{bluedestek: 0},
	{bluedizkirma: 0},
	{bluekan: 0},
	{bluelazer: 0},
	{Tween: 0},
	{bluelight: 0},
	{bluesu: 0},
	{ORANGE_WINS: 0},
	{bluhealtzemin: 0},
	{bottle: 0},
	{bulleteffectblue: 0},
	{ScrollTo: 0},
	{camera: 0},
	{DestroyOutsideLayout: 0},
	{ciuuw: 0},
	{darkmode: 0},
	{duvar: 0},
	{duvar1: 0},
	{duvar2: 0},
	{duvar3: 0},
	{estimatedwaitingtime_15s: 0},
	{FIGHT_box: 0},
	{FLAWLESSVICTORY_blue: 0},
	{FLAWLESSVICTORY_orange: 0},
	{gameoverbg: 0},
	{gameoverbg2: 0},
	{govde_sag: 0},
	{govde_sagbg: 0},
	{govde_sol: 0},
	{govde_solbg: 0},
	{gunblue: 0},
	{gunorange: 0},
	{hayaletduvar: 0},
	{headshoot: 0},
	{Rotate: 0},
	{kazanan_light: 0},
	{kimkazandiblue: 0},
	{kimkazandiorange: 0},
	{kol_sag: 0},
	{kol_sag2: 0},
	{kol_sag2_box: 0},
	{kol_sag2bg: 0},
	{kol_sag3: 0},
	{kol_sag3bg: 0},
	{kol_sag4: 0},
	{kol_sag4bg: 0},
	{kol_sagbg: 0},
	{kol_sol: 0},
	{kol_sol2: 0},
	{kol_sol2bg: 0},
	{kol_sol3: 0},
	{kol_sol3bg: 0},
	{kol_sol4: 0},
	{kol_sol4bg: 0},
	{kol_solbg: 0},
	{lamb_timewarp: 0},
	{ligtlamp: 0},
	{ligtlamp2: 0},
	{ligtline1: 0},
	{ligtline2: 0},
	{ligtline3: 0},
	{ligtline4: 0},
	{ligtline5: 0},
	{ligtline6: 0},
	{ligtline7: 0},
	{ligtline8: 0},
	{mainmenu: 0},
	{Solid: 0},
	{masa: 0},
	{masafade: 0},
	{moregames: 0},
	{orange_healt_bar: 0},
	{orange_star_panel: 0},
	{orangebullet: 0},
	{orangeeffectblue: 0},
	{orangehealtzemin: 0},
	{orangekan: 0},
	{orangelazer: 0},
	{orangelight: 0},
	{orangesu: 0},
	{BLUE_WINS: 0},
	{poverbarturuncu: 0},
	{powerbarmavi: 0},
	{ready: 0},
	{replay: 0},
	{searchingforopponent: 0},
	{Sprite: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{taban: 0},
	{Untitled1_0000_Layer5copy: 0},
	{Untitled1_0001_Layer: 0},
	{Untitled1_0003_Layer: 0},
	{Untitled1_0011_1p: 0},
	{Untitled1_0012_2p: 0},
	{Untitled1_0013_w: 0},
	{Untitled1_0014_Layer: 0},
	{Untitled1_0016_twoplayergamesorgcopy: 0},
	{Untitled1_0018_Layer: 0},
	{Untitled1_0020_Layer8copy: 0},
	{Untitled1_0021_Layer: 0},
	{Untitled1_0023_Untitled1_0002_Layer: 0},
	{Untitled1_0028_DUELL: 0},
	{Untitled1_0030_DRUNKEN: 0},
	{winman: 0},
	{wpush: 0},
	{ypcollider: 0},
	{Untitled1_0028_DUELL2: 0},
	{Untitled1_0028_DUELL3: 0},
	{Untitled1_0028_DUELL4: 0},
	{Untitled1_0013_w2: 0},
	{Untitled1_0014_Layer2: 0},
	{Untitled1_0028_DUELL5: 0},
	{Untitled1_0028_DUELL6: 0},
	{Untitled1_0028_DUELL7: 0},
	{angled_table: 0},
	{arrow_push_table: 0},
	{ayak_sag2_table: 0},
	{ayak_sag_bg2_table: 0},
	{ayak_sag_bg_table: 0},
	{ayak_sag_table: 0},
	{ayak_sol2_table: 0},
	{ayak_sol_bg2_table: 0},
	{ayak_sol_bg_table: 0},
	{ayak_sol_table: 0},
	{bacak_sag2_table: 0},
	{bacak_sag_bg2_table: 0},
	{bacak_sag_bg_table: 0},
	{bacak_sag_table: 0},
	{bacak_sol2_table: 0},
	{bacak_sol_bg2_table: 0},
	{bacak_sol_bg_table: 0},
	{bacak_sol_table: 0},
	{baldir_sag2_table: 0},
	{baldir_sag_bg2_table: 0},
	{baldir_sag_bg_table: 0},
	{baldir_sag_table: 0},
	{baldir_sol2_table: 0},
	{baldir_sol_bg2_table: 0},
	{baldir_sol_bg_table: 0},
	{baldir_sol_table: 0},
	{ball3deffect_table: 0},
	{bas_sag_bg_table: 0},
	{bas_sag_table: 0},
	{bas_sol_bg_table: 0},
	{bas_sol_table: 0},
	{bg_table: 0},
	{bgg_table: 0},
	{bileksag2_table: 0},
	{bileksag_bg2_table: 0},
	{bileksag_bg_table: 0},
	{bileksag_table: 0},
	{bileksol2_table: 0},
	{bileksol_bg2_table: 0},
	{bileksol_bg_table: 0},
	{bileksol_table: 0},
	{blue_star_panel_table: 0},
	{boommm_table: 0},
	{bow_ball_table: 0},
	{button_1p_table: 0},
	{button_2p_table: 0},
	{button_arrowpush_table: 0},
	{button_game_home_table: 0},
	{button_home_table: 0},
	{button_playmoregames_table: 0},
	{button_replay_table: 0},
	{button_win_moregames_table: 0},
	{button_wpush_table: 0},
	{MoveTo: 0},
	{camera_table: 0},
	{Flash: 0},
	{colleft_table: 0},
	{collider_table: 0},
	{deneme3_table: 0},
	{govde_sag_bg_table: 0},
	{govde_sag_table: 0},
	{govde_sol_bg_table: 0},
	{govde_sol_table: 0},
	{kablo_table: 0},
	{kol_sag2_table: 0},
	{kol_sag_bg2_table: 0},
	{kol_sag_bg_table: 0},
	{kol_sag_table: 0},
	{kol_sol2_table: 0},
	{kol_sol_bg2_table: 0},
	{kol_sol_bg_table: 0},
	{kol_sol_table: 0},
	{ligtlamp2_table: 0},
	{ligtlamp_table: 0},
	{ligtline3_table: 0},
	{lower_angle_Set_ayak_sag_table: 0},
	{lower_angle_Set_ayak_sol_table: 0},
	{lower_angle_Set_bacak_sag_table: 0},
	{lower_angle_Set_bacak_sol_table: 0},
	{lower_angle_Set_baldir_sag_table: 0},
	{lower_angle_Set_baldir_sol_table: 0},
	{manz_table: 0},
	{masaayaksag_table: 0},
	{masaayaksol_table: 0},
	{masagolge_table: 0},
	{mavigolge_table: 0},
	{orange_star_panel_table: 0},
	{orangegolge_table: 0},
	{portal_table: 0},
	{scores_text_table: 0},
	{Sprite11_table: 0},
	{Sprite2_table: 0},
	{Sprite3_table: 0},
	{Sprite5_table: 0},
	{Sprite6_table: 0},
	{Sprite7_table: 0},
	{Sprite8_table: 0},
	{table_table: 0},
	{tennisball_table: 0},
	{tennisball_table2: 0},
	{top_table: 0},
	{Untitled2_0000_go_table_table: 0},
	{Untitled2_0007_Group_table: 0},
	{Untitled2_0007_PLAYCOOLGAMES_table: 0},
	{upper_angle_Set_ayak_sag_table: 0},
	{upper_angle_Set_ayak_sol_table: 0},
	{upper_angle_Set_bacak_sag_table: 0},
	{upper_angle_Set_bacak_sol_table: 0},
	{upper_angle_Set_baldir_sag_table: 0},
	{upper_angle_Set_baldir_sol_table: 0},
	{w_push_table: 0},
	{winner_light_table: 0},
	{wins_text_table: 0},
	{"1p_Medieval": 0},
	{"2p_Medieval": 0},
	{akey_Medieval: 0},
	{asdsa_Medieval: 0},
	{bggg_Medieval: 0},
	{bluayakarka_Medieval: 0},
	{bluayakon_Medieval: 0},
	{blue_kaide_Medieval: 0},
	{blue_saft1_Medieval: 0},
	{blue_saft2_Medieval: 0},
	{blue_teker1_Medieval: 0},
	{blue_teker2_Medieval: 0},
	{bluebacakarka_Medieval: 0},
	{bluebacakon_Medieval: 0},
	{bluebaldirarka_Medieval: 0},
	{bluebaldiron_Medieval: 0},
	{bluebas_Medieval: 0},
	{bluegovde_Medieval: 0},
	{bluegun2_Medieval: 0},
	{bluegun3_Medieval: 0},
	{bluegun_Medieval: 0},
	{bluehead_Medieval: 0},
	{bluehealtbar_Medieval: 0},
	{blueittitgec_Medieval: 0},
	{bluekan_Medieval: 0},
	{bluekolarka2_Medieval: 0},
	{bluekolarka_Medieval: 0},
	{bluekolon2_Medieval: 0},
	{bluekolon_Medieval: 0},
	{bluelarka_Medieval: 0},
	{bluelon_Medieval: 0},
	{bluestar_Medieval: 0},
	{bulut_Medieval: 0},
	{camera_Medieval: 0},
	{dkey_Medieval: 0},
	{effectt_Medieval: 0},
	{hiclipartcom_Medieval: 0},
	{home_Medieval: 0},
	{htpweb_Medieval: 0},
	{leftarrow_Medieval: 0},
	{loading_Medieval: 0},
	{mizrak_Medieval: 0},
	{MOON_Medieval: 0},
	{orange_kaide_Medieval: 0},
	{orange_saft1_Medieval: 0},
	{orange_saft2_Medieval: 0},
	{orange_teker1_Medieval: 0},
	{orange_teker2_Medieval: 0},
	{orangeayakarka_Medieval: 0},
	{orangeayakon_Medieval: 0},
	{orangebacakarka_Medieval: 0},
	{orangebacakon_Medieval: 0},
	{orangebaldirarka_Medieval: 0},
	{orangebaldiron_Medieval: 0},
	{orangebas_Medieval: 0},
	{orangeelarka_Medieval: 0},
	{orangeelon_Medieval: 0},
	{orangegovde_Medieval: 0},
	{orangegun2_Medieval: 0},
	{orangegun3_Medieval: 0},
	{orangegun_Medieval: 0},
	{orangehead_Medieval: 0},
	{orangehealtbar_Medieval: 0},
	{orangeittirgec_Medieval: 0},
	{orangekan_Medieval: 0},
	{orangekolarka2_Medieval: 0},
	{orangekolarka_Medieval: 0},
	{orangekolon2_Medieval: 0},
	{orangekolon_Medieval: 0},
	{orangemizrak_Medieval: 0},
	{orangestar_Medieval: 0},
	{ormanblack_Medieval: 0},
	{playbg_Medieval: 0},
	{replay_Medieval: 0},
	{rightarrow_Medieval: 0},
	{roadd_Medieval: 0},
	{ROUNDD_Medieval: 0},
	{scores_Medieval: 0},
	{spark_Medieval: 0},
	{speeder_Medieval: 0},
	{Sprite2_Medieval: 0},
	{Sprite3_Medieval: 0},
	{Sprite4_Medieval: 0},
	{Sprite5_Medieval: 0},
	{Sprite_Medieval: 0},
	{starss_Medieval: 0},
	{TiledBackground_Medieval: 0},
	{title1_Medieval: 0},
	{title2_Medieval: 0},
	{title3_Medieval: 0},
	{Untitled2_0000_a_dkeys_Medieval: 0},
	{Untitled2_0000_rightwins_Medieval: 0},
	{Untitled2_0001_arrowkeys_Medieval: 0},
	{Untitled2_0003_Layer_Medieval: 0},
	{Untitled2_0004_Layer10copy_Medieval: 0},
	{Untitled2_0005_Layer10copy_Medieval: 0},
	{Untitled2_0006_Layer2copy_Medieval: 0},
	{Untitled2_0007_Layer2copy_Medieval: 0},
	{Untitled2_0033_RoundedRectangle2_Medieval: 0},
	{Untitled2_0033_RoundedRectangle_Medieval: 0},
	{winmoregames_Medieval: 0},
	{DragDrop: 0},
	{z_Camera_Object_A_Medieval: 0},
	{z_Camera_Object_B_Medieval: 0},
	{z_Camera_Object_Camera2_Medieval: 0},
	{playercamactive: 0},
	{z_Camera_Object_Camera_Medieval: 0},
	{z_Camera_Object_Line_Medieval: 0},
	{zeminblue_Medieval: 0},
	{zeminorange_Medieval: 0},
	{a_Getontop: 0},
	{ayak_sag_Getontop: 0},
	{ayak_sol_Getontop: 0},
	{bacak_sag_Getontop: 0},
	{bacak_sol_Getontop: 0},
	{baldir_sag_Getontop: 0},
	{baldir_sol_Getontop: 0},
	{ball_Getontop: 0},
	{bas_sag_Getontop: 0},
	{bas_sol_Getontop: 0},
	{blueayak_Getontop: 0},
	{bluebacak_Getontop: 0},
	{bluebaldir_Getontop: 0},
	{bluebas_Getontop: 0},
	{bluegovde_Getontop: 0},
	{bluekol_Getontop: 0},
	{bluescr_Getontop: 0},
	{collider_Getontop: 0},
	{d_Getontop: 0},
	{duvar_Getontop: 0},
	{getontop_Getontop: 0},
	{govde_sag_Getontop: 0},
	{govde_sol_Getontop: 0},
	{kol_sag_Getontop: 0},
	{kol_sol_Getontop: 0},
	{lef_arrow_Getontop: 0},
	{leftayak_Getontop: 0},
	{leftayakeffect_Getontop: 0},
	{leftbacak_Getontop: 0},
	{leftbacakeffect_Getontop: 0},
	{leftbaldir_Getontop: 0},
	{leftbaldireffect2_Getontop: 0},
	{leftbas_Getontop: 0},
	{leftbaseffect_Getontop: 0},
	{leftgovde_Getontop: 0},
	{leftgovdeeffect_Getontop: 0},
	{leftkol_Getontop: 0},
	{leftkoleffect_Getontop: 0},
	{lower_angle_Set_ayak_sag_Getontop: 0},
	{lower_angle_Set_ayak_sol_Getontop: 0},
	{lower_angle_Set_bacak_sag_Getontop: 0},
	{lower_angle_Set_bacak_sol_Getontop: 0},
	{lower_angle_Set_baldir_sag_Getontop: 0},
	{lower_angle_Set_baldir_sol_Getontop: 0},
	{moregames_Getontop: 0},
	{force_up: 0},
	{force_down: 0},
	{object_movible_Getontop: 0},
	{obstacle_Getontop: 0},
	{orangescr_Getontop: 0},
	{right_arrow_Getontop: 0},
	{rightayakeffect_Getontop: 0},
	{rightbacakeffect_Getontop: 0},
	{rightbaldireffect_Getontop: 0},
	{rightbaseffect_Getontop: 0},
	{rightgovdeeffect_Getontop: 0},
	{rightkoleffect_Getontop: 0},
	{TiledBackground_Getontop: 0},
	{timeee_Getontop: 0},
	{Untitled2_0000_Group_Getontop: 0},
	{Untitled2_0001_Group_Getontop: 0},
	{Untitled2_0002_Untitled1_0005_Layer69copy_Getontop: 0},
	{Untitled2_0003_Untitled1_0004_Layer_Getontop: 0},
	{Untitled2_0005_Untitled1_0000_Layer_Getontop: 0},
	{Untitled2_0010_touch_Getontop: 0},
	{Untitled_Getontop_Getontop: 0},
	{up_arrow_Getontop: 0},
	{uparrowtouch_Getontop: 0},
	{upper_angle_Set_ayak_sag_Getontop: 0},
	{upper_angle_Set_ayak_sol_Getontop: 0},
	{upper_angle_Set_bacak_sag_Getontop: 0},
	{upper_angle_Set_bacak_sol_Getontop: 0},
	{upper_angle_Set_baldir_sag_Getontop: 0},
	{upper_angle_Set_baldir_sol_Getontop: 0},
	{w_Getontop: 0},
	{who_wins_Getontop: 0},
	{wtouch_Getontop: 0},
	{"3d_seesaw": 0},
	{aspawnangle_seesaw: 0},
	{Ball_Over_seesaw: 0},
	{Ball_Overlay_seesaw: 0},
	{Ball_seesaw: 0},
	{balltrace2_seesaw: 0},
	{balltrace_seesaw_seesaw: 0},
	{basket_seesaw: 0},
	{beach_seesaw: 0},
	{blue_basket_light_seesaw: 0},
	{blue_wins_seesaw: 0},
	{blue_wins_texture_seesaw: 0},
	{bluecast1_seesaw: 0},
	{bluecast2_seesaw: 0},
	{bluering_seesaw: 0},
	{bluesensor_seesaw: 0},
	{blueskor_seesaw: 0},
	{bspawnangle_seesaw: 0},
	{Camera_seesaw: 0},
	{CBlast_seesaw: 0},
	{explosion_seesaw: 0},
	{game_bg_seesaw: 0},
	{GoalE_seesaw: 0},
	{GoalP_seesaw: 0},
	{rightt_touch_seesaw: 0},
	{mainmenu_seesaw: 0},
	{more_games_seesaw: 0},
	{Particles_seesaw: 0},
	{play2_seesaw: 0},
	{play_again_seesaw: 0},
	{pressa_seesaw: 0},
	{pressk_seesaw: 0},
	{red_basket_light_seesaw: 0},
	{red_wins_seesaw: 0},
	{red_wins_texture_seesaw: 0},
	{redcast1_seesaw: 0},
	{redcast2_seesaw: 0},
	{redring_seesaw: 0},
	{redsensor_seesaw: 0},
	{redskor_seesaw: 0},
	{left_touch_seesaw: 0},
	{ScoreBG_seesaw: 0},
	{seesaw_seesaw: 0},
	{seesawlogo_seesaw: 0},
	{blueplayerr_seesaw: 0},
	{Sprite13_seesaw: 0},
	{Sprite14_seesaw: 0},
	{Sprite15_seesaw: 0},
	{Sprite17_seesaw: 0},
	{Sprite22_seesaw: 0},
	{Sprite3_seesaw: 0},
	{Sprite6_seesaw: 0},
	{Sprite8_seesaw: 0},
	{redplayerr_seesaw: 0},
	{Sprite_seesaw: 0},
	{stopa_seesaw: 0},
	{stopb_seesaw: 0},
	{SunBams_seesaw: 0},
	{Wall_seesaw: 0},
	{whiteFX_seesaw: 0},
	{Win_seesaw: 0},
	{Sprite5_seesaw: 0},
	{Sprite4_seesaw: 0},
	{Sprite2_seesaw: 0},
	{Sprite20_seesaw: 0},
	{Sprite16_seesaw: 0},
	{Sprite11_seesaw: 0},
	{Sprite10_seesaw: 0},
	{soccer_seesaw: 0},
	{soccer_ball_button_seesaw: 0},
	{beach_ball_button_seesaw: 0},
	{basket_ball_button_seesaw: 0},
	{"3dball_playpage_soccer_seesaw": 0},
	{"3dball_playpage_beach_seesaw": 0},
	{"3dball_playpage_basket_seesaw": 0},
	{ScoreBG_seesaw2: 0},
	{ai_sensor_seesaw: 0},
	{"1player_Cow": 0},
	{"2player_Cow": 0},
	{"30sn_Cow": 0},
	{"40sn_Cow": 0},
	{"50sn_Cow": 0},
	{"60sn_Cow": 0},
	{A_Cow: 0},
	{aa_Cow: 0},
	{cam_Cow: 0},
	{CoolGames_Cow: 0},
	{D_Cow: 0},
	{dd_Cow: 0},
	{eye2_Cow: 0},
	{eye_Cow: 0},
	{gerisay_Cow: 0},
	{hom2_Cow: 0},
	{hom_Cow: 0},
	{Howmanysecondscanyoumilkingfourbuckets_Cow: 0},
	{intro_background_Cow: 0},
	{Sine2: 0},
	{intro_bg_Cow: 0},
	{intro_play_Cow: 0},
	{intro_playcoolgames_Cow: 0},
	{J_Cow: 0},
	{jj_Cow: 0},
	{K_Cow: 0},
	{kk_Cow: 0},
	{L_Cow: 0},
	{Layer11copy_Cow: 0},
	{Layer12copy_Cow: 0},
	{Layer2_Cow: 0},
	{Layer3copy2_Cow: 0},
	{ll_Cow: 0},
	{mg2_Cow: 0},
	{mg_Cow: 0},
	{milk_bullet_Cow: 0},
	{milk_p1_Cow: 0},
	{milk_p2_Cow: 0},
	{MilkTank_Cow: 0},
	{MILKTHECOW_Cow: 0},
	{moo1_Cow: 0},
	{moo2_Cow: 0},
	{rep_Cow: 0},
	{S_Cow: 0},
	{sag_Cow: 0},
	{sag_destroy_Cow: 0},
	{sag_ust_kova_Cow: 0},
	{sagbigmeme_Cow: 0},
	{saggolge_Cow: 0},
	{sagkova_Cow: 0},
	{sagkovaskor_Cow: 0},
	{sagkovatext4_Cow: 0},
	{sagtank_destroy_Cow: 0},
	{sagtankbar_Cow: 0},
	{sagtanktext_Cow: 0},
	{sol_Cow: 0},
	{sol_destroy_Cow: 0},
	{solbigmeme_Cow: 0},
	{solgolge_Cow: 0},
	{solkova_Cow: 0},
	{solkovaskor_Cow: 0},
	{solkovatext3_Cow: 0},
	{solkovaustkatman_Cow: 0},
	{soltank_destroy_Cow: 0},
	{soltankbar_Cow: 0},
	{soltanktext2_Cow: 0},
	{sound_Cow: 0},
	{Sprite2_Cow: 0},
	{Sprite_Cow: 0},
	{ss_Cow: 0},
	{tanktrouble_Cow: 0},
	{TwoPlayer_Cow: 0},
	{Untitled2_Cow: 0},
	{Untitled3_Cow: 0},
	{Untitled4_Cow: 0},
	{Untitled_Cow: 0},
	{VectorSmartObject2_Cow: 0},
	{VectorSmartObject3_Cow: 0},
	{VectorSmartObject6_Cow: 0},
	{VectorSmartObject_Cow: 0},
	{VectorSmartObjectcopy2_Cow: 0},
	{VectorSmartObjectcopy4_Cow: 0},
	{VectorSmartObjectcopy_Cow: 0},
	{Win_Cow: 0},
	{Winner_Cow: 0},
	{zemmin_Cow: 0},
	{Layer4copy_Cow: 0},
	{Audio: 0},
	{Browser: 0},
	{Function: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{PlatformInfo: 0},
	{Touch: 0},
	{camera2: 0},
	{"0001_PaperNote_Vegas": 0},
	{"0005_Layer_Vegas": 0},
	{"0009_o__Vegas": 0},
	{"0010_x__Vegas": 0},
	{"0014_selectgamecount_Vegas": 0},
	{"1PlayerButton_Vegas": 0},
	{"2PlayerButton_Vegas": 0},
	{Background_Vegas: 0},
	{Border_Vegas: 0},
	{Camera_Vegas: 0},
	{Close_Vegas: 0},
	{computer_Vegas: 0},
	{dead_Vegas: 0},
	{Default_Vegas: 0},
	{Symbol: 0},
	{XPos: 0},
	{YPos: 0},
	{Figure_Vegas: 0},
	{game_bg_Vegas: 0},
	{gc10_Vegas: 0},
	{gc3_Vegas: 0},
	{gc5_Vegas: 0},
	{gc_x_Vegas: 0},
	{ink_Vegas: 0},
	{introtwporg_Vegas: 0},
	{l1_Vegas: 0},
	{l2_Vegas: 0},
	{l3_Vegas: 0},
	{l4_Vegas: 0},
	{line2_Vegas: 0},
	{line3_Vegas: 0},
	{MenuButton2_Vegas: 0},
	{MenuButton_Vegas: 0},
	{more_games_Vegas: 0},
	{o1_Vegas: 0},
	{o2_Vegas: 0},
	{o3_Vegas: 0},
	{o4_Vegas: 0},
	{o5_Vegas: 0},
	{o6_Vegas: 0},
	{o7_Vegas: 0},
	{o8_Vegas: 0},
	{o9_Vegas: 0},
	{oo2_Vegas: 0},
	{oo3_Vegas: 0},
	{oo4_Vegas: 0},
	{oo5_Vegas: 0},
	{oo6_Vegas: 0},
	{oo7_Vegas: 0},
	{oo8_Vegas: 0},
	{oo9_Vegas: 0},
	{oscore_Vegas: 0},
	{owinner_Vegas: 0},
	{ox1_Vegas: 0},
	{ox2_Vegas: 0},
	{ox3_Vegas: 0},
	{ox4_Vegas: 0},
	{ox5_Vegas: 0},
	{ox6_Vegas: 0},
	{ox7_Vegas: 0},
	{ox8_Vegas: 0},
	{ox9_Vegas: 0},
	{Particles2_Vegas: 0},
	{Particles3_Vegas: 0},
	{Particles4_Vegas: 0},
	{Particles_Vegas: 0},
	{play_again_Vegas: 0},
	{play_intro_btn_Vegas: 0},
	{Player1_Vegas: 0},
	{Player2_Vegas: 0},
	{playy_Vegas: 0},
	{Score_Vegas: 0},
	{Sound_Vegas: 0},
	{Soundb_Vegas: 0},
	{Sprite3_Vegas: 0},
	{Sprite5_Vegas: 0},
	{Sprite_Vegas: 0},
	{stone_Vegas: 0},
	{TicTac2_Vegas: 0},
	{TicTac_Vegas: 0},
	{twplogo2_Vegas: 0},
	{twplogo_Vegas: 0},
	{Untitled2_Vegas: 0},
	{vin_o_Vegas: 0},
	{vinx_Vegas: 0},
	{winbgboard_Vegas: 0},
	{windestroy_o_Vegas: 0},
	{windestroy_x_Vegas: 0},
	{winner_wood_Vegas: 0},
	{winnerbg_Vegas: 0},
	{x1_Vegas: 0},
	{x2_Vegas: 0},
	{x3_Vegas: 0},
	{x4_Vegas: 0},
	{x5_Vegas: 0},
	{x6_Vegas: 0},
	{x7_Vegas: 0},
	{x8_Vegas: 0},
	{x9_Vegas: 0},
	{xscore_Vegas: 0},
	{xwinner_Vegas: 0},
	{xx1_Vegas: 0},
	{xx2_Vegas: 0},
	{xx3_Vegas: 0},
	{xx4_Vegas: 0},
	{xx5_Vegas: 0},
	{xx6_Vegas: 0},
	{xx7_Vegas: 0},
	{xx8_Vegas: 0},
	{xx9_Vegas: 0},
	{xxx2_Vegas: 0},
	{xxx3_Vegas: 0},
	{xxx4_Vegas: 0},
	{xxx5_Vegas: 0},
	{xxx6_Vegas: 0},
	{xxx7_Vegas: 0},
	{xxx8_Vegas: 0},
	{xxx9_Vegas: 0},
	{you_Vegas: 0},
	{zem1_Vegas: 0},
	{zem_Vegas: 0},
	{ArrayX_Vegas: 0},
	{ArrayY_Vegas: 0},
	{ArrayZ_Vegas: 0},
	{Background2_Vegas: 0},
	{Facebook: 0},
	{pplay_Vegas: 0},
	{Sprite2_Vegas: 0},
	{X_TURN: 0},
	{O_TURN: 0},
	{balon_camera: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{main_left_arrow: 0},
	{main_right_arrow: 0},
	{Sprite18: 0},
	{Video: 0},
	{game_name: 0},
	{game_name2: 0},
	{Main_Left_Scr: 0},
	{Main_Right_Scr: 0},
	{Sprite20: 0},
	{m_title_2p: 0},
	{Sprite22: 0},
	{m_title_choose: 0},
	{m_title_1p: 0},
	{Video2: 0},
	{kazik_seesaw: 0},
	{resetscorebutton: 0},
	{backbutton: 0},
	{sound_on_off: 0},
	{ikon_vagon: 0},
	{mercek: 0},
	{backgraund: 0},
	{monitor: 0},
	{score: 0},
	{Layer2copy: 0},
	{main_playbtn: 0},
	{main_homebtn: 0},
	{main_sound_off: 0},
	{main_reset: 0},
	{main_tttvegass: 0},
	{main_seesawballl: 0},
	{main_getontopp: 0},
	{main_medievall: 0},
	{main_drunkenduel: 0},
	{main_tugtheetablee: 0},
	{main_milkthecov: 0},
	{choosgameicon: 0},
	{seesawduvar: 0},
	{filee2: 0},
	{pota: 0},
	{filee: 0},
	{ustpota: 0},
	{redyay: 0},
	{maviyay: 0},
	{main_pbtn1: 0},
	{main_pbtn2: 0},
	{main_moregames: 0},
	{Sprite26: 0},
	{backgraund2: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{mode: 0},
	{challenge_text: 0},
	{Sprite33: 0},
	{challenge_right_arrow: 0},
	{challenge_left_arrow: 0},
	{dil: 0},
	{language_text: 0},
	{menu_popup: 0},
	{yes: 0},
	{no: 0},
	{Menu_Text: 0},
	{yess: 0},
	{noo: 0},
	{menu_popup2: 0},
	{twen: 0},
	{l11: 0},
	{l2: 0},
	{l0: 0},
	{l1: 0},
	{l3: 0},
	{l4: 0},
	{l5: 0},
	{l6: 0},
	{l7: 0},
	{l8: 0},
	{l10: 0},
	{l9: 0},
	{Sprite19: 0},
	{x: 0},
	{Text: 0},
	{WeeGooSDK: 0},
	{govdeler: 0},
	{guns: 0},
	{govdebg: 0},
	{blueman: 0},
	{orangeman: 0},
	{Family1: 0},
	{lamb: 0},
	{destroy: 0},
	{sag_bg: 0},
	{sol_bg: 0},
	{Family2: 0},
	{winnerfade: 0},
	{vinbuton: 0},
	{yapayzekahedef: 0},
	{sagkollar_box: 0},
	{sag_box: 0},
	{sag_2_uzuv_box: 0},
	{Family1_table: 0},
	{golge_table: 0},
	{insivible_table: 0},
	{anchor_table: 0},
	{tween_table: 0},
	{add_table: 0},
	{winspanel_table: 0},
	{blueman_table: 0},
	{orangeman_table: 0},
	{button_table: 0},
	{bluefizik_Medieval: 0},
	{bluearac_Medieval: 0},
	{orangefizik_Medieval: 0},
	{orangearac_Medieval: 0},
	{blueman_Medieval: 0},
	{orangeman_Medieval: 0},
	{enerjieleman_Medieval: 0},
	{anchorr_Medieval: 0},
	{winseleman_Medieval: 0},
	{cursor_Medieval: 0},
	{playeleman_Medieval: 0},
	{touchbutton_Medieval: 0},
	{webhtp_Medieval: 0},
	{exgun_Medieval: 0},
	{touchbutton_Getontop: 0},
	{insivible_Getontop: 0},
	{pins_Getontop: 0},
	{cursor_Getontop: 0},
	{lefteffect_Getontop: 0},
	{wineffect_Getontop: 0},
	{castpin_seesaw: 0},
	{play_ball_seesaw: 0},
	{pin_Cow: 0},
	{add_button_Cow: 0},
	{moregamesicon_Cow: 0},
	{meme_Cow: 0},
	{anchor_Cow: 0},
	{dsaljk_Cow: 0},
	{Family1_Cow: 0},
	{sutbuton_Cow: 0},
	{button_Cow: 0},
	{buutton_balon: 0},
	{Family2_D_duel_Two: 0},
	{Pin_Vegas: 0},
	{zems_Vegas: 0},
	{Family2_Vegas: 0},
	{xx_Vegas: 0},
	{Family1_Vegas: 0},
	{particle_Vegas: 0},
	{button_Vegas: 0},
	{ox_Vegas: 0},
	{m_title_adjust: 0},
	{main_buttonn: 0},
	{challenge_button: 0},
	{language: 0},
	{zekapover: 0},
	{angelll: 0},
	{outline: 0},
	{orange_healt: 0},
	{blue_healt: 0},
	{blue_ghostt: 0},
	{orangeghost: 0},
	{stop: 0},
	{blue_score: 0},
	{orange_score: 0},
	{kimkazandi: 0},
	{"1p_or_2p": 0},
	{start_table: 0},
	{mavikazandi_table: 0},
	{turuncukazandi_table: 0},
	{renk_table: 0},
	{scale_table: 0},
	{blue_scr_table: 0},
	{Orange_scr_table: 0},
	{finish_table: 0},
	{volumee_table: 0},
	{yapayzeka_table: 0},
	{zekapower_table: 0},
	{"1p_or_2p3": 0},
	{orangelost: 0},
	{bluelost: 0},
	{blue_healt2: 0},
	{orange_healt2: 0},
	{kamerastop2: 0},
	{layoutscalell2: 0},
	{Camera2: 0},
	{Left_Scr_Medieval: 0},
	{Right_Scr_Medieval: 0},
	{ROUNDNUMBER: 0},
	{yapayzeka: 0},
	{"1p_or_2p4": 0},
	{finish: 0},
	{bggframe: 0},
	{playpage: 0},
	{gamepage: 0},
	{winspage: 0},
	{adjustdeger: 0},
	{leftscr_Getontop: 0},
	{rightscr_Getontop: 0},
	{yapay_w: 0},
	{yapay_a: 0},
	{yapay_d: 0},
	{adjust_Getontop: 0},
	{"1p_or_2p_Getontop": 0},
	{ready_seesaw: 0},
	{blue_score_seesaw: 0},
	{red_score_seesaw: 0},
	{mac_sonu_seesaw: 0},
	{forceAmountDT: 0},
	{gerisayim_Cow: 0},
	{sagtank_Cow: 0},
	{soltan_Cow: 0},
	{stop_Cow: 0},
	{gamecount_Vegas: 0},
	{stop_Vegas: 0},
	{frame_Vegas: 0},
	{"2Players_Vegas": 0},
	{WhoMovesFirst_Vegas: 0},
	{Win_Vegas: 0},
	{Player2Score_Vegas: 0},
	{Player1Score_Vegas: 0},
	{Step_Vegas: 0},
	{Move_Vegas: 0},
	{hangi_oyun_anasayfa: 0},
	{Main_Left_Score: 0},
	{Main_Right_Score: 0},
	{Main_Sound: 0},
	{main_1p_or_2p: 0},
	{Main_sound_vol: 0},
	{ScnRefreshRate: 0},
	{ballSpeed_Hz: 0},
	{ses: 0},
	{pause: 0},
	{challenge: 0}
];

self.InstanceType = {
	Arrowpush: class extends self.ISpriteInstance {},
	bacak_sag: class extends self.ISpriteInstance {},
	bacak_sag2: class extends self.ISpriteInstance {},
	bacak_sag2bg: class extends self.ISpriteInstance {},
	bacak_sagbg: class extends self.ISpriteInstance {},
	bacak_sol: class extends self.ISpriteInstance {},
	bacak_sol2: class extends self.ISpriteInstance {},
	bacak_sol2bg: class extends self.ISpriteInstance {},
	bacak_solbg: class extends self.ISpriteInstance {},
	baldir_sag: class extends self.ISpriteInstance {},
	baldir_sag2: class extends self.ISpriteInstance {},
	baldir_sag2bg: class extends self.ISpriteInstance {},
	baldir_sagbg: class extends self.ISpriteInstance {},
	baldir_sol: class extends self.ISpriteInstance {},
	baldir_sol2: class extends self.ISpriteInstance {},
	baldir_sol2bg: class extends self.ISpriteInstance {},
	baldir_solbg: class extends self.ISpriteInstance {},
	bas_sag: class extends self.ISpriteInstance {},
	bas_sag_timewarp: class extends self.ISpriteInstance {},
	bas_sagbg: class extends self.ISpriteInstance {},
	bas_sol: class extends self.ISpriteInstance {},
	bas_sol_timewarp: class extends self.ISpriteInstance {},
	bas_solbg: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	bgfade: class extends self.ISpriteInstance {},
	blue_healt_bar: class extends self.ISpriteInstance {},
	blue_star_panel: class extends self.ISpriteInstance {},
	bluebullet: class extends self.ISpriteInstance {},
	bluedestek: class extends self.ISpriteInstance {},
	bluedizkirma: class extends self.ISpriteInstance {},
	bluekan: class extends self.ISpriteInstance {},
	bluelazer: class extends self.ISpriteInstance {},
	bluelight: class extends self.ISpriteInstance {},
	bluesu: class extends self.ISpriteInstance {},
	ORANGE_WINS: class extends self.ISpriteInstance {},
	bluhealtzemin: class extends self.ISpriteInstance {},
	bottle: class extends self.ISpriteInstance {},
	bulleteffectblue: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	ciuuw: class extends self.ISpriteInstance {},
	darkmode: class extends self.ISpriteInstance {},
	duvar: class extends self.ISpriteInstance {},
	duvar1: class extends self.ISpriteInstance {},
	duvar2: class extends self.ISpriteInstance {},
	duvar3: class extends self.ISpriteInstance {},
	estimatedwaitingtime_15s: class extends self.ISpriteInstance {},
	FIGHT_box: class extends self.ISpriteInstance {},
	FLAWLESSVICTORY_blue: class extends self.ISpriteInstance {},
	FLAWLESSVICTORY_orange: class extends self.ISpriteInstance {},
	gameoverbg: class extends self.ISpriteInstance {},
	gameoverbg2: class extends self.ISpriteInstance {},
	govde_sag: class extends self.ISpriteInstance {},
	govde_sagbg: class extends self.ISpriteInstance {},
	govde_sol: class extends self.ISpriteInstance {},
	govde_solbg: class extends self.ISpriteInstance {},
	gunblue: class extends self.ISpriteInstance {},
	gunorange: class extends self.ISpriteInstance {},
	hayaletduvar: class extends self.ISpriteInstance {},
	headshoot: class extends self.ISpriteInstance {},
	kazanan_light: class extends self.ISpriteInstance {},
	kimkazandiblue: class extends self.ISpriteInstance {},
	kimkazandiorange: class extends self.ISpriteInstance {},
	kol_sag: class extends self.ISpriteInstance {},
	kol_sag2: class extends self.ISpriteInstance {},
	kol_sag2_box: class extends self.ISpriteInstance {},
	kol_sag2bg: class extends self.ISpriteInstance {},
	kol_sag3: class extends self.ISpriteInstance {},
	kol_sag3bg: class extends self.ISpriteInstance {},
	kol_sag4: class extends self.ISpriteInstance {},
	kol_sag4bg: class extends self.ISpriteInstance {},
	kol_sagbg: class extends self.ISpriteInstance {},
	kol_sol: class extends self.ISpriteInstance {},
	kol_sol2: class extends self.ISpriteInstance {},
	kol_sol2bg: class extends self.ISpriteInstance {},
	kol_sol3: class extends self.ISpriteInstance {},
	kol_sol3bg: class extends self.ISpriteInstance {},
	kol_sol4: class extends self.ISpriteInstance {},
	kol_sol4bg: class extends self.ISpriteInstance {},
	kol_solbg: class extends self.ISpriteInstance {},
	lamb_timewarp: class extends self.ISpriteInstance {},
	ligtlamp: class extends self.ISpriteInstance {},
	ligtlamp2: class extends self.ISpriteInstance {},
	ligtline1: class extends self.ISpriteInstance {},
	ligtline2: class extends self.ISpriteInstance {},
	ligtline3: class extends self.ISpriteInstance {},
	ligtline4: class extends self.ISpriteInstance {},
	ligtline5: class extends self.ISpriteInstance {},
	ligtline6: class extends self.ISpriteInstance {},
	ligtline7: class extends self.ISpriteInstance {},
	ligtline8: class extends self.ISpriteInstance {},
	mainmenu: class extends self.ISpriteInstance {},
	masa: class extends self.ISpriteInstance {},
	masafade: class extends self.ISpriteInstance {},
	moregames: class extends self.ISpriteInstance {},
	orange_healt_bar: class extends self.ISpriteInstance {},
	orange_star_panel: class extends self.ISpriteInstance {},
	orangebullet: class extends self.ISpriteInstance {},
	orangeeffectblue: class extends self.ISpriteInstance {},
	orangehealtzemin: class extends self.ISpriteInstance {},
	orangekan: class extends self.ISpriteInstance {},
	orangelazer: class extends self.ISpriteInstance {},
	orangelight: class extends self.ISpriteInstance {},
	orangesu: class extends self.ISpriteInstance {},
	BLUE_WINS: class extends self.ISpriteInstance {},
	poverbarturuncu: class extends self.ISpriteInstance {},
	powerbarmavi: class extends self.ISpriteInstance {},
	ready: class extends self.ISpriteInstance {},
	replay: class extends self.ISpriteInstance {},
	searchingforopponent: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	taban: class extends self.ISpriteInstance {},
	Untitled1_0000_Layer5copy: class extends self.ISpriteInstance {},
	Untitled1_0001_Layer: class extends self.ISpriteInstance {},
	Untitled1_0003_Layer: class extends self.ISpriteInstance {},
	Untitled1_0011_1p: class extends self.ISpriteInstance {},
	Untitled1_0012_2p: class extends self.ISpriteInstance {},
	Untitled1_0013_w: class extends self.ISpriteInstance {},
	Untitled1_0014_Layer: class extends self.ISpriteInstance {},
	Untitled1_0016_twoplayergamesorgcopy: class extends self.ISpriteInstance {},
	Untitled1_0018_Layer: class extends self.ISpriteInstance {},
	Untitled1_0020_Layer8copy: class extends self.ISpriteInstance {},
	Untitled1_0021_Layer: class extends self.ISpriteInstance {},
	Untitled1_0023_Untitled1_0002_Layer: class extends self.ISpriteInstance {},
	Untitled1_0028_DUELL: class extends self.ISpriteInstance {},
	Untitled1_0030_DRUNKEN: class extends self.ISpriteInstance {},
	winman: class extends self.ISpriteInstance {},
	wpush: class extends self.ISpriteInstance {},
	ypcollider: class extends self.ISpriteInstance {},
	Untitled1_0028_DUELL2: class extends self.ISpriteInstance {},
	Untitled1_0028_DUELL3: class extends self.ISpriteInstance {},
	Untitled1_0028_DUELL4: class extends self.ISpriteInstance {},
	Untitled1_0013_w2: class extends self.ISpriteInstance {},
	Untitled1_0014_Layer2: class extends self.ISpriteInstance {},
	Untitled1_0028_DUELL5: class extends self.ISpriteInstance {},
	Untitled1_0028_DUELL6: class extends self.ISpriteInstance {},
	Untitled1_0028_DUELL7: class extends self.ISpriteInstance {},
	angled_table: class extends self.ISpriteInstance {},
	arrow_push_table: class extends self.ISpriteInstance {},
	ayak_sag2_table: class extends self.ISpriteInstance {},
	ayak_sag_bg2_table: class extends self.ISpriteInstance {},
	ayak_sag_bg_table: class extends self.ISpriteInstance {},
	ayak_sag_table: class extends self.ISpriteInstance {},
	ayak_sol2_table: class extends self.ISpriteInstance {},
	ayak_sol_bg2_table: class extends self.ISpriteInstance {},
	ayak_sol_bg_table: class extends self.ISpriteInstance {},
	ayak_sol_table: class extends self.ISpriteInstance {},
	bacak_sag2_table: class extends self.ISpriteInstance {},
	bacak_sag_bg2_table: class extends self.ISpriteInstance {},
	bacak_sag_bg_table: class extends self.ISpriteInstance {},
	bacak_sag_table: class extends self.ISpriteInstance {},
	bacak_sol2_table: class extends self.ISpriteInstance {},
	bacak_sol_bg2_table: class extends self.ISpriteInstance {},
	bacak_sol_bg_table: class extends self.ISpriteInstance {},
	bacak_sol_table: class extends self.ISpriteInstance {},
	baldir_sag2_table: class extends self.ISpriteInstance {},
	baldir_sag_bg2_table: class extends self.ISpriteInstance {},
	baldir_sag_bg_table: class extends self.ISpriteInstance {},
	baldir_sag_table: class extends self.ISpriteInstance {},
	baldir_sol2_table: class extends self.ISpriteInstance {},
	baldir_sol_bg2_table: class extends self.ISpriteInstance {},
	baldir_sol_bg_table: class extends self.ISpriteInstance {},
	baldir_sol_table: class extends self.ISpriteInstance {},
	ball3deffect_table: class extends self.ISpriteInstance {},
	bas_sag_bg_table: class extends self.ISpriteInstance {},
	bas_sag_table: class extends self.ISpriteInstance {},
	bas_sol_bg_table: class extends self.ISpriteInstance {},
	bas_sol_table: class extends self.ISpriteInstance {},
	bg_table: class extends self.ISpriteInstance {},
	bgg_table: class extends self.ISpriteInstance {},
	bileksag2_table: class extends self.ISpriteInstance {},
	bileksag_bg2_table: class extends self.ISpriteInstance {},
	bileksag_bg_table: class extends self.ISpriteInstance {},
	bileksag_table: class extends self.ISpriteInstance {},
	bileksol2_table: class extends self.ISpriteInstance {},
	bileksol_bg2_table: class extends self.ISpriteInstance {},
	bileksol_bg_table: class extends self.ISpriteInstance {},
	bileksol_table: class extends self.ISpriteInstance {},
	blue_star_panel_table: class extends self.ISpriteInstance {},
	boommm_table: class extends self.ISpriteInstance {},
	bow_ball_table: class extends self.ISpriteInstance {},
	button_1p_table: class extends self.ISpriteInstance {},
	button_2p_table: class extends self.ISpriteInstance {},
	button_arrowpush_table: class extends self.ISpriteInstance {},
	button_game_home_table: class extends self.ISpriteInstance {},
	button_home_table: class extends self.ISpriteInstance {},
	button_playmoregames_table: class extends self.ISpriteInstance {},
	button_replay_table: class extends self.ISpriteInstance {},
	button_win_moregames_table: class extends self.ISpriteInstance {},
	button_wpush_table: class extends self.ISpriteInstance {},
	camera_table: class extends self.ISpriteInstance {},
	colleft_table: class extends self.ISpriteInstance {},
	collider_table: class extends self.ISpriteInstance {},
	deneme3_table: class extends self.ISpriteInstance {},
	govde_sag_bg_table: class extends self.ISpriteInstance {},
	govde_sag_table: class extends self.ISpriteInstance {},
	govde_sol_bg_table: class extends self.ISpriteInstance {},
	govde_sol_table: class extends self.ISpriteInstance {},
	kablo_table: class extends self.ISpriteInstance {},
	kol_sag2_table: class extends self.ISpriteInstance {},
	kol_sag_bg2_table: class extends self.ISpriteInstance {},
	kol_sag_bg_table: class extends self.ISpriteInstance {},
	kol_sag_table: class extends self.ISpriteInstance {},
	kol_sol2_table: class extends self.ISpriteInstance {},
	kol_sol_bg2_table: class extends self.ISpriteInstance {},
	kol_sol_bg_table: class extends self.ISpriteInstance {},
	kol_sol_table: class extends self.ISpriteInstance {},
	ligtlamp2_table: class extends self.ISpriteInstance {},
	ligtlamp_table: class extends self.ISpriteInstance {},
	ligtline3_table: class extends self.ISpriteInstance {},
	lower_angle_Set_ayak_sag_table: class extends self.ISpriteInstance {},
	lower_angle_Set_ayak_sol_table: class extends self.ISpriteInstance {},
	lower_angle_Set_bacak_sag_table: class extends self.ISpriteInstance {},
	lower_angle_Set_bacak_sol_table: class extends self.ISpriteInstance {},
	lower_angle_Set_baldir_sag_table: class extends self.ISpriteInstance {},
	lower_angle_Set_baldir_sol_table: class extends self.ISpriteInstance {},
	manz_table: class extends self.ISpriteInstance {},
	masaayaksag_table: class extends self.ISpriteInstance {},
	masaayaksol_table: class extends self.ISpriteInstance {},
	masagolge_table: class extends self.ISpriteInstance {},
	mavigolge_table: class extends self.ISpriteInstance {},
	orange_star_panel_table: class extends self.ISpriteInstance {},
	orangegolge_table: class extends self.ISpriteInstance {},
	portal_table: class extends self.ISpriteInstance {},
	scores_text_table: class extends self.ISpriteInstance {},
	Sprite11_table: class extends self.ISpriteInstance {},
	Sprite2_table: class extends self.ISpriteInstance {},
	Sprite3_table: class extends self.ISpriteInstance {},
	Sprite5_table: class extends self.ISpriteInstance {},
	Sprite6_table: class extends self.ISpriteInstance {},
	Sprite7_table: class extends self.ISpriteInstance {},
	Sprite8_table: class extends self.ISpriteInstance {},
	table_table: class extends self.ISpriteInstance {},
	tennisball_table: class extends self.ISpriteInstance {},
	tennisball_table2: class extends self.ISpriteInstance {},
	top_table: class extends self.ISpriteInstance {},
	Untitled2_0000_go_table_table: class extends self.ISpriteInstance {},
	Untitled2_0007_Group_table: class extends self.ISpriteInstance {},
	Untitled2_0007_PLAYCOOLGAMES_table: class extends self.ISpriteInstance {},
	upper_angle_Set_ayak_sag_table: class extends self.ISpriteInstance {},
	upper_angle_Set_ayak_sol_table: class extends self.ISpriteInstance {},
	upper_angle_Set_bacak_sag_table: class extends self.ISpriteInstance {},
	upper_angle_Set_bacak_sol_table: class extends self.ISpriteInstance {},
	upper_angle_Set_baldir_sag_table: class extends self.ISpriteInstance {},
	upper_angle_Set_baldir_sol_table: class extends self.ISpriteInstance {},
	w_push_table: class extends self.ISpriteInstance {},
	winner_light_table: class extends self.ISpriteInstance {},
	wins_text_table: class extends self.ISpriteInstance {},
	_1p_Medieval: class extends self.ISpriteInstance {},
	_2p_Medieval: class extends self.ISpriteInstance {},
	akey_Medieval: class extends self.ISpriteInstance {},
	asdsa_Medieval: class extends self.ISpriteInstance {},
	bggg_Medieval: class extends self.ISpriteInstance {},
	bluayakarka_Medieval: class extends self.ISpriteInstance {},
	bluayakon_Medieval: class extends self.ISpriteInstance {},
	blue_kaide_Medieval: class extends self.ISpriteInstance {},
	blue_saft1_Medieval: class extends self.ISpriteInstance {},
	blue_saft2_Medieval: class extends self.ISpriteInstance {},
	blue_teker1_Medieval: class extends self.ISpriteInstance {},
	blue_teker2_Medieval: class extends self.ISpriteInstance {},
	bluebacakarka_Medieval: class extends self.ISpriteInstance {},
	bluebacakon_Medieval: class extends self.ISpriteInstance {},
	bluebaldirarka_Medieval: class extends self.ISpriteInstance {},
	bluebaldiron_Medieval: class extends self.ISpriteInstance {},
	bluebas_Medieval: class extends self.ISpriteInstance {},
	bluegovde_Medieval: class extends self.ISpriteInstance {},
	bluegun2_Medieval: class extends self.ISpriteInstance {},
	bluegun3_Medieval: class extends self.ISpriteInstance {},
	bluegun_Medieval: class extends self.ISpriteInstance {},
	bluehead_Medieval: class extends self.ISpriteInstance {},
	bluehealtbar_Medieval: class extends self.ISpriteInstance {},
	blueittitgec_Medieval: class extends self.ISpriteInstance {},
	bluekan_Medieval: class extends self.ISpriteInstance {},
	bluekolarka2_Medieval: class extends self.ISpriteInstance {},
	bluekolarka_Medieval: class extends self.ISpriteInstance {},
	bluekolon2_Medieval: class extends self.ISpriteInstance {},
	bluekolon_Medieval: class extends self.ISpriteInstance {},
	bluelarka_Medieval: class extends self.ISpriteInstance {},
	bluelon_Medieval: class extends self.ISpriteInstance {},
	bluestar_Medieval: class extends self.ISpriteInstance {},
	bulut_Medieval: class extends self.ISpriteInstance {},
	camera_Medieval: class extends self.ISpriteInstance {},
	dkey_Medieval: class extends self.ISpriteInstance {},
	effectt_Medieval: class extends self.ISpriteInstance {},
	hiclipartcom_Medieval: class extends self.ISpriteInstance {},
	home_Medieval: class extends self.ISpriteInstance {},
	htpweb_Medieval: class extends self.ISpriteInstance {},
	leftarrow_Medieval: class extends self.ISpriteInstance {},
	loading_Medieval: class extends self.ISpriteInstance {},
	mizrak_Medieval: class extends self.ISpriteInstance {},
	MOON_Medieval: class extends self.ISpriteInstance {},
	orange_kaide_Medieval: class extends self.ISpriteInstance {},
	orange_saft1_Medieval: class extends self.ISpriteInstance {},
	orange_saft2_Medieval: class extends self.ISpriteInstance {},
	orange_teker1_Medieval: class extends self.ISpriteInstance {},
	orange_teker2_Medieval: class extends self.ISpriteInstance {},
	orangeayakarka_Medieval: class extends self.ISpriteInstance {},
	orangeayakon_Medieval: class extends self.ISpriteInstance {},
	orangebacakarka_Medieval: class extends self.ISpriteInstance {},
	orangebacakon_Medieval: class extends self.ISpriteInstance {},
	orangebaldirarka_Medieval: class extends self.ISpriteInstance {},
	orangebaldiron_Medieval: class extends self.ISpriteInstance {},
	orangebas_Medieval: class extends self.ISpriteInstance {},
	orangeelarka_Medieval: class extends self.ISpriteInstance {},
	orangeelon_Medieval: class extends self.ISpriteInstance {},
	orangegovde_Medieval: class extends self.ISpriteInstance {},
	orangegun2_Medieval: class extends self.ISpriteInstance {},
	orangegun3_Medieval: class extends self.ISpriteInstance {},
	orangegun_Medieval: class extends self.ISpriteInstance {},
	orangehead_Medieval: class extends self.ISpriteInstance {},
	orangehealtbar_Medieval: class extends self.ISpriteInstance {},
	orangeittirgec_Medieval: class extends self.ISpriteInstance {},
	orangekan_Medieval: class extends self.ISpriteInstance {},
	orangekolarka2_Medieval: class extends self.ISpriteInstance {},
	orangekolarka_Medieval: class extends self.ISpriteInstance {},
	orangekolon2_Medieval: class extends self.ISpriteInstance {},
	orangekolon_Medieval: class extends self.ISpriteInstance {},
	orangemizrak_Medieval: class extends self.ISpriteInstance {},
	orangestar_Medieval: class extends self.ISpriteInstance {},
	ormanblack_Medieval: class extends self.ISpriteInstance {},
	playbg_Medieval: class extends self.ISpriteInstance {},
	replay_Medieval: class extends self.ISpriteInstance {},
	rightarrow_Medieval: class extends self.ISpriteInstance {},
	roadd_Medieval: class extends self.ISpriteInstance {},
	ROUNDD_Medieval: class extends self.ISpriteInstance {},
	scores_Medieval: class extends self.ISpriteInstance {},
	spark_Medieval: class extends self.ISpriteInstance {},
	speeder_Medieval: class extends self.ISpriteInstance {},
	Sprite2_Medieval: class extends self.ISpriteInstance {},
	Sprite3_Medieval: class extends self.ISpriteInstance {},
	Sprite4_Medieval: class extends self.ISpriteInstance {},
	Sprite5_Medieval: class extends self.ISpriteInstance {},
	Sprite_Medieval: class extends self.ISpriteInstance {},
	starss_Medieval: class extends self.ISpriteInstance {},
	TiledBackground_Medieval: class extends self.ITiledBackgroundInstance {},
	title1_Medieval: class extends self.ISpriteInstance {},
	title2_Medieval: class extends self.ISpriteInstance {},
	title3_Medieval: class extends self.ISpriteInstance {},
	Untitled2_0000_a_dkeys_Medieval: class extends self.ISpriteInstance {},
	Untitled2_0000_rightwins_Medieval: class extends self.ISpriteInstance {},
	Untitled2_0001_arrowkeys_Medieval: class extends self.ISpriteInstance {},
	Untitled2_0003_Layer_Medieval: class extends self.ISpriteInstance {},
	Untitled2_0004_Layer10copy_Medieval: class extends self.ISpriteInstance {},
	Untitled2_0005_Layer10copy_Medieval: class extends self.ISpriteInstance {},
	Untitled2_0006_Layer2copy_Medieval: class extends self.ISpriteInstance {},
	Untitled2_0007_Layer2copy_Medieval: class extends self.ISpriteInstance {},
	Untitled2_0033_RoundedRectangle2_Medieval: class extends self.ISpriteInstance {},
	Untitled2_0033_RoundedRectangle_Medieval: class extends self.ISpriteInstance {},
	winmoregames_Medieval: class extends self.ISpriteInstance {},
	z_Camera_Object_A_Medieval: class extends self.ISpriteInstance {},
	z_Camera_Object_B_Medieval: class extends self.ISpriteInstance {},
	z_Camera_Object_Camera2_Medieval: class extends self.ISpriteInstance {},
	z_Camera_Object_Camera_Medieval: class extends self.ISpriteInstance {},
	z_Camera_Object_Line_Medieval: class extends self.ISpriteInstance {},
	zeminblue_Medieval: class extends self.ISpriteInstance {},
	zeminorange_Medieval: class extends self.ISpriteInstance {},
	a_Getontop: class extends self.ISpriteInstance {},
	ayak_sag_Getontop: class extends self.ISpriteInstance {},
	ayak_sol_Getontop: class extends self.ISpriteInstance {},
	bacak_sag_Getontop: class extends self.ISpriteInstance {},
	bacak_sol_Getontop: class extends self.ISpriteInstance {},
	baldir_sag_Getontop: class extends self.ISpriteInstance {},
	baldir_sol_Getontop: class extends self.ISpriteInstance {},
	ball_Getontop: class extends self.ISpriteInstance {},
	bas_sag_Getontop: class extends self.ISpriteInstance {},
	bas_sol_Getontop: class extends self.ISpriteInstance {},
	blueayak_Getontop: class extends self.ISpriteInstance {},
	bluebacak_Getontop: class extends self.ISpriteInstance {},
	bluebaldir_Getontop: class extends self.ISpriteInstance {},
	bluebas_Getontop: class extends self.ISpriteInstance {},
	bluegovde_Getontop: class extends self.ISpriteInstance {},
	bluekol_Getontop: class extends self.ISpriteInstance {},
	bluescr_Getontop: class extends self.ISpriteFontInstance {},
	collider_Getontop: class extends self.ISpriteInstance {},
	d_Getontop: class extends self.ISpriteInstance {},
	duvar_Getontop: class extends self.ISpriteInstance {},
	getontop_Getontop: class extends self.ISpriteInstance {},
	govde_sag_Getontop: class extends self.ISpriteInstance {},
	govde_sol_Getontop: class extends self.ISpriteInstance {},
	kol_sag_Getontop: class extends self.ISpriteInstance {},
	kol_sol_Getontop: class extends self.ISpriteInstance {},
	lef_arrow_Getontop: class extends self.ISpriteInstance {},
	leftayak_Getontop: class extends self.ISpriteInstance {},
	leftayakeffect_Getontop: class extends self.ISpriteInstance {},
	leftbacak_Getontop: class extends self.ISpriteInstance {},
	leftbacakeffect_Getontop: class extends self.ISpriteInstance {},
	leftbaldir_Getontop: class extends self.ISpriteInstance {},
	leftbaldireffect2_Getontop: class extends self.ISpriteInstance {},
	leftbas_Getontop: class extends self.ISpriteInstance {},
	leftbaseffect_Getontop: class extends self.ISpriteInstance {},
	leftgovde_Getontop: class extends self.ISpriteInstance {},
	leftgovdeeffect_Getontop: class extends self.ISpriteInstance {},
	leftkol_Getontop: class extends self.ISpriteInstance {},
	leftkoleffect_Getontop: class extends self.ISpriteInstance {},
	lower_angle_Set_ayak_sag_Getontop: class extends self.ISpriteInstance {},
	lower_angle_Set_ayak_sol_Getontop: class extends self.ISpriteInstance {},
	lower_angle_Set_bacak_sag_Getontop: class extends self.ISpriteInstance {},
	lower_angle_Set_bacak_sol_Getontop: class extends self.ISpriteInstance {},
	lower_angle_Set_baldir_sag_Getontop: class extends self.ISpriteInstance {},
	lower_angle_Set_baldir_sol_Getontop: class extends self.ISpriteInstance {},
	moregames_Getontop: class extends self.ISpriteInstance {},
	object_movible_Getontop: class extends self.ISpriteInstance {},
	obstacle_Getontop: class extends self.ISpriteInstance {},
	orangescr_Getontop: class extends self.ISpriteFontInstance {},
	right_arrow_Getontop: class extends self.ISpriteInstance {},
	rightayakeffect_Getontop: class extends self.ISpriteInstance {},
	rightbacakeffect_Getontop: class extends self.ISpriteInstance {},
	rightbaldireffect_Getontop: class extends self.ISpriteInstance {},
	rightbaseffect_Getontop: class extends self.ISpriteInstance {},
	rightgovdeeffect_Getontop: class extends self.ISpriteInstance {},
	rightkoleffect_Getontop: class extends self.ISpriteInstance {},
	TiledBackground_Getontop: class extends self.ITiledBackgroundInstance {},
	timeee_Getontop: class extends self.ISpriteInstance {},
	Untitled2_0000_Group_Getontop: class extends self.ISpriteInstance {},
	Untitled2_0001_Group_Getontop: class extends self.ISpriteInstance {},
	Untitled2_0002_Untitled1_0005_Layer69copy_Getontop: class extends self.ISpriteInstance {},
	Untitled2_0003_Untitled1_0004_Layer_Getontop: class extends self.ISpriteInstance {},
	Untitled2_0005_Untitled1_0000_Layer_Getontop: class extends self.ISpriteInstance {},
	Untitled2_0010_touch_Getontop: class extends self.ISpriteInstance {},
	Untitled_Getontop_Getontop: class extends self.ISpriteInstance {},
	up_arrow_Getontop: class extends self.ISpriteInstance {},
	uparrowtouch_Getontop: class extends self.ISpriteInstance {},
	upper_angle_Set_ayak_sag_Getontop: class extends self.ISpriteInstance {},
	upper_angle_Set_ayak_sol_Getontop: class extends self.ISpriteInstance {},
	upper_angle_Set_bacak_sag_Getontop: class extends self.ISpriteInstance {},
	upper_angle_Set_bacak_sol_Getontop: class extends self.ISpriteInstance {},
	upper_angle_Set_baldir_sag_Getontop: class extends self.ISpriteInstance {},
	upper_angle_Set_baldir_sol_Getontop: class extends self.ISpriteInstance {},
	w_Getontop: class extends self.ISpriteInstance {},
	who_wins_Getontop: class extends self.ISpriteInstance {},
	wtouch_Getontop: class extends self.ISpriteInstance {},
	_3d_seesaw: class extends self.ISpriteInstance {},
	aspawnangle_seesaw: class extends self.ISpriteInstance {},
	Ball_Over_seesaw: class extends self.ISpriteInstance {},
	Ball_Overlay_seesaw: class extends self.ISpriteInstance {},
	Ball_seesaw: class extends self.ISpriteInstance {},
	balltrace2_seesaw: class extends self.ISpriteInstance {},
	balltrace_seesaw_seesaw: class extends self.ISpriteInstance {},
	basket_seesaw: class extends self.ISpriteInstance {},
	beach_seesaw: class extends self.ISpriteInstance {},
	blue_basket_light_seesaw: class extends self.ISpriteInstance {},
	blue_wins_seesaw: class extends self.ISpriteInstance {},
	blue_wins_texture_seesaw: class extends self.ISpriteInstance {},
	bluecast1_seesaw: class extends self.ISpriteInstance {},
	bluecast2_seesaw: class extends self.ISpriteInstance {},
	bluering_seesaw: class extends self.ISpriteInstance {},
	bluesensor_seesaw: class extends self.ISpriteInstance {},
	blueskor_seesaw: class extends self.ISpriteInstance {},
	bspawnangle_seesaw: class extends self.ISpriteInstance {},
	Camera_seesaw: class extends self.ISpriteInstance {},
	CBlast_seesaw: class extends self.ISpriteInstance {},
	explosion_seesaw: class extends self.ISpriteInstance {},
	game_bg_seesaw: class extends self.ISpriteInstance {},
	GoalE_seesaw: class extends self.ISpriteInstance {},
	GoalP_seesaw: class extends self.ISpriteInstance {},
	rightt_touch_seesaw: class extends self.ISpriteInstance {},
	mainmenu_seesaw: class extends self.ISpriteInstance {},
	more_games_seesaw: class extends self.ISpriteInstance {},
	Particles_seesaw: class extends self.IParticlesInstance {},
	play2_seesaw: class extends self.ISpriteInstance {},
	play_again_seesaw: class extends self.ISpriteInstance {},
	pressa_seesaw: class extends self.ISpriteInstance {},
	pressk_seesaw: class extends self.ISpriteInstance {},
	red_basket_light_seesaw: class extends self.ISpriteInstance {},
	red_wins_seesaw: class extends self.ISpriteInstance {},
	red_wins_texture_seesaw: class extends self.ISpriteInstance {},
	redcast1_seesaw: class extends self.ISpriteInstance {},
	redcast2_seesaw: class extends self.ISpriteInstance {},
	redring_seesaw: class extends self.ISpriteInstance {},
	redsensor_seesaw: class extends self.ISpriteInstance {},
	redskor_seesaw: class extends self.ISpriteInstance {},
	left_touch_seesaw: class extends self.ISpriteInstance {},
	ScoreBG_seesaw: class extends self.ISpriteInstance {},
	seesaw_seesaw: class extends self.ISpriteInstance {},
	seesawlogo_seesaw: class extends self.ISpriteInstance {},
	blueplayerr_seesaw: class extends self.ISpriteInstance {},
	Sprite13_seesaw: class extends self.ISpriteInstance {},
	Sprite14_seesaw: class extends self.ISpriteInstance {},
	Sprite15_seesaw: class extends self.ISpriteInstance {},
	Sprite17_seesaw: class extends self.ISpriteInstance {},
	Sprite22_seesaw: class extends self.ISpriteInstance {},
	Sprite3_seesaw: class extends self.ISpriteInstance {},
	Sprite6_seesaw: class extends self.ISpriteInstance {},
	Sprite8_seesaw: class extends self.ISpriteInstance {},
	redplayerr_seesaw: class extends self.ISpriteInstance {},
	Sprite_seesaw: class extends self.ISpriteInstance {},
	stopa_seesaw: class extends self.ISpriteInstance {},
	stopb_seesaw: class extends self.ISpriteInstance {},
	SunBams_seesaw: class extends self.ISpriteInstance {},
	Wall_seesaw: class extends self.ISpriteInstance {},
	whiteFX_seesaw: class extends self.ISpriteInstance {},
	Win_seesaw: class extends self.ISpriteInstance {},
	Sprite5_seesaw: class extends self.ISpriteInstance {},
	Sprite4_seesaw: class extends self.ISpriteInstance {},
	Sprite2_seesaw: class extends self.ISpriteInstance {},
	Sprite20_seesaw: class extends self.ISpriteInstance {},
	Sprite16_seesaw: class extends self.ISpriteInstance {},
	Sprite11_seesaw: class extends self.ISpriteInstance {},
	Sprite10_seesaw: class extends self.ISpriteInstance {},
	soccer_seesaw: class extends self.ISpriteInstance {},
	soccer_ball_button_seesaw: class extends self.ISpriteInstance {},
	beach_ball_button_seesaw: class extends self.ISpriteInstance {},
	basket_ball_button_seesaw: class extends self.ISpriteInstance {},
	_3dball_playpage_soccer_seesaw: class extends self.ISpriteInstance {},
	_3dball_playpage_beach_seesaw: class extends self.ISpriteInstance {},
	_3dball_playpage_basket_seesaw: class extends self.ISpriteInstance {},
	ScoreBG_seesaw2: class extends self.ISpriteInstance {},
	ai_sensor_seesaw: class extends self.ISpriteInstance {},
	_1player_Cow: class extends self.ISpriteInstance {},
	_2player_Cow: class extends self.ISpriteInstance {},
	_30sn_Cow: class extends self.ISpriteInstance {},
	_40sn_Cow: class extends self.ISpriteInstance {},
	_50sn_Cow: class extends self.ISpriteInstance {},
	_60sn_Cow: class extends self.ISpriteInstance {},
	A_Cow: class extends self.ISpriteInstance {},
	aa_Cow: class extends self.ISpriteInstance {},
	cam_Cow: class extends self.ISpriteInstance {},
	CoolGames_Cow: class extends self.ISpriteInstance {},
	D_Cow: class extends self.ISpriteInstance {},
	dd_Cow: class extends self.ISpriteInstance {},
	eye2_Cow: class extends self.ISpriteInstance {},
	eye_Cow: class extends self.ISpriteInstance {},
	gerisay_Cow: class extends self.ISpriteFontInstance {},
	hom2_Cow: class extends self.ISpriteInstance {},
	hom_Cow: class extends self.ISpriteInstance {},
	Howmanysecondscanyoumilkingfourbuckets_Cow: class extends self.ISpriteInstance {},
	intro_background_Cow: class extends self.ISpriteInstance {},
	intro_bg_Cow: class extends self.ISpriteInstance {},
	intro_play_Cow: class extends self.ISpriteInstance {},
	intro_playcoolgames_Cow: class extends self.ISpriteInstance {},
	J_Cow: class extends self.ISpriteInstance {},
	jj_Cow: class extends self.ISpriteInstance {},
	K_Cow: class extends self.ISpriteInstance {},
	kk_Cow: class extends self.ISpriteInstance {},
	L_Cow: class extends self.ISpriteInstance {},
	Layer11copy_Cow: class extends self.ISpriteInstance {},
	Layer12copy_Cow: class extends self.ISpriteInstance {},
	Layer2_Cow: class extends self.ISpriteInstance {},
	Layer3copy2_Cow: class extends self.ISpriteInstance {},
	ll_Cow: class extends self.ISpriteInstance {},
	mg2_Cow: class extends self.ISpriteInstance {},
	mg_Cow: class extends self.ISpriteInstance {},
	milk_bullet_Cow: class extends self.ISpriteInstance {},
	milk_p1_Cow: class extends self.ISpriteInstance {},
	milk_p2_Cow: class extends self.ISpriteInstance {},
	MilkTank_Cow: class extends self.ISpriteInstance {},
	MILKTHECOW_Cow: class extends self.ISpriteInstance {},
	moo1_Cow: class extends self.ISpriteInstance {},
	moo2_Cow: class extends self.ISpriteInstance {},
	rep_Cow: class extends self.ISpriteInstance {},
	S_Cow: class extends self.ISpriteInstance {},
	sag_Cow: class extends self.ISpriteInstance {},
	sag_destroy_Cow: class extends self.ISpriteInstance {},
	sag_ust_kova_Cow: class extends self.ISpriteInstance {},
	sagbigmeme_Cow: class extends self.ISpriteInstance {},
	saggolge_Cow: class extends self.ISpriteInstance {},
	sagkova_Cow: class extends self.ISpriteInstance {},
	sagkovaskor_Cow: class extends self.ISpriteInstance {},
	sagkovatext4_Cow: class extends self.ISpriteFontInstance {},
	sagtank_destroy_Cow: class extends self.ISpriteInstance {},
	sagtankbar_Cow: class extends self.ISpriteInstance {},
	sagtanktext_Cow: class extends self.ISpriteFontInstance {},
	sol_Cow: class extends self.ISpriteInstance {},
	sol_destroy_Cow: class extends self.ISpriteInstance {},
	solbigmeme_Cow: class extends self.ISpriteInstance {},
	solgolge_Cow: class extends self.ISpriteInstance {},
	solkova_Cow: class extends self.ISpriteInstance {},
	solkovaskor_Cow: class extends self.ISpriteInstance {},
	solkovatext3_Cow: class extends self.ISpriteFontInstance {},
	solkovaustkatman_Cow: class extends self.ISpriteInstance {},
	soltank_destroy_Cow: class extends self.ISpriteInstance {},
	soltankbar_Cow: class extends self.ISpriteInstance {},
	soltanktext2_Cow: class extends self.ISpriteFontInstance {},
	sound_Cow: class extends self.ISpriteInstance {},
	Sprite2_Cow: class extends self.ISpriteInstance {},
	Sprite_Cow: class extends self.ISpriteInstance {},
	ss_Cow: class extends self.ISpriteInstance {},
	tanktrouble_Cow: class extends self.ISpriteInstance {},
	TwoPlayer_Cow: class extends self.ISpriteInstance {},
	Untitled2_Cow: class extends self.ISpriteInstance {},
	Untitled3_Cow: class extends self.ISpriteInstance {},
	Untitled4_Cow: class extends self.ISpriteInstance {},
	Untitled_Cow: class extends self.ISpriteInstance {},
	VectorSmartObject2_Cow: class extends self.ISpriteInstance {},
	VectorSmartObject3_Cow: class extends self.ISpriteInstance {},
	VectorSmartObject6_Cow: class extends self.ISpriteInstance {},
	VectorSmartObject_Cow: class extends self.ISpriteInstance {},
	VectorSmartObjectcopy2_Cow: class extends self.ISpriteInstance {},
	VectorSmartObjectcopy4_Cow: class extends self.ISpriteInstance {},
	VectorSmartObjectcopy_Cow: class extends self.ISpriteInstance {},
	Win_Cow: class extends self.ISpriteInstance {},
	Winner_Cow: class extends self.ISpriteInstance {},
	zemmin_Cow: class extends self.ISpriteInstance {},
	Layer4copy_Cow: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	camera2: class extends self.ISpriteInstance {},
	_0001_PaperNote_Vegas: class extends self.ISpriteInstance {},
	_0005_Layer_Vegas: class extends self.ISpriteInstance {},
	_0009_o__Vegas: class extends self.ISpriteInstance {},
	_0010_x__Vegas: class extends self.ISpriteInstance {},
	_0014_selectgamecount_Vegas: class extends self.ISpriteInstance {},
	_1PlayerButton_Vegas: class extends self.ISpriteInstance {},
	_2PlayerButton_Vegas: class extends self.ISpriteInstance {},
	Background_Vegas: class extends self.ITiledBackgroundInstance {},
	Border_Vegas: class extends self.ISpriteInstance {},
	Camera_Vegas: class extends self.ISpriteInstance {},
	Close_Vegas: class extends self.ISpriteInstance {},
	computer_Vegas: class extends self.ISpriteInstance {},
	dead_Vegas: class extends self.ISpriteInstance {},
	Default_Vegas: class extends self.ISpriteInstance {},
	Figure_Vegas: class extends self.ISpriteInstance {},
	game_bg_Vegas: class extends self.ISpriteInstance {},
	gc10_Vegas: class extends self.ISpriteInstance {},
	gc3_Vegas: class extends self.ISpriteInstance {},
	gc5_Vegas: class extends self.ISpriteInstance {},
	gc_x_Vegas: class extends self.ISpriteInstance {},
	ink_Vegas: class extends self.ISpriteInstance {},
	introtwporg_Vegas: class extends self.ISpriteInstance {},
	l1_Vegas: class extends self.ISpriteInstance {},
	l2_Vegas: class extends self.ISpriteInstance {},
	l3_Vegas: class extends self.ISpriteInstance {},
	l4_Vegas: class extends self.ISpriteInstance {},
	line2_Vegas: class extends self.ISpriteInstance {},
	line3_Vegas: class extends self.ISpriteInstance {},
	MenuButton2_Vegas: class extends self.ISpriteInstance {},
	MenuButton_Vegas: class extends self.ISpriteInstance {},
	more_games_Vegas: class extends self.ISpriteInstance {},
	o1_Vegas: class extends self.ISpriteInstance {},
	o2_Vegas: class extends self.ISpriteInstance {},
	o3_Vegas: class extends self.ISpriteInstance {},
	o4_Vegas: class extends self.ISpriteInstance {},
	o5_Vegas: class extends self.ISpriteInstance {},
	o6_Vegas: class extends self.ISpriteInstance {},
	o7_Vegas: class extends self.ISpriteInstance {},
	o8_Vegas: class extends self.ISpriteInstance {},
	o9_Vegas: class extends self.ISpriteInstance {},
	oo2_Vegas: class extends self.ISpriteInstance {},
	oo3_Vegas: class extends self.ISpriteInstance {},
	oo4_Vegas: class extends self.ISpriteInstance {},
	oo5_Vegas: class extends self.ISpriteInstance {},
	oo6_Vegas: class extends self.ISpriteInstance {},
	oo7_Vegas: class extends self.ISpriteInstance {},
	oo8_Vegas: class extends self.ISpriteInstance {},
	oo9_Vegas: class extends self.ISpriteInstance {},
	oscore_Vegas: class extends self.ISpriteInstance {},
	owinner_Vegas: class extends self.ISpriteInstance {},
	ox1_Vegas: class extends self.ISpriteInstance {},
	ox2_Vegas: class extends self.ISpriteInstance {},
	ox3_Vegas: class extends self.ISpriteInstance {},
	ox4_Vegas: class extends self.ISpriteInstance {},
	ox5_Vegas: class extends self.ISpriteInstance {},
	ox6_Vegas: class extends self.ISpriteInstance {},
	ox7_Vegas: class extends self.ISpriteInstance {},
	ox8_Vegas: class extends self.ISpriteInstance {},
	ox9_Vegas: class extends self.ISpriteInstance {},
	Particles2_Vegas: class extends self.IParticlesInstance {},
	Particles3_Vegas: class extends self.IParticlesInstance {},
	Particles4_Vegas: class extends self.IParticlesInstance {},
	Particles_Vegas: class extends self.IParticlesInstance {},
	play_again_Vegas: class extends self.ISpriteInstance {},
	play_intro_btn_Vegas: class extends self.ISpriteInstance {},
	Player1_Vegas: class extends self.ITextInstance {},
	Player2_Vegas: class extends self.ITextInstance {},
	playy_Vegas: class extends self.ISpriteInstance {},
	Score_Vegas: class extends self.ITextInstance {},
	Sound_Vegas: class extends self.ISpriteInstance {},
	Soundb_Vegas: class extends self.ISpriteInstance {},
	Sprite3_Vegas: class extends self.ISpriteInstance {},
	Sprite5_Vegas: class extends self.ISpriteInstance {},
	Sprite_Vegas: class extends self.ISpriteInstance {},
	stone_Vegas: class extends self.ISpriteInstance {},
	TicTac2_Vegas: class extends self.ISpriteInstance {},
	TicTac_Vegas: class extends self.ISpriteInstance {},
	twplogo2_Vegas: class extends self.ISpriteInstance {},
	twplogo_Vegas: class extends self.ISpriteInstance {},
	Untitled2_Vegas: class extends self.ISpriteInstance {},
	vin_o_Vegas: class extends self.ISpriteInstance {},
	vinx_Vegas: class extends self.ISpriteInstance {},
	winbgboard_Vegas: class extends self.ISpriteInstance {},
	windestroy_o_Vegas: class extends self.ISpriteInstance {},
	windestroy_x_Vegas: class extends self.ISpriteInstance {},
	winner_wood_Vegas: class extends self.ISpriteInstance {},
	winnerbg_Vegas: class extends self.ISpriteInstance {},
	x1_Vegas: class extends self.ISpriteInstance {},
	x2_Vegas: class extends self.ISpriteInstance {},
	x3_Vegas: class extends self.ISpriteInstance {},
	x4_Vegas: class extends self.ISpriteInstance {},
	x5_Vegas: class extends self.ISpriteInstance {},
	x6_Vegas: class extends self.ISpriteInstance {},
	x7_Vegas: class extends self.ISpriteInstance {},
	x8_Vegas: class extends self.ISpriteInstance {},
	x9_Vegas: class extends self.ISpriteInstance {},
	xscore_Vegas: class extends self.ISpriteInstance {},
	xwinner_Vegas: class extends self.ISpriteInstance {},
	xx1_Vegas: class extends self.ISpriteInstance {},
	xx2_Vegas: class extends self.ISpriteInstance {},
	xx3_Vegas: class extends self.ISpriteInstance {},
	xx4_Vegas: class extends self.ISpriteInstance {},
	xx5_Vegas: class extends self.ISpriteInstance {},
	xx6_Vegas: class extends self.ISpriteInstance {},
	xx7_Vegas: class extends self.ISpriteInstance {},
	xx8_Vegas: class extends self.ISpriteInstance {},
	xx9_Vegas: class extends self.ISpriteInstance {},
	xxx2_Vegas: class extends self.ISpriteInstance {},
	xxx3_Vegas: class extends self.ISpriteInstance {},
	xxx4_Vegas: class extends self.ISpriteInstance {},
	xxx5_Vegas: class extends self.ISpriteInstance {},
	xxx6_Vegas: class extends self.ISpriteInstance {},
	xxx7_Vegas: class extends self.ISpriteInstance {},
	xxx8_Vegas: class extends self.ISpriteInstance {},
	xxx9_Vegas: class extends self.ISpriteInstance {},
	you_Vegas: class extends self.ISpriteInstance {},
	zem1_Vegas: class extends self.ISpriteInstance {},
	zem_Vegas: class extends self.ISpriteInstance {},
	ArrayX_Vegas: class extends self.IArrayInstance {},
	ArrayY_Vegas: class extends self.IArrayInstance {},
	ArrayZ_Vegas: class extends self.IArrayInstance {},
	Background2_Vegas: class extends self.ITiledBackgroundInstance {},
	Facebook: class extends self.IInstance {},
	pplay_Vegas: class extends self.ISpriteInstance {},
	Sprite2_Vegas: class extends self.ISpriteInstance {},
	X_TURN: class extends self.ISpriteInstance {},
	O_TURN: class extends self.ISpriteInstance {},
	balon_camera: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	main_left_arrow: class extends self.ISpriteInstance {},
	main_right_arrow: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	game_name: class extends self.ITextInstance {},
	game_name2: class extends self.ITextInstance {},
	Main_Left_Scr: class extends self.ITextInstance {},
	Main_Right_Scr: class extends self.ITextInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	m_title_2p: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	m_title_choose: class extends self.ISpriteInstance {},
	m_title_1p: class extends self.ISpriteInstance {},
	Video2: class extends self.IWorldInstance {},
	kazik_seesaw: class extends self.ISpriteInstance {},
	resetscorebutton: class extends self.ITextInstance {},
	backbutton: class extends self.ITextInstance {},
	sound_on_off: class extends self.ITextInstance {},
	ikon_vagon: class extends self.ISpriteInstance {},
	mercek: class extends self.ISpriteInstance {},
	backgraund: class extends self.ISpriteInstance {},
	monitor: class extends self.ISpriteInstance {},
	score: class extends self.ISpriteInstance {},
	Layer2copy: class extends self.ISpriteInstance {},
	main_playbtn: class extends self.ISpriteInstance {},
	main_homebtn: class extends self.ISpriteInstance {},
	main_sound_off: class extends self.ISpriteInstance {},
	main_reset: class extends self.ISpriteInstance {},
	main_tttvegass: class extends self.ISpriteInstance {},
	main_seesawballl: class extends self.ISpriteInstance {},
	main_getontopp: class extends self.ISpriteInstance {},
	main_medievall: class extends self.ISpriteInstance {},
	main_drunkenduel: class extends self.ISpriteInstance {},
	main_tugtheetablee: class extends self.ISpriteInstance {},
	main_milkthecov: class extends self.ISpriteInstance {},
	choosgameicon: class extends self.ISpriteInstance {},
	seesawduvar: class extends self.ISpriteInstance {},
	filee2: class extends self.ISpriteInstance {},
	pota: class extends self.ISpriteInstance {},
	filee: class extends self.ISpriteInstance {},
	ustpota: class extends self.ISpriteInstance {},
	redyay: class extends self.ISpriteInstance {},
	maviyay: class extends self.ISpriteInstance {},
	main_pbtn1: class extends self.ISpriteInstance {},
	main_pbtn2: class extends self.ISpriteInstance {},
	main_moregames: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	backgraund2: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	mode: class extends self.ISpriteInstance {},
	challenge_text: class extends self.ITextInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	challenge_right_arrow: class extends self.ISpriteInstance {},
	challenge_left_arrow: class extends self.ISpriteInstance {},
	dil: class extends self.ISpriteInstance {},
	language_text: class extends self.ITextInstance {},
	menu_popup: class extends self.ISpriteInstance {},
	yes: class extends self.ISpriteInstance {},
	no: class extends self.ISpriteInstance {},
	Menu_Text: class extends self.ITextInstance {},
	yess: class extends self.ITextInstance {},
	noo: class extends self.ITextInstance {},
	menu_popup2: class extends self.ISpriteInstance {},
	l11: class extends self.ISpriteInstance {},
	l2: class extends self.ISpriteInstance {},
	l0: class extends self.ISpriteInstance {},
	l1: class extends self.ISpriteInstance {},
	l3: class extends self.ISpriteInstance {},
	l4: class extends self.ISpriteInstance {},
	l5: class extends self.ISpriteInstance {},
	l6: class extends self.ISpriteInstance {},
	l7: class extends self.ISpriteInstance {},
	l8: class extends self.ISpriteInstance {},
	l10: class extends self.ISpriteInstance {},
	l9: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	x: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	WeeGooSDK: class extends self.IInstance {},
	govdeler: class extends self.ISpriteInstance {},
	guns: class extends self.ISpriteInstance {},
	govdebg: class extends self.ISpriteInstance {},
	blueman: class extends self.ISpriteInstance {},
	orangeman: class extends self.ISpriteInstance {},
	Family1: class extends self.ISpriteInstance {},
	lamb: class extends self.ISpriteInstance {},
	destroy: class extends self.ISpriteInstance {},
	sag_bg: class extends self.ISpriteInstance {},
	sol_bg: class extends self.ISpriteInstance {},
	Family2: class extends self.ISpriteInstance {},
	winnerfade: class extends self.ISpriteInstance {},
	vinbuton: class extends self.ISpriteInstance {},
	yapayzekahedef: class extends self.ISpriteInstance {},
	sagkollar_box: class extends self.ISpriteInstance {},
	sag_box: class extends self.ISpriteInstance {},
	sag_2_uzuv_box: class extends self.ISpriteInstance {},
	Family1_table: class extends self.ISpriteInstance {},
	golge_table: class extends self.ISpriteInstance {},
	insivible_table: class extends self.ISpriteInstance {},
	anchor_table: class extends self.ISpriteInstance {},
	tween_table: class extends self.ISpriteInstance {},
	add_table: class extends self.ISpriteInstance {},
	winspanel_table: class extends self.ISpriteInstance {},
	blueman_table: class extends self.ISpriteInstance {},
	orangeman_table: class extends self.ISpriteInstance {},
	button_table: class extends self.ISpriteInstance {},
	bluefizik_Medieval: class extends self.ISpriteInstance {},
	bluearac_Medieval: class extends self.ISpriteInstance {},
	orangefizik_Medieval: class extends self.ISpriteInstance {},
	orangearac_Medieval: class extends self.ISpriteInstance {},
	blueman_Medieval: class extends self.ISpriteInstance {},
	orangeman_Medieval: class extends self.ISpriteInstance {},
	enerjieleman_Medieval: class extends self.ISpriteInstance {},
	anchorr_Medieval: class extends self.ISpriteInstance {},
	winseleman_Medieval: class extends self.ISpriteInstance {},
	cursor_Medieval: class extends self.ISpriteInstance {},
	playeleman_Medieval: class extends self.ISpriteInstance {},
	touchbutton_Medieval: class extends self.ISpriteInstance {},
	webhtp_Medieval: class extends self.ISpriteInstance {},
	exgun_Medieval: class extends self.ISpriteInstance {},
	touchbutton_Getontop: class extends self.ISpriteInstance {},
	insivible_Getontop: class extends self.ISpriteInstance {},
	pins_Getontop: class extends self.ISpriteInstance {},
	cursor_Getontop: class extends self.ISpriteInstance {},
	lefteffect_Getontop: class extends self.ISpriteInstance {},
	wineffect_Getontop: class extends self.ISpriteInstance {},
	castpin_seesaw: class extends self.ISpriteInstance {},
	play_ball_seesaw: class extends self.ISpriteInstance {},
	pin_Cow: class extends self.ISpriteInstance {},
	add_button_Cow: class extends self.ISpriteInstance {},
	moregamesicon_Cow: class extends self.ISpriteInstance {},
	meme_Cow: class extends self.ISpriteInstance {},
	anchor_Cow: class extends self.ISpriteInstance {},
	dsaljk_Cow: class extends self.ISpriteInstance {},
	Family1_Cow: class extends self.ISpriteInstance {},
	sutbuton_Cow: class extends self.ISpriteInstance {},
	button_Cow: class extends self.ISpriteInstance {},
	buutton_balon: class extends self.ISpriteInstance {},
	Family2_D_duel_Two: class extends self.ISpriteInstance {},
	Pin_Vegas: class extends self.ISpriteInstance {},
	zems_Vegas: class extends self.ISpriteInstance {},
	Family2_Vegas: class extends self.ISpriteInstance {},
	xx_Vegas: class extends self.ISpriteInstance {},
	Family1_Vegas: class extends self.ISpriteInstance {},
	particle_Vegas: class extends self.IParticlesInstance {},
	button_Vegas: class extends self.ISpriteInstance {},
	ox_Vegas: class extends self.ISpriteInstance {},
	m_title_adjust: class extends self.ISpriteInstance {},
	main_buttonn: class extends self.ISpriteInstance {},
	challenge_button: class extends self.ISpriteInstance {},
	language: class extends self.ISpriteInstance {}
}