const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.scrollto,
		C3.Behaviors.Pin,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Behaviors.lunarray_LiteTween,
		C3.Plugins.Particles,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Platform,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Browser,
		C3.Plugins.WGSDK,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Physics.Acts.ApplyTorque,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Behaviors.Physics.Acts.ApplyForce,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.Touch.Cnds.OnDoubleTapGestureObject,
		C3.Plugins.LocalStorage.Cnds.OnAllGetsComplete,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Browser.Acts.GoToURL
	];
};
self.C3_JsPropNameTable = [
	{Physics: 0},
	{Ground: 0},
	{Text: 0},
	{BackWheel: 0},
	{Mouse: 0},
	{ScrollTo: 0},
	{CarBody: 0},
	{FrontWheel: 0},
	{Pin: 0},
	{Solid: 0},
	{Backtouch: 0},
	{Fronttouch: 0},
	{Keyboard: 0},
	{Ground2: 0},
	{kriva: 0},
	{okidac: 0},
	{oklop: 0},
	{Ground3: 0},
	{Body: 0},
	{Sine: 0},
	{Head: 0},
	{kapa: 0},
	{cilj: 0},
	{BG: 0},
	{zemlja: 0},
	{bomba: 0},
	{Sprite3: 0},
	{Sprite11: 0},
	{platforma: 0},
	{konfeti: 0},
	{Touch: 0},
	{drive: 0},
	{BestScoreFont: 0},
	{menu: 0},
	{BSound2: 0},
	{Audio: 0},
	{stop: 0},
	{LiteTween: 0},
	{dalje: 0},
	{ponovo: 0},
	{failed2: 0},
	{okvir: 0},
	{okvir2: 0},
	{Firework: 0},
	{diamond: 0},
	{ctd_score: 0},
	{txt_display_record: 0},
	{LocalStorage: 0},
	{ctd_score2: 0},
	{PuntosLabel: 0},
	{Mejor: 0},
	{txt_display_record2: 0},
	{Sprite: 0},
	{ruka: 0},
	{Sprite2: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{btn_games: 0},
	{ctd_score3: 0},
	{Platform: 0},
	{Fade: 0},
	{ponto_extra: 0},
	{bridge: 0},
	{Sprite6: 0},
	{TiledBackground4: 0},
	{AUTOHALLOWEEN: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{TiledBackground5: 0},
	{Sprite10: 0},
	{Sprite12: 0},
	{TiledBackground6: 0},
	{platformaudar: 0},
	{TiledBackground7: 0},
	{Sprite13: 0},
	{platformalet: 0},
	{box: 0},
	{Anchor: 0},
	{HomeButton: 0},
	{ShipSkin2: 0},
	{Open: 0},
	{Level: 0},
	{LevelsBlock: 0},
	{CoinsFont3: 0},
	{LevelsText: 0},
	{SpriteFont123: 0},
	{Sprite28: 0},
	{leveli: 0},
	{Sprite14: 0},
	{Rope3: 0},
	{Wheel1: 0},
	{Rope5: 0},
	{Rope0: 0},
	{Rope1: 0},
	{Rope6: 0},
	{Rope4: 0},
	{Rope2: 0},
	{Sprite27: 0},
	{pozadina: 0},
	{Fireworknove: 0},
	{zvijezda: 0},
	{masna: 0},
	{menu2: 0},
	{Sprite15: 0},
	{Browser: 0},
	{txt_display_record3: 0},
	{BG2: 0},
	{drive2: 0},
	{kovceg: 0},
	{Sprite17: 0},
	{replay: 0},
	{Sprite16: 0},
	{jaja: 0},
	{Sprite18: 0},
	{kutija: 0},
	{Sprite20: 0},
	{SemiRealFire2: 0},
	{Sprite7: 0},
	{Sprite19: 0},
	{logokrajisnici: 0},
	{jump: 0},
	{CoinsFont4: 0},
	{mis: 0},
	{TIPKOVNICA: 0},
	{skip: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{ToolTip: 0},
	{Snow: 0},
	{Sprite24: 0},
	{glavanjena: 0},
	{Sprite26: 0},
	{BSound3: 0},
	{leveli2: 0},
	{kapa2: 0},
	{Wheel2: 0},
	{Sprite21: 0},
	{Sprite25: 0},
	{WeeGooSDK: 0},
	{CarGame: 0},
	{obstacles: 0},
	{buttons: 0},
	{LAST_LEVEL: 0},
	{WIN: 0},
	{ClaveMejor: 0},
	{MejorPuntuacion: 0},
	{Puntuacion: 0},
	{sound: 0},
	{recorde: 0},
	{SoundEf: 0}
];

self.InstanceType = {
	Ground: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	BackWheel: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	CarBody: class extends self.ISpriteInstance {},
	FrontWheel: class extends self.ISpriteInstance {},
	Backtouch: class extends self.ISpriteInstance {},
	Fronttouch: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Ground2: class extends self.ISpriteInstance {},
	kriva: class extends self.ISpriteInstance {},
	okidac: class extends self.ISpriteInstance {},
	oklop: class extends self.ISpriteInstance {},
	Ground3: class extends self.ISpriteInstance {},
	Body: class extends self.ISpriteInstance {},
	Head: class extends self.ISpriteInstance {},
	kapa: class extends self.ISpriteInstance {},
	cilj: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	zemlja: class extends self.ISpriteInstance {},
	bomba: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	platforma: class extends self.ISpriteInstance {},
	konfeti: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	drive: class extends self.ISpriteInstance {},
	BestScoreFont: class extends self.ISpriteFontInstance {},
	menu: class extends self.ISpriteInstance {},
	BSound2: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	stop: class extends self.ISpriteInstance {},
	dalje: class extends self.ISpriteInstance {},
	ponovo: class extends self.ISpriteInstance {},
	failed2: class extends self.ISpriteInstance {},
	okvir: class extends self.ISpriteInstance {},
	okvir2: class extends self.ISpriteInstance {},
	Firework: class extends self.IParticlesInstance {},
	diamond: class extends self.ISpriteInstance {},
	ctd_score: class extends self.ISpriteFontInstance {},
	txt_display_record: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	ctd_score2: class extends self.ISpriteFontInstance {},
	PuntosLabel: class extends self.ITextInstance {},
	Mejor: class extends self.ITextInstance {},
	txt_display_record2: class extends self.ISpriteFontInstance {},
	Sprite: class extends self.ISpriteInstance {},
	ruka: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	btn_games: class extends self.ISpriteInstance {},
	ctd_score3: class extends self.ISpriteFontInstance {},
	ponto_extra: class extends self.ISpriteFontInstance {},
	bridge: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	AUTOHALLOWEEN: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	platformaudar: class extends self.ISpriteInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	platformalet: class extends self.ISpriteInstance {},
	box: class extends self.ITiledBackgroundInstance {},
	HomeButton: class extends self.ISpriteInstance {},
	ShipSkin2: class extends self.ISpriteInstance {},
	LevelsBlock: class extends self.ISpriteInstance {},
	CoinsFont3: class extends self.ISpriteFontInstance {},
	LevelsText: class extends self.ISpriteFontInstance {},
	SpriteFont123: class extends self.ISpriteFontInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	leveli: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Rope3: class extends self.ISpriteInstance {},
	Wheel1: class extends self.ISpriteInstance {},
	Rope5: class extends self.ISpriteInstance {},
	Rope0: class extends self.ISpriteInstance {},
	Rope1: class extends self.ISpriteInstance {},
	Rope6: class extends self.ISpriteInstance {},
	Rope4: class extends self.ISpriteInstance {},
	Rope2: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	pozadina: class extends self.ISpriteInstance {},
	Fireworknove: class extends self.IParticlesInstance {},
	zvijezda: class extends self.ISpriteInstance {},
	masna: class extends self.ISpriteInstance {},
	menu2: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	txt_display_record3: class extends self.ISpriteFontInstance {},
	BG2: class extends self.ISpriteInstance {},
	drive2: class extends self.ISpriteInstance {},
	kovceg: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	replay: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	jaja: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	kutija: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	SemiRealFire2: class extends self.IParticlesInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	logokrajisnici: class extends self.ISpriteInstance {},
	jump: class extends self.ISpriteInstance {},
	CoinsFont4: class extends self.ISpriteFontInstance {},
	mis: class extends self.ISpriteInstance {},
	TIPKOVNICA: class extends self.ISpriteInstance {},
	skip: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Snow: class extends self.IParticlesInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	glavanjena: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	BSound3: class extends self.ISpriteInstance {},
	leveli2: class extends self.ISpriteInstance {},
	kapa2: class extends self.ISpriteInstance {},
	Wheel2: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends C3.Plugins.WGSDK.Instance {},
	CarGame: class extends self.ISpriteInstance {},
	obstacles: class extends self.ISpriteInstance {},
	buttons: class extends self.ISpriteInstance {}
}