const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Behaviors.scrollto,
		C3.Plugins.Particles,
		C3.Behaviors.MoveTo,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Plugins.PlatformInfo,
		C3.Plugins.ppstudio_ga4,
		C3.Plugins.WGSDK,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.ppstudio_ga4.Acts.GASendEvent,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.ppstudio_ga4.Acts.InitGA,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Arr.Exps.At,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.PickAll,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.zeropad,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Acts.ToggleBoolVar
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{bear: 0},
	{gameplay_bg: 0},
	{level_selection: 0},
	{level_selection_bg: 0},
	{main_menu_bg: 0},
	{Rotate: 0},
	{Sine: 0},
	{Sine2: 0},
	{Confetti: 0},
	{shape_bar: 0},
	{ScrollTo: 0},
	{shake: 0},
	{bg: 0},
	{Particles: 0},
	{LevelNo: 0},
	{Sprite: 0},
	{home: 0},
	{levelNo: 0},
	{level_ui: 0},
	{life: 0},
	{lockedNo: 0},
	{locked: 0},
	{music: 0},
	{L: 0},
	{next: 0},
	{nextLevel: 0},
	{positionX: 0},
	{match: 0},
	{MoveTo: 0},
	{DragDrop: 0},
	{obj: 0},
	{isOccupied: 0},
	{place: 0},
	{play: 0},
	{retry: 0},
	{sound: 0},
	{try_again_text: 0},
	{Tum_BoatArtboard: 0},
	{win_screen: 0},
	{Title: 0},
	{Touch: 0},
	{Audio: 0},
	{levelText: 0},
	{lifeText: 0},
	{Text: 0},
	{forX: 0},
	{spUID: 0},
	{Browser: 0},
	{PlatformInfo: 0},
	{GA4: 0},
	{WeeGooSDK: 0},
	{levelsUnlocked: 0},
	{spriteArrayindex: 0},
	{level: 0}
];

self.InstanceType = {
	bear: class extends self.ISpriteInstance {},
	gameplay_bg: class extends self.ISpriteInstance {},
	level_selection: class extends self.ISpriteInstance {},
	level_selection_bg: class extends self.ISpriteInstance {},
	main_menu_bg: class extends self.ISpriteInstance {},
	Confetti: class extends self.ISpriteInstance {},
	shape_bar: class extends self.ISpriteInstance {},
	shake: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Sprite: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	level_ui: class extends self.ISpriteInstance {},
	life: class extends self.ISpriteInstance {},
	locked: class extends self.ISpriteInstance {},
	music: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	nextLevel: class extends self.ISpriteInstance {},
	obj: class extends self.ISpriteInstance {},
	place: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	retry: class extends self.ISpriteInstance {},
	sound: class extends self.ISpriteInstance {},
	try_again_text: class extends self.ISpriteInstance {},
	Tum_BoatArtboard: class extends self.ISpriteInstance {},
	win_screen: class extends self.ISpriteInstance {},
	Title: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	levelText: class extends self.ITextInstance {},
	lifeText: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	forX: class extends self.IArrayInstance {},
	spUID: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	GA4: class extends self.IInstance {},
	WeeGooSDK: class extends self.IInstance {}
}