const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Physics,
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Behaviors.bound,
		C3.Plugins.Button,
		C3.Behaviors.Anchor,
		C3.Plugins.LocalStorage,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStart,
		C3.Behaviors.Physics.Acts.SetIterations,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStop,
		C3.Plugins.Eponesh_GameScore.Acts.GamesCollectionsOpen,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.Plugins.Eponesh_GameScore.Acts.ChangeLanguage,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing
	];
};
self.C3_JsPropNameTable = [
	{Physics: 0},
	{Ground: 0},
	{Box1: 0},
	{Text: 0},
	{Pig: 0},
	{Touch: 0},
	{CatapultBlock: 0},
	{Block: 0},
	{lvl: 0},
	{BoundToLayout: 0},
	{Sprite: 0},
	{RestartButton: 0},
	{Anchor: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Box2: 0},
	{TiledBackground: 0},
	{LocalStorage: 0},
	{GamePush: 0},
	{Text2: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Mouse: 0},
	{IsAiming: 0},
	{Level: 0},
	{timer: 0}
];

self.InstanceType = {
	Ground: class extends self.ITiledBackgroundInstance {},
	Box1: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Pig: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	CatapultBlock: class extends self.ISpriteInstance {},
	Block: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	RestartButton: class extends self.IButtonInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Box2: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	LocalStorage: class extends self.IInstance {},
	GamePush: class extends self.C3.Plugins.Eponesh_GameScore.Instance {},
	Text2: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {}
}