const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.AJAX,
		C3.Plugins.Audio,
		C3.Plugins.Share,
		C3.Plugins.BinaryData,
		C3.Plugins.Browser,
		C3.Plugins.Date,
		C3.Plugins.Arr,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Date.Exps.ExportTimestamp,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgba255,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.WGSDK.Cnds.RewardGranted,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{Easy: 0},
	{Hard: 0},
	{Medium: 0},
	{Touch: 0},
	{AJAX: 0},
	{Audio: 0},
	{Share: 0},
	{BinaryData: 0},
	{Browser: 0},
	{Date: 0},
	{Random_Number_Array: 0},
	{Array: 0},
	{Gif_Animation_Text: 0},
	{"3_Options_Array": 0},
	{Star: 0},
	{Star_Particles: 0},
	{Sound: 0},
	{Sine: 0},
	{Sine2: 0},
	{Play: 0},
	{Btn_50_50: 0},
	{Home_G_Btn: 0},
	{Leader_board_Small: 0},
	{Leaderboard_Btn: 0},
	{HomeBtn2: 0},
	{btn_more: 0},
	{Tween: 0},
	{Liloandstitch: 0},
	{Quiz: 0},
	{Challenge: 0},
	{BackPad: 0},
	{Background: 0},
	{Black_Trans: 0},
	{Trans_Mask: 0},
	{Level_Question: 0},
	{answers: 0},
	{Options_Text: 0},
	{Out_of_Totall_Qus: 0},
	{Out_of: 0},
	{Score_Text: 0},
	{Total_Qust_Text: 0},
	{Correct_Ans_Text: 0},
	{Time_Text: 0},
	{Time_Gplay_Txt: 0},
	{Total_Qus_Text: 0},
	{Default_Y: 0},
	{Y_Tween: 0},
	{Main_Image: 0},
	{Option_Order: 0},
	{Can_Click: 0},
	{Option: 0},
	{Comments_Text: 0},
	{Final_Score_Text: 0},
	{Reload: 0},
	{ScoreBoard: 0},
	{Share2: 0},
	{Correct: 0},
	{UI_Pad: 0},
	{Text: 0},
	{Black: 0},
	{Reload_Btn: 0},
	{SpriteFont: 0},
	{Loader2_bottom: 0},
	{Loader2TOp: 0},
	{Fx: 0},
	{Summit_Score_UI: 0},
	{Online_Save: 0},
	{Local_Save: 0},
	{Tint: 0},
	{Title_Country: 0},
	{WeeGooSDK: 0},
	{Clickable: 0},
	{newFam: 0},
	{Max_Question: 0},
	{Array_Height: 0},
	{Answer_Option: 0},
	{Tween_T: 0},
	{Dummy_Score: 0},
	{First_time_Load: 0},
	{Y8_pop_Up: 0},
	{mute: 0},
	{Show_Ad: 0},
	{Total_Question: 0},
	{Tween_Time: 0},
	{Random_N: 0},
	{Set_Frame: 0},
	{Question_Count: 0},
	{Correct_Answers: 0},
	{Start_Time_Stamp: 0},
	{time_Count: 0},
	{"50_50": 0},
	{Card_Count: 0}
];

self.InstanceType = {
	Easy: class extends self.ISpriteInstance {},
	Hard: class extends self.ISpriteInstance {},
	Medium: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Share: class extends self.IInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	Browser: class extends self.IInstance {},
	Date: class extends self.IInstance {},
	Random_Number_Array: class extends self.IArrayInstance {},
	Array: class extends self.IArrayInstance {},
	Gif_Animation_Text: class extends self.IArrayInstance {},
	_3_Options_Array: class extends self.IArrayInstance {},
	Star: class extends self.ISpriteInstance {},
	Star_Particles: class extends self.IParticlesInstance {},
	Sound: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	Btn_50_50: class extends self.ISpriteInstance {},
	Home_G_Btn: class extends self.ISpriteInstance {},
	Leader_board_Small: class extends self.ISpriteInstance {},
	Leaderboard_Btn: class extends self.ISpriteInstance {},
	HomeBtn2: class extends self.ISpriteInstance {},
	btn_more: class extends self.ISpriteInstance {},
	Liloandstitch: class extends self.ISpriteInstance {},
	Quiz: class extends self.ISpriteInstance {},
	Challenge: class extends self.ISpriteInstance {},
	BackPad: class extends self.ISpriteInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	Black_Trans: class extends self.ISpriteInstance {},
	Trans_Mask: class extends self.ISpriteInstance {},
	Level_Question: class extends self.ISpriteFontInstance {},
	Options_Text: class extends self.ISpriteFontInstance {},
	Out_of_Totall_Qus: class extends self.ISpriteFontInstance {},
	Out_of: class extends self.ISpriteFontInstance {},
	Score_Text: class extends self.ISpriteFontInstance {},
	Total_Qust_Text: class extends self.ISpriteFontInstance {},
	Correct_Ans_Text: class extends self.ISpriteFontInstance {},
	Time_Text: class extends self.ISpriteFontInstance {},
	Time_Gplay_Txt: class extends self.ISpriteFontInstance {},
	Total_Qus_Text: class extends self.ISpriteFontInstance {},
	Main_Image: class extends self.ISpriteInstance {},
	Option: class extends self.ISpriteInstance {},
	Comments_Text: class extends self.ISpriteFontInstance {},
	Final_Score_Text: class extends self.ISpriteFontInstance {},
	Reload: class extends self.ISpriteInstance {},
	ScoreBoard: class extends self.ISpriteInstance {},
	Share2: class extends self.ISpriteInstance {},
	Correct: class extends self.ISpriteInstance {},
	UI_Pad: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Black: class extends self.ISpriteInstance {},
	Reload_Btn: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Loader2_bottom: class extends self.ISpriteInstance {},
	Loader2TOp: class extends self.ISpriteInstance {},
	Fx: class extends self.IParticlesInstance {},
	Summit_Score_UI: class extends self.ISpriteInstance {},
	Online_Save: class extends self.ISpriteInstance {},
	Local_Save: class extends self.ISpriteInstance {},
	Tint: class extends self.ISpriteInstance {},
	Title_Country: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	Clickable: class extends self.ISpriteInstance {},
	newFam: class extends self.ISpriteInstance {}
}