const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Behaviors.jumpthru,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Pin,
		C3.Behaviors.wrap,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Plugins.LocalStorage,
		C3.Plugins.Particles,
		C3.Plugins.gamepad,
		C3.Plugins.Browser,
		C3.Plugins.WGSDK,
		C3.Behaviors.Rotate,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Tween,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Exps.len,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Platform.Acts.SetMaxFallSpeed,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.CompareAnimSpeed,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.TiledBg.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Platform.Acts.SetGravityAngle,
		C3.Behaviors.Platform.Exps.GravityAngle,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.jumpthru.Acts.SetEnabled,
		C3.Behaviors.solid.Cnds.IsEnabled,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Behaviors.jumpthru.Cnds.IsEnabled,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Acts.SetX,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Tilemap.Acts.SetX,
		C3.Plugins.Tilemap.Exps.X,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.Tilemap.Cnds.CompareX,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnAnyItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.WGSDK.Cnds.RewardReady,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.WGSDK.Cnds.RewardClosed
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Tilemap1: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Flash: 0},
	{Player: 0},
	{Keyboard: 0},
	{BG: 0},
	{LIVE: 0},
	{Mushroom: 0},
	{BG2: 0},
	{BG3: 0},
	{Tilemap1Mask: 0},
	{position1: 0},
	{falling: 0},
	{Bullet: 0},
	{Sine: 0},
	{Fan: 0},
	{Jumpthru: 0},
	{Blink: 0},
	{saw: 0},
	{Spikes: 0},
	{thing_: 0},
	{Rope: 0},
	{button: 0},
	{bridge: 0},
	{BOX: 0},
	{Var: 0},
	{BOX2: 0},
	{breakBox11: 0},
	{breakBox12: 0},
	{breakBox13: 0},
	{breakBox14: 0},
	{boxCollision: 0},
	{Apple: 0},
	{Collected: 0},
	{Rabbit: 0},
	{RinoN: 0},
	{Rino: 0},
	{DorY: 0},
	{Dor: 0},
	{bird1: 0},
	{Va: 0},
	{pipe: 0},
	{box2Collision: 0},
	{end: 0},
	{Pin: 0},
	{LEVELtext: 0},
	{WaterBall: 0},
	{angl: 0},
	{Wrap: 0},
	{BrownOff: 0},
	{grav: 0},
	{SpikeHead: 0},
	{direction: 0},
	{arrow: 0},
	{Touch: 0},
	{start: 0},
	{Tittle: 0},
	{Audio: 0},
	{move_left_right: 0},
	{move_jump: 0},
	{Spring: 0},
	{levelIcon: 0},
	{Red_Diamond: 0},
	{arrow_jump: 0},
	{home: 0},
	{pause: 0},
	{next: 0},
	{play: 0},
	{restart: 0},
	{TiledBackground: 0},
	{Apple2: 0},
	{Array: 0},
	{LocalStorage: 0},
	{Particles2: 0},
	{Particles: 0},
	{levelN: 0},
	{water: 0},
	{water0: 0},
	{setting: 0},
	{music_volume: 0},
	{sound_volume: 0},
	{transfer_effect: 0},
	{health: 0},
	{Heart: 0},
	{Gamepad: 0},
	{moregames: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{playad: 0},
	{touchad: 0},
	{Browser: 0},
	{WeeGooSDK: 0},
	{Rotate: 0},
	{Enemies: 0},
	{Tilesets: 0},
	{Traps: 0},
	{BOXS: 0},
	{breakBox1: 0},
	{Items: 0},
	{Pathfinding: 0},
	{birds: 0},
	{GUI: 0},
	{Tween: 0},
	{volume: 0},
	{Timer: 0},
	{player_health: 0},
	{screen_width: 0},
	{screen_height: 0},
	{score: 0},
	{WIN: 0},
	{LEVEL: 0},
	{wait: 0},
	{openedLevels: 0}
];

self.InstanceType = {
	Tilemap1: class extends self.ITilemapInstance {},
	Player: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	BG: class extends self.ITiledBackgroundInstance {},
	Mushroom: class extends self.ISpriteInstance {},
	BG2: class extends self.ITiledBackgroundInstance {},
	BG3: class extends self.ITiledBackgroundInstance {},
	Tilemap1Mask: class extends self.ITiledBackgroundInstance {},
	Fan: class extends self.ISpriteInstance {},
	Blink: class extends self.ISpriteInstance {},
	saw: class extends self.ISpriteInstance {},
	Spikes: class extends self.ITiledBackgroundInstance {},
	thing_: class extends self.ISpriteInstance {},
	Rope: class extends self.ITiledBackgroundInstance {},
	button: class extends self.ISpriteInstance {},
	bridge: class extends self.ISpriteInstance {},
	BOX: class extends self.ISpriteInstance {},
	BOX2: class extends self.ISpriteInstance {},
	breakBox11: class extends self.ISpriteInstance {},
	breakBox12: class extends self.ISpriteInstance {},
	breakBox13: class extends self.ISpriteInstance {},
	breakBox14: class extends self.ISpriteInstance {},
	boxCollision: class extends self.ISpriteInstance {},
	Apple: class extends self.ISpriteInstance {},
	Collected: class extends self.ISpriteInstance {},
	Rabbit: class extends self.ISpriteInstance {},
	Rino: class extends self.ISpriteInstance {},
	Dor: class extends self.ISpriteInstance {},
	bird1: class extends self.ISpriteInstance {},
	pipe: class extends self.ISpriteInstance {},
	box2Collision: class extends self.ISpriteInstance {},
	end: class extends self.ISpriteInstance {},
	LEVELtext: class extends self.ISpriteFontInstance {},
	WaterBall: class extends self.ISpriteInstance {},
	BrownOff: class extends self.ISpriteInstance {},
	SpikeHead: class extends self.ISpriteInstance {},
	arrow: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	start: class extends self.ISpriteInstance {},
	Tittle: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	move_left_right: class extends self.ITiledBackgroundInstance {},
	move_jump: class extends self.ITiledBackgroundInstance {},
	Spring: class extends self.ISpriteInstance {},
	levelIcon: class extends self.ISpriteInstance {},
	Red_Diamond: class extends self.ISpriteInstance {},
	arrow_jump: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	pause: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	restart: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Apple2: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	LocalStorage: class extends self.IInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Particles: class extends self.IParticlesInstance {},
	levelN: class extends self.ISpriteInstance {},
	water: class extends self.ISpriteInstance {},
	water0: class extends self.ITiledBackgroundInstance {},
	setting: class extends self.ISpriteInstance {},
	music_volume: class extends self.ISpriteInstance {},
	sound_volume: class extends self.ISpriteInstance {},
	transfer_effect: class extends self.ISpriteInstance {},
	Heart: class extends self.ISpriteInstance {},
	Gamepad: class extends self.IInstance {},
	moregames: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	playad: class extends self.ISpriteInstance {},
	touchad: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	WeeGooSDK: class extends self.IInstance {},
	Enemies: class extends self.ISpriteInstance {},
	Tilesets: class extends self.ITilemapInstance {},
	Traps: class extends self.ISpriteInstance {},
	BOXS: class extends self.ISpriteInstance {},
	breakBox1: class extends self.ISpriteInstance {},
	Items: class extends self.ISpriteInstance {},
	birds: class extends self.ISpriteInstance {},
	GUI: class extends self.ISpriteInstance {},
	volume: class extends self.ISpriteInstance {}
}