const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.destroy,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Behaviors.Anchor,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Fade,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStart,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.TextBox.Acts.AppendText,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.System.Acts.SetLayerBackground,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStop,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsInvite,
		C3.Plugins.Eponesh_GameScore.Cnds.PaymentsPickProduct,
		C3.Plugins.Eponesh_GameScore.Exps.PaymentsCurProductPrice,
		C3.Plugins.Eponesh_GameScore.Exps.PaymentsCurProductCurrencySymbol,
		C3.Plugins.Eponesh_GameScore.Cnds.PaymentsIsPurchased,
		C3.Plugins.Eponesh_GameScore.Acts.PaymentsPurchase
	];
};
self.C3_JsPropNameTable = [
	{TextInput: 0},
	{Button: 0},
	{Touch: 0},
	{Physics: 0},
	{DestroyOutsideLayout: 0},
	{DragDrop: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{hp: 0},
	{Solid: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{BoundToLayout: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Bullet: 0},
	{Sprite11: 0},
	{CONTROL: 0},
	{Sprite12: 0},
	{Keyboard: 0},
	{Anchor: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Pathfinding: 0},
	{Fade: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{PlatformInfo: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Text: 0},
	{TiledBackground: 0},
	{slovar: 0},
	{Text2: 0},
	{premium: 0},
	{Sprite25: 0},
	{GamePush: 0},
	{buypremium: 0},
	{LocalStorage: 0},
	{start: 0},
	{start_map: 0},
	{FREND: 0},
	{Sprite26: 0},
	{Text3: 0},
	{blocks: 0},
	{Family1: 0},
	{tnt: 0}
];

self.InstanceType = {
	TextInput: class extends self.ITextInputInstance {},
	Button: class extends self.IButtonInstance {},
	Touch: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	slovar: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	premium: class extends self.ITextInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	GamePush: class extends self.C3.Plugins.Eponesh_GameScore.Instance {},
	buypremium: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	start: class extends self.ITextInstance {},
	start_map: class extends self.ITextInstance {},
	FREND: class extends self.ITextInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	blocks: class extends self.ISpriteInstance {},
	Family1: class extends self.ISpriteInstance {}
}