const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Behaviors.LOS,
		C3.Behaviors.MoveTo,
		C3.Plugins.Camera3D,
		C3.Plugins.Shape3D,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.skymen_smartJoystick,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Audio,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.skymen_smartJoystick.Acts.BindHandle,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.skymen_smartJoystick.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.skymen_smartJoystick.Cnds.IsDragging,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.skymen_smartJoystick.Exps.JoystickDirX,
		C3.Plugins.skymen_smartJoystick.Exps.JoystickDirY,
		C3.Plugins.skymen_smartJoystick.Exps.JoystickDistance,
		C3.Behaviors.EightDir.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.WGSDK.Cnds.RewardGranted
	];
};
self.C3_JsPropNameTable = [
	{Health: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{Player: 0},
	{Pin: 0},
	{Gun: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Bullet: 0},
	{Ammo: 0},
	{Aim: 0},
	{attack: 0},
	{Sine: 0},
	{LineOfSight: 0},
	{MoveTo: 0},
	{Sine2: 0},
	{SkibidiToiletEnemy1: 0},
	{"3DCamera": 0},
	{Solid: 0},
	{"3DShape": 0},
	{icon: 0},
	{HealthBar: 0},
	{Home: 0},
	{binaaaa: 0},
	{maxhit: 0},
	{shadow: 0},
	{AmmoText: 0},
	{ammoicon: 0},
	{ammopack: 0},
	{healthpack: 0},
	{BossFightEtkl: 0},
	{Attack: 0},
	{Boss1: 0},
	{HealthBar2: 0},
	{Boss1Health: 0},
	{Skibibiditoilet: 0},
	{SkibidiToiletEnemy2: 0},
	{Boss2: 0},
	{dark: 0},
	{Text: 0},
	{MenuETKL: 0},
	{Skibibiditoilet2: 0},
	{SkibidiToiletEnemy3: 0},
	{Ammo2: 0},
	{Boss3: 0},
	{SkibidiToiletEnemy4: 0},
	{Boss4: 0},
	{SkibidiToiletEnemy5: 0},
	{Boss5: 0},
	{Player2: 0},
	{ToiletIcon: 0},
	{dark2: 0},
	{ammopack2: 0},
	{healthpack2: 0},
	{OwnerText: 0},
	{dark3: 0},
	{Skibibiditoilet3: 0},
	{Skibibiditoilet4: 0},
	{Skibibiditoilet5: 0},
	{Skibibiditoilet6: 0},
	{ShopBuyText1: 0},
	{ShopBuyText2: 0},
	{ShopBuyText3: 0},
	{ShopBuyText4: 0},
	{ShopBuyText5: 0},
	{ShopBuyText6: 0},
	{ShopBuyText7: 0},
	{ShopBuyText8: 0},
	{ShopBuyText9: 0},
	{ShopBuyText10: 0},
	{Player3: 0},
	{Skibibiditoilet7: 0},
	{Skibibiditoilet8: 0},
	{Skibibiditoilet9: 0},
	{Skibibiditoilet10: 0},
	{Skibibiditoilet11: 0},
	{coinicon: 0},
	{Coin: 0},
	{ShoppingCart: 0},
	{Buyetkl1: 0},
	{Buyetkl2: 0},
	{Buyetkl3: 0},
	{Buyetkl4: 0},
	{Buyetkl5: 0},
	{Buyetkl6: 0},
	{Buyetkl7: 0},
	{Buyetkl8: 0},
	{Buyetkl9: 0},
	{Buyetkl10: 0},
	{LevelETKL1: 0},
	{LevelETKL2: 0},
	{LevelETKL3: 0},
	{LevelETKL4: 0},
	{LevelETKL5: 0},
	{LevelETKL6: 0},
	{LevelETKL7: 0},
	{LevelETKL8: 0},
	{LevelETKL9: 0},
	{LevelETKL10: 0},
	{OwnerText2: 0},
	{MenuETKL1: 0},
	{ShopETKL: 0},
	{CloseETKL: 0},
	{SmartJoystick: 0},
	{Sprite: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{type: 0},
	{joistikkirizi: 0},
	{PlatformInfo: 0},
	{Black_skull: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{menubutton: 0},
	{shoparka: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{adsbutton: 0},
	{winhemu: 0},
	{Sprite5: 0},
	{Audio: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{WeeGooSDK: 0},
	{Damage: 0},
	{giveammovalue: 0},
	{givehealthvalue: 0},
	{Gun5: 0},
	{Gun4: 0},
	{Gun3: 0},
	{Gun2: 0},
	{Skin: 0},
	{cameramanskibidiscore: 0},
	{Skin2: 0},
	{Skin3: 0},
	{Skin4: 0},
	{Skin5: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Gun: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Ammo: class extends self.ISpriteInstance {},
	Aim: class extends self.ISpriteInstance {},
	SkibidiToiletEnemy1: class extends self.ISpriteInstance {},
	_3DCamera: class extends self.IInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	icon: class extends self.ISpriteInstance {},
	HealthBar: class extends self.ISpriteInstance {},
	Health: class extends self.ITiledBackgroundInstance {},
	Home: class extends self.ISpriteInstance {},
	binaaaa: class extends self.ISpriteInstance {},
	Solid: class extends self.ISpriteInstance {},
	maxhit: class extends self.ISpriteInstance {},
	shadow: class extends self.ISpriteInstance {},
	AmmoText: class extends self.ITextInstance {},
	ammoicon: class extends self.ISpriteInstance {},
	ammopack: class extends self.ISpriteInstance {},
	healthpack: class extends self.ISpriteInstance {},
	BossFightEtkl: class extends self.ISpriteInstance {},
	Boss1: class extends self.ISpriteInstance {},
	HealthBar2: class extends self.ISpriteInstance {},
	Boss1Health: class extends self.ITiledBackgroundInstance {},
	Skibibiditoilet: class extends self.ISpriteInstance {},
	SkibidiToiletEnemy2: class extends self.ISpriteInstance {},
	Boss2: class extends self.ISpriteInstance {},
	dark: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	MenuETKL: class extends self.ISpriteInstance {},
	Skibibiditoilet2: class extends self.ISpriteInstance {},
	SkibidiToiletEnemy3: class extends self.ISpriteInstance {},
	Ammo2: class extends self.ISpriteInstance {},
	Boss3: class extends self.ISpriteInstance {},
	SkibidiToiletEnemy4: class extends self.ISpriteInstance {},
	Boss4: class extends self.ISpriteInstance {},
	SkibidiToiletEnemy5: class extends self.ISpriteInstance {},
	Boss5: class extends self.ISpriteInstance {},
	Player2: class extends self.ISpriteInstance {},
	ToiletIcon: class extends self.ISpriteInstance {},
	dark2: class extends self.ISpriteInstance {},
	ammopack2: class extends self.ISpriteInstance {},
	healthpack2: class extends self.ISpriteInstance {},
	OwnerText: class extends self.ITextInstance {},
	dark3: class extends self.ISpriteInstance {},
	Skibibiditoilet3: class extends self.ISpriteInstance {},
	Skibibiditoilet4: class extends self.ISpriteInstance {},
	Skibibiditoilet5: class extends self.ISpriteInstance {},
	Skibibiditoilet6: class extends self.ISpriteInstance {},
	ShopBuyText1: class extends self.ITextInstance {},
	ShopBuyText2: class extends self.ITextInstance {},
	ShopBuyText3: class extends self.ITextInstance {},
	ShopBuyText4: class extends self.ITextInstance {},
	ShopBuyText5: class extends self.ITextInstance {},
	ShopBuyText6: class extends self.ITextInstance {},
	ShopBuyText7: class extends self.ITextInstance {},
	ShopBuyText8: class extends self.ITextInstance {},
	ShopBuyText9: class extends self.ITextInstance {},
	ShopBuyText10: class extends self.ITextInstance {},
	Player3: class extends self.ISpriteInstance {},
	Skibibiditoilet7: class extends self.ISpriteInstance {},
	Skibibiditoilet8: class extends self.ISpriteInstance {},
	Skibibiditoilet9: class extends self.ISpriteInstance {},
	Skibibiditoilet10: class extends self.ISpriteInstance {},
	Skibibiditoilet11: class extends self.ISpriteInstance {},
	coinicon: class extends self.ISpriteInstance {},
	Coin: class extends self.ITextInstance {},
	ShoppingCart: class extends self.ISpriteInstance {},
	Buyetkl1: class extends self.ISpriteInstance {},
	Buyetkl2: class extends self.ISpriteInstance {},
	Buyetkl3: class extends self.ISpriteInstance {},
	Buyetkl4: class extends self.ISpriteInstance {},
	Buyetkl5: class extends self.ISpriteInstance {},
	Buyetkl6: class extends self.ISpriteInstance {},
	Buyetkl7: class extends self.ISpriteInstance {},
	Buyetkl8: class extends self.ISpriteInstance {},
	Buyetkl9: class extends self.ISpriteInstance {},
	Buyetkl10: class extends self.ISpriteInstance {},
	LevelETKL1: class extends self.ISpriteInstance {},
	LevelETKL2: class extends self.ISpriteInstance {},
	LevelETKL3: class extends self.ISpriteInstance {},
	LevelETKL4: class extends self.ISpriteInstance {},
	LevelETKL5: class extends self.ISpriteInstance {},
	LevelETKL6: class extends self.ISpriteInstance {},
	LevelETKL7: class extends self.ISpriteInstance {},
	LevelETKL8: class extends self.ISpriteInstance {},
	LevelETKL9: class extends self.ISpriteInstance {},
	LevelETKL10: class extends self.ISpriteInstance {},
	OwnerText2: class extends self.ITextInstance {},
	MenuETKL1: class extends self.ISpriteInstance {},
	ShopETKL: class extends self.ISpriteInstance {},
	CloseETKL: class extends self.ISpriteInstance {},
	SmartJoystick: class extends self.IWorldInstance {},
	Sprite: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	joistikkirizi: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	Black_skull: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	menubutton: class extends self.ISpriteInstance {},
	shoparka: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	adsbutton: class extends self.ISpriteInstance {},
	winhemu: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {}
}