const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.custom,
		C3.Behaviors.scrollto,
		C3.Behaviors.Timer,
		C3.Plugins.Keyboard,
		C3.Plugins.Shape3D,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Behaviors.LOS,
		C3.Plugins.gamepad,
		C3.Behaviors.Rotate,
		C3.Behaviors.destroy,
		C3.Behaviors.Fade,
		C3.Plugins.Spritefont2,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Sprite.Acts.RotateTowardAngle,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.custom.Acts.AccelerateAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.custom.Acts.SetSpeed,
		C3.Behaviors.custom.Exps.Speed,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Rotate.Exps.Speed,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.TiledBg.Exps.BBoxRight,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.SetLayerEffectParam,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{Custom: 0},
	{ScrollTo: 0},
	{Timer: 0},
	{JetCollision: 0},
	{Keyboard: 0},
	{JetEngine: 0},
	{World: 0},
	{JetParticles: 0},
	{Water: 0},
	{MountainsBack: 0},
	{MountainsFront: 0},
	{Clouds: 0},
	{CloudsTexture: 0},
	{JetAnimations: 0},
	{Tween: 0},
	{Wave: 0},
	{Bullet: 0},
	{Sine: 0},
	{HostileVTOL: 0},
	{LineOfSight: 0},
	{Missile: 0},
	{AmmoIndex: 0},
	{Ammo: 0},
	{HostileIcon: 0},
	{MissileParticles: 0},
	{Gamepad: 0},
	{FrontierLimits: 0},
	{MissileLock: 0},
	{TargetLock: 0},
	{HUD: 0},
	{Compass: 0},
	{JetBurst: 0},
	{Rotate: 0},
	{FireBall: 0},
	{SizeMultiplier: 0},
	{DestroyOutsideLayout: 0},
	{ExplosionGuide: 0},
	{Fade: 0},
	{JetTrail: 0},
	{MuzzleFlash: 0},
	{Tutorial: 0},
	{WeeGooSDK: 0},
	{InputLeft: 0},
	{InputRight: 0},
	{InputUp: 0},
	{InputDown: 0},
	{HorizontalAxis: 0},
	{VerticalAxis: 0},
	{AxisAngle: 0},
	{ACCELERATION: 0},
	{ROTATIONSPEED: 0},
	{MAXSPEED: 0},
	{FALLSPEED: 0},
	{CameraScale: 0},
	{RandomSize: 0},
	{MissileUID: 0},
	{HostileAngle: 0},
	{MAXTIMEOUTOFCOMBAT: 0},
	{TimeOutOfCombat: 0},
	{BWEffect: 0}
];

self.InstanceType = {
	JetCollision: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	JetEngine: class extends self.ISpriteInstance {},
	World: class extends self.I3DShapeInstance {},
	JetParticles: class extends self.IParticlesInstance {},
	Water: class extends self.ISpriteInstance {},
	MountainsBack: class extends self.I3DShapeInstance {},
	MountainsFront: class extends self.I3DShapeInstance {},
	Clouds: class extends self.I3DShapeInstance {},
	CloudsTexture: class extends self.ITiledBackgroundInstance {},
	JetAnimations: class extends self.ISpriteInstance {},
	Wave: class extends self.ISpriteInstance {},
	HostileVTOL: class extends self.ISpriteInstance {},
	Missile: class extends self.ISpriteInstance {},
	Ammo: class extends self.ISpriteInstance {},
	HostileIcon: class extends self.ISpriteInstance {},
	MissileParticles: class extends self.IParticlesInstance {},
	Gamepad: class extends self.IInstance {},
	FrontierLimits: class extends self.ITiledBackgroundInstance {},
	MissileLock: class extends self.ISpriteInstance {},
	TargetLock: class extends self.ISpriteInstance {},
	HUD: class extends self.ISpriteInstance {},
	Compass: class extends self.ITiledBackgroundInstance {},
	JetBurst: class extends self.ISpriteInstance {},
	FireBall: class extends self.ISpriteInstance {},
	ExplosionGuide: class extends self.ISpriteInstance {},
	JetTrail: class extends self.ISpriteInstance {},
	MuzzleFlash: class extends self.ISpriteInstance {},
	Tutorial: class extends self.ISpriteFontInstance {},
	WeeGooSDK: class extends self.IInstance {}
}