const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.gamepad,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Plugins.PlatformInfo,
		C3.Plugins.TiledBg,
		C3.Plugins.LocalStorage,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Rex_Platform_MoveTo,
		C3.Behaviors.Bullet,
		C3.Behaviors.Pin,
		C3.Behaviors.Rotate,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Rex_Platform_MoveTo.Acts.Stop,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Behaviors.Rex_Platform_MoveTo.Acts.SetTargetPosOnObject,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Browser: 0},
	{Gamepad: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{Run: 0},
	{Platform: 0},
	{Player: 0},
	{Player2: 0},
	{Solid: 0},
	{Tilemap: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{Sine: 0},
	{kapi: 0},
	{type: 0},
	{Text: 0},
	{Score: 0},
	{Fade: 0},
	{Sprite3: 0},
	{PlatformInfo: 0},
	{next: 0},
	{Startclick: 0},
	{replay: 0},
	{TiledBackground3: 0},
	{sekerkirmizi: 0},
	{pause: 0},
	{pngaaacom: 0},
	{LocalStorage: 0},
	{sag: 0},
	{sol: 0},
	{zipla: 0},
	{hareket: 0},
	{enemybot: 0},
	{Sprite10: 0},
	{capi: 0},
	{slimeduvar: 0},
	{pause2: 0},
	{TiledBackground: 0},
	{Scoretext: 0},
	{Silinmeyen: 0},
	{tap: 0},
	{mapduvar: 0},
	{PlatformMoveTo: 0},
	{noob: 0},
	{Sprite2: 0},
	{yeti: 0},
	{Bullet: 0},
	{yetiball: 0},
	{TiledBackground2: 0},
	{hacker2: 0},
	{jump: 0},
	{Pin: 0},
	{Rotate: 0},
	{silah: 0},
	{Spriteatak: 0},
	{noob2: 0},
	{moregames: 0},
	{Sprite4: 0},
	{bulud: 0},
	{sagci: 0},
	{solcu: 0},
	{silah2: 0},
	{TiledBackground4: 0},
	{TiledBackground5: 0},
	{TiledBackground6: 0},
	{Sprite: 0},
	{Text2: 0},
	{WeeGooSDK: 0},
	{suger: 0},
	{CameraTarger: 0},
	{noobhelpsheepscore: 0},
	{noobhelpsheeplevel: 0},
	{sound: 0},
	{music: 0},
	{dur: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Player: class extends self.ISpriteInstance {},
	Player2: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Camera: class extends self.ISpriteInstance {},
	kapi: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Score: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	next: class extends self.ISpriteInstance {},
	Startclick: class extends self.ISpriteInstance {},
	replay: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	sekerkirmizi: class extends self.ISpriteInstance {},
	pause: class extends self.ISpriteInstance {},
	pngaaacom: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	sag: class extends self.ISpriteInstance {},
	sol: class extends self.ISpriteInstance {},
	zipla: class extends self.ISpriteInstance {},
	enemybot: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	capi: class extends self.ISpriteInstance {},
	slimeduvar: class extends self.ISpriteInstance {},
	pause2: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Scoretext: class extends self.ISpriteFontInstance {},
	Silinmeyen: class extends self.ISpriteFontInstance {},
	tap: class extends self.ISpriteInstance {},
	mapduvar: class extends self.ISpriteInstance {},
	noob: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	yeti: class extends self.ISpriteInstance {},
	yetiball: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	hacker2: class extends self.ISpriteInstance {},
	jump: class extends self.ISpriteInstance {},
	silah: class extends self.ISpriteInstance {},
	Spriteatak: class extends self.ISpriteInstance {},
	noob2: class extends self.ISpriteInstance {},
	moregames: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	bulud: class extends self.ITiledBackgroundInstance {},
	sagci: class extends self.ISpriteInstance {},
	solcu: class extends self.ISpriteInstance {},
	silah2: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	WeeGooSDK: class extends self.IInstance {},
	suger: class extends self.ISpriteInstance {}
}