const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Physics,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.Particles,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Plugins.GM_SDK,
		C3.Plugins.WGSDK,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Exps.LayerNumber,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.TiledBg.Acts.SetTowardPosition,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.regexmatchat,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Spritefont2.Exps.IID
	];
};
self.C3_JsPropNameTable = [
	{game_bg: 0},
	{play_btn: 0},
	{Sine: 0},
	{mainmenu_fruits: 0},
	{Physics: 0},
	{Ball: 0},
	{Cursor: 0},
	{DistanceRuler: 0},
	{platform: 0},
	{fruit: 0},
	{Tween: 0},
	{blast: 0},
	{blastparticle_obj: 0},
	{Blast_Particle: 0},
	{danger: 0},
	{background_of_losewin: 0},
	{Touch: 0},
	{Audio: 0},
	{home_btn: 0},
	{sound_btn: 0},
	{music_btn: 0},
	{TITLEAsset: 0},
	{LEVELBgAsset: 0},
	{LEVELBUTTONAsset: 0},
	{LEVELAsset: 0},
	{LEVELBUTTONLOCKAsset: 0},
	{LEVELBUTTONLOCKAsset2: 0},
	{SpriteFont: 0},
	{Particles: 0},
	{Sprite: 0},
	{levelAsset2: 0},
	{SpriteFont2: 0},
	{LEVELCOMPLETEAsset: 0},
	{LEVELCOMPLETEAsset2: 0},
	{LEVELCOMPLETEAsset3: 0},
	{FAILAsset: 0},
	{FAILAsset2: 0},
	{FAILAsset3: 0},
	{LEVELCOMPLETE1Asset: 0},
	{SpriteFont3: 0},
	{LocalStorage: 0},
	{iButtonAsset: 0},
	{instruction_page: 0},
	{crossButtonAsset: 0},
	{pointerAsset: 0},
	{GameMonetizeSDK: 0},
	{WeeGooSDK: 0},
	{btns: 0},
	{ball_throwable: 0},
	{juice_color_for_particle: 0},
	{sound_state: 0},
	{music_state: 0},
	{most_level_unlocked: 0},
	{level_menu_index: 0},
	{most_level_menu_index: 0}
];

self.InstanceType = {
	game_bg: class extends self.ISpriteInstance {},
	play_btn: class extends self.ISpriteInstance {},
	mainmenu_fruits: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	Cursor: class extends self.ISpriteInstance {},
	DistanceRuler: class extends self.ITiledBackgroundInstance {},
	platform: class extends self.ISpriteInstance {},
	fruit: class extends self.ISpriteInstance {},
	blast: class extends self.ISpriteInstance {},
	blastparticle_obj: class extends self.ISpriteInstance {},
	Blast_Particle: class extends self.IParticlesInstance {},
	danger: class extends self.ISpriteInstance {},
	background_of_losewin: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	home_btn: class extends self.ISpriteInstance {},
	sound_btn: class extends self.ISpriteInstance {},
	music_btn: class extends self.ISpriteInstance {},
	TITLEAsset: class extends self.ISpriteInstance {},
	LEVELBgAsset: class extends self.ISpriteInstance {},
	LEVELBUTTONAsset: class extends self.ISpriteInstance {},
	LEVELAsset: class extends self.ISpriteInstance {},
	LEVELBUTTONLOCKAsset: class extends self.ISpriteInstance {},
	LEVELBUTTONLOCKAsset2: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Particles: class extends self.IParticlesInstance {},
	Sprite: class extends self.ISpriteInstance {},
	levelAsset2: class extends self.ISpriteInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	LEVELCOMPLETEAsset: class extends self.ISpriteInstance {},
	LEVELCOMPLETEAsset2: class extends self.ISpriteInstance {},
	LEVELCOMPLETEAsset3: class extends self.ISpriteInstance {},
	FAILAsset: class extends self.ISpriteInstance {},
	FAILAsset2: class extends self.ISpriteInstance {},
	FAILAsset3: class extends self.ISpriteInstance {},
	LEVELCOMPLETE1Asset: class extends self.ISpriteInstance {},
	SpriteFont3: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	iButtonAsset: class extends self.ISpriteInstance {},
	instruction_page: class extends self.ISpriteInstance {},
	crossButtonAsset: class extends self.ISpriteInstance {},
	pointerAsset: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	WeeGooSDK: class extends self.IInstance {},
	btns: class extends self.ISpriteInstance {}
}