const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Car,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Behaviors.Sin,
		C3.Plugins.PlatformInfo,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.Car.Cnds.IsMoving,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Car.Acts.SimulateControl,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Car.Acts.SetSpeed,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetFullscreenQuality,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetLayerBackground,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Eponesh_GameScore.Acts.ChangeLanguage,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Car: 0},
	{ScrollTo: 0},
	{Sprite2: 0},
	{dead: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{lvl: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{TiledBackground3: 0},
	{Text: 0},
	{Anchor: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sine: 0},
	{Sprite11: 0},
	{PlatformInfo: 0},
	{Sprite12: 0},
	{Text2: 0},
	{Bullet: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{lvls: 0},
	{Touch: 0},
	{pc: 0},
	{LocalStorage: 0},
	{ads: 0},
	{lvls2: 0},
	{GameScore: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite10: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{count: 0},
	{graph: 0},
	{money: 0},
	{skin: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	lvls: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	pc: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	ads: class extends self.ISpriteInstance {},
	lvls2: class extends self.ITextInstance {},
	GameScore: class extends self.C3.Plugins.Eponesh_GameScore.Instance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {}
}