const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Plugins.Particles,
		C3.Behaviors.destroy,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Timer,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Arr.Exps.CurX,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsStickyPlaying,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowSticky,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Exps.Height,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Audio.Cnds.IsAnyPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Behaviors.DragnDrop.Acts.Drop,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Touch.Cnds.OnDoubleTapGestureObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Sprite.Exps.AsJSON,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.LoadFromJsonString,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenAvailable,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart
	];
};
self.C3_JsPropNameTable = [
	{posX: 0},
	{posY: 0},
	{num: 0},
	{suit: 0},
	{id: 0},
	{open: 0},
	{drag: 0},
	{complate: 0},
	{active: 0},
	{card: 0},
	{map: 0},
	{arcard: 0},
	{Touch: 0},
	{Type: 0},
	{xx: 0},
	{yy: 0},
	{Tween: 0},
	{SF: 0},
	{Column: 0},
	{type: 0},
	{Синусоида: 0},
	{btn: 0},
	{Confetty: 0},
	{AdvancedRandom: 0},
	{hystory: 0},
	{hystoryCard: 0},
	{Аудио: 0},
	{txt_Logo: 0},
	{sprt_Logo: 0},
	{GamePush: 0},
	{fon_BackGround: 0},
	{sprt_Language: 0},
	{Клавиатура: 0},
	{fon_Connect_Dell: 0},
	{Пуля: 0},
	{sprt_Winn: 0},
	{sprt_Contact: 0},
	{УничтожениеВнеМакета: 0},
	{trail_Winn: 0},
	{sprt_trail: 0},
	{DragDrop: 0},
	{Timer: 0},
	{Fcard: 0},
	{ComplateColumn: 0},
	{shaffle: 0},
	{ADS_timer: 0},
	{countcolumn: 0},
	{countcolumn2: 0},
	{countcolumn3: 0},
	{column: 0},
	{wait: 0},
	{Open: 0},
	{columnCount: 0},
	{columnsize: 0},
	{DragParentID: 0},
	{CountDrag: 0},
	{DragStart: 0},
	{Accepted: 0},
	{save: 0},
	{OldPosX: 0},
	{OldPosY: 0},
	{cardID: 0},
	{uid: 0},
	{savecount: 0},
	{SaveString: 0},
	{win: 0},
	{countcard: 0},
	{GP: 0}
];

self.InstanceType = {
	card: class extends self.ISpriteInstance {},
	map: class extends self.IArrayInstance {},
	arcard: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	SF: class extends self.ISpriteFontInstance {},
	Column: class extends self.ISpriteInstance {},
	btn: class extends self.ISpriteInstance {},
	Confetty: class extends self.ISpriteInstance {},
	AdvancedRandom: class extends self.IInstance {},
	hystory: class extends self.IArrayInstance {},
	hystoryCard: class extends self.IArrayInstance {},
	Аудио: class extends self.IInstance {},
	txt_Logo: class extends self.ITextInstance {},
	sprt_Logo: class extends self.ISpriteInstance {},
	GamePush: class extends self.IInstance {},
	fon_BackGround: class extends self.ITiledBackgroundInstance {},
	sprt_Language: class extends self.ISpriteInstance {},
	Клавиатура: class extends self.IInstance {},
	fon_Connect_Dell: class extends self.ITiledBackgroundInstance {},
	sprt_Winn: class extends self.ISpriteInstance {},
	sprt_Contact: class extends self.ISpriteInstance {},
	trail_Winn: class extends self.IParticlesInstance {},
	sprt_trail: class extends self.ISpriteInstance {},
	Fcard: class extends self.ISpriteInstance {}
}