const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Json,
		C3.Plugins.LocalStorage,
		C3.Plugins.Date,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Timeline,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Physics,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.Rotate,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Particles,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Timeline.Acts.SetInstance,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgba255,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Acts.AddLayer,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.find,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Json.Exps.ToBeautifiedString,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Behaviors.MoveTo.Exps.WaypointYAt,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStart,
		C3.Plugins.AJAX.Acts.Request,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.SetEffect,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.Date.Exps.ToTotalSeconds,
		C3.Plugins.Date.Exps.Difference,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStop,
		C3.Behaviors.MoveTo.Acts.SetRotateSpeed,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsFullscreenClose,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedClose,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.PlatformInfo.Exps.SafeAreaInsetLeft,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Exps.LayerNumber,
		C3.Plugins.PlatformInfo.Exps.SafeAreaInsetTop,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.PlatformInfo.Exps.SafeAreaInsetBottom,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Timeline.Acts.StopTimelineByTags,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{Array_Types: 0},
	{JSON_Config: 0},
	{LocalStorage: 0},
	{JSON_Levels: 0},
	{Array_Helpers: 0},
	{Date: 0},
	{Audio: 0},
	{Touch: 0},
	{PlatformInfo: 0},
	{TimelineController: 0},
	{uid_stack: 0},
	{stack_order: 0},
	{type: 0},
	{is_moving: 0},
	{is_destroy: 0},
	{is_animation: 0},
	{count_moves: 0},
	{dir_move: 0},
	{time_delay: 0},
	{dist_change_animation: 0},
	{frame_animation: 0},
	{x_prev: 0},
	{y_prev: 0},
	{count_distance: 0},
	{speed: 0},
	{total_dist: 0},
	{dist_total_move: 0},
	{Tween: 0},
	{MoveTo: 0},
	{hexa: 0},
	{stack_list_check: 0},
	{stack_list_matchs: 0},
	{group_match: 0},
	{slot_order: 0},
	{stack_target: 0},
	{stack_count_moves: 0},
	{stack_count_destroy: 0},
	{stack_count_destroy_max: 0},
	{is_skip: 0},
	{is_matching: 0},
	{is_match: 0},
	{stack_layer: 0},
	{type_destroying: 0},
	{is_disable: 0},
	{is_hexa_grass: 0},
	{is_hexa_box: 0},
	{is_ice: 0},
	{is_pic: 0},
	{is_bird: 0},
	{is_car: 0},
	{can_set_stack_drag: 0},
	{is_guide: 0},
	{stack_slot: 0},
	{hexa_checker: 0},
	{stack_slot_spawn: 0},
	{uid_stack_spawn: 0},
	{active: 0},
	{uid_slot: 0},
	{order: 0},
	{stack_drag: 0},
	{stack_check: 0},
	{dir: 0},
	{hexa_check_point: 0},
	{Physics: 0},
	{Fade: 0},
	{fx_star_white: 0},
	{combo: 0},
	{combo_point: 0},
	{fx_hammer: 0},
	{background: 0},
	{btn_setting: 0},
	{bar_hexaColorFull: 0},
	{header_box_coin: 0},
	{coin: 0},
	{btn_more_ads: 0},
	{target: 0},
	{w: 0},
	{w_step: 0},
	{game_bar: 0},
	{target_container_parent: 0},
	{destroy: 0},
	{hexa_grass: 0},
	{target_txt_num: 0},
	{counter: 0},
	{type_hexa: 0},
	{type_color: 0},
	{target_temp: 0},
	{target_ic: 0},
	{Footer_deco: 0},
	{banner_target: 0},
	{hexa_box: 0},
	{icc: 0},
	{hexa_ice: 0},
	{booster: 0},
	{dot: 0},
	{width_orignal: 0},
	{height_original: 0},
	{out_of_move_controller: 0},
	{controller_title: 0},
	{btn_audio: 0},
	{btn_music: 0},
	{btn_exit: 0},
	{h: 0},
	{setting_container: 0},
	{bg_controller: 0},
	{control: 0},
	{width_original: 0},
	{list_controller: 0},
	{cost: 0},
	{shop_item: 0},
	{list_txt: 0},
	{ic_coin2: 0},
	{list_item_btn: 0},
	{list_btn_close: 0},
	{home_txt_level: 0},
	{title_game: 0},
	{pig: 0},
	{pig_bank_bar_bg: 0},
	{coins: 0},
	{pig_bank_bar: 0},
	{Rotate: 0},
	{rays: 0},
	{btn_task_list: 0},
	{btn_reward: 0},
	{home_label: 0},
	{trease: 0},
	{checked: 0},
	{task_list_bar_bg: 0},
	{task_list_bar: 0},
	{cirlce: 0},
	{effect_circle: 0},
	{ic_target: 0},
	{reward_controller: 0},
	{box_dec: 0},
	{reward_txt_coin: 0},
	{btn_controller_reward: 0},
	{ic_ads: 0},
	{btn_restart: 0},
	{level_txt: 0},
	{reward_txt_watch: 0},
	{daily_item_title: 0},
	{daily_reward_item: 0},
	{list_btn_txt: 0},
	{task_list_item: 0},
	{task_list_item_title: 0},
	{shop_item_title: 0},
	{popup_title: 0},
	{booster_txt: 0},
	{target_title: 0},
	{coin_txt: 0},
	{home_btn_play: 0},
	{home_btn_label_shadow: 0},
	{home_btn_label: 0},
	{TYPE: 0},
	{drag_container: 0},
	{DIR: 0},
	{bg_overlay_hidden: 0},
	{DragDrop: 0},
	{list_scroll: 0},
	{List_checkPoint: 0},
	{GROUP: 0},
	{responsive: 0},
	{container_ic_target: 0},
	{num: 0},
	{dot_effect: 0},
	{Particles: 0},
	{HexaAura: 0},
	{hexa_locked: 0},
	{stack_slot_locked: 0},
	{hexa_meta_txt: 0},
	{target2: 0},
	{grass_green: 0},
	{hexa_fragment_box: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Layer: 0},
	{fx_smoke: 0},
	{hexa_picture: 0},
	{picture: 0},
	{UID_Bough: 0},
	{index: 0},
	{hexa_bird: 0},
	{egg: 0},
	{bird: 0},
	{obj_timeline_rotate: 0},
	{land: 0},
	{count_move: 0},
	{is_move_complete: 0},
	{hexa_car: 0},
	{pos: 0},
	{land_car: 0},
	{obj_timeline_car: 0},
	{lane_target: 0},
	{lane_dot: 0},
	{caroot: 0},
	{hexa_carrot: 0},
	{seeds_carrot: 0},
	{nums: 0},
	{hexa_seeds: 0},
	{seed_carrot: 0},
	{is_die: 0},
	{hexa_turtle: 0},
	{x_pre: 0},
	{y_pre: 0},
	{rocket: 0},
	{hexa_rocket: 0},
	{victory_banner: 0},
	{target_title2: 0},
	{victory_txt_coin: 0},
	{box_deco: 0},
	{victory_btn_claim: 0},
	{victory_controller: 0},
	{confi: 0},
	{btn_close: 0},
	{loader_ads_controller: 0},
	{ads_loading_txt: 0},
	{ic_coin_effect: 0},
	{hexa_ads: 0},
	{daily_item_date: 0},
	{btn_txt: 0},
	{btn_next: 0},
	{loader_loading_controller: 0},
	{btn_clear: 0},
	{clear_controller: 0},
	{btn_clear_data: 0},
	{TutorialHand: 0},
	{LoadingBg: 0},
	{Loading: 0},
	{watch_ads_controller: 0},
	{watch_btn_ads: 0},
	{GamePush: 0},
	{FamilyStackSlot: 0},
	{FamilyHexaMetas: 0},
	{stack_listMatch: 0},
	{stack_indexAudioClear: 0},
	{stack_indexAudioSort: 0},
	{stack_carIsLoaded: 0},
	{stack_hexaHeight: 0},
	{stack_hexaWidth: 0},
	{stack_spaceCard: 0},
	{path: 0},
	{list_check: 0},
	{length: 0},
	{vx: 0},
	{vy: 0},
	{x: 0},
	{y: 0},
	{data: 0},
	{uid: 0},
	{count: 0},
	{uid_target: 0},
	{uid_value: 0},
	{max_card: 0},
	{list_stack: 0},
	{num_class: 0},
	{y_min: 0},
	{y_max: 0},
	{is_stack_check: 0},
	{nums_card: 0},
	{layer: 0},
	{is_valid: 0},
	{t: 0},
	{uid_move_from: 0},
	{uid_move_to: 0},
	{x_center: 0},
	{y_center: 0},
	{dis_total: 0},
	{uid_stack_check: 0},
	{type_check: 0},
	{can_move: 0},
	{nums_stack_destroy: 0},
	{is_create_fx: 0},
	{count_hexa_destroy: 0},
	{is_slot_empty: 0},
	{stack_list: 0},
	{return_value: 0},
	{x_hexa_seed: 0},
	{y_hexa_seed: 0},
	{HEXDIGITS: 0},
	{color: 0},
	{UI_stateLocked: 0},
	{UI_isReturnAudio: 0},
	{UI_Setting_isOpen: 0},
	{UI_List_positionNewY: 0},
	{UI_List_positionOldY: 0},
	{UI_List_positionLimitTop: 0},
	{UI_List_positionLimitBottom: 0},
	{UI_List_swipeSpeed: 0},
	{UI_List_itemDailyRewardHeight: 0},
	{UI_List_itemTaskListHeight: 0},
	{UI_List_itemShopHeight: 0},
	{UI_List_isDisableScroll: 0},
	{UI_List_isMoving: 0},
	{Victory_counter: 0},
	{Victory_bonus: 0},
	{Victory_isBonusComplete: 0},
	{ads_stackSlot: 0},
	{UI_timeScale: 0},
	{pig_barWidth: 0},
	{pig_barStep: 0},
	{Ads_state: 0},
	{list_size: 0},
	{x_start: 0},
	{y_start: 0},
	{space_item: 0},
	{is_item_first: 0},
	{timer: 0},
	{timer_total: 0},
	{isLocked: 0},
	{size: 0},
	{layer_name: 0},
	{score: 0},
	{Game_isEnd: 0},
	{Game_State: 0},
	{Booster_isUsed: 0},
	{nums_combo: 0},
	{is_stack_slot: 0},
	{val: 0},
	{x_min: 0},
	{x_max: 0},
	{type_hex: 0},
	{x_dot_effect: 0},
	{y_dot_effect: 0},
	{is_complete: 0},
	{key_main: 0},
	{width_step: 0},
	{width_bar: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	Array_Types: class extends self.IArrayInstance {},
	JSON_Config: class extends self.IJSONInstance {},
	LocalStorage: class extends self.IInstance {},
	JSON_Levels: class extends self.IJSONInstance {},
	Array_Helpers: class extends self.IArrayInstance {},
	Date: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	TimelineController: class extends self.IInstance {},
	hexa: class extends self.ISpriteInstance {},
	stack_slot: class extends self.ISpriteInstance {},
	hexa_checker: class extends self.ISpriteInstance {},
	stack_slot_spawn: class extends self.ISpriteInstance {},
	stack_drag: class extends self.ISpriteInstance {},
	stack_check: class extends self.ISpriteInstance {},
	hexa_check_point: class extends self.ISpriteInstance {},
	fx_star_white: class extends self.ISpriteInstance {},
	combo: class extends self.ISpriteInstance {},
	combo_point: class extends self.ISpriteInstance {},
	fx_hammer: class extends self.ISpriteInstance {},
	background: class extends self.ISpriteInstance {},
	btn_setting: class extends self.ISpriteInstance {},
	bar_hexaColorFull: class extends self.ISpriteInstance {},
	header_box_coin: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	btn_more_ads: class extends self.ISpriteInstance {},
	target: class extends self.ISpriteInstance {},
	game_bar: class extends self.ITiledBackgroundInstance {},
	target_container_parent: class extends self.ISpriteInstance {},
	hexa_grass: class extends self.ISpriteInstance {},
	target_txt_num: class extends self.ITextInstance {},
	target_ic: class extends self.ISpriteInstance {},
	Footer_deco: class extends self.ITiledBackgroundInstance {},
	banner_target: class extends self.ISpriteInstance {},
	hexa_box: class extends self.ISpriteInstance {},
	icc: class extends self.ISpriteInstance {},
	hexa_ice: class extends self.ISpriteInstance {},
	booster: class extends self.ISpriteInstance {},
	dot: class extends self.ISpriteInstance {},
	out_of_move_controller: class extends self.ISpriteInstance {},
	controller_title: class extends self.ITextInstance {},
	btn_audio: class extends self.ISpriteInstance {},
	btn_music: class extends self.ISpriteInstance {},
	btn_exit: class extends self.ISpriteInstance {},
	setting_container: class extends self.ISpriteInstance {},
	bg_controller: class extends self.ISpriteInstance {},
	list_controller: class extends self.ISpriteInstance {},
	shop_item: class extends self.ISpriteInstance {},
	list_txt: class extends self.ITextInstance {},
	ic_coin2: class extends self.ISpriteInstance {},
	list_item_btn: class extends self.ISpriteInstance {},
	list_btn_close: class extends self.ISpriteInstance {},
	home_txt_level: class extends self.ITextInstance {},
	title_game: class extends self.ISpriteInstance {},
	pig: class extends self.ISpriteInstance {},
	pig_bank_bar_bg: class extends self.ISpriteInstance {},
	coins: class extends self.ISpriteInstance {},
	pig_bank_bar: class extends self.ITiledBackgroundInstance {},
	rays: class extends self.ISpriteInstance {},
	btn_task_list: class extends self.ISpriteInstance {},
	btn_reward: class extends self.ISpriteInstance {},
	home_label: class extends self.ITextInstance {},
	trease: class extends self.ISpriteInstance {},
	checked: class extends self.ISpriteInstance {},
	task_list_bar_bg: class extends self.ISpriteInstance {},
	task_list_bar: class extends self.ITiledBackgroundInstance {},
	cirlce: class extends self.ISpriteInstance {},
	effect_circle: class extends self.ISpriteInstance {},
	ic_target: class extends self.ISpriteInstance {},
	reward_controller: class extends self.ISpriteInstance {},
	box_dec: class extends self.ISpriteInstance {},
	reward_txt_coin: class extends self.ITextInstance {},
	btn_controller_reward: class extends self.ISpriteInstance {},
	ic_ads: class extends self.ISpriteInstance {},
	btn_restart: class extends self.ISpriteInstance {},
	level_txt: class extends self.ITextInstance {},
	reward_txt_watch: class extends self.ITextInstance {},
	daily_item_title: class extends self.ITextInstance {},
	daily_reward_item: class extends self.ISpriteInstance {},
	list_btn_txt: class extends self.ITextInstance {},
	task_list_item: class extends self.ISpriteInstance {},
	task_list_item_title: class extends self.ITextInstance {},
	shop_item_title: class extends self.ITextInstance {},
	popup_title: class extends self.ITextInstance {},
	booster_txt: class extends self.ITextInstance {},
	target_title: class extends self.ITextInstance {},
	coin_txt: class extends self.ITextInstance {},
	home_btn_play: class extends self.ISpriteInstance {},
	home_btn_label_shadow: class extends self.ITextInstance {},
	home_btn_label: class extends self.ITextInstance {},
	drag_container: class extends self.ISpriteInstance {},
	bg_overlay_hidden: class extends self.ISpriteInstance {},
	list_scroll: class extends self.ISpriteInstance {},
	List_checkPoint: class extends self.ISpriteInstance {},
	responsive: class extends self.ISpriteInstance {},
	container_ic_target: class extends self.ISpriteInstance {},
	dot_effect: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	HexaAura: class extends self.ISpriteInstance {},
	hexa_locked: class extends self.ISpriteInstance {},
	stack_slot_locked: class extends self.ISpriteInstance {},
	hexa_meta_txt: class extends self.ITextInstance {},
	target2: class extends self.ISpriteInstance {},
	grass_green: class extends self.ISpriteInstance {},
	hexa_fragment_box: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Layer: class extends self.ISpriteInstance {},
	fx_smoke: class extends self.ISpriteInstance {},
	hexa_picture: class extends self.ISpriteInstance {},
	picture: class extends self.ISpriteInstance {},
	hexa_bird: class extends self.ISpriteInstance {},
	egg: class extends self.ISpriteInstance {},
	bird: class extends self.ISpriteInstance {},
	obj_timeline_rotate: class extends self.ISpriteInstance {},
	hexa_car: class extends self.ISpriteInstance {},
	land_car: class extends self.ISpriteInstance {},
	obj_timeline_car: class extends self.ISpriteInstance {},
	lane_target: class extends self.ISpriteInstance {},
	lane_dot: class extends self.ISpriteInstance {},
	caroot: class extends self.ISpriteInstance {},
	hexa_carrot: class extends self.ISpriteInstance {},
	seeds_carrot: class extends self.ISpriteInstance {},
	hexa_seeds: class extends self.ISpriteInstance {},
	seed_carrot: class extends self.ISpriteInstance {},
	hexa_turtle: class extends self.ISpriteInstance {},
	rocket: class extends self.ISpriteInstance {},
	hexa_rocket: class extends self.ISpriteInstance {},
	victory_banner: class extends self.ISpriteInstance {},
	target_title2: class extends self.ITextInstance {},
	victory_txt_coin: class extends self.ITextInstance {},
	box_deco: class extends self.ISpriteInstance {},
	victory_btn_claim: class extends self.ISpriteInstance {},
	victory_controller: class extends self.ISpriteInstance {},
	confi: class extends self.ISpriteInstance {},
	btn_close: class extends self.ISpriteInstance {},
	loader_ads_controller: class extends self.ISpriteInstance {},
	ads_loading_txt: class extends self.ITextInstance {},
	ic_coin_effect: class extends self.ISpriteInstance {},
	hexa_ads: class extends self.ISpriteInstance {},
	daily_item_date: class extends self.ITextInstance {},
	btn_txt: class extends self.ITextInstance {},
	btn_next: class extends self.ISpriteInstance {},
	loader_loading_controller: class extends self.ISpriteInstance {},
	btn_clear: class extends self.ISpriteInstance {},
	clear_controller: class extends self.ISpriteInstance {},
	btn_clear_data: class extends self.ISpriteInstance {},
	TutorialHand: class extends self.ISpriteInstance {},
	LoadingBg: class extends self.ISpriteInstance {},
	Loading: class extends self.ITiledBackgroundInstance {},
	watch_ads_controller: class extends self.ISpriteInstance {},
	watch_btn_ads: class extends self.ISpriteInstance {},
	GamePush: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	FamilyStackSlot: class extends self.ISpriteInstance {},
	FamilyHexaMetas: class extends self.ISpriteInstance {}
}