const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.DrawingCanvas,
		C3.Behaviors.Tween,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.bound,
		C3.Plugins.Sprite,
		C3.Plugins.NinePatch,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Pin,
		C3.Plugins.WGSDK,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.DrawingCanvas.Acts.SetInstanceVar,
		C3.Plugins.DrawingCanvas.Acts.SetSize,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.DrawingCanvas.Acts.MoveToTop,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.DrawingCanvas.Exps.Angle,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.DrawingCanvas.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.NinePatch.Cnds.PickByUID,
		C3.Plugins.NinePatch.Acts.SetBoolInstanceVar,
		C3.Plugins.DrawingCanvas.Acts.SetBoolInstanceVar,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.NinePatch.Cnds.PickDistance,
		C3.Plugins.DrawingCanvas.Exps.X,
		C3.Plugins.DrawingCanvas.Exps.Y,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.NinePatch.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.NinePatch.Exps.UID,
		C3.Plugins.DrawingCanvas.Acts.SetPos,
		C3.Plugins.DrawingCanvas.Exps.Width,
		C3.Plugins.DrawingCanvas.Exps.Height,
		C3.Plugins.DrawingCanvas.Acts.MoveToBottom,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.DrawingCanvas.Exps.Count,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Behaviors.Sin.Acts.SetMovement,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Acts.SetLayoutAngle,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.WGSDK.Cnds.RewardGranted,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.LocalStorage.Cnds.OnAllGetsComplete,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Spritefont2.Acts.AppendText,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{Index: 0},
	{Snapped: 0},
	{GridBlockUID: 0},
	{Tween: 0},
	{DragDrop: 0},
	{BoundToLayout: 0},
	{Piece: 0},
	{SourceImage: 0},
	{GridBlock: 0},
	{PickEffect: 0},
	{GameManager: 0},
	{SplashGlow: 0},
	{Flash: 0},
	{WinGlow: 0},
	{Frame: 0},
	{Keyboard: 0},
	{Fade: 0},
	{Tutorial: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{okvir: 0},
	{Sine: 0},
	{playbtn2: 0},
	{menu: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{playbtn: 0},
	{Touch: 0},
	{Sprite3: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{BSound: 0},
	{SourceImage2: 0},
	{drugi: 0},
	{okvir2: 0},
	{Mouse: 0},
	{okvir3: 0},
	{dalje: 0},
	{treci: 0},
	{cetvrti: 0},
	{peti: 0},
	{sesti: 0},
	{Audio: 0},
	{Sprite4: 0},
	{ShakingSpriteFont: 0},
	{MOREGAMESBTN: 0},
	{SpriteFont: 0},
	{Text: 0},
	{Browser: 0},
	{Sprite9: 0},
	{sedmi: 0},
	{osmi: 0},
	{deveti: 0},
	{Text2: 0},
	{Sprite10: 0},
	{MALIKOMAD: 0},
	{TACKA: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{REWARD: 0},
	{trideset: 0},
	{textreklama: 0},
	{reklamabrojanje: 0},
	{REWARD2maska: 0},
	{Sprite13: 0},
	{menu2: 0},
	{Open: 0},
	{Level: 0},
	{LevelsBlock: 0},
	{LocalStorage: 0},
	{LevelsText: 0},
	{pozadina: 0},
	{Pin: 0},
	{SpriteFont123: 0},
	{nagrade: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{y8: 0},
	{Loginy8moja: 0},
	{playerName: 0},
	{logo_main: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{SASTRANE: 0},
	{Sprite33: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{kapaa: 0},
	{Sprite38: 0},
	{pozadina2: 0},
	{pozadina3: 0},
	{Sprite32: 0},
	{Sprite39: 0},
	{lagged: 0},
	{Confetti: 0},
	{WeeGooSDK: 0},
	{btn: 0},
	{LAST_LEVEL: 0},
	{WIN: 0},
	{LevelComplete: 0},
	{PiecesPerLine: 0},
	{PiecesWidth: 0},
	{PiecesHeight: 0},
	{SpawnMargin: 0},
	{SnapDistance: 0},
	{sound: 0},
	{SoundEf: 0},
	{Timer: 0},
	{CurrentIndex: 0},
	{Count: 0},
	{Duration: 0},
	{Strength: 0},
	{OffsetSpeed: 0},
	{shakingTextString: 0}
];

self.InstanceType = {
	Piece: class extends self.IDrawingCanvasInstance {},
	SourceImage: class extends self.ISpriteInstance {},
	GridBlock: class extends self.I9PatchInstance {},
	PickEffect: class extends self.I9PatchInstance {},
	GameManager: class extends self.ISpriteInstance {},
	SplashGlow: class extends self.IParticlesInstance {},
	Flash: class extends self.ITiledBackgroundInstance {},
	WinGlow: class extends self.IParticlesInstance {},
	Frame: class extends self.I9PatchInstance {},
	Keyboard: class extends self.IInstance {},
	Tutorial: class extends self.ISpriteFontInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	okvir: class extends self.ISpriteInstance {},
	playbtn2: class extends self.ISpriteInstance {},
	menu: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	playbtn: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	BSound: class extends self.ISpriteInstance {},
	SourceImage2: class extends self.ISpriteInstance {},
	drugi: class extends self.ISpriteInstance {},
	okvir2: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	okvir3: class extends self.ISpriteInstance {},
	dalje: class extends self.ISpriteInstance {},
	treci: class extends self.ISpriteInstance {},
	cetvrti: class extends self.ISpriteInstance {},
	peti: class extends self.ISpriteInstance {},
	sesti: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	ShakingSpriteFont: class extends self.ISpriteFontInstance {},
	MOREGAMESBTN: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Text: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	sedmi: class extends self.ISpriteInstance {},
	osmi: class extends self.ISpriteInstance {},
	deveti: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	MALIKOMAD: class extends self.ISpriteInstance {},
	TACKA: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	REWARD: class extends self.ISpriteInstance {},
	textreklama: class extends self.ITextInstance {},
	reklamabrojanje: class extends self.ISpriteInstance {},
	REWARD2maska: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	menu2: class extends self.ISpriteInstance {},
	LevelsBlock: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	LevelsText: class extends self.ISpriteFontInstance {},
	pozadina: class extends self.ISpriteInstance {},
	SpriteFont123: class extends self.ISpriteFontInstance {},
	nagrade: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	y8: class extends self.ISpriteInstance {},
	Loginy8moja: class extends self.ISpriteInstance {},
	playerName: class extends self.ITextInstance {},
	logo_main: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	SASTRANE: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	kapaa: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	pozadina2: class extends self.ISpriteInstance {},
	pozadina3: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	lagged: class extends self.ISpriteInstance {},
	Confetti: class extends self.IParticlesInstance {},
	WeeGooSDK: class extends C3.Plugins.WGSDK.Instance {},
	btn: class extends self.ISpriteInstance {}
}