const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Behaviors.Timer,
		C3.Behaviors.destroy,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.WGSDK,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Particles.Acts.MoveToBottom,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Spritefont2.Acts.MoveToTop,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{BarOff: 0},
	{BarOn: 0},
	{BlueBall: 0},
	{Physics: 0},
	{circle: 0},
	{Tween: 0},
	{effectPlay: 0},
	{Fade: 0},
	{fade: 0},
	{fadeEnd: 0},
	{FadeLose: 0},
	{FadeWin: 0},
	{GreenBall: 0},
	{Gun: 0},
	{homebutton: 0},
	{levelbutton: 0},
	{Sine: 0},
	{loseLogo: 0},
	{loseRestart: 0},
	{maskGUI: 0},
	{maskGUI2: 0},
	{menubutton: 0},
	{ParticlesLifeOff: 0},
	{Timer: 0},
	{partWhite: 0},
	{PinkBall: 0},
	{platform: 0},
	{platform2: 0},
	{platform3: 0},
	{platform4: 0},
	{rectangle: 0},
	{RedBall: 0},
	{restartbutton: 0},
	{returnButton: 0},
	{life: 0},
	{DestroyOutsideLayout: 0},
	{star: 0},
	{TiledBackground: 0},
	{triggerMenu: 0},
	{winLevel: 0},
	{WinLogo: 0},
	{winNext: 0},
	{YellowBall: 0},
	{logo: 0},
	{play: 0},
	{level: 0},
	{LevelPlace: 0},
	{levelsLogo: 0},
	{LevelNumber: 0},
	{LevelNumber2: 0},
	{textCompleted: 0},
	{textLevel: 0},
	{textTime: 0},
	{Completed: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{btn_more_in: 0},
	{Browser: 0},
	{fbg_eye: 0},
	{WeeGooSDK: 0},
	{AllBalloon: 0},
	{AllPlatforms: 0},
	{AllWinParts: 0},
	{Pin: 0},
	{AllButtons: 0},
	{LoseWinObjects: 0},
	{WIN: 0},
	{TimeWin: 0},
	{Life: 0},
	{LEVELS: 0},
	{CompletedLevels: 0},
	{LevelWin: 0},
	{LevelLose: 0},
	{WinCounts: 0}
];

self.InstanceType = {
	BarOff: class extends self.ISpriteInstance {},
	BarOn: class extends self.ISpriteInstance {},
	BlueBall: class extends self.ISpriteInstance {},
	circle: class extends self.ISpriteInstance {},
	effectPlay: class extends self.ISpriteInstance {},
	fade: class extends self.ITiledBackgroundInstance {},
	fadeEnd: class extends self.ITiledBackgroundInstance {},
	FadeLose: class extends self.ITiledBackgroundInstance {},
	FadeWin: class extends self.ITiledBackgroundInstance {},
	GreenBall: class extends self.ISpriteInstance {},
	Gun: class extends self.ISpriteInstance {},
	homebutton: class extends self.ISpriteInstance {},
	levelbutton: class extends self.ISpriteInstance {},
	loseLogo: class extends self.ISpriteInstance {},
	loseRestart: class extends self.ISpriteInstance {},
	maskGUI: class extends self.ISpriteInstance {},
	maskGUI2: class extends self.ISpriteInstance {},
	menubutton: class extends self.ISpriteInstance {},
	ParticlesLifeOff: class extends self.IParticlesInstance {},
	partWhite: class extends self.ISpriteInstance {},
	PinkBall: class extends self.ISpriteInstance {},
	platform: class extends self.ISpriteInstance {},
	platform2: class extends self.ISpriteInstance {},
	platform3: class extends self.ISpriteInstance {},
	platform4: class extends self.ISpriteInstance {},
	rectangle: class extends self.ISpriteInstance {},
	RedBall: class extends self.ISpriteInstance {},
	restartbutton: class extends self.ISpriteInstance {},
	returnButton: class extends self.ISpriteInstance {},
	star: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	triggerMenu: class extends self.ISpriteInstance {},
	winLevel: class extends self.ISpriteInstance {},
	WinLogo: class extends self.ISpriteInstance {},
	winNext: class extends self.ISpriteInstance {},
	YellowBall: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	LevelPlace: class extends self.ISpriteInstance {},
	levelsLogo: class extends self.ISpriteInstance {},
	LevelNumber: class extends self.ISpriteFontInstance {},
	LevelNumber2: class extends self.ISpriteFontInstance {},
	textCompleted: class extends self.ISpriteFontInstance {},
	textLevel: class extends self.ISpriteFontInstance {},
	textTime: class extends self.ITextInstance {},
	Completed: class extends self.ISpriteFontInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	btn_more_in: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	fbg_eye: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	AllBalloon: class extends self.ISpriteInstance {},
	AllPlatforms: class extends self.ISpriteInstance {},
	AllWinParts: class extends self.ISpriteInstance {},
	AllButtons: class extends self.ISpriteInstance {},
	LoseWinObjects: class extends self.ISpriteInstance {}
}