const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Pathfinding,
		C3.Plugins.Touch,
		C3.Behaviors.destroy,
		C3.Behaviors.Tween,
		C3.Behaviors.Flash,
		C3.Plugins.Arr,
		C3.Plugins.Text,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Particles,
		C3.Plugins.WGSDK,
		C3.Plugins.ppstudio_ga4,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Acts.RegenerateMap,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.MoveTo.Acts.MoveAlongPathfindingPath,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Pathfinding.Acts.AddObstacle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Behaviors.MoveTo.Acts.MoveAlongTimelineByName,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.MoveTo.Exps.MovingAngle,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Behaviors.MoveTo.Cnds.CompareSpeed,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.ppstudio_ga4.Acts.GASendEvent,
		C3.Plugins.ppstudio_ga4.Acts.InitGA,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Plugins.System.Cnds.OnLoadFailed
	];
};
self.C3_JsPropNameTable = [
	{xAxis: 0},
	{yAxis: 0},
	{MoveTo: 0},
	{Pathfinding: 0},
	{Sprite: 0},
	{Touch: 0},
	{block: 0},
	{Asset: 0},
	{Front: 0},
	{Asset2: 0},
	{Asset3: 0},
	{trackId: 0},
	{hint: 0},
	{DestroyOutsideLayout: 0},
	{Tween: 0},
	{Flash: 0},
	{car: 0},
	{LevelNo: 0},
	{level: 0},
	{spriteX: 0},
	{spriteY: 0},
	{coin: 0},
	{Asset4: 0},
	{cointCount: 0},
	{blackScreenAsset: 0},
	{Rotate: 0},
	{Asset5: 0},
	{next: 0},
	{Asset6: 0},
	{levelText: 0},
	{moveText: 0},
	{carFrame: 0},
	{PositionIndexOfChangeDirection: 0},
	{destroyCarHint: 0},
	{hintText: 0},
	{destroyHint: 0},
	{arrow: 0},
	{retry: 0},
	{home: 0},
	{Asset7: 0},
	{setting: 0},
	{Asset8: 0},
	{Asset9: 0},
	{Asset10: 0},
	{Sine: 0},
	{Asset11: 0},
	{start: 0},
	{sound: 0},
	{music: 0},
	{Asset12: 0},
	{Asset13: 0},
	{Audio: 0},
	{life: 0},
	{Sine2: 0},
	{Confetti: 0},
	{Particles: 0},
	{home2: 0},
	{retry2: 0},
	{WeeGooSDK: 0},
	{GA4: 0},
	{arrayIndex: 0},
	{carUid: 0},
	{FrameWhileComingBack: 0},
	{carAnimation: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	block: class extends self.ISpriteInstance {},
	Asset: class extends self.ISpriteInstance {},
	Front: class extends self.ISpriteInstance {},
	Asset2: class extends self.ISpriteInstance {},
	Asset3: class extends self.ISpriteInstance {},
	car: class extends self.ISpriteInstance {},
	level: class extends self.ISpriteInstance {},
	spriteX: class extends self.IArrayInstance {},
	spriteY: class extends self.IArrayInstance {},
	coin: class extends self.ISpriteInstance {},
	Asset4: class extends self.ISpriteInstance {},
	cointCount: class extends self.ITextInstance {},
	blackScreenAsset: class extends self.ISpriteInstance {},
	Asset5: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	Asset6: class extends self.ISpriteInstance {},
	levelText: class extends self.ITextInstance {},
	moveText: class extends self.ITextInstance {},
	carFrame: class extends self.IArrayInstance {},
	PositionIndexOfChangeDirection: class extends self.IArrayInstance {},
	hint: class extends self.ISpriteInstance {},
	destroyCarHint: class extends self.ISpriteInstance {},
	hintText: class extends self.ITextInstance {},
	destroyHint: class extends self.ITextInstance {},
	arrow: class extends self.ISpriteInstance {},
	retry: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	Asset7: class extends self.ISpriteInstance {},
	setting: class extends self.ISpriteInstance {},
	Asset8: class extends self.ISpriteInstance {},
	Asset9: class extends self.ISpriteInstance {},
	Asset10: class extends self.ISpriteInstance {},
	Asset11: class extends self.ISpriteInstance {},
	start: class extends self.ISpriteInstance {},
	sound: class extends self.ISpriteInstance {},
	music: class extends self.ISpriteInstance {},
	Asset12: class extends self.ISpriteInstance {},
	Asset13: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	life: class extends self.ISpriteInstance {},
	Confetti: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	home2: class extends self.ISpriteInstance {},
	retry2: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	GA4: class extends self.IInstance {}
}