const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Plugins.Mouse,
		C3.Behaviors.destroy,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Plugins.Eponesh_GameScore,
		C3.Behaviors.Anchor,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Text.Acts.Destroy,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Physics.Acts.ApplyForceToward,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsPost,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Eponesh_GameScore.Acts.ChangeLanguage,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart
	];
};
self.C3_JsPropNameTable = [
	{Physics: 0},
	{Ground: 0},
	{Fade: 0},
	{Text: 0},
	{BackWheel: 0},
	{Mouse: 0},
	{size: 0},
	{DestroyOutsideLayout: 0},
	{CarBody: 0},
	{FrontWheel: 0},
	{Sprite: 0},
	{Touch: 0},
	{Keyboard: 0},
	{TiledBackground: 0},
	{Sprite2: 0},
	{draw: 0},
	{Text2: 0},
	{GamePush: 0},
	{Anchor: 0},
	{Sprite3: 0},
	{lvl: 0},
	{Sprite4: 0},
	{TiledBackground2: 0},
	{Sprite5: 0},
	{Text3: 0},
	{Sprite6: 0},
	{Text4: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{LocalStorage: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Family1: 0},
	{Lvl: 0},
	{Money: 0},
	{Car: 0},
	{DrawMode: 0}
];

self.InstanceType = {
	Ground: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	BackWheel: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	CarBody: class extends self.ISpriteInstance {},
	FrontWheel: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	GamePush: class extends self.C3.Plugins.Eponesh_GameScore.Instance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Family1: class extends self.ISpriteInstance {}
}