const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.Sin,
		C3.Behaviors.EightDir,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Behaviors.Pin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Plugins.Browser,
		C3.Plugins.Particles,
		C3.Plugins.ppstudio_ga4,
		C3.Plugins.WGSDK,
		C3.Plugins.PlatformInfo,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Touch.Cnds.OnDoubleTapGesture,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.ppstudio_ga4.Acts.InitGA,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.ppstudio_ga4.Acts.GASendEvent,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Sin.Acts.SetMovement
	];
};
self.C3_JsPropNameTable = [
	{STYLE: 0},
	{A: 0},
	{ACTIVE: 0},
	{LiteTween: 0},
	{BRICK: 0},
	{GO: 0},
	{BRICK2: 0},
	{DIS: 0},
	{Sine: 0},
	{"8Direction": 0},
	{SH: 0},
	{SMOKE: 0},
	{touchA: 0},
	{touchB: 0},
	{POINT: 0},
	{BG: 0},
	{menuBG: 0},
	{PANEL: 0},
	{TITLE: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{Audio: 0},
	{Pin: 0},
	{menuBUTTON: 0},
	{pauseBUTTON: 0},
	{playBUTTON: 0},
	{replayBUTTON: 0},
	{soundBUTTON: 0},
	{scoreTEXT: 0},
	{BEST: 0},
	{bestTEXT: 0},
	{scoreTEXT2: 0},
	{Fade: 0},
	{TUT: 0},
	{Browser: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{no_touch: 0},
	{tank_play_buy: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{HighScoreFont: 0},
	{LastScoreFont: 0},
	{Sprite7: 0},
	{Particles: 0},
	{Particles2: 0},
	{Particles3: 0},
	{Particles4: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{GA4: 0},
	{WeeGooSDK: 0},
	{PlatformInfo: 0},
	{SCORE: 0},
	{COUNT: 0},
	{ALLOW: 0},
	{GAMEOVER: 0},
	{MOVE: 0},
	{SPEED: 0},
	{DESTROY: 0},
	{reTOUCH: 0},
	{START: 0},
	{SILENT: 0},
	{PAUSE: 0}
];

self.InstanceType = {
	A: class extends self.ISpriteInstance {},
	BRICK: class extends self.ISpriteInstance {},
	BRICK2: class extends self.ISpriteInstance {},
	DIS: class extends self.ISpriteInstance {},
	SH: class extends self.ISpriteInstance {},
	SMOKE: class extends self.ISpriteInstance {},
	touchA: class extends self.ISpriteInstance {},
	touchB: class extends self.ISpriteInstance {},
	POINT: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	menuBG: class extends self.ISpriteInstance {},
	PANEL: class extends self.ISpriteInstance {},
	TITLE: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	menuBUTTON: class extends self.ISpriteInstance {},
	pauseBUTTON: class extends self.ISpriteInstance {},
	playBUTTON: class extends self.ISpriteInstance {},
	replayBUTTON: class extends self.ISpriteInstance {},
	soundBUTTON: class extends self.ISpriteInstance {},
	scoreTEXT: class extends self.ISpriteFontInstance {},
	BEST: class extends self.ISpriteInstance {},
	bestTEXT: class extends self.ISpriteFontInstance {},
	scoreTEXT2: class extends self.ISpriteFontInstance {},
	TUT: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	no_touch: class extends self.ISpriteInstance {},
	tank_play_buy: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	HighScoreFont: class extends self.ISpriteFontInstance {},
	LastScoreFont: class extends self.ISpriteFontInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Particles4: class extends self.IParticlesInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	GA4: class extends self.IInstance {},
	WeeGooSDK: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {}
}