const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.SetMuted
	];
};
self.C3_JsPropNameTable = [
	{bg: 0},
	{Tween: 0},
	{butterfly2: 0},
	{Sine: 0},
	{butterfly1: 0},
	{title: 0},
	{play: 0},
	{cloud: 0},
	{Asset: 0},
	{animation: 0},
	{match: 0},
	{Asset2: 0},
	{levelNo: 0},
	{level: 0},
	{Text: 0},
	{home: 0},
	{sound: 0},
	{Touch: 0},
	{Sprite: 0},
	{win: 0},
	{next: 0},
	{reset: 0},
	{lose: 0},
	{Audio: 0},
	{animation2: 0},
	{WeeGooSDK: 0}
];

self.InstanceType = {
	bg: class extends self.ISpriteInstance {},
	butterfly2: class extends self.ISpriteInstance {},
	butterfly1: class extends self.ISpriteInstance {},
	title: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	cloud: class extends self.ISpriteInstance {},
	Asset: class extends self.ISpriteInstance {},
	animation: class extends self.ISpriteInstance {},
	Asset2: class extends self.ISpriteInstance {},
	level: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	home: class extends self.ISpriteInstance {},
	sound: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	win: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	reset: class extends self.ISpriteInstance {},
	lose: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	animation2: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {}
}