const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Shape3D,
		C3.Behaviors.solid,
		C3.Plugins.Camera3D,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Rotate,
		C3.Behaviors.Tween,
		C3.Behaviors.LOS,
		C3.Behaviors.EightDir,
		C3.Plugins.Spritefont2,
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Behaviors.Sin,
		C3.Behaviors.Pin,
		C3.Plugins.LocalStorage,
		C3.Behaviors.lunarray_LiteTween,
		C3.Plugins.Browser,
		C3.Plugins.WGSDK,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Shape3D.Acts.SetHeight,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Shape3D.Acts.SetZHeight,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Shape3D.Acts.SetFaceObject,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Spritefont2.Exps.ZElevation,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Camera3D.Exps.CameraX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Camera3D.Exps.CameraY,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Shape3D.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Plugins.Shape3D.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Shape3D.Cnds.OnCollision,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Behaviors.solid.Cnds.IsEnabled,
		C3.Plugins.Shape3D.Acts.SubInstanceVar,
		C3.Plugins.Shape3D.Cnds.CompareInstanceVar,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Shape3D.Exps.Angle,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Shape3D.Exps.Count,
		C3.Plugins.Shape3D.Exps.ZHeight,
		C3.Plugins.Shape3D.Cnds.OnDestroyed,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Plugins.Shape3D.Acts.SetSize,
		C3.Plugins.Shape3D.Exps.Width,
		C3.Plugins.Shape3D.Exps.Height,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Shape3D.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Shape3D.Acts.SetBoolInstanceVar,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Shape3D.Acts.SetVisible,
		C3.Behaviors.Tween.Acts.SetEnabled,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.WGSDK.Cnds.RewardReady,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.WGSDK.Cnds.RewardClosed,
		C3.Plugins.WGSDK.Cnds.RewardGranted,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.LocalStorage.Cnds.OnAllGetsComplete,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.GoToLayoutByName
	];
};
self.C3_JsPropNameTable = [
	{GrassTexture1: 0},
	{GrassTexture2: 0},
	{GrassTexture3: 0},
	{RoofTexture1: 0},
	{RoofTexture2: 0},
	{RoofTexture3: 0},
	{RoofTexture4: 0},
	{WallTexture1: 0},
	{WallTexture2: 0},
	{WallTexture3: 0},
	{WallTexture4: 0},
	{CandleHolderTexture: 0},
	{PlayerTexture: 0},
	{Solid: 0},
	{Wall: 0},
	{"3DCamera": 0},
	{PlayerBillboard: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Spell: 0},
	{Ground: 0},
	{Heath: 0},
	{Rotate: 0},
	{Crystal: 0},
	{MaxCrystals: 0},
	{Tween: 0},
	{Door: 0},
	{ReadyToJump: 0},
	{LineOfSight: 0},
	{Monster: 0},
	{Particle: 0},
	{Beam: 0},
	{ShootingAngle: 0},
	{"8Direction": 0},
	{PlayerCollision: 0},
	{Crate: 0},
	{Tutorial: 0},
	{DecorationBillboard: 0},
	{Pillar: 0},
	{Temple: 0},
	{Trigger: 0},
	{TiledBackground: 0},
	{Ground2: 0},
	{Ground3: 0},
	{ctd_score: 0},
	{addmetakreklama: 0},
	{Sprite33: 0},
	{Touch: 0},
	{ctd_score2: 0},
	{Spell2: 0},
	{a: 0},
	{Wheel: 0},
	{Button: 0},
	{Pin: 0},
	{Text: 0},
	{zavrti: 0},
	{play: 0},
	{krug: 0},
	{play2: 0},
	{zavrti2: 0},
	{SpriteFont: 0},
	{ctd_score3: 0},
	{Sprite2: 0},
	{addtimereklama: 0},
	{Ground4: 0},
	{KONTROLASLIKA: 0},
	{gore: 0},
	{lijevo: 0},
	{dole: 0},
	{desno: 0},
	{Sprite4: 0},
	{BSound: 0},
	{Audio: 0},
	{home: 0},
	{PlatformInfo: 0},
	{Sine: 0},
	{START: 0},
	{Sprite5: 0},
	{TiledBackground2: 0},
	{Sprite: 0},
	{Ground5: 0},
	{Open: 0},
	{Level: 0},
	{LevelsBlock: 0},
	{select: 0},
	{SpriteFont123: 0},
	{LocalStorage: 0},
	{LevelsText: 0},
	{LiteTween: 0},
	{NEXTLEVEL: 0},
	{wheeloffortune: 0},
	{nexleveltext: 0},
	{"3DShape": 0},
	{Ground6: 0},
	{Ground7: 0},
	{Ground8: 0},
	{Ground9: 0},
	{ponovo: 0},
	{addmetakreklama2: 0},
	{ctd_score4: 0},
	{Ground10: 0},
	{Ground11: 0},
	{crnapozadina: 0},
	{Ground12: 0},
	{Ground13: 0},
	{laser: 0},
	{lasergif: 0},
	{Ground14: 0},
	{Ground15: 0},
	{Sprite6: 0},
	{Ground16: 0},
	{Sprite7: 0},
	{replay: 0},
	{Sprite8: 0},
	{moregames: 0},
	{dance: 0},
	{PlayerBillboard2: 0},
	{Ground17: 0},
	{zapucanje: 0},
	{Browser: 0},
	{y8: 0},
	{Loginy8moja: 0},
	{playerName: 0},
	{PUSKA: 0},
	{PUSKA2: 0},
	{Sprite3: 0},
	{winpanel2: 0},
	{WeeGooSDK: 0},
	{nagrade: 0},
	{Sprite9: 0},
	{kontrolemobilni: 0},
	{LastLevel: 0},
	{WIN: 0},
	{LevelComplete: 0},
	{LAST_LEVEL: 0},
	{sound: 0},
	{SoundEf: 0},
	{Seed: 0},
	{SPREAD: 0},
	{DistanceBuffer: 0},
	{AngleBuffer: 0},
	{TimeBuffer: 0},
	{PositionX: 0},
	{PositionY: 0},
	{Quantity: 0},
	{Color: 0},
	{JUMPTIME: 0},
	{COOLDOWN: 0},
	{sectorCount: 0},
	{prizes: 0},
	{winningSector: 0}
];

self.InstanceType = {
	GrassTexture1: class extends self.ISpriteInstance {},
	GrassTexture2: class extends self.ISpriteInstance {},
	GrassTexture3: class extends self.ISpriteInstance {},
	RoofTexture1: class extends self.ISpriteInstance {},
	RoofTexture2: class extends self.ISpriteInstance {},
	RoofTexture3: class extends self.ISpriteInstance {},
	RoofTexture4: class extends self.ISpriteInstance {},
	WallTexture1: class extends self.ISpriteInstance {},
	WallTexture2: class extends self.ISpriteInstance {},
	WallTexture3: class extends self.ISpriteInstance {},
	WallTexture4: class extends self.ISpriteInstance {},
	CandleHolderTexture: class extends self.ISpriteInstance {},
	PlayerTexture: class extends self.ISpriteInstance {},
	Wall: class extends self.I3DShapeInstance {},
	_3DCamera: class extends self.IInstance {},
	PlayerBillboard: class extends self.I3DShapeInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Spell: class extends self.I3DShapeInstance {},
	Ground: class extends self.ISpriteInstance {},
	Crystal: class extends self.I3DShapeInstance {},
	Door: class extends self.I3DShapeInstance {},
	Monster: class extends self.I3DShapeInstance {},
	Particle: class extends self.I3DShapeInstance {},
	Beam: class extends self.I3DShapeInstance {},
	PlayerCollision: class extends self.ISpriteInstance {},
	Crate: class extends self.I3DShapeInstance {},
	Tutorial: class extends self.ISpriteFontInstance {},
	DecorationBillboard: class extends self.I3DShapeInstance {},
	Pillar: class extends self.I3DShapeInstance {},
	Temple: class extends self.I3DShapeInstance {},
	Trigger: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Ground2: class extends self.ISpriteInstance {},
	Ground3: class extends self.ISpriteInstance {},
	ctd_score: class extends self.ISpriteFontInstance {},
	addmetakreklama: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	ctd_score2: class extends self.ISpriteFontInstance {},
	Spell2: class extends self.I3DShapeInstance {},
	Wheel: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	Pin: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	zavrti: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	krug: class extends self.ISpriteInstance {},
	play2: class extends self.ISpriteInstance {},
	zavrti2: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	ctd_score3: class extends self.ISpriteFontInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	addtimereklama: class extends self.ISpriteInstance {},
	Ground4: class extends self.ISpriteInstance {},
	KONTROLASLIKA: class extends self.ISpriteInstance {},
	gore: class extends self.ISpriteInstance {},
	lijevo: class extends self.ISpriteInstance {},
	dole: class extends self.ISpriteInstance {},
	desno: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	BSound: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	home: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	START: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Ground5: class extends self.ISpriteInstance {},
	LevelsBlock: class extends self.ISpriteInstance {},
	select: class extends self.ISpriteInstance {},
	SpriteFont123: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	LevelsText: class extends self.ISpriteFontInstance {},
	NEXTLEVEL: class extends self.ISpriteInstance {},
	wheeloffortune: class extends self.ISpriteInstance {},
	nexleveltext: class extends self.ISpriteInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	Ground6: class extends self.ISpriteInstance {},
	Ground7: class extends self.ISpriteInstance {},
	Ground8: class extends self.ISpriteInstance {},
	Ground9: class extends self.ISpriteInstance {},
	ponovo: class extends self.ISpriteInstance {},
	addmetakreklama2: class extends self.ISpriteInstance {},
	ctd_score4: class extends self.ISpriteFontInstance {},
	Ground10: class extends self.ISpriteInstance {},
	Ground11: class extends self.ISpriteInstance {},
	crnapozadina: class extends self.ISpriteInstance {},
	Ground12: class extends self.ISpriteInstance {},
	Ground13: class extends self.ISpriteInstance {},
	laser: class extends self.I3DShapeInstance {},
	lasergif: class extends self.ISpriteInstance {},
	Ground14: class extends self.ISpriteInstance {},
	Ground15: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Ground16: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	replay: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	moregames: class extends self.ISpriteInstance {},
	dance: class extends self.ISpriteInstance {},
	PlayerBillboard2: class extends self.I3DShapeInstance {},
	Ground17: class extends self.ISpriteInstance {},
	zapucanje: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	y8: class extends self.ISpriteInstance {},
	Loginy8moja: class extends self.ISpriteInstance {},
	playerName: class extends self.ITextInstance {},
	PUSKA: class extends self.ISpriteInstance {},
	PUSKA2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	winpanel2: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	nagrade: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	kontrolemobilni: class extends self.ISpriteInstance {}
}