const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Behaviors.destroy,
		C3.Behaviors.jumpthru,
		C3.Plugins.Eponesh_GameScore,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Behaviors.Anchor,
		C3.Plugins.PlatformInfo,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Eponesh_GameScore.Cnds.PaymentsIsPurchased,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStart,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Text.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Eponesh_GameScore.Cnds.AchievementsIsUnlocked,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSetScore,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStop,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Eponesh_GameScore.Cnds.PaymentsPickProduct,
		C3.Plugins.Eponesh_GameScore.Exps.PaymentsCurProductPrice,
		C3.Plugins.Eponesh_GameScore.Exps.PaymentsCurProductCurrencySymbol,
		C3.Plugins.Eponesh_GameScore.Acts.PaymentsPurchase,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardOpen,
		C3.Plugins.Eponesh_GameScore.Acts.AchievementsOpen,
		C3.Plugins.Eponesh_GameScore.Acts.ChangeLanguage,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.Plugins.Eponesh_GameScore.Acts.AchievementsUnlock
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{Sprite: 0},
	{Solid: 0},
	{TiledBackground: 0},
	{Sprite2: 0},
	{Touch: 0},
	{Keyboard: 0},
	{hp: 0},
	{DestroyOutsideLayout: 0},
	{block: 0},
	{block2: 0},
	{Jumpthru: 0},
	{block3: 0},
	{block4: 0},
	{GamePush: 0},
	{TiledBackground2: 0},
	{Bullet: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Text: 0},
	{Fade: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Anchor: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Text2: 0},
	{PlatformInfo: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{TiledBackground3: 0},
	{buy1: 0},
	{buy2: 0},
	{buy3: 0},
	{buy4: 0},
	{Text3: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{info: 0},
	{info2: 0},
	{info3: 0},
	{pc: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Text4: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{Sprite33: 0},
	{Sprite34: 0},
	{Family1: 0},
	{mode_ns: 0},
	{block_ns: 0},
	{not_save_winner: 0},
	{money: 0},
	{skin: 0},
	{not_save_control: 0},
	{RANDOMER: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	block: class extends self.ISpriteInstance {},
	block2: class extends self.ISpriteInstance {},
	block3: class extends self.ISpriteInstance {},
	block4: class extends self.ISpriteInstance {},
	GamePush: class extends self.C3.Plugins.Eponesh_GameScore.Instance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	PlatformInfo: class extends self.IInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	buy1: class extends self.ITextInstance {},
	buy2: class extends self.ITextInstance {},
	buy3: class extends self.ITextInstance {},
	buy4: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	info: class extends self.ITextInstance {},
	info2: class extends self.ITextInstance {},
	info3: class extends self.ITextInstance {},
	pc: class extends self.ITextInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Family1: class extends self.ISpriteInstance {}
}