const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.destroy,
		C3.Behaviors.scrollto,
		C3.Behaviors.Anchor,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.LocalStorage,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.TiledBg.Cnds.IsVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{TiledBackground: 0},
	{control: 0},
	{Sine: 0},
	{block1: 0},
	{Sprite: 0},
	{Platform: 0},
	{DestroyOutsideLayout: 0},
	{ScrollTo: 0},
	{Sprite2: 0},
	{Anchor: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{block2: 0},
	{Keyboard: 0},
	{Touch: 0},
	{lvl: 0},
	{Sprite7: 0},
	{block3: 0},
	{block4: 0},
	{Text: 0},
	{Sprite8: 0},
	{LVL: 0},
	{LocalStorage: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{PlatformInfo: 0},
	{GamePush: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	block1: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	block2: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	block3: class extends self.ITiledBackgroundInstance {},
	block4: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	LVL: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	GamePush: class extends self.C3.Plugins.Eponesh_GameScore.Instance {}
}