const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Behaviors.Tween,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.System.Cnds.OnCanvasSnapshot,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Audio.Acts.Preload,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetAnim
	];
};
self.C3_JsPropNameTable = [
	{bg: 0},
	{brushColor: 0},
	{frame_bg: 0},
	{frame2: 0},
	{images: 0},
	{brush: 0},
	{brush_size_local: 0},
	{color_size: 0},
	{tamanho: 0},
	{brushSize: 0},
	{eraser: 0},
	{pencil: 0},
	{mousePosition: 0},
	{brush_local: 0},
	{Touch: 0},
	{Browser: 0},
	{btn_camera: 0},
	{Mouse: 0},
	{frame: 0},
	{OpacityExit: 0},
	{BtnYes: 0},
	{BtnNo: 0},
	{TablePrint: 0},
	{Audio: 0},
	{btn_home: 0},
	{btn_reset: 0},
	{btn_more: 0},
	{TableExit: 0},
	{Y_exit: 0},
	{N_exit: 0},
	{Tween: 0},
	{lv: 0},
	{BtnSound: 0},
	{btn_back: 0},
	{btn_play: 0},
	{btn_more_games: 0},
	{Fade: 0},
	{NewKidsGames: 0},
	{Sine: 0},
	{title: 0},
	{ch1: 0},
	{ch2: 0},
	{image_car: 0},
	{select: 0},
	{Y8: 0},
	{paint: 0},
	{WeeGooSDK: 0},
	{Print: 0},
	{Exit: 0},
	{pencil_erase: 0},
	{id_pencil: 0},
	{ready: 0},
	{size: 0},
	{color: 0},
	{LevelSelect: 0},
	{Melody: 0}
];

self.InstanceType = {
	bg: class extends self.ISpriteInstance {},
	brushColor: class extends self.ISpriteInstance {},
	frame_bg: class extends self.ISpriteInstance {},
	frame2: class extends self.ISpriteInstance {},
	images: class extends self.ISpriteInstance {},
	brush: class extends self.ISpriteInstance {},
	brush_size_local: class extends self.ISpriteInstance {},
	color_size: class extends self.ISpriteInstance {},
	brushSize: class extends self.ISpriteInstance {},
	eraser: class extends self.ISpriteInstance {},
	pencil: class extends self.ISpriteInstance {},
	mousePosition: class extends self.ISpriteInstance {},
	brush_local: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	btn_camera: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	frame: class extends self.ISpriteInstance {},
	OpacityExit: class extends self.ISpriteInstance {},
	BtnYes: class extends self.ISpriteInstance {},
	BtnNo: class extends self.ISpriteInstance {},
	TablePrint: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	btn_home: class extends self.ISpriteInstance {},
	btn_reset: class extends self.ISpriteInstance {},
	btn_more: class extends self.ISpriteInstance {},
	TableExit: class extends self.ISpriteInstance {},
	Y_exit: class extends self.ISpriteInstance {},
	N_exit: class extends self.ISpriteInstance {},
	lv: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	btn_back: class extends self.ISpriteInstance {},
	btn_play: class extends self.ISpriteInstance {},
	btn_more_games: class extends self.ISpriteInstance {},
	NewKidsGames: class extends self.ISpriteInstance {},
	title: class extends self.ISpriteInstance {},
	ch1: class extends self.ISpriteInstance {},
	ch2: class extends self.ISpriteInstance {},
	image_car: class extends self.ISpriteInstance {},
	select: class extends self.ISpriteInstance {},
	Y8: class extends self.ISpriteInstance {},
	paint: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	Print: class extends self.ISpriteInstance {},
	Exit: class extends self.ISpriteInstance {}
}