const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Behaviors.destroy,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Timeline,
		C3.Plugins.Internationalization,
		C3.Plugins.Json,
		C3.Plugins.AJAX,
		C3.Plugins.PlatformInfo,
		C3.Plugins.LocalStorage,
		C3.Plugins.WGSDK,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Dictionary,
		C3.Plugins.Globals,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Globals.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.DragnDrop.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Internationalization.Exps.Lookup,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.JavaScriptInEvents.Commonlogic_Event12_Act1,
		C3.Plugins.Globals.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Globals.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Globals.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Globals.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Internationalization.Acts.LoadFromJSON,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Internationalization.Acts.SetLocale,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Acts.SetLayerHTML,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.LoadLayoutTextures,
		C3.Plugins.System.Cnds.OnImageLoadingComplete,
		C3.Plugins.System.Acts.GoToLayoutByName
	];
};
self.C3_JsPropNameTable = [
	{index: 0},
	{distance: 0},
	{FrameVE: 0},
	{active: 0},
	{placeHolderIndex: 0},
	{movetoX: 0},
	{movetoY: 0},
	{scaleto: 0},
	{DragDrop: 0},
	{PieceVE: 0},
	{puzzle: 0},
	{Sine: 0},
	{Tween: 0},
	{ThumbnailsVeryEasy: 0},
	{FrameE: 0},
	{PieceE: 0},
	{ThumbnailsEasy: 0},
	{FrameN: 0},
	{PieceN: 0},
	{DestroyOutsideLayout: 0},
	{ThumbnailsNormal: 0},
	{Touch: 0},
	{Mouse: 0},
	{Audio: 0},
	{Browser: 0},
	{TimelineController: 0},
	{Internationalization: 0},
	{JSON: 0},
	{AJAX: 0},
	{PlatformInfo: 0},
	{LocalStorage: 0},
	{WeeGooSDK: 0},
	{grass: 0},
	{PlayBtn: 0},
	{HeaderText: 0},
	{MainMenuAnimals: 0},
	{MenuContainer: 0},
	{mode: 0},
	{MenuBtn: 0},
	{DifSelect: 0},
	{lang: 0},
	{Langs: 0},
	{LangMenuTooltip: 0},
	{VE: 0},
	{EA: 0},
	{NO: 0},
	{GameModes: 0},
	{Bat: 0},
	{Giraffe: 0},
	{Cat: 0},
	{Chicken: 0},
	{Cow: 0},
	{Crocodile: 0},
	{Deer: 0},
	{Dog: 0},
	{Duck: 0},
	{Elephant: 0},
	{Fox: 0},
	{Goat: 0},
	{Goose: 0},
	{Hippo: 0},
	{Horse: 0},
	{Lamb: 0},
	{Leopard: 0},
	{Lion: 0},
	{Moose: 0},
	{Pig: 0},
	{Tiger: 0},
	{Turtle: 0},
	{Wolf: 0},
	{AnimalsName: 0},
	{MainMenu: 0},
	{LangMenu: 0},
	{Menues: 0},
	{close: 0},
	{overlay: 0},
	{pieceIndex: 0},
	{placeHolder: 0},
	{PlayerPlayBtn: 0},
	{txtLog: 0},
	{txtLog2: 0},
	{next: 0},
	{prew: 0},
	{WinText: 0},
	{PlayerIsPlaying: 0},
	{PlayerStarted: 0},
	{Player: 0},
	{SelectedIndex: 0},
	{MagnetDistance: 0},
	{Distance: 0},
	{RemainingPieces: 0},
	{PlayerWon: 0},
	{ImageName: 0},
	{GameDifficult: 0},
	{SelectedImageIndex: 0},
	{MaxPazzleCount: 0},
	{GameLanguage: 0},
	{Game: 0},
	{CurrentMenu: 0},
	{ShowAdCounter: 0},
	{Imageframe800x: 0},
	{pieceHolder: 0},
	{newbg: 0},
	{settings: 0},
	{iPiece: 0},
	{iPlace: 0},
	{moveBack: 0},
	{NextLayout: 0},
	{itemSelected: 0}
];

self.InstanceType = {
	FrameVE: class extends self.ISpriteInstance {},
	PieceVE: class extends self.ISpriteInstance {},
	ThumbnailsVeryEasy: class extends self.ISpriteInstance {},
	FrameE: class extends self.ISpriteInstance {},
	PieceE: class extends self.ISpriteInstance {},
	ThumbnailsEasy: class extends self.ISpriteInstance {},
	FrameN: class extends self.ISpriteInstance {},
	PieceN: class extends self.ISpriteInstance {},
	ThumbnailsNormal: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	TimelineController: class extends self.IInstance {},
	Internationalization: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	AJAX: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	WeeGooSDK: class extends self.IInstance {},
	grass: class extends self.ISpriteInstance {},
	PlayBtn: class extends self.ISpriteInstance {},
	HeaderText: class extends self.ITextInstance {},
	MainMenuAnimals: class extends self.ISpriteInstance {},
	MenuContainer: class extends self.ISpriteInstance {},
	MenuBtn: class extends self.IButtonInstance {},
	DifSelect: class extends self.ISpriteInstance {},
	Langs: class extends self.ISpriteInstance {},
	LangMenuTooltip: class extends self.ITextInstance {},
	GameModes: class extends self.IDictionaryInstance {},
	AnimalsName: class extends self.IDictionaryInstance {},
	Menues: class extends self.IDictionaryInstance {},
	close: class extends self.ISpriteInstance {},
	overlay: class extends self.ISpriteInstance {},
	placeHolder: class extends self.ISpriteInstance {},
	PlayerPlayBtn: class extends self.ISpriteInstance {},
	txtLog: class extends self.ITextInstance {},
	txtLog2: class extends self.ITextInstance {},
	next: class extends self.ISpriteInstance {},
	prew: class extends self.ISpriteInstance {},
	WinText: class extends self.ITextInstance {},
	Player: class extends self.IInstance {},
	Game: class extends self.IInstance {},
	MainMenu: class extends self.IInstance {},
	Imageframe800x: class extends self.ISpriteInstance {},
	pieceHolder: class extends self.ISpriteInstance {},
	newbg: class extends self.ISpriteInstance {},
	settings: class extends self.ISpriteInstance {}
}