const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Behaviors.Bullet,
		C3.Behaviors.Pin,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Behaviors.Orbit,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.shadowlight,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Rotate,
		C3.Plugins.WGSDK,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetElasticity,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Browser.Exps.ExecJS,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Orbit.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.ApplyImpulseToward,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Behaviors.Physics.Acts.RemoveJoints,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Physics: 0},
	{ground: 0},
	{player: 0},
	{str: 0},
	{launched: 0},
	{Bullet: 0},
	{Pin: 0},
	{strijela: 0},
	{Mouse: 0},
	{fakePivot: 0},
	{Text: 0},
	{zid: 0},
	{arrow2: 0},
	{Touch: 0},
	{DragDrop: 0},
	{povlacenje: 0},
	{xhand: 0},
	{strijela2: 0},
	{zidcrni: 0},
	{ToolTip: 0},
	{CartoonFire2: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{labubu: 0},
	{Sine: 0},
	{Orbit: 0},
	{Checker: 0},
	{Head: 0},
	{RightArm: 0},
	{LeftLeg: 0},
	{RightLeg: 0},
	{Body: 0},
	{LeftArm: 0},
	{Blood: 0},
	{Sprite6: 0},
	{Sprite4: 0},
	{podloga: 0},
	{play: 0},
	{moregames: 0},
	{Browser: 0},
	{Sprite7: 0},
	{trava: 0},
	{SemiRealFire2: 0},
	{FireSparks: 0},
	{Sprite20: 0},
	{BSound: 0},
	{Audio: 0},
	{ShadowLight: 0},
	{Particles: 0},
	{RestartBtn: 0},
	{menu: 0},
	{Sprite5: 0},
	{again: 0},
	{Sprite8: 0},
	{dalje: 0},
	{Sprite9: 0},
	{Blood2: 0},
	{totem: 0},
	{portal: 0},
	{portal2: 0},
	{strijelazaportal: 0},
	{strijelazaportalzajabuku: 0},
	{Sprite10: 0},
	{slike: 0},
	{strijela3: 0},
	{portal3: 0},
	{portal4: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{skip: 0},
	{ruka: 0},
	{maja: 0},
	{BG_Table: 0},
	{HOME2: 0},
	{igraj: 0},
	{more2: 0},
	{Sprite15: 0},
	{steve2: 0},
	{Rope0: 0},
	{Rope1: 0},
	{Rope2: 0},
	{Rope3: 0},
	{Rope4: 0},
	{Rope5: 0},
	{Rope6: 0},
	{Wheel1: 0},
	{kugla: 0},
	{uze: 0},
	{Sprite3: 0},
	{curScale: 0},
	{TrailGlow: 0},
	{OldX: 0},
	{OldY: 0},
	{trailCreator: 0},
	{ScoreText: 0},
	{LocalStorage: 0},
	{TheHighscore: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite33: 0},
	{strijelakasjena2: 0},
	{spawner: 0},
	{Sprite18: 0},
	{Checker2: 0},
	{BG_Table2: 0},
	{vodadonja: 0},
	{Sprite21: 0},
	{prskalovoda: 0},
	{Sprite19: 0},
	{Confetti: 0},
	{prskalovoda2: 0},
	{drvo: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{FireParticles: 0},
	{lagged: 0},
	{Rotate: 0},
	{kocka: 0},
	{euro: 0},
	{kocka2: 0},
	{ponovo: 0},
	{ScoreText2: 0},
	{euro2: 0},
	{euro3: 0},
	{godina: 0},
	{Sprite11: 0},
	{Text2: 0},
	{WeeGooSDK: 0},
	{buddy: 0},
	{buttons: 0},
	{konopac: 0},
	{ropefamilija: 0},
	{a: 0},
	{sound: 0},
	{SoundEf: 0},
	{Score: 0},
	{jabukepoeni: 0},
	{Highscore: 0},
	{distPivot: 0},
	{xHand: 0},
	{yHand: 0},
	{x: 0},
	{y: 0},
	{wiggle: 0}
];

self.InstanceType = {
	ground: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	strijela: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	fakePivot: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	zid: class extends self.ISpriteInstance {},
	arrow2: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	povlacenje: class extends self.ISpriteInstance {},
	xhand: class extends self.ISpriteInstance {},
	strijela2: class extends self.ISpriteInstance {},
	zidcrni: class extends self.ISpriteInstance {},
	CartoonFire2: class extends self.IParticlesInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	labubu: class extends self.ISpriteInstance {},
	Checker: class extends self.ISpriteInstance {},
	Head: class extends self.ISpriteInstance {},
	RightArm: class extends self.ISpriteInstance {},
	LeftLeg: class extends self.ISpriteInstance {},
	RightLeg: class extends self.ISpriteInstance {},
	Body: class extends self.ISpriteInstance {},
	LeftArm: class extends self.ISpriteInstance {},
	Blood: class extends self.IParticlesInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	podloga: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	moregames: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	trava: class extends self.ISpriteInstance {},
	SemiRealFire2: class extends self.IParticlesInstance {},
	FireSparks: class extends self.IParticlesInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	BSound: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	Particles: class extends self.IParticlesInstance {},
	RestartBtn: class extends self.ISpriteInstance {},
	menu: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	again: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	dalje: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Blood2: class extends self.IParticlesInstance {},
	totem: class extends self.ISpriteInstance {},
	portal: class extends self.ISpriteInstance {},
	portal2: class extends self.ISpriteInstance {},
	strijelazaportal: class extends self.ISpriteInstance {},
	strijelazaportalzajabuku: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	slike: class extends self.ISpriteInstance {},
	strijela3: class extends self.ISpriteInstance {},
	portal3: class extends self.ISpriteInstance {},
	portal4: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	skip: class extends self.ISpriteInstance {},
	ruka: class extends self.ISpriteInstance {},
	maja: class extends self.ISpriteInstance {},
	BG_Table: class extends self.ISpriteInstance {},
	HOME2: class extends self.ISpriteInstance {},
	igraj: class extends self.ISpriteInstance {},
	more2: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	steve2: class extends self.ISpriteInstance {},
	Rope0: class extends self.ISpriteInstance {},
	Rope1: class extends self.ISpriteInstance {},
	Rope2: class extends self.ISpriteInstance {},
	Rope3: class extends self.ISpriteInstance {},
	Rope4: class extends self.ISpriteInstance {},
	Rope5: class extends self.ISpriteInstance {},
	Rope6: class extends self.ISpriteInstance {},
	Wheel1: class extends self.ISpriteInstance {},
	kugla: class extends self.ISpriteInstance {},
	uze: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TrailGlow: class extends self.ISpriteInstance {},
	trailCreator: class extends self.ISpriteInstance {},
	ScoreText: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	TheHighscore: class extends self.ITextInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	strijelakasjena2: class extends self.ISpriteInstance {},
	spawner: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Checker2: class extends self.ISpriteInstance {},
	BG_Table2: class extends self.ISpriteInstance {},
	vodadonja: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	prskalovoda: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Confetti: class extends self.IParticlesInstance {},
	prskalovoda2: class extends self.ISpriteInstance {},
	drvo: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	FireParticles: class extends self.IParticlesInstance {},
	lagged: class extends self.ISpriteInstance {},
	kocka: class extends self.ISpriteInstance {},
	euro: class extends self.ISpriteInstance {},
	kocka2: class extends self.ISpriteInstance {},
	ponovo: class extends self.ISpriteInstance {},
	ScoreText2: class extends self.ITextInstance {},
	euro2: class extends self.ISpriteInstance {},
	euro3: class extends self.ISpriteInstance {},
	godina: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	WeeGooSDK: class extends C3.Plugins.WGSDK.Instance {},
	buddy: class extends self.ISpriteInstance {},
	buttons: class extends self.ISpriteInstance {},
	konopac: class extends self.ISpriteInstance {},
	ropefamilija: class extends self.ISpriteInstance {}
}