const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Arr,
		C3.Plugins.Dictionary,
		C3.Plugins.LocalStorage,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.Rotate,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Tween,
		C3.Behaviors.Physics,
		C3.Behaviors.destroy,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Behaviors.scrollto,
		C3.Plugins.Spritefont2,
		C3.Plugins.TextBox,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Date,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Exps.float,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.System.Exps.rgba255,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Behaviors.Physics.Acts.ApplyForce,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Exps.layoutheight,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Json.Exps.ToBeautifiedString,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardSetRecord,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardPublishRecord,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStop,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsFullscreenClose,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardOpenScoped,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedClose,
		C3.Plugins.Eponesh_GameScore.Cnds.OnRewardsGiveError,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData
	];
};
self.C3_JsPropNameTable = [
	{Array_Helpers: 0},
	{Array_Numbers: 0},
	{Array_Positions: 0},
	{Array_NumberRandom: 0},
	{Dic_Colors: 0},
	{Array_Colors: 0},
	{LocalStorage: 0},
	{AJAX: 0},
	{JSON_Config: 0},
	{Touch: 0},
	{Audio: 0},
	{board: 0},
	{bg: 0},
	{bg_frame: 0},
	{Rotate: 0},
	{bgHuan: 0},
	{uid_template: 0},
	{value: 0},
	{is_new: 0},
	{uid_target: 0},
	{is_fall: 0},
	{time_delay: 0},
	{MoveTo: 0},
	{Tween: 0},
	{Physics: 0},
	{DestroyOutsideLayout: 0},
	{ball: 0},
	{xian: 0},
	{list_checker: 0},
	{mark_y: 0},
	{value_temp: 0},
	{is_spawner_ball: 0},
	{row: 0},
	{col: 0},
	{is_target: 0},
	{count_merge: 0},
	{count_merge_temp: 0},
	{total_merge: 0},
	{is_exist_ball_new: 0},
	{ball_template: 0},
	{ball_point_shoot: 0},
	{ball_point_shoot_pre: 0},
	{template7: 0},
	{template6: 0},
	{checker: 0},
	{checker_point: 0},
	{point_spawn: 0},
	{Keyboard: 0},
	{drag_container: 0},
	{arrow: 0},
	{active: 0},
	{order: 0},
	{type: 0},
	{Game_Dot: 0},
	{ball_check: 0},
	{wall_left: 0},
	{wall_right: 0},
	{wall_top: 0},
	{ball_tip: 0},
	{state_shoot: 0},
	{index_move: 0},
	{is_shoot: 0},
	{ball_shoot: 0},
	{point_order: 0},
	{point_move: 0},
	{destroy_container: 0},
	{checker_ball_spawner: 0},
	{lives: 0},
	{txt_lives: 0},
	{Fade: 0},
	{Block_Effect: 0},
	{btn_bomb: 0},
	{mergeGuang: 0},
	{change_hint: 0},
	{rays: 0},
	{is_icon: 0},
	{skip_ball_btn: 0},
	{rocket: 0},
	{rocket_cover: 0},
	{bg_score: 0},
	{rect: 0},
	{xicon: 0},
	{btn_sound: 0},
	{is_victory: 0},
	{btn_rank: 0},
	{ScrollTo: 0},
	{shake: 0},
	{checker_bomb: 0},
	{count_move: 0},
	{score_extra_txt: 0},
	{score_txt: 0},
	{btn_ads_skip_ball: 0},
	{score_txt2: 0},
	{skip_ball_txt: 0},
	{videomarketing: 0},
	{ad_icon: 0},
	{circle: 0},
	{speed: 0},
	{speed_change: 0},
	{count_frame: 0},
	{G_Line: 0},
	{w: 0},
	{h: 0},
	{icon_medal: 0},
	{ball_over_bg: 0},
	{checker_ball_lose: 0},
	{Game_CheckCollision: 0},
	{logo: 0},
	{Bubble_pop_3d_kids_cartoon_editable_text_effect: 0},
	{loading_bar_bg: 0},
	{loading_bar: 0},
	{bg_controller: 0},
	{relive_btn: 0},
	{relive_bar: 0},
	{score_txt3: 0},
	{relive_title: 0},
	{relive_controller: 0},
	{over_controller: 0},
	{score_panel: 0},
	{title_game_over: 0},
	{huangguan: 0},
	{score_best_txt: 0},
	{btn_restart: 0},
	{btn_play_txt: 0},
	{victory_controller: 0},
	{title_vitcotyr: 0},
	{title_setting: 0},
	{box: 0},
	{remove_btn: 0},
	{btn_lang: 0},
	{bg_input: 0},
	{btn_continue: 0},
	{btn_edit: 0},
	{btn_continue_txt: 0},
	{TextInput: 0},
	{setting_btn: 0},
	{GamePush: 0},
	{Date: 0},
	{setting_controllerv2: 0},
	{combo: 0},
	{fx_bomb2: 0},
	{fx_rocket2: 0},
	{fx_smoke2: 0},
	{FamilyTemplates: 0},
	{FamilyTemplate: 0},
	{balls_offset: 0},
	{balls_size: 0},
	{balls_isMergeActive: 0},
	{balls_numberMax: 0},
	{balls_indexNumRandomMax: 0},
	{balls_rowIndex: 0},
	{balls_listConnect: 0},
	{balls_isStart: 0},
	{balls_isUseBomb: 0},
	{balls_rocket_count: 0},
	{balls_rocket_target: 0},
	{balls_rocket_stepHeight: 0},
	{balls_rocket_height: 0},
	{balls_level: 0},
	{balls_skipNumber: 0},
	{balls_listMatch: 0},
	{balls_isRelive: 0},
	{balls_isEnd: 0},
	{balls_isTouch: 0},
	{relive_timer: 0},
	{relive_btn_isPress: 0},
	{relive_isTimer: 0},
	{audio_merge_index: 0},
	{item: 0},
	{pos_x: 0},
	{pos_y: 0},
	{y_spawner: 0},
	{is_spawer: 0},
	{y_spawner_set: 0},
	{row_index: 0},
	{is_add_template: 0},
	{row_max: 0},
	{is_valid: 0},
	{index_random: 0},
	{is_non_effect: 0},
	{is_over_bg: 0},
	{return_value: 0},
	{ratio: 0},
	{max_num: 0},
	{index: 0},
	{angle_shoot: 0},
	{vec_x: 0},
	{vec_y: 0},
	{x: 0},
	{y: 0},
	{is_break: 0},
	{uid_ball_template: 0},
	{x_prev: 0},
	{y_prev: 0},
	{count: 0},
	{num_dots: 0},
	{angle_dot: 0},
	{vx: 0},
	{vy: 0},
	{x_next: 0},
	{y_next: 0},
	{is_merge: 0},
	{row_min: 0},
	{list: 0},
	{x_target: 0},
	{y_target: 0},
	{is_same_row: 0},
	{x_start: 0},
	{y_start: 0},
	{x_min: 0},
	{y_min: 0},
	{x_max: 0},
	{y_max: 0},
	{length: 0},
	{uid: 0},
	{size: 0},
	{dist: 0},
	{x_end: 0},
	{y_end: 0},
	{UI_isLocked: 0},
	{Ads_stateRelive: 0},
	{UI_isAudio: 0},
	{score_positionX: 0},
	{score_positionY: 0},
	{score: 0},
	{score_update: 0},
	{score_extra: 0},
	{loading_barWidth: 0},
	{loading_barStep: 0},
	{key_main: 0},
	{loader_count: 0}
];

self.InstanceType = {
	Array_Helpers: class extends self.IArrayInstance {},
	Array_Numbers: class extends self.IArrayInstance {},
	Array_Positions: class extends self.IArrayInstance {},
	Array_NumberRandom: class extends self.IArrayInstance {},
	Dic_Colors: class extends self.IDictionaryInstance {},
	Array_Colors: class extends self.IArrayInstance {},
	LocalStorage: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	JSON_Config: class extends self.IJSONInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	board: class extends self.ISpriteInstance {},
	bg: class extends self.ITiledBackgroundInstance {},
	bg_frame: class extends self.ISpriteInstance {},
	bgHuan: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	xian: class extends self.ISpriteInstance {},
	ball_template: class extends self.ISpriteInstance {},
	ball_point_shoot: class extends self.ISpriteInstance {},
	ball_point_shoot_pre: class extends self.ISpriteInstance {},
	template7: class extends self.ISpriteInstance {},
	template6: class extends self.ISpriteInstance {},
	checker: class extends self.ISpriteInstance {},
	checker_point: class extends self.ISpriteInstance {},
	point_spawn: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	drag_container: class extends self.ISpriteInstance {},
	arrow: class extends self.ISpriteInstance {},
	Game_Dot: class extends self.ISpriteInstance {},
	ball_check: class extends self.ISpriteInstance {},
	wall_left: class extends self.ISpriteInstance {},
	wall_right: class extends self.ISpriteInstance {},
	wall_top: class extends self.ISpriteInstance {},
	ball_tip: class extends self.ISpriteInstance {},
	ball_shoot: class extends self.ISpriteInstance {},
	point_move: class extends self.ISpriteInstance {},
	destroy_container: class extends self.ISpriteInstance {},
	checker_ball_spawner: class extends self.ISpriteInstance {},
	txt_lives: class extends self.ITextInstance {},
	Block_Effect: class extends self.ISpriteInstance {},
	btn_bomb: class extends self.ISpriteInstance {},
	mergeGuang: class extends self.ISpriteInstance {},
	change_hint: class extends self.ISpriteInstance {},
	rays: class extends self.ISpriteInstance {},
	skip_ball_btn: class extends self.ISpriteInstance {},
	rocket: class extends self.ISpriteInstance {},
	rocket_cover: class extends self.ITiledBackgroundInstance {},
	bg_score: class extends self.ISpriteInstance {},
	rect: class extends self.ISpriteInstance {},
	xicon: class extends self.ISpriteInstance {},
	btn_sound: class extends self.ISpriteInstance {},
	btn_rank: class extends self.ISpriteInstance {},
	shake: class extends self.ISpriteInstance {},
	checker_bomb: class extends self.ISpriteInstance {},
	score_extra_txt: class extends self.ISpriteFontInstance {},
	score_txt: class extends self.ISpriteFontInstance {},
	btn_ads_skip_ball: class extends self.ISpriteInstance {},
	score_txt2: class extends self.ISpriteFontInstance {},
	skip_ball_txt: class extends self.ISpriteFontInstance {},
	videomarketing: class extends self.ISpriteInstance {},
	ad_icon: class extends self.ISpriteInstance {},
	circle: class extends self.ISpriteInstance {},
	G_Line: class extends self.ITiledBackgroundInstance {},
	icon_medal: class extends self.ISpriteInstance {},
	ball_over_bg: class extends self.ISpriteInstance {},
	checker_ball_lose: class extends self.ISpriteInstance {},
	Game_CheckCollision: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	Bubble_pop_3d_kids_cartoon_editable_text_effect: class extends self.ISpriteInstance {},
	loading_bar_bg: class extends self.ISpriteInstance {},
	loading_bar: class extends self.ITiledBackgroundInstance {},
	bg_controller: class extends self.ISpriteInstance {},
	relive_btn: class extends self.ISpriteInstance {},
	relive_bar: class extends self.ISpriteInstance {},
	score_txt3: class extends self.ISpriteFontInstance {},
	relive_title: class extends self.ISpriteInstance {},
	relive_controller: class extends self.ISpriteInstance {},
	over_controller: class extends self.ISpriteInstance {},
	score_panel: class extends self.ISpriteInstance {},
	title_game_over: class extends self.ISpriteInstance {},
	huangguan: class extends self.ISpriteInstance {},
	score_best_txt: class extends self.ISpriteFontInstance {},
	btn_restart: class extends self.ISpriteInstance {},
	btn_play_txt: class extends self.ISpriteInstance {},
	victory_controller: class extends self.ISpriteInstance {},
	title_vitcotyr: class extends self.ISpriteInstance {},
	title_setting: class extends self.ISpriteInstance {},
	box: class extends self.ISpriteInstance {},
	remove_btn: class extends self.ISpriteInstance {},
	btn_lang: class extends self.ISpriteInstance {},
	bg_input: class extends self.ISpriteInstance {},
	btn_continue: class extends self.ISpriteInstance {},
	btn_edit: class extends self.ISpriteInstance {},
	btn_continue_txt: class extends self.ISpriteInstance {},
	TextInput: class extends self.ITextInputInstance {},
	setting_btn: class extends self.ISpriteInstance {},
	GamePush: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	Date: class extends self.IInstance {},
	setting_controllerv2: class extends self.ISpriteInstance {},
	combo: class extends self.ISpriteInstance {},
	fx_bomb2: class extends self.ISpriteInstance {},
	fx_rocket2: class extends self.ISpriteInstance {},
	fx_smoke2: class extends self.ISpriteInstance {},
	FamilyTemplates: class extends self.ISpriteInstance {},
	FamilyTemplate: class extends self.ISpriteInstance {}
}