const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Rotate,
		C3.Plugins.Touch,
		C3.Behaviors.Sin,
		C3.Behaviors.Physics,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Function,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Flash,
		C3.Plugins.Particles,
		C3.Behaviors.Pin,
		C3.Plugins.WGSDK,
		C3.Plugins.PlatformInfo,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Browser.Acts.ExecJs,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.time,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Browser.Acts.RequestFullScreen
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{Platform: 0},
	{Rotate: 0},
	{planeGreen: 0},
	{Touch: 0},
	{groundRock: 0},
	{Sine: 0},
	{rockIceDown: 0},
	{Physics: 0},
	{rockIceUp: 0},
	{Bullet: 0},
	{Fade: 0},
	{puffLarge: 0},
	{LocalStorage: 0},
	{Browser: 0},
	{Audio: 0},
	{Function: 0},
	{Sprite7: 0},
	{txtMnScore: 0},
	{txtHighScore: 0},
	{Flash: 0},
	{btnPlay: 0},
	{btnSound: 0},
	{BatRider: 0},
	{shoot: 0},
	{batShooter: 0},
	{batfire: 0},
	{cocoBullet: 0},
	{smoke: 0},
	{touchareaMove: 0},
	{touchareaShoot: 0},
	{eye: 0},
	{eye2: 0},
	{eye3: 0},
	{Particles: 0},
	{Pin: 0},
	{Sprite4: 0},
	{txtScore: 0},
	{btnHome: 0},
	{Sprite16: 0},
	{DamageParticle1: 0},
	{DamageParticle2: 0},
	{Life: 0},
	{Sprite2: 0},
	{WeeGooSDK: 0},
	{PlatformInfo: 0},
	{canfire: 0},
	{ready: 0},
	{DownRockCreate: 0},
	{upRockCreate: 0},
	{rockup: 0},
	{lose: 0},
	{health: 0},
	{shooterbatTime: 0},
	{riderbatTime: 0},
	{rockdown: 0},
	{dtsum: 0},
	{tscale: 0},
	{dtCount: 0},
	{check: 0},
	{HighScore: 0},
	{timer: 0},
	{object: 0},
	{Hiscore: 0},
	{Score: 0},
	{speed: 0},
	{Sound: 0},
	{HighScore2: 0},
	{timer2: 0}
];

self.InstanceType = {
	background: class extends self.ISpriteInstance {},
	planeGreen: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	groundRock: class extends self.ISpriteInstance {},
	rockIceDown: class extends self.ISpriteInstance {},
	rockIceUp: class extends self.ISpriteInstance {},
	puffLarge: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	txtMnScore: class extends self.ISpriteFontInstance {},
	txtHighScore: class extends self.ISpriteFontInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	btnSound: class extends self.ISpriteInstance {},
	BatRider: class extends self.ISpriteInstance {},
	batShooter: class extends self.ISpriteInstance {},
	batfire: class extends self.ISpriteInstance {},
	cocoBullet: class extends self.ISpriteInstance {},
	smoke: class extends self.IParticlesInstance {},
	touchareaMove: class extends self.ISpriteInstance {},
	touchareaShoot: class extends self.ISpriteInstance {},
	eye: class extends self.ISpriteInstance {},
	eye2: class extends self.ISpriteInstance {},
	eye3: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	txtScore: class extends self.ISpriteFontInstance {},
	btnHome: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	DamageParticle1: class extends self.IParticlesInstance {},
	DamageParticle2: class extends self.IParticlesInstance {},
	Life: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {}
}