const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Plugins.Spritefont2,
		C3.Plugins.WGSDK,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.PlatformInfo.Cnds.IsOnMacOS,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.WGSDK.Cnds.RewardGranted
	];
};
self.C3_JsPropNameTable = [
	{beh_solid: 0},
	{map_ground: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Player1: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{homes: 0},
	{Audio: 0},
	{sol: 0},
	{zipla: 0},
	{PlatformInfo: 0},
	{Rotate: 0},
	{Sprite5: 0},
	{next: 0},
	{Solid: 0},
	{duvar: 0},
	{olme: 0},
	{replay2: 0},
	{dikenengel: 0},
	{Sine: 0},
	{starts: 0},
	{Sprite4: 0},
	{pcttus: 0},
	{Coin: 0},
	{tap: 0},
	{duvarss: 0},
	{topspawn: 0},
	{TiledBackground2: 0},
	{Sprite2: 0},
	{tunel: 0},
	{solid: 0},
	{Tween: 0},
	{Sprite9: 0},
	{Sprite11: 0},
	{type: 0},
	{Text: 0},
	{Array: 0},
	{hometepe: 0},
	{homegit: 0},
	{skipads: 0},
	{cointext: 0},
	{tikla: 0},
	{Text2: 0},
	{cointextt: 0},
	{Sprite: 0},
	{TiledBackground: 0},
	{TiledBackground4: 0},
	{Sprite6: 0},
	{TiledBackground5: 0},
	{engel: 0},
	{devzombi: 0},
	{zombizipla: 0},
	{Sprite3: 0},
	{starts2: 0},
	{WeeGooSDK: 0},
	{labubuskatelevels: 0},
	{labubuskatescores: 0},
	{music: 0},
	{pause: 0},
	{P1Skin: 0},
	{P1SkinSelect: 0},
	{reward: 0}
];

self.InstanceType = {
	map_ground: class extends self.ITilemapInstance {},
	Player1: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	homes: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	sol: class extends self.ISpriteInstance {},
	zipla: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	duvar: class extends self.ISpriteInstance {},
	olme: class extends self.ISpriteInstance {},
	replay2: class extends self.ISpriteInstance {},
	dikenengel: class extends self.ISpriteInstance {},
	starts: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	pcttus: class extends self.ISpriteInstance {},
	Coin: class extends self.ISpriteInstance {},
	tap: class extends self.ISpriteInstance {},
	duvarss: class extends self.ISpriteInstance {},
	topspawn: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	tunel: class extends self.ISpriteInstance {},
	solid: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Array: class extends self.IArrayInstance {},
	hometepe: class extends self.ISpriteInstance {},
	homegit: class extends self.ISpriteInstance {},
	skipads: class extends self.ISpriteInstance {},
	cointext: class extends self.ISpriteFontInstance {},
	tikla: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	cointextt: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	engel: class extends self.ISpriteInstance {},
	devzombi: class extends self.ISpriteInstance {},
	zombizipla: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	starts2: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {}
}