const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Tween,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Spritefont2,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Spritefont2.Cnds.HasTags,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Acts.SetLayoutEffectParam,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Exps.right,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Sprite.Exps.TagAt,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Behaviors.Platform.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgba255,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Spritefont2.Acts.ChangeTags,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Tilemap: 0},
	{Foreground: 0},
	{Background: 0},
	{crouching: 0},
	{creating: 0},
	{Platform: 0},
	{Tween: 0},
	{BoundToLayout: 0},
	{Player: 0},
	{PlayerSprite: 0},
	{Keyboard: 0},
	{PlayerBlock: 0},
	{PlayerBlockTest: 0},
	{PlayerGadget: 0},
	{PlayerGadgetHit: 0},
	{Text: 0},
	{Rain: 0},
	{Switch: 0},
	{direction: 0},
	{prevDirection: 0},
	{speed: 0},
	{falling: 0},
	{vertical: 0},
	{Enemy: 0},
	{EnemyDriller: 0},
	{Aircon: 0},
	{Pipe: 0},
	{Sine: 0},
	{Signs: 0},
	{Door: 0},
	{EnemyRotor: 0},
	{GameManager: 0},
	{Spotlight: 0},
	{WinZone: 0},
	{PlayerParticles: 0},
	{Security: 0},
	{WeeGooSDK: 0}
];

self.InstanceType = {
	Tilemap: class extends self.ITilemapInstance {},
	Foreground: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	PlayerSprite: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	PlayerBlock: class extends self.ISpriteInstance {},
	PlayerBlockTest: class extends self.ISpriteInstance {},
	PlayerGadget: class extends self.ISpriteInstance {},
	PlayerGadgetHit: class extends self.ISpriteInstance {},
	Text: class extends self.ISpriteFontInstance {},
	Rain: class extends self.ITiledBackgroundInstance {},
	Switch: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	EnemyDriller: class extends self.ISpriteInstance {},
	Aircon: class extends self.ISpriteInstance {},
	Pipe: class extends self.ISpriteInstance {},
	Signs: class extends self.ISpriteInstance {},
	Door: class extends self.ISpriteInstance {},
	EnemyRotor: class extends self.ISpriteInstance {},
	GameManager: class extends self.ISpriteInstance {},
	Spotlight: class extends self.ISpriteInstance {},
	WinZone: class extends self.ITiledBackgroundInstance {},
	PlayerParticles: class extends self.IParticlesInstance {},
	Security: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {}
}