const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.Bullet,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Behaviors.Rotate,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Behaviors.Physics.Acts.SetPreventRotate,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Cnds.AngleWithin,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.RotateCounterclockwise,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Physics.Acts.SetElasticity,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.ResetPersisted,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward
	];
};
self.C3_JsPropNameTable = [
	{Physics: 0},
	{line: 0},
	{Bullet: 0},
	{Keeper: 0},
	{Dot: 0},
	{walls2: 0},
	{walls3: 0},
	{walls4: 0},
	{goal: 0},
	{goal1: 0},
	{EndResults: 0},
	{Audio: 0},
	{Browser: 0},
	{Touch: 0},
	{shoot: 0},
	{angledir: 0},
	{BekPlayer: 0},
	{ball: 0},
	{Sine: 0},
	{Striker: 0},
	{ball2: 0},
	{Play: 0},
	{balls: 0},
	{goals: 0},
	{SoccerGreenField: 0},
	{greenwalls: 0},
	{BGMENU: 0},
	{TextAICOM: 0},
	{SOCCERPINBALL: 0},
	{Rotate: 0},
	{Rays: 0},
	{blue_sort_: 0},
	{MOREGAMES: 0},
	{bot: 0},
	{highScoreBoxAsset: 0},
	{WeeGooSDK: 0},
	{TargetGoalPlayer: 0},
	{StockBall: 0},
	{Goal: 0},
	{naptechgames: 0}
];

self.InstanceType = {
	line: class extends self.ISpriteInstance {},
	Keeper: class extends self.ISpriteInstance {},
	Dot: class extends self.ISpriteInstance {},
	walls2: class extends self.ISpriteInstance {},
	walls3: class extends self.ISpriteInstance {},
	walls4: class extends self.ISpriteInstance {},
	goal: class extends self.ISpriteInstance {},
	EndResults: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	BekPlayer: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	Striker: class extends self.ISpriteInstance {},
	ball2: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	balls: class extends self.ITextInstance {},
	goals: class extends self.ITextInstance {},
	SoccerGreenField: class extends self.ISpriteInstance {},
	greenwalls: class extends self.ITiledBackgroundInstance {},
	BGMENU: class extends self.ISpriteInstance {},
	TextAICOM: class extends self.ISpriteInstance {},
	SOCCERPINBALL: class extends self.ISpriteInstance {},
	Rays: class extends self.ISpriteInstance {},
	blue_sort_: class extends self.ISpriteInstance {},
	MOREGAMES: class extends self.ISpriteInstance {},
	bot: class extends self.ISpriteInstance {},
	highScoreBoxAsset: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {}
}