const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Mouse,
		C3.Behaviors.Pin,
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Plugins.Keyboard,
		C3.Plugins.Spritefont2,
		C3.Plugins.NinePatch,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Behaviors.Sin,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.LocalStorage,
		C3.Plugins.WGSDK,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.AdvancedRandom.Acts.CreatePermutationTable,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.AdvancedRandom.Exps.Permutation,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.NinePatch.Cnds.OnCreated,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.NinePatch.Acts.SetPosToObject,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.TiledBg.Acts.SetZ,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.LayerEmpty,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.WGSDK.Cnds.RewardGranted,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{CardIndex: 0},
	{Active: 0},
	{Ready: 0},
	{beh_tween: 0},
	{Card: 0},
	{Mouse: 0},
	{beh_pin: 0},
	{CardShadow: 0},
	{SelectedCards: 0},
	{Browser: 0},
	{AdvancedRandom: 0},
	{GlowParticles: 0},
	{beh_fade: 0},
	{Flash: 0},
	{Table: 0},
	{CardsRandomizer: 0},
	{Keyboard: 0},
	{FontID: 0},
	{Fade: 0},
	{Text: 0},
	{SelectedArea: 0},
	{Touch: 0},
	{PlatformInfo: 0},
	{Sine: 0},
	{play: 0},
	{Anchor: 0},
	{homebutton: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Audio: 0},
	{BSound: 0},
	{nextlevelbutton: 0},
	{Sprite8: 0},
	{WELLDONE: 0},
	{ponovo: 0},
	{ponovo1: 0},
	{FIREWORK: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Background: 0},
	{moregames: 0},
	{help: 0},
	{poeni: 0},
	{LocalStorage: 0},
	{drvo: 0},
	{Sprite2: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{homebutton2: 0},
	{homebutton3: 0},
	{EASY: 0},
	{Sprite20: 0},
	{MEDIUM: 0},
	{HARD: 0},
	{EXPERT: 0},
	{EASY2: 0},
	{Card2: 0},
	{btn_games: 0},
	{nagrade: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite19: 0},
	{FIREWORK2: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{WeeGooSDK: 0},
	{buttons: 0},
	{sound: 0},
	{SoundEf: 0},
	{CARDSMAXHEIGHT: 0},
	{ActiveCards: 0},
	{ReadyCards: 0},
	{score: 0},
	{OffsetSpeed: 0},
	{Step: 0},
	{CURSORBORDER: 0},
	{CurrentCursorSpeed: 0},
	{CursorAngle: 0},
	{ShowCards: 0}
];

self.InstanceType = {
	Card: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	CardShadow: class extends self.ISpriteInstance {},
	SelectedCards: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	AdvancedRandom: class extends self.IInstance {},
	GlowParticles: class extends self.IParticlesInstance {},
	Flash: class extends self.ITiledBackgroundInstance {},
	Table: class extends self.ITiledBackgroundInstance {},
	CardsRandomizer: class extends self.IArrayInstance {},
	Keyboard: class extends self.IInstance {},
	Text: class extends self.ISpriteFontInstance {},
	SelectedArea: class extends self.I9PatchInstance {},
	Touch: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	play: class extends self.ISpriteInstance {},
	homebutton: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	BSound: class extends self.ISpriteInstance {},
	nextlevelbutton: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	WELLDONE: class extends self.ISpriteInstance {},
	ponovo: class extends self.ISpriteInstance {},
	ponovo1: class extends self.ISpriteInstance {},
	FIREWORK: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	moregames: class extends self.ISpriteInstance {},
	help: class extends self.ISpriteInstance {},
	poeni: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	drvo: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	homebutton2: class extends self.ISpriteInstance {},
	homebutton3: class extends self.ISpriteInstance {},
	EASY: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	MEDIUM: class extends self.ISpriteInstance {},
	HARD: class extends self.ISpriteInstance {},
	EXPERT: class extends self.ISpriteInstance {},
	EASY2: class extends self.ISpriteInstance {},
	Card2: class extends self.ISpriteInstance {},
	btn_games: class extends self.ISpriteInstance {},
	nagrade: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	FIREWORK2: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends C3.Plugins.WGSDK.Instance {},
	buttons: class extends self.ISpriteInstance {}
}