const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Particles,
		C3.Behaviors.Bullet,
		C3.Behaviors.Pin,
		C3.Behaviors.Turret,
		C3.Plugins.Text,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Touch,
		C3.Behaviors.Tween,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Behaviors.Timer,
		C3.Plugins.LocalStorage,
		C3.JavaScriptInEvents.Sobitya_Event1,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Eponesh_GameScore.Cnds.IsPaymentsAvailable,
		C3.Plugins.Eponesh_GameScore.Cnds.PaymentsPickProduct,
		C3.Plugins.Eponesh_GameScore.Cnds.IsPaymentsCurProductPurchased,
		C3.Plugins.Eponesh_GameScore.Acts.PaymentsConsume,
		C3.Plugins.Eponesh_GameScore.Exps.PaymentsCurProductTag,
		C3.Plugins.Eponesh_GameScore.Exps.PaymentsCurProductPrice,
		C3.Plugins.Eponesh_GameScore.Exps.PaymentsCurProductCurrencySymbol,
		C3.Plugins.Eponesh_GameScore.Exps.PaymentsCurProductName,
		C3.Plugins.Eponesh_GameScore.Exps.PaymentsCurProductDescription,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPaymentsPurchase,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPaymentsConsume,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Eponesh_GameScore.Acts.PaymentsPurchase,
		C3.Plugins.Browser.Cnds.OnWindowBlur,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Browser.Cnds.OnWindowFocus,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsFullscreenClose,
		C3.Behaviors.Turret.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowSticky,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Eponesh_GameScore.Cnds.PlatformType,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStart,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Exps.int,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStop,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardSetRecord,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardPublishRecord,
		C3.Plugins.Eponesh_GameScore.Acts.AchievementsSetProgress,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsShare,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Turret.Acts.SetRateOfFire,
		C3.Plugins.Eponesh_GameScore.Acts.AchievementsUnlock,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Text.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Touch.Cnds.OnDoubleTapGesture,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedClose,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsRewardedPlaying,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Turret.Acts.SetRange,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardFetchScoped,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardOpenScoped,
		C3.Plugins.Eponesh_GameScore.Acts.AchievementsFetch,
		C3.Plugins.Eponesh_GameScore.Acts.AchievementsOpen,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsPreloaderStart,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsPreloaderPlaying,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsPreloaderClose
	];
};
self.C3_JsPropNameTable = [
	{Buildings: 0},
	{Buildings2: 0},
	{Buildings3: 0},
	{TilesFon: 0},
	{Tiles: 0},
	{bochka: 0},
	{koster: 0},
	{kust: 0},
	{kust2: 0},
	{kust3: 0},
	{kust4: 0},
	{kust5: 0},
	{tree: 0},
	{Твёрдый: 0},
	{wall: 0},
	{FireParticles: 0},
	{SmokeParticles: 0},
	{fire: 0},
	{smoke: 0},
	{Towers: 0},
	{isIdle: 0},
	{isGoingToTower: 0},
	{isDefending: 0},
	{isGoingBack: 0},
	{towerTargetID: 0},
	{campTargetID: 0},
	{hasWeapon: 0},
	{isOnTower: 0},
	{Character: 0},
	{hp: 0},
	{id: 0},
	{CanDamageWall: 0},
	{Пуля: 0},
	{Zombie: 0},
	{koleso: 0},
	{Musorka: 0},
	{Прикрепить: 0},
	{Турель: 0},
	{NeStrelyaet: 0},
	{bullet: 0},
	{Welcome: 0},
	{Select: 0},
	{Restart: 0},
	{ads: 0},
	{Failure: 0},
	{Rewive: 0},
	{Start: 0},
	{GamePush: 0},
	{Tuch: 0},
	{Welcome2: 0},
	{TextSoftMoney: 0},
	{BuyBot: 0},
	{Upgrade2: 0},
	{Upgrade3: 0},
	{Upgrade4: 0},
	{Upgrade5: 0},
	{Wave: 0},
	{leaderidle: 0},
	{Nextwave: 0},
	{TextNextWave: 0},
	{RewardSpeed: 0},
	{RewardMoneyX2: 0},
	{Info: 0},
	{SoftMoney: 0},
	{HardMoney: 0},
	{TextHardMoney: 0},
	{HpBase: 0},
	{TextHpBase: 0},
	{TextHpZombie: 0},
	{isTaken: 0},
	{Shooter: 0},
	{TowerPoint: 0},
	{Shooter2: 0},
	{Shooter3: 0},
	{Shooter4: 0},
	{Shooter5: 0},
	{Shooter6: 0},
	{Shooter7: 0},
	{Shooter8: 0},
	{Shooter9: 0},
	{Shooter10: 0},
	{Shooter11: 0},
	{Shooter12: 0},
	{TowerPoint2: 0},
	{TowerPoint3: 0},
	{TowerPoint4: 0},
	{TowerPoint5: 0},
	{TowerPoint6: 0},
	{TowerPoint7: 0},
	{TowerPoint8: 0},
	{TowerPoint9: 0},
	{TowerPoint10: 0},
	{TowerPoint11: 0},
	{TowerPoint12: 0},
	{TextBuyBot: 0},
	{TextUpgrade: 0},
	{TextTask: 0},
	{TextX2_speed: 0},
	{TextX2_income: 0},
	{Textleaderidle: 0},
	{Textleaderidle2: 0},
	{Textleaderidle3: 0},
	{TextUpgrade2: 0},
	{TextUpgrade3: 0},
	{TextUpgrade4: 0},
	{Upgrade6: 0},
	{TextUpgrade5: 0},
	{InitialFunding: 0},
	{ReinforcedWalls: 0},
	{Resourcefulness: 0},
	{ExpertTinkerer: 0},
	{EnhancedTowers: 0},
	{TextInitialFunding: 0},
	{TextReinforcedWalls: 0},
	{TextResourcefulness: 0},
	{TextExpertTinkerer: 0},
	{TextEnhancedTowers: 0},
	{Твинанимация: 0},
	{SoftMoney2: 0},
	{Audio: 0},
	{Blood: 0},
	{CennikBuyBot: 0},
	{CennikUpgrade: 0},
	{CennikUpgrade2: 0},
	{CennikUpgrade3: 0},
	{CennikUpgrade4: 0},
	{CennikUpgrade5: 0},
	{WaveSpeed: 0},
	{WaveMoney: 0},
	{x2speed: 0},
	{ads2: 0},
	{CennikInitialFunding: 0},
	{CennikReinforcedWalls: 0},
	{CennikResourcefulnessLevel: 0},
	{Browser: 0},
	{CountEnhancedTowers: 0},
	{CountExpertTinkerer: 0},
	{EnhancedTowers50: 0},
	{ExpertTinkerer340: 0},
	{HardMoney2: 0},
	{leaderidle2: 0},
	{leaderidle3: 0},
	{Pause: 0},
	{Play: 0},
	{PauseIcon: 0},
	{sound: 0},
	{friends: 0},
	{Explosions: 0},
	{GlowParticles: 0},
	{FireCD: 0},
	{Таймер: 0},
	{Zombie2: 0},
	{ownerUID: 0},
	{NeStrelyaet2: 0},
	{bullet2: 0},
	{TextHpZombie2: 0},
	{RewardArtillery: 0},
	{Text_Artilery: 0},
	{Text_HardMoney: 0},
	{RewardHardMoney: 0},
	{Explosion: 0},
	{WaveArtilery: 0},
	{OblojkaOffera: 0},
	{Currency: 0},
	{Currency2: 0},
	{Currency3: 0},
	{Currency4: 0},
	{Currency5: 0},
	{Offer: 0},
	{Offer2: 0},
	{Offer3: 0},
	{Offer4: 0},
	{Offer5: 0},
	{Exit: 0},
	{CurrencyNazv: 0},
	{CurrencyOpis: 0},
	{CurrencyNazv2: 0},
	{CurrencyNazv3: 0},
	{CurrencyNazv4: 0},
	{CurrencyNazv5: 0},
	{CurrencyOpis2: 0},
	{CurrencyOpis3: 0},
	{CurrencyOpis4: 0},
	{CurrencyOpis5: 0},
	{producticon: 0},
	{producticon2: 0},
	{producticon3: 0},
	{producticon4: 0},
	{producticon5: 0},
	{"30procentov": 0},
	{freeiconfire: 0},
	{OffersMarket: 0},
	{TextOffers: 0},
	{FuGa: 0},
	{Tg: 0},
	{Nazv: 0},
	{Opisanje: 0},
	{Knopka: 0},
	{KrutayaPokupka: 0},
	{CennikKrutoi: 0},
	{Dostijenya: 0},
	{DostijenyaText: 0},
	{TextOffersTop: 0},
	{BuySpecialOffer: 0},
	{TextCennikOffersTop: 0},
	{LocalStorage: 0},
	{CampPoints: 0},
	{TowerPoints: 0},
	{gold: 0},
	{hardgold: 0},
	{turretDamage: 0},
	{turretFireRate: 0},
	{zombieHP: 0},
	{baseHP: 0},
	{zombiesPerWave: 0},
	{waveNumber: 0},
	{isShooting: 0},
	{EnemiesAlive: 0},
	{IsSpawning: 0},
	{botIndex: 0},
	{towerindex: 0},
	{InitialFundingLevel: 0},
	{WallsDamageReduction: 0},
	{GoldBoost: 0},
	{waveStarted: 0},
	{waveEnded: 0},
	{SpeedBoostsLeft: 0},
	{MoneyBoostsLeft: 0},
	{IsSpeedBoostOn: 0},
	{SpeedBoostAvailable: 0},
	{IsMoneyBoostOn: 0},
	{ReviveRequested: 0},
	{MaxWallHP: 0},
	{WallLevel: 0},
	{UpgradeWallCost: 0},
	{TowerUpgradeLevel: 0},
	{TurretSpeedUpgradeLevel: 0},
	{TurretDamageUpgradeLevel: 0},
	{ReinforcedWallsLevel: 0},
	{ResourcefulnessLevel: 0},
	{KillZombiesDaily: 0},
	{WavesCompletedDaily: 0},
	{Mission1Claimed: 0},
	{Mission2Claimed: 0},
	{LastResetDay: 0},
	{DailyTask1Progress: 0},
	{DailyTask1Target: 0},
	{DailyTask1Reward: 0},
	{DailyTask2Progress: 0},
	{DailyTask2Target: 0},
	{DailyTask2Reward: 0},
	{TotalZombieKills: 0},
	{IsGameOver: 0},
	{isSoundOffByPlayer: 0},
	{IsGamePaused: 0},
	{isOfferShown: 0},
	{BuyAdsInter: 0},
	{AbolutlyOffer: 0},
	{soundstate: 0},
	{ArteleryBoostsLeft: 0},
	{IsDefeatScreenShown: 0},
	{krutoy: 0}
];

self.InstanceType = {
	Buildings: class extends self.ISpriteInstance {},
	Buildings2: class extends self.ISpriteInstance {},
	Buildings3: class extends self.ISpriteInstance {},
	TilesFon: class extends self.ITiledBackgroundInstance {},
	Tiles: class extends self.ITilemapInstance {},
	bochka: class extends self.ISpriteInstance {},
	koster: class extends self.ISpriteInstance {},
	kust: class extends self.ISpriteInstance {},
	kust2: class extends self.ISpriteInstance {},
	kust3: class extends self.ISpriteInstance {},
	kust4: class extends self.ISpriteInstance {},
	kust5: class extends self.ISpriteInstance {},
	tree: class extends self.ISpriteInstance {},
	wall: class extends self.ISpriteInstance {},
	FireParticles: class extends self.IParticlesInstance {},
	SmokeParticles: class extends self.IParticlesInstance {},
	fire: class extends self.ISpriteInstance {},
	smoke: class extends self.ISpriteInstance {},
	Towers: class extends self.ISpriteInstance {},
	Character: class extends self.ISpriteInstance {},
	Zombie: class extends self.ISpriteInstance {},
	koleso: class extends self.ISpriteInstance {},
	Musorka: class extends self.ISpriteInstance {},
	NeStrelyaet: class extends self.ISpriteInstance {},
	bullet: class extends self.ISpriteInstance {},
	Welcome: class extends self.ISpriteInstance {},
	Select: class extends self.ISpriteInstance {},
	Restart: class extends self.ISpriteInstance {},
	ads: class extends self.ISpriteInstance {},
	Failure: class extends self.ITextInstance {},
	Rewive: class extends self.ITextInstance {},
	Start: class extends self.ITextInstance {},
	GamePush: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	Tuch: class extends self.IInstance {},
	Welcome2: class extends self.ISpriteInstance {},
	TextSoftMoney: class extends self.ITextInstance {},
	BuyBot: class extends self.ISpriteInstance {},
	Upgrade2: class extends self.ISpriteInstance {},
	Upgrade3: class extends self.ISpriteInstance {},
	Upgrade4: class extends self.ISpriteInstance {},
	Upgrade5: class extends self.ISpriteInstance {},
	Wave: class extends self.ITextInstance {},
	leaderidle: class extends self.ISpriteInstance {},
	Nextwave: class extends self.ISpriteInstance {},
	TextNextWave: class extends self.ITextInstance {},
	RewardSpeed: class extends self.ISpriteInstance {},
	RewardMoneyX2: class extends self.ISpriteInstance {},
	Info: class extends self.ISpriteInstance {},
	SoftMoney: class extends self.ISpriteInstance {},
	HardMoney: class extends self.ISpriteInstance {},
	TextHardMoney: class extends self.ITextInstance {},
	HpBase: class extends self.ISpriteInstance {},
	TextHpBase: class extends self.ITextInstance {},
	TextHpZombie: class extends self.ITextInstance {},
	Shooter: class extends self.ISpriteInstance {},
	TowerPoint: class extends self.ISpriteInstance {},
	Shooter2: class extends self.ISpriteInstance {},
	Shooter3: class extends self.ISpriteInstance {},
	Shooter4: class extends self.ISpriteInstance {},
	Shooter5: class extends self.ISpriteInstance {},
	Shooter6: class extends self.ISpriteInstance {},
	Shooter7: class extends self.ISpriteInstance {},
	Shooter8: class extends self.ISpriteInstance {},
	Shooter9: class extends self.ISpriteInstance {},
	Shooter10: class extends self.ISpriteInstance {},
	Shooter11: class extends self.ISpriteInstance {},
	Shooter12: class extends self.ISpriteInstance {},
	TowerPoint2: class extends self.ISpriteInstance {},
	TowerPoint3: class extends self.ISpriteInstance {},
	TowerPoint4: class extends self.ISpriteInstance {},
	TowerPoint5: class extends self.ISpriteInstance {},
	TowerPoint6: class extends self.ISpriteInstance {},
	TowerPoint7: class extends self.ISpriteInstance {},
	TowerPoint8: class extends self.ISpriteInstance {},
	TowerPoint9: class extends self.ISpriteInstance {},
	TowerPoint10: class extends self.ISpriteInstance {},
	TowerPoint11: class extends self.ISpriteInstance {},
	TowerPoint12: class extends self.ISpriteInstance {},
	TextBuyBot: class extends self.ITextInstance {},
	TextUpgrade: class extends self.ITextInstance {},
	TextTask: class extends self.ITextInstance {},
	TextX2_speed: class extends self.ITextInstance {},
	TextX2_income: class extends self.ITextInstance {},
	Textleaderidle: class extends self.ITextInstance {},
	Textleaderidle2: class extends self.ITextInstance {},
	Textleaderidle3: class extends self.ITextInstance {},
	TextUpgrade2: class extends self.ITextInstance {},
	TextUpgrade3: class extends self.ITextInstance {},
	TextUpgrade4: class extends self.ITextInstance {},
	Upgrade6: class extends self.ISpriteInstance {},
	TextUpgrade5: class extends self.ITextInstance {},
	InitialFunding: class extends self.ISpriteInstance {},
	ReinforcedWalls: class extends self.ISpriteInstance {},
	Resourcefulness: class extends self.ISpriteInstance {},
	ExpertTinkerer: class extends self.ISpriteInstance {},
	EnhancedTowers: class extends self.ISpriteInstance {},
	TextInitialFunding: class extends self.ITextInstance {},
	TextReinforcedWalls: class extends self.ITextInstance {},
	TextResourcefulness: class extends self.ITextInstance {},
	TextExpertTinkerer: class extends self.ITextInstance {},
	TextEnhancedTowers: class extends self.ITextInstance {},
	SoftMoney2: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Blood: class extends self.IParticlesInstance {},
	CennikBuyBot: class extends self.ITextInstance {},
	CennikUpgrade: class extends self.ITextInstance {},
	CennikUpgrade2: class extends self.ITextInstance {},
	CennikUpgrade3: class extends self.ITextInstance {},
	CennikUpgrade4: class extends self.ITextInstance {},
	CennikUpgrade5: class extends self.ITextInstance {},
	WaveSpeed: class extends self.ITextInstance {},
	WaveMoney: class extends self.ITextInstance {},
	x2speed: class extends self.ISpriteInstance {},
	ads2: class extends self.ISpriteInstance {},
	CennikInitialFunding: class extends self.ITextInstance {},
	CennikReinforcedWalls: class extends self.ITextInstance {},
	CennikResourcefulnessLevel: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	CountEnhancedTowers: class extends self.ITextInstance {},
	CountExpertTinkerer: class extends self.ITextInstance {},
	EnhancedTowers50: class extends self.ITextInstance {},
	ExpertTinkerer340: class extends self.ITextInstance {},
	HardMoney2: class extends self.ISpriteInstance {},
	leaderidle2: class extends self.ISpriteInstance {},
	leaderidle3: class extends self.ISpriteInstance {},
	Pause: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	PauseIcon: class extends self.ISpriteInstance {},
	sound: class extends self.ISpriteInstance {},
	friends: class extends self.ISpriteInstance {},
	Explosions: class extends self.ISpriteInstance {},
	GlowParticles: class extends self.IParticlesInstance {},
	Zombie2: class extends self.ISpriteInstance {},
	NeStrelyaet2: class extends self.ISpriteInstance {},
	bullet2: class extends self.ISpriteInstance {},
	TextHpZombie2: class extends self.ITextInstance {},
	RewardArtillery: class extends self.ISpriteInstance {},
	Text_Artilery: class extends self.ITextInstance {},
	Text_HardMoney: class extends self.ITextInstance {},
	RewardHardMoney: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	WaveArtilery: class extends self.ITextInstance {},
	OblojkaOffera: class extends self.ISpriteInstance {},
	Currency: class extends self.ITextInstance {},
	Currency2: class extends self.ITextInstance {},
	Currency3: class extends self.ITextInstance {},
	Currency4: class extends self.ITextInstance {},
	Currency5: class extends self.ITextInstance {},
	Offer: class extends self.ISpriteInstance {},
	Offer2: class extends self.ISpriteInstance {},
	Offer3: class extends self.ISpriteInstance {},
	Offer4: class extends self.ISpriteInstance {},
	Offer5: class extends self.ISpriteInstance {},
	Exit: class extends self.ISpriteInstance {},
	CurrencyNazv: class extends self.ITextInstance {},
	CurrencyOpis: class extends self.ITextInstance {},
	CurrencyNazv2: class extends self.ITextInstance {},
	CurrencyNazv3: class extends self.ITextInstance {},
	CurrencyNazv4: class extends self.ITextInstance {},
	CurrencyNazv5: class extends self.ITextInstance {},
	CurrencyOpis2: class extends self.ITextInstance {},
	CurrencyOpis3: class extends self.ITextInstance {},
	CurrencyOpis4: class extends self.ITextInstance {},
	CurrencyOpis5: class extends self.ITextInstance {},
	producticon: class extends self.ISpriteInstance {},
	producticon2: class extends self.ISpriteInstance {},
	producticon3: class extends self.ISpriteInstance {},
	producticon4: class extends self.ISpriteInstance {},
	producticon5: class extends self.ISpriteInstance {},
	_30procentov: class extends self.ISpriteInstance {},
	freeiconfire: class extends self.ISpriteInstance {},
	OffersMarket: class extends self.ISpriteInstance {},
	TextOffers: class extends self.ITextInstance {},
	FuGa: class extends self.ISpriteInstance {},
	Tg: class extends self.ISpriteInstance {},
	Nazv: class extends self.ITextInstance {},
	Opisanje: class extends self.ITextInstance {},
	Knopka: class extends self.ITextInstance {},
	KrutayaPokupka: class extends self.ISpriteInstance {},
	CennikKrutoi: class extends self.ITextInstance {},
	Dostijenya: class extends self.ISpriteInstance {},
	DostijenyaText: class extends self.ITextInstance {},
	TextOffersTop: class extends self.ITextInstance {},
	BuySpecialOffer: class extends self.ISpriteInstance {},
	TextCennikOffersTop: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	CampPoints: class extends self.ISpriteInstance {},
	TowerPoints: class extends self.ISpriteInstance {}
}