const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.AJAX,
		C3.Plugins.Dictionary,
		C3.Plugins.LocalStorage,
		C3.Plugins.Sprite,
		C3.Plugins.NinePatch,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Behaviors.Fade,
		C3.Behaviors.scrollto,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsStickyAvailable,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowSticky,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Eponesh_GameScore.Cnds.PlatformType,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.Alert,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Cnds.CompareXYZ,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Eponesh_GameScore.Acts.ChangeLanguageByCode,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetEffect,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Eponesh_GameScore.Cnds.PaymentsPickProduct,
		C3.Plugins.Eponesh_GameScore.Exps.PaymentsCurProductPrice,
		C3.Plugins.Eponesh_GameScore.Exps.PaymentsCurProductCurrencySymbol,
		C3.Plugins.Eponesh_GameScore.Acts.PaymentsPurchase,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPaymentsPurchase,
		C3.Plugins.Eponesh_GameScore.Acts.PaymentsConsume,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPaymentsConsume,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerAdd,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Eponesh_GameScore.Cnds.IsPaymentsAvailable,
		C3.Plugins.Eponesh_GameScore.Cnds.IsPaymentsCurProductPurchased,
		C3.Plugins.Eponesh_GameScore.Exps.PaymentsCurProductTag,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Eponesh_GameScore.Acts.AdsCloseSticky,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPause,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Eponesh_GameScore.Acts.MuteMusic,
		C3.Plugins.Eponesh_GameScore.Cnds.OnResume,
		C3.Plugins.Eponesh_GameScore.Acts.UnmuteMusic,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsPreloaderPlaying,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsPreloaderClose,
		C3.Plugins.Eponesh_GameScore.Cnds.PlayerCompare,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsJoinCommunity,
		C3.Plugins.Eponesh_GameScore.Cnds.IsGamesCollectionsAvailable,
		C3.Plugins.Eponesh_GameScore.Acts.GamesCollectionsOpen,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardOpen,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSetScore,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsPreloaderAvailable,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowPreloader,
		C3.Plugins.Eponesh_GameScore.Exps.Language,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.Eponesh_GameScore.Acts.ChangeLanguage,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Browser.Acts.LoadStyleSheet,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Text.Acts.SetFontFace,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Spritefont2.Exps.LayerNumber,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Spritefont2.Acts.SetSize,
		C3.Plugins.Spritefont2.Exps.Width,
		C3.Plugins.Spritefont2.Exps.Height,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.Spritefont2.Exps.ColorValue,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Spritefont2.Exps.CharacterScale,
		C3.Plugins.Spritefont2.Exps.UID,
		C3.JavaScriptInEvents.Translations_Event14_Act11,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Dictionary.Acts.Clear,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Arr.Exps.Depth,
		C3.Plugins.Arr.Exps.Height
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{GameData: 0},
	{SwapData: 0},
	{Touch: 0},
	{ArrayTemp2: 0},
	{array_level: 0},
	{Browser: 0},
	{AJAX: 0},
	{array_save: 0},
	{stringsArray: 0},
	{stringsDictionary: 0},
	{StorageData: 0},
	{LocalStorage: 0},
	{QuitBTN: 0},
	{MoreGamesBTN: 0},
	{RestartBTN: 0},
	{ContinueBTN: 0},
	{SoundBTNMenu: 0},
	{PlayBTN: 0},
	{TapBTN: 0},
	{StartBTN: 0},
	{NoBTN: 0},
	{YesBTN: 0},
	{YesBTN2: 0},
	{YesBTN3: 0},
	{NoBTN2: 0},
	{SoundBTN2: 0},
	{RstBTN2: 0},
	{RstBTN3: 0},
	{RstBTN4: 0},
	{id: 0},
	{Tween: 0},
	{Button: 0},
	{BombEffect: 0},
	{BonusText: 0},
	{type: 0},
	{CheckUI: 0},
	{DarkBackground: 0},
	{GameHeaderUI: 0},
	{row: 0},
	{col: 0},
	{Moving: 0},
	{TargetY: 0},
	{RedFoc: 0},
	{Swap: 0},
	{isMatch: 0},
	{Trigger: 0},
	{Seno: 0},
	{GameItem: 0},
	{GameItemInitial: 0},
	{GameItemTween: 0},
	{GameItemUI: 0},
	{GameTiles: 0},
	{GrassOutline: 0},
	{LevelCompleteParticles: 0},
	{Girar: 0},
	{LevelCompleteSpin: 0},
	{LevelCompleteStar: 0},
	{LevelParticles: 0},
	{Sine: 0},
	{LevelPointer: 0},
	{LivesHeaderUI: 0},
	{Fade: 0},
	{LiveTaken: 0},
	{Rotate: 0},
	{LoadingAnimation: 0},
	{ScrollTo: 0},
	{MapCamera: 0},
	{MatchEffect1: 0},
	{MatchEffect2: 0},
	{MatchWoodParticles: 0},
	{NoMoreLivesUI: 0},
	{Power1: 0},
	{Power2: 0},
	{Power3: 0},
	{Power4: 0},
	{PowerEffectv1: 0},
	{PowerEffectv2: 0},
	{PowerEffectv3: 0},
	{PowerEffectv4: 0},
	{PowerParticles: 0},
	{Desvanecer: 0},
	{PowerUpsBackground: 0},
	{power: 0},
	{Pin: 0},
	{PowerUPSFont: 0},
	{PowerUpsHeaderUI: 0},
	{type2: 0},
	{TargetFont: 0},
	{WellDoneUI: 0},
	{WoodFrame: 0},
	{WoodMenu: 0},
	{FadeScreen: 0},
	{NoMoreLivesUI2: 0},
	{Power5: 0},
	{tovar: 0},
	{LoadingAnimation2: 0},
	{Power6: 0},
	{GameHeaderUI2: 0},
	{TargetFont2: 0},
	{bay: 0},
	{pokupka: 0},
	{textnocode: 0},
	{code: 0},
	{teds2: 0},
	{logo: 0},
	{Dk: 0},
	{Поворот: 0},
	{Sp2: 0},
	{Sp1: 0},
	{Sp3: 0},
	{GamePush: 0},
	{SpriteFont_EN: 0},
	{SpriteFont_RU: 0},
	{Text: 0},
	{tempText1: 0},
	{spriteokno: 0},
	{tempFlag: 0},
	{Твинанимация: 0},
	{btnex: 0},
	{level: 0},
	{moves: 0},
	{vksoc: 0},
	{livess: 0},
	{spriteokno2: 0},
	{powers: 0},
	{videopower: 0},
	{cena: 0},
	{heads: 0},
	{headershop: 0},
	{GameBackground: 0},
	{spriteokno3: 0},
	{setings: 0},
	{VkBTN: 0},
	{Buttons: 0},
	{LangSpritefonts: 0},
	{LangSprites: 0},
	{LangTexts: 0},
	{score: 0},
	{combos: 0},
	{game_mode: 0},
	{max_color: 0},
	{state: 0},
	{width: 0},
	{height: 0},
	{PosX: 0},
	{PosY: 0},
	{tile_size: 0},
	{fall_speed: 0},
	{is_falling: 0},
	{draging: 0},
	{top_cell: 0},
	{match_count: 0},
	{cur_level: 0},
	{cur_moves: 0},
	{ScreenWidthValue: 0},
	{ScreenHeightValue: 0},
	{value1: 0},
	{value2: 0},
	{redfoc: 0},
	{frame: 0},
	{uid: 0},
	{shift: 0},
	{shift2: 0},
	{cur: 0},
	{Touching: 0},
	{NotMatch: 0},
	{value: 0},
	{plus: 0},
	{substract: 0},
	{ScoreTemp: 0},
	{ScoreTemp2: 0},
	{origin_x: 0},
	{origin_y: 0},
	{end_x: 0},
	{end_y: 0},
	{UsingPower: 0},
	{P2trigger: 0},
	{music: 0},
	{sound: 0},
	{Powers1: 0},
	{Powers2: 0},
	{Powers3: 0},
	{Powers4: 0},
	{Livess: 0},
	{gp_unlocked_level: 0},
	{total_level: 0},
	{unlocked_level: 0},
	{Lives: 0},
	{name: 0},
	{Target1: 0},
	{Target2: 0},
	{Target3: 0},
	{x: 0},
	{y: 0},
	{lang: 0},
	{tempString: 0},
	{sourceUID: 0},
	{destUID: 0},
	{languageIndex: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	GameData: class extends self.IArrayInstance {},
	SwapData: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	ArrayTemp2: class extends self.IArrayInstance {},
	array_level: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	array_save: class extends self.IArrayInstance {},
	stringsArray: class extends self.IArrayInstance {},
	stringsDictionary: class extends self.IDictionaryInstance {},
	StorageData: class extends self.IDictionaryInstance {},
	LocalStorage: class extends self.IInstance {},
	QuitBTN: class extends self.ISpriteInstance {},
	MoreGamesBTN: class extends self.ISpriteInstance {},
	RestartBTN: class extends self.ISpriteInstance {},
	ContinueBTN: class extends self.ISpriteInstance {},
	SoundBTNMenu: class extends self.ISpriteInstance {},
	PlayBTN: class extends self.ISpriteInstance {},
	TapBTN: class extends self.ISpriteInstance {},
	StartBTN: class extends self.ISpriteInstance {},
	NoBTN: class extends self.ISpriteInstance {},
	YesBTN: class extends self.ISpriteInstance {},
	YesBTN2: class extends self.ISpriteInstance {},
	YesBTN3: class extends self.ISpriteInstance {},
	NoBTN2: class extends self.ISpriteInstance {},
	SoundBTN2: class extends self.ISpriteInstance {},
	RstBTN2: class extends self.ISpriteInstance {},
	RstBTN3: class extends self.ISpriteInstance {},
	RstBTN4: class extends self.ISpriteInstance {},
	Button: class extends self.IWorldInstance {},
	BombEffect: class extends self.ISpriteInstance {},
	BonusText: class extends self.ISpriteInstance {},
	CheckUI: class extends self.ISpriteInstance {},
	DarkBackground: class extends self.ITiledBackgroundInstance {},
	GameHeaderUI: class extends self.ISpriteInstance {},
	GameItem: class extends self.ISpriteInstance {},
	GameItemInitial: class extends self.ISpriteInstance {},
	GameItemTween: class extends self.ISpriteInstance {},
	GameItemUI: class extends self.ISpriteInstance {},
	GameTiles: class extends self.ISpriteInstance {},
	GrassOutline: class extends self.ISpriteInstance {},
	LevelCompleteParticles: class extends self.IParticlesInstance {},
	LevelCompleteSpin: class extends self.ISpriteInstance {},
	LevelCompleteStar: class extends self.ISpriteInstance {},
	LevelParticles: class extends self.IParticlesInstance {},
	LevelPointer: class extends self.ISpriteInstance {},
	LivesHeaderUI: class extends self.ISpriteInstance {},
	LiveTaken: class extends self.ISpriteInstance {},
	LoadingAnimation: class extends self.ISpriteInstance {},
	MapCamera: class extends self.ISpriteInstance {},
	MatchEffect1: class extends self.ISpriteInstance {},
	MatchEffect2: class extends self.ISpriteInstance {},
	MatchWoodParticles: class extends self.IParticlesInstance {},
	NoMoreLivesUI: class extends self.ISpriteInstance {},
	Power1: class extends self.ISpriteInstance {},
	Power2: class extends self.ISpriteInstance {},
	Power3: class extends self.ISpriteInstance {},
	Power4: class extends self.ISpriteInstance {},
	PowerEffectv1: class extends self.ISpriteInstance {},
	PowerEffectv2: class extends self.ISpriteInstance {},
	PowerEffectv3: class extends self.ISpriteInstance {},
	PowerEffectv4: class extends self.ISpriteInstance {},
	PowerParticles: class extends self.IParticlesInstance {},
	PowerUpsBackground: class extends self.ITiledBackgroundInstance {},
	PowerUPSFont: class extends self.ISpriteFontInstance {},
	PowerUpsHeaderUI: class extends self.ISpriteInstance {},
	TargetFont: class extends self.ISpriteFontInstance {},
	WellDoneUI: class extends self.ISpriteInstance {},
	WoodFrame: class extends self.ISpriteInstance {},
	WoodMenu: class extends self.ISpriteInstance {},
	FadeScreen: class extends self.ISpriteInstance {},
	NoMoreLivesUI2: class extends self.ISpriteInstance {},
	Power5: class extends self.ISpriteInstance {},
	LoadingAnimation2: class extends self.ISpriteInstance {},
	Power6: class extends self.ISpriteInstance {},
	GameHeaderUI2: class extends self.ISpriteInstance {},
	TargetFont2: class extends self.ISpriteFontInstance {},
	pokupka: class extends self.ISpriteInstance {},
	textnocode: class extends self.ITextInstance {},
	teds2: class extends self.ITextInstance {},
	logo: class extends self.ISpriteInstance {},
	Dk: class extends self.ISpriteInstance {},
	Sp2: class extends self.ISpriteInstance {},
	Sp1: class extends self.ISpriteInstance {},
	Sp3: class extends self.ISpriteInstance {},
	GamePush: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	SpriteFont_EN: class extends self.ISpriteFontInstance {},
	SpriteFont_RU: class extends self.ISpriteFontInstance {},
	Text: class extends self.ITextInstance {},
	tempText1: class extends self.ITextInstance {},
	spriteokno: class extends self.ISpriteInstance {},
	tempFlag: class extends self.ISpriteInstance {},
	btnex: class extends self.ISpriteInstance {},
	level: class extends self.ITextInstance {},
	moves: class extends self.ITextInstance {},
	vksoc: class extends self.ITextInstance {},
	livess: class extends self.ITextInstance {},
	spriteokno2: class extends self.ISpriteInstance {},
	videopower: class extends self.ISpriteInstance {},
	cena: class extends self.ITextInstance {},
	headershop: class extends self.ITextInstance {},
	GameBackground: class extends self.ITiledBackgroundInstance {},
	spriteokno3: class extends self.ISpriteInstance {},
	setings: class extends self.ISpriteInstance {},
	VkBTN: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	LangSpritefonts: class extends self.ISpriteFontInstance {},
	LangSprites: class extends self.ISpriteInstance {},
	LangTexts: class extends self.ITextInstance {}
}