const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Text,
		C3.Plugins.NinePatch,
		C3.Plugins.Touch,
		C3.Behaviors.Tween,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Pin,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.NinePatch.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.WGSDK.Cnds.RewardGranted,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Audio.Acts.PlayByName
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{JSON: 0},
	{txtQNum: 0},
	{txtQType: 0},
	{txtQ: 0},
	{txtAnswer: 0},
	{index: 0},
	{Answer: 0},
	{Btn: 0},
	{Touch: 0},
	{txt1: 0},
	{Tween: 0},
	{txtpercent: 0},
	{Sine: 0},
	{BtnReset: 0},
	{sprunkiplay: 0},
	{gtaplay: 0},
	{likovi: 0},
	{frame: 0},
	{Pin: 0},
	{Sprite20: 0},
	{naocalenove: 0},
	{Sprite: 0},
	{hint: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{start: 0},
	{Sprite7: 0},
	{txtQ2: 0},
	{Sprite6: 0},
	{Fireflies: 0},
	{Sprite8: 0},
	{Fog: 0},
	{FireSparkParticles: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite21: 0},
	{home: 0},
	{home2: 0},
	{BSound: 0},
	{Sprite17: 0},
	{GTA: 0},
	{moregames: 0},
	{pokemonplay: 0},
	{Pokemonlikovi: 0},
	{minecraftnplay: 0},
	{Minecraftlikovi: 0},
	{SportSlike: 0},
	{Sport: 0},
	{CarLogos: 0},
	{CarLogosSlike: 0},
	{Audio: 0},
	{FireworkParticles2: 0},
	{Mouse: 0},
	{videoigrice: 0},
	{Browser: 0},
	{WeeGooSDK: 0},
	{Sprite18: 0},
	{QCount: 0},
	{QNum: 0},
	{QType: 0},
	{Q: 0},
	{Answers: 0},
	{CorrectAnswer: 0},
	{Clicked: 0},
	{TargetPercent: 0},
	{CorrectAnswered: 0},
	{vNum: 0},
	{sound: 0},
	{SoundEf: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	txtQNum: class extends self.ITextInstance {},
	txtQType: class extends self.ITextInstance {},
	txtQ: class extends self.ITextInstance {},
	txtAnswer: class extends self.ITextInstance {},
	Btn: class extends self.IWorldInstance {},
	Touch: class extends self.IInstance {},
	txt1: class extends self.ITextInstance {},
	txtpercent: class extends self.ITextInstance {},
	BtnReset: class extends self.ISpriteInstance {},
	sprunkiplay: class extends self.ISpriteInstance {},
	gtaplay: class extends self.ISpriteInstance {},
	likovi: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	naocalenove: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	hint: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	start: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	txtQ2: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Fireflies: class extends self.IParticlesInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Fog: class extends self.ITiledBackgroundInstance {},
	FireSparkParticles: class extends self.IParticlesInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	home2: class extends self.ISpriteInstance {},
	BSound: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	GTA: class extends self.ISpriteInstance {},
	moregames: class extends self.ISpriteInstance {},
	pokemonplay: class extends self.ISpriteInstance {},
	Pokemonlikovi: class extends self.ISpriteInstance {},
	minecraftnplay: class extends self.ISpriteInstance {},
	Minecraftlikovi: class extends self.ISpriteInstance {},
	SportSlike: class extends self.ISpriteInstance {},
	Sport: class extends self.ISpriteInstance {},
	CarLogos: class extends self.ISpriteInstance {},
	CarLogosSlike: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	FireworkParticles2: class extends self.IParticlesInstance {},
	Mouse: class extends self.IInstance {},
	videoigrice: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	WeeGooSDK: class extends self.IInstance {},
	Sprite18: class extends self.ISpriteInstance {}
}