const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.LOS,
		C3.Behaviors.custom,
		C3.Plugins.Keyboard,
		C3.Plugins.gamepad,
		C3.Plugins.Camera3D,
		C3.Plugins.Shape3D,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Plugins.WGSDK,
		C3.Behaviors.solid,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Plugins.Shape3D.Exps.ZHeight,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Shape3D.Acts.AddChild,
		C3.Plugins.Shape3D.Acts.SetFaceObject,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.LOS.Acts.CastRay,
		C3.Behaviors.LOS.Exps.Range,
		C3.Behaviors.LOS.Cnds.RayIntersected,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.LOS.Exps.HitDistance,
		C3.Behaviors.LOS.Exps.ReflectionAngle,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Shape3D.Acts.RemoveFromParent,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Shape3D.Acts.SetEffectParam,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Camera3D.Exps.LookX,
		C3.Plugins.Camera3D.Exps.LookY,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY
	];
};
self.C3_JsPropNameTable = [
	{AngleOfMotion: 0},
	{MovementSpeed: 0},
	{PreviousX: 0},
	{PreviousY: 0},
	{Enabled: 0},
	{LineOfSight: 0},
	{Custom: 0},
	{BallCollision: 0},
	{WallCollision: 0},
	{Paddle: 0},
	{Keyboard: 0},
	{Gamepad: 0},
	{ColorIndex: 0},
	{BlockCollision: 0},
	{"3DCamera": 0},
	{Ground: 0},
	{Tween: 0},
	{BlockShape: 0},
	{BallAnimation: 0},
	{Background: 0},
	{TopWall: 0},
	{LeftWall: 0},
	{RightWall: 0},
	{RightCorner: 0},
	{LeftCorner: 0},
	{BlockFrontFace: 0},
	{BlockLeftFace: 0},
	{BlockRightFace: 0},
	{BlockBottomFace: 0},
	{Fog: 0},
	{Text: 0},
	{BallTrail: 0},
	{WeeGooSDK: 0},
	{Solid: 0},
	{LoopSize: 0},
	{StepLength: 0},
	{ShortestDistance: 0},
	{ReflectionAngle: 0},
	{CurrentX: 0},
	{CurrentY: 0},
	{PaddleSpeed: 0},
	{Direction: 0}
];

self.InstanceType = {
	BallCollision: class extends self.ISpriteInstance {},
	WallCollision: class extends self.ISpriteInstance {},
	Paddle: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	BlockCollision: class extends self.ISpriteInstance {},
	_3DCamera: class extends self.IInstance {},
	Ground: class extends self.I3DShapeInstance {},
	BlockShape: class extends self.I3DShapeInstance {},
	BallAnimation: class extends self.ISpriteInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	TopWall: class extends self.I3DShapeInstance {},
	LeftWall: class extends self.I3DShapeInstance {},
	RightWall: class extends self.I3DShapeInstance {},
	RightCorner: class extends self.I3DShapeInstance {},
	LeftCorner: class extends self.I3DShapeInstance {},
	BlockFrontFace: class extends self.ISpriteInstance {},
	BlockLeftFace: class extends self.ISpriteInstance {},
	BlockRightFace: class extends self.ISpriteInstance {},
	BlockBottomFace: class extends self.ISpriteInstance {},
	Fog: class extends self.ISpriteInstance {},
	Text: class extends self.ISpriteFontInstance {},
	BallTrail: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	Solid: class extends self.ISpriteInstance {}
}