const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Json,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Timer,
		C3.Behaviors.Tween,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Date,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Arr,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Behaviors.Physics,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Plugins.TiledBg,
		C3.Plugins.DrawingCanvas,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Exps.viewportheight,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsStickyPlaying,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsStickyAvailable,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowSticky,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardOpen,
		C3.Plugins.Eponesh_GameScore.Acts.AchievementsOpen,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsInvite,
		C3.Plugins.Json.Cnds.CompareValue,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.AdvancedRandom.Acts.SetSeed,
		C3.Plugins.AdvancedRandom.Exps.RandomSeed,
		C3.Plugins.AdvancedRandom.Acts.CreatePermutationTable,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.AdvancedRandom.Exps.Permutation,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Eponesh_GameScore.Cnds.AchievementsIsUnlocked,
		C3.Plugins.Eponesh_GameScore.Acts.AchievementsUnlock,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardFetchPlayerRating,
		C3.Plugins.Eponesh_GameScore.Cnds.OnLeaderboardFetchPlayer,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardPlayerPosition,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Eponesh_GameScore.Acts.GamesCollectionsOpen,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.Eponesh_GameScore.Cnds.IsSFXMuted,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Eponesh_GameScore.Cnds.IsPaused,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Date.Exps.ToTimerHours,
		C3.Plugins.Date.Exps.ToTimerMinutes,
		C3.Plugins.Date.Exps.ToTimerSeconds,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Browser.Acts.LoadStyleSheet,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Eponesh_GameScore.Cnds.PlayerCompare,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.originalwindowwidth,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.originalwindowheight,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.SetIterations,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.AddLayer,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStart,
		C3.Plugins.DrawingCanvas.Acts.SetPosToObject,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Plugins.DrawingCanvas.Acts.MoveToBottom,
		C3.Plugins.DrawingCanvas.Acts.SetDefaultColor,
		C3.Plugins.DrawingCanvas.Acts.SetPos,
		C3.Plugins.DrawingCanvas.Exps.X,
		C3.Plugins.DrawingCanvas.Exps.Y,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStop,
		C3.Plugins.Json.Acts.AddTo,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Exps.layoutscale,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.System.Exps.roundtodp,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Eponesh_GameScore.Acts.UnmuteSFX,
		C3.Plugins.Eponesh_GameScore.Acts.MuteSFX,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Arr.Exps.At,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsRewardedAvailable,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Eponesh_GameScore.Cnds.IsSocialsSupportsNativeInvite,
		C3.Plugins.Eponesh_GameScore.Cnds.PlatformType,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Plugins.System.Exps.loadingprogress
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{Audio: 0},
	{Browser: 0},
	{JSON_save: 0},
	{Touch: 0},
	{status_game: 0},
	{Timer: 0},
	{Tween: 0},
	{sys: 0},
	{GamePush: 0},
	{fade: 0},
	{JSON_text: 0},
	{Date: 0},
	{AdvancedRandom: 0},
	{fade_out: 0},
	{Candy_frame: 0},
	{New_levels: 0},
	{Arr_choose: 0},
	{Type: 0},
	{btn_end: 0},
	{pos_x: 0},
	{pos_y: 0},
	{btn_ui: 0},
	{text_ui: 0},
	{type: 0},
	{pos_btn: 0},
	{Sine: 0},
	{Arm: 0},
	{Text_win: 0},
	{btn_ui2: 0},
	{Text_ads: 0},
	{Index: 0},
	{Parent: 0},
	{New_frame: 0},
	{Choose: 0},
	{Candy: 0},
	{Candys_Count: 0},
	{Done: 0},
	{Frame_Candy: 0},
	{type_vis: 0},
	{Timer_start: 0},
	{Colba: 0},
	{Box_back: 0},
	{Box_front: 0},
	{time: 0},
	{Frame_bg: 0},
	{Center_bg: 0},
	{Colba_back: 0},
	{Colba_top: 0},
	{Variant: 0},
	{Physics: 0},
	{Candy_tube: 0},
	{index: 0},
	{Candy_pos: 0},
	{state: 0},
	{win_ang: 0},
	{now_ang: 0},
	{For_win: 0},
	{tube: 0},
	{angel_s: 0},
	{tube_end: 0},
	{Tube_start: 0},
	{position: 0},
	{border: 0},
	{choose_tube: 0},
	{class: 0},
	{gui_buttons: 0},
	{Text_time: 0},
	{cell: 0},
	{Tube_decor: 0},
	{Dim: 0},
	{sub_status: 0},
	{posX: 0},
	{posY: 0},
	{Basa: 0},
	{Turns: 0},
	{Etiketka: 0},
	{Mechanik: 0},
	{Rotate: 0},
	{Rolls: 0},
	{Rope_tbg: 0},
	{Tube_decor_bg: 0},
	{Tube_tbg: 0},
	{Tube_tbg2: 0},
	{Tube_tbg3: 0},
	{a_tube_false: 0},
	{TEST: 0},
	{Sprite: 0},
	{BG: 0},
	{Particles_win: 0},
	{Sprite2: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{DrawingCanvas: 0},
	{Btn_socials: 0},
	{F_Candy: 0},
	{F_Colba: 0},
	{tubes: 0},
	{name_sound: 0},
	{name_tag: 0},
	{name_next: 0},
	{my_top: 0},
	{ads_type: 0},
	{ads_time: 0},
	{fullscreen_on_start: 0},
	{event: 0},
	{type_reward: 0},
	{Day_now: 0},
	{Day_last: 0},
	{Day_next: 0},
	{event_time: 0},
	{lang: 0},
	{CanvasPan: 0},
	{LastX: 0},
	{LastY: 0},
	{TouchAngle: 0},
	{TouchDistance: 0},
	{transition: 0},
	{zoom: 0},
	{scale: 0},
	{time_go: 0},
	{seconds: 0},
	{minutes: 0},
	{a: 0},
	{b: 0},
	{BG_tube: 0},
	{T_posX: 0},
	{T_posY: 0},
	{count_candy: 0},
	{numb: 0},
	{Save_now_in: 0},
	{LevelSave: 0},
	{SelectedGlass: 0},
	{SelectedBallFrame: 0},
	{Status_game: 0},
	{Is_activ_tap: 0},
	{top_Y: 0},
	{bottom_Y: 0},
	{time_move: 0},
	{Now_level: 0},
	{New_frame_candy: 0},
	{status_move: 0},
	{star_index: 0},
	{choose_n: 0},
	{old_colba: 0},
	{GlassTarget: 0},
	{Count_max: 0},
	{CorrectCount: 0},
	{save_position: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	JSON_save: class extends self.IJSONInstance {},
	Touch: class extends self.IInstance {},
	sys: class extends self.ISpriteInstance {},
	GamePush: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	fade: class extends self.ISpriteInstance {},
	JSON_text: class extends self.IJSONInstance {},
	Date: class extends self.IInstance {},
	AdvancedRandom: class extends self.IInstance {},
	fade_out: class extends self.ISpriteInstance {},
	Candy_frame: class extends self.IArrayInstance {},
	New_levels: class extends self.IArrayInstance {},
	Arr_choose: class extends self.IArrayInstance {},
	btn_end: class extends self.ISpriteInstance {},
	btn_ui: class extends self.ISpriteInstance {},
	text_ui: class extends self.ITextInstance {},
	pos_btn: class extends self.ISpriteInstance {},
	Arm: class extends self.ISpriteInstance {},
	Text_win: class extends self.ITextInstance {},
	btn_ui2: class extends self.ISpriteInstance {},
	Text_ads: class extends self.ITextInstance {},
	Candy: class extends self.ISpriteInstance {},
	Colba: class extends self.ISpriteInstance {},
	Box_back: class extends self.ISpriteInstance {},
	Box_front: class extends self.ISpriteInstance {},
	Center_bg: class extends self.ISpriteInstance {},
	Colba_back: class extends self.ISpriteInstance {},
	Colba_top: class extends self.ISpriteInstance {},
	Variant: class extends self.ISpriteInstance {},
	Candy_tube: class extends self.ISpriteInstance {},
	Candy_pos: class extends self.ISpriteInstance {},
	tube: class extends self.ISpriteInstance {},
	tube_end: class extends self.ISpriteInstance {},
	Tube_start: class extends self.ISpriteInstance {},
	border: class extends self.ISpriteInstance {},
	choose_tube: class extends self.ISpriteInstance {},
	gui_buttons: class extends self.ISpriteInstance {},
	Text_time: class extends self.ITextInstance {},
	Tube_decor: class extends self.ISpriteInstance {},
	Dim: class extends self.IParticlesInstance {},
	Basa: class extends self.ISpriteInstance {},
	Turns: class extends self.ISpriteInstance {},
	Etiketka: class extends self.ISpriteInstance {},
	Mechanik: class extends self.ISpriteInstance {},
	Rolls: class extends self.ISpriteInstance {},
	Rope_tbg: class extends self.ITiledBackgroundInstance {},
	Tube_decor_bg: class extends self.ISpriteInstance {},
	Tube_tbg: class extends self.ITiledBackgroundInstance {},
	Tube_tbg2: class extends self.ITiledBackgroundInstance {},
	Tube_tbg3: class extends self.ITiledBackgroundInstance {},
	a_tube_false: class extends self.IArrayInstance {},
	TEST: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	Particles_win: class extends self.IParticlesInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	Btn_socials: class extends self.ISpriteInstance {},
	F_Candy: class extends self.ISpriteInstance {},
	F_Colba: class extends self.ISpriteInstance {},
	tubes: class extends self.ISpriteInstance {}
}