const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.bound,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Behaviors.Rotate,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Behaviors.Platform,
		C3.Behaviors.Pin,
		C3.Behaviors.Anchor,
		C3.Behaviors.Flash,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent
	];
};
self.C3_JsPropNameTable = [
	{Browser: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{DragDrop: 0},
	{BoundToLayout: 0},
	{Jumpthru: 0},
	{block_Horizontal: 0},
	{block_Vertical: 0},
	{block_rotate_narrow: 0},
	{Bullet: 0},
	{platformPack_tile: 0},
	{Wrap: 0},
	{block_small: 0},
	{block_square: 0},
	{Rotate: 0},
	{block_corner: 0},
	{Asset: 0},
	{Asset12x: 0},
	{Background: 0},
	{Asset2: 0},
	{Asset252x: 0},
	{Tween: 0},
	{Asset3: 0},
	{Asset4: 0},
	{Sine: 0},
	{Asset5: 0},
	{LeftArrow: 0},
	{Level: 0},
	{levels_button: 0},
	{minimapIcon_arrowD: 0},
	{Next: 0},
	{options_button: 0},
	{Previous: 0},
	{retry_button: 0},
	{RightArrow: 0},
	{SpriteFont: 0},
	{Text: 0},
	{Tutorial: 0},
	{play_button: 0},
	{HM: 0},
	{sound: 0},
	{Audio: 0},
	{Platform: 0},
	{Pin: 0},
	{Player: 0},
	{NUMBER: 0},
	{Anchor: 0},
	{bear_Life: 0},
	{bear_Life2: 0},
	{block_locked_small: 0},
	{Final: 0},
	{Flash: 0},
	{key: 0},
	{Particles2: 0},
	{Solid: 0},
	{Wall: 0},
	{Particles: 0},
	{Particles3: 0},
	{Sprite: 0},
	{spikes1: 0},
	{spikes2: 0},
	{spikes3: 0},
	{spikes4: 0},
	{spikes5: 0},
	{spikes6: 0},
	{spikes7: 0},
	{spikes8: 0},
	{spikes9: 0},
	{spikes10: 0},
	{apple: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{WeeGooSDK: 0},
	{Key: 0},
	{current_level: 0},
	{Highest_level: 0}
];

self.InstanceType = {
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	block_Horizontal: class extends self.ISpriteInstance {},
	block_Vertical: class extends self.ISpriteInstance {},
	block_rotate_narrow: class extends self.ISpriteInstance {},
	platformPack_tile: class extends self.ISpriteInstance {},
	block_small: class extends self.ISpriteInstance {},
	block_square: class extends self.ISpriteInstance {},
	block_corner: class extends self.ISpriteInstance {},
	Asset: class extends self.ISpriteInstance {},
	Asset12x: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Asset2: class extends self.ISpriteInstance {},
	Asset252x: class extends self.ISpriteInstance {},
	Asset3: class extends self.ISpriteInstance {},
	Asset4: class extends self.ISpriteInstance {},
	Asset5: class extends self.ISpriteInstance {},
	LeftArrow: class extends self.ISpriteInstance {},
	Level: class extends self.ITextInstance {},
	levels_button: class extends self.ISpriteInstance {},
	minimapIcon_arrowD: class extends self.ISpriteInstance {},
	Next: class extends self.ISpriteInstance {},
	options_button: class extends self.ISpriteInstance {},
	Previous: class extends self.ISpriteInstance {},
	retry_button: class extends self.ISpriteInstance {},
	RightArrow: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Text: class extends self.ITextInstance {},
	Tutorial: class extends self.ITextInstance {},
	play_button: class extends self.ISpriteInstance {},
	HM: class extends self.ISpriteInstance {},
	sound: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Player: class extends self.ISpriteInstance {},
	bear_Life: class extends self.ISpriteInstance {},
	bear_Life2: class extends self.ISpriteInstance {},
	block_locked_small: class extends self.ISpriteInstance {},
	Final: class extends self.ISpriteInstance {},
	key: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Wall: class extends self.ITiledBackgroundInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Sprite: class extends self.ISpriteInstance {},
	spikes1: class extends self.ISpriteInstance {},
	spikes2: class extends self.ISpriteInstance {},
	spikes3: class extends self.ISpriteInstance {},
	spikes4: class extends self.ISpriteInstance {},
	spikes5: class extends self.ISpriteInstance {},
	spikes6: class extends self.ISpriteInstance {},
	spikes7: class extends self.ISpriteInstance {},
	spikes8: class extends self.ISpriteInstance {},
	spikes9: class extends self.ISpriteInstance {},
	spikes10: class extends self.ISpriteInstance {},
	apple: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {}
}