const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Platform,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.PlatformInfo,
		C3.Plugins.LocalStorage,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Eponesh_GameScore.Acts.ChangeLanguage,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart
	];
};
self.C3_JsPropNameTable = [
	{Anchor: 0},
	{Sprite2: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{vlevo: 0},
	{vpravo: 0},
	{Solid: 0},
	{spike: 0},
	{zemla: 0},
	{zemla2: 0},
	{Sine: 0},
	{Sprite: 0},
	{spike_mobe: 0},
	{Jumpthru: 0},
	{platforma: 0},
	{Spike_vrachalka: 0},
	{fire: 0},
	{control: 0},
	{Platform: 0},
	{player1: 0},
	{Sprite3: 0},
	{Touch: 0},
	{Keyboard: 0},
	{lvl: 0},
	{Sprite6: 0},
	{player2: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Text: 0},
	{Sprite10: 0},
	{spritelvl: 0},
	{textlvl: 0},
	{GamePush: 0},
	{jump: 0},
	{mission: 0},
	{PlatformInfo: 0},
	{Sprite7: 0},
	{money2: 0},
	{money: 0},
	{Text2: 0},
	{SKIN1: 0},
	{SKIN2: 0},
	{Sprite11: 0},
	{money3: 0},
	{LocalStorage: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Family1: 0},
	{skin1: 0},
	{skin2: 0},
	{players: 0},
	{win1: 0},
	{win2: 0},
	{gift: 0}
];

self.InstanceType = {
	Sprite2: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	vlevo: class extends self.ISpriteInstance {},
	vpravo: class extends self.ISpriteInstance {},
	spike: class extends self.ISpriteInstance {},
	zemla: class extends self.ISpriteInstance {},
	zemla2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	spike_mobe: class extends self.ISpriteInstance {},
	platforma: class extends self.ISpriteInstance {},
	Spike_vrachalka: class extends self.ISpriteInstance {},
	fire: class extends self.ISpriteInstance {},
	player1: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	player2: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	spritelvl: class extends self.ISpriteInstance {},
	textlvl: class extends self.ITextInstance {},
	GamePush: class extends self.C3.Plugins.Eponesh_GameScore.Instance {},
	jump: class extends self.ITextInstance {},
	mission: class extends self.ITextInstance {},
	PlatformInfo: class extends self.IInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	money2: class extends self.ITextInstance {},
	money: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	SKIN1: class extends self.ISpriteInstance {},
	SKIN2: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	money3: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Family1: class extends self.ISpriteInstance {}
}