const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.aekiro_proui,
		C3.Plugins.AJAX,
		C3.Plugins.LocalStorage,
		C3.Plugins.NinePatch,
		C3.Plugins.Browser,
		C3.Behaviors.aekiro_button,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Behaviors.scrollto,
		C3.Behaviors.skymenTrail,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Anchor,
		C3.Plugins.WGSDK,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Behaviors.Sin.Acts.SetMovement,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.ScriptsInEvents.Setup_Event65_Act11,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.ScriptsInEvents.Setup_Event69_Act7,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.ScriptsInEvents.Setup_Event72_Act1,
		C3.ScriptsInEvents.Setup_Event72_Act3,
		C3.ScriptsInEvents.Setup_Event74_Act1,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Spritefont2.Exps.Height,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Exps.Width,
		C3.Plugins.Spritefont2.Acts.SetSize,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Particles.Acts.Destroy,
		C3.ScriptsInEvents.Setup_Event82_Act8,
		C3.ScriptsInEvents.Setup_Event82_Act9,
		C3.ScriptsInEvents.Setup_Event86_Act1,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.SpeedForID,
		C3.Plugins.Touch.Exps.TouchID,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Exps.AngleForID,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.NinePatch.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.Particles.Acts.SetRate,
		C3.ScriptsInEvents.Start_Event23_Act2,
		C3.ScriptsInEvents.Start_Event24_Act1,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.ScriptsInEvents.Start_Event26_Act1,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.IsEffectEnabled,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.ScriptsInEvents.Start_Event61_Act1,
		C3.ScriptsInEvents.Start_Event63_Act1,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.ScriptsInEvents.Game_Event1_Act7,
		C3.Behaviors.skymenTrail.Acts.SetWidthStart,
		C3.Behaviors.skymenTrail.Acts.Attach,
		C3.Behaviors.skymenTrail.Acts.Reset,
		C3.ScriptsInEvents.Game_Event19_Act1,
		C3.ScriptsInEvents.Game_Event22_Act1,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.ScriptsInEvents.Game_Event26_Act1,
		C3.ScriptsInEvents.Game_Event28_Act1,
		C3.ScriptsInEvents.Game_Event30_Act1,
		C3.ScriptsInEvents.Game_Event31_Act1,
		C3.ScriptsInEvents.Game_Event32_Act1,
		C3.ScriptsInEvents.Game_Event33_Act1,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.ScriptsInEvents.Game_Event42_Act1,
		C3.ScriptsInEvents.Game_Event44_Act9,
		C3.ScriptsInEvents.Game_Event45_Act4,
		C3.ScriptsInEvents.Game_Event45_Act5,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.ScriptsInEvents.Abilities_Event5_Act1,
		C3.Plugins.Spritefont2.Acts.MoveToTop,
		C3.ScriptsInEvents.Abilities_Event12_Act1
	];
};
self.C3_JsPropNameTable = [
	{ww: 0},
	{hh: 0},
	{gc: 0},
	{Tween: 0},
	{goldicon: 0},
	{Touch: 0},
	{Keyboard: 0},
	{Audio: 0},
	{ProUI: 0},
	{AJAX: 0},
	{LocalStorage: 0},
	{dark: 0},
	{"NAME📌": 0},
	{"DIRECTION_DOWN📌": 0},
	{listTotHeight: 0},
	{listTotHehight2: 0},
	{"9patchchours": 0},
	{"PARENT_NAME📌": 0},
	{touchyinit: 0},
	{touchspeed: 0},
	{slidepos: 0},
	{slideinitialvelocityu: 0},
	{scrolling: 0},
	{piny: 0},
	{pinylimit: 0},
	{yyy: 0},
	{yyyy: 0},
	{choruspin: 0},
	{Browser: 0},
	{dark2: 0},
	{party: 0},
	{Button: 0},
	{buttonsettings: 0},
	{buttonsettings2: 0},
	{buttonsettings3: 0},
	{exitbutton: 0},
	{flags: 0},
	{Fade: 0},
	{message: 0},
	{particleConfetti: 0},
	{particleConfettiP: 0},
	{staar: 0},
	{staar2: 0},
	{staar3: 0},
	{goldbg: 0},
	{w: 0},
	{levelbutton: 0},
	{Rotate: 0},
	{effectbt: 0},
	{levelupef2: 0},
	{backbutton: 0},
	{Sine: 0},
	{tutFinger: 0},
	{tapto: 0},
	{Sprite5: 0},
	{ScrollTo: 0},
	{CameraShake: 0},
	{R: 0},
	{scale: 0},
	{RESPONSIVE: 0},
	{areatext: 0},
	{areatext3: 0},
	{type: 0},
	{textholdd: 0},
	{areatext5: 0},
	{areatitle2: 0},
	{collectionname: 0},
	{collectionbg: 0},
	{collectionbgclosed: 0},
	{desc: 0},
	{price: 0},
	{frame: 0},
	{addicon: 0},
	{redcircle: 0},
	{redcircletxt: 0},
	{Sprite2: 0},
	{cardHolder: 0},
	{baseCard: 0},
	{backMove: 0},
	{booster: 0},
	{Sprite3: 0},
	{Sprite11: 0},
	{Sprite13: 0},
	{Sine2: 0},
	{Sprite14: 0},
	{plane: 0},
	{nextlevels: 0},
	{Sprite15: 0},
	{lockcard: 0},
	{Sprite10: 0},
	{Particles: 0},
	{Particles2: 0},
	{abilitiesdesc: 0},
	{abilitiesbg: 0},
	{abilitiesbuy: 0},
	{AbilitiesCreate: 0},
	{abilitiesimg: 0},
	{abilitiespart: 0},
	{abilitiestxtbg: 0},
	{cbag: 0},
	{CNGRLT: 0},
	{collected: 0},
	{collectioncards: 0},
	{CollectionCreate: 0},
	{collectiongreen: 0},
	{collectionimg: 0},
	{collectionlock: 0},
	{collectionpagebg: 0},
	{collectionrewimg: 0},
	{collectionrewimg2: 0},
	{new: 0},
	{Sprite12: 0},
	{endbutton: 0},
	{endlight: 0},
	{endlight2: 0},
	{fail: 0},
	{end: 0},
	{endb: 0},
	{h: 0},
	{starparticle: 0},
	{TrailHeadStar: 0},
	{TrailRenderer: 0},
	{Trail3: 0},
	{uitopbottom: 0},
	{uimenu: 0},
	{Sprite6: 0},
	{rewardanim: 0},
	{Sprite7: 0},
	{v: 0},
	{spriteText: 0},
	{spriteTextmessage: 0},
	{LobbyCreate: 0},
	{LR: 0},
	{camera: 0},
	{Sprite17: 0},
	{puzzleicon: 0},
	{ranking1: 0},
	{loading: 0},
	{xx: 0},
	{yy: 0},
	{topr: 0},
	{topr2: 0},
	{resp: 0},
	{Sprite: 0},
	{particledrops: 0},
	{Sprite4: 0},
	{Trail4: 0},
	{TrailHeadStar2: 0},
	{Sprite8: 0},
	{drawline: 0},
	{white: 0},
	{Sprite18: 0},
	{spriteText2: 0},
	{fail2: 0},
	{free: 0},
	{hand: 0},
	{lock: 0},
	{money: 0},
	{SCards: 0},
	{decktxt: 0},
	{Sprite9: 0},
	{Sprite19: 0},
	{Anchor: 0},
	{btn_more: 0},
	{WeeGooSDK: 0},
	{"9p_Back": 0},
	{MoveTo: 0},
	{sp_Pin: 0},
	{delete: 0},
	{layer: 0},
	{opacity: 0},
	{ECactive: 0},
	{x: 0},
	{y: 0},
	{height: 0},
	{width: 0},
	{action: 0},
	{aangle: 0},
	{sine: 0},
	{fxMuted: 0},
	{musicMuted: 0},
	{gold: 0},
	{diamond: 0},
	{lives: 0},
	{audioName: 0},
	{Loop: 0},
	{chestReward1: 0},
	{chestReward2: 0},
	{chestReward3: 0},
	{chestRewardq1: 0},
	{chestRewardq2: 0},
	{chestRewardq3: 0},
	{rotateWheelAngle: 0},
	{rewardscreen: 0},
	{animation: 0},
	{valuee: 0},
	{Parameter0: 0},
	{addorsub: 0},
	{value: 0},
	{lastmy: 0},
	{card1frame: 0},
	{card1cname: 0},
	{card1cardname: 0},
	{card1v: 0},
	{card2frame: 0},
	{card2v: 0},
	{carduid: 0},
	{carduid2: 0},
	{card2cname: 0},
	{card2cardname: 0},
	{dcc: 0},
	{name: 0},
	{d: 0},
	{Grid_size: 0},
	{ScrollYLimit: 0},
	{CurrentNAME: 0},
	{level: 0},
	{swipe: 0},
	{gamelevel: 0},
	{x2: 0},
	{y2: 0},
	{color: 0},
	{currentLevel: 0},
	{startx: 0},
	{starty: 0},
	{uid: 0},
	{wheelticket: 0},
	{cstarty2: 0}
];

self.InstanceType = {
	goldicon: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	ProUI: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	dark: class extends self.ISpriteInstance {},
	_9patchchours: class extends self.IWorldInstance {},
	choruspin: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	dark2: class extends self.ISpriteInstance {},
	party: class extends self.ISpriteInstance {},
	buttonsettings: class extends self.ISpriteInstance {},
	buttonsettings2: class extends self.ISpriteInstance {},
	buttonsettings3: class extends self.ISpriteInstance {},
	exitbutton: class extends self.ISpriteInstance {},
	flags: class extends self.ISpriteInstance {},
	message: class extends self.ITextInstance {},
	particleConfetti: class extends self.ISpriteInstance {},
	particleConfettiP: class extends self.IParticlesInstance {},
	staar: class extends self.IParticlesInstance {},
	staar2: class extends self.IParticlesInstance {},
	staar3: class extends self.IParticlesInstance {},
	goldbg: class extends self.ISpriteInstance {},
	levelbutton: class extends self.ISpriteInstance {},
	effectbt: class extends self.ISpriteInstance {},
	levelupef2: class extends self.ISpriteInstance {},
	backbutton: class extends self.ISpriteInstance {},
	tutFinger: class extends self.ISpriteInstance {},
	tapto: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	CameraShake: class extends self.ISpriteInstance {},
	RESPONSIVE: class extends self.ISpriteInstance {},
	areatext: class extends self.ITextInstance {},
	areatext3: class extends self.ITextInstance {},
	textholdd: class extends self.ITextInstance {},
	areatext5: class extends self.ITextInstance {},
	areatitle2: class extends self.ITextInstance {},
	collectionname: class extends self.ITextInstance {},
	collectionbg: class extends self.ISpriteInstance {},
	collectionbgclosed: class extends self.ISpriteInstance {},
	addicon: class extends self.ISpriteInstance {},
	redcircle: class extends self.ISpriteInstance {},
	redcircletxt: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	cardHolder: class extends self.ISpriteInstance {},
	baseCard: class extends self.ISpriteInstance {},
	backMove: class extends self.ISpriteInstance {},
	booster: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	plane: class extends self.ISpriteInstance {},
	nextlevels: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	lockcard: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	abilitiesdesc: class extends self.ITextInstance {},
	abilitiesbg: class extends self.ISpriteInstance {},
	abilitiesbuy: class extends self.ISpriteInstance {},
	AbilitiesCreate: class extends self.ISpriteInstance {},
	abilitiesimg: class extends self.ISpriteInstance {},
	abilitiespart: class extends self.ISpriteInstance {},
	abilitiestxtbg: class extends self.ISpriteInstance {},
	cbag: class extends self.ISpriteInstance {},
	CNGRLT: class extends self.ISpriteInstance {},
	collectioncards: class extends self.ISpriteInstance {},
	CollectionCreate: class extends self.ISpriteInstance {},
	collectiongreen: class extends self.ISpriteInstance {},
	collectionimg: class extends self.ISpriteInstance {},
	collectionlock: class extends self.ISpriteInstance {},
	collectionpagebg: class extends self.ISpriteInstance {},
	collectionrewimg: class extends self.ISpriteInstance {},
	collectionrewimg2: class extends self.ISpriteInstance {},
	new: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	endbutton: class extends self.ISpriteInstance {},
	endlight: class extends self.ISpriteInstance {},
	endlight2: class extends self.ISpriteInstance {},
	fail: class extends self.ISpriteInstance {},
	end: class extends self.ISpriteInstance {},
	endb: class extends self.ISpriteInstance {},
	starparticle: class extends self.ISpriteInstance {},
	TrailHeadStar: class extends self.ISpriteInstance {},
	Trail3: class extends self.ISpriteInstance {},
	uitopbottom: class extends self.ISpriteInstance {},
	uimenu: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	rewardanim: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	spriteText: class extends self.ISpriteFontInstance {},
	spriteTextmessage: class extends self.ISpriteFontInstance {},
	LobbyCreate: class extends self.ISpriteInstance {},
	LR: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	puzzleicon: class extends self.ISpriteInstance {},
	ranking1: class extends self.ISpriteInstance {},
	loading: class extends self.ISpriteInstance {},
	topr: class extends self.ISpriteInstance {},
	topr2: class extends self.ISpriteInstance {},
	resp: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	particledrops: class extends self.IParticlesInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Trail4: class extends self.ISpriteInstance {},
	TrailHeadStar2: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	drawline: class extends self.ISpriteInstance {},
	white: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	spriteText2: class extends self.ISpriteFontInstance {},
	fail2: class extends self.ISpriteInstance {},
	SCards: class extends self.ISpriteInstance {},
	decktxt: class extends self.ITextInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	btn_more: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	_9p_Back: class extends self.IWorldInstance {},
	sp_Pin: class extends self.ISpriteInstance {}
}