const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.sliderbar,
		C3.Plugins.Audio,
		C3.Behaviors.Fade,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.DrawingCanvas,
		C3.Plugins.Browser,
		C3.Plugins.WGSDK,
		C3.Behaviors.DragnDrop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TiledBg.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetTowardPosition,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.sliderbar.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetLayerEffectParam,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.sliderbar.Cnds.OnChanging,
		C3.Plugins.DrawingCanvas.Cnds.OnSavedImage,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.DrawingCanvas.Exps.SavedImageURL,
		C3.Plugins.DrawingCanvas.Acts.ClearCanvas,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Plugins.DrawingCanvas.Acts.SaveImage,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Fade.Acts.StartFade
	];
};
self.C3_JsPropNameTable = [
	{Leg_Left_A: 0},
	{isLastTouched: 0},
	{type: 0},
	{Body: 0},
	{leg_node_L: 0},
	{foot_L: 0},
	{Leg_Left_B: 0},
	{leg_node_R: 0},
	{foot_R: 0},
	{Leg_Right_A: 0},
	{Leg_Right_B: 0},
	{arm_Left_A: 0},
	{arm_node_L: 0},
	{arm_Left_b: 0},
	{Hand_L: 0},
	{Touch: 0},
	{arm_right_A: 0},
	{arm_node_R: 0},
	{arm_right_b: 0},
	{Hand_R: 0},
	{Head: 0},
	{neck: 0},
	{eyes: 0},
	{Mouth: 0},
	{Pos: 0},
	{ui_bg: 0},
	{Body2: 0},
	{Material: 0},
	{arrow_right: 0},
	{arrow_left: 0},
	{arrow_mat_right: 0},
	{arrow_mat_left: 0},
	{sliderType: 0},
	{SliderBar: 0},
	{ui_turn_r: 0},
	{ui_turn_l: 0},
	{ui_minus: 0},
	{ui_plus: 0},
	{ui_saturation: 0},
	{colorWheel: 0},
	{foot_L2: 0},
	{foot_R2: 0},
	{Hand_L2: 0},
	{Hand_R2: 0},
	{Head2: 0},
	{bg_concrete: 0},
	{eyes2: 0},
	{Mouth2: 0},
	{ui_saturation2: 0},
	{arrowLeft: 0},
	{arrowRight: 0},
	{ui_audio: 0},
	{Audio: 0},
	{bg_black: 0},
	{cover_PI: 0},
	{Fade: 0},
	{cover_Dev: 0},
	{cover_Ti: 0},
	{cover_Ball_Red: 0},
	{cover_Ball_blu: 0},
	{Tween: 0},
	{fader: 0},
	{isSelected: 0},
	{btn_play: 0},
	{import: 0},
	{Sine: 0},
	{Title: 0},
	{DrawingCanvas: 0},
	{Browser: 0},
	{WeeGooSDK: 0},
	{DragDrop: 0},
	{BodyParts: 0},
	{Arrows: 0},
	{ArrowsMat: 0},
	{Buttons: 0},
	{Covers: 0},
	{Legs: 0},
	{Head_mat: 0},
	{Body_mat: 0},
	{hand_r: 0},
	{hand_r_mat: 0},
	{hand_l: 0},
	{hand_l_mat: 0},
	{foot_l: 0},
	{foot_l_mat: 0},
	{foot_r: 0},
	{foot_r_mat: 0},
	{eye: 0},
	{mouth: 0},
	{position: 0},
	{isSound: 0}
];

self.InstanceType = {
	Leg_Left_A: class extends self.ITiledBackgroundInstance {},
	Body: class extends self.ISpriteInstance {},
	leg_node_L: class extends self.ISpriteInstance {},
	foot_L: class extends self.ISpriteInstance {},
	Leg_Left_B: class extends self.ITiledBackgroundInstance {},
	leg_node_R: class extends self.ISpriteInstance {},
	foot_R: class extends self.ISpriteInstance {},
	Leg_Right_A: class extends self.ITiledBackgroundInstance {},
	Leg_Right_B: class extends self.ITiledBackgroundInstance {},
	arm_Left_A: class extends self.ITiledBackgroundInstance {},
	arm_node_L: class extends self.ISpriteInstance {},
	arm_Left_b: class extends self.ITiledBackgroundInstance {},
	Hand_L: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	arm_right_A: class extends self.ITiledBackgroundInstance {},
	arm_node_R: class extends self.ISpriteInstance {},
	arm_right_b: class extends self.ITiledBackgroundInstance {},
	Hand_R: class extends self.ISpriteInstance {},
	Head: class extends self.ISpriteInstance {},
	neck: class extends self.ITiledBackgroundInstance {},
	eyes: class extends self.ISpriteInstance {},
	Mouth: class extends self.ISpriteInstance {},
	ui_bg: class extends self.ISpriteInstance {},
	Body2: class extends self.ISpriteInstance {},
	Material: class extends self.ISpriteInstance {},
	arrow_right: class extends self.ISpriteInstance {},
	arrow_left: class extends self.ISpriteInstance {},
	arrow_mat_right: class extends self.ISpriteInstance {},
	arrow_mat_left: class extends self.ISpriteInstance {},
	SliderBar: class extends self.ISliderBarInstance {},
	ui_turn_r: class extends self.ISpriteInstance {},
	ui_turn_l: class extends self.ISpriteInstance {},
	ui_minus: class extends self.ISpriteInstance {},
	ui_plus: class extends self.ISpriteInstance {},
	ui_saturation: class extends self.ISpriteInstance {},
	colorWheel: class extends self.ISpriteInstance {},
	foot_L2: class extends self.ISpriteInstance {},
	foot_R2: class extends self.ISpriteInstance {},
	Hand_L2: class extends self.ISpriteInstance {},
	Hand_R2: class extends self.ISpriteInstance {},
	Head2: class extends self.ISpriteInstance {},
	bg_concrete: class extends self.ISpriteInstance {},
	eyes2: class extends self.ISpriteInstance {},
	Mouth2: class extends self.ISpriteInstance {},
	ui_saturation2: class extends self.ISpriteInstance {},
	arrowLeft: class extends self.ISpriteInstance {},
	arrowRight: class extends self.ISpriteInstance {},
	ui_audio: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	bg_black: class extends self.ITiledBackgroundInstance {},
	cover_PI: class extends self.ISpriteInstance {},
	cover_Dev: class extends self.ISpriteInstance {},
	cover_Ti: class extends self.ISpriteInstance {},
	cover_Ball_Red: class extends self.ISpriteInstance {},
	cover_Ball_blu: class extends self.ISpriteInstance {},
	fader: class extends self.ITiledBackgroundInstance {},
	btn_play: class extends self.ISpriteInstance {},
	import: class extends self.ISpriteInstance {},
	Title: class extends self.ISpriteInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	Browser: class extends self.IInstance {},
	WeeGooSDK: class extends self.IInstance {},
	BodyParts: class extends self.ISpriteInstance {},
	Arrows: class extends self.ISpriteInstance {},
	ArrowsMat: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	Covers: class extends self.ISpriteInstance {},
	Legs: class extends self.ITiledBackgroundInstance {}
}