const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.NinePatch,
		C3.Plugins.Mouse,
		C3.Plugins.Arr,
		C3.Plugins.PlatformInfo,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Behaviors.Flash,
		C3.Behaviors.Timer,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.Anchor,
		C3.Plugins.Browser,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Acts.StopLoop,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Text.Acts.TypewriterFinish,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Exps.len,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.Text.Exps.TextWidth,
		C3.Plugins.Text.Exps.TextHeight,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.NinePatch.Acts.SetAngle,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Text.Cnds.IsRunningTypewriterText,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.WGSDK.Cnds.RewardGranted,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Touch.Exps.TouchCount,
		C3.Plugins.Touch.Exps.XAt,
		C3.Plugins.Touch.Exps.YAt,
		C3.Plugins.System.Exps.layerscrollx,
		C3.Plugins.System.Exps.layerscrolly,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.NinePatch.Exps.BBoxLeft,
		C3.Plugins.NinePatch.Exps.BBoxRight,
		C3.Plugins.NinePatch.Exps.BBoxTop,
		C3.Plugins.NinePatch.Exps.BBoxBottom,
		C3.Plugins.NinePatch.Exps.UID,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Mouse.Exps.WheelDeltaY,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.NinePatch.Cnds.PickByUID,
		C3.Plugins.System.Acts.SetLayerScroll,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.System.Exps.random,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Cnds.OnTypewriterTextFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.PlatformInfo.Cnds.IsOnMacOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnLinux,
		C3.Plugins.PlatformInfo.Cnds.IsOnChromeOS,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.LocalStorage.Cnds.OnAllGetsComplete,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Audio.Acts.Stop
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{Fade: 0},
	{World: 0},
	{Touch: 0},
	{Audio: 0},
	{Background: 0},
	{Identification: 0},
	{Button: 0},
	{Mouse: 0},
	{CatBoundingBox: 0},
	{Array: 0},
	{PlatformInfo: 0},
	{Sine: 0},
	{Logo: 0},
	{Instructor: 0},
	{SpeechBalloon: 0},
	{Modal: 0},
	{Instructions: 0},
	{CatCounter: 0},
	{CatCounterBackground: 0},
	{Pin: 0},
	{ButtonIcon: 0},
	{Flash: 0},
	{Hint1: 0},
	{PawnPattern: 0},
	{CanvasFrame: 0},
	{ReturnToMainMenu: 0},
	{Credits: 0},
	{OffsetDirection: 0},
	{ScrollingAngle: 0},
	{CatPattern: 0},
	{MainMenuCat: 0},
	{Noise: 0},
	{Timer: 0},
	{CatBackgroundCircle: 0},
	{Cats: 0},
	{ColorMask: 0},
	{NEXTLEVEL: 0},
	{sesir: 0},
	{hat: 0},
	{hat1: 0},
	{difference1: 0},
	{difference5: 0},
	{difference3: 0},
	{difference2: 0},
	{difference4: 0},
	{ScoreText: 0},
	{ScoreTextt: 0},
	{kats: 0},
	{Cats1: 0},
	{Cats2: 0},
	{Cats3: 0},
	{Cats4: 0},
	{Cats5: 0},
	{hintID: 0},
	{Hint: 0},
	{hintreklama: 0},
	{CatCounter2: 0},
	{Open: 0},
	{Level: 0},
	{LevelsBlock: 0},
	{select: 0},
	{SpriteFont123: 0},
	{LocalStorage: 0},
	{LevelsText: 0},
	{Logo2: 0},
	{Sprite: 0},
	{Logo3: 0},
	{"10sekundioff": 0},
	{menutimeup: 0},
	{replaytimeup: 0},
	{LiteTween: 0},
	{timeisup: 0},
	{replayploca2: 0},
	{menuploca: 0},
	{ploca: 0},
	{dalje: 0},
	{ruka: 0},
	{dalje2: 0},
	{Credits2: 0},
	{pozadinazaaute: 0},
	{zidzahow: 0},
	{Anchor: 0},
	{StarsFont2: 0},
	{ShopCharacter1: 0},
	{ShopCharacter2: 0},
	{ShopCharacter3: 0},
	{ShopCharacter4: 0},
	{ShopCharacter5: 0},
	{ShopCharacter6: 0},
	{ShopCharacter7: 0},
	{ShopCharacter8: 0},
	{ShopCharacter9: 0},
	{ShopCharacter10: 0},
	{Lockdrugilik: 0},
	{Lockdrugilik2: 0},
	{Lockdrugilik3: 0},
	{Lockdrugilik4: 0},
	{Lockdrugilik5: 0},
	{Lockdrugilik9: 0},
	{ShopSelector: 0},
	{Lockdrugilik6: 0},
	{Lockdrugilik7: 0},
	{Lockdrugilik8: 0},
	{ShopCharacter20: 0},
	{ShopCharacter19: 0},
	{ShopCharacter18: 0},
	{ShopCharacter12: 0},
	{ShopCharacter13: 0},
	{ShopCharacter14: 0},
	{ShopCharacter16: 0},
	{ShopCharacter17: 0},
	{ShopCharacter11: 0},
	{ShopCharacter15: 0},
	{PlayerSkins: 0},
	{StarsFont: 0},
	{shopdugme: 0},
	{shop: 0},
	{StarsFont1: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{hintreklama2: 0},
	{StarsFont3: 0},
	{shop2: 0},
	{moregames: 0},
	{a: 0},
	{Wheel: 0},
	{Text: 0},
	{ctd_score3: 0},
	{krug: 0},
	{Sprite7: 0},
	{zavrti: 0},
	{playzawheels: 0},
	{zavrtisareklamama: 0},
	{addmetakreklama: 0},
	{StarsFont4: 0},
	{zavrti2: 0},
	{Cats6: 0},
	{Sprite4: 0},
	{World2: 0},
	{winpanel4: 0},
	{Sprite43: 0},
	{winpanel2: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Lens3: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{uvecaj: 0},
	{umanji: 0},
	{Sprite10: 0},
	{Sprite13: 0},
	{Sprite62: 0},
	{konfete: 0},
	{Sprite11: 0},
	{sting: 0},
	{oren: 0},
	{mrsun: 0},
	{mrcomputer: 0},
	{funbot: 0},
	{simon: 0},
	{Garnold: 0},
	{funboot: 0},
	{mrtree: 0},
	{mard: 0},
	{daljezakraj: 0},
	{Browser: 0},
	{playerName: 0},
	{y8: 0},
	{Loginy8moja: 0},
	{WeeGooSDK: 0},
	{Sprite12: 0},
	{CatUID: 0},
	{SkipAnimation: 0},
	{FoundAnyErrors: 0},
	{TextIndex: 0},
	{DIALOGUETEXT: 0},
	{BoopCooldown: 0},
	{TotalCatsFound: 0},
	{Unlock20: 0},
	{Unlock19: 0},
	{Unlock18: 0},
	{Unlock17: 0},
	{Unlock16: 0},
	{Unlock15: 0},
	{Unlock14: 0},
	{Unlock13: 0},
	{Unlock12: 0},
	{Unlock11: 0},
	{Unlock10: 0},
	{Unlock9: 0},
	{Unlock8: 0},
	{Unlock7: 0},
	{Unlock6: 0},
	{Unlock5: 0},
	{Unlock4: 0},
	{Unlock3: 0},
	{Unlock2: 0},
	{Unlock1: 0},
	{character: 0},
	{unlocks: 0},
	{stars: 0},
	{Coins: 0},
	{highscore: 0},
	{LAYOUTTRANSITIONDURATION: 0},
	{Score: 0},
	{currentHintID: 0},
	{LastLevel: 0},
	{WIN: 0},
	{LevelComplete: 0},
	{LAST_LEVEL: 0},
	{NextLayoutNameBuffer: 0},
	{IsBusy: 0},
	{NextLayoutName: 0},
	{InputFocus: 0},
	{Index: 0},
	{StartingWidth: 0},
	{StartingHeight: 0},
	{ReferenceX: 0},
	{ReferenceY: 0},
	{ChangeX: 0},
	{ChangeY: 0},
	{IgnoreCat: 0},
	{ReferenceDistance: 0},
	{Change: 0},
	{ButtonTiltDirection: 0},
	{ButtonUID: 0},
	{PositionX: 0},
	{PositionY: 0},
	{Delta: 0},
	{Scale: 0},
	{A: 0},
	{B: 0},
	{C: 0},
	{DEFAULTSFXVOLUME: 0},
	{DEFAULTBGMVOLUME: 0},
	{SFXVolume: 0},
	{BGMVolume: 0},
	{SFXName: 0},
	{IgnoreSFXVolume: 0},
	{BGMName: 0},
	{IgnoreBGMVolume: 0},
	{Direction: 0},
	{CurrentValue: 0},
	{TargetValue: 0},
	{Speed: 0},
	{IsWithinRange: 0},
	{Minimum: 0},
	{Maximum: 0},
	{Target: 0},
	{FiniteLerpThreshold: 0},
	{InterpolatedValue: 0},
	{PointA: 0},
	{PointB: 0},
	{Factor: 0},
	{HasBooted: 0},
	{TextBuffer: 0},
	{sectorCount: 0},
	{prizes: 0},
	{winningSector: 0},
	{ctd_score: 0}
];

self.InstanceType = {
	Fade: class extends self.ITiledBackgroundInstance {},
	World: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	Button: class extends self.IWorldInstance {},
	Mouse: class extends self.IInstance {},
	CatBoundingBox: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	PlatformInfo: class extends self.IInstance {},
	Logo: class extends self.ISpriteInstance {},
	Instructor: class extends self.ISpriteInstance {},
	SpeechBalloon: class extends self.IWorldInstance {},
	Modal: class extends self.ITiledBackgroundInstance {},
	Instructions: class extends self.ITextInstance {},
	CatCounter: class extends self.ITextInstance {},
	CatCounterBackground: class extends self.ISpriteInstance {},
	ButtonIcon: class extends self.ISpriteInstance {},
	Hint1: class extends self.ITextInstance {},
	PawnPattern: class extends self.ITiledBackgroundInstance {},
	CanvasFrame: class extends self.IWorldInstance {},
	Credits: class extends self.ITextInstance {},
	CatPattern: class extends self.ITiledBackgroundInstance {},
	MainMenuCat: class extends self.ISpriteInstance {},
	Noise: class extends self.ITiledBackgroundInstance {},
	CatBackgroundCircle: class extends self.ISpriteInstance {},
	Cats: class extends self.ISpriteInstance {},
	ColorMask: class extends self.ITiledBackgroundInstance {},
	NEXTLEVEL: class extends self.ISpriteInstance {},
	hat: class extends self.ISpriteInstance {},
	hat1: class extends self.ISpriteInstance {},
	difference1: class extends self.ISpriteInstance {},
	difference5: class extends self.ISpriteInstance {},
	difference3: class extends self.ISpriteInstance {},
	difference2: class extends self.ISpriteInstance {},
	difference4: class extends self.ISpriteInstance {},
	ScoreText: class extends self.ITextInstance {},
	ScoreTextt: class extends self.ITextInstance {},
	Cats1: class extends self.ISpriteInstance {},
	Cats2: class extends self.ISpriteInstance {},
	Cats3: class extends self.ISpriteInstance {},
	Cats4: class extends self.ISpriteInstance {},
	Cats5: class extends self.ISpriteInstance {},
	Hint: class extends self.ISpriteInstance {},
	hintreklama: class extends self.ISpriteInstance {},
	CatCounter2: class extends self.ITextInstance {},
	LevelsBlock: class extends self.ISpriteInstance {},
	select: class extends self.ISpriteInstance {},
	SpriteFont123: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	LevelsText: class extends self.ISpriteFontInstance {},
	Logo2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Logo3: class extends self.ISpriteInstance {},
	_10sekundioff: class extends self.ISpriteInstance {},
	menutimeup: class extends self.ISpriteInstance {},
	replaytimeup: class extends self.ISpriteInstance {},
	timeisup: class extends self.ISpriteInstance {},
	replayploca2: class extends self.ISpriteInstance {},
	menuploca: class extends self.ISpriteInstance {},
	ploca: class extends self.ISpriteInstance {},
	dalje: class extends self.IWorldInstance {},
	ruka: class extends self.ISpriteInstance {},
	dalje2: class extends self.IWorldInstance {},
	Credits2: class extends self.ITextInstance {},
	pozadinazaaute: class extends self.ISpriteInstance {},
	zidzahow: class extends self.ISpriteInstance {},
	StarsFont2: class extends self.ISpriteFontInstance {},
	ShopCharacter1: class extends self.ISpriteInstance {},
	ShopCharacter2: class extends self.ISpriteInstance {},
	ShopCharacter3: class extends self.ISpriteInstance {},
	ShopCharacter4: class extends self.ISpriteInstance {},
	ShopCharacter5: class extends self.ISpriteInstance {},
	ShopCharacter6: class extends self.ISpriteInstance {},
	ShopCharacter7: class extends self.ISpriteInstance {},
	ShopCharacter8: class extends self.ISpriteInstance {},
	ShopCharacter9: class extends self.ISpriteInstance {},
	ShopCharacter10: class extends self.ISpriteInstance {},
	Lockdrugilik: class extends self.ISpriteInstance {},
	Lockdrugilik2: class extends self.ISpriteInstance {},
	Lockdrugilik3: class extends self.ISpriteInstance {},
	Lockdrugilik4: class extends self.ISpriteInstance {},
	Lockdrugilik5: class extends self.ISpriteInstance {},
	Lockdrugilik9: class extends self.ISpriteInstance {},
	ShopSelector: class extends self.ISpriteInstance {},
	Lockdrugilik6: class extends self.ISpriteInstance {},
	Lockdrugilik7: class extends self.ISpriteInstance {},
	Lockdrugilik8: class extends self.ISpriteInstance {},
	ShopCharacter20: class extends self.ISpriteInstance {},
	ShopCharacter19: class extends self.ISpriteInstance {},
	ShopCharacter18: class extends self.ISpriteInstance {},
	ShopCharacter12: class extends self.ISpriteInstance {},
	ShopCharacter13: class extends self.ISpriteInstance {},
	ShopCharacter14: class extends self.ISpriteInstance {},
	ShopCharacter16: class extends self.ISpriteInstance {},
	ShopCharacter17: class extends self.ISpriteInstance {},
	ShopCharacter11: class extends self.ISpriteInstance {},
	ShopCharacter15: class extends self.ISpriteInstance {},
	PlayerSkins: class extends self.ISpriteInstance {},
	StarsFont: class extends self.ISpriteFontInstance {},
	shopdugme: class extends self.ISpriteInstance {},
	shop: class extends self.IWorldInstance {},
	StarsFont1: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	hintreklama2: class extends self.ISpriteInstance {},
	StarsFont3: class extends self.ITextInstance {},
	shop2: class extends self.IWorldInstance {},
	moregames: class extends self.ISpriteInstance {},
	Wheel: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	ctd_score3: class extends self.ISpriteFontInstance {},
	krug: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Pin: class extends self.ISpriteInstance {},
	zavrti: class extends self.ISpriteInstance {},
	playzawheels: class extends self.ISpriteInstance {},
	zavrtisareklamama: class extends self.ISpriteInstance {},
	addmetakreklama: class extends self.ISpriteInstance {},
	StarsFont4: class extends self.ITextInstance {},
	zavrti2: class extends self.ISpriteInstance {},
	Cats6: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	World2: class extends self.ISpriteInstance {},
	winpanel4: class extends self.ISpriteInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	winpanel2: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Lens3: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	uvecaj: class extends self.ISpriteInstance {},
	umanji: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite62: class extends self.ISpriteInstance {},
	konfete: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	sting: class extends self.ISpriteInstance {},
	oren: class extends self.ISpriteInstance {},
	mrsun: class extends self.ISpriteInstance {},
	mrcomputer: class extends self.ISpriteInstance {},
	funbot: class extends self.ISpriteInstance {},
	simon: class extends self.ISpriteInstance {},
	Garnold: class extends self.ISpriteInstance {},
	funboot: class extends self.ISpriteInstance {},
	mrtree: class extends self.ISpriteInstance {},
	mard: class extends self.ISpriteInstance {},
	daljezakraj: class extends self.IWorldInstance {},
	Browser: class extends self.IInstance {},
	playerName: class extends self.ITextInstance {},
	y8: class extends self.ISpriteInstance {},
	Loginy8moja: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	Sprite12: class extends self.ISpriteInstance {}
}