const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.Keyboard,
		C3.Plugins.Arr,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.AJAX,
		C3.Plugins.NinePatch,
		C3.Plugins.Particles,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Behaviors.Flash,
		C3.Plugins.gamepad,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.AdvancedRandom.Acts.CreatePermutationTable,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.float,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.AdvancedRandom.Exps.Permutation,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.TiledBg.Exps.Count,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareChildCount,
		C3.Plugins.Sprite.Exps.ChildCount,
		C3.Plugins.Sprite.Cnds.PickNthChild,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Acts.SetLayoutAngle,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{Player: 0},
	{Rope: 0},
	{InitialX: 0},
	{InitialY: 0},
	{PickedSomething: 0},
	{Sine: 0},
	{Tween: 0},
	{Hook: 0},
	{Sparks: 0},
	{Valuable: 0},
	{Level: 0},
	{Keyboard: 0},
	{AvailablePositions: 0},
	{AdvancedRandom: 0},
	{AJAX: 0},
	{GameData: 0},
	{FogMask: 0},
	{TiledBackground: 0},
	{GameManager: 0},
	{BlurMask: 0},
	{FogGlow: 0},
	{AirDust: 0},
	{Fade: 0},
	{Flash: 0},
	{TextFont: 0},
	{Gamepad: 0},
	{WeeGooSDK: 0},
	{Lighten: 0},
	{MAXITEMS: 0},
	{HookWeight: 0},
	{MaxDistance: 0},
	{DistanceFromObject: 0},
	{ObjectWeight: 0},
	{Scale: 0},
	{Duration: 0},
	{Blur: 0},
	{MaxAngleVariation: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Rope: class extends self.ITiledBackgroundInstance {},
	Hook: class extends self.ISpriteInstance {},
	Sparks: class extends self.ISpriteInstance {},
	Valuable: class extends self.ISpriteInstance {},
	Level: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	AvailablePositions: class extends self.IArrayInstance {},
	AdvancedRandom: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	GameData: class extends self.IArrayInstance {},
	FogMask: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	GameManager: class extends self.ISpriteInstance {},
	BlurMask: class extends self.IWorldInstance {},
	FogGlow: class extends self.ISpriteInstance {},
	AirDust: class extends self.IParticlesInstance {},
	TextFont: class extends self.ISpriteFontInstance {},
	Gamepad: class extends self.IInstance {},
	WeeGooSDK: class extends self.IInstance {},
	Lighten: class extends self.ISpriteInstance {}
}