const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Behaviors.Pin,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Plugins.TiledBg,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Bullet,
		C3.Plugins.NinePatch,
		C3.Behaviors.destroy,
		C3.Behaviors.MoveTo,
		C3.Plugins.Arr,
		C3.Behaviors.Physics,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Dictionary,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.Sprite.Acts.SetMeshPoint,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Text.Exps.FaceSize,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Eponesh_GameScore.Cnds.IsSocialsSupportsShare,
		C3.Plugins.Eponesh_GameScore.Cnds.PlatformType,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.LockOrientation,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Text.Cnds.CompareOpacity,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Arr.Exps.At,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetAcceleration,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsPreloaderPlaying,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Exps.MeshColumns,
		C3.Plugins.Sprite.Exps.MeshRows,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetMeshSize,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.NinePatch.Exps.BBoxLeft,
		C3.Plugins.NinePatch.Exps.BBoxTop,
		C3.Plugins.NinePatch.Exps.BBoxRight,
		C3.Plugins.NinePatch.Exps.BBoxBottom,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.AJAX.Cnds.OnAnyComplete,
		C3.Plugins.System.Exps.left,
		C3.Plugins.AJAX.Exps.Tag,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.System.Exps.trim,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.Json.Exps.CurrentValue,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.DragnDrop.Cnds.IsEnabled,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerFetchFields,
		C3.Plugins.Eponesh_GameScore.Cnds.IsPlayerReady,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPlayerLoadError,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerReset,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerScore,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSetScore,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsStickyPlaying,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowSticky,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsRewardedPlaying,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Eponesh_GameScore.Cnds.OnResume,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardSetRecord,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardPublishRecord,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardOpen,
		C3.Plugins.Eponesh_GameScore.Acts.GamesCollectionsOpen,
		C3.Plugins.Eponesh_GameScore.Acts.AchievementsUnlock,
		C3.Plugins.Eponesh_GameScore.Acts.AchievementsOpen,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsInvite,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsPost,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.OnURLLoaded,
		C3.Plugins.NinePatch.Cnds.IsVisible,
		C3.Plugins.NinePatch.Cnds.CompareOpacity,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.NinePatch.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetOpacity
	];
};
self.C3_JsPropNameTable = [
	{class: 0},
	{Background: 0},
	{classSub: 0},
	{num: 0},
	{xDefault: 0},
	{sizeDefault: 0},
	{Fade: 0},
	{Fade2: 0},
	{Pin: 0},
	{Tween: 0},
	{TextInfo: 0},
	{Body: 0},
	{state: 0},
	{defaultWidth: 0},
	{defaultHeight: 0},
	{Fade3: 0},
	{Sine: 0},
	{Button: 0},
	{Dharmagames: 0},
	{Rotate: 0},
	{Icon: 0},
	{Kundalini: 0},
	{LogoMask: 0},
	{MaskScroll: 0},
	{lastY: 0},
	{defaultY: 0},
	{DragDrop: 0},
	{ScrollMarker: 0},
	{TextTest: 0},
	{TextButton: 0},
	{TextButtonThemes: 0},
	{Bullet: 0},
	{Firework: 0},
	{TextDescription: 0},
	{TextTitle: 0},
	{Window: 0},
	{WindowBackground: 0},
	{TextButtonThemesNew: 0},
	{defaultX: 0},
	{ScrollBarBackground: 0},
	{ScrollBarSlider: 0},
	{DestroyOutsideLayout: 0},
	{MoveTo: 0},
	{Coin: 0},
	{row: 0},
	{column: 0},
	{Mesh: 0},
	{MeshBase: 0},
	{Picture: 0},
	{Frame: 0},
	{Shadow: 0},
	{ArrayThemes: 0},
	{MeshBaseFrame: 0},
	{Physics: 0},
	{Lump: 0},
	{Trash: 0},
	{ArrayPictures: 0},
	{ArrayAlbum: 0},
	{ArrayTrash: 0},
	{ArrayFirework: 0},
	{PictureAlbum: 0},
	{ArrayAlbumTemp: 0},
	{Block: 0},
	{targetX: 0},
	{targetY: 0},
	{timeMove: 0},
	{Finger: 0},
	{ArrayProgress: 0},
	{Keyboard: 0},
	{Touch: 0},
	{Audio: 0},
	{PlatformInfo: 0},
	{GamePush: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{AJAX: 0},
	{JSON: 0},
	{Dictionary: 0},
	{Mouse: 0},
	{meshDragStartX: 0},
	{meshDragStartY: 0},
	{meshBaseToggleStateDistance: 0},
	{meshOffsetFromBaseDistance: 0},
	{albumPages: 0},
	{albumPagesSizeDefault: 0},
	{albumPagesIncreaseCost: 0},
	{background: 0},
	{columnDefault: 0},
	{countLumpsMax: 0},
	{difficulty: 0},
	{fingerNum: 0},
	{frameOffset: 0},
	{frameWidthDefault: 0},
	{frameBottom: 0},
	{frameLeft: 0},
	{frameRight: 0},
	{frameTop: 0},
	{level: 0},
	{gameName: 0},
	{language: 0},
	{languagePrevious: 0},
	{loadHelp: 0},
	{loadMusic: 0},
	{loadSound: 0},
	{log: 0},
	{mode: 0},
	{modeLoadingGamePush: 0},
	{modePrevious: 0},
	{music: 0},
	{musicVolume: 0},
	{pictureBottom: 0},
	{pictureFileName: 0},
	{pictureHeight: 0},
	{pictureLeft: 0},
	{pictureRight: 0},
	{pictureSizeFactor: 0},
	{pictureTop: 0},
	{pictureWidth: 0},
	{prompt: 0},
	{record: 0},
	{rowDefault: 0},
	{score: 0},
	{scorePerPicture: 0},
	{sound: 0},
	{soundVolume: 0},
	{step: 0},
	{stickDistance: 0},
	{theme: 0},
	{themeNum: 0},
	{timeMoveCoinToBar: 0},
	{touchGesture: 0},
	{tutorial: 0},
	{URLGamePushFiles: 0},
	{transition: 0},
	{text: 0},
	{textFadeIn: 0},
	{fade: 0},
	{randomIndexArrayFirework: 0},
	{particle: 0},
	{countParticles: 0},
	{fireworkX: 0},
	{fireworkY: 0},
	{scale: 0},
	{speed: 0},
	{fadeWait: 0},
	{fadeOut: 0},
	{fireworkSound: 0},
	{fireworkSoundVolume: 0},
	{increaseScale: 0},
	{increaseTime: 0},
	{shakeType: 0},
	{coinX: 0},
	{coinY: 0},
	{coinsCount: 0},
	{layer: 0},
	{fingerX: 0},
	{fingerY: 0},
	{fadeIn: 0},
	{countLumps: 0},
	{target: 0},
	{layout: 0},
	{winTrigger: 0},
	{barYStart: 0},
	{barYBottom: 0},
	{buttonTheme0X: 0},
	{buttonThemeBottomY: 0},
	{buttonThemeDistanceX: 0},
	{buttonThemeDistanceY: 0},
	{buttonThemeDistanceToShadow: 0},
	{buttonThemeWidth: 0},
	{buttonThemeHeight: 0},
	{buttonThemeNewOffsetX: 0},
	{buttonThemeNewOffsetY: 0},
	{buttonThemePictureWidth: 0},
	{buttonThemePictureOffsetY: 0},
	{buttonThemeTextOffsetY: 0},
	{timerTouchList: 0},
	{touchStartX: 0},
	{touchStartY: 0},
	{touchX: 0},
	{touchY: 0},
	{triggerTouchList: 0},
	{currentThemeNum: 0},
	{adsInterstitial: 0},
	{achievements: 0},
	{platform: 0},
	{gamePushAdsRewardedTarget: 0},
	{loadPlayerFields: 0},
	{aaTestString: 0},
	{abTestNum: 0},
	{loadArrayThemes: 0},
	{loadArrayPictures: 0},
	{loadArrayAlbum: 0},
	{loadArrayTrash: 0},
	{URLScripts: 0},
	{URLImages: 0},
	{countPictures: 0},
	{currentTheme: 0},
	{buttonAlbumDistanceX: 0},
	{buttonAlbumDistanceToShadow: 0},
	{buttonAlbumHeight: 0},
	{buttonAlbumPictureHeight: 0},
	{buttonAlbumWidth: 0},
	{buttonAlbumPictureNum: 0},
	{buttonPictureDeleteOffsetX: 0},
	{buttonPictureDeleteOffsetY: 0},
	{countPicturesVisibleInAlbumScreen: 0},
	{countPicturesVisibleInScreen: 0},
	{scrollbarOffsetFactor: 0},
	{pageNum: 0},
	{index: 0},
	{indexTemp: 0}
];

self.InstanceType = {
	Background: class extends self.ISpriteInstance {},
	TextInfo: class extends self.ITextInstance {},
	Body: class extends self.ISpriteInstance {},
	Button: class extends self.ISpriteInstance {},
	Dharmagames: class extends self.ISpriteInstance {},
	Icon: class extends self.ISpriteInstance {},
	Kundalini: class extends self.ISpriteInstance {},
	LogoMask: class extends self.ITiledBackgroundInstance {},
	MaskScroll: class extends self.ITiledBackgroundInstance {},
	ScrollMarker: class extends self.ISpriteInstance {},
	TextTest: class extends self.ITextInstance {},
	TextButton: class extends self.ITextInstance {},
	TextButtonThemes: class extends self.ITextInstance {},
	Firework: class extends self.ISpriteInstance {},
	TextDescription: class extends self.ITextInstance {},
	TextTitle: class extends self.ITextInstance {},
	Window: class extends self.IWorldInstance {},
	WindowBackground: class extends self.ITiledBackgroundInstance {},
	TextButtonThemesNew: class extends self.ITextInstance {},
	ScrollBarBackground: class extends self.IWorldInstance {},
	ScrollBarSlider: class extends self.IWorldInstance {},
	Coin: class extends self.ISpriteInstance {},
	Mesh: class extends self.ISpriteInstance {},
	MeshBase: class extends self.ISpriteInstance {},
	Picture: class extends self.ISpriteInstance {},
	Frame: class extends self.IWorldInstance {},
	Shadow: class extends self.IWorldInstance {},
	ArrayThemes: class extends self.IArrayInstance {},
	MeshBaseFrame: class extends self.ISpriteInstance {},
	Lump: class extends self.ISpriteInstance {},
	Trash: class extends self.ISpriteInstance {},
	ArrayPictures: class extends self.IArrayInstance {},
	ArrayAlbum: class extends self.IArrayInstance {},
	ArrayTrash: class extends self.IArrayInstance {},
	ArrayFirework: class extends self.IArrayInstance {},
	PictureAlbum: class extends self.ISpriteInstance {},
	ArrayAlbumTemp: class extends self.IArrayInstance {},
	Block: class extends self.ITiledBackgroundInstance {},
	Finger: class extends self.ISpriteInstance {},
	ArrayProgress: class extends self.IArrayInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	GamePush: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	Mouse: class extends self.IInstance {}
}