const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Fade,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Behaviors.scrollto,
		C3.Plugins.NinePatch,
		C3.Behaviors.solid,
		C3.Behaviors.Anchor,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Plugins.TextBox,
		C3.Behaviors.MoveTo,
		C3.Plugins.TiledBg,
		C3.Behaviors.destroy,
		C3.Behaviors.Physics,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Bullet,
		C3.Behaviors.Platform,
		C3.Behaviors.Sin,
		C3.Plugins.Tilemap,
		C3.Plugins.Arr,
		C3.Behaviors.Rotate,
		C3.Plugins.AJAX,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Touch,
		C3.Plugins.XML,
		C3.Plugins.Dictionary,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.time,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SetDoubleJumpEnabled,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Eponesh_GameScore.Cnds.IsSocialsSupportsShare,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Eponesh_GameScore.Cnds.IsGamesCollectionsAvailable,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsRewardedAvailable,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsPreloaderPlaying,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetSolidCollisionFilter,
		C3.Behaviors.Platform.Exps.MaxSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Text.Exps.FaceSize,
		C3.Plugins.TextBox.Exps.Count,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.TextBox.Cnds.IsFocused,
		C3.Plugins.TextBox.Acts.SetPlaceholder,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSetName,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.TiledBg.Exps.Count,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Sin.Acts.SetMovement,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.Text.Exps.Text,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Acts.SetDefaultControls,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Behaviors.Platform.Acts.SetDeceleration,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.XML.Acts.Load,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.XML.Exps.StringValue,
		C3.Plugins.XML.Exps.NumberValue,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStart,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStop,
		C3.Plugins.Eponesh_GameScore.Cnds.IsPlayerReady,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsRewardedPlaying,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Eponesh_GameScore.Cnds.OnResume,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsStickyPlaying,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowSticky,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerReset,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerID,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.TextBox.Cnds.CompareInstanceVar,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardFetchPlayerRating,
		C3.Plugins.Eponesh_GameScore.Cnds.OnLeaderboardFetchPlayer,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardPlayerPosition,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardOpen,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsInvite,
		C3.Plugins.Eponesh_GameScore.Acts.GamesCollectionsOpen
	];
};
self.C3_JsPropNameTable = [
	{class: 0},
	{state: 0},
	{num: 0},
	{id: 0},
	{defaultWidth: 0},
	{defaultHeight: 0},
	{DragDrop: 0},
	{Fade: 0},
	{Fade2: 0},
	{Tween: 0},
	{Pin: 0},
	{Button: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{WindowLevelComplete: 0},
	{TitleGame: 0},
	{Solid: 0},
	{Anchor: 0},
	{Bar: 0},
	{ButtonLevelSelect: 0},
	{WindowQuit: 0},
	{RibbonSimple: 0},
	{RibbonGala: 0},
	{WindowSettings: 0},
	{TextGems: 0},
	{TextBarLevel: 0},
	{TextTime: 0},
	{TextTest: 0},
	{TextTest2: 0},
	{TextLevelComplete: 0},
	{TextLevelSelectTime: 0},
	{TextWindowQuit: 0},
	{TextConnect: 0},
	{TextAllHighScores: 0},
	{sizeDefault: 0},
	{TextButton: 0},
	{WindowAllHighScores: 0},
	{TextSmallHighScores: 0},
	{MoveTo: 0},
	{TextInput: 0},
	{Fade3: 0},
	{TextNotification: 0},
	{TextHello: 0},
	{TextPrompt: 0},
	{WindowInputPlayerName: 0},
	{TextWindowTitle: 0},
	{TextLevelSelectNumber: 0},
	{ScrollMarkerLevelLeft: 0},
	{ScrollMarkerLevelRight: 0},
	{PromptButtonUp: 0},
	{DestroyOutsideLayout: 0},
	{TextLevelNumber: 0},
	{TextLevelStartPrompt: 0},
	{TextLogo: 0},
	{TextProgressbar: 0},
	{Physics: 0},
	{FloorPhysicInvisible: 0},
	{Jumpthru: 0},
	{PlatformInvisible: 0},
	{LevelBorder: 0},
	{PromptArrowJump: 0},
	{TextRank: 0},
	{biome: 0},
	{Lock: 0},
	{WindowHighScores: 0},
	{WindowLevelSelect1: 0},
	{Icon: 0},
	{WindowLevelSelect2: 0},
	{TextBar: 0},
	{TextTitle: 0},
	{Hearts: 0},
	{ScrollMarkerHighScoresBottom: 0},
	{ScrollMarkerHighScoresTop: 0},
	{ScrollMarkerShopLeft: 0},
	{ScrollMarkerShopRight: 0},
	{TextPromptStart: 0},
	{WindowCoins: 0},
	{WindowGems: 0},
	{WindowPlumes: 0},
	{WindowSkins: 0},
	{MaskBottom: 0},
	{MaskTop: 0},
	{WindowLevelSelect3: 0},
	{TextStarterPack: 0},
	{WindowLevelSelect4: 0},
	{TextVersion: 0},
	{PanelShare: 0},
	{TextPanelTitle: 0},
	{Bullet: 0},
	{Bat: 0},
	{Bg: 0},
	{jumping: 0},
	{lockX: 0},
	{invulnerability: 0},
	{Platform: 0},
	{PlayerBase: 0},
	{Player: 0},
	{EndLevel: 0},
	{EndPoint: 0},
	{Coin: 0},
	{direct: 0},
	{maxSpeed: 0},
	{Mushroom: 0},
	{dec: 0},
	{Sine: 0},
	{Sine2: 0},
	{Sine3: 0},
	{ParticleEffect: 0},
	{Shadow: 0},
	{Spikes: 0},
	{started: 0},
	{StartPoint: 0},
	{TiledBackground1: 0},
	{dir: 0},
	{TriggerReversal: 0},
	{TriggerJump: 0},
	{move: 0},
	{posX: 0},
	{Water: 0},
	{Tilemap: 0},
	{ArrayLevelsResult: 0},
	{healt: 0},
	{BossMushroom: 0},
	{Wall: 0},
	{FlyingFox: 0},
	{health: 0},
	{BossFlyingFox: 0},
	{Ceiling: 0},
	{EasterEgg: 0},
	{Sand: 0},
	{TilemapEasterEggs: 0},
	{TiledBackground2: 0},
	{Gem: 0},
	{CoinPrize: 0},
	{WallPlatformerInvisible: 0},
	{PlayerTest: 0},
	{Plume: 0},
	{Ice: 0},
	{TiledBackground3: 0},
	{Penguin: 0},
	{startX: 0},
	{startY: 0},
	{startAngle: 0},
	{Fish: 0},
	{ArrayPlumes: 0},
	{ArraySkins: 0},
	{IceFloe: 0},
	{BossFish: 0},
	{Lava: 0},
	{Periscope: 0},
	{Fireball: 0},
	{TiledBackground4: 0},
	{Dwarf: 0},
	{IslandLava: 0},
	{SpikesFalling: 0},
	{Rotate: 0},
	{SpikesFallingPiece: 0},
	{IslandFalling: 0},
	{BossDwarf: 0},
	{AJAX: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{PlatformInfo: 0},
	{Touch: 0},
	{XML: 0},
	{Dictionary: 0},
	{GamePush: 0},
	{countTopHighScoresInTable: 0},
	{dev: 0},
	{fixScore: 0},
	{hiScore: 0},
	{scrollMarkerHighScoresStartY: 0},
	{scrollMarkerHighScoresTopYDefault: 0},
	{scrollMarkerHighScoresBottomYUpLimit: 0},
	{touchStartY: 0},
	{timerTouchHighScrores: 0},
	{triggerTouchHighScrores: 0},
	{buttonLeftX: 0},
	{buttonLeftXDefault: 0},
	{buttonLeftY: 0},
	{buttonLeftYDefault: 0},
	{buttonRightX: 0},
	{buttonRightXDefault: 0},
	{buttonRightY: 0},
	{buttonRightYDefault: 0},
	{buttonJumpX: 0},
	{buttonJumpXDefault: 0},
	{buttonJumpY: 0},
	{buttonJumpYDefault: 0},
	{buttonRestartX: 0},
	{buttonRestartXDefault: 0},
	{buttonRestartY: 0},
	{buttonRestartYDefault: 0},
	{playerNum: 0},
	{scrollMarkerLevelStartX: 0},
	{timerTouchLevel: 0},
	{touchStartX: 0},
	{triggerTouchLevel: 0},
	{gemsForOpenLevel: 0},
	{gemsForOpenBiome2: 0},
	{bossFlyingFoxAttackHeight: 0},
	{bossFlyingFoxHitWait: 0},
	{bossFlyingFoxSpeedFall: 0},
	{bossFlyingFoxSpeedFly: 0},
	{bossFlyingFoxSpeedKick: 0},
	{coins: 0},
	{coinsPerLevel: 0},
	{coinsPerBuy1: 0},
	{coinsPerBuy2: 0},
	{costCopper: 0},
	{costGold: 0},
	{costSilver: 0},
	{countHighScrores: 0},
	{countLevels: 0},
	{countPlumesInShop: 0},
	{countSkinsInShop: 0},
	{currentLevel: 0},
	{deltaTime: 0},
	{deltaTimeMilliseconds: 0},
	{deltaTimeMinutes: 0},
	{deltaTimeSeconds: 0},
	{flyingFoxSpeedFall: 0},
	{flyingFoxSpeedFly: 0},
	{flyingFoxAttackHeight: 0},
	{flyingFoxHitWait: 0},
	{gameName: 0},
	{gems: 0},
	{gemsPerLevel: 0},
	{gemsPerBuy1: 0},
	{gemsPerBuy2: 0},
	{language: 0},
	{levelAvailable: 0},
	{lives: 0},
	{loadMoveButtons: 0},
	{maxLenghtPlayerName: 0},
	{mode: 0},
	{modePrevious: 0},
	{music: 0},
	{musicCurrent: 0},
	{musicVolume: 0},
	{playerName: 0},
	{playerNamePrevious: 0},
	{pause: 0},
	{playerLastX: 0},
	{playerLastY: 0},
	{playerMaxSpeedDefault: 0},
	{playerMaxSpeedSand: 0},
	{playerMaxSpeedIce: 0},
	{playerAccelerationIce: 0},
	{playerAccelerationDefault: 0},
	{playerDecelerationIce: 0},
	{playerDecelerationDefault: 0},
	{playerTouchedStart: 0},
	{rank: 0},
	{readyPlayButtons: 0},
	{score: 0},
	{sound: 0},
	{soundVolume: 0},
	{screenPrevious: 0},
	{textInputPlayerNameX: 0},
	{textInputPlayerNameXLeft: 0},
	{timeDefaultForAnyLevel: 0},
	{timeDeltaSeconds: 0},
	{timeMax: 0},
	{timeMilliseconds: 0},
	{timeMinutes: 0},
	{timeSeconds: 0},
	{timeTotalSeconds: 0},
	{timeTotalSecondsForAllLevels: 0},
	{timeTotalSecondsForAllLevelsPrevious: 0},
	{transition: 0},
	{factor: 0},
	{text: 0},
	{coinX: 0},
	{coinY: 0},
	{cost: 0},
	{pieceX: 0},
	{pieceY: 0},
	{layout: 0},
	{previousIslandX: 0},
	{previousIslandY: 0},
	{testText: 0},
	{aaTestString: 0},
	{testText3: 0},
	{testTimer: 0},
	{testTextLeaks: 0},
	{lastVersion: 0},
	{loadComplete: 0},
	{plume: 0},
	{plume1ID: 0},
	{plume1Name: 0},
	{plume1Cost: 0},
	{plume2ID: 0},
	{plume2Name: 0},
	{plume2Cost: 0},
	{plume3ID: 0},
	{plume3Name: 0},
	{plume3Cost: 0},
	{plume4ID: 0},
	{plume4Name: 0},
	{plume4Cost: 0},
	{plumeRandomPosition: 0},
	{posScrollMarkerLeftXForAds: 0},
	{posScrollMarkerLeftXForCoins: 0},
	{posScrollMarkerLeftXForGems: 0},
	{scrollMarkerShopStartX: 0},
	{skin: 0},
	{skinNumber: 0},
	{skinVarForSave: 0},
	{timerTouchShop: 0},
	{triggerTouchShop: 0},
	{loadGameStart: 0},
	{loadArrayLevels: 0},
	{loadPlayerFields: 0},
	{arrayPlumes: 0},
	{arraySkins: 0},
	{arrayLevels: 0},
	{recordFactor: 0}
];

self.InstanceType = {
	Button: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	WindowLevelComplete: class extends self.IWorldInstance {},
	TitleGame: class extends self.ISpriteInstance {},
	Bar: class extends self.ISpriteInstance {},
	ButtonLevelSelect: class extends self.ISpriteInstance {},
	WindowQuit: class extends self.IWorldInstance {},
	RibbonSimple: class extends self.IWorldInstance {},
	RibbonGala: class extends self.IWorldInstance {},
	WindowSettings: class extends self.IWorldInstance {},
	TextGems: class extends self.ISpriteFontInstance {},
	TextBarLevel: class extends self.ISpriteFontInstance {},
	TextTime: class extends self.ISpriteFontInstance {},
	TextTest: class extends self.ITextInstance {},
	TextTest2: class extends self.ITextInstance {},
	TextLevelComplete: class extends self.ITextInstance {},
	TextLevelSelectTime: class extends self.ITextInstance {},
	TextWindowQuit: class extends self.ITextInstance {},
	TextConnect: class extends self.ITextInstance {},
	TextAllHighScores: class extends self.ITextInstance {},
	TextButton: class extends self.ITextInstance {},
	WindowAllHighScores: class extends self.IWorldInstance {},
	TextSmallHighScores: class extends self.ITextInstance {},
	TextInput: class extends self.ITextInputInstance {},
	TextNotification: class extends self.ITextInstance {},
	TextHello: class extends self.ITextInstance {},
	TextPrompt: class extends self.ITextInstance {},
	WindowInputPlayerName: class extends self.IWorldInstance {},
	TextWindowTitle: class extends self.ITextInstance {},
	TextLevelSelectNumber: class extends self.ITextInstance {},
	ScrollMarkerLevelLeft: class extends self.ITiledBackgroundInstance {},
	ScrollMarkerLevelRight: class extends self.ITiledBackgroundInstance {},
	PromptButtonUp: class extends self.ISpriteInstance {},
	TextLevelNumber: class extends self.ITextInstance {},
	TextLevelStartPrompt: class extends self.ITextInstance {},
	TextLogo: class extends self.ITextInstance {},
	TextProgressbar: class extends self.ITextInstance {},
	FloorPhysicInvisible: class extends self.ITiledBackgroundInstance {},
	PlatformInvisible: class extends self.ITiledBackgroundInstance {},
	LevelBorder: class extends self.ISpriteInstance {},
	PromptArrowJump: class extends self.ISpriteInstance {},
	TextRank: class extends self.ITextInstance {},
	Lock: class extends self.ISpriteInstance {},
	WindowHighScores: class extends self.IWorldInstance {},
	WindowLevelSelect1: class extends self.IWorldInstance {},
	Icon: class extends self.ISpriteInstance {},
	WindowLevelSelect2: class extends self.IWorldInstance {},
	TextBar: class extends self.ITextInstance {},
	TextTitle: class extends self.ITextInstance {},
	Hearts: class extends self.ITiledBackgroundInstance {},
	ScrollMarkerHighScoresBottom: class extends self.ITiledBackgroundInstance {},
	ScrollMarkerHighScoresTop: class extends self.ITiledBackgroundInstance {},
	ScrollMarkerShopLeft: class extends self.ITiledBackgroundInstance {},
	ScrollMarkerShopRight: class extends self.ITiledBackgroundInstance {},
	TextPromptStart: class extends self.ITextInstance {},
	WindowCoins: class extends self.IWorldInstance {},
	WindowGems: class extends self.IWorldInstance {},
	WindowPlumes: class extends self.IWorldInstance {},
	WindowSkins: class extends self.IWorldInstance {},
	MaskBottom: class extends self.ITiledBackgroundInstance {},
	MaskTop: class extends self.ITiledBackgroundInstance {},
	WindowLevelSelect3: class extends self.IWorldInstance {},
	TextStarterPack: class extends self.ITextInstance {},
	WindowLevelSelect4: class extends self.IWorldInstance {},
	TextVersion: class extends self.ITextInstance {},
	PanelShare: class extends self.IWorldInstance {},
	TextPanelTitle: class extends self.ITextInstance {},
	Bat: class extends self.ISpriteInstance {},
	Bg: class extends self.ISpriteInstance {},
	PlayerBase: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	EndLevel: class extends self.ISpriteInstance {},
	EndPoint: class extends self.ISpriteInstance {},
	Coin: class extends self.ISpriteInstance {},
	Mushroom: class extends self.ISpriteInstance {},
	ParticleEffect: class extends self.ISpriteInstance {},
	Shadow: class extends self.ISpriteInstance {},
	Spikes: class extends self.ISpriteInstance {},
	StartPoint: class extends self.ISpriteInstance {},
	TiledBackground1: class extends self.ITiledBackgroundInstance {},
	TriggerReversal: class extends self.ISpriteInstance {},
	TriggerJump: class extends self.ISpriteInstance {},
	Water: class extends self.ITiledBackgroundInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	ArrayLevelsResult: class extends self.IArrayInstance {},
	BossMushroom: class extends self.ISpriteInstance {},
	Wall: class extends self.ISpriteInstance {},
	FlyingFox: class extends self.ISpriteInstance {},
	BossFlyingFox: class extends self.ISpriteInstance {},
	Ceiling: class extends self.ISpriteInstance {},
	EasterEgg: class extends self.ISpriteInstance {},
	Sand: class extends self.ITiledBackgroundInstance {},
	TilemapEasterEggs: class extends self.ITilemapInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Gem: class extends self.ISpriteInstance {},
	CoinPrize: class extends self.ISpriteInstance {},
	WallPlatformerInvisible: class extends self.ITiledBackgroundInstance {},
	PlayerTest: class extends self.ISpriteInstance {},
	Plume: class extends self.ISpriteInstance {},
	Ice: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Penguin: class extends self.ISpriteInstance {},
	Fish: class extends self.ISpriteInstance {},
	ArrayPlumes: class extends self.IArrayInstance {},
	ArraySkins: class extends self.IArrayInstance {},
	IceFloe: class extends self.ISpriteInstance {},
	BossFish: class extends self.ISpriteInstance {},
	Lava: class extends self.ISpriteInstance {},
	Periscope: class extends self.ISpriteInstance {},
	Fireball: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Dwarf: class extends self.ISpriteInstance {},
	IslandLava: class extends self.ISpriteInstance {},
	SpikesFalling: class extends self.ISpriteInstance {},
	SpikesFallingPiece: class extends self.ISpriteInstance {},
	IslandFalling: class extends self.ITiledBackgroundInstance {},
	BossDwarf: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	XML: class extends self.IInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	GamePush: class extends C3.Plugins.Eponesh_GameScore.Instance {}
}