const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.AJAX,
		C3.Plugins.Browser,
		C3.Plugins.Dictionary,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Behaviors.Pin,
		C3.Plugins.Particles,
		C3.Behaviors.Physics,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Plugins.NinePatch,
		C3.Plugins.Tilemap,
		C3.Behaviors.Tween,
		C3.Plugins.Spritefont2,
		C3.Plugins.Eponesh_GameScore,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Browser.Acts.LoadStyleSheet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetFontFace,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Spritefont2.Exps.LayerNumber,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Spritefont2.Acts.SetSize,
		C3.Plugins.Spritefont2.Exps.Width,
		C3.Plugins.Spritefont2.Exps.Height,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.Spritefont2.Exps.ColorValue,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Spritefont2.Exps.CharacterScale,
		C3.Plugins.Spritefont2.Exps.UID,
		C3.ScriptsInEvents.Translations_Event14_Act11,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Dictionary.Acts.Clear,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.Depth,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Arr.Cnds.CompareXYZ,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsPreloaderAvailable,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowPreloader,
		C3.Plugins.Eponesh_GameScore.Exps.Language,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.Eponesh_GameScore.Acts.ChangeLanguage,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPause,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Eponesh_GameScore.Cnds.OnResume,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Eponesh_GameScore.Acts.AdsCloseSticky,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsShare,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Eponesh_GameScore.Cnds.PlatformType,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Eponesh_GameScore.Cnds.IsGamesCollectionsAvailable,
		C3.Plugins.Eponesh_GameScore.Acts.GamesCollectionsOpen,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsStickyAvailable,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowSticky,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Tilemap.Acts.EraseTileRange,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Pin.Cnds.IsPinned,
		C3.Behaviors.Physics.Cnds.IsSleeping,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Rotate.Exps.Speed,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Browser.Acts.Vibrate,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle
	];
};
self.C3_JsPropNameTable = [
	{code: 0},
	{level: 0},
	{home_text: 0},
	{tpleyt: 0},
	{Text: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{AJAX: 0},
	{Browser: 0},
	{StorageData: 0},
	{stringsArray: 0},
	{stringsDictionary: 0},
	{Touch: 0},
	{btnex: 0},
	{BtnMusic: 0},
	{BtnSound: 0},
	{adsreward: 0},
	{Поворот: 0},
	{Sp1: 0},
	{Sp2: 0},
	{Sp3: 0},
	{Спрайт4: 0},
	{BtnVibro: 0},
	{Dk: 0},
	{Pin: 0},
	{sprite10: 0},
	{winsre: 0},
	{Спрайт7: 0},
	{resets: 0},
	{Sprite2: 0},
	{fade: 0},
	{menuhome: 0},
	{tempFlag: 0},
	{Rotate: 0},
	{Loading2: 0},
	{btnRestart2: 0},
	{btnRestart3: 0},
	{txtlvlnum: 0},
	{prtclWin: 0},
	{Physics: 0},
	{pinDragColls: 0},
	{Fade: 0},
	{Sprite: 0},
	{ids: 0},
	{pinDestrLine: 0},
	{Bullet: 0},
	{pinDestrTouch: 0},
	{movTogl: 0},
	{min: 0},
	{max: 0},
	{pinMove: 0},
	{touchPos: 0},
	{pinMovWay: 0},
	{pinRotate: 0},
	{rock: 0},
	{destrPoint: 0},
	{Tilemap: 0},
	{sandTexture: 0},
	{waters: 0},
	{fish: 0},
	{waters2: 0},
	{lava: 0},
	{prtclSteam: 0},
	{shark: 0},
	{kapliCount: 0},
	{kapliMax: 0},
	{lavaCount: 0},
	{lavaMax: 0},
	{fishCounter: 0},
	{enemyCounter: 0},
	{bomb: 0},
	{lavaPos: 0},
	{waterPos: 0},
	{jan: 0},
	{crab: 0},
	{id: 0},
	{Tween: 0},
	{Button: 0},
	{bgs: 0},
	{collTiles: 0},
	{collTriangl: 0},
	{SpriteFont_RU: 0},
	{SpriteFont_EN: 0},
	{sfxColls: 0},
	{rus3: 0},
	{rus2: 0},
	{rus1: 0},
	{GamePush: 0},
	{vk: 0},
	{vksoc: 0},
	{PlayBTN: 0},
	{GameBackground: 0},
	{WellDoneUI: 0},
	{Girar: 0},
	{LevelCompleteSpin: 0},
	{TapBTN: 0},
	{LevelCompleteParticles: 0},
	{Seno: 0},
	{LevelCompleteStar: 0},
	{LevelCompleteStar2: 0},
	{WellDoneUI2: 0},
	{TapBTN2: 0},
	{MoreGamesBTN: 0},
	{tovar: 0},
	{LoadingAnimation2: 0},
	{VkBTN: 0},
	{LangTexts: 0},
	{LangSprites: 0},
	{LangSpritefonts: 0},
	{pinsLine: 0},
	{pinsHead: 0},
	{famWater: 0},
	{famOutScrDestr: 0},
	{famLava: 0},
	{lang: 0},
	{tempString: 0},
	{sourceUID: 0},
	{destUID: 0},
	{languageIndex: 0},
	{thislvl_gp: 0},
	{thislvl: 0},
	{music: 0},
	{sound: 0},
	{vibro: 0},
	{rusalka: 0},
	{SoundName: 0},
	{Vol: 0},
	{radius: 0},
	{dx: 0}
];

self.InstanceType = {
	level: class extends self.ITextInstance {},
	home_text: class extends self.ITextInstance {},
	tpleyt: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	StorageData: class extends self.IDictionaryInstance {},
	stringsArray: class extends self.IArrayInstance {},
	stringsDictionary: class extends self.IDictionaryInstance {},
	Touch: class extends self.IInstance {},
	btnex: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	adsreward: class extends self.ISpriteInstance {},
	Sp1: class extends self.ISpriteInstance {},
	Sp2: class extends self.ISpriteInstance {},
	Sp3: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	BtnVibro: class extends self.ISpriteInstance {},
	Dk: class extends self.ISpriteInstance {},
	Pin: class extends self.ISpriteInstance {},
	sprite10: class extends self.ISpriteInstance {},
	winsre: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	resets: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	fade: class extends self.ISpriteInstance {},
	menuhome: class extends self.ISpriteInstance {},
	tempFlag: class extends self.ISpriteInstance {},
	Loading2: class extends self.ISpriteInstance {},
	btnRestart2: class extends self.ISpriteInstance {},
	btnRestart3: class extends self.ISpriteInstance {},
	txtlvlnum: class extends self.ITextInstance {},
	prtclWin: class extends self.IParticlesInstance {},
	pinDragColls: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	pinDestrLine: class extends self.ITiledBackgroundInstance {},
	pinDestrTouch: class extends self.ISpriteInstance {},
	pinMove: class extends self.ISpriteInstance {},
	touchPos: class extends self.ISpriteInstance {},
	pinMovWay: class extends self.IWorldInstance {},
	pinRotate: class extends self.ISpriteInstance {},
	rock: class extends self.ISpriteInstance {},
	destrPoint: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	sandTexture: class extends self.ITiledBackgroundInstance {},
	waters: class extends self.ISpriteInstance {},
	fish: class extends self.ISpriteInstance {},
	waters2: class extends self.ISpriteInstance {},
	lava: class extends self.ISpriteInstance {},
	prtclSteam: class extends self.IParticlesInstance {},
	shark: class extends self.ISpriteInstance {},
	fishCounter: class extends self.ISpriteInstance {},
	enemyCounter: class extends self.ISpriteInstance {},
	bomb: class extends self.ISpriteInstance {},
	lavaPos: class extends self.ISpriteInstance {},
	waterPos: class extends self.ISpriteInstance {},
	crab: class extends self.ISpriteInstance {},
	Button: class extends self.IWorldInstance {},
	bgs: class extends self.ISpriteInstance {},
	collTiles: class extends self.ITiledBackgroundInstance {},
	collTriangl: class extends self.ISpriteInstance {},
	SpriteFont_RU: class extends self.ISpriteFontInstance {},
	SpriteFont_EN: class extends self.ISpriteFontInstance {},
	sfxColls: class extends self.ISpriteInstance {},
	rus3: class extends self.ISpriteInstance {},
	rus2: class extends self.ISpriteInstance {},
	rus1: class extends self.ISpriteInstance {},
	GamePush: class extends self.C3.Plugins.Eponesh_GameScore.Instance {},
	vk: class extends self.ISpriteInstance {},
	vksoc: class extends self.ITextInstance {},
	PlayBTN: class extends self.ISpriteInstance {},
	GameBackground: class extends self.ITiledBackgroundInstance {},
	WellDoneUI: class extends self.ISpriteInstance {},
	LevelCompleteSpin: class extends self.ISpriteInstance {},
	TapBTN: class extends self.ISpriteInstance {},
	LevelCompleteParticles: class extends self.IParticlesInstance {},
	LevelCompleteStar: class extends self.ISpriteInstance {},
	LevelCompleteStar2: class extends self.ISpriteInstance {},
	WellDoneUI2: class extends self.ISpriteInstance {},
	TapBTN2: class extends self.ISpriteInstance {},
	MoreGamesBTN: class extends self.ISpriteInstance {},
	LoadingAnimation2: class extends self.ISpriteInstance {},
	VkBTN: class extends self.ISpriteInstance {},
	LangTexts: class extends self.ITextInstance {},
	LangSprites: class extends self.ISpriteInstance {},
	LangSpritefonts: class extends self.ISpriteFontInstance {},
	pinsLine: class extends self.ITiledBackgroundInstance {},
	pinsHead: class extends self.ISpriteInstance {},
	famWater: class extends self.ISpriteInstance {},
	famOutScrDestr: class extends self.ISpriteInstance {},
	famLava: class extends self.ISpriteInstance {}
}