const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Tween,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Behaviors.Pin,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Exps.AnimationFrameCount
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Physics: 0},
	{Tilemap: 0},
	{attack: 0},
	{spawn: 0},
	{davuk_var: 0},
	{Platform: 0},
	{Tween: 0},
	{BoundToLayout: 0},
	{player: 0},
	{Keyboard: 0},
	{player2: 0},
	{p1_attack: 0},
	{p2_attack: 0},
	{id: 0},
	{spawn_point: 0},
	{tnt: 0},
	{tnt_boom: 0},
	{tnt_patlama: 0},
	{TiledBackground: 0},
	{Game_name_text: 0},
	{Sine: 0},
	{buttons: 0},
	{PlatformInfo: 0},
	{Touch: 0},
	{Mouse: 0},
	{skin_oge: 0},
	{skin_degistirme_ok: 0},
	{Pin: 0},
	{p1_skin: 0},
	{p2_skin: 0},
	{score_tabl: 0},
	{time_text: 0},
	{p1_score_text: 0},
	{p2_score_text: 0},
	{winner_card: 0},
	{winner_text: 0},
	{mobile_buttona: 0},
	{cit: 0},
	{yon: 0},
	{davuk: 0},
	{healt: 0},
	{davuk_platform: 0},
	{platform_direk: 0},
	{davuk_collision: 0},
	{block_healt_text: 0},
	{trigger: 0},
	{davuk2: 0},
	{bulut2: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{WeeGooSDK: 0},
	{second: 0},
	{p1_score: 0},
	{p2_score: 0},
	{game_stop: 0}
];

self.InstanceType = {
	Tilemap: class extends self.ITilemapInstance {},
	player: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	player2: class extends self.ISpriteInstance {},
	p1_attack: class extends self.ISpriteInstance {},
	p2_attack: class extends self.ISpriteInstance {},
	spawn_point: class extends self.ISpriteInstance {},
	tnt: class extends self.ISpriteInstance {},
	tnt_boom: class extends self.IParticlesInstance {},
	tnt_patlama: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Game_name_text: class extends self.ITextInstance {},
	buttons: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	skin_oge: class extends self.ISpriteInstance {},
	skin_degistirme_ok: class extends self.ISpriteInstance {},
	p1_skin: class extends self.ISpriteInstance {},
	p2_skin: class extends self.ISpriteInstance {},
	score_tabl: class extends self.ISpriteInstance {},
	time_text: class extends self.ITextInstance {},
	p1_score_text: class extends self.ITextInstance {},
	p2_score_text: class extends self.ITextInstance {},
	winner_card: class extends self.ISpriteInstance {},
	winner_text: class extends self.ITextInstance {},
	mobile_buttona: class extends self.ISpriteInstance {},
	cit: class extends self.ISpriteInstance {},
	davuk: class extends self.ISpriteInstance {},
	davuk_platform: class extends self.ISpriteInstance {},
	platform_direk: class extends self.ISpriteInstance {},
	davuk_collision: class extends self.ISpriteInstance {},
	block_healt_text: class extends self.ITextInstance {},
	trigger: class extends self.ISpriteInstance {},
	davuk2: class extends self.ISpriteInstance {},
	bulut2: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {}
}