const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.jumpthru,
		C3.Behaviors.scrollto,
		C3.Plugins.Touch,
		C3.Behaviors.Platform,
		C3.Behaviors.wrap,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.Particles,
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.ppstudio_ga4,
		C3.Plugins.PlatformInfo,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Acts.LoadFromJsonString,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Sprite.Exps.AsJSON,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.ppstudio_ga4.Acts.GASendEvent,
		C3.Plugins.ppstudio_ga4.Acts.InitGA,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Browser.Acts.RequestFullScreen
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{fon: 0},
	{Solid: 0},
	{Jumpthru: 0},
	{Sprite4: 0},
	{ScrollTo: 0},
	{Sprite5: 0},
	{Leftg: 0},
	{Rightg: 0},
	{up: 0},
	{pausa: 0},
	{Touch: 0},
	{id: 0},
	{mir: 0},
	{anim: 0},
	{Platform: 0},
	{Wrap: 0},
	{gg: 0},
	{Sprite11: 0},
	{Sine: 0},
	{Sine2: 0},
	{Sprite12: 0},
	{Fade: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{timer: 0},
	{enemu: 0},
	{score: 0},
	{Array: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite9: 0},
	{Sprite8: 0},
	{Sprite10: 0},
	{music: 0},
	{sound: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{demo: 0},
	{go: 0},
	{Audio: 0},
	{GameResultsFont: 0},
	{StartGame: 0},
	{LastScoreFont: 0},
	{Particles: 0},
	{Keyboard: 0},
	{Sprite2: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{GA4: 0},
	{PlatformInfo: 0},
	{WeeGooSDK: 0},
	{Best: 0},
	{Musick: 0},
	{Saund: 0},
	{GG: 0},
	{Spawn: 0},
	{Score: 0},
	{Score2: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	fon: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Leftg: class extends self.ISpriteInstance {},
	Rightg: class extends self.ISpriteInstance {},
	up: class extends self.ISpriteInstance {},
	pausa: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	gg: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	enemu: class extends self.ISpriteInstance {},
	score: class extends self.ITextInstance {},
	Array: class extends self.IArrayInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	music: class extends self.ISpriteInstance {},
	sound: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	demo: class extends self.ISpriteInstance {},
	go: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	GameResultsFont: class extends self.ISpriteFontInstance {},
	StartGame: class extends self.ISpriteInstance {},
	LastScoreFont: class extends self.ISpriteFontInstance {},
	Particles: class extends self.IParticlesInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	GA4: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	WeeGooSDK: class extends self.IInstance {}
}