const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Plugins.Arr,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Behaviors.Physics,
		C3.Plugins.TiledBg,
		C3.Plugins.LocalStorage,
		C3.Behaviors.destroy,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.Browser,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetLayerBackground,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Text.Acts.ToggleBoolInstanceVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Text.Cnds.CompareOpacity,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgb,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.layoutheight,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Cnds.CompareOpacity,
		C3.Plugins.Spritefont2.Cnds.IsVisible,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward
	];
};
self.C3_JsPropNameTable = [
	{speedBall: 0},
	{previousColor: 0},
	{defeat: 0},
	{degreesROT: 0},
	{Fade: 0},
	{polygon: 0},
	{Touch: 0},
	{Solid: 0},
	{infoTEXT: 0},
	{Bullet: 0},
	{Wrap: 0},
	{color: 0},
	{opositiveColors: 0},
	{Sine: 0},
	{b_rr: 0},
	{Keyboard: 0},
	{Physics: 0},
	{b_start: 0},
	{bar: 0},
	{b_confg: 0},
	{pauseActive: 0},
	{b_pause: 0},
	{blackscreen: 0},
	{b_home: 0},
	{LocalStorage: 0},
	{DestroyOutsideLayout: 0},
	{AuxTEXT: 0},
	{Audio: 0},
	{logo: 0},
	{bgIns: 0},
	{start: 0},
	{sizeScale: 0},
	{r: 0},
	{bgop: 0},
	{op_title: 0},
	{disabled: 0},
	{op_autoRR: 0},
	{op_Music: 0},
	{op_Sounds: 0},
	{op_resetHS: 0},
	{op_level: 0},
	{op_Back: 0},
	{arrow: 0},
	{bg_main: 0},
	{progress: 0},
	{intro_: 0},
	{fadeIN: 0},
	{transition: 0},
	{fadeOUT: 0},
	{txt_touchtostart: 0},
	{b_moregames: 0},
	{Browser: 0},
	{colors: 0},
	{bgColor: 0},
	{TiledBackground: 0},
	{Text: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{pausebackground: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{WeeGooSDK: 0},
	{soundsON: 0},
	{musicON: 0},
	{bestScore: 0},
	{autoRR: 0},
	{score: 0},
	{angleTouch: 0},
	{level: 0},
	{p_color: 0},
	{load_ok: 0}
];

self.InstanceType = {
	polygon: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	infoTEXT: class extends self.ITextInstance {},
	color: class extends self.ISpriteInstance {},
	opositiveColors: class extends self.IArrayInstance {},
	b_rr: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	b_start: class extends self.ISpriteInstance {},
	bar: class extends self.ITiledBackgroundInstance {},
	b_confg: class extends self.ISpriteInstance {},
	b_pause: class extends self.ISpriteInstance {},
	blackscreen: class extends self.ITiledBackgroundInstance {},
	b_home: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	AuxTEXT: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	logo: class extends self.ISpriteInstance {},
	bgIns: class extends self.ITiledBackgroundInstance {},
	start: class extends self.ISpriteInstance {},
	r: class extends self.ISpriteInstance {},
	bgop: class extends self.ITiledBackgroundInstance {},
	op_title: class extends self.ITextInstance {},
	op_autoRR: class extends self.ITextInstance {},
	op_Music: class extends self.ITextInstance {},
	op_Sounds: class extends self.ITextInstance {},
	op_resetHS: class extends self.ITextInstance {},
	op_level: class extends self.ITextInstance {},
	op_Back: class extends self.ITextInstance {},
	arrow: class extends self.ISpriteInstance {},
	bg_main: class extends self.ITiledBackgroundInstance {},
	progress: class extends self.ISpriteInstance {},
	intro_: class extends self.ISpriteInstance {},
	fadeIN: class extends self.ITiledBackgroundInstance {},
	transition: class extends self.ITiledBackgroundInstance {},
	fadeOUT: class extends self.ITiledBackgroundInstance {},
	txt_touchtostart: class extends self.ISpriteFontInstance {},
	b_moregames: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	bgColor: class extends self.ITiledBackgroundInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	pausebackground: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {}
}