const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Physics,
		C3.Behaviors.Rotate,
		C3.Plugins.Touch,
		C3.Behaviors.Pin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Behaviors.Bullet,
		C3.Plugins.Function,
		C3.Plugins.ppstudio_ga4,
		C3.Plugins.WGSDK,
		C3.Plugins.PlatformInfo,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.MoveToTop,
		C3.Behaviors.Physics.Acts.ApplyImpulseToward,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.System.Exps.max,
		C3.Behaviors.Sin.Exps.Period,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.ppstudio_ga4.Acts.GAAddProperty,
		C3.Plugins.ppstudio_ga4.Acts.GASendEvent,
		C3.Plugins.Browser.Acts.ExecJs,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.ppstudio_ga4.Acts.InitGA,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward
	];
};
self.C3_JsPropNameTable = [
	{bg: 0},
	{Sine: 0},
	{goal: 0},
	{Physics: 0},
	{Rotate: 0},
	{ball: 0},
	{Touch: 0},
	{Pin: 0},
	{arrow: 0},
	{ground: 0},
	{shadow: 0},
	{Sprite2: 0},
	{ball1: 0},
	{ball2: 0},
	{ball3: 0},
	{Sprite3: 0},
	{SpriteFont: 0},
	{Sprite4: 0},
	{up: 0},
	{edge: 0},
	{Fade: 0},
	{scoreShow: 0},
	{Sprite: 0},
	{play: 0},
	{btnSound: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{txthighscore: 0},
	{txtscore: 0},
	{LocalStorage: 0},
	{Browser: 0},
	{Bullet: 0},
	{splash: 0},
	{btnBack: 0},
	{btnHome: 0},
	{ballshootArea: 0},
	{Function: 0},
	{payeh: 0},
	{payehHead: 0},
	{payehbody: 0},
	{box: 0},
	{GA4: 0},
	{WeeGooSDK: 0},
	{PlatformInfo: 0},
	{isgoal: 0},
	{Score: 0},
	{loseball: 0},
	{CanShoot: 0},
	{Reached: 0},
	{PayehSize: 0},
	{flagBox: 0},
	{CanSlow: 0},
	{shooted: 0},
	{toched: 0},
	{ver: 0},
	{Sound: 0},
	{HighScore: 0},
	{IsScreenRotate: 0}
];

self.InstanceType = {
	bg: class extends self.ISpriteInstance {},
	goal: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	arrow: class extends self.ISpriteInstance {},
	ground: class extends self.ISpriteInstance {},
	shadow: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	ball1: class extends self.ISpriteInstance {},
	ball2: class extends self.ISpriteInstance {},
	ball3: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	edge: class extends self.ISpriteInstance {},
	scoreShow: class extends self.ISpriteFontInstance {},
	Sprite: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	btnSound: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	txthighscore: class extends self.ISpriteFontInstance {},
	txtscore: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	splash: class extends self.ISpriteInstance {},
	btnBack: class extends self.ISpriteInstance {},
	btnHome: class extends self.ISpriteInstance {},
	ballshootArea: class extends self.ISpriteInstance {},
	Function: class extends self.IInstance {},
	payeh: class extends self.ISpriteInstance {},
	payehHead: class extends self.ISpriteInstance {},
	payehbody: class extends self.ISpriteInstance {},
	box: class extends self.ISpriteInstance {},
	GA4: class extends self.IInstance {},
	WeeGooSDK: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {}
}