const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.AJAX,
		C3.Plugins.Browser,
		C3.Plugins.Dictionary,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Plugins.Shape3D,
		C3.Behaviors.solid,
		C3.Plugins.Camera3D,
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Plugins.Spritefont2,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Plugins.Tilemap,
		C3.Behaviors.Pin,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsStickyAvailable,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowSticky,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Shape3D.Acts.SetZHeight,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Platform.Acts.SetDefaultControls,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetZElevation,
		C3.Plugins.Particles.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Particles.Acts.SetInitSize,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetGravityAngle,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Eponesh_GameScore.Acts.AdsCloseSticky,
		C3.Plugins.Browser.Acts.Vibrate,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Spritefont2.Cnds.CompareY,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Text.Cnds.CompareY,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPause,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Eponesh_GameScore.Cnds.OnResume,
		C3.Plugins.Browser.Acts.LoadStyleSheet,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Text.Acts.SetFontFace,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Spritefont2.Exps.LayerNumber,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Spritefont2.Acts.SetSize,
		C3.Plugins.Spritefont2.Exps.Width,
		C3.Plugins.Spritefont2.Exps.Height,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.Spritefont2.Exps.ColorValue,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Spritefont2.Exps.CharacterScale,
		C3.Plugins.Spritefont2.Exps.UID,
		C3.ScriptsInEvents.Translations_Event14_Act11,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Dictionary.Acts.Clear,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.Depth,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Arr.Cnds.CompareXYZ,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsPreloaderAvailable,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowPreloader,
		C3.Plugins.Eponesh_GameScore.Exps.Language,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.Eponesh_GameScore.Acts.ChangeLanguage,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Browser.Exps.Language,
		C3.Plugins.Text.Acts.Destroy,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsShare,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Eponesh_GameScore.Cnds.PlatformType,
		C3.Plugins.Eponesh_GameScore.Cnds.IsGamesCollectionsAvailable,
		C3.Plugins.Eponesh_GameScore.Acts.GamesCollectionsOpen,
		C3.Plugins.Eponesh_GameScore.Cnds.AchievementsIsUnlocked,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Eponesh_GameScore.Acts.AchievementsUnlock
	];
};
self.C3_JsPropNameTable = [
	{tempText1: 0},
	{money: 0},
	{code: 0},
	{level: 0},
	{home_text: 0},
	{tpleyt: 0},
	{prizz: 0},
	{spintxt: 0},
	{spintxt2: 0},
	{Text: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{AJAX: 0},
	{Browser: 0},
	{StorageData: 0},
	{stringsArray: 0},
	{stringsDictionary: 0},
	{Touch: 0},
	{Solid: 0},
	{"3DShape": 0},
	{"3DCamera": 0},
	{Array_price: 0},
	{Array_save: 0},
	{Keyboard: 0},
	{btnex: 0},
	{BtnMusic: 0},
	{BtnSound: 0},
	{btnRestart: 0},
	{adsreward: 0},
	{Поворот: 0},
	{Sp1: 0},
	{Sp2: 0},
	{Sp3: 0},
	{spin: 0},
	{spin2: 0},
	{sprite4: 0},
	{BtnVibro: 0},
	{Dk: 0},
	{Pin: 0},
	{sprite10: 0},
	{Tween: 0},
	{topcoin: 0},
	{winsre: 0},
	{Спрайт7: 0},
	{resets: 0},
	{Black: 0},
	{fade: 0},
	{menuhome: 0},
	{menuright: 0},
	{tempFlag: 0},
	{a: 0},
	{Wheel: 0},
	{Rotate: 0},
	{Loading2: 0},
	{Синусоид: 0},
	{moneta2: 0},
	{SuccessPrizeCoin_Effect: 0},
	{Prizecoin: 0},
	{video: 0},
	{Particles: 0},
	{background: 0},
	{SpriteFont_RU: 0},
	{SpriteFont_EN: 0},
	{Sine: 0},
	{hand: 0},
	{ScrollTo: 0},
	{cam: 0},
	{price: 0},
	{Var: 0},
	{Board: 0},
	{X_SUM: 0},
	{Y_SUM: 0},
	{PositionX: 0},
	{PositionY: 0},
	{GO: 0},
	{Start_Width: 0},
	{Start_Height: 0},
	{Platform: 0},
	{Balls: 0},
	{land: 0},
	{Tilemap: 0},
	{LEVELS: 0},
	{score: 0},
	{modes: 0},
	{TextFont: 0},
	{Star: 0},
	{Smoke: 0},
	{setting: 0},
	{Num: 0},
	{S: 0},
	{p_y: 0},
	{p_x: 0},
	{Mask: 0},
	{Home: 0},
	{GamePush: 0},
	{vk: 0},
	{vksoc: 0},
	{Particles2: 0},
	{winParticle: 0},
	{winParticleSprite: 0},
	{MoreGamesBTN: 0},
	{Home2: 0},
	{TapBTN: 0},
	{Girar: 0},
	{LevelCompleteSpin: 0},
	{WellDoneUI: 0},
	{Seno: 0},
	{LevelCompleteStar: 0},
	{LevelCompleteParticles: 0},
	{VkBTN: 0},
	{adfon: 0},
	{Синусоида: 0},
	{Balls2: 0},
	{Спрайт: 0},
	{LangTexts: 0},
	{LangSprites: 0},
	{head: 0},
	{LangSpritefonts: 0},
	{Tile: 0},
	{ScreenHeightValue: 0},
	{ScreenWidthValue: 0},
	{lang: 0},
	{tempString: 0},
	{sourceUID: 0},
	{destUID: 0},
	{languageIndex: 0},
	{sectorCount: 0},
	{prizes: 0},
	{winningSector: 0},
	{twist_five: 0},
	{prizload: 0},
	{thislvl: 0},
	{music: 0},
	{sound: 0},
	{vibro: 0},
	{X1: 0},
	{X2: 0},
	{Y1: 0},
	{Y2: 0},
	{cube_end: 0},
	{WIN: 0},
	{VOLUME: 0},
	{STARS: 0},
	{startTime: 0},
	{prog: 0},
	{thislvl_gp: 0},
	{cube_end_gp: 0},
	{ball_gp: 0},
	{SoundName: 0},
	{Vol: 0},
	{ball: 0}
];

self.InstanceType = {
	tempText1: class extends self.ITextInstance {},
	money: class extends self.ITextInstance {},
	level: class extends self.ITextInstance {},
	home_text: class extends self.ITextInstance {},
	tpleyt: class extends self.ITextInstance {},
	prizz: class extends self.ITextInstance {},
	spintxt: class extends self.ITextInstance {},
	spintxt2: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	StorageData: class extends self.IDictionaryInstance {},
	stringsArray: class extends self.IArrayInstance {},
	stringsDictionary: class extends self.IDictionaryInstance {},
	Touch: class extends self.IInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	_3DCamera: class extends self.IInstance {},
	Array_price: class extends self.IArrayInstance {},
	Array_save: class extends self.IArrayInstance {},
	Keyboard: class extends self.IInstance {},
	btnex: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	btnRestart: class extends self.ISpriteInstance {},
	adsreward: class extends self.ISpriteInstance {},
	Sp1: class extends self.ISpriteInstance {},
	Sp2: class extends self.ISpriteInstance {},
	Sp3: class extends self.ISpriteInstance {},
	spin: class extends self.ISpriteInstance {},
	spin2: class extends self.ISpriteInstance {},
	sprite4: class extends self.ISpriteInstance {},
	BtnVibro: class extends self.ISpriteInstance {},
	Dk: class extends self.ISpriteInstance {},
	Pin: class extends self.ISpriteInstance {},
	sprite10: class extends self.ISpriteInstance {},
	topcoin: class extends self.ISpriteInstance {},
	winsre: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	resets: class extends self.ISpriteInstance {},
	Black: class extends self.ITiledBackgroundInstance {},
	fade: class extends self.ISpriteInstance {},
	menuhome: class extends self.ISpriteInstance {},
	menuright: class extends self.ISpriteInstance {},
	tempFlag: class extends self.ISpriteInstance {},
	Wheel: class extends self.ISpriteInstance {},
	Loading2: class extends self.ISpriteInstance {},
	moneta2: class extends self.ISpriteInstance {},
	Prizecoin: class extends self.ISpriteInstance {},
	video: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	background: class extends self.ISpriteInstance {},
	SpriteFont_RU: class extends self.ISpriteFontInstance {},
	SpriteFont_EN: class extends self.ISpriteFontInstance {},
	hand: class extends self.ISpriteInstance {},
	cam: class extends self.ISpriteInstance {},
	Board: class extends self.ISpriteInstance {},
	Balls: class extends self.ISpriteInstance {},
	land: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	TextFont: class extends self.ISpriteFontInstance {},
	Star: class extends self.ISpriteInstance {},
	Smoke: class extends self.IParticlesInstance {},
	setting: class extends self.ISpriteInstance {},
	S: class extends self.ISpriteInstance {},
	p_y: class extends self.ITextInstance {},
	p_x: class extends self.ITextInstance {},
	Mask: class extends self.ITiledBackgroundInstance {},
	Home: class extends self.ISpriteInstance {},
	GamePush: class extends self.C3.Plugins.Eponesh_GameScore.Instance {},
	vk: class extends self.ISpriteInstance {},
	vksoc: class extends self.ITextInstance {},
	Particles2: class extends self.IParticlesInstance {},
	winParticle: class extends self.IParticlesInstance {},
	winParticleSprite: class extends self.ISpriteInstance {},
	MoreGamesBTN: class extends self.ISpriteInstance {},
	Home2: class extends self.ISpriteInstance {},
	TapBTN: class extends self.ISpriteInstance {},
	LevelCompleteSpin: class extends self.ISpriteInstance {},
	WellDoneUI: class extends self.ISpriteInstance {},
	LevelCompleteStar: class extends self.ISpriteInstance {},
	LevelCompleteParticles: class extends self.IParticlesInstance {},
	VkBTN: class extends self.ISpriteInstance {},
	adfon: class extends self.ISpriteInstance {},
	Balls2: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	LangTexts: class extends self.ITextInstance {},
	LangSprites: class extends self.ISpriteInstance {},
	head: class extends self.ISpriteInstance {},
	LangSpritefonts: class extends self.ISpriteFontInstance {},
	Tile: class extends self.ITilemapInstance {}
}