const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Button,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Plugins.Arr,
		C3.Plugins.Json,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.TiledBg,
		C3.Plugins.TextBox,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.AJAX,
		C3.Plugins.LocalStorage,
		C3.Plugins.SVGPicture,
		C3.Behaviors.MoveTo,
		C3.Plugins.NinePatch,
		C3.Plugins.Audio,
		C3.Plugins.SpellSync_Core,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.AddChild,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetLayerScroll,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Exps.min,
		C3.Plugins.NinePatch.Cnds.OnCreated,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.System.Exps.max,
		C3.Plugins.SpellSync_Core.Acts.GameplayStop,
		C3.Plugins.Json.Acts.SetValue,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Exps.layerscrolly,
		C3.Plugins.NinePatch.Exps.LayerName,
		C3.Plugins.NinePatch.Acts.MoveToLayer,
		C3.Plugins.Spritefont2.Acts.MoveToLayer,
		C3.Plugins.Json.Acts.PushValue,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Json.Exps.GetAsCompactString,
		C3.ScriptsInEvents.Gamesheet_Event318_Act2,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.SpellSync_Core.Acts.GameplayStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Spritefont2.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.Spritefont2.Exps.TextWidth,
		C3.Plugins.Spritefont2.Exps.TextHeight,
		C3.Plugins.Spritefont2.Acts.MoveToTop,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Json.Acts.SubtractFrom,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.ScriptsInEvents.Gamesheet_Event472_Act3,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Sprite.Acts.SetX,
		C3.ScriptsInEvents.Gamesheet_Event497_Act3,
		C3.ScriptsInEvents.Gamesheet_Event498_Act3,
		C3.ScriptsInEvents.Gamesheet_Event500_Act5,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.TextBox.Cnds.CompareInstanceVar,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.TextBox.Acts.SetInstanceVar,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Plugins.Json.Acts.SetArray,
		C3.Plugins.Json.Acts.SetObject,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.Arr.Acts.SplitString,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.ScriptsInEvents.Generalsheet_Event47_Act1,
		C3.Plugins.SVGPicture.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.SetPosToObject,
		C3.Plugins.SVGPicture.Acts.SetInstanceVar,
		C3.Plugins.SVGPicture.Acts.SetImageByName,
		C3.Plugins.SVGPicture.Acts.SetSize,
		C3.Plugins.SVGPicture.Exps.UID,
		C3.Plugins.SVGPicture.Cnds.PickByUID,
		C3.Plugins.SVGPicture.Exps.X,
		C3.Plugins.SVGPicture.Exps.Y,
		C3.Plugins.SVGPicture.Exps.Width,
		C3.Plugins.SVGPicture.Exps.Height,
		C3.Plugins.SVGPicture.Acts.SetDefaultColor,
		C3.Plugins.SVGPicture.Acts.SetOpacity,
		C3.Plugins.SVGPicture.Acts.MoveToBottom,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.canvastolayery,
		C3.Plugins.System.Exps.layertocanvasx,
		C3.Plugins.System.Exps.layertocanvasy,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Behaviors.MoveTo.Exps.Speed,
		C3.Behaviors.MoveTo.Cnds.CompareSpeed,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.SpellSync_Core.Acts.AdsShowPreloader,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemRemoved,
		C3.Plugins.SpellSync_Core.Acts.AdsShowFullscreen,
		C3.Plugins.SpellSync_Core.Acts.AdsShowRewarded,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.SpellSync_Core.Cnds.OnAdsRewardedReward,
		C3.Plugins.SpellSync_Core.Cnds.OnPause,
		C3.Plugins.SpellSync_Core.Cnds.OnResume
	];
};
self.C3_JsPropNameTable = [
	{StartW: 0},
	{StartH: 0},
	{Clickable: 0},
	{BtnClose: 0},
	{BtnContinue: 0},
	{BtnCreateBoard: 0},
	{BtnExit: 0},
	{BtnGenerate: 0},
	{BtnGoLevel: 0},
	{Index: 0},
	{BtnLevel: 0},
	{BtnMusic: 0},
	{BtnReset: 0},
	{BtnRestart: 0},
	{BtnSettings: 0},
	{BtnSFX: 0},
	{BtnBooster: 0},
	{BtnBuyLevels: 0},
	{BtnResume: 0},
	{BtnWatchAd: 0},
	{BtnAdClose: 0},
	{FreeBooster: 0},
	{BtnAdX2: 0},
	{TxtBtnLevels: 0},
	{TxtLabel: 0},
	{TxtLevelInPopup: 0},
	{TxtLoading: 0},
	{TxtMoves: 0},
	{TxtMovesInPopup: 0},
	{TxtTarget: 0},
	{TxtVersion: 0},
	{TxtLevel: 0},
	{TxtCoins: 0},
	{TxtBoosterCount: 0},
	{Tween: 0},
	{TxtBoosterDescription: 0},
	{TxtBoosterDescription2: 0},
	{TxtTut: 0},
	{TxtBuyLevelsPopup: 0},
	{TxtBtnBuyLevels: 0},
	{TxtBuyLevelsPopupTitle: 0},
	{TxtLevelUnavailablePopupTitle2: 0},
	{TxtPaused: 0},
	{TxtBtnWatchAdUnlockLevels: 0},
	{TxtLoading2: 0},
	{TxtReward: 0},
	{TxtBtnWatchAd: 0},
	{TxtWatchAdCoins: 0},
	{Time: 0},
	{Timer: 0},
	{TxtAd: 0},
	{TxtNextReward: 0},
	{Array: 0},
	{ArrayColSpot: 0},
	{ArrayColSpotEnd: 0},
	{ArrayDotType: 0},
	{JSON_Config: 0},
	{JSON_Creator: 0},
	{JSON_Levels: 0},
	{JSON_LS: 0},
	{JSON_TutLevel: 0},
	{xx: 0},
	{yy: 0},
	{Filled: 0},
	{Del: 0},
	{isWall: 0},
	{HasWater: 0},
	{HasGlass: 0},
	{Picked: 0},
	{HasBox: 0},
	{Spot: 0},
	{PosFixer: 0},
	{ColorIndex: 0},
	{SelectedIndex: 0},
	{BoosterMode: 0},
	{StartX: 0},
	{StartY: 0},
	{Shuffled: 0},
	{TutSelect: 0},
	{TutIndex: 0},
	{Dot: 0},
	{Keyboard: 0},
	{Touch: 0},
	{Browser: 0},
	{ColorSprite: 0},
	{Line: 0},
	{DotCircle: 0},
	{Wall: 0},
	{Water: 0},
	{Toucher: 0},
	{DY: 0},
	{Started: 0},
	{Cam: 0},
	{TiledBackground: 0},
	{Used: 0},
	{ForceUse: 0},
	{CreatorItems: 0},
	{Type: 0},
	{TextInput: 0},
	{Sine: 0},
	{Selector: 0},
	{Rnd: 0},
	{ItemOnBoard: 0},
	{Mouse: 0},
	{Text: 0},
	{TargetsPosFixer: 0},
	{Target: 0},
	{Progress: 0},
	{Done: 0},
	{Tick: 0},
	{Tick2: 0},
	{TextInputResult: 0},
	{AJAX: 0},
	{LocalStorage: 0},
	{SVGPicture: 0},
	{SVGPicture2: 0},
	{ScrollY: 0},
	{Bg: 0},
	{SpdReduceRate: 0},
	{MaxSpd: 0},
	{MoveTo: 0},
	{Swiper: 0},
	{LevelsLine: 0},
	{LevelsPopup: 0},
	{BlackBg: 0},
	{Glass: 0},
	{Box: 0},
	{TargetsBg: 0},
	{MovesBg: 0},
	{PausePopup: 0},
	{Audio: 0},
	{Title: 0},
	{CoinsBg: 0},
	{LevelDonePopup: 0},
	{PopupWhiteBox: 0},
	{LosePopup: 0},
	{BoosterCountBg: 0},
	{DescriptionBg: 0},
	{DescriptionBg2: 0},
	{HandTut: 0},
	{TutFader: 0},
	{Line2: 0},
	{NotEnoughCoins: 0},
	{Level: 0},
	{BuyLevelsPopup: 0},
	{Lock: 0},
	{LevelUnavailablePopup: 0},
	{level3TutBox: 0},
	{level3TutAlert: 0},
	{BtnFreeCoins: 0},
	{Value: 0},
	{FlyingCoin: 0},
	{WatchAdPopup: 0},
	{Arrow: 0},
	{SpellSync: 0},
	{FSpot: 0},
	{FDot: 0},
	{FLine: 0},
	{FWall: 0},
	{FWater: 0},
	{FInGameItems: 0},
	{FTarget: 0},
	{FCreatorItems: 0},
	{FBtnLevel: 0},
	{FButtons: 0},
	{FGlass: 0},
	{FBox: 0},
	{BoardW: 0},
	{BoardH: 0},
	{Size: 0},
	{LineHeight: 0},
	{SelectedDot: 0},
	{GSelectIndex: 0},
	{WaterIndex: 0},
	{GameStarted: 0},
	{AnchorsCreated: 0},
	{HasAnchor: 0},
	{Moves: 0},
	{ActiveBooster: 0},
	{Shuffling: 0},
	{EndGame: 0},
	{HandState: 0},
	{TutStep: 0},
	{TutSelecting: 0},
	{isSquare: 0},
	{PurchaseTransactionID: 0},
	{LastTutFlag: 0},
	{isInLvl3Tut: 0},
	{lineWidthRange: 0},
	{TotalRewarded: 0},
	{isPlay: 0},
	{vLeft: 0},
	{vRight: 0},
	{vTop: 0},
	{vBottom: 0},
	{BW: 0},
	{BH: 0},
	{vLevel: 0},
	{MiddleX: 0},
	{MiddleY: 0},
	{ItemsList: 0},
	{vItemName: 0},
	{SpotID: 0},
	{IsAnchor: 0},
	{vRnd: 0},
	{vItem: 0},
	{DotID: 0},
	{MainID: 0},
	{SecondID: 0},
	{FDotID: 0},
	{ItemID: 0},
	{DistXX: 0},
	{DistYY: 0},
	{MainSpotID: 0},
	{ItemName: 0},
	{vExist: 0},
	{vJSON: 0},
	{Do: 0},
	{BoosterName: 0},
	{vX: 0},
	{vY: 0},
	{vXX: 0},
	{vYY: 0},
	{vFound: 0},
	{vValue: 0},
	{String: 0},
	{BoardWidth: 0},
	{BoardHeight: 0},
	{GSeed: 0},
	{vIndex: 0},
	{W: 0},
	{H: 0},
	{X: 0},
	{Enable: 0},
	{CurLayer: 0},
	{ClickedButton: 0},
	{CurScrollY: 0},
	{GetValuesFlag: 0},
	{GetValuesFlag2: 0},
	{Name: 0},
	{SearchFor: 0},
	{ValueString: 0},
	{ScreenWidth: 0},
	{ScreenHeight: 0},
	{Swiping: 0},
	{CanSwipe: 0},
	{TouchStartY: 0},
	{Range: 0},
	{BuyAllLevels: 0},
	{PrevLayer: 0},
	{vSpc: 0},
	{vSize: 0},
	{vDist: 0},
	{SVGID: 0},
	{vTouchSpeed: 0},
	{Y: 0},
	{LSKey: 0},
	{RewardedState: 0}
];

self.InstanceType = {
	BtnClose: class extends self.ISpriteInstance {},
	BtnContinue: class extends self.ISpriteInstance {},
	BtnCreateBoard: class extends self.IButtonInstance {},
	BtnExit: class extends self.ISpriteInstance {},
	BtnGenerate: class extends self.IButtonInstance {},
	BtnGoLevel: class extends self.ISpriteInstance {},
	BtnLevel: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	BtnReset: class extends self.ISpriteInstance {},
	BtnRestart: class extends self.ISpriteInstance {},
	BtnSettings: class extends self.ISpriteInstance {},
	BtnSFX: class extends self.ISpriteInstance {},
	BtnBooster: class extends self.ISpriteInstance {},
	BtnBuyLevels: class extends self.ISpriteInstance {},
	BtnResume: class extends self.ISpriteInstance {},
	BtnWatchAd: class extends self.ISpriteInstance {},
	BtnAdClose: class extends self.ISpriteInstance {},
	FreeBooster: class extends self.ISpriteInstance {},
	BtnAdX2: class extends self.ISpriteInstance {},
	TxtBtnLevels: class extends self.ISpriteFontInstance {},
	TxtLabel: class extends self.ISpriteFontInstance {},
	TxtLevelInPopup: class extends self.ISpriteFontInstance {},
	TxtLoading: class extends self.ISpriteFontInstance {},
	TxtMoves: class extends self.ISpriteFontInstance {},
	TxtMovesInPopup: class extends self.ISpriteFontInstance {},
	TxtTarget: class extends self.ISpriteFontInstance {},
	TxtVersion: class extends self.ISpriteFontInstance {},
	TxtLevel: class extends self.ISpriteFontInstance {},
	TxtCoins: class extends self.ISpriteFontInstance {},
	TxtBoosterCount: class extends self.ISpriteFontInstance {},
	TxtBoosterDescription: class extends self.ISpriteFontInstance {},
	TxtBoosterDescription2: class extends self.ISpriteFontInstance {},
	TxtTut: class extends self.ISpriteFontInstance {},
	TxtBuyLevelsPopup: class extends self.ISpriteFontInstance {},
	TxtBtnBuyLevels: class extends self.ISpriteFontInstance {},
	TxtBuyLevelsPopupTitle: class extends self.ISpriteFontInstance {},
	TxtLevelUnavailablePopupTitle2: class extends self.ISpriteFontInstance {},
	TxtPaused: class extends self.ISpriteFontInstance {},
	TxtBtnWatchAdUnlockLevels: class extends self.ISpriteFontInstance {},
	TxtLoading2: class extends self.ISpriteFontInstance {},
	TxtReward: class extends self.ISpriteFontInstance {},
	TxtBtnWatchAd: class extends self.ISpriteFontInstance {},
	TxtWatchAdCoins: class extends self.ISpriteFontInstance {},
	TxtAd: class extends self.ISpriteFontInstance {},
	TxtNextReward: class extends self.ISpriteFontInstance {},
	Array: class extends self.IArrayInstance {},
	ArrayColSpot: class extends self.IArrayInstance {},
	ArrayColSpotEnd: class extends self.IArrayInstance {},
	ArrayDotType: class extends self.IArrayInstance {},
	JSON_Config: class extends self.IJSONInstance {},
	JSON_Creator: class extends self.IJSONInstance {},
	JSON_Levels: class extends self.IJSONInstance {},
	JSON_LS: class extends self.IJSONInstance {},
	JSON_TutLevel: class extends self.IJSONInstance {},
	Spot: class extends self.ISpriteInstance {},
	PosFixer: class extends self.ISpriteInstance {},
	Dot: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	ColorSprite: class extends self.ISpriteInstance {},
	Line: class extends self.ITiledBackgroundInstance {},
	DotCircle: class extends self.ISpriteInstance {},
	Wall: class extends self.ISpriteInstance {},
	Water: class extends self.ISpriteInstance {},
	Toucher: class extends self.ISpriteInstance {},
	Cam: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	CreatorItems: class extends self.ISpriteInstance {},
	TextInput: class extends self.ITextInputInstance {},
	Selector: class extends self.ISpriteInstance {},
	ItemOnBoard: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	TargetsPosFixer: class extends self.ISpriteInstance {},
	Target: class extends self.ISpriteInstance {},
	Tick: class extends self.ISpriteInstance {},
	Tick2: class extends self.ISpriteInstance {},
	TextInputResult: class extends self.ITextInputInstance {},
	AJAX: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	SVGPicture: class extends self.ISVGPictureInstance {},
	SVGPicture2: class extends self.ISVGPictureInstance {},
	Bg: class extends self.ITiledBackgroundInstance {},
	Swiper: class extends self.ISpriteInstance {},
	LevelsLine: class extends self.ITiledBackgroundInstance {},
	LevelsPopup: class extends self.ISpriteInstance {},
	BlackBg: class extends self.ITiledBackgroundInstance {},
	Glass: class extends self.ISpriteInstance {},
	Box: class extends self.ISpriteInstance {},
	TargetsBg: class extends self.IWorldInstance {},
	MovesBg: class extends self.IWorldInstance {},
	PausePopup: class extends self.IWorldInstance {},
	Audio: class extends self.IInstance {},
	Title: class extends self.ISpriteInstance {},
	CoinsBg: class extends self.IWorldInstance {},
	LevelDonePopup: class extends self.IWorldInstance {},
	PopupWhiteBox: class extends self.IWorldInstance {},
	LosePopup: class extends self.IWorldInstance {},
	BoosterCountBg: class extends self.ISpriteInstance {},
	DescriptionBg: class extends self.IWorldInstance {},
	DescriptionBg2: class extends self.IWorldInstance {},
	HandTut: class extends self.ISpriteInstance {},
	TutFader: class extends self.ISpriteInstance {},
	Line2: class extends self.ITiledBackgroundInstance {},
	NotEnoughCoins: class extends self.ISpriteInstance {},
	BuyLevelsPopup: class extends self.ISpriteInstance {},
	Lock: class extends self.ISpriteInstance {},
	LevelUnavailablePopup: class extends self.ISpriteInstance {},
	level3TutBox: class extends self.IWorldInstance {},
	level3TutAlert: class extends self.ISpriteInstance {},
	BtnFreeCoins: class extends self.ISpriteInstance {},
	FlyingCoin: class extends self.ISpriteInstance {},
	WatchAdPopup: class extends self.IWorldInstance {},
	Arrow: class extends self.ISpriteInstance {},
	SpellSync: class extends self.IInstance {},
	FSpot: class extends self.ISpriteInstance {},
	FDot: class extends self.ISpriteInstance {},
	FLine: class extends self.ITiledBackgroundInstance {},
	FWall: class extends self.ISpriteInstance {},
	FWater: class extends self.ISpriteInstance {},
	FInGameItems: class extends self.ISpriteInstance {},
	FTarget: class extends self.ISpriteInstance {},
	FCreatorItems: class extends self.ISpriteInstance {},
	FBtnLevel: class extends self.ISpriteInstance {},
	FButtons: class extends self.ISpriteInstance {},
	FGlass: class extends self.ISpriteInstance {},
	FBox: class extends self.ISpriteInstance {}
}