const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.WGSDK,
		C3.Behaviors.LOS,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Behaviors.Timer,
		C3.Plugins.Particles,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Tilemap.Acts.SetOpacity,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.LOS.Acts.CastRay,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.LOS.Exps.Range,
		C3.Behaviors.LOS.Exps.HitDistance,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Spritefont2.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.BBoxMidX,
		C3.Plugins.Sprite.Exps.BBoxMidY,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameTag,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.WGSDK.Cnds.RewardGranted,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetLayerTransparent,
		C3.Plugins.Spritefont2.Exps.Count,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.Platform.Acts.SetMaxFallSpeed,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Platform.Acts.SetGravityAngle,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.TiledBg.Cnds.OnCreated,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Acts.SetPosToObject,
		C3.Plugins.Spritefont2.Acts.SetPosToObject,
		C3.Plugins.Spritefont2.Cnds.IsVisible,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.TiledBg.Cnds.IsVisible,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Cnds.OnLoadFailed
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Physics: 0},
	{til6: 0},
	{tile0: 0},
	{adad: 0},
	{til2: 0},
	{til3: 0},
	{til4: 0},
	{til5: 0},
	{til1: 0},
	{til7: 0},
	{til8: 0},
	{til9: 0},
	{til10: 0},
	{tileCollision: 0},
	{TileRanjau: 0},
	{bg: 0},
	{bg2: 0},
	{Tween: 0},
	{PlayerGrafik: 0},
	{Move: 0},
	{jump: 0},
	{slide: 0},
	{gravity: 0},
	{Platform: 0},
	{PlayerCollisions: 0},
	{ScrollTo: 0},
	{Kamera: 0},
	{destroy: 0},
	{PlayerDestroy: 0},
	{PlayerDestroyGrafik: 0},
	{tutor: 0},
	{partikelPlayer: 0},
	{Touch: 0},
	{Keyboard: 0},
	{Audio: 0},
	{Mouse: 0},
	{WeeGooSDK: 0},
	{ranjau: 0},
	{anglle: 0},
	{JumpUp: 0},
	{Aktif: 0},
	{Tujuan: 0},
	{move: 0},
	{LineOfSight: 0},
	{Jump: 0},
	{Rotate: 0},
	{duri: 0},
	{aktif: 0},
	{Sine: 0},
	{Timer: 0},
	{JumpAir: 0},
	{value: 0},
	{AddPersen: 0},
	{ParticlesJump: 0},
	{PartikelJump: 0},
	{ParticlesJumpAir: 0},
	{FinisCollisions: 0},
	{size: 0},
	{PartikelFinis: 0},
	{level: 0},
	{SelectLevel: 0},
	{textlevel: 0},
	{lockLevel: 0},
	{borderLevel: 0},
	{Barnormal: 0},
	{TextPersenNormal: 0},
	{allTextLevel: 0},
	{BarPractice: 0},
	{TextPersenPractice: 0},
	{swipe: 0},
	{Swipe: 0},
	{textTutorial: 0},
	{logo: 0},
	{bgintro: 0},
	{pause: 0},
	{resume: 0},
	{home: 0},
	{sound: 0},
	{restart: 0},
	{NextLevel: 0},
	{sound2: 0},
	{bgPause: 0},
	{textPause: 0},
	{PopUpGameOver: 0},
	{textGameOver: 0},
	{BorderPersenGO: 0},
	{BarPersenGO: 0},
	{textPersenGO: 0},
	{cahaya: 0},
	{textGameStart: 0},
	{SkinName: 0},
	{BorderReward: 0},
	{textReward: 0},
	{UseReward: 0},
	{PlayerGrafikReward: 0},
	{CollisionCheckpoin: 0},
	{FaceCheckpoin: 0},
	{hapusCheckpoin: 0},
	{TombolCheckpoin: 0},
	{TombolCheckpoin2: 0},
	{tile: 0},
	{GameAktif: 0},
	{GameStart: 0},
	{GameOver: 0},
	{GameComplete: 0},
	{audio: 0},
	{skinName: 0},
	{GamePlay: 0},
	{Mode: 0},
	{rewardname: 0},
	{reward: 0},
	{CheckLevel: 0},
	{pencapaian: 0},
	{name: 0},
	{level1: 0},
	{level2: 0},
	{level3: 0},
	{level4: 0},
	{level5: 0},
	{level6: 0},
	{level7: 0},
	{level8: 0},
	{level9: 0},
	{level10: 0},
	{Practice1: 0},
	{Practice2: 0},
	{Practice3: 0},
	{Practice4: 0},
	{Practice5: 0},
	{Practice6: 0},
	{Practice7: 0},
	{Practice8: 0},
	{Practice9: 0},
	{Practice10: 0},
	{ADS: 0},
	{data: 0}
];

self.InstanceType = {
	til6: class extends self.ITilemapInstance {},
	tile0: class extends self.ITilemapInstance {},
	adad: class extends self.ISpriteInstance {},
	til2: class extends self.ITilemapInstance {},
	til3: class extends self.ITilemapInstance {},
	til4: class extends self.ITilemapInstance {},
	til5: class extends self.ITilemapInstance {},
	til1: class extends self.ITilemapInstance {},
	til7: class extends self.ITilemapInstance {},
	til8: class extends self.ITilemapInstance {},
	til9: class extends self.ITilemapInstance {},
	til10: class extends self.ITilemapInstance {},
	tileCollision: class extends self.ITilemapInstance {},
	TileRanjau: class extends self.ITilemapInstance {},
	bg: class extends self.ITiledBackgroundInstance {},
	bg2: class extends self.ITiledBackgroundInstance {},
	PlayerGrafik: class extends self.ISpriteInstance {},
	PlayerCollisions: class extends self.ISpriteInstance {},
	Kamera: class extends self.ISpriteInstance {},
	destroy: class extends self.ISpriteInstance {},
	PlayerDestroy: class extends self.ISpriteInstance {},
	PlayerDestroyGrafik: class extends self.ISpriteInstance {},
	tutor: class extends self.ISpriteInstance {},
	partikelPlayer: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	WeeGooSDK: class extends self.IInstance {},
	ranjau: class extends self.ISpriteInstance {},
	JumpUp: class extends self.ISpriteInstance {},
	Jump: class extends self.ISpriteInstance {},
	duri: class extends self.ISpriteInstance {},
	JumpAir: class extends self.ISpriteInstance {},
	AddPersen: class extends self.ISpriteInstance {},
	ParticlesJump: class extends self.IParticlesInstance {},
	PartikelJump: class extends self.IParticlesInstance {},
	ParticlesJumpAir: class extends self.IParticlesInstance {},
	FinisCollisions: class extends self.ISpriteInstance {},
	PartikelFinis: class extends self.ISpriteInstance {},
	SelectLevel: class extends self.ISpriteInstance {},
	textlevel: class extends self.ISpriteFontInstance {},
	lockLevel: class extends self.ISpriteInstance {},
	borderLevel: class extends self.ISpriteInstance {},
	Barnormal: class extends self.ITiledBackgroundInstance {},
	TextPersenNormal: class extends self.ISpriteFontInstance {},
	allTextLevel: class extends self.ISpriteFontInstance {},
	BarPractice: class extends self.ITiledBackgroundInstance {},
	TextPersenPractice: class extends self.ISpriteFontInstance {},
	Swipe: class extends self.ISpriteInstance {},
	textTutorial: class extends self.ISpriteFontInstance {},
	logo: class extends self.ISpriteInstance {},
	bgintro: class extends self.ISpriteInstance {},
	pause: class extends self.ISpriteInstance {},
	resume: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	sound: class extends self.ISpriteInstance {},
	restart: class extends self.ISpriteInstance {},
	NextLevel: class extends self.ISpriteInstance {},
	sound2: class extends self.ISpriteInstance {},
	bgPause: class extends self.ISpriteInstance {},
	textPause: class extends self.ISpriteFontInstance {},
	PopUpGameOver: class extends self.ISpriteInstance {},
	textGameOver: class extends self.ISpriteFontInstance {},
	BorderPersenGO: class extends self.ISpriteInstance {},
	BarPersenGO: class extends self.ITiledBackgroundInstance {},
	textPersenGO: class extends self.ISpriteFontInstance {},
	cahaya: class extends self.ISpriteInstance {},
	textGameStart: class extends self.ISpriteFontInstance {},
	BorderReward: class extends self.ISpriteInstance {},
	textReward: class extends self.ISpriteFontInstance {},
	UseReward: class extends self.ISpriteInstance {},
	PlayerGrafikReward: class extends self.ISpriteInstance {},
	CollisionCheckpoin: class extends self.ISpriteInstance {},
	FaceCheckpoin: class extends self.ISpriteInstance {},
	hapusCheckpoin: class extends self.ISpriteInstance {},
	TombolCheckpoin: class extends self.ISpriteInstance {},
	TombolCheckpoin2: class extends self.ISpriteInstance {},
	tile: class extends self.ITilemapInstance {}
}