const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Behaviors.Rotate,
		C3.Behaviors.Timer,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Arr,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.AJAX,
		C3.Plugins.Dictionary,
		C3.Plugins.GameRecorder,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Behaviors.Sin.Exps.Value,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetMeshPoint,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.Particles.Exps.X,
		C3.Plugins.Particles.Exps.Y,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Eponesh_GameScore.Acts.AchievementsOpen,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Eponesh_GameScore.Acts.SetBackground,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.Plugins.Eponesh_GameScore.Exps.Language,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStop,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStart,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Tween.Acts.PauseTweens,
		C3.Plugins.Sprite.Acts.SetMeshSize,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Text.Cnds.OnTypewriterTextFinished,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Particles.Exps.Rate,
		C3.Plugins.Particles.Acts.SetInitSpeed,
		C3.Plugins.Particles.Exps.InitSpeed,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSetScore,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenAvailable,
		C3.Plugins.Eponesh_GameScore.Cnds.IsPlayerStub,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedClose,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsLastAdSuccess,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsFullscreenClose,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAchievementsClose,
		C3.Plugins.GameRecorder.Acts.StartRecording2,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.GameRecorder.Acts.StopRecording,
		C3.Plugins.GameRecorder.Cnds.OnRecordingReady,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.GameRecorder.Exps.RecordingURL,
		C3.Plugins.Eponesh_GameScore.Cnds.AchievementsIsUnlocked,
		C3.Plugins.Eponesh_GameScore.Acts.AchievementsSetProgress,
		C3.Plugins.Eponesh_GameScore.Acts.AchievementsUnlock,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardFetch,
		C3.Plugins.Eponesh_GameScore.Cnds.LeaderboardEachPlayer,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerName,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerScore,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerID,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerField,
		C3.Plugins.Dictionary.Acts.Clear
	];
};
self.C3_JsPropNameTable = [
	{BKG_Green: 0},
	{Part_Splash: 0},
	{Part_TileSplash: 0},
	{TileNumber: 0},
	{Sine: 0},
	{Tween: 0},
	{PositionTile: 0},
	{Part_Splash2: 0},
	{BKG_Game: 0},
	{Part_Dionea: 0},
	{BKG_Map: 0},
	{LaboratoryBkg: 0},
	{Rotate: 0},
	{RotatingCandyPlate: 0},
	{TitleOrnament: 0},
	{SplashCoins: 0},
	{BONUS_Dionea: 0},
	{CoinsFrame: 0},
	{SplashCoinsIcon: 0},
	{BlurScreen: 0},
	{BlankScreen: 0},
	{ButtonTag: 0},
	{ButtonBuyIngredient: 0},
	{PinkButton: 0},
	{RotatingBonusPlate: 0},
	{RotatingBonusPlateBW: 0},
	{OfferTimer: 0},
	{Timer: 0},
	{Dionea_Bonus_ADS_Button: 0},
	{AdsTimerFrame: 0},
	{DioneaQtyFrame: 0},
	{RewardedAdsTag: 0},
	{Darker: 0},
	{TargetTileUID: 0},
	{Sine2: 0},
	{FlyAgarics: 0},
	{PinkOverviewButton: 0},
	{ReturnButton: 0},
	{GameLogo: 0},
	{Claudron: 0},
	{SteamParticles: 0},
	{FlameReflectionParticlesOrange: 0},
	{FlameTonguesParticles: 0},
	{ParchmentIngedientIndex: 0},
	{ParchmentPosition: 0},
	{Parchment: 0},
	{PinkButton208x72: 0},
	{ForwardButton: 0},
	{RoundMapButon: 0},
	{PinkFlag: 0},
	{CoinsEnemyHitParticles: 0},
	{EnemyAngryMeterFrame: 0},
	{EnemyAngryMeterBar: 0},
	{mvfTag: 0},
	{MenuVariablesFrame: 0},
	{BonusChest: 0},
	{CastleActivityTag: 0},
	{BonusChestPlate: 0},
	{CastleAdditionalActivity: 0},
	{CastleAATimerPlate: 0},
	{CastleAAButton: 0},
	{GoldenGoblet: 0},
	{GoldenGobletGlare: 0},
	{ButtonRetreat: 0},
	{RetreatMenuFrame: 0},
	{ShortButton_Red: 0},
	{ShortButton_Green: 0},
	{BonusChestCoinplate: 0},
	{OFFER_Number: 0},
	{OfferSphereFrame: 0},
	{Sphere_Red: 0},
	{GlareForSphere: 0},
	{OfferButton_Decline: 0},
	{OfferButton_Accept: 0},
	{Sphere_Yellow: 0},
	{Glare_8Points: 0},
	{SphereParticle_RED: 0},
	{SphereParticlesRED: 0},
	{SphereParticlesAdditive: 0},
	{SphereParticlesYELLOW: 0},
	{Sphere_Green: 0},
	{Sphere_Blue: 0},
	{SphereParticlesGreen: 0},
	{SphereParticlesGreenAdditive: 0},
	{SphereParticlesBlueSnowflakes: 0},
	{SphereParticlesBlueSnowflakesAdditive: 0},
	{SphereBlueParticlesSnowflakeAdditiveLine: 0},
	{SphereParticlesGreenSplash: 0},
	{ButtonLeaderboard: 0},
	{ButtonLeaderboardBack: 0},
	{ButtonLeaderboardCoin: 0},
	{ButtonLeaderboardMerges: 0},
	{LeaderboardEntryBkg: 0},
	{ButtonLeaderboardScores: 0},
	{ButtonLeaderboardDamage: 0},
	{IsDragged: 0},
	{CandyType: 0},
	{Candy_1R: 0},
	{Candy_2O: 0},
	{Candy_3Y: 0},
	{Candy_4G: 0},
	{Candy_5L: 0},
	{Candy_6B: 0},
	{Candy_7V: 0},
	{TweenName: 0},
	{SplashCandies: 0},
	{Dionea: 0},
	{ENEMY_HP: 0},
	{ENEMY_MaxHP: 0},
	{ENEMY_DefeatTime: 0},
	{ENEMY_SpellCoolDown: 0},
	{WarlockMaxHP: 0},
	{WarlockHP: 0},
	{WarlockSpellCoolDown: 0},
	{WarlockDefeatTime: 0},
	{Warlock: 0},
	{WarlockCloak: 0},
	{WarlockOrbR1: 0},
	{WarlockOrbR2: 0},
	{SpellParticles: 0},
	{SpellParticlesAdditive: 0},
	{SpellParticlesAdditiveIdle: 0},
	{SpellParticlesAdditiveHIT: 0},
	{IngredientOrder: 0},
	{Ingredients: 0},
	{IngredientSplashRed: 0},
	{IngredientSplashYellow: 0},
	{IngredientSplashGreen: 0},
	{IngredientSplashBlue: 0},
	{Potion: 0},
	{PotionSplashRed: 0},
	{PotionSplashYellow: 0},
	{PotionSplashGreen: 0},
	{PotionSplashBlue: 0},
	{FireworksParticlesRocket_Red: 0},
	{FireworksParticlesRocket_Yellow: 0},
	{FireworksParticlesRocket_Green: 0},
	{FireworksParticlesRocket_Blue: 0},
	{FireworksParticlesSplash_Red: 0},
	{FireworksParticlesSplash_Yellow: 0},
	{FireworksParticlesSplash_Green: 0},
	{FireworksParticlesSplash_Blue: 0},
	{FireworksParticlesSplash_Additive: 0},
	{FireworksParticlesRocket_Additive: 0},
	{Shaman: 0},
	{ShamanEyeGlare: 0},
	{ShamanCircle: 0},
	{ShamanDustParticles: 0},
	{SpiritCircle: 0},
	{Witch: 0},
	{Witch_Hairs: 0},
	{Witch_Cloak: 0},
	{Witch_HatPart: 0},
	{Witch_HairRightpart: 0},
	{Witch_HairLeftpart: 0},
	{Witch_Lightning: 0},
	{Witch_LightningParticles: 0},
	{Witch_HandsParticles: 0},
	{Witch_HandsParticlesGreen: 0},
	{Witch_LightningReflections: 0},
	{Witch_HorizontalRay: 0},
	{Witch_HorizontalRayReflection: 0},
	{Sorcerer: 0},
	{Sorcerer_SymbolParticles: 0},
	{Sorcerer_MagicChain: 0},
	{Sorcerer_Bolt: 0},
	{SorcererSpellHitParticle: 0},
	{SorcererDustParticle: 0},
	{Sorcerer_BoltReflection: 0},
	{Tutor_Scroll_Upper: 0},
	{Tutor_Scroll_Lower: 0},
	{TB_Tutor_Scroll_Middle: 0},
	{Tutor_Darker: 0},
	{TUTOR_Cell: 0},
	{TUTOR_Plate: 0},
	{TUTOR_RedCandy: 0},
	{TUTOR_OrangeCandy: 0},
	{TUTOR_Title_txt: 0},
	{TUTOR_txt: 0},
	{TUTOR_Particles: 0},
	{TUTOR_Enemies: 0},
	{Tutor_Lines: 0},
	{TUTOR_CandyRainbow: 0},
	{TUTOR_Lab: 0},
	{TUTOR_Potion: 0},
	{TUTOR_Dionea: 0},
	{TUTOR_BONUS_Dionea: 0},
	{TUTOR_DioneaGlare: 0},
	{TUTOR_RetreatCampEngraving: 0},
	{TUTOR_EndGame: 0},
	{Sine3: 0},
	{MenuControlBox: 0},
	{GameLogoGlareParticle: 0},
	{CihLogo: 0},
	{EnemyHPbar: 0},
	{EnemyHPbarBkg: 0},
	{txtEnemyHP: 0},
	{Touch: 0},
	{Field: 0},
	{FieldUIDs: 0},
	{EmptyCellsArray: 0},
	{EmptyCellsUIDsArray: 0},
	{GamePush: 0},
	{TranslationArray: 0},
	{AJAX: 0},
	{TranslationDictionary: 0},
	{IngredientsCostArray: 0},
	{PotionIngredientsArray: 0},
	{FlagOffsetArray: 0},
	{ShamanCandyLinearArray: 0},
	{ShamanUIDsLinearArray: 0},
	{Sorcerer_UIDArray: 0},
	{VideoRecorder: 0},
	{Browser: 0},
	{Keyboard: 0},
	{WarlockCloakArray: 0},
	{LeaderboardArray: 0},
	{LeaderboardDictionary: 0},
	{txtLoadConsole: 0},
	{txtPoints: 0},
	{txtFreeCells: 0},
	{txtPointsText: 0},
	{txtFreeCellsText: 0},
	{txtCoins: 0},
	{txtDebug: 0},
	{txtAdsTimer: 0},
	{txtBonusQty: 0},
	{txtGOPointsEarned: 0},
	{txtGOCoinsEarned: 0},
	{txtButtonLabel: 0},
	{txtIngredients: 0},
	{txtIngredientLabel: 0},
	{txtIngredientPrice: 0},
	{txtVersion: 0},
	{txtCoinsText: 0},
	{txtBonusChestTime: 0},
	{txtBonusChestCoins: 0},
	{txtBonusChestCoinsBkg: 0},
	{txtCastleActivityTimer: 0},
	{txtGOResults: 0},
	{txtGOResultsText: 0},
	{txtCastleActivityBonus: 0},
	{txtCastleActivityBonusBKG: 0},
	{txtRetreatMenuTitle: 0},
	{txtRetreatMenuText: 0},
	{txtShortButtonLabel: 0},
	{txtBonusChestCoinsQty: 0},
	{txtOfferMenuText: 0},
	{txtLeaderboardTitle: 0},
	{txtLeaderboardEntry: 0},
	{txtLeaderboardTitleDescription: 0},
	{CANDIES: 0},
	{BONUSES: 0},
	{FIREWORK_ROCKETS: 0},
	{ENEMIES: 0},
	{MENU_BLUR: 0},
	{MENU_X2: 0},
	{MENU_SPHERE_OFFER_NUMBER: 0},
	{lvSineOffset: 0},
	{lvOffset: 0},
	{lvActivityState: 0},
	{parID: 0},
	{parState: 0},
	{lvID: 0},
	{lvTimeLeft: 0},
	{lvResult: 0},
	{parX: 0},
	{parY: 0},
	{parButtonTag: 0},
	{lvIndex: 0},
	{lvYStringInterval: 0},
	{lvYTitleInterval: 0},
	{lvXStringInterval: 0},
	{lvYHeader: 0},
	{lvYDescription: 0},
	{parText: 0},
	{lvSaturationColor: 0},
	{parActive: 0},
	{parCost: 0},
	{lvRandom: 0},
	{lvX: 0},
	{lvY: 0},
	{lvReturn: 0},
	{lvTimeMins: 0},
	{lvTimeSecs: 0},
	{parTime: 0},
	{lvCoinsBonus: 0},
	{lvSphereType: 0},
	{lvOfferNumber: 0},
	{score: 0},
	{iLangNum: 0},
	{iLanguage: 0},
	{GAME_EnemiesDefeated: 0},
	{GAME_MERGES: 0},
	{GAME_COINS: 0},
	{GAME_TOTALCOINS: 0},
	{GAME_Startup: 0},
	{GAME_BonusChest: 0},
	{GAME_BonusChestTime: 0},
	{GAME_BonusActivity1: 0},
	{GAME_BonusActivity1Time: 0},
	{GAME_BonusActivity2: 0},
	{GAME_BonusActivity2Time: 0},
	{GAME_BonusActivity3: 0},
	{GAME_BonusActivity3Time: 0},
	{RECORDER_PREFIX: 0},
	{GAME_CURRENTENEMYPOTION: 0},
	{GAME_CompositeLinesQty: 0},
	{GAME_COMPLETIONS: 0},
	{GAME_LASTVERSIONPLAYED: 0},
	{GAME_TUTORIAL_LEVEL: 0},
	{GAME_Sphere_Red: 0},
	{GAME_Sphere_Yellow: 0},
	{GAME_Sphere_Green: 0},
	{GAME_Sphere_Blue: 0},
	{GAME_FS_ADS_TAG: 0},
	{GAME_ACHIEVEMENTSCOUNT: 0},
	{GAME_EnemyMaxHp: 0},
	{LG_POINTS: 0},
	{LG_DEBUG: 0},
	{LG_DIONEA_QTY: 0},
	{LG_BonusDIONEA_QTY: 0},
	{LG_COINS: 0},
	{LG_DioneaOfferActive: 0},
	{LG_DioneaOfferTriggerTimer: 0},
	{LG_ENEMYFliesNow: 0},
	{LG_NextENEMYSpawn: 0},
	{LG_NextENEMYSpawnIncrement: 0},
	{LG_NextENEMYMaxHP: 0},
	{LG_LastEnemySpawnDefeatTime: 0},
	{LG_NextEnemySpellCoolDown: 0},
	{LG_ENDGAME: 0},
	{LG_NextDioneaBonusGrant: 0},
	{LG_MergesQty: 0},
	{LG_FreeCellsLeft: 0},
	{LG_FLYAGARICSTRIGGERED: 0},
	{LG_DEBUG2: 0},
	{Tile_X: 0},
	{Tile_Y: 0},
	{T49UID: 0},
	{LG_BestMerge: 0},
	{StateMachine: 0},
	{DraggedCandyUID: 0},
	{DraggedCandyType: 0},
	{DraggedBonusUID: 0},
	{DraggedBonusType: 0},
	{LG_TUTOR_DRAGGING: 0},
	{CandyStartX: 0},
	{CandyStartY: 0},
	{CandySettled: 0},
	{LG_NCMFT_BaseCellXNum: 0},
	{LG_NCMFT_BaseCellYNum: 0},
	{LG_NCMFT_BaseCellUID: 0},
	{LG_NCMFT_BaseCellCandyValue: 0},
	{LG_ENEMYDEFEATED: 0},
	{LG_CS_CandySplashTime: 0},
	{LG_CS_NewCandySplashTime: 0},
	{LG_MaximalDamage: 0},
	{LastChosenTile: 0},
	{lv_CheatTimes: 0},
	{parNextState: 0},
	{lvTutorTextY: 0},
	{parStep: 0},
	{lvRedTilesQty: 0},
	{lvIsTileFree: 0},
	{lvXTN: 0},
	{lvYTN: 0},
	{parTileNumber: 0},
	{parTileUID: 0},
	{lv1: 0},
	{lv_TileNumber: 0},
	{parTemplateNumber: 0},
	{lvHoveredFreeTileUID: 0},
	{lvHoveredOccupiedTileUID: 0},
	{lvTileNumber: 0},
	{lvCurrentTileUID: 0},
	{lvCurrentTileFrame: 0},
	{lvTileX0: 0},
	{lvTileX1: 0},
	{lvTileY0: 0},
	{lvTileY1: 0},
	{lvPointsEarned: 0},
	{lvCandy: 0},
	{lvRatio: 0},
	{lvMatch: 0},
	{parCell0: 0},
	{parCell1: 0},
	{parCell2: 0},
	{parCell3: 0},
	{parCell4: 0},
	{pX: 0},
	{pY: 0},
	{pV: 0},
	{pSCU: 0},
	{lvCellUID: 0},
	{lvA: 0},
	{lvB: 0},
	{lvC: 0},
	{lvD: 0},
	{lvE: 0},
	{parCellX: 0},
	{parCellY: 0},
	{parLength: 0},
	{lvX0: 0},
	{lvY0: 0},
	{lvX1: 0},
	{lvY1: 0},
	{parCellFromUID: 0},
	{parCellToUID: 0},
	{parSplashCandyValue: 0},
	{parBaseCellUID: 0},
	{parXNum: 0},
	{parYNum: 0},
	{parValue: 0},
	{parCandyType: 0},
	{parScoreEarned: 0},
	{lvNum: 0},
	{lvType: 0},
	{lvUidNum: 0},
	{parType: 0},
	{parUID: 0},
	{lvAbsX: 0},
	{lvAbsY: 0},
	{parMatchType: 0},
	{parFirstElementXNum: 0},
	{parFirstElementYNum: 0},
	{lvRatioValue: 0},
	{parAddPoints: 0},
	{parMerge: 0},
	{lvFrame: 0},
	{parCoinX: 0},
	{parCoinY: 0},
	{lvRandomAngle: 0},
	{lvToBeDestroyed: 0},
	{lvDefaultTimer: 0},
	{parX0: 0},
	{parY0: 0},
	{parX1: 0},
	{parY1: 0},
	{parTweenName: 0},
	{lvDirection: 0},
	{lvStartupPosition: 0},
	{lvMoveTo: 0},
	{lvWarlockHP: 0},
	{lvSpellCoolDown: 0},
	{lvFreeCellX: 0},
	{lvROX: 0},
	{lvROY: 0},
	{lvLOX: 0},
	{lvLOY: 0},
	{lvSteps: 0},
	{parTargetX: 0},
	{parTargetY: 0},
	{lvTargetCellNumber: 0},
	{lvTargetCellX: 0},
	{lvTargetCellY: 0},
	{lvTargetCellXNum: 0},
	{lvTargetCellYNum: 0},
	{lvRandomCell_Xnum: 0},
	{lvRandomCell_Ynum: 0},
	{lvRandomCell_UID: 0},
	{lvRandomMovesQty: 0},
	{lvRandomRow_Ynum: 0},
	{lvRandomRow_Y: 0},
	{lvLoopindex: 0},
	{lvCellX: 0},
	{lvCellY: 0},
	{lvCellCandyType: 0},
	{lvCurrentIndex: 0},
	{lvUID: 0},
	{lvCandyType: 0},
	{lvUIDCell: 0},
	{lvRow: 0},
	{lvCol: 0},
	{lvBoltDistance: 0},
	{lvRandomChance: 0},
	{lvOriginalType: 0},
	{lvLastCell: 0},
	{parTimes: 0},
	{lvCurX: 0},
	{lvCurY: 0},
	{parTargetCellXNum: 0},
	{parTargetCellYNum: 0},
	{lvCellValue: 0},
	{parShamanArrayIndex: 0},
	{parDefault: 0},
	{lvTimerRetard: 0},
	{lvPositionTileFrame: 0},
	{lvPosX: 0},
	{lvPosY: 0},
	{lvMaxHP: 0},
	{parHitPower: 0},
	{lvRandomTime: 0},
	{lvTime: 0},
	{parUID0: 0},
	{parUID1: 0},
	{lvX2: 0},
	{lvY2: 0},
	{lvTargetCellUID: 0},
	{lvEnemyHP: 0},
	{lvShamanX: 0},
	{lvShamanY: 0},
	{lvScale: 0},
	{lvOpacity: 0},
	{lvTweenTTL: 0},
	{parCellUID: 0},
	{parTextTag: 0},
	{lvSign: 0},
	{lvTouchX: 0},
	{lvTouchY: 0},
	{parSphereX: 0},
	{parSphereY: 0},
	{parSphereType: 0},
	{lvRandomPlace: 0},
	{lvSphereX: 0},
	{lvSphereY: 0},
	{LA_ZoomIn: 0},
	{LA_PotionCreated: 0},
	{LA_IngredientsCollected: 0},
	{lvRandomPoint: 0},
	{parTag: 0},
	{lvNotAffordable: 0},
	{parIngredientNumber: 0},
	{parSwitch: 0},
	{lvChapterIncrement: 0},
	{lvIngredientNumber: 0},
	{lvVal: 0},
	{lvCurIngSta: 0},
	{lvIngredientUID: 0},
	{lvTargetPoint: 0},
	{lvPointX: 0},
	{lvPointY: 0},
	{lv: 0},
	{parCastleActivityID: 0},
	{lvVerTxt: 0},
	{parCheckForFirstIngredientBought: 0},
	{lvName: 0},
	{lvText: 0},
	{lvAchievementsCount: 0},
	{lvFieldKeyName: 0}
];

self.InstanceType = {
	BKG_Green: class extends self.ISpriteInstance {},
	Part_Splash: class extends self.IParticlesInstance {},
	Part_TileSplash: class extends self.IParticlesInstance {},
	PositionTile: class extends self.ISpriteInstance {},
	Part_Splash2: class extends self.IParticlesInstance {},
	BKG_Game: class extends self.ISpriteInstance {},
	Part_Dionea: class extends self.IParticlesInstance {},
	BKG_Map: class extends self.ISpriteInstance {},
	LaboratoryBkg: class extends self.ISpriteInstance {},
	RotatingCandyPlate: class extends self.ISpriteInstance {},
	TitleOrnament: class extends self.ISpriteInstance {},
	SplashCoins: class extends self.ISpriteInstance {},
	BONUS_Dionea: class extends self.ISpriteInstance {},
	CoinsFrame: class extends self.ISpriteInstance {},
	SplashCoinsIcon: class extends self.ISpriteInstance {},
	BlurScreen: class extends self.ISpriteInstance {},
	BlankScreen: class extends self.ISpriteInstance {},
	PinkButton: class extends self.ISpriteInstance {},
	RotatingBonusPlate: class extends self.ISpriteInstance {},
	RotatingBonusPlateBW: class extends self.ISpriteInstance {},
	Dionea_Bonus_ADS_Button: class extends self.ISpriteInstance {},
	AdsTimerFrame: class extends self.ISpriteInstance {},
	DioneaQtyFrame: class extends self.ISpriteInstance {},
	RewardedAdsTag: class extends self.ISpriteInstance {},
	Darker: class extends self.ISpriteInstance {},
	FlyAgarics: class extends self.ISpriteInstance {},
	PinkOverviewButton: class extends self.ISpriteInstance {},
	ReturnButton: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	Claudron: class extends self.ISpriteInstance {},
	SteamParticles: class extends self.IParticlesInstance {},
	FlameReflectionParticlesOrange: class extends self.IParticlesInstance {},
	FlameTonguesParticles: class extends self.IParticlesInstance {},
	Parchment: class extends self.ISpriteInstance {},
	PinkButton208x72: class extends self.ISpriteInstance {},
	ForwardButton: class extends self.ISpriteInstance {},
	RoundMapButon: class extends self.ISpriteInstance {},
	PinkFlag: class extends self.ISpriteInstance {},
	CoinsEnemyHitParticles: class extends self.IParticlesInstance {},
	EnemyAngryMeterFrame: class extends self.ISpriteInstance {},
	EnemyAngryMeterBar: class extends self.ISpriteInstance {},
	MenuVariablesFrame: class extends self.ISpriteInstance {},
	BonusChest: class extends self.ISpriteInstance {},
	BonusChestPlate: class extends self.ISpriteInstance {},
	CastleAdditionalActivity: class extends self.ISpriteInstance {},
	CastleAATimerPlate: class extends self.ISpriteInstance {},
	CastleAAButton: class extends self.ISpriteInstance {},
	GoldenGoblet: class extends self.ISpriteInstance {},
	GoldenGobletGlare: class extends self.ISpriteInstance {},
	ButtonRetreat: class extends self.ISpriteInstance {},
	RetreatMenuFrame: class extends self.ISpriteInstance {},
	ShortButton_Red: class extends self.ISpriteInstance {},
	ShortButton_Green: class extends self.ISpriteInstance {},
	BonusChestCoinplate: class extends self.ISpriteInstance {},
	OfferSphereFrame: class extends self.ISpriteInstance {},
	Sphere_Red: class extends self.ISpriteInstance {},
	GlareForSphere: class extends self.ISpriteInstance {},
	OfferButton_Decline: class extends self.ISpriteInstance {},
	OfferButton_Accept: class extends self.ISpriteInstance {},
	Sphere_Yellow: class extends self.ISpriteInstance {},
	Glare_8Points: class extends self.ISpriteInstance {},
	SphereParticle_RED: class extends self.IParticlesInstance {},
	SphereParticlesRED: class extends self.IParticlesInstance {},
	SphereParticlesAdditive: class extends self.IParticlesInstance {},
	SphereParticlesYELLOW: class extends self.IParticlesInstance {},
	Sphere_Green: class extends self.ISpriteInstance {},
	Sphere_Blue: class extends self.ISpriteInstance {},
	SphereParticlesGreen: class extends self.IParticlesInstance {},
	SphereParticlesGreenAdditive: class extends self.IParticlesInstance {},
	SphereParticlesBlueSnowflakes: class extends self.IParticlesInstance {},
	SphereParticlesBlueSnowflakesAdditive: class extends self.IParticlesInstance {},
	SphereBlueParticlesSnowflakeAdditiveLine: class extends self.IParticlesInstance {},
	SphereParticlesGreenSplash: class extends self.IParticlesInstance {},
	ButtonLeaderboard: class extends self.ISpriteInstance {},
	ButtonLeaderboardBack: class extends self.ISpriteInstance {},
	ButtonLeaderboardCoin: class extends self.ISpriteInstance {},
	ButtonLeaderboardMerges: class extends self.ISpriteInstance {},
	LeaderboardEntryBkg: class extends self.ISpriteInstance {},
	ButtonLeaderboardScores: class extends self.ISpriteInstance {},
	ButtonLeaderboardDamage: class extends self.ISpriteInstance {},
	Candy_1R: class extends self.ISpriteInstance {},
	Candy_2O: class extends self.ISpriteInstance {},
	Candy_3Y: class extends self.ISpriteInstance {},
	Candy_4G: class extends self.ISpriteInstance {},
	Candy_5L: class extends self.ISpriteInstance {},
	Candy_6B: class extends self.ISpriteInstance {},
	Candy_7V: class extends self.ISpriteInstance {},
	SplashCandies: class extends self.ISpriteInstance {},
	Dionea: class extends self.ISpriteInstance {},
	Warlock: class extends self.ISpriteInstance {},
	WarlockCloak: class extends self.ISpriteInstance {},
	WarlockOrbR1: class extends self.ISpriteInstance {},
	WarlockOrbR2: class extends self.ISpriteInstance {},
	SpellParticles: class extends self.IParticlesInstance {},
	SpellParticlesAdditive: class extends self.IParticlesInstance {},
	SpellParticlesAdditiveIdle: class extends self.IParticlesInstance {},
	SpellParticlesAdditiveHIT: class extends self.IParticlesInstance {},
	Ingredients: class extends self.ISpriteInstance {},
	IngredientSplashRed: class extends self.IParticlesInstance {},
	IngredientSplashYellow: class extends self.IParticlesInstance {},
	IngredientSplashGreen: class extends self.IParticlesInstance {},
	IngredientSplashBlue: class extends self.IParticlesInstance {},
	Potion: class extends self.ISpriteInstance {},
	PotionSplashRed: class extends self.IParticlesInstance {},
	PotionSplashYellow: class extends self.IParticlesInstance {},
	PotionSplashGreen: class extends self.IParticlesInstance {},
	PotionSplashBlue: class extends self.IParticlesInstance {},
	FireworksParticlesRocket_Red: class extends self.IParticlesInstance {},
	FireworksParticlesRocket_Yellow: class extends self.IParticlesInstance {},
	FireworksParticlesRocket_Green: class extends self.IParticlesInstance {},
	FireworksParticlesRocket_Blue: class extends self.IParticlesInstance {},
	FireworksParticlesSplash_Red: class extends self.IParticlesInstance {},
	FireworksParticlesSplash_Yellow: class extends self.IParticlesInstance {},
	FireworksParticlesSplash_Green: class extends self.IParticlesInstance {},
	FireworksParticlesSplash_Blue: class extends self.IParticlesInstance {},
	FireworksParticlesSplash_Additive: class extends self.IParticlesInstance {},
	FireworksParticlesRocket_Additive: class extends self.IParticlesInstance {},
	Shaman: class extends self.ISpriteInstance {},
	ShamanEyeGlare: class extends self.ISpriteInstance {},
	ShamanCircle: class extends self.ISpriteInstance {},
	ShamanDustParticles: class extends self.IParticlesInstance {},
	SpiritCircle: class extends self.ISpriteInstance {},
	Witch: class extends self.ISpriteInstance {},
	Witch_Hairs: class extends self.ISpriteInstance {},
	Witch_Cloak: class extends self.ISpriteInstance {},
	Witch_HatPart: class extends self.ISpriteInstance {},
	Witch_HairRightpart: class extends self.ISpriteInstance {},
	Witch_HairLeftpart: class extends self.ISpriteInstance {},
	Witch_Lightning: class extends self.ISpriteInstance {},
	Witch_LightningParticles: class extends self.IParticlesInstance {},
	Witch_HandsParticles: class extends self.IParticlesInstance {},
	Witch_HandsParticlesGreen: class extends self.IParticlesInstance {},
	Witch_LightningReflections: class extends self.ISpriteInstance {},
	Witch_HorizontalRay: class extends self.ISpriteInstance {},
	Witch_HorizontalRayReflection: class extends self.ISpriteInstance {},
	Sorcerer: class extends self.ISpriteInstance {},
	Sorcerer_SymbolParticles: class extends self.IParticlesInstance {},
	Sorcerer_MagicChain: class extends self.ISpriteInstance {},
	Sorcerer_Bolt: class extends self.ISpriteInstance {},
	SorcererSpellHitParticle: class extends self.IParticlesInstance {},
	SorcererDustParticle: class extends self.IParticlesInstance {},
	Sorcerer_BoltReflection: class extends self.ISpriteInstance {},
	Tutor_Scroll_Upper: class extends self.ISpriteInstance {},
	Tutor_Scroll_Lower: class extends self.ISpriteInstance {},
	TB_Tutor_Scroll_Middle: class extends self.ITiledBackgroundInstance {},
	Tutor_Darker: class extends self.ISpriteInstance {},
	TUTOR_Cell: class extends self.ISpriteInstance {},
	TUTOR_Plate: class extends self.ISpriteInstance {},
	TUTOR_RedCandy: class extends self.ISpriteInstance {},
	TUTOR_OrangeCandy: class extends self.ISpriteInstance {},
	TUTOR_Title_txt: class extends self.ITextInstance {},
	TUTOR_txt: class extends self.ITextInstance {},
	TUTOR_Particles: class extends self.IParticlesInstance {},
	TUTOR_Enemies: class extends self.ISpriteInstance {},
	Tutor_Lines: class extends self.ISpriteInstance {},
	TUTOR_CandyRainbow: class extends self.ISpriteInstance {},
	TUTOR_Lab: class extends self.ISpriteInstance {},
	TUTOR_Potion: class extends self.ISpriteInstance {},
	TUTOR_Dionea: class extends self.ISpriteInstance {},
	TUTOR_BONUS_Dionea: class extends self.ISpriteInstance {},
	TUTOR_DioneaGlare: class extends self.ISpriteInstance {},
	TUTOR_RetreatCampEngraving: class extends self.ISpriteInstance {},
	TUTOR_EndGame: class extends self.ISpriteInstance {},
	MenuControlBox: class extends self.ISpriteInstance {},
	GameLogoGlareParticle: class extends self.IParticlesInstance {},
	CihLogo: class extends self.ISpriteInstance {},
	EnemyHPbar: class extends self.ISpriteInstance {},
	EnemyHPbarBkg: class extends self.ISpriteInstance {},
	txtEnemyHP: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Field: class extends self.IArrayInstance {},
	FieldUIDs: class extends self.IArrayInstance {},
	EmptyCellsArray: class extends self.IArrayInstance {},
	EmptyCellsUIDsArray: class extends self.IArrayInstance {},
	GamePush: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	TranslationArray: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	TranslationDictionary: class extends self.IDictionaryInstance {},
	IngredientsCostArray: class extends self.IArrayInstance {},
	PotionIngredientsArray: class extends self.IArrayInstance {},
	FlagOffsetArray: class extends self.IArrayInstance {},
	ShamanCandyLinearArray: class extends self.IArrayInstance {},
	ShamanUIDsLinearArray: class extends self.IArrayInstance {},
	Sorcerer_UIDArray: class extends self.IArrayInstance {},
	VideoRecorder: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	WarlockCloakArray: class extends self.IArrayInstance {},
	LeaderboardArray: class extends self.IArrayInstance {},
	LeaderboardDictionary: class extends self.IDictionaryInstance {},
	txtLoadConsole: class extends self.ITextInstance {},
	txtPoints: class extends self.ITextInstance {},
	txtFreeCells: class extends self.ITextInstance {},
	txtPointsText: class extends self.ITextInstance {},
	txtFreeCellsText: class extends self.ITextInstance {},
	txtCoins: class extends self.ITextInstance {},
	txtDebug: class extends self.ITextInstance {},
	txtAdsTimer: class extends self.ITextInstance {},
	txtBonusQty: class extends self.ITextInstance {},
	txtGOPointsEarned: class extends self.ITextInstance {},
	txtGOCoinsEarned: class extends self.ITextInstance {},
	txtButtonLabel: class extends self.ITextInstance {},
	txtIngredients: class extends self.ITextInstance {},
	txtIngredientLabel: class extends self.ITextInstance {},
	txtIngredientPrice: class extends self.ITextInstance {},
	txtVersion: class extends self.ITextInstance {},
	txtCoinsText: class extends self.ITextInstance {},
	txtBonusChestTime: class extends self.ITextInstance {},
	txtBonusChestCoins: class extends self.ITextInstance {},
	txtBonusChestCoinsBkg: class extends self.ITextInstance {},
	txtCastleActivityTimer: class extends self.ITextInstance {},
	txtGOResults: class extends self.ITextInstance {},
	txtGOResultsText: class extends self.ITextInstance {},
	txtCastleActivityBonus: class extends self.ITextInstance {},
	txtCastleActivityBonusBKG: class extends self.ITextInstance {},
	txtRetreatMenuTitle: class extends self.ITextInstance {},
	txtRetreatMenuText: class extends self.ITextInstance {},
	txtShortButtonLabel: class extends self.ITextInstance {},
	txtBonusChestCoinsQty: class extends self.ITextInstance {},
	txtOfferMenuText: class extends self.ITextInstance {},
	txtLeaderboardTitle: class extends self.ITextInstance {},
	txtLeaderboardEntry: class extends self.ITextInstance {},
	txtLeaderboardTitleDescription: class extends self.ITextInstance {},
	CANDIES: class extends self.ISpriteInstance {},
	BONUSES: class extends self.ISpriteInstance {},
	FIREWORK_ROCKETS: class extends self.IParticlesInstance {},
	ENEMIES: class extends self.ISpriteInstance {}
}