const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Dictionary,
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Plugins.gamepad,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Plugins.NinePatch,
		C3.Behaviors.wrap,
		C3.Plugins.Tilemap,
		C3.Behaviors.Flash,
		C3.Behaviors.Platform,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Plugins.WGSDK,
		C3.Behaviors.solid,
		C3.Behaviors.jumpthru,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Exps.VectorY,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Behaviors.Platform.Acts.SetDeceleration,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.viewporttop,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Behaviors.Platform.Exps.JumpStrength,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Spritefont2.Acts.SetHAlign,
		C3.Plugins.Spritefont2.Acts.SetWidth,
		C3.Plugins.Spritefont2.Acts.SetHeight,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Exps.MaxSpeed,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Acts.RestoreObjectTimescale,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.Spritefont2.Cnds.IsOnScreen,
		C3.Plugins.Spritefont2.Exps.Opacity,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Spritefont2.Acts.SetEffectParam,
		C3.Plugins.Spritefont2.Exps.UID,
		C3.Plugins.Spritefont2.Cnds.PickByUID,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.NinePatch.Exps.UID,
		C3.Plugins.NinePatch.Cnds.PickByUID,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.NinePatch.Exps.Height
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{Audio: 0},
	{Mouse: 0},
	{Dictionary: 0},
	{Browser: 0},
	{Menu: 0},
	{Index: 0},
	{Index_Max: 0},
	{Gamepad: 0},
	{Forest_Plant_1: 0},
	{Forest_Plant_2: 0},
	{Sine: 0},
	{Bullet: 0},
	{Leaf: 0},
	{Droplet: 0},
	{Cave_Mushroom_1: 0},
	{Cave_Mushroom_2: 0},
	{Torch: 0},
	{Torch2: 0},
	{Temple_Tile_1: 0},
	{CameraZone: 0},
	{Collectibles: 0},
	{Collisions: 0},
	{JumpThru: 0},
	{Weather_Leaves: 0},
	{Weather_Droplets: 0},
	{Layout_Variables: 0},
	{Water: 0},
	{ID: 0},
	{Door: 0},
	{EndLevel: 0},
	{StartGame: 0},
	{Spring: 0},
	{BG_Forest_0: 0},
	{BG_Forest_1: 0},
	{BG_Cave_0: 0},
	{BG_Cave_1: 0},
	{BG_Temple_0: 0},
	{BG_Forest_2: 0},
	{BG_Temple_1: 0},
	{BG_Forest_4: 0},
	{BG_Temple_2: 0},
	{Wrap: 0},
	{BG_TitleScreen: 0},
	{Logo: 0},
	{EndingSprite: 0},
	{TM_Forest: 0},
	{TM_Cave: 0},
	{TM_Temple: 0},
	{HurtTimer: 0},
	{KnockBackTimer: 0},
	{Flash: 0},
	{Player_Mask: 0},
	{Bounce: 0},
	{Platform: 0},
	{Player_Base: 0},
	{NPC_Kiwi: 0},
	{Health: 0},
	{Shielded: 0},
	{Invincible: 0},
	{Direction: 0},
	{En_Beetle: 0},
	{DeathPit: 0},
	{Spawner_Boulder: 0},
	{En_Acorn: 0},
	{En_Boulder: 0},
	{En_Cannon: 0},
	{En_CannonBall: 0},
	{En_Fish: 0},
	{SpinTimer: 0},
	{En_Hedgehog: 0},
	{En_Spear: 0},
	{En_Spikes: 0},
	{En_Squirrel: 0},
	{En_Stalactite: 0},
	{Spawner_Fish: 0},
	{Type: 0},
	{SpriteFont: 0},
	{HUD_Health: 0},
	{HUD_Beetle: 0},
	{HUD_Font: 0},
	{State: 0},
	{Transition: 0},
	{Light: 0},
	{Rotate: 0},
	{GenericParticle: 0},
	{Darkness: 0},
	{WeeGooSDK: 0},
	{Solid: 0},
	{Jumpthru: 0},
	{Solids: 0},
	{Enemies: 0},
	{Spritefonts: 0},
	{direction: 0},
	{damage: 0},
	{createX: 0},
	{createY: 0},
	{transitionState: 0},
	{doorId: 0},
	{excludeDoorUid: 0},
	{enemyUid: 0},
	{GameStarted: 0},
	{CurrentMenu: 0},
	{MenuLock: 0},
	{CameraZone_UID: 0},
	{spriteFontUid: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	Browser: class extends self.IInstance {},
	Menu: class extends self.ISpriteInstance {},
	Gamepad: class extends self.IInstance {},
	Forest_Plant_1: class extends self.ISpriteInstance {},
	Forest_Plant_2: class extends self.ISpriteInstance {},
	Leaf: class extends self.ISpriteInstance {},
	Droplet: class extends self.ISpriteInstance {},
	Cave_Mushroom_1: class extends self.ISpriteInstance {},
	Cave_Mushroom_2: class extends self.ISpriteInstance {},
	Torch: class extends self.ISpriteInstance {},
	Torch2: class extends self.ISpriteInstance {},
	Temple_Tile_1: class extends self.ISpriteInstance {},
	CameraZone: class extends self.IWorldInstance {},
	Collectibles: class extends self.ISpriteInstance {},
	Collisions: class extends self.ISpriteInstance {},
	JumpThru: class extends self.ISpriteInstance {},
	Layout_Variables: class extends self.ISpriteInstance {},
	Water: class extends self.ISpriteInstance {},
	Door: class extends self.ISpriteInstance {},
	EndLevel: class extends self.ISpriteInstance {},
	StartGame: class extends self.ISpriteInstance {},
	Spring: class extends self.ISpriteInstance {},
	BG_Forest_0: class extends self.ISpriteInstance {},
	BG_Forest_1: class extends self.ISpriteInstance {},
	BG_Cave_0: class extends self.ISpriteInstance {},
	BG_Cave_1: class extends self.ISpriteInstance {},
	BG_Temple_0: class extends self.ISpriteInstance {},
	BG_Forest_2: class extends self.ISpriteInstance {},
	BG_Temple_1: class extends self.ISpriteInstance {},
	BG_Forest_4: class extends self.ISpriteInstance {},
	BG_Temple_2: class extends self.ISpriteInstance {},
	BG_TitleScreen: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	EndingSprite: class extends self.ISpriteInstance {},
	TM_Forest: class extends self.ITilemapInstance {},
	TM_Cave: class extends self.ITilemapInstance {},
	TM_Temple: class extends self.ITilemapInstance {},
	Player_Mask: class extends self.ISpriteInstance {},
	Player_Base: class extends self.ISpriteInstance {},
	NPC_Kiwi: class extends self.ISpriteInstance {},
	En_Beetle: class extends self.ISpriteInstance {},
	DeathPit: class extends self.ITiledBackgroundInstance {},
	Spawner_Boulder: class extends self.ISpriteInstance {},
	En_Acorn: class extends self.ISpriteInstance {},
	En_Boulder: class extends self.ISpriteInstance {},
	En_Cannon: class extends self.ISpriteInstance {},
	En_CannonBall: class extends self.ISpriteInstance {},
	En_Fish: class extends self.ISpriteInstance {},
	En_Hedgehog: class extends self.ISpriteInstance {},
	En_Spear: class extends self.ISpriteInstance {},
	En_Spikes: class extends self.ISpriteInstance {},
	En_Squirrel: class extends self.ISpriteInstance {},
	En_Stalactite: class extends self.ISpriteInstance {},
	Spawner_Fish: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	HUD_Health: class extends self.ISpriteInstance {},
	HUD_Beetle: class extends self.ISpriteInstance {},
	HUD_Font: class extends self.ISpriteFontInstance {},
	Transition: class extends self.ISpriteInstance {},
	Light: class extends self.ISpriteInstance {},
	GenericParticle: class extends self.ISpriteInstance {},
	Darkness: class extends self.ITiledBackgroundInstance {},
	WeeGooSDK: class extends self.IInstance {},
	Solids: class extends self.ISpriteInstance {},
	Enemies: class extends self.ISpriteInstance {},
	Spritefonts: class extends self.ISpriteFontInstance {}
}