const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.Fade,
		C3.Behaviors.scrollto,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Flash,
		C3.Plugins.NinePatch,
		C3.Behaviors.Sin,
		C3.Plugins.gamepad,
		C3.Plugins.Touch,
		C3.Behaviors.Persist,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.video,
		C3.Plugins.SVGPicture,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayoutEffectParam,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.ChangeTags,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Plugins.gamepad.Exps.Axis,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Exps.layoutscale,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Platform.Exps.MaxSpeed,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Spritefont2.Cnds.IsRunningTypewriterText,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Mouse.Exps.AbsoluteX,
		C3.Plugins.Mouse.Exps.AbsoluteY,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.NinePatch.Acts.SetEffectParam,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.ResetPersisted,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.gamepad.Cnds.HasGamepads,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Plugins.Spritefont2.Cnds.OnTypewriterTextFinished,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.video.Acts.SetMuted,
		C3.Plugins.video.Acts.Destroy,
		C3.Plugins.System.Acts.UnloadUnusedTextures,
		C3.Plugins.System.Acts.LoadLayoutTextures,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.WGSDK.Cnds.RewardReady,
		C3.Plugins.WGSDK.Cnds.RewardGranted
	];
};
self.C3_JsPropNameTable = [
	{Room_: 0},
	{Room_10: 0},
	{Room_10_A: 0},
	{Room_10_A2: 0},
	{Room_10_front: 0},
	{Room_11: 0},
	{Room_11_front: 0},
	{Room_12: 0},
	{Room_13_A: 0},
	{Room_13_A2: 0},
	{Room_13_A3: 0},
	{Room_15_A: 0},
	{Room_15_A2: 0},
	{Room_16_A: 0},
	{Room_16_A2: 0},
	{Room_17_A: 0},
	{Room_17_A2: 0},
	{Room_17_front: 0},
	{Room_18_front: 0},
	{Room_19_front: 0},
	{room_1_front: 0},
	{Room_2: 0},
	{Room_20: 0},
	{Room_2_A: 0},
	{Room_2_A2: 0},
	{Room_3: 0},
	{Room_3_A: 0},
	{Room_3_A2: 0},
	{Room_4: 0},
	{Room_5: 0},
	{Room_5_A: 0},
	{Room_5_B: 0},
	{Room_5_front: 0},
	{Room_6: 0},
	{Room_6_front_A: 0},
	{Room_6_front_b: 0},
	{Room_7: 0},
	{Room_8: 0},
	{Room_8_front: 0},
	{Room_9: 0},
	{Room_9_front: 0},
	{room_door: 0},
	{player_legs: 0},
	{isAiming: 0},
	{isRolling: 0},
	{state: 0},
	{isInteracting: 0},
	{isShooting: 0},
	{walkDir: 0},
	{rateo: 0},
	{Damage: 0},
	{stomp: 0},
	{interaction_num: 0},
	{isMenu: 0},
	{isAttacking: 0},
	{Platform: 0},
	{player_Coll: 0},
	{Tween: 0},
	{player_body: 0},
	{Solid: 0},
	{solidColl: 0},
	{player_aimAngle: 0},
	{Keyboard: 0},
	{aim: 0},
	{Mouse: 0},
	{Fade: 0},
	{Muzzle_flare: 0},
	{ScrollTo: 0},
	{camera: 0},
	{Bullet: 0},
	{Rotate: 0},
	{bullet: 0},
	{part_sparks: 0},
	{laserpointer: 0},
	{light: 0},
	{conelight: 0},
	{BG_Prova_: 0},
	{BG_Prova_2: 0},
	{shadow: 0},
	{e_mask_zombie: 0},
	{Audio: 0},
	{HP: 0},
	{attack: 0},
	{hit: 0},
	{e_zombie: 0},
	{e_zombie_view_range: 0},
	{damage: 0},
	{damage_1: 0},
	{e_zombie_attack_mask: 0},
	{ui_bloodscreen: 0},
	{Text: 0},
	{fader: 0},
	{player_death: 0},
	{isPerforante: 0},
	{Power: 0},
	{gunBullet: 0},
	{smoke: 0},
	{part_blood: 0},
	{e_dead_zombie: 0},
	{blood_spot: 0},
	{Array: 0},
	{AJAX: 0},
	{num_interazione_Y: 0},
	{oggetto: 0},
	{Descrizione_A: 0},
	{Descrizione_B: 0},
	{Immagine_A: 0},
	{Immagine_B: 0},
	{interazione: 0},
	{type: 0},
	{array_at_y: 0},
	{Flash: 0},
	{SpriteFont: 0},
	{prova_oggetto: 0},
	{immagini_closeUps: 0},
	{menu_bg: 0},
	{menu_9patch_black2: 0},
	{menu_9patch_black3: 0},
	{menu_9patch_black: 0},
	{Sine: 0},
	{eff_interferenza: 0},
	{Item_icon: 0},
	{isWeapon: 0},
	{info: 0},
	{isAmmo: 0},
	{array_y: 0},
	{item_menu: 0},
	{Gamepad: 0},
	{cursor_pointer3D: 0},
	{SpriteFont_menu: 0},
	{Touch: 0},
	{wep_icon: 0},
	{ui_flash: 0},
	{attack_knife: 0},
	{bloodSpot: 0},
	{KeyA: 0},
	{KeyB: 0},
	{KeyC: 0},
	{KeyD: 0},
	{KeyE: 0},
	{KeyF: 0},
	{PosX: 0},
	{RoomNum: 0},
	{Code1: 0},
	{Code2: 0},
	{Enigma1: 0},
	{Enigma2: 0},
	{IfClosedArray: 0},
	{isCode1Locked: 0},
	{isCode2Locked: 0},
	{isElevator: 0},
	{Floor: 0},
	{isEnigma: 0},
	{audioToPlay: 0},
	{interazione_Door: 0},
	{roomToGo: 0},
	{interazione_Enigmi: 0},
	{prova_tastierino: 0},
	{isGame: 0},
	{Codice: 0},
	{digit1: 0},
	{digit2: 0},
	{digit3: 0},
	{digit4: 0},
	{digitNum: 0},
	{MusicTrack: 0},
	{choice: 0},
	{isQuitting: 0},
	{RoomNumber: 0},
	{gameControl: 0},
	{e_mask_spider: 0},
	{e_dead_spider: 0},
	{e_spider: 0},
	{e_spider_viewrange: 0},
	{e_spider_attack: 0},
	{item_collect: 0},
	{ArrayNum: 0},
	{Persist: 0},
	{item_onscreen: 0},
	{Elevator: 0},
	{pseudoFader: 0},
	{Elevator_Pulsantiera: 0},
	{glow: 0},
	{bg_enigma: 0},
	{Code: 0},
	{Code_glass: 0},
	{Code_2_schermo: 0},
	{opacity_value: 0},
	{btn_yes: 0},
	{btn_no: 0},
	{btn_leave: 0},
	{btn_newgame: 0},
	{btn_loadgame: 0},
	{LocalStorage: 0},
	{Cover: 0},
	{btn_options: 0},
	{btn_quit: 0},
	{Browser: 0},
	{Sprite: 0},
	{Cover_2: 0},
	{btn_sfx: 0},
	{btn_music: 0},
	{btn_fullscreen: 0},
	{btn_mouse_gamepad: 0},
	{btn_back: 0},
	{ui_button: 0},
	{fmvNum: 0},
	{fmv_bar: 0},
	{Video: 0},
	{SpawnerID: 0},
	{creature: 0},
	{Evento: 0},
	{spawner: 0},
	{ui_controls_gamepad: 0},
	{btn_back2: 0},
	{base: 0},
	{PezzoCarne: 0},
	{ui_lifeLine: 0},
	{SpriteFont_m: 0},
	{gameOver: 0},
	{blood_drop: 0},
	{GameOver_Screen: 0},
	{cover_Ball_Red: 0},
	{cover_Dev: 0},
	{TiledBackground: 0},
	{cover_Ti: 0},
	{cover_PI: 0},
	{cover_Ball_blu: 0},
	{pang_fader: 0},
	{ArrayMap: 0},
	{floorMap: 0},
	{mapRoom: 0},
	{isExplored: 0},
	{map_piece: 0},
	{mapDoor: 0},
	{map_piece_completo: 0},
	{ui_controls_gamepad2: 0},
	{download: 0},
	{controls_eng: 0},
	{btn_Rewarded: 0},
	{movie: 0},
	{available_on_steam: 0},
	{itchioBadge: 0},
	{WeeGooSDK: 0},
	{enemies_mask: 0},
	{Enemies: 0},
	{enemy_damage: 0},
	{PlayerBullets: 0},
	{deadBody: 0},
	{PickedUpObjects: 0},
	{Interazioni: 0},
	{Rooms: 0},
	{buttons: 0},
	{FG: 0},
	{Titoli: 0},
	{UIControls: 0},
	{Weapon: 0},
	{ammo_gun: 0},
	{ammo_submachine: 0},
	{ammo_rifle: 0},
	{ammo_shotgun: 0},
	{isSound: 0},
	{hp: 0},
	{hp_max: 0},
	{isPause: 0},
	{isMouse: 0},
	{PlayerPosX: 0},
	{Room: 0},
	{GameFloor: 0},
	{musicTrack: 0},
	{keyA: 0},
	{keyB: 0},
	{keyC: 0},
	{keyD: 0},
	{keyE: 0},
	{keyF: 0},
	{Map1: 0},
	{Map2: 0},
	{Map3: 0},
	{Map4: 0},
	{Map5: 0},
	{machinegun: 0},
	{shotgun: 0},
	{rifle: 0},
	{smallMedikit: 0},
	{medikit: 0},
	{floppy: 0},
	{FMV_1: 0},
	{FMV_2: 0},
	{FMV_3: 0},
	{quest: 0},
	{fmv: 0},
	{GameSaved: 0},
	{isMusic: 0},
	{isFullscreen: 0}
];

self.InstanceType = {
	Room_: class extends self.ISpriteInstance {},
	Room_10: class extends self.ISpriteInstance {},
	Room_10_A: class extends self.ISpriteInstance {},
	Room_10_A2: class extends self.ISpriteInstance {},
	Room_10_front: class extends self.ISpriteInstance {},
	Room_11: class extends self.ISpriteInstance {},
	Room_11_front: class extends self.ISpriteInstance {},
	Room_12: class extends self.ISpriteInstance {},
	Room_13_A: class extends self.ISpriteInstance {},
	Room_13_A2: class extends self.ISpriteInstance {},
	Room_13_A3: class extends self.ISpriteInstance {},
	Room_15_A: class extends self.ISpriteInstance {},
	Room_15_A2: class extends self.ISpriteInstance {},
	Room_16_A: class extends self.ISpriteInstance {},
	Room_16_A2: class extends self.ISpriteInstance {},
	Room_17_A: class extends self.ISpriteInstance {},
	Room_17_A2: class extends self.ISpriteInstance {},
	Room_17_front: class extends self.ISpriteInstance {},
	Room_18_front: class extends self.ISpriteInstance {},
	Room_19_front: class extends self.ISpriteInstance {},
	room_1_front: class extends self.ISpriteInstance {},
	Room_2: class extends self.ISpriteInstance {},
	Room_20: class extends self.ISpriteInstance {},
	Room_2_A: class extends self.ISpriteInstance {},
	Room_2_A2: class extends self.ISpriteInstance {},
	Room_3: class extends self.ISpriteInstance {},
	Room_3_A: class extends self.ISpriteInstance {},
	Room_3_A2: class extends self.ISpriteInstance {},
	Room_4: class extends self.ISpriteInstance {},
	Room_5: class extends self.ISpriteInstance {},
	Room_5_A: class extends self.ISpriteInstance {},
	Room_5_B: class extends self.ISpriteInstance {},
	Room_5_front: class extends self.ISpriteInstance {},
	Room_6: class extends self.ISpriteInstance {},
	Room_6_front_A: class extends self.ISpriteInstance {},
	Room_6_front_b: class extends self.ISpriteInstance {},
	Room_7: class extends self.ISpriteInstance {},
	Room_8: class extends self.ISpriteInstance {},
	Room_8_front: class extends self.ISpriteInstance {},
	Room_9: class extends self.ISpriteInstance {},
	Room_9_front: class extends self.ISpriteInstance {},
	room_door: class extends self.ISpriteInstance {},
	player_legs: class extends self.ISpriteInstance {},
	player_Coll: class extends self.ISpriteInstance {},
	player_body: class extends self.ISpriteInstance {},
	solidColl: class extends self.ITiledBackgroundInstance {},
	player_aimAngle: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	aim: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Muzzle_flare: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	bullet: class extends self.ISpriteInstance {},
	part_sparks: class extends self.IParticlesInstance {},
	laserpointer: class extends self.ISpriteInstance {},
	light: class extends self.ISpriteInstance {},
	conelight: class extends self.ISpriteInstance {},
	BG_Prova_: class extends self.ISpriteInstance {},
	BG_Prova_2: class extends self.ISpriteInstance {},
	shadow: class extends self.ISpriteInstance {},
	e_mask_zombie: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	e_zombie: class extends self.ISpriteInstance {},
	e_zombie_view_range: class extends self.ISpriteInstance {},
	damage_1: class extends self.ISpriteInstance {},
	e_zombie_attack_mask: class extends self.ISpriteInstance {},
	ui_bloodscreen: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	fader: class extends self.ISpriteInstance {},
	player_death: class extends self.ISpriteInstance {},
	gunBullet: class extends self.ISpriteInstance {},
	smoke: class extends self.ISpriteInstance {},
	part_blood: class extends self.IParticlesInstance {},
	e_dead_zombie: class extends self.ISpriteInstance {},
	blood_spot: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	interazione: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	prova_oggetto: class extends self.ISpriteInstance {},
	immagini_closeUps: class extends self.ISpriteInstance {},
	menu_bg: class extends self.ISpriteInstance {},
	menu_9patch_black2: class extends self.IWorldInstance {},
	menu_9patch_black3: class extends self.IWorldInstance {},
	menu_9patch_black: class extends self.IWorldInstance {},
	eff_interferenza: class extends self.ISpriteInstance {},
	Item_icon: class extends self.ISpriteInstance {},
	item_menu: class extends self.ISpriteInstance {},
	Gamepad: class extends self.IInstance {},
	cursor_pointer3D: class extends self.ISpriteInstance {},
	SpriteFont_menu: class extends self.ISpriteFontInstance {},
	Touch: class extends self.IInstance {},
	wep_icon: class extends self.ISpriteInstance {},
	ui_flash: class extends self.ISpriteInstance {},
	attack_knife: class extends self.ISpriteInstance {},
	bloodSpot: class extends self.ISpriteInstance {},
	interazione_Door: class extends self.ISpriteInstance {},
	interazione_Enigmi: class extends self.ISpriteInstance {},
	prova_tastierino: class extends self.ISpriteInstance {},
	gameControl: class extends self.ISpriteInstance {},
	e_mask_spider: class extends self.ISpriteInstance {},
	e_dead_spider: class extends self.ISpriteInstance {},
	e_spider: class extends self.ISpriteInstance {},
	e_spider_viewrange: class extends self.ISpriteInstance {},
	e_spider_attack: class extends self.ISpriteInstance {},
	item_collect: class extends self.ISpriteInstance {},
	item_onscreen: class extends self.ISpriteInstance {},
	Elevator: class extends self.ISpriteInstance {},
	pseudoFader: class extends self.ITiledBackgroundInstance {},
	Elevator_Pulsantiera: class extends self.ISpriteInstance {},
	glow: class extends self.ISpriteInstance {},
	bg_enigma: class extends self.ISpriteInstance {},
	Code: class extends self.ISpriteInstance {},
	Code_glass: class extends self.ISpriteInstance {},
	Code_2_schermo: class extends self.ISpriteInstance {},
	btn_yes: class extends self.ISpriteInstance {},
	btn_no: class extends self.ISpriteInstance {},
	btn_leave: class extends self.ISpriteInstance {},
	btn_newgame: class extends self.ISpriteInstance {},
	btn_loadgame: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Cover: class extends self.ISpriteInstance {},
	btn_options: class extends self.ISpriteInstance {},
	btn_quit: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Cover_2: class extends self.ISpriteInstance {},
	btn_sfx: class extends self.ISpriteInstance {},
	btn_music: class extends self.ISpriteInstance {},
	btn_fullscreen: class extends self.ISpriteInstance {},
	btn_mouse_gamepad: class extends self.ISpriteInstance {},
	btn_back: class extends self.ISpriteInstance {},
	ui_button: class extends self.ISpriteInstance {},
	fmv_bar: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	spawner: class extends self.ISpriteInstance {},
	ui_controls_gamepad: class extends self.ISpriteInstance {},
	btn_back2: class extends self.ISpriteInstance {},
	base: class extends self.ISpriteInstance {},
	PezzoCarne: class extends self.ISpriteInstance {},
	ui_lifeLine: class extends self.ISpriteInstance {},
	SpriteFont_m: class extends self.ISpriteFontInstance {},
	gameOver: class extends self.ITiledBackgroundInstance {},
	blood_drop: class extends self.ISpriteInstance {},
	GameOver_Screen: class extends self.ISpriteInstance {},
	cover_Ball_Red: class extends self.ISpriteInstance {},
	cover_Dev: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	cover_Ti: class extends self.ISpriteInstance {},
	cover_PI: class extends self.ISpriteInstance {},
	cover_Ball_blu: class extends self.ISpriteInstance {},
	pang_fader: class extends self.ITiledBackgroundInstance {},
	ArrayMap: class extends self.IArrayInstance {},
	map_piece: class extends self.ISpriteInstance {},
	mapDoor: class extends self.ISpriteInstance {},
	map_piece_completo: class extends self.ISpriteInstance {},
	ui_controls_gamepad2: class extends self.ISpriteInstance {},
	download: class extends self.ISpriteInstance {},
	controls_eng: class extends self.ISpriteInstance {},
	btn_Rewarded: class extends self.ISpriteInstance {},
	movie: class extends self.ISpriteInstance {},
	available_on_steam: class extends self.ISpriteInstance {},
	itchioBadge: class extends self.ISVGPictureInstance {},
	WeeGooSDK: class extends self.IInstance {},
	enemies_mask: class extends self.ISpriteInstance {},
	Enemies: class extends self.ISpriteInstance {},
	enemy_damage: class extends self.ISpriteInstance {},
	PlayerBullets: class extends self.ISpriteInstance {},
	deadBody: class extends self.ISpriteInstance {},
	PickedUpObjects: class extends self.ISpriteInstance {},
	Interazioni: class extends self.ISpriteInstance {},
	Rooms: class extends self.ISpriteInstance {},
	buttons: class extends self.ISpriteInstance {},
	FG: class extends self.ISpriteInstance {},
	Titoli: class extends self.ISpriteInstance {},
	UIControls: class extends self.ISpriteInstance {}
}