const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Browser,
		C3.Plugins.gamepad,
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Behaviors.Platform,
		C3.Behaviors.EightDir,
		C3.Behaviors.Bullet,
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.LOS,
		C3.Behaviors.Sin,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Behaviors.Platform.Cnds.IsEnabled,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.TiledBg.Cnds.OnCreated,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Behaviors.LOS.Acts.CastRay,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Behaviors.LOS.Exps.Range,
		C3.Behaviors.LOS.Cnds.RayIntersected,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.LOS.Exps.HitDistance,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.EightDir.Cnds.IsEnabled,
		C3.Plugins.System.Exps.anglelerp,
		C3.Behaviors.EightDir.Acts.SetVectorX,
		C3.Behaviors.EightDir.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.Browser.Acts.Close
	];
};
self.C3_JsPropNameTable = [
	{Browser: 0},
	{Gamepad: 0},
	{Keyboard: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{Tween: 0},
	{Timer: 0},
	{GameManager: 0},
	{Fade: 0},
	{TextFont: 0},
	{JumpingDust: 0},
	{LandingDust: 0},
	{LastX: 0},
	{LastY: 0},
	{Platform: 0},
	{"8Direction": 0},
	{PlayerCollision: 0},
	{PlayerGraphics: 0},
	{SmallExplosion: 0},
	{WalkingDust: 0},
	{BigFlash: 0},
	{Bullet: 0},
	{Spark: 0},
	{TrailMask: 0},
	{Background: 0},
	{Solid: 0},
	{Ground: 0},
	{LinePattern: 0},
	{LineOfSight: 0},
	{Flash: 0},
	{Spike: 0},
	{TeleportPlatformFront: 0},
	{Charged: 0},
	{TeleportTrigger: 0},
	{TeleportPlatformBack: 0},
	{Sine: 0},
	{MagicFeather: 0},
	{MagicFeatherBubble: 0},
	{WeeGooSDK: 0},
	{GAMEPADDEADZONE: 0},
	{TARGETFRAMERATE: 0},
	{DEFAULTLAYOUTSCALE: 0},
	{InputLeft: 0},
	{InputRight: 0},
	{InputUp: 0},
	{InputDown: 0},
	{HorizontalAxis: 0},
	{VerticalAxis: 0},
	{AxisAngle: 0},
	{CAMERASPEED: 0},
	{CAMERAOFFSETX: 0},
	{CAMERAOFFSETY: 0},
	{Intensity: 0},
	{Duration: 0},
	{LerpedAngle: 0},
	{FlightModeSpeed: 0},
	{FLIGHTMODEDURATION: 0},
	{PositionX: 0},
	{PositionY: 0},
	{DirectionAngle: 0}
];

self.InstanceType = {
	Browser: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Camera: class extends self.ISpriteInstance {},
	GameManager: class extends self.ISpriteInstance {},
	TextFont: class extends self.ISpriteFontInstance {},
	JumpingDust: class extends self.ISpriteInstance {},
	LandingDust: class extends self.ISpriteInstance {},
	PlayerCollision: class extends self.ISpriteInstance {},
	PlayerGraphics: class extends self.ISpriteInstance {},
	SmallExplosion: class extends self.ISpriteInstance {},
	WalkingDust: class extends self.ISpriteInstance {},
	BigFlash: class extends self.ISpriteInstance {},
	Spark: class extends self.ISpriteInstance {},
	TrailMask: class extends self.ISpriteInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	Ground: class extends self.ITilemapInstance {},
	LinePattern: class extends self.ITiledBackgroundInstance {},
	Flash: class extends self.ITiledBackgroundInstance {},
	Spike: class extends self.ISpriteInstance {},
	TeleportPlatformFront: class extends self.ISpriteInstance {},
	TeleportTrigger: class extends self.ISpriteInstance {},
	TeleportPlatformBack: class extends self.ISpriteInstance {},
	MagicFeather: class extends self.ISpriteInstance {},
	MagicFeatherBubble: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {}
}