const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Behaviors.DragnDrop,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Plugins.WGSDK,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.time,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.LocalStorage.Cnds.OnAllGetsComplete,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.GoToLayoutByName
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sprite2: 0},
	{Sine: 0},
	{play: 0},
	{more: 0},
	{home: 0},
	{Sprite6: 0},
	{difference: 0},
	{ScoreTextt: 0},
	{Touch: 0},
	{Sprite7: 0},
	{sesir: 0},
	{hat: 0},
	{krug: 0},
	{Browser: 0},
	{vatromet: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Mouse: 0},
	{Sprite5: 0},
	{Sprite8: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Tween: 0},
	{zavjesa: 0},
	{Pin: 0},
	{dalje: 0},
	{igrice: 0},
	{Sprite19: 0},
	{zvijezde: 0},
	{Fireworks1: 0},
	{Fireworks2: 0},
	{Fireworks5: 0},
	{Fireworks6: 0},
	{Fireworks4: 0},
	{Fireworks3: 0},
	{menu: 0},
	{welldone: 0},
	{difference2: 0},
	{Audio: 0},
	{BG_Table: 0},
	{BSound: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite24: 0},
	{Sprite26: 0},
	{DragDrop: 0},
	{loopa: 0},
	{tacka: 0},
	{b: 0},
	{b2: 0},
	{difference3: 0},
	{difference4: 0},
	{b3: 0},
	{staklo: 0},
	{c3: 0},
	{c2: 0},
	{c1: 0},
	{d1: 0},
	{d2: 0},
	{d3: 0},
	{e1: 0},
	{e2: 0},
	{e3: 0},
	{Timer: 0},
	{SpriteFont123: 0},
	{Particles: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{level1: 0},
	{level2: 0},
	{level3: 0},
	{level4: 0},
	{level5: 0},
	{Sprite32: 0},
	{dalje2: 0},
	{Sprite18: 0},
	{ruka: 0},
	{Open: 0},
	{Level: 0},
	{LevelsBlock: 0},
	{LocalStorage: 0},
	{brojevi: 0},
	{LevelsText: 0},
	{loopa2: 0},
	{Sprite33: 0},
	{home2: 0},
	{Sprite23: 0},
	{Sprite25: 0},
	{Sprite34: 0},
	{pozadina: 0},
	{Sprite35: 0},
	{Confetti: 0},
	{WeeGooSDK: 0},
	{buttons: 0},
	{LAST_LEVEL: 0},
	{WIN: 0},
	{LevelComplete: 0},
	{Score: 0},
	{TIMERWIDTH: 0},
	{Highscore: 0},
	{sound: 0},
	{SoundEf: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	more: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	difference: class extends self.ISpriteInstance {},
	ScoreTextt: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	hat: class extends self.ISpriteInstance {},
	krug: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	vatromet: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	zavjesa: class extends self.ISpriteInstance {},
	dalje: class extends self.ISpriteInstance {},
	igrice: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	zvijezde: class extends self.ISpriteInstance {},
	Fireworks1: class extends self.IParticlesInstance {},
	Fireworks2: class extends self.IParticlesInstance {},
	Fireworks5: class extends self.IParticlesInstance {},
	Fireworks6: class extends self.IParticlesInstance {},
	Fireworks4: class extends self.IParticlesInstance {},
	Fireworks3: class extends self.IParticlesInstance {},
	menu: class extends self.ISpriteInstance {},
	welldone: class extends self.ISpriteInstance {},
	difference2: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	BG_Table: class extends self.ISpriteInstance {},
	BSound: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	loopa: class extends self.ISpriteInstance {},
	tacka: class extends self.ISpriteInstance {},
	b: class extends self.ISpriteInstance {},
	b2: class extends self.ISpriteInstance {},
	difference3: class extends self.ISpriteInstance {},
	difference4: class extends self.ISpriteInstance {},
	b3: class extends self.ISpriteInstance {},
	staklo: class extends self.ISpriteInstance {},
	c3: class extends self.ISpriteInstance {},
	c2: class extends self.ISpriteInstance {},
	c1: class extends self.ISpriteInstance {},
	d1: class extends self.ISpriteInstance {},
	d2: class extends self.ISpriteInstance {},
	d3: class extends self.ISpriteInstance {},
	e1: class extends self.ISpriteInstance {},
	e2: class extends self.ISpriteInstance {},
	e3: class extends self.ISpriteInstance {},
	Timer: class extends self.ITiledBackgroundInstance {},
	SpriteFont123: class extends self.ISpriteFontInstance {},
	Particles: class extends self.IParticlesInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	level1: class extends self.ISpriteInstance {},
	level2: class extends self.ISpriteInstance {},
	level3: class extends self.ISpriteInstance {},
	level4: class extends self.ISpriteInstance {},
	level5: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	dalje2: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	ruka: class extends self.ISpriteInstance {},
	LevelsBlock: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	brojevi: class extends self.ISpriteFontInstance {},
	LevelsText: class extends self.ISpriteFontInstance {},
	loopa2: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	home2: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	pozadina: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Confetti: class extends self.IParticlesInstance {},
	WeeGooSDK: class extends C3.Plugins.WGSDK.Instance {},
	buttons: class extends self.ISpriteInstance {}
}