const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Behaviors.Timer,
		C3.Behaviors.scrollto,
		C3.Plugins.Text,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.AdvancedRandom.Acts.CreatePermutationTable,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.AdvancedRandom.Exps.Permutation,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToBottom
	];
};
self.C3_JsPropNameTable = [
	{Index: 0},
	{PreviousX: 0},
	{PreviousY: 0},
	{HasTheBall: 0},
	{Tween: 0},
	{Cup: 0},
	{CupShadow: 0},
	{AdvancedRandom: 0},
	{Touch: 0},
	{Keyboard: 0},
	{Ball: 0},
	{Timer: 0},
	{ScrollTo: 0},
	{GameManager: 0},
	{ID: 0},
	{DefaultY: 0},
	{IsShadow: 0},
	{Text: 0},
	{Blast: 0},
	{WeeGooSDK: 0},
	{AllowPlayerInput: 0},
	{IsFirstInteraction: 0},
	{SHADOWPROJECTIONANGLE: 0},
	{SHADOWPROJECTIONDISTANCE: 0},
	{TotalMoves: 0},
	{RemainingMoves: 0},
	{Score: 0},
	{NormalizedDifficulty: 0},
	{ROUNDSUNTILMAXDIFFICULTY: 0},
	{EASYDIVIDER: 0},
	{HARDDIVIDER: 0},
	{CheckCupByIndex: 0},
	{FirstCupX: 0},
	{SecondCupX: 0},
	{DistanceBetweenCups: 0},
	{CupIndex: 0},
	{TextID: 0}
];

self.InstanceType = {
	Cup: class extends self.ISpriteInstance {},
	CupShadow: class extends self.ISpriteInstance {},
	AdvancedRandom: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Ball: class extends self.ISpriteInstance {},
	GameManager: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Blast: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {}
}