const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.custom,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Tween,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Plugins.Touch,
		C3.Behaviors.Fade,
		C3.Behaviors.Bullet,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Rotate,
		C3.Behaviors.scrollto,
		C3.Behaviors.MoveTo,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.TiledBg.Acts.SetEffectParam,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.custom.Acts.SetSpeed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.WGSDK.Cnds.RewardGranted,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.WGSDK.Cnds.RewardReady,
		C3.Behaviors.Fade.Acts.StartFade
	];
};
self.C3_JsPropNameTable = [
	{percentage: 0},
	{Custom: 0},
	{Monster_Head_down: 0},
	{Sine: 0},
	{Monster_body: 0},
	{Monster_Head_up: 0},
	{bg_base: 0},
	{bg_1: 0},
	{Solid: 0},
	{tg: 0},
	{bg_2: 0},
	{bg_3: 0},
	{gameSpeed: 0},
	{distance: 0},
	{timer: 0},
	{isGame: 0},
	{IsGameOver: 0},
	{isWin: 0},
	{spawningTime: 0},
	{isSelected: 0},
	{LevelToUnlock: 0},
	{hsl: 0},
	{gameControl: 0},
	{hp: 0},
	{Tween: 0},
	{Platform: 0},
	{Flash: 0},
	{Player: 0},
	{fg: 0},
	{Touch: 0},
	{ui_ico_player: 0},
	{ui_bar: 0},
	{ui_blackBG: 0},
	{ui_barfiller: 0},
	{tg_up: 0},
	{Fade: 0},
	{Bullet: 0},
	{Player_shadow: 0},
	{LocalStorage: 0},
	{Rotate: 0},
	{Dead_bird: 0},
	{ScrollTo: 0},
	{MoveTo: 0},
	{camera: 0},
	{flash: 0},
	{ui_LevelComplete: 0},
	{ui_GameOver: 0},
	{btn_next: 0},
	{btn_menu: 0},
	{btn_retry: 0},
	{btn_reward: 0},
	{ui_SkipLevel: 0},
	{darkner: 0},
	{btn_play: 0},
	{flag: 0},
	{Array: 0},
	{AJAX: 0},
	{MonsterDistance: 0},
	{HSLcolor: 0},
	{SpawningTIme: 0},
	{anim: 0},
	{level: 0},
	{locked: 0},
	{btn_level: 0},
	{SpriteFont: 0},
	{Title_Fly: 0},
	{Title_Fly2: 0},
	{Title_Fly3: 0},
	{Fader: 0},
	{ui_level_select: 0},
	{btn_right: 0},
	{btn_Left: 0},
	{ui_lev: 0},
	{SpriteFontLev: 0},
	{ui_LevelComplete_shadow: 0},
	{ui_hp_full: 0},
	{ui_hp_empty: 0},
	{hpUp: 0},
	{ui_youCompletedTheGame: 0},
	{ui_Congratulations: 0},
	{icon_touch: 0},
	{Audio: 0},
	{Keyboard: 0},
	{btn_sound: 0},
	{bg_black: 0},
	{cover_PI: 0},
	{cover_Dev: 0},
	{cover_Ti: 0},
	{cover_Ball_Red: 0},
	{cover_Ball_blu: 0},
	{WeeGooSDK: 0},
	{Sfondi: 0},
	{Monster: 0},
	{uis: 0},
	{Buttons: 0},
	{TileBG: 0},
	{Logos: 0},
	{CoverScreen: 0},
	{Cover: 0},
	{GameSpeed: 0},
	{Timer: 0},
	{SpawningTime: 0},
	{MonsterAnim: 0},
	{Levels: 0},
	{HSLColor: 0},
	{isSound: 0}
];

self.InstanceType = {
	Monster_Head_down: class extends self.ISpriteInstance {},
	Monster_body: class extends self.ISpriteInstance {},
	Monster_Head_up: class extends self.ISpriteInstance {},
	bg_base: class extends self.ISpriteInstance {},
	bg_1: class extends self.ISpriteInstance {},
	tg: class extends self.ITiledBackgroundInstance {},
	bg_2: class extends self.ISpriteInstance {},
	bg_3: class extends self.ISpriteInstance {},
	gameControl: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	fg: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	ui_ico_player: class extends self.ISpriteInstance {},
	ui_bar: class extends self.ISpriteInstance {},
	ui_blackBG: class extends self.ITiledBackgroundInstance {},
	ui_barfiller: class extends self.ISpriteInstance {},
	tg_up: class extends self.ITiledBackgroundInstance {},
	Player_shadow: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Dead_bird: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	flash: class extends self.ISpriteInstance {},
	ui_LevelComplete: class extends self.ISpriteInstance {},
	ui_GameOver: class extends self.ISpriteInstance {},
	btn_next: class extends self.ISpriteInstance {},
	btn_menu: class extends self.ISpriteInstance {},
	btn_retry: class extends self.ISpriteInstance {},
	btn_reward: class extends self.ISpriteInstance {},
	ui_SkipLevel: class extends self.ISpriteInstance {},
	darkner: class extends self.ISpriteInstance {},
	btn_play: class extends self.ISpriteInstance {},
	flag: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	btn_level: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Title_Fly: class extends self.ISpriteInstance {},
	Title_Fly2: class extends self.ISpriteInstance {},
	Title_Fly3: class extends self.ISpriteInstance {},
	Fader: class extends self.ISpriteInstance {},
	ui_level_select: class extends self.ISpriteInstance {},
	btn_right: class extends self.ISpriteInstance {},
	btn_Left: class extends self.ISpriteInstance {},
	ui_lev: class extends self.ISpriteInstance {},
	SpriteFontLev: class extends self.ISpriteFontInstance {},
	ui_LevelComplete_shadow: class extends self.ISpriteInstance {},
	ui_hp_full: class extends self.ITiledBackgroundInstance {},
	ui_hp_empty: class extends self.ITiledBackgroundInstance {},
	hpUp: class extends self.ISpriteInstance {},
	ui_youCompletedTheGame: class extends self.ISpriteInstance {},
	ui_Congratulations: class extends self.ISpriteInstance {},
	icon_touch: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	btn_sound: class extends self.ISpriteInstance {},
	bg_black: class extends self.ITiledBackgroundInstance {},
	cover_PI: class extends self.ISpriteInstance {},
	cover_Dev: class extends self.ISpriteInstance {},
	cover_Ti: class extends self.ISpriteInstance {},
	cover_Ball_Red: class extends self.ISpriteInstance {},
	cover_Ball_blu: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	Sfondi: class extends self.ISpriteInstance {},
	Monster: class extends self.ISpriteInstance {},
	uis: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	TileBG: class extends self.ITiledBackgroundInstance {},
	Logos: class extends self.ISpriteInstance {},
	CoverScreen: class extends self.ISpriteInstance {},
	Cover: class extends self.ISpriteInstance {}
}