const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Camera3D,
		C3.Plugins.Shape3D,
		C3.Behaviors.Timer,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Plugins.NinePatch,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Flash,
		C3.Plugins.gamepad,
		C3.Plugins.LocalStorage,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Behaviors.Pin,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Behaviors.Rotate,
		C3.Plugins.WGSDK,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.System.Exps.random,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Shape3D.Exps.Angle,
		C3.Plugins.Shape3D.Acts.SetPos,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.gamepad.Cnds.OnButtonUp,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Shape3D.Cnds.IsOverlapping,
		C3.Plugins.Shape3D.Acts.SetOpacity,
		C3.Plugins.Shape3D.Cnds.OnCollision,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.NinePatch.Exps.BBoxLeft,
		C3.Plugins.NinePatch.Exps.BBoxRight,
		C3.Plugins.NinePatch.Exps.BBoxTop,
		C3.Plugins.NinePatch.Exps.BBoxBottom,
		C3.Plugins.System.Acts.StopLoop,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.Shape3D.Exps.ZHeight,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Shape3D.Acts.SetFaceObject,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Shape3D.Acts.SetTowardPosition,
		C3.Plugins.Camera3D.Exps.CameraX,
		C3.Plugins.Camera3D.Exps.CameraY,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.Camera3D.Exps.CameraZ,
		C3.Plugins.Camera3D.Exps.LookX,
		C3.Plugins.Camera3D.Exps.LookY,
		C3.Plugins.Camera3D.Exps.LookZ,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.LocalStorage.Cnds.OnAllGetsComplete,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Mouse.Acts.ReleasePointerLock,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Text.Acts.SetPos
	];
};
self.C3_JsPropNameTable = [
	{"3DCamera": 0},
	{Timer: 0},
	{Tween: 0},
	{PlayerModel: 0},
	{LightGrass: 0},
	{BallModel: 0},
	{HoleModel: 0},
	{Keyboard: 0},
	{PowerBarCover: 0},
	{BallShadow: 0},
	{Fade: 0},
	{PlayerTexture: 0},
	{WaterPuddle: 0},
	{WaterSplashModel: 0},
	{SkyboxModel: 0},
	{TreeModel: 0},
	{WaterSplashTexture: 0},
	{WindDirection: 0},
	{Flash: 0},
	{Text: 0},
	{WindDirectionFrame: 0},
	{PowerBarColors: 0},
	{PowerBarFrame: 0},
	{DarkGrass: 0},
	{FlagTexture: 0},
	{Controls: 0},
	{Gamepad: 0},
	{PlayerTexture2: 0},
	{Wall01: 0},
	{granica: 0},
	{LocalStorage: 0},
	{HighScoreText: 0},
	{HoleModel2: 0},
	{Solid: 0},
	{Wall2: 0},
	{Sprite: 0},
	{Sine: 0},
	{play: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Touch: 0},
	{Noise: 0},
	{MoreGames: 0},
	{Browser: 0},
	{BSound: 0},
	{menu: 0},
	{lijevo: 0},
	{desno: 0},
	{shoot: 0},
	{kameranazad: 0},
	{Sprite2: 0},
	{dalje: 0},
	{more: 0},
	{menu2: 0},
	{levelitext: 0},
	{Pokusaja: 0},
	{Sprite5: 0},
	{Sprite26: 0},
	{Sprite23: 0},
	{levelselect: 0},
	{Sprite24: 0},
	{Open: 0},
	{Level: 0},
	{LevelsBlock: 0},
	{slovazalevele: 0},
	{Pin: 0},
	{SpriteFont123: 0},
	{Sprite6: 0},
	{Mouse: 0},
	{outofmoves: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Audio: 0},
	{vatromet: 0},
	{a: 0},
	{Wheel: 0},
	{zavrti: 0},
	{playzawheels: 0},
	{zavrtisareklamama: 0},
	{addmetakreklama: 0},
	{StarsFont4: 0},
	{zavrti3: 0},
	{ruke: 0},
	{metci: 0},
	{StarsFont2: 0},
	{krug: 0},
	{zavrti2: 0},
	{zavrti4: 0},
	{wheels: 0},
	{Sprite13: 0},
	{Textzawheels: 0},
	{santa: 0},
	{kapa: 0},
	{Rotate: 0},
	{coin3d: 0},
	{home: 0},
	{WeeGooSDK: 0},
	{zid: 0},
	{HighScore: 0},
	{Score1: 0},
	{Score: 0},
	{Metci: 0},
	{GameState: 0},
	{sound: 0},
	{SoundEf: 0},
	{unlocks: 0},
	{LAST_LEVEL: 0},
	{WIN: 0},
	{sound2: 0},
	{SoundEf2: 0},
	{RandomAngle: 0},
	{RandomDistance: 0},
	{POWERBARLENGTH: 0},
	{AimingAngle: 0},
	{HitStrength: 0},
	{TurningSpeed: 0},
	{MINTURNINGSPEED: 0},
	{MAXTURNINGSPEED: 0},
	{ACCELERATIONSPEED: 0},
	{BallVectorX: 0},
	{BallVectorY: 0},
	{BallVectorZ: 0},
	{WINDSTRENGTH: 0},
	{IsOutOfBounds: 0},
	{IsOnWater: 0},
	{AngleBetweenPlayerAndBall: 0},
	{IgnoreInterpolation: 0},
	{Direction: 0},
	{CurrentValue: 0},
	{TargetValue: 0},
	{Speed: 0},
	{sectorCount: 0},
	{prizes: 0},
	{Stars: 0},
	{winningSector: 0}
];

self.InstanceType = {
	_3DCamera: class extends self.IInstance {},
	PlayerModel: class extends self.I3DShapeInstance {},
	LightGrass: class extends self.ITiledBackgroundInstance {},
	BallModel: class extends self.I3DShapeInstance {},
	HoleModel: class extends self.I3DShapeInstance {},
	Keyboard: class extends self.IInstance {},
	PowerBarCover: class extends self.ITiledBackgroundInstance {},
	BallShadow: class extends self.ISpriteInstance {},
	Fade: class extends self.ITiledBackgroundInstance {},
	PlayerTexture: class extends self.ISpriteInstance {},
	WaterPuddle: class extends self.IWorldInstance {},
	WaterSplashModel: class extends self.I3DShapeInstance {},
	SkyboxModel: class extends self.I3DShapeInstance {},
	TreeModel: class extends self.I3DShapeInstance {},
	WaterSplashTexture: class extends self.ISpriteInstance {},
	WindDirection: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ISpriteFontInstance {},
	WindDirectionFrame: class extends self.ISpriteInstance {},
	PowerBarColors: class extends self.ISpriteInstance {},
	PowerBarFrame: class extends self.ISpriteInstance {},
	DarkGrass: class extends self.ITiledBackgroundInstance {},
	FlagTexture: class extends self.ISpriteInstance {},
	Controls: class extends self.ISpriteInstance {},
	Gamepad: class extends self.IInstance {},
	PlayerTexture2: class extends self.ISpriteInstance {},
	Wall01: class extends self.I3DShapeInstance {},
	granica: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	HighScoreText: class extends self.ISpriteFontInstance {},
	HoleModel2: class extends self.I3DShapeInstance {},
	Wall2: class extends self.I3DShapeInstance {},
	Sprite: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Noise: class extends self.ITiledBackgroundInstance {},
	MoreGames: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	BSound: class extends self.ISpriteInstance {},
	menu: class extends self.ISpriteInstance {},
	lijevo: class extends self.ISpriteInstance {},
	desno: class extends self.ISpriteInstance {},
	shoot: class extends self.ISpriteInstance {},
	kameranazad: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	dalje: class extends self.ISpriteInstance {},
	more: class extends self.ISpriteInstance {},
	menu2: class extends self.ISpriteInstance {},
	levelitext: class extends self.ISpriteFontInstance {},
	Pokusaja: class extends self.ISpriteFontInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	levelselect: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	LevelsBlock: class extends self.ISpriteInstance {},
	slovazalevele: class extends self.ISpriteFontInstance {},
	SpriteFont123: class extends self.ISpriteFontInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	outofmoves: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	vatromet: class extends self.ISpriteInstance {},
	Wheel: class extends self.ISpriteInstance {},
	zavrti: class extends self.ISpriteInstance {},
	playzawheels: class extends self.ISpriteInstance {},
	zavrtisareklamama: class extends self.ISpriteInstance {},
	addmetakreklama: class extends self.ISpriteInstance {},
	StarsFont4: class extends self.ITextInstance {},
	zavrti3: class extends self.ISpriteInstance {},
	ruke: class extends self.ISpriteFontInstance {},
	metci: class extends self.ITextInstance {},
	StarsFont2: class extends self.ITextInstance {},
	krug: class extends self.ISpriteInstance {},
	Pin: class extends self.ISpriteInstance {},
	zavrti2: class extends self.ISpriteInstance {},
	zavrti4: class extends self.ISpriteInstance {},
	wheels: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Textzawheels: class extends self.ITextInstance {},
	santa: class extends self.ISpriteInstance {},
	kapa: class extends self.ISpriteInstance {},
	coin3d: class extends self.I3DShapeInstance {},
	home: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	zid: class extends self.I3DShapeInstance {}
}