const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Pin,
		C3.Behaviors.scrollto,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Touch,
		C3.Plugins.ppstudio_ga4,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.ppstudio_ga4.Acts.InitGA,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.ppstudio_ga4.Acts.GASendEvent,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.SetRotateSpeed,
		C3.Behaviors.MoveTo.Acts.SetMovingAngle,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Arr.Exps.At,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Plugins.System.Cnds.OnLoadFailed
	];
};
self.C3_JsPropNameTable = [
	{close: 0},
	{music: 0},
	{Anchor: 0},
	{settings: 0},
	{sound: 0},
	{VCArtboard4: 0},
	{VCArtboard3: 0},
	{play: 0},
	{Sine: 0},
	{VCArtboard2: 0},
	{VCArtboard11: 0},
	{conBtn: 0},
	{Tween: 0},
	{forConsonant: 0},
	{forVowel: 0},
	{Xaxis: 0},
	{Yaxis: 0},
	{DragDrop: 0},
	{MoveTo: 0},
	{Pin: 0},
	{obj: 0},
	{isOccupied: 0},
	{place: 0},
	{VCArtboard7: 0},
	{VCArtboard8: 0},
	{vwlBtn: 0},
	{life: 0},
	{next: 0},
	{ScrollTo: 0},
	{shake: 0},
	{VCArtboard107_2: 0},
	{VCArtboard10_: 0},
	{VCArtboard12: 0},
	{home: 0},
	{retry: 0},
	{Rotate: 0},
	{Sine2: 0},
	{Confetti: 0},
	{Particles: 0},
	{VCArtboard10: 0},
	{VCArtboard121_: 0},
	{VCArtboard9: 0},
	{VCArtboard: 0},
	{VCArtboard5: 0},
	{VCArtboard6: 0},
	{coin: 0},
	{levelText: 0},
	{timeLeft: 0},
	{levelNo: 0},
	{levelSelect: 0},
	{lockedNo: 0},
	{locked: 0},
	{sort: 0},
	{allAlphabets: 0},
	{forX: 0},
	{forY: 0},
	{spUID: 0},
	{Audio: 0},
	{Browser: 0},
	{PlatformInfo: 0},
	{Touch: 0},
	{GA4: 0},
	{WeeGooSDK: 0},
	{titleAsset: 0},
	{sortPlaying: 0},
	{findPlaying: 0},
	{timeRemaning: 0},
	{frame: 0},
	{objArrayIndex: 0},
	{totalMovedAlphabets: 0},
	{vowelMoved: 0},
	{consonantMoved: 0},
	{levelsUnlocked: 0},
	{letter: 0},
	{correct: 0},
	{highScore: 0}
];

self.InstanceType = {
	close: class extends self.ISpriteInstance {},
	music: class extends self.ISpriteInstance {},
	settings: class extends self.ISpriteInstance {},
	sound: class extends self.ISpriteInstance {},
	VCArtboard4: class extends self.ISpriteInstance {},
	VCArtboard3: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	VCArtboard2: class extends self.ISpriteInstance {},
	VCArtboard11: class extends self.ISpriteInstance {},
	conBtn: class extends self.ISpriteInstance {},
	forConsonant: class extends self.ISpriteInstance {},
	forVowel: class extends self.ISpriteInstance {},
	obj: class extends self.ISpriteInstance {},
	place: class extends self.ISpriteInstance {},
	VCArtboard7: class extends self.ISpriteInstance {},
	VCArtboard8: class extends self.ISpriteInstance {},
	vwlBtn: class extends self.ISpriteInstance {},
	life: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	shake: class extends self.ISpriteInstance {},
	VCArtboard107_2: class extends self.ISpriteInstance {},
	VCArtboard10_: class extends self.ISpriteInstance {},
	VCArtboard12: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	retry: class extends self.ISpriteInstance {},
	Confetti: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	VCArtboard10: class extends self.ISpriteInstance {},
	VCArtboard121_: class extends self.ISpriteInstance {},
	VCArtboard9: class extends self.ISpriteInstance {},
	VCArtboard: class extends self.ISpriteInstance {},
	VCArtboard5: class extends self.ISpriteInstance {},
	VCArtboard6: class extends self.ISpriteInstance {},
	coin: class extends self.ITextInstance {},
	levelText: class extends self.ITextInstance {},
	timeLeft: class extends self.ITextInstance {},
	levelSelect: class extends self.ISpriteInstance {},
	locked: class extends self.ISpriteInstance {},
	sort: class extends self.ISpriteInstance {},
	allAlphabets: class extends self.IArrayInstance {},
	forX: class extends self.IArrayInstance {},
	forY: class extends self.IArrayInstance {},
	spUID: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	GA4: class extends C3.Plugins.ppstudio_ga4.Instance {},
	WeeGooSDK: class extends C3.Plugins.WGSDK.Instance {},
	titleAsset: class extends self.ISpriteInstance {}
}