const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.right,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{placed: 0},
	{startingX: 0},
	{startingY: 0},
	{removeTip: 0},
	{DragDrop: 0},
	{Tween: 0},
	{Person: 0},
	{tipID: 0},
	{TextTips: 0},
	{correctPerson: 0},
	{taken: 0},
	{Spot: 0},
	{PersonNameFrame: 0},
	{PersonNameText: 0},
	{Line: 0},
	{lifeID: 0},
	{Life: 0},
	{Fader: 0},
	{TextFail: 0},
	{TextTutorial: 0},
	{Touch: 0},
	{LifeSpot: 0},
	{strikeID: 0},
	{Strikethrough: 0},
	{TextSuccess: 0},
	{TextFinalSuccess: 0},
	{BGGame: 0},
	{BGTutoSuccess: 0},
	{WeeGooSDK: 0},
	{lives: 0},
	{correctCount: 0}
];

self.InstanceType = {
	Person: class extends self.ISpriteInstance {},
	TextTips: class extends self.ITextInstance {},
	Spot: class extends self.ISpriteInstance {},
	PersonNameFrame: class extends self.ISpriteInstance {},
	PersonNameText: class extends self.ITextInstance {},
	Line: class extends self.ITiledBackgroundInstance {},
	Life: class extends self.ISpriteInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	TextFail: class extends self.ITextInstance {},
	TextTutorial: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	LifeSpot: class extends self.ISpriteInstance {},
	Strikethrough: class extends self.ITiledBackgroundInstance {},
	TextSuccess: class extends self.ITextInstance {},
	TextFinalSuccess: class extends self.ITextInstance {},
	BGGame: class extends self.ISpriteInstance {},
	BGTutoSuccess: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {}
}