(function () {
  "use strict";

  const A = "Assets/";
  window.ChicConfig = Object.freeze({
    WIDTH: 1280,
    HEIGHT: 720,
    SAVE_KEY: "chicCutsSaveV1",
    SAVE_VERSION: 1,
    INITIAL_HINTS: 2,
    MAX_TILE_SIZE: 110,
    BOARD: Object.freeze({ x: 263.2, y: 99.8, w: 607.8, h: 520.4 }),
    BOARD_INNER: Object.freeze({ x: 292.1, y: 140, w: 550, h: 440 }),
    BASKET_PANEL: Object.freeze({ x: 28.3, y: 124.9, w: 162.2, h: 400.2 }),
    UI: Object.freeze({
      titleStart: { x: 245.9, y: 413, w: 396.1, h: 131.8 },
      audio: { x: 1179.9, y: 16.2, w: 80.3, h: 80.7 },
      back: { x: 11.1, y: 16.2, w: 79.6, h: 81 },
      restart: { x: 1093.3, y: 16.2, w: 80.7, h: 81 },
      undo: { x: 897.9, y: 592.6, w: 108.4, h: 110.8 },
      hint: { x: 1024.9, y: 585.2, w: 108.7, h: 118.2 },
      levelPanel: { x: 308.6, y: 16.2, w: 178.9, h: 75.5 },
      movesPanel: { x: 526.9, y: 12.2, w: 178.9, h: 75.5 },
      pagePrev: { x: 513.1, y: 622, w: 70.9, h: 52.1 },
      pageNext: { x: 991.8, y: 621.5, w: 71.2, h: 52.4 },
      completeLevels: { x: 513.3, y: 465.1, w: 105.7, h: 105.2 },
      completeNext: { x: 621.3, y: 448.1, w: 120.4, h: 124.8 },
      completeRestart: { x: 743.8, y: 464.9, w: 106.8, h: 107 },
      overLevels: { x: 603.9, y: 404.7, w: 108.4, h: 107.9 },
      overRestart: { x: 715.3, y: 404.6, w: 109.5, h: 109.7 }
    }),
    IMAGES: Object.freeze({
      titleBg: A + "TittleScreenBackground.jpg",
      loadingBg: A + "LoadingScreenBackground.jpg",
      selectBg: A + "SelectLevelScreenBackground.jpg",
      gameplayBg: A + "GamePlayScreenBackground.jpg",
      black: A + "BlackScreen.png",
      start: A + "TittleScreen_StartButton.png",
      audio: A + "AudioButton.png",
      mute: A + "AudioMuteButton.png",
      back: A + "BackButton.png",
      restart: A + "RestartButton.png",
      undo: A + "UndoButton.png",
      hint: A + "HintButton.png",
      board: A + "GameBoard.png",
      basketPanel: A + "ClothBasketPanel.png",
      levelPanel: A + "GamePlayScreen_LevelTextPanel.png",
      movesPanel: A + "GamePlayScreen_MovesLeftTextPanel.png",
      loadTray: A + "LoadingScreen_ProgressBarTray.png",
      loadFill: A + "LoadingScreen_ProgressBarFillImage.png",
      levelComplete: A + "LevelCompletePanel.png",
      gameOver: A + "GameOverPanel.png",
      resultLevels: A + "ResultPanel_LevelsButton.png",
      resultNext: A + "ResultPanel_NextLevelButton.png",
      resultRestart: A + "ResultPanel_RestartButton.png",
      levelDone: A + "SelectLevelScreen_CompletedLevelButton.png",
      levelOpen: A + "SelectLevelScreen_UnlockedLevelButton.png",
      levelLocked: A + "SelectLevelScreen_LockedLevelButton.png",
      pagePrev: A + "SelectLevelScreen_DecreasePageNoButton.png",
      pageNext: A + "SelectLevelScreen_IncreasePageNoButton.png",
      cursor: A + "Cursor.png"
    }),
    FABRICS: Object.freeze(Array.from({ length: 8 }, (_, i) => A + `ClothPattern${i + 1}.png`)),
    BASKETS: Object.freeze(Array.from({ length: 8 }, (_, i) => A + `ClothPatternBasket${i + 1}.png`)),
    AUDIO: Object.freeze({
      music: A + "Audio/chic_cuts_main_theme.ogg",
      cut: A + "Audio/chic_cuts_scissor_snip.ogg",
      separate: A + "Audio/chic_cuts_fabric_separation.ogg",
      collect: A + "Audio/chic_cuts_fabric_collect.ogg",
      click: A + "Audio/chic_cuts_ui_button_press.ogg",
      undo: A + "Audio/chic_cuts_undo.ogg",
      hint: A + "Audio/chic_cuts_hint.ogg",
      invalid: A + "Audio/chic_cuts_invalid_cut.ogg",
      complete: A + "Audio/chic_cuts_level_complete.ogg",
      over: A + "Audio/chic_cuts_game_over.ogg",
      page: A + "Audio/chic_cuts_level_page_swipe.ogg",
      locked: A + "Audio/chic_cuts_locked_level.ogg"
    })
  });
})();
