const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.solid,
		C3.Plugins.Touch,
		C3.Behaviors.Platform,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Behaviors.jumpthru,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Plugins.Function,
		C3.Behaviors.Fade,
		C3.Plugins.Browser,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Physics.Acts.ApplyImpulseToward,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Browser.Acts.ExecJs,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Acts.SetTimescale
	];
};
self.C3_JsPropNameTable = [
	{Physics: 0},
	{ballinstance: 0},
	{Solid: 0},
	{line: 0},
	{Touch: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Platform: 0},
	{Sine: 0},
	{Goaler: 0},
	{Bullet: 0},
	{ball: 0},
	{fence: 0},
	{Sprite2: 0},
	{bgback: 0},
	{Sprite3: 0},
	{Jumpthru: 0},
	{Sprite6: 0},
	{btnPlay: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Audio: 0},
	{Sprite7: 0},
	{Sprite10: 0},
	{txtHighScore: 0},
	{txtMnScore: 0},
	{LocalStorage: 0},
	{btnHome: 0},
	{btnSound: 0},
	{ballshadow: 0},
	{Function: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Fade: 0},
	{ballscore: 0},
	{txtScore: 0},
	{line2: 0},
	{angosht: 0},
	{Browser: 0},
	{Sprite13: 0},
	{btnBack: 0},
	{ballshootarea: 0},
	{WeeGooSDK: 0},
	{touchAY: 0},
	{touchBY: 0},
	{Power: 0},
	{BallCatch: 0},
	{Score: 0},
	{minper: 0},
	{IsGoal: 0},
	{maxper: 0},
	{touchBX: 0},
	{touchAX: 0},
	{loseball: 0},
	{BallTouch: 0},
	{choosed: 0},
	{rndsound: 0},
	{ver: 0},
	{HighScore: 0}
];

self.InstanceType = {
	ballinstance: class extends self.ISpriteInstance {},
	line: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Goaler: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	fence: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	bgback: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	txtHighScore: class extends self.ISpriteFontInstance {},
	txtMnScore: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	btnHome: class extends self.ISpriteInstance {},
	btnSound: class extends self.ISpriteInstance {},
	ballshadow: class extends self.ISpriteInstance {},
	Function: class extends self.IInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	ballscore: class extends self.ISpriteInstance {},
	txtScore: class extends self.ISpriteFontInstance {},
	line2: class extends self.ISpriteInstance {},
	angosht: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	btnBack: class extends self.ISpriteInstance {},
	ballshootarea: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {}
}