const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Arr,
		C3.Plugins.Dictionary,
		C3.Behaviors.Pin,
		C3.Behaviors.Timer,
		C3.Plugins.Tilemap,
		C3.Behaviors.MoveTo,
		C3.Plugins.Audio,
		C3.Plugins.Particles,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Tilemap.Exps.Width,
		C3.Plugins.Tilemap.Exps.Height,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.time,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Tilemap.Exps.TileToPositionX,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Tilemap.Exps.TileToPositionY,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Tilemap.Exps.X,
		C3.Plugins.Tilemap.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Exps.MaxSpeed,
		C3.Behaviors.MoveTo.Acts.SetAcceleration,
		C3.Behaviors.MoveTo.Exps.Acceleration,
		C3.Behaviors.MoveTo.Acts.SetDeceleration,
		C3.Behaviors.MoveTo.Exps.Deceleration,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Behaviors.Sin.Exps.Period,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Tilemap.Cnds.CompareTileAt,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Dictionary.Cnds.ForEachKey,
		C3.Plugins.Dictionary.Exps.CurrentKey,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Dictionary.Acts.Clear,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Tilemap.Acts.SetTile,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Tilemap.Exps.BBoxBottom,
		C3.Plugins.Tilemap.Exps.PositionToTileX,
		C3.Plugins.Tilemap.Exps.PositionToTileY,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.System.Cnds.PickOverlappingPoint,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.WGSDK.Cnds.RewardGranted,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.WGSDK.Acts.InitReward
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{LocalStorage: 0},
	{Browser: 0},
	{AdvancedRandom: 0},
	{BaseText: 0},
	{txtBest: 0},
	{Sine: 0},
	{btnPlay: 0},
	{chef: 0},
	{icoBest: 0},
	{logo: 0},
	{txtBest2: 0},
	{Matches: 0},
	{Groups: 0},
	{mark: 0},
	{swiping: 0},
	{power: 0},
	{group: 0},
	{done: 0},
	{cross: 0},
	{lastSwipe: 0},
	{lastDir: 0},
	{falling: 0},
	{lastX: 0},
	{lastY: 0},
	{moved: 0},
	{neighbor: 0},
	{Pin: 0},
	{Block: 0},
	{Timer: 0},
	{SyncMove: 0},
	{Grid: 0},
	{MoveTo: 0},
	{Spawner: 0},
	{SyncSwap: 0},
	{SyncRef: 0},
	{barTop: 0},
	{txtMoves: 0},
	{txtScore: 0},
	{txtTimer: 0},
	{value: 0},
	{Power: 0},
	{txtCount: 0},
	{btnPause: 0},
	{btnExit: 0},
	{btnResume: 0},
	{BG: 0},
	{Hide: 0},
	{PauseWindow: 0},
	{txtLabel: 0},
	{Audio: 0},
	{Sprite: 0},
	{Asset13x: 0},
	{top: 0},
	{btnMenu: 0},
	{btnHow: 0},
	{gameOver: 0},
	{icons: 0},
	{btnRestart: 0},
	{Particles: 0},
	{watchads: 0},
	{watchadsbottle: 0},
	{WeeGooSDK: 0},
	{watchads2: 0},
	{UI: 0},
	{Move: 0},
	{BlockPick: 0},
	{x: 0},
	{y: 0},
	{Ex: 0},
	{Ey: 0},
	{BothValid: 0},
	{uid1: 0},
	{uid2: 0},
	{SrcX: 0},
	{SrcY: 0},
	{DstX: 0},
	{DstY: 0},
	{swipe: 0},
	{uid: 0},
	{count: 0},
	{valid: 0},
	{anim: 0},
	{type: 0},
	{ltop: 0},
	{lbot: 0},
	{ctop: 0},
	{cbot: 0},
	{g: 0},
	{rx: 0},
	{ry: 0},
	{anim1: 0},
	{anim2: 0},
	{anim3: 0},
	{found: 0},
	{dir: 0},
	{frame: 0},
	{tgtX: 0},
	{tgtY: 0},
	{xMin: 0},
	{yMin: 0},
	{val: 0},
	{s: 0},
	{m: 0},
	{win: 0},
	{x2: 0},
	{y2: 0},
	{HSteps: 0},
	{VSteps: 0},
	{yb: 0},
	{yt: 0},
	{xl: 0},
	{xr: 0},
	{run: 0},
	{full: 0},
	{xt: 0},
	{Moves: 0},
	{MovesBase: 0},
	{Score: 0},
	{BestScore: 0},
	{ScorePerMatch: 0},
	{KEYBestScore: 0},
	{TimerBase: 0},
	{Tx: 0},
	{Ty: 0},
	{TileSize: 0},
	{TileSize2: 0},
	{Update: 0},
	{Checking: 0},
	{MatchGroup: 0},
	{CNTNormal: 0},
	{UIPWRLine: 0},
	{UIPWRSwap: 0},
	{InitFreePowersMax: 0},
	{RandomCount: 0},
	{TMRNoMatch: 0},
	{TimerNoMatch: 0},
	{TMRUpdate: 0},
	{TimerUpdate: 0},
	{TileCountV: 0},
	{TileCountH: 0},
	{TILE_FULL: 0},
	{TILE_EMPTY: 0},
	{TILE_TARGET: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	AdvancedRandom: class extends self.IInstance {},
	txtBest: class extends self.ITextInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	chef: class extends self.ISpriteInstance {},
	icoBest: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	txtBest2: class extends self.ITextInstance {},
	Matches: class extends self.IArrayInstance {},
	Groups: class extends self.IDictionaryInstance {},
	Block: class extends self.ISpriteInstance {},
	SyncMove: class extends self.ISpriteInstance {},
	Grid: class extends self.ITilemapInstance {},
	Spawner: class extends self.ISpriteInstance {},
	SyncSwap: class extends self.ISpriteInstance {},
	SyncRef: class extends self.ISpriteInstance {},
	barTop: class extends self.ISpriteInstance {},
	txtMoves: class extends self.ITextInstance {},
	txtScore: class extends self.ITextInstance {},
	txtTimer: class extends self.ITextInstance {},
	Power: class extends self.ISpriteInstance {},
	txtCount: class extends self.ITextInstance {},
	btnPause: class extends self.ISpriteInstance {},
	btnExit: class extends self.ISpriteInstance {},
	btnResume: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	Hide: class extends self.ISpriteInstance {},
	PauseWindow: class extends self.ISpriteInstance {},
	txtLabel: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Asset13x: class extends self.ISpriteInstance {},
	top: class extends self.ISpriteInstance {},
	btnMenu: class extends self.ISpriteInstance {},
	btnHow: class extends self.ISpriteInstance {},
	gameOver: class extends self.ISpriteInstance {},
	icons: class extends self.ISpriteInstance {},
	btnRestart: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	watchads: class extends self.ISpriteInstance {},
	watchadsbottle: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {},
	watchads2: class extends self.ISpriteInstance {},
	UI: class extends self.ISpriteInstance {},
	Move: class extends self.ISpriteInstance {},
	BlockPick: class extends self.ISpriteInstance {}
}