const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.NinePatch,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Arr,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.StopLoop,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.NinePatch.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY
	];
};
self.C3_JsPropNameTable = [
	{Index: 0},
	{Container: 0},
	{Tween: 0},
	{Item: 0},
	{SineWidth: 0},
	{SineHeight: 0},
	{Cursor: 0},
	{Touch: 0},
	{Board: 0},
	{Picked: 0},
	{Text: 0},
	{Fade: 0},
	{Background: 0},
	{LargeBubbles: 0},
	{SmallBubbles: 0},
	{Sine: 0},
	{Lid: 0},
	{WeeGooSDK: 0},
	{AllowPlayerInput: 0},
	{ContainerLoopindex: 0},
	{ItemLoopindex: 0},
	{ItemTypesFound: 0},
	{Add: 0},
	{MAXITEMSPERCONTAINER: 0},
	{DISTANCEBETWEENEACHITEM: 0},
	{PickedItemType: 0},
	{PickedContainerUID: 0},
	{PickedContainerIndex: 0},
	{FreeSlots: 0},
	{ProceedWithTransferPart0: 0},
	{SkipPart1: 0},
	{ProceedWithTransferPart1: 0},
	{CurrentIndex: 0},
	{FirstEmptyIndex: 0},
	{TotalCleared: 0},
	{ContainerIndex: 0},
	{Info: 0},
	{REQUIREDITEMSOFSAMETYPEPERCONTAINER: 0},
	{TotalItemTypes: 0},
	{HowManyOfSameType: 0},
	{CorrectColumns: 0},
	{BottomItemType: 0},
	{CurrentItemType: 0},
	{LARGEBUBBLESSCROLLINGSPEED: 0},
	{SMALLBUBBLESSCROLLINGSPEED: 0},
	{BUBBLESSCROLLINGANGLE: 0}
];

self.InstanceType = {
	Container: class extends self.ISpriteInstance {},
	Item: class extends self.ISpriteInstance {},
	Cursor: class extends self.IWorldInstance {},
	Touch: class extends self.IInstance {},
	Board: class extends self.IArrayInstance {},
	Picked: class extends self.IArrayInstance {},
	Text: class extends self.ITextInstance {},
	Fade: class extends self.ITiledBackgroundInstance {},
	Background: class extends self.ISpriteInstance {},
	LargeBubbles: class extends self.ITiledBackgroundInstance {},
	SmallBubbles: class extends self.ITiledBackgroundInstance {},
	Lid: class extends self.ISpriteInstance {},
	WeeGooSDK: class extends self.IInstance {}
}