const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Camera3D,
		C3.Plugins.Keyboard,
		C3.Plugins.Shape3D,
		C3.Behaviors.Timer,
		C3.Plugins.Sprite,
		C3.Behaviors.TileMovement,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Plugins.WGSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Spritefont2.Cnds.CompareOpacity,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.TileMovement.Acts.SimulateControl,
		C3.Behaviors.TileMovement.Cnds.IsMovingDirection,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Shape3D.Acts.SetPos,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Shape3D.Exps.Count,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Shape3D.Exps.Width,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Shape3D.Cnds.OnCollision,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.Shape3D.Cnds.OnCreated,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Shape3D.Cnds.PickByUID,
		C3.Plugins.Shape3D.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Shape3D.Acts.AddChild,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Shape3D.Exps.UID,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Shape3D.Cnds.CompareInstanceVar,
		C3.Plugins.Shape3D.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Shape3D.Acts.SetEffectParam,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.PlatformInfo.Exps.CanvasCssWidth,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.PlatformInfo.Exps.CanvasCssHeight,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.Shape3D.Cnds.IsOnScreen,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Camera3D.Exps.LayerToCanvasX,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Plugins.Camera3D.Exps.LayerToCanvasY,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.Camera3D.Exps.CameraX,
		C3.Plugins.Camera3D.Exps.CameraY,
		C3.Plugins.Shape3D.Acts.SetY,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX
	];
};
self.C3_JsPropNameTable = [
	{"3DCamera": 0},
	{Keyboard: 0},
	{Timer: 0},
	{Guy: 0},
	{TileMovement: 0},
	{Player: 0},
	{BoxSpawn: 0},
	{Scenario: 0},
	{Solid: 0},
	{ArenaLimit: 0},
	{TexGuy: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{hp: 0},
	{points: 0},
	{type: 0},
	{BoxCommon: 0},
	{BoxGuy: 0},
	{BoxWeapon: 0},
	{GameTimer: 0},
	{PlatformInfo: 0},
	{associatedUID: 0},
	{Tween: 0},
	{TextPoints: 0},
	{Ground: 0},
	{TexBuildingsRightNear: 0},
	{TexBuildingsLeftNear: 0},
	{GuyDead: 0},
	{TexGuyDead: 0},
	{TextTutorial: 0},
	{TextUpgrade: 0},
	{TextScore: 0},
	{TextGameOver: 0},
	{Fader: 0},
	{BulletDestroyer: 0},
	{TexBuildingsLeftFar: 0},
	{TexBuildingsRightFar: 0},
	{TexSandSmoke: 0},
	{SandSmoke: 0},
	{WeeGooSDK: 0},
	{Boxes: 0},
	{score: 0},
	{atkdelay: 0},
	{currentSpeed: 0},
	{gameStarted: 0},
	{gameOver: 0},
	{boxType: 0},
	{UID: 0},
	{canvasXRatio: 0},
	{canvasYRatio: 0}
];

self.InstanceType = {
	_3DCamera: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Guy: class extends self.I3DShapeInstance {},
	Player: class extends self.ISpriteInstance {},
	BoxSpawn: class extends self.ISpriteInstance {},
	Scenario: class extends self.I3DShapeInstance {},
	ArenaLimit: class extends self.ISpriteInstance {},
	TexGuy: class extends self.ISpriteInstance {},
	Bullet: class extends self.I3DShapeInstance {},
	BoxCommon: class extends self.I3DShapeInstance {},
	BoxGuy: class extends self.I3DShapeInstance {},
	BoxWeapon: class extends self.I3DShapeInstance {},
	GameTimer: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	TextPoints: class extends self.ISpriteFontInstance {},
	Ground: class extends self.ITiledBackgroundInstance {},
	TexBuildingsRightNear: class extends self.ITiledBackgroundInstance {},
	TexBuildingsLeftNear: class extends self.ITiledBackgroundInstance {},
	GuyDead: class extends self.I3DShapeInstance {},
	TexGuyDead: class extends self.ISpriteInstance {},
	TextTutorial: class extends self.ISpriteFontInstance {},
	TextUpgrade: class extends self.ISpriteFontInstance {},
	TextScore: class extends self.ISpriteFontInstance {},
	TextGameOver: class extends self.ISpriteFontInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	BulletDestroyer: class extends self.ISpriteInstance {},
	TexBuildingsLeftFar: class extends self.ITiledBackgroundInstance {},
	TexBuildingsRightFar: class extends self.ITiledBackgroundInstance {},
	TexSandSmoke: class extends self.ISpriteInstance {},
	SandSmoke: class extends self.I3DShapeInstance {},
	WeeGooSDK: class extends self.IInstance {},
	Boxes: class extends self.I3DShapeInstance {}
}