const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Behaviors.Rotate,
		C3.Plugins.Browser,
		C3.Plugins.WGSDK,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.WGSDK.Acts.InitReward,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.WGSDK.Cnds.RewardReady,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.WGSDK.Acts.ShowReward,
		C3.Plugins.WGSDK.Cnds.RewardGranted,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.WGSDK.Acts.GameEvent,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.WGSDK.Cnds.WgsdkLoaded,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.LocalStorage.Cnds.OnAllGetsComplete,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.GoToLayoutByName
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Matched: 0},
	{Rank: 0},
	{Physics: 0},
	{Platform: 0},
	{Blocks: 0},
	{zidovi: 0},
	{Solid: 0},
	{Bar: 0},
	{Touch: 0},
	{Mask: 0},
	{Total: 0},
	{Moves: 0},
	{Bar2: 0},
	{Sprite4: 0},
	{Moves2: 0},
	{Sprite5: 0},
	{M01: 0},
	{M2: 0},
	{M3: 0},
	{UI1: 0},
	{UI2: 0},
	{win: 0},
	{GameOver: 0},
	{Pin: 0},
	{podloga: 0},
	{podloga2: 0},
	{home: 0},
	{again: 0},
	{Sine: 0},
	{next: 0},
	{levelup: 0},
	{smiley: 0},
	{failed: 0},
	{sadsmiley: 0},
	{ponovo: 0},
	{BSound: 0},
	{konfeti123: 0},
	{Sprite3: 0},
	{start: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{podlogazalevele: 0},
	{select: 0},
	{Open: 0},
	{Level: 0},
	{LevelsBlock: 0},
	{SpriteFont123: 0},
	{home2: 0},
	{Sprite6: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{LevelsText: 0},
	{Audio: 0},
	{Rotate: 0},
	{Sprite2: 0},
	{addmoves: 0},
	{Sprite13: 0},
	{zidovi2: 0},
	{ponovo2: 0},
	{zidovi3: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{konfeti124: 0},
	{konfeti125: 0},
	{playagain: 0},
	{home3: 0},
	{sarena: 0},
	{bobicasta: 0},
	{sekeric: 0},
	{Sprite16: 0},
	{more: 0},
	{gamesgames: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Browser: 0},
	{WeeGooSDK: 0},
	{videoigrice: 0},
	{kocka: 0},
	{btn: 0},
	{rafaeltrigo: 0},
	{Times: 0},
	{ToggleMoves: 0},
	{M1: 0},
	{M1Frame: 0},
	{M2Frame: 0},
	{M3Frame: 0},
	{LAST_LEVEL: 0},
	{WIN: 0},
	{LevelComplete: 0},
	{sound: 0},
	{SoundEf: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Blocks: class extends self.ISpriteInstance {},
	zidovi: class extends self.ISpriteInstance {},
	Bar: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mask: class extends self.ISpriteInstance {},
	Total: class extends self.ITextInstance {},
	Moves: class extends self.ITextInstance {},
	Bar2: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Moves2: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	M01: class extends self.ITextInstance {},
	M2: class extends self.ITextInstance {},
	M3: class extends self.ITextInstance {},
	UI1: class extends self.ISpriteInstance {},
	UI2: class extends self.ISpriteInstance {},
	win: class extends self.ITextInstance {},
	GameOver: class extends self.ITextInstance {},
	podloga: class extends self.ISpriteInstance {},
	podloga2: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	again: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	levelup: class extends self.ISpriteInstance {},
	smiley: class extends self.ISpriteInstance {},
	failed: class extends self.ISpriteInstance {},
	sadsmiley: class extends self.ISpriteInstance {},
	ponovo: class extends self.ISpriteInstance {},
	BSound: class extends self.ISpriteInstance {},
	konfeti123: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	start: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	podlogazalevele: class extends self.ISpriteInstance {},
	select: class extends self.ISpriteInstance {},
	LevelsBlock: class extends self.ISpriteInstance {},
	SpriteFont123: class extends self.ISpriteFontInstance {},
	home2: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	LevelsText: class extends self.ISpriteFontInstance {},
	Audio: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	addmoves: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	zidovi2: class extends self.ISpriteInstance {},
	ponovo2: class extends self.ISpriteInstance {},
	zidovi3: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	konfeti124: class extends self.ISpriteInstance {},
	konfeti125: class extends self.ISpriteInstance {},
	playagain: class extends self.ISpriteInstance {},
	home3: class extends self.ISpriteInstance {},
	sarena: class extends self.ISpriteInstance {},
	bobicasta: class extends self.ISpriteInstance {},
	sekeric: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	more: class extends self.ISpriteInstance {},
	gamesgames: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	WeeGooSDK: class extends self.IInstance {},
	videoigrice: class extends self.ISpriteInstance {},
	kocka: class extends self.ISpriteInstance {},
	btn: class extends self.ISpriteInstance {}
}