const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.piranha305_trajectory,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Behaviors.solid,
		C3.Plugins.Arr,
		C3.Behaviors.LOS,
		C3.Plugins.Button,
		C3.Behaviors.NoSave,
		C3.Behaviors.skymen_RadialProgress,
		C3.Plugins.sliderbar,
		C3.Behaviors.Anchor,
		C3.Plugins.NinePatch,
		C3.Plugins.Dictionary,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.TiledBg.Acts.SetImageScaleX,
		C3.Plugins.TiledBg.Acts.SetImageScaleY,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Arr.Acts.SplitString,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.Arr.Exps.Front,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Behaviors.LOS.Acts.CastRay,
		C3.Behaviors.LOS.Cnds.RayIntersected,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Behaviors.LOS.Exps.HitX,
		C3.Behaviors.LOS.Exps.HitY,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Text.Cnds.PickInstVarHiLow,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Text.Exps.Count,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Behaviors.piranha305_trajectory.Acts.SetTrajectoryByVelocity,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Text.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsRewardedPlaying,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsFullscreenClose,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsClose,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedClose,
		C3.Plugins.Eponesh_GameScore.Cnds.OnMuteSFX,
		C3.Plugins.Eponesh_GameScore.Cnds.OnMuteMusic,
		C3.Plugins.Eponesh_GameScore.Cnds.OnMute,
		C3.Plugins.Eponesh_GameScore.Cnds.OnUnmuteSFX,
		C3.Plugins.Eponesh_GameScore.Cnds.OnUnmuteMusic,
		C3.Plugins.Eponesh_GameScore.Cnds.OnUnmute,
		C3.Plugins.Eponesh_GameScore.Cnds.IsMuted,
		C3.Plugins.Eponesh_GameScore.Cnds.IsMusicMuted,
		C3.Plugins.Eponesh_GameScore.Cnds.IsSFXMuted,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Exps.roundtodp,
		C3.Behaviors.skymen_RadialProgress.Acts.SetValue,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerWaitForReady,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowPreloader,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowSticky,
		C3.Plugins.Dictionary.Cnds.IsEmpty,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Eponesh_GameScore.Cnds.PlatformType,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.Eponesh_GameScore.Cnds.DeviceType,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.Plugins.sliderbar.Cnds.CompareInstanceVar,
		C3.Plugins.sliderbar.Acts.SetValue,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStart,
		C3.Plugins.sliderbar.Cnds.OnChanging,
		C3.Plugins.sliderbar.Cnds.CompareValue,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsInvite,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsShare
	];
};
self.C3_JsPropNameTable = [
	{xCoord: 0},
	{yCoord: 0},
	{Num: 0},
	{ID: 0},
	{LVL: 0},
	{Tween: 0},
	{Trajectory: 0},
	{NumberSlot: 0},
	{Mouse: 0},
	{Plat: 0},
	{ButtonRestart: 0},
	{Text: 0},
	{Touch: 0},
	{Sine: 0},
	{Karand: 0},
	{Bg11: 0},
	{Browser: 0},
	{Diff: 0},
	{LocalStorage: 0},
	{Tema: 0},
	{Audio: 0},
	{Vis: 0},
	{Xcoor: 0},
	{Ycoor: 0},
	{Swap: 0},
	{Solid: 0},
	{ArrayNum: 0},
	{LineOfSight: 0},
	{LineRay: 0},
	{HowPlay: 0},
	{Win: 0},
	{Tut: 0},
	{Button: 0},
	{ArrayColor: 0},
	{Variable1: 0},
	{Number: 0},
	{Array: 0},
	{LineTrig: 0},
	{ArrayStr: 0},
	{ButtonPom: 0},
	{ButtonPomNum: 0},
	{TextPom: 0},
	{NoSave: 0},
	{TextUndo: 0},
	{TextPointUrov: 0},
	{TextCoin: 0},
	{TextPointMain: 0},
	{Coin: 0},
	{TextPlus: 0},
	{TextPlusMinus: 0},
	{CoinS: 0},
	{ButtonPomSmall: 0},
	{TextMag: 0},
	{ButttMag: 0},
	{TextMagCoin: 0},
	{ButRew: 0},
	{MagCent: 0},
	{CoinSMag: 0},
	{CloseMag: 0},
	{PlatCent: 0},
	{Bg5: 0},
	{Bg4: 0},
	{Bg3: 0},
	{Bg2: 0},
	{Bg1: 0},
	{Bg: 0},
	{RadialProgress: 0},
	{RadialQ2: 0},
	{Load: 0},
	{WinSetSpr3: 0},
	{WinSetSpr2: 0},
	{WinSetSpr: 0},
	{Якорь: 0},
	{Volume: 0},
	{Tuzz: 0},
	{Tut2: 0},
	{TextWin: 0},
	{TextLVL: 0},
	{L: 0},
	{TextFrame: 0},
	{TextFram: 0},
	{TextFinish: 0},
	{TextDiam: 0},
	{TextCoinn: 0},
	{TextCoin2: 0},
	{TextBigFramee: 0},
	{TextBigFrameCollision: 0},
	{TextBigFrame: 0},
	{Free: 0},
	{NN: 0},
	{TextBigFram: 0},
	{Star: 0},
	{Синусоид: 0},
	{Sprite5: 0},
	{SettingsUp: 0},
	{ScoreDiam: 0},
	{RightPodlozhka2: 0},
	{RightPodlozhka: 0},
	{RadialQ3: 0},
	{MainSceneText: 0},
	{LVLNumBest: 0},
	{LVLNum: 0},
	{Load2: 0},
	{Hend: 0},
	{FonPravila: 0},
	{Твинанимация: 0},
	{Fon: 0},
	{Diam: 0},
	{ClearStor: 0},
	{ButtonText: 0},
	{ButtonSprite: 0},
	{ButtonSave: 0},
	{ButSel: 0},
	{Sprite: 0},
	{Numbermenu: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{SettingsDict: 0},
	{TextPom2: 0},
	{AJAX: 0},
	{JSON: 0},
	{GamePush: 0},
	{Loc: 0},
	{Tile: 0},
	{Frame1: 0},
	{Sound: 0},
	{Music: 0},
	{WinPointMain: 0},
	{Finder: 0},
	{Undo: 0},
	{Body: 0},
	{UndoSchet: 0},
	{PlusRyad: 0},
	{WinPointUrov: 0},
	{SlotXCoor: 0},
	{SlotYCoor: 0},
	{NumPr: 0},
	{NumPr2: 0},
	{IDKar: 0},
	{IDKar2: 0},
	{WinLoose: 0},
	{Language: 0},
	{Domen: 0},
	{Lang: 0},
	{Xstart: 0},
	{Ystart: 0},
	{SpriteSize: 0},
	{Start: 0},
	{Start1: 0},
	{SwapStart: 0},
	{GDVK: 0},
	{y: 0},
	{x: 0},
	{ycoord: 0},
	{num: 0},
	{Li1: 0},
	{Li2: 0},
	{IDNS: 0},
	{IDNS2: 0},
	{IDNS3: 0},
	{LVLRand: 0},
	{Li3: 0},
	{StartLVL: 0},
	{L2: 0},
	{Li5: 0},
	{ID3: 0},
	{L1: 0},
	{L3: 0},
	{IDSwap1: 0},
	{IDSwap2: 0},
	{NumSwap1: 0},
	{NumSwap2: 0},
	{XSwap1: 0},
	{XSwap2: 0},
	{YSwap1: 0},
	{YSwap2: 0},
	{Xs1: 0},
	{Xs2: 0},
	{Ys1: 0},
	{Ys2: 0},
	{IDProv: 0},
	{IDProv2: 0},
	{IDProv3: 0},
	{NumProv: 0},
	{NumProv2: 0},
	{Lii: 0},
	{Y1: 0},
	{Y2: 0},
	{S1: 0},
	{S2: 0},
	{Y: 0},
	{ID2: 0},
	{Li: 0},
	{Rev: 0},
	{Count2: 0},
	{NumCount: 0},
	{SlotCount: 0},
	{Yy: 0},
	{Xx: 0},
	{Sch: 0},
	{Ll: 0},
	{Count: 0},
	{IDMaxN: 0},
	{IDMax: 0},
	{x2: 0},
	{y2: 0},
	{XM: 0},
	{XU: 0},
	{XC: 0},
	{YM: 0},
	{YU: 0},
	{YC: 0},
	{Liiii: 0},
	{Liiii2: 0},
	{Col2: 0},
	{Col3: 0},
	{Mag: 0},
	{N: 0}
];

self.InstanceType = {
	NumberSlot: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	ButtonRestart: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Karand: class extends self.ISpriteInstance {},
	Bg11: class extends self.ITiledBackgroundInstance {},
	Browser: class extends self.IInstance {},
	Diff: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Tema: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Num: class extends self.ITextInstance {},
	ArrayNum: class extends self.IArrayInstance {},
	LineRay: class extends self.ISpriteInstance {},
	HowPlay: class extends self.ISpriteInstance {},
	Win: class extends self.ISpriteInstance {},
	Tut: class extends self.ITextInstance {},
	Button: class extends self.IButtonInstance {},
	ArrayColor: class extends self.IArrayInstance {},
	Number: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	LineTrig: class extends self.ISpriteInstance {},
	ArrayStr: class extends self.IArrayInstance {},
	ButtonPom: class extends self.ISpriteInstance {},
	ButtonPomNum: class extends self.ISpriteInstance {},
	TextPom: class extends self.ITextInstance {},
	TextUndo: class extends self.ITextInstance {},
	TextPointUrov: class extends self.ITextInstance {},
	TextCoin: class extends self.ITextInstance {},
	TextPointMain: class extends self.ITextInstance {},
	Coin: class extends self.ISpriteInstance {},
	TextPlus: class extends self.ITextInstance {},
	TextPlusMinus: class extends self.ITextInstance {},
	CoinS: class extends self.ISpriteInstance {},
	ButtonPomSmall: class extends self.ISpriteInstance {},
	TextMag: class extends self.ITextInstance {},
	ButttMag: class extends self.ISpriteInstance {},
	TextMagCoin: class extends self.ITextInstance {},
	ButRew: class extends self.ISpriteInstance {},
	MagCent: class extends self.ISpriteInstance {},
	CoinSMag: class extends self.ISpriteInstance {},
	CloseMag: class extends self.ISpriteInstance {},
	PlatCent: class extends self.ISpriteInstance {},
	Bg5: class extends self.ITiledBackgroundInstance {},
	Bg4: class extends self.ITiledBackgroundInstance {},
	Bg3: class extends self.ITiledBackgroundInstance {},
	Bg2: class extends self.ITiledBackgroundInstance {},
	Bg1: class extends self.ITiledBackgroundInstance {},
	Bg: class extends self.ITiledBackgroundInstance {},
	RadialQ2: class extends self.ISpriteInstance {},
	Load: class extends self.ISpriteInstance {},
	WinSetSpr3: class extends self.ISpriteInstance {},
	WinSetSpr2: class extends self.ISpriteInstance {},
	WinSetSpr: class extends self.ISpriteInstance {},
	Volume: class extends self.ISliderBarInstance {},
	Tuzz: class extends self.ITextInstance {},
	Tut2: class extends self.ITextInstance {},
	TextWin: class extends self.ITextInstance {},
	TextLVL: class extends self.ITextInstance {},
	TextFrame: class extends self.ISpriteInstance {},
	TextFram: class extends self.ITextInstance {},
	TextFinish: class extends self.ITextInstance {},
	TextDiam: class extends self.IWorldInstance {},
	TextCoinn: class extends self.ITextInstance {},
	TextCoin2: class extends self.IWorldInstance {},
	TextBigFramee: class extends self.ITextInstance {},
	TextBigFrameCollision: class extends self.ISpriteInstance {},
	TextBigFrame: class extends self.IWorldInstance {},
	TextBigFram: class extends self.ISpriteInstance {},
	Star: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	SettingsUp: class extends self.ISpriteInstance {},
	ScoreDiam: class extends self.ISpriteInstance {},
	RightPodlozhka2: class extends self.ISpriteInstance {},
	RightPodlozhka: class extends self.ISpriteInstance {},
	RadialQ3: class extends self.ISpriteInstance {},
	MainSceneText: class extends self.ITextInstance {},
	LVLNumBest: class extends self.ITextInstance {},
	LVLNum: class extends self.ITextInstance {},
	Load2: class extends self.ISpriteInstance {},
	Hend: class extends self.ISpriteInstance {},
	FonPravila: class extends self.ISpriteInstance {},
	Fon: class extends self.ISpriteInstance {},
	Diam: class extends self.ISpriteInstance {},
	ClearStor: class extends self.ISpriteInstance {},
	ButtonText: class extends self.ITextInstance {},
	ButtonSprite: class extends self.ISpriteInstance {},
	ButtonSave: class extends self.ISpriteInstance {},
	ButSel: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Numbermenu: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	SettingsDict: class extends self.IDictionaryInstance {},
	TextPom2: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	GamePush: class extends self.C3.Plugins.Eponesh_GameScore.Instance {}
}